Function preamble generation stabilized.
Such generation now proceeds fairly apace. While malignant bugs malinger, the
boot-heel of infectious open-source justice also malingers.

diff --git a/src/00-start/00-declare/60-func/die b/src/00-start/00-declare/60-func/die
--- a/src/00-start/00-declare/60-func/die
+++ b/src/00-start/00-declare/60-func/die
@@ -5,15 +5,12 @@
 
 :parcel <<'/---'
 Handle *function declarer exception handlers* (i.e., functions throwing
-exceptions resulting from validation errors in declared functions).
+exceptions resulting from function declarers).
 /---
 
-# Due to a chicken-and-the-egg problem, all functions and globals defined below
-# are subsequently documented under @{help} in the main codebase.
-
-# ....................{ EXCEPTIONS ~ cause                 }....................
+# ....................{ EXCEPTIONS                         }....................
 :func.document <<'/---'
-:void ::func_.die_of_cause(:string exception_message)
+:void ::func.die(:string exception_message)
 
 Throw an exception with the passed message, presumably detailing a syntactic or
 semantic error in the currently declared function prototype. This private
@@ -27,63 +24,100 @@ For convenience, such message is expected to be a lowercase sentence fragment:
   function name such prototype declares. (For simplicity, any subsequent
   function name such prototype declares is currently ignored.)
 * Suffixed by such prototype.
+
+== Message Format ==
+
+The passed message should be formatted as a lowercase sentence fragment (e.g.,
+`prototype invalid`), which this function then:
+
+* Prefixes by `Parcel ={parcel_name} function ${func_name}() `, where:
+** `${parcel_name}` is the name of the parcel containing such alias.
+** `${func_name}` is the first function name such prototype declares. (For
+   simplicity, any subsequent function name such prototype declares is ignored.)
+* Suffixes by such prototype.
 /---
-function ::func_.die_of_cause() {
+function ::func.die() {
+    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+    # Synchronize with ::alias.die().
+    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+
     # Validate sanity.
     (( # == 1 )) || :die 'Expected one exception message.'
-    local error_prefix
-    
-    # If such function was declared in a parcel, prefix such exception message
-    # by such parsel.
-    error_prefix=$(::parcel.get_current)
-    if [[ -n ${error_prefix} ]] {
-        error_prefix+='function '
-    } else {
-        error_prefix+='Function '
-    }
+    local exception_message=${1} exception_prefix exception_suffix
 
+    # String prefixing such exception message.
+    exception_prefix=$(::parcel.get_current)'function '
+    
     # If such prototype has been parsed, at least one function name has been
     # matched from such prototype. In such case, prepend such exception by the
     # first such name.
     if [[ -n ${ZESHY__FUNC_NAMES[1]-} ]] {
-        error_prefix+=${ZESHY__FUNC_NAMES[1]-}'() '
+        exception_prefix+=${ZESHY__FUNC_NAMES[1]-}'() '
+    }
+
+    # If such prototype has been declared, suffix such exception by such
+    # prototype. For readability, indent each line of such prototype.
+    if [[ -n ${ZESHY__FUNC_PROTOTYPE-} ]] {
+        local func_prototype=${ZESHY__FUNC_PROTOTYPE}
+        ::string.indent func_prototype
+        exception_suffix=$'\n\n''Function prototype:'$'\n'${func_prototype}
     }
 
     # Throw such exception.
-    :die ${error_prefix}${1}$':\n\n'${ZESHY__FUNC_PROTOTYPE}
+    :die ${exception_prefix}${exception_message}${exception_suffix}
 }
 
-# ....................{ EXCEPTIONS ~ cause : type          }....................
+# ....................{ EXCEPTIONS ~ arg                   }....................
 :func.document <<'/---'
-:void ::func_.die_of_cause_arg_type(:string exception_message)
+:void ::func.die_of_arg(:string exception_message)
+
+Throw an exception with the passed message, presumably detailing a syntactic or
+semantic error in the currently parsed argument in the currently declared
+function prototype. This private exception handler is intended to be called
+_only_ by ::func_.stop().
+/---
+function ::func.die_of_arg() {
+    # Validate sanity.
+    (( # == 1 )) || :die 'Expected one exception message.'
+    local arg_name
+
+    # Such argument's current name.
+    ::func.set_arg_current_name arg_name
+
+    # Throw such exception.
+    ::func.die 'argument ${'${arg_name}'} '${1}
+}
+
+# ....................{ EXCEPTIONS ~ arg : type            }....................
+:func.document <<'/---'
+:void ::func.die_of_arg_type(:string exception_message)
 
 Throw an exception with the passed message, presumably detailing a syntactic or
 semantic error in the currently parsed argument type in the currently declared
 function prototype. This private exception handler is intended to be called
 _only_ by ::func_.stop().
 /---
-function ::func_.die_of_cause_arg_type() {
+function ::func.die_of_arg_type() {
     # Validate sanity.
     (( # == 1 )) || :die 'Expected one exception message.'
-    local arg_name arg_type
+    local arg_type
 
-    # Such argument's current name and type.
-    ::func.set_arg_current_name arg_name
+    # Such argument's current type.
     ::func.set_arg_current_type arg_type
 
     # Throw such exception.
-    ::func_.die_of_cause 'argument ${'${arg_name}'} type '${arg_type}' '${1}
+    ::func.die_of_arg 'type '${arg_type}' '${1}
 }
 
 :func.document <<'/---'
-:void ::func_.die_of_cause_arg_type_direct(:string exception_message)
+:void ::func.die_of_arg_type_direct(:string exception_message)
 
 Throw an exception with the passed message, presumably detailing a semantic error in the currently parsed argument type in the currently declared
 function prototype correctable by revising such argument to refer to a variable
 by name. This private exception handler is intended to be called _only_ by
 ::func_.stop().
 /---
-function ::func_.die_of_cause_arg_type_direct() {
+function ::func.die_of_arg_type_direct() {
     # Validate sanity.
     (( # == 1 )) || :die 'Expected one exception message.'
     local arg_type_source arg_type_target
@@ -117,20 +151,20 @@ function ::func_.die_of_cause_arg_type_direct() {
     }
 
     # Throw an exception reflecting such argument's current type.
-    ::func_.die_of_cause_arg_type\
-        ${1}'; consider refactoring such argument into a string referring to a variable via type indirection (e.g., from "'${arg_type_source}'" to "'${arg_type_target}'")'
+    ::func.die_of_arg_type\
+        ${1}' Consider refactoring such argument into a string referring to a variable via type indirection (e.g., from "'${arg_type_source}'" to "'${arg_type_target}'").'
 }
 
-# ....................{ EXCEPTIONS ~ cause : variadic      }....................
+# ....................{ EXCEPTIONS ~ arg : variadic        }....................
 :func.document <<'/---'
-:void ::func_.die_of_cause_arg_variadic(:string exception_message)
+:void ::func.die_of_arg_variadic(:string exception_message)
 
 Throw an exception with the passed message, presumably detailing a semantic
 error in the variadicity of the currently parsed argument in the currently
 declared function prototype. This private exception handler is intended to be
 called _only_ by ::func_.stop().
 /---
-function ::func_.die_of_cause_arg_variadic() {
+function ::func.die_of_arg_variadic() {
     # Validate sanity.
     (( # == 1 )) || :die 'Expected one exception message.'
     local arg_name_source arg_name_target arg_type_source arg_type_target
@@ -144,75 +178,17 @@ function ::func_.die_of_cause_arg_variadic() {
     arg_name_target=${arg_name_source}
 
     # If such argument is mandatory, constrain such list to be non-empty.
-    if (( ! arg_is_optional )) {
-        arg_type_target+='+nonempty'
-    }
+    (( arg_is_optional )) || arg_type_target+='+nonempty'
 
     # Throw an exception reflecting such argument's current type and name.
-    ::func_.die_of_cause\
-        ${1}'; consider converting the variadic argument list beginning with argument ${'${arg_name_source}'} into a string indirectly referring to a list (e.g., from "'${arg_type_source}' '${arg_name_source}', ..." to "'${arg_type_target}' '${arg_name_target}'"'
+    ::func.die\
+        ${1}' Consider converting variadic argument ${'${arg_name_source}'} into a non-variadic string indirectly referring to a list (e.g., from "'${arg_type_source}'... '${arg_name_source}'" to "'${arg_type_target}' '${arg_name_target}'").'
 }
 
-# ....................{ EXCEPTIONS ~ arg count             }....................
-:func.document <<'/---'
-:void ::func.die_of_arg_count_not_equaling(
-    :string func_arg1?, ...,
-    :int+nonnegative func_arg_count_expected)
-
-Throw an exception due to the passed argument list (presumably, the same list
-passed to the calling function) _not_ containing the passed number of arguments
-(presumably, required by such function's prototype). This private exception
-handler is intended to be programmatically prefixed to function bodies _only_
-by ::func_.stop().
-/---
-function ::func.die_of_arg_count_not_equaling() {
-    (( # )) || :die\
-        'Expected one or more arguments and one expected argument count.'
-    ::func.die_of_arg_count "${@[1,-2]}"\
-        "${@[-1]} arguments but received ${#@[1,-2]}"
-}
-
-:func.document <<'/---'
-:void ::func.die_of_arg_count_not_exceeding(
-    :string func_arg1?, ...,
-    :int+nonnegative func_arg_count_min)
-
-Throw an exception due to the passed argument list (presumably, the same list
-passed to the calling function) _not_ containing at least the passed number of
-arguments (presumably, required by such function's prototype). This private
-exception handler is intended to be programmatically prefixed to function
-bodies _only_ by ::func_.stop().
-/---
-function ::func.die_of_arg_count_not_exceeding() {
-    (( # )) || :die\
-        'Expected one or more arguments, one actual argument count, and one minimum argument count.'
-    ::func.die_of_arg_count "${@[1,-3]}"\
-        "at least ${@[-1]} arguments but received only ${#@[1,-2]}"
-}
-
-:func.document <<'/---'
-:void ::func.die_of_arg_count_not_ranging(
-    :string func_arg1?, ...,
-    :int+nonnegative func_arg_count_min,
-    :int+nonnegative func_arg_count_max,)
-
-Throw an exception due to the passed argument list (presumably, the same list
-passed to the calling function) containing fewer than the passed minimum number
-of arguments or more than the passed maximum number of arguments (presumably,
-required by such function's prototype). This private exception handler is
-intended to be programmatically prefixed to function bodies _only_ by
-::func_.stop().
-/---
-function ::func.die_of_arg_count_not_ranging() {
-    (( # >= 2 )) || :die\
-        'Expected one or more arguments, one minimum argument count, and one maximum argument count.'
-    ::func.die_of_arg_count "${@[1,-3]}"\
-        "between ${@[-2]} and ${@[-1]} arguments but received ${#@[1,-3]}"
-}
-
+# ....................{ EXCEPTIONS ~ arg : count           }....................
 :func.document <<'/---'
 :void ::func.die_of_arg_count(
-    :string func_arg1?, ...,
+    :string... func_args?,
     :string exception_message)
 
 Throw an exception due to the passed argument list (presumably, the same list
@@ -229,7 +205,6 @@ function ::func.die_of_arg_count() {
         exception_message="${@[-1]}"\
         func_name\
         func_prototype\
-        func_arg\
         func_args
     integer func_arg_index=1
     (( ${#funcstack} >= 3 )) || :die 'Called directly from the command line.'
@@ -239,22 +214,82 @@ function ::func.die_of_arg_count() {
 
     # Such function's prototype, indented for readability.
     :func.set_prototype "${func_name}" func_prototype
-    func_prototype='    '${func_prototype//$'\n'/$'\n'    }
+    ::string.indent func_prototype
 
     # Such function's arguments, reformatted for readability.
-    for func_arg (${@[1,-2]}) {
+    local func_arg
+    for   func_arg (${@[1,-2]}) {
         func_args+='['${func_arg_index}'] '${func_arg}$'\n'
         func_arg_index+=1
     }
 
+    #FIXME: For readability, prefix such message by the name of the parcel
+    #containing such function.
+
     # Throw such exception message, appropriately prefixed and suffixed.
-    :die 'Function '${func_name}'() expected '${exception_message}'.'$'\n\n''Function prototype:'$'\n'${func_prototype}$'\n\n''Arguments passed:'$'\n'${func_args}' '
+    :die 'Function '${func_name}'() expected '${exception_message}$'\n\n''Function prototype:'$'\n'${func_prototype}$'\n\n''Arguments passed:'$'\n'${func_args}' '
+}
+
+:func.document <<'/---'
+:void ::func.die_of_arg_count_not_equaling(
+    :string... func_args?,
+    :int+nonnegative func_arg_count_expected)
+
+Throw an exception due to the passed argument list (presumably, the same list
+passed to the calling function) _not_ containing the passed number of arguments
+(presumably, required by such function's prototype). This private exception
+handler is intended to be programmatically prefixed to function bodies _only_
+by ::func_.stop().
+/---
+function ::func.die_of_arg_count_not_equaling() {
+    (( # )) || :die\
+        'Expected one or more arguments and one expected argument count.'
+    ::func.die_of_arg_count "${@[1,-2]}"\
+        "${@[-1]} arguments but received ${#@[1,-2]}."
+}
+
+:func.document <<'/---'
+:void ::func.die_of_arg_count_not_exceeding(
+    :string... func_args?,
+    :int+nonnegative func_arg_count_min)
+
+Throw an exception due to the passed argument list (presumably, the same list
+passed to the calling function) _not_ containing at least the passed number of
+arguments (presumably, required by such function's prototype). This private
+exception handler is intended to be programmatically prefixed to function
+bodies _only_ by ::func_.stop().
+/---
+function ::func.die_of_arg_count_not_exceeding() {
+    (( # )) || :die\
+        'Expected one or more arguments, one actual argument count, and one minimum argument count.'
+    ::func.die_of_arg_count "${@[1,-3]}"\
+        "at least ${@[-1]} arguments but received only ${#@[1,-2]}."
+}
+
+:func.document <<'/---'
+:void ::func.die_of_arg_count_not_ranging(
+    :string... func_args?,
+    :int+nonnegative func_arg_count_min,
+    :int+nonnegative func_arg_count_max,)
+
+Throw an exception due to the passed argument list (presumably, the same list
+passed to the calling function) containing fewer than the passed minimum number
+of arguments or more than the passed maximum number of arguments (presumably,
+required by such function's prototype). This private exception handler is
+intended to be programmatically prefixed to function bodies _only_ by
+::func_.stop().
+/---
+function ::func.die_of_arg_count_not_ranging() {
+    (( # >= 2 )) || :die\
+        'Expected one or more arguments, one minimum argument count, and one maximum argument count.'
+    ::func.die_of_arg_count "${@[1,-3]}"\
+        "between ${@[-2]} and ${@[-1]} arguments but received ${#@[1,-3]}."
 }
 
 # ....................{ EXCEPTIONS ~ arg type              }....................
 :func.document <<'/---'
 :void ::func.die_unless_arg_expansions_pass_tester(
-    :string func_arg1, ...,
+    :string... func_args,
     :string func_arg_expansions,
     :string/func tester_name)
 
@@ -279,6 +314,8 @@ function ::func.die_unless_arg_expansions_pass_tester() {
     local\
         arg_indices_string="${@[-2]}"\
         arg_tester_name="${@[-1]}"\
+        arg_index_min\
+        arg_index_max\
         arg_value\
         error_message\
         func_prototype
@@ -295,11 +332,12 @@ function ::func.die_unless_arg_expansions_pass_tester() {
     # innteger ranges, this list contains only actual integers.
     local -a arg_indices
 
-    # Such function's prototype.
+    # Such function's prototype, indented for readability.
     :func.set_prototype "${func_name}" func_prototype
+    ::string.indent func_prototype
 
     # Convert such space-delimited string to such list.
-    local arg_index_string arg_index_min arg_index_max
+    local arg_index_string
     for   arg_index_string (${(z)arg_indices_string}) {
         # Strip such string of "${@[" and "]}" delimiters.
         arg_index_string="${${arg_index#\$\{@\[}%]\}}"
@@ -397,7 +435,7 @@ function ::func.die_unless_arg_expansions_pass_tester() {
 
 # ....................{ SETTERS                            }....................
 :func.document <<'/---'
-:void ::func.set_arg_current_type(^:string arg_type)
+:void ::func.set_arg_current_type(^:string arg_type_name)
 
 Set the passed string variable to the the current argument's *full type* (i.e.,
 `/`- and `+`-delimited concatenation of such argument's subtypes and related
@@ -415,7 +453,7 @@ function ::func.set_arg_current_type() {
 
 #FIXME: Rename to ::func.set_arg_name_prototype().
 :func.document <<'/---'
-:void ::func.set_arg_current_name(^:string arg_name)
+:void ::func.set_arg_current_name(^:string arg_name_name)
 
 Set the passed string variable to the current argument's *full name* (i.e.,
 `+`-delimited concatenation of such argument's mandatory documentation-specific
@@ -443,6 +481,21 @@ function ::func.set_arg_current_name() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+    # If such function was declared in a parcel, prefix such exception message
+    # by such parsel.
+    # exception_prefix=$(::parcel.get_current)
+    # if [[ -n ${exception_prefix} ]] {
+    #     exception_prefix+='function '
+    # } else {
+    #     exception_prefix+='Function '
+    # }
+
+# Handle *function declarer exception handlers* (i.e., functions throwing
+# exceptions resulting from validation errors in declared functions).
+
+# Due to a chicken-and-the-egg problem, all functions and globals defined below
+# are subsequently documented under @{help} in the main codebase.
+
     # Note that, due to zsh obscurities, the suffixing " " is *REQUIRED* to
     # ensure such exc
 
@@ -518,7 +571,7 @@ function ::func.set_arg_current_name() {
     # Argument type to recommend such argument be refactored as.
 
         # 'argument ${'${arg_name}'} type '${match[${ZESHY_CALLABLE_PROTOTYPE_ARG_MATCH_INDEX_SUBTYPES}]}' '${1}
-#FUXME: Consider renaming to merely ::func_.die_of_cause().
+#FUXME: Consider renaming to merely ::func.die().
 
 #invalid, as 
 #     local arg_type_label=${arg_type}
@@ -526,7 +579,7 @@ function ::func.set_arg_current_name() {
 #     # If such argument is subtyped, append such label by such types.
 # [[ -z "${arg_subtype}" ]] || print -r -- '+'${arg_subtype}
 # 
-#     ::func_.die_of_cause\
+#     ::func.die\
 #         'argument ${'${arg_name}'} type '${arg_type_label}' invalid, as '${1}
 
 #FUXME: Consider renaming to merely ::func_.die_of(). Indeed, we can profitably
@@ -535,7 +588,7 @@ function ::func.set_arg_current_name() {
 #In the case of *.die_of*() handlers, the preposition "of" already implies such
 #function to accept an exception message; so, we needn't ever state that.
 #Indeed, attempting to add "_cause" induces trouble. As example, which would we
-#prefer: ::func_.die_of_arg_type_cause() or ::func_.die_of_cause_arg_type()?
+#prefer: ::func_.die_of_arg_type_cause() or ::func.die_of_arg_type()?
 #For orthogonality, probably the latter; 
 
             # If either such string is not an integer, throw an exception.
diff --git a/src/00-start/00-declare/70-alias/alias b/src/00-start/00-declare/70-alias/alias
--- a/src/00-start/00-declare/70-alias/alias
+++ b/src/00-start/00-declare/70-alias/alias
@@ -40,12 +40,12 @@ is intended to be referenced _only_ by ::alias().
 typeset -g ZESHY__ALIAS_TO_EXPANSION_NAME_KEY
 
 :global.document <<'/---'
-:string ZESHY__ALIAS_LABEL
+:string ZESHY__ALIAS_TYPE
 
-Human-readable label for the currently declared alias type. This private global
-is intended to be referenced _only_ by ::alias().
+Type of the currently declared alias. This private global is intended to be
+referenced _only_ by ::alias().
 
-== Valid Values ==
+== Valid Types ==
 
 Such type _must_ be one of the following enumeration-style string literals:
 
@@ -53,7 +53,7 @@ Such type _must_ be one of the following enumeration-style string literals:
 * `general`, signifying a general alias.
 * `suffix`, signifying a suffix alias.
 /---
-typeset -g ZESHY__ALIAS_LABEL
+typeset -g ZESHY__ALIAS_TYPE
 
 :global.document <<'/---'
 :string ZESHY__ALIAS_PROTOTYPE
@@ -91,7 +91,7 @@ typeset -g ZESHY__ALIAS_NAME
 
 # ....................{ DECLARERS ~ private                }....................
 :func_ ':void ::alias[
-    args =  (:string `alias_label,
+    args =  (:string `alias_type,
              `^:map `aliases_name,
              :string `alias_prototype,
              :string `alias_expansion),
@@ -99,7 +99,7 @@ typeset -g ZESHY__ALIAS_NAME
     # Localize arguments. Since
     # ::alias.document_prototype,stdin_of_type_if_found_or_noop() already
     # validates such type, avoid doing so here.
-    ZESHY__ALIAS_LABEL="${1}"
+    ZESHY__ALIAS_TYPE="${1}"
     ZESHY__ALIAS_TO_EXPANSION_NAME="${2}"
     ZESHY__ALIAS_PROTOTYPE="${3}"
     ZESHY__ALIAS_EXPANSION="${4}"
@@ -109,13 +109,10 @@ typeset -g ZESHY__ALIAS_NAME
     [[ ${ZESHY__ALIAS_TO_EXPANSION_NAME} == ([gs]|)'aliases' ]] || :die\
         'Aliases map ${'${ZESHY__ALIAS_TO_EXPANSION_NAME}'} unrecognized (i.e., neither "aliases", "galiases", nor "saliases").'
 
-    #FIXME: Generalize such exception handling into a new function
-    #::alias.die_of_cause() defined in a new parcel ={die}.
-
     # If such prototype is syntactically invalid, throw an exception.
     [[ ${ZESHY__ALIAS_PROTOTYPE} =~\
-       ${ZESHY_CALLABLE_PROTOTYPE_NAMES_PCRE} ]] || :die\
-        $(::parcel.get_current)${ZESHY__ALIAS_LABEL}' alias prototype invalid:'$'\n\n'${ZESHY__ALIAS_PROTOTYPE}
+       ${ZESHY_CALLABLE_PROTOTYPE_NAMES_PCRE} ]] ||\
+       ::alias.die 'prototype invalid.'
 
     # If such prototype only declares one name, set such list to such name.
     if [[ -n ${match[1]-} ]] {
@@ -126,8 +123,7 @@ typeset -g ZESHY__ALIAS_NAME
     # be iteratively matched with a PCRE rather than split on commas.
     } else {
         # If such match failed to capture such names, throw an exception.
-        (( ${#match} == 2 )) || :die\
-            $(::parcel.get_current)${ZESHY__ALIAS_LABEL}' alias names unparsable from prototype:'$'\n\n'${ZESHY__ALIAS_PROTOTYPE}
+        (( ${#match} == 2 )) || ::alias.die 'names unparsable from prototype.'
 
         # Cache such names *BEFORE* pcre_match() overwrites ${match}. For
         # abject laziness, reuse existing string global ${ZESHY__ALIAS_NAME}
@@ -168,15 +164,8 @@ typeset -g ZESHY__ALIAS_NAME
         #string to its intended map key as above. Currently, laziness previals.
 
         # If such alias already exists, throw an exception. See :map.is_key().
-        (( ${(P)+ZESHY__ALIAS_TO_EXPANSION_NAME_KEY} == 0 )) || {
-            #FIXME: Actually do so! See ={*-func/die} for related logic.
-
-            # For readability, indent such alias' current definition.
-            local alias_definition=${(P)ZESHY__ALIAS_TO_EXPANSION_NAME_KEY}
-
-            :die\
-                $(::parcel.get_current)${ZESHY__ALIAS_LABEL}' alias '${ZESHY__ALIAS_NAME}'() already defined as:'$'\n\n'${alias_definition}
-        }
+        (( ${(P)+ZESHY__ALIAS_TO_EXPANSION_NAME_KEY} == 0 )) ||
+            ::alias.die_of_redefinition ${(P)ZESHY__ALIAS_TO_EXPANSION_NAME_KEY}
 
         # Declare such alias by assigning to the appropriate key of such map.
         # See :string.set().
@@ -208,8 +197,14 @@ typeset -g ZESHY__ALIAS_NAME
     # defining such aliases above.
     ::alias_of_type.document_prototype_with_stdin_if_nonempty_or_noop\
         "${ZESHY__ALIAS_NAMES[@]}"\
-        "${ZESHY__ALIAS_LABEL}"\
+        "${ZESHY__ALIAS_TYPE}"\
         "${ZESHY__ALIAS_PROTOTYPE}"
+
+    # Clear globals declared above. Since clearing *ALL* such globals would be
+    # needlessly inefficient, clear only that subset of globals inviting issues
+    # elsewhere when left uncleared. See ::func_.stop() for similar logic.
+    ZESHY__ALIAS_NAMES=()
+    ZESHY__ALIAS_PROTOTYPE=
 }:func <<'/---'
 Declare an alias of the passed type residing in the current parcel with
 prototype and hence name parsed from either the passed optional prototype _or_
@@ -259,9 +254,9 @@ I don't believe anything, but I have many suspicions.
 ------------------------------------------
 ==========================================
 
-== Alias Label ==
+== Alias Type ==
 
-The passed label _must_ be one of the following strings:
+The passed type _must_ be one of the following strings:
 
 * `command`, declaring command aliases. See :alias_command().
 * `general`, declaring general aliases. See :alias_general()
@@ -337,6 +332,23 @@ syntax as that supported by function prototypes and AsciiDoc. See
 /---
 
 # --------------------( WASTELANDS                         )--------------------
+        #     # Such type, capitalized for readability.
+        #     local alias_type=${(C)ZESHY__ALIAS_TYPE[1]}${ZESHY__ALIAS_TYPE[2,-1]}
+
+        #     # Such alias' current definition, indented for readability.
+        #     local alias_definition=${(P)ZESHY__ALIAS_TO_EXPANSION_NAME_KEY}
+        #     ::string.indent alias_definition
+
+        #     # Throw such exception.
+        #     ::alias.die_of_definition ${(P)ZESHY__ALIAS_TO_EXPANSION_NAME_KEY}\
+        #         ${ZESHY__ALIAS_NAME}'() already defined.'$'\n\n'${alias_type}' alias definition:'$'\n'${alias_definition}
+        # }
+
+            #FUXME: Actually do so! See ={*-func/die} for related logic.
+
+    #FUXME: Generalize such exception handling into a new function
+    #::alias.die_of_cause() defined in a new parcel ={die}.
+
         #FUXME: Sadly, this *STILL* isn't quite general enough. We'll probably
         #need to manually escape "]" characters in such alias name, at least.
 
@@ -352,7 +364,7 @@ syntax as that supported by function prototypes and AsciiDoc. See
         #relatives to aliases, as in ={*-global/export}.
 
         # Function defining such alias.
-        # alias_definer=":alias_${ZESHY__ALIAS_LABEL}.define"
+        # alias_definer=":alias_${ZESHY__ALIAS_TYPE}.define"
         # :func.die_unless "${alias_definer}"
 
         # # Define such alias.
@@ -519,7 +531,7 @@ syntax as that supported by function prototypes and AsciiDoc. See
 #     set_list_to_string_words words__sltssowf "${args__sltssowf[@]}"
 # 
 #     # Set the current argument list to such words.
-#     set_args "${words__sltssowf[@]}"
+#     :args.set "${words__sltssowf[@]}"
 # 
 #     # Delete such temporary list.
 #     undefine_variable words__sltssowf
