Function prototype generation draft complete.
:func_() and cohorts (e.g., :func_.start(), :func_.stop()) now correctly
generate function preambles for all early-time alias functionality (e.g.,
:alias_command(), :alias_suffix(). What beckons on the grim tide of the morrow?

diff --git a/src/00-start/00-declare/60-func/start b/src/00-start/00-declare/60-func/start
--- a/src/00-start/00-declare/60-func/start
+++ b/src/00-start/00-declare/60-func/start
@@ -179,6 +179,7 @@ function :func_ ::func_.start() {
     [[ -z ${ZESHY__FUNC_PROTOTYPE-x} ]] || :die\
         '":func_" not preceded by "}:func" (i.e., ${ZESHY__FUNC_PROTOTYPE} undefined or non-empty).'
     ZESHY__FUNC_PROTOTYPE="${1}"
+    print -r 'prototype: '${ZESHY__FUNC_PROTOTYPE}
 
     # Clear such map. See :map.clear(). (Ordinarily, orthogonality would imply
     # we also clear such list here. Unlike such map, however, such list need
@@ -240,7 +241,7 @@ function :func_ ::func_.start() {
     [[ ${ZESHY__FUNC_PROTOTYPE} =~\
        ${ZESHY_CALLABLE_PROTOTYPE_PCRE} ]] ||
        ::func_.die_of_cause 'prototype invalid'
-    # print -r -- "matches: ${match[*]} (${#match})"
+    integer match_index; for match_index ({1..${ZESHY_CALLABLE_PROTOTYPE_MATCH_INDEX_ARG_CHANNEL_SECOND_ARGS}}) { print -r 'match '${match_index}': '${match[${match_index}]-} }
 
     # If such match failed to capture either such callable's attributes or
     # names, throw an exception.
@@ -306,23 +307,39 @@ function :func_ ::func_.start() {
     # If any such function already exists, throw an exception.
     :func.die_if "${ZESHY__FUNC_NAMES[@]}"
 
-    # Such conventional argument list.
-    ZESHY__FUNC_ARGS=${ZESHY__FUNC_MATCH[${ZESHY_CALLABLE_PROTOTYPE_MATCH_INDEX_ARGS}]}
+    #FIXME: If nonempty, we need to excise the last character of such match,
+    #which we should validate to *ALWAYS* be ")". Similar logic applies to
+    #argument channels below, as well.
+    #FIXME: Actually, honestly, such logic seems an increasingly poor idea.
+    #Excise all such suffixing ")" tomfoolery and revert us back to sanity.
 
-    # Clear such standard input-specific argument list.
+    # Clear such standard input argument list. Since both branches of the
+    # conditional below set such customary argument list, avoid doing so here.
     ZESHY__FUNC_STDIN=
 
-    # If such prototype did *NOT* specify a conventional argument list, such
-    # prototype specified either one or two argument channels. Parse the
-    # argument lists for such channels into the corresponding strings.
-    if [[ -z ${ZESHY__FUNC_ARGS} ]] {
-        # If such match failed to capture such channels, throw an exception.
-        (( ${#ZESHY__FUNC_MATCH} >=\
-           ZESHY_CALLABLE_PROTOTYPE_MATCH_INDEX_ARG_CHANNEL_FIRST_ARGS )) ||
-            ::func_.die_of_cause 'argument channels unparsable from prototype'
-
-        # For the match indices corresponding to the names of the first and
-        # second argument channels (if any), ...
+    # If such prototype declared no first argument channel, such prototype
+    # either declared:
+    #
+    # * An empty argument channel list (e.g., ":void :empty_channels[]").
+    # * An empty argument list (e.g., ":void :empty_args()").
+    # * A non-empty argument list (e.g., ":void :nonempty_args(:string here)").
+    #
+    # While syntactically different, the former two cases signify the same
+    # semantics of empty standard and standard input argument lists. In either
+    # case, the standard input argument list is empty.
+    #
+    # While the latter case differs both syntactically and semantically, such
+    # case also implies the standard input argument list to be empty.
+    #
+    # All three cases may be efficiently handled by setting the possibly
+    # non-empty standard list -- ignoring the empty standard input list.
+    if [[ -z ${ZESHY__FUNC_MATCH[${ZESHY_CALLABLE_PROTOTYPE_MATCH_INDEX_ARG_CHANNEL_FIRST_ARGS}]-} ]] {
+        ZESHY__FUNC_ARGS=${ZESHY__FUNC_MATCH[${ZESHY_CALLABLE_PROTOTYPE_MATCH_INDEX_ARGS}]}
+    # Else, such prototype declared at least a first argument channel. Parse
+    # the argument lists for such channel and the following optional second
+    # channel into the corresponding strings.
+    } else {
+        # For each match index of the name of the first and second channels... (if
         for ZESHY__FUNC_MATCH_INDEX (
             ${ZESHY_CALLABLE_PROTOTYPE_MATCH_INDEX_ARG_CHANNEL_FIRST_NAME}
             ${ZESHY_CALLABLE_PROTOTYPE_MATCH_INDEX_ARG_CHANNEL_SECOND_NAME}
@@ -331,13 +348,9 @@ function :func_ ::func_.start() {
             # input-specific argument list, set the corresponding string.
             case ${ZESHY__FUNC_MATCH[${ZESHY__FUNC_MATCH_INDEX}]-} {
             ('args')
-                # Discard the ")" suffixing such match. See ={*-pcre}.
-                ZESHY__FUNC_ARGS=${ZESHY__FUNC_MATCH[$(( ZESHY__FUNC_MATCH_INDEX + 1 ))][1,-2]}
-                ;;
+                ZESHY__FUNC_ARGS=${ZESHY__FUNC_MATCH[$(( ZESHY__FUNC_MATCH_INDEX + 1 ))]} ;;
             ('stdin')
-                # Discard the ")" suffixing such match. See ={*-pcre}.
-                ZESHY__FUNC_STDIN=${ZESHY__FUNC_MATCH[$(( ZESHY__FUNC_MATCH_INDEX + 1 ))][1,-2]}
-                ;;
+                ZESHY__FUNC_STDIN=${ZESHY__FUNC_MATCH[$(( ZESHY__FUNC_MATCH_INDEX + 1 ))]} ;;
             # Else if such channel name is empty, such channel *MUST* be an
             # unspecified second channel. Since such channel is optional, this
             # is *NOT* an error. (Simply ignore this.)
@@ -349,6 +362,7 @@ function :func_ ::func_.start() {
             }
         }
     }
+    print -r 'arg list: '${ZESHY__FUNC_ARGS}
 }
 
 #FIXME: In lieu of unit tests...
@@ -479,6 +493,65 @@ function declare_function_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+ # If such argument list
+    # is indeed empty, setting such string simply clears such string; else, setting such string 
+ # both the 
+    # necessarily declared a standard argument list.
+    # # If such prototype declared a standard argument list, munge such string.
+    # if [[ -n ${ZESHY__FUNC_ARGS} ]] {
+    #     # If the last character of such list is *NOT* ")", throw an exception.
+    #     # By PCRE design, such list terminates on such otherwise ignorable
+    #     # delimiter, efficiently ensuring this branch succeeds even on empty
+    #     # argument lists (i.e., "()"). (While this exception should *NEVER*
+    #     # trigger, its preservation guards against unseemly regressions.)
+    #     [[ ${ZESHY__FUNC_ARGS[-1]} == ')' ]] || ::func_.die_of_cause\
+    #         'standard argument list terminator not ")" in prototype'
+
+    #     # Set such string, excising such terminating ")".
+    #     ZESHY__FUNC_ARGS=${ZESHY__FUNC_ARGS[1,-2]}
+    # }
+
+    # Such conventional argument list. 
+    # ZESHY__FUNC_ARGS=${ZESHY__FUNC_MATCH[${ZESHY_CALLABLE_PROTOTYPE_MATCH_INDEX_ARGS}]}
+    # print -r 'arg list (before): '${ZESHY__FUNC_ARGS}
+
+        # If such match failed to capture such channels, throw an exception.
+        # (( ${#ZESHY__FUNC_MATCH} >=\
+        #    ZESHY_CALLABLE_PROTOTYPE_MATCH_INDEX_ARG_CHANNEL_FIRST_ARGS )) ||
+        #     ::func_.die_of_cause 'argument channels unparsable from prototype'
+
+    # no standard argument list, such prototype
+    # declared either one or two argument channels. Parse the argument lists
+    # for such channels into the corresponding strings.
+
+#-z ${ZESHY__FUNC_ARGS} && 
+ # Since both branches of the
+    # conditional below set such customary argument list, avoid doing so here.
+    # # If such prototype declared a customary argument list, set such string.
+    # if [[ -n ${ZESHY__FUNC_ARGS} ]] {
+    #     # If the last character of such list is *NOT* ")", throw an exception.
+    #     # By PCRE design, such list terminates on such otherwise ignorable
+    #     # delimiter, efficiently ensuring this branch succeeds even on empty
+    #     # argument lists (i.e., "()"). (While this exception should *NEVER*
+    #     # trigger, its preservation guards against unseemly regressions.)
+    #     [[ ${ZESHY__FUNC_ARGS[-1]} == ')' ]] || ::func_.die_of_cause\
+    #         'argument list terminator not ")" in prototype'
+
+    #     # Set such string, excising such terminating ")".
+    #     ZESHY__FUNC_ARGS=${ZESHY__FUNC_ARGS[1,-2]}
+
+                # Discard the ")" suffixing such match. See ={*-pcre}.
+                # Discard the ")" suffixing such match. See ={*-pcre}.
+
+# By PCRE design, such character is guaranteed to be , which should validate to *ALWAYS* be ")".
+    # Such conventional argument list.
+    # ZESHY__FUNC_ARGS=${ZESHY__FUNC_MATCH[${ZESHY_CALLABLE_PROTOTYPE_MATCH_INDEX_ARGS}]}
+
+    # If such prototype did *NOT* specify a conventional argument list, such
+    # prototype specified either one or two argument channels. Parse the
+    # argument lists for such channels into the corresponding strings.
+    # if [[ -z ${ZESHY__FUNC_ARGS} ]] {
+
 #_not_ 
 # :map_global ZESHY_FUNCTION_NAME_TO_FUNCTION_NAME_FIRST <<'/---'
 # Map each function name to the first function name declared for such function.
@@ -1690,7 +1763,7 @@ function declare_function_with_stdin() {
                 # Note such fact.
                 # arg_is_variadic=1
 
-            # if [[ -z "${match[${ZESHY_CALLABLE_PROTOTYPE_ARG_MATCH_INDEX_IS_VARIADIC}]-}" ]] {
+            # if [[ -z "${match[${ZESHY_CALLABLE_PROTOTYPE_ARG_MATCH_INDEX_TYPE_IS_VARIADIC}]-}" ]] {
             #     # Note such fact.
             #     arg_is_variadic=0
 
@@ -2218,7 +2291,7 @@ function declare_function_with_stdin() {
 #     ZESHY_CALLABLE_PROTOTYPE_ARG_MATCH_INDEX_NAME=3\
 #     ZESHY_CALLABLE_PROTOTYPE_ARG_MATCH_INDEX_IS_ABSENTABLE=4\
 #     ZESHY_CALLABLE_PROTOTYPE_ARG_MATCH_INDEX_DEFAULT_VALUE=5\
-#     ZESHY_CALLABLE_PROTOTYPE_ARG_MATCH_INDEX_IS_VARIADIC=6
+#     ZESHY_CALLABLE_PROTOTYPE_ARG_MATCH_INDEX_TYPE_IS_VARIADIC=6
 
     #FUXME: Replace with the equivalent globals declared above.
 
