Added call stack handling to low-level printers.
Low-level printer functions now appropriately set string global
${ZESHY_PRINT_CALL_STACK_ROOT}, to ensure proper newline delimiting.
Added 0-byte file testers to component "path/file/file". Moved 0-byte
file creators to component "path/posix/size" with the other such
functions. Renamed run() to run_command(). A minor suite of minor
fixes (and surely regressions), as well.

diff --git a/src/always/runnable/command/option b/src/always/runnable/command/option
--- a/src/always/runnable/command/option
+++ b/src/always/runnable/command/option
@@ -10,7 +10,7 @@
 
 # ....................{ RUNNERS ~ options                  }....................
 document_function '
-string run_with_options(
+string run_command_with_options(
   string command_prefix,
   string options_list_names,
   string command_arg1, string command_arg2, ...)
@@ -19,7 +19,7 @@ Construct a command from the passed arguments; then run such command: e.g.,
 
   # Run grep recursively with the passed list of options and user arguments,
   # paging standard output if required.
-  >>> run_with_options "run_paged grep"\
+  >>> run_command_with_options "run_command_paged grep"\
   ...   "ZESHY_GREP_OPTIONS ZESHY_GREP_OPTIONS_IF_RECURSIVE" "${(q)@}"
 
 Specifically:
@@ -30,16 +30,16 @@ Specifically:
   "ZESHY_GREP_OPTIONS" and "ZESHY_GREP_OPTIONS_IF_RECURSIVE").
 * Set the command to be run to pipe standard input if this function was piped
   such input or to the empty string otherwise (e.g., "cat /dev/stdin |" or "").
-* Append the passed prefix to such command (e.g., "run_paged grep -R").
+* Append the passed prefix to such command (e.g., "run_command_paged grep -R").
 * For every list name in such list:
   * If that list exists, append all elements of that list to such command.
   * Else throw an exception.
 * Append the passed arguments to such command (e.g., "${(q)@}").
 * Run such command (e.g., assuming the caller passed a single argument ''Weeds''
   and piped no input and the above options lists contain default elements,
-  "run_paged grep --extended-regexp --no-messages --recursive ''Weeds''").
+  "run_command_paged grep --extended-regexp --no-messages --recursive ''Weeds''").
 '
-function run_with_options() {
+function run_command_with_options() {
     # Validate passed arguments.
     die_unless_args_2_or_more\
         'expected one command prefix, one list name, and optional command arguments'
@@ -70,12 +70,12 @@ function run_with_options() {
     command__rwo+=( "${@}" )
 
     # Run such command.
-#   print_string "run_with_options: \"${command__rwo[*]}\"..."
-    run "${command__rwo[@]}"
+#   print_string "run_command_with_options: \"${command__rwo[*]}\"..."
+    run_command "${command__rwo[@]}"
 }
 
 document_function '
-string run_with_options_silently(
+string run_command_with_options_silently(
   string command_prefix,
   string options_list_names,
   string command_arg1, string command_arg2, ...)
@@ -84,9 +84,9 @@ Construct a command from the passed arguments; then run such command quietly
 (i.e., with neither terminal output or interactive input). To do so, append
 " ${list_name_first}_IF_SHELL_NON_INTERACTIVE" to the passed string of list
 names, where ${list_name_first} is the first list name in such string; then
-call run_with_options() on such arguments.
+call run_command_with_options() on such arguments.
 '
-function run_with_options_silently() {
+function run_command_with_options_silently() {
     # Validate passed arguments.
     die_unless_args_2_or_more\
         'expected one command prefix, one list name, and optional command arguments'
@@ -104,16 +104,16 @@ function run_with_options_silently() {
         2+=" ${options_list_name_first__rwos}_IF_SHELL_NONINTERACTIVE"
 
     # Run such command. Avoid prepending such command with a call to
-    # run_silently(), which inadvertently silences error output from
-    # run_with_options(). Specifically, don't do this:
+    # run_command_silently(), which inadvertently silences error output from
+    # run_command_with_options(). Specifically, don't do this:
     #
-    #     >>> run_silently run_with_options "${@}"
-    run_with_options "${@}"
-#   run_with_options "${@}" '1>&2'
+    #     >>> run_command_silently run_command_with_options "${@}"
+    run_command_with_options "${@}"
+#   run_command_with_options "${@}" '1>&2'
 }
 
 document_function '
-string run_with_options_configured(
+string run_command_with_options_configured(
   string command_prefix,
   string options_list_names,
   string command_arg1, string command_arg2, ...)
@@ -123,9 +123,9 @@ or not the current shell is interactive; then run such command. To do so, append
 " ${list_name_first}_IF_SHELL_INTERACTIVE" if this shell is interactive or
 " ${list_name_first}_IF_SHELL_NON_INTERACTIVE" otherwise to the passed string of
 list names, where ${list_name_first} is the first list name in such string; then
-call run_with_options() on such arguments.
+call run_command_with_options() on such arguments.
 '
-function run_with_options_configured() {
+function run_command_with_options_configured() {
     # Validate passed arguments.
     die_unless_args_2_or_more\
         'expected one command prefix, one list name, and optional command arguments'
@@ -147,7 +147,7 @@ function run_with_options_configured() {
         2+=" ${options_list_name__rwoc}"
 
     # Run such command.
-    run_with_options "${@}"
+    run_command_with_options "${@}"
 }
 
 # --------------------( WASTELANDS                         )--------------------
@@ -155,10 +155,10 @@ function run_with_options_configured() {
 #   print "list type: ${(t)options_list_names__rwo}"
 #   die_unless_list options_list_names__rwo
     # Similarly, avoid prepending such command with a call to
-    # run_to_standard_error(), which... well, I can't quite remember
+    # run_command_to_standard_error(), which... well, I can't quite remember
     # why not. Hmm.
     #
-    #     >>> run_to_standard_error run_with_options "${@}"
+    #     >>> run_command_to_standard_error run_command_with_options "${@}"
 #   print "running silently: ${*}"
 #   for options_list_name__rwos (
 #       "${options_list_name_first__rwos}_IF_SILENT"
