Initial working commit.
This commit corrects all outstanding issues with the prior, as well
as introducing several new top-level Zeshy components: e.g.,

* Zeshy File, for file- and path-handling facilities.
* Zeshy Inspect, for Zsh object inspection facilities.
* Zeshy OS, for Zsh operating system facilities.

And, so on.

diff --git a/bin/zeshy b/bin/zeshy
--- a/bin/zeshy
+++ b/bin/zeshy
@@ -3,11 +3,17 @@
 #                     [ Time-stamp: "2008-10-27 03:30:32 leycec" ]
 #
 # --------------------( SYNOPSIS                           )--------------------
-# Shebang Zeshy loader. This Zeshy-specific Zsh script replaces the
-# "#!/usr/bin/env zsh" shebang command, used to invoke Zsh on a file, with the
-# "#!/usr/bin/env zeshy" shebang command, used to invoke Zeshy-enabled Zsh on a
-# file, where "Zeshy-enabled" means a Zsh shell process having available all
-# functions, aliases, and variables defined by "zeshy/core". 
+# Shebang Zeshy loader. This Zeshy-specific Zsh shell script replaces the
+# "#!/usr/bin/env zsh" shebang command, which invokes Zsh on the file, with a
+# "#!/usr/bin/env zeshy" shebang command, which invokes Zeshy-capable Zsh on the
+# same file.
+#
+# Here, "Zeshy-capable Zsh" means a Zsh shell process having available:
+#
+# * All functions, aliases, and variables exported by Zeshy Core. 
+# * No functions or aliases exported by other Zeshy components.
+# * But possibly variables exported by other Zeshy components, if inherited from the
+#   caller's environment. In other words, do not rely on this.
 #
 # --------------------( USAGE                              )--------------------
 # Third-party scripts requiring one or more Zeshy components are encouraged to
@@ -31,15 +37,26 @@
 # Note that this script performs additional checks for path and platform sanity;
 # thus, the above approach is strongly discouraged.
 
-# ....................{ ZESHY                              }....................
-# Ensure "${ZESHY_HOME}" is defined and, if not, attempt to find it.
+# ....................{ MAIN                               }....................
+# Ensure "${ZESHY_HOME}" is defined and, if not, try to do so.
 if [[ -z "${ZESHY_HOME}" ]]; then
-    
+    if [[ -r    '/etc/env.d/50zeshy' ]]
+    then source '/etc/env.d/50zeshy'
+    else export ZESHY_HOME='/usr/share/zeshy'
+    fi
 fi
 
-# Source "zeshy/core", if not already available.
-[[ -n "${ZESHY_CORE_IS_AVAILABLE}" ]] || 
-whence -w import 
+# If Zeshy does not exist, fail with error.
+if [[ ! -d "${ZESHY_HOME}" ]]; then
+    echo "zeshy: Zeshy not found at \"${ZESHY_HOME}\"" 2>&1
+    exit 1
+fi
+
+# Import Zeshy Core.
+source "${ZESHY_HOME}/zeshy/core"
+
+# Import and run the passed Zsh script. 
+import "${0}"
 
 # --------------------( COPYRIGHT AND LICENSE              )--------------------
 # The information below applies to everything in this distribution,
diff --git a/src/zshrc b/src/zshrc
--- a/src/zshrc
+++ b/src/zshrc
@@ -143,7 +143,6 @@ alias se="stop-service"
 # Three letter.
 alias dil="diff-less"
 alias mvp="mv-pcre"
-alias mvt="mv-temp"
 alias unp="unpack"
 alias wcr="wc-recursive"
 
@@ -188,21 +187,6 @@ cpr-quiet() { \cp --archive --recursive --verbose --update "${@}" 2> /dev/null }
 alias mv="mv --interactive --verbose" 
 alias mv-pdf="mv ~leycec/pub/new/*.pdf ~leycec/pub/new/pdf/"
 alias mv-torrent="mv ~leycec/pub/new/*.torrent ~leycec/pub/new/torrent/"
-
-# Move any number of source files and paths to "/tmp/", suffixing all files and
-# paths that already exist in "/tmp/" with the current time. 
-mv-temp() {
-  for MOVE_SRC_FILE in $* ; do
-    MOVE_BASENAME=$(basename "$MOVE_SRC_FILE")
-    MOVE_TRG_FILE="/tmp/$MOVE_BASENAME"
-
-    if [ -e "$MOVE_TRG_FILE" ]; then
-      MOVE_TRG_FILE="/tmp/$MOVE_BASENAME~"$(date +'%F_%H-%M-%S')
-    fi
-
-    mv "$MOVE_SRC_FILE" "$MOVE_TRG_FILE"
-  done
-}
 
 # File. (Remove.)
 alias rm="rm --interactive=always --verbose"
@@ -981,23 +965,22 @@ mp3splt-cue() {
     CUE_FILE="$1"
   fi
 
-  echo "mp3splt-cue: splitting '$MP3_FILE' using '$CUE_FILE'..."
+  echo "mp3splt-cue: splitting \"$MP3_FILE\" using cue file \"$CUE_FILE\"..."
   mp3splt -afc "$CUE_FILE" "$MP3_FILE"
 }
 
 ncmpcpp() {
-  # Start the local "mpd" server if not already started.
-  if ! pidof mpd 1> /dev/null; then
-    utter "restarting mpd..."
+    # Start the local "mpd" server if not already started.
+    if ! is_running mpd; then
+        utter "restarting mpd..."
 
-    if [ -x /etc/init.d/mpd ]; then
-      sudo /etc/init.d/mpd restart || die "restarting mpd... failed!"
-    else
-      /usr/bin/mpd --no-create-db  || die "restarting mpd... failed!"
+        if [[ -x '/etc/init.d/mpd' ]]
+        then sudo '/etc/init.d/mpd' restart || die "restarting mpd... failed!"
+        else /usr/bin/mpd --no-create-db  || die "restarting mpd... failed!"
+        fi
     fi
-  fi
 
-  command ncmpcpp
+    command ncmpcpp
 }
 
 # Fonts.
