Improved Zeshy startup.
Consolidated "bin/zeshy" and "bin/zeshy.dev" into "bin/zeshy". Began
implementating safeguards against Zeshy reloads during startup Zsh
logic.

diff --git a/bin/zeshy b/bin/zeshy
--- a/bin/zeshy
+++ b/bin/zeshy
@@ -33,6 +33,12 @@
 #   here *SHOULD* have a direct C analogue. The potential startup speedup makes
 #   this a particularly worthwhile improvement.
 
+# ....................{ SHELL                              }....................
+# Enable shell strictness. While Zeshy replaces such crude options with
+# considerably more robust error handling (e.g., printing stack traces and help
+# documentation on errors), this certainly beats the default do-nothing logic.
+setopt err_return no_unset warn_create_global
+
 # ....................{ PATHS                              }....................
 #FIXME: The "install" script *MUST* absolutely globally replace all instances of
 #  @ZESHY_HOME@ in this script. (There should only be one such instance,
@@ -42,44 +48,152 @@
 # Absolute path of the root Zeshy overlay (i.e., topmost Zeshy directory). The
 # Zeshy installation script defaults this path to the corresponding path passed
 # to such script by the current system or user during Zeshy installation.
-export ZESHY_HOME="${ZESHY_HOME:-@ZESHY_HOME@}"
+export ZESHY_HOME='@ZESHY_HOME@'
 
-# Absolute path of the root Zeshy overlay's startup script, which when sourced
-# loads all Zeshy aliases, functions, and globals specific to the current user.
-export ZESHY_HOME_SCRIPT="${ZESHY_HOME}/main"
+# If such path has not been replaced, the user failed to install Zeshy (e.g.,
+# due to legitimately running Zeshy under a cloned "git" repository), detect
+# this and attempt to respond rationally.
+[[ "${ZESHY_HOME}" == '@ZESHY_HOME@' ]] && {
+    # Absolute path of the the current script. Since the following statement
+    # erroneously interprets a trailing "(:A)" as a literal string rather than
+    # shell word modifier, embed the trailing "(:A)" in a command substitution:
+    # e.g.,
+    #
+    #     # This utterly fails. (Thanks, Zsh.)
+    #     >>> ZESHY_FILENAME="${0}"(:A) && print ${ZESHY_FILENAME}
+    #     /usr/bin/zeshy(:A)
+    local ZESHY_FILENAME; ZESHY_FILENAME="$(print -- "${0}"(:A))"
+    #print "ZESHY_FILENAME: ${ZESHY_FILENAME}"
 
-# If either such path is not found, fail with error.
+    # Absolute path of the directory containing this script.
+    local ZESHY_COMMAND_DIR="${ZESHY_FILENAME:h}"
+
+    # Absolute path of the main Zeshy overlay.
+    ZESHY_HOME="$(print -- "${ZESHY_COMMAND_DIR}/../src"(:A))"
+}
+#print "ZESHY_HOME: ${ZESHY_HOME}"
+
+# If such path is not found, fail with error.
 [[ -d "${ZESHY_HOME}" ]] || {
     print "zeshy: main overlay \"${ZESHY_HOME}\" not found" 1>&2
 
     # If the default value for ${ZESHY_HOME} was not replaced, the Zeshy
     # installation script was probably not run. (Kindly notify the user.)
-    [[ "${ZESHY_HOME}" == '@ZESHY_HOME_HOME@' ]] && {
+    [[ "${ZESHY_HOME}" == '@ZESHY_HOME@' ]] && {
         print 'zeshy: "@"-style substitution not substituted' 1>&2
         print 'zeshy: not installed or installed incorrectly' 1>&2
     }
 
     exit 1
 }
+
+# Absolute path of the root Zeshy overlay's startup script, which when sourced
+# loads all Zeshy aliases, functions, and globals specific to the current user.
+export ZESHY_HOME_SCRIPT="${ZESHY_HOME}/main"
+
+# If such path is not found, fail with error.
 [[ -f "${ZESHY_HOME_SCRIPT}" ]] || {
     print "zeshy: main script \"${ZESHY_HOME_SCRIPT}\" not found" 1>&2
     exit 1
 }
 
+# ....................{ OPTIONS                            }....................
+local help_message="Usage: zeshy [OPTION]... [FILE [ARGUMENT]...]
+
+Open a Zeshy-fortified zsh shell under the passed OPTIONs. Source the optionally
+passed FILE as a Zeshy script passed the passed ARGUMENTs.
+
+Main options:
+  -h, --help             print this help text and exit
+  -i, --interactive      open an interactive non-login zsh shell
+  -l, --login            open an interactive login zsh shell
+  --                     stop parsing options
+
+Parameterized options:
+  -c COMMAND,            run this Zeshy shell command (e.g., \"-c 'is_dir /'\")
+     --command=COMMAND
+  -o OPTION,             enable this zsh shell option (\"man zshoptions\")
+     --option=OPTION
+
+Startup options:
+  --no-digest            do not load Zeshy from a digest file but by sourcing
+                            relevant Zeshy scripts; by default, Zeshy prefers the
+                            former for efficiency when reloaded
+"
+
+# If called as "zeshy-login", prepend option "-l" to the passed arguments.
+# Ideally, this script would itself ascertain whether or not it was run as a
+# login shell by a process running "login". Such process reliably prefixes the
+# ${argv[0]} string identifying the name of this process with "-", thus
+# signifying this shell to be a login shell. Unfortunately, Zsh squelches such
+# "-" unless explicitly running this script under "zsh" rather than an implicit
+# shebang line (e.g., as "- zsh /usr/bin/zeshy" rather than "- /usr/bin/zeshy").
+# While replacing this script with a customary C-based binary would rectify such
+# issue, "the best laid schemes of mice and men/often go awry."
+[[ "${0:t}" == 'zeshy-login' ]] && set -- -l "${@}"
+
+# If passed no arguments and...
+(( # )) ||
+    # If standard input to the current shell is attached to a terminal, drop the
+    # caller into an interactive Zeshy shell.
+    if [[ -t 0 ]]
+    then set -- -i
+    # Otherwise, drop the caller off the Tarabithian bridge.
+    else die 'expected at least one argument when called non-interactively'
+    fi
+
+# Load module "zutil", defining zparseargs() and other helpful builtins.
+zmodload zsh/zutil
+
+#FIXME: Add a canonical "-v, --version" option.
+
+# Parse passed options specific to this script, propagating all other arguments
+# to the main Zeshy script. If such parsing fails, print the help string to
+# standard error and exit with non-zero status. See parse_arg_options() for
+# further details.
+local -A arg_options
+zparseopts -M -D -E -A arg_options --\
+    h i l -help=h -interactive=i -login=l || {
+    print -- "${help_message}" 1>&2
+    exit 1
+}
+
+# If passed a help option, ignore all other options, print the help string to
+# standard output, and exit with zero status.
+(( ${+arg_options[-h]} )) && {
+    print -- "${help_message}"
+    exit 0
+}
+
 # ....................{ MAIN                               }....................
-#FIXME: Extend to support options -- particularly, "-c", which should definitely
-#be the first option we implement support for, and "-", implying a login shell.
-#Supporting the latter option is essential for masquerading Zeshy as a proper
-#shell (and in particular allowing use of Zeshy in "/etc/passwd").
-#FIXME: O.K.; this script pretty much has to be rewritten as a basic Bourne
-#shell script. I know, I know; but there's really no other way. Such script
-#should combine the contents of this and "zeshy.dev" into a single driver
-#script invoking zsh with desired options (e.g., "-"). After careful thought, I
-#can't help but conclude that the only sane means of loading Zeshy when manually
-#invoking zsh is by passing the path to ${ZESHY_HOME} as the first argument to
-#"zsh" and all other arguments passed to such script as subsequent arguments to
-#"zsh". According to "man zsh", "zsh -i ${ZESHY_HOME}" *SHOULD* have the desired
-#effect of running "zsh" interactively after sourcing the passed Zsh script.
+# To avoid reloading Zeshy if already loaded by startup Zsh logic, pass an
+# option to the main Zeshy script instructing such script to avoid doing so.
+# Since only the current script should ever pass such option, avoid publicly
+# documenting such option in the above help text. For details, see corresponding
+# comments in the main Zeshy script.
+set -- "${@}" --no-reload-by-current-process
+
+# If passed either "-l" or "-i", replace the current process with a new process
+# running zsh under such options. (Since changing such options changes zsh's
+# startup behavior, such options cannot be changed at runtime but must be
+# explicitly passed to the "zsh" command.)
+#
+# Since login shells are implicitly interactive, "-l" subsumes "-i". Hence,
+# test the latter before the former.
+if (( ${+arg_options[-l]} ))
+then exec zsh -l -- "${ZESHY_HOME_SCRIPT}" "${@}"
+elif (( ${+arg_options[-i]} ))
+then exec zsh -i -- "${ZESHY_HOME_SCRIPT}" "${@}"
+# Else source the main Zeshy script with the passed arguments under the current
+# zsh process.
+else source -- "${ZESHY_HOME_SCRIPT}" "${@}"
+fi
+
+# --------------------( WASTELANDS                         )--------------------
+# --no-reload            do not load Zeshy if previously loaded by the current
+#                           shell; by default, Zeshy prefers to always reload
+#                           itself to account for configuration changes
+
 #FIXME: Note that this will play poorly with our current method of sourcing
 #Zeshy in "/etc/zsh/zshrc". We'll be loading Zeshy twice -- first by
 #"/etc/zsh/zshrc" and second by the passed parameter to "zsh". Clearly, the
@@ -141,7 +255,47 @@ export ZESHY_HOME_SCRIPT="${ZESHY_HOME}/main"
 #
 #Oh, and if such test succeeds, "unset ZESHY_PID_IF_ZSH_STARTUP". No more reason
 #to keep such global around at that point -- just clutters things up.
-#FIXME: O.K.; Linux login precedents are, frankly, bizarre. Here's out it works:
+
+#, if such Zeshy script has not already been sourced by the current
+# zsh process (e.g., due to a Zsh dotfile sourcing such script on Zsh startup)
+
+# --no-digest-or-source  do not load Zeshy at all; only handle passed arguments
+    # If Zeshy has already been loaded by the current process, avoid doing so
+    # again by passing the appropriate option to Zeshy, below.
+#   [[ "${ZESHY_PID_IF_ZSH_STARTUP-}" -eq ${$} ]] &&
+#       set -- --no-digest-or-source "${@}"
+
+# --no-digest            do not load Zeshy from a digest file but by sourcing
+#                           relevant Zeshy scripts (warning: this is slow)
+# --no-digest-or-source  do not load Zeshy; only handle passed arguments
+    # Process ID of the current process.
+#   export -i ZESHY_PID_IF_ZSH_STARTUP
+
+#if (( ${+arg_options[-i]} + ${+arg_options[-l]} ))
+#then exec zsh "${arg_options[@]}" -- "${ZESHY_HOME_SCRIPT}" "${@}"
+
+#FUXME: Merge "zeshy.dev" here. Yes, just do it. This will allow users to test
+#Zeshy from a cloned git repository without necessarily installing it, which is
+#*VERY* nice and polite and such.
+# Run Zeshy from an in-development "git" rather than installed directory tree.
+# This script sets ${ZESHY_HOME} to conform to "git" directory tree structure
+# and otherwise operates similar to the main "zeshy" command.
+
+# Find the index of the first passed argument either equal to "-c" or not
+# prefixed by "-", signifying the first Zeshy-specific argument.
+#integer zsh_nonoption_first_index="${@[(i)(-c|([^-])*)]}"
+#integer zsh_option_last_index=$(( zsh_nonoption_first_index - 1))
+
+# Split passed arguments into Zsh-specific options and Zeshy-specific arguments.
+# The former include all passed arguments prefixed by "-" excluding "-c", while
+# the latter include all remaining passed arguments.
+#local -a zsh_options zeshy_args
+#zsh_options=( "${@[1,${zsh_option_last_index}]}" )
+#zeshy_args=( "${@[${zsh_nonoption_first_index},-1]}" )
+#print "options: ${zsh_options[@]}"
+#print "nonoptions: ${zeshy_args[@]}"
+
+#FUXME: O.K.; Linux login precedents are, frankly, bizarre. Here's out it works:
 #
 #* All (or nearly all) shells check $argv[0] to see whether or not the name they
 #  were run as is prefixed with a hyphen (e.g., "-bash", "-zsh"). If so, this
@@ -154,65 +308,61 @@ export ZESHY_HOME_SCRIPT="${ZESHY_HOME}/main"
 #In any case, the latter method of passing "-l" should suffice in the above
 #driver script. We'll need to test ${0} for a "-" prefix in such script, as
 #that's presumably what the "login" process will run such script as. (Crazy.)
-#FIXME: Weaksauce. Linux's "/etc/passwd" shell field supports no passed
+#FUXME: Weaksauce. Linux's "/etc/passwd" shell field supports no passed
 #arguments. *sigh* We'll need to create a secondary "/usr/bin/zeshy-login"
 #script -- probably just a symbolic link to this script. We can then check
 #whether or not this script was invoked as "zeshy-login"; if so, obviously
 #prepend "-l" to the passed argument list as follows:
-[[ "${0}" == (|*/)zeshy-login ]] && set -- -l "${@}"
+#FUXME: If neither "-l" or "-i" were passed, we needn't "exec" a new Zsh process.
+# For efficiently sensible process trees, replace the process running the
+# current shell with a new process running Zeshy under a new Zsh shell.
+#if [[ -n "${(M)zsh_options:#-[a-z]#[il]*}" ]]
 
-#FIXME: Fix. Document. Oh, Christ.
-[[ -o interactive ]] && {
-    print "already an interactive shell; unsure how to respond, frankly" 1>&2
-    return 1
-}
-
-#FIXME: O.K.; we should probably be testing here whether or not we were run with
+#FUXME: O.K.; we should probably be testing here whether or not we were run with
 #a "-"-prepended $argv[0] string and hence as a login shell. Unfortunately, I'm
 #not entirely sure how to accomplish that cross-platform portably. Zsh appears
 #to provide no access to such string, as verified by printing such variables
 #below. However, there is a way. You won't like it, but...
 #"/proc/${$}/cmdline" *DOES* provide efficient access under Linux to the null-
 #delimited argv string. That's probably the only way, unfortunately.
-#FIXME: Uh-oh. Problem. Zsh appears to squelch the prefixing "-" unless the
+#FUXME: Uh-oh. Problem. Zsh appears to squelch the prefixing "-" unless the
 #script is explicitly called as follows: "- zsh /usr/bin/zeshy".
 #"- /usr/bin/zeshy" has no effect. Lame! I suppose Zsh thought it "knew" best
 #and decided to simply hide such prefix. O.K.; that implies that we *NEED* "-l"
-#to be explicitly passed to this script on login. We can 
+#to be explicitly passed to this script on login. We can...
 
 #print "argv: ${argv[@]}"
 #print "0: ${0}"
 
-# If the caller passed no arguments and...
-[[ ${#} -eq 0 ]] &&
-    # If standard input to the current shell is attached to a terminal, drop the
-    # caller into an interactive Zeshy shell.
-    if [[ -t 0 ]]
-    then set -- -i
-    # Otherwise, drop the caller off the Tarabithian bridge.
-    else die 'expected at least one argument when called non-interactively'
-    fi
+#FUXME: Fix. Document. Oh, Christ.
+#[[ -o interactive ]] && {
+#    print "already an interactive shell; unsure how to proceed, so dying" 1>&2
+#    return 1
+#}
 
-# Find the index of the first passed argument either equal to "-c" or not
-# prefixed by "-", signifying the first Zeshy-specific argument.
-integer zsh_nonoption_first_index="${@[(i)(-c|([^-])*)]}"
-integer zsh_option_last_index=$(( zsh_nonoption_first_index - 1))
+#FUXME: Extend to support options -- particularly, "-c", which should definitely
+#be the first option we implement support for, and "-", implying a login shell.
+#Supporting the latter option is essential for masquerading Zeshy as a proper
+#shell (and in particular allowing use of Zeshy in "/etc/passwd").
+#FUXME: O.K.; this script pretty much has to be rewritten as a basic Bourne
+#shell script. I know, I know; but there's really no other way. Such script
+#should combine the contents of this and "zeshy.dev" into a single driver
+#script invoking zsh with desired options (e.g., "-"). After careful thought, I
+#can't help but conclude that the only sane means of loading Zeshy when manually
+#invoking zsh is by passing the path to ${ZESHY_HOME} as the first argument to
+#"zsh" and all other arguments passed to such script as subsequent arguments to
+#"zsh". According to "man zsh", "zsh -i ${ZESHY_HOME}" *SHOULD* have the desired
+#effect of running "zsh" interactively after sourcing the passed Zsh script.
+# Map long to short options.
+#(( ${+arg_options[--hello]} )) && arg_options[-h]=
+#(( ${+arg_options[--login]} )) && arg_options[-l]=
+#(( ${+arg_options[--interactive]} )) && arg_options[-i]=
 
-# Split passed arguments into Zsh-specific options and Zeshy-specific arguments.
-# The former include all passed arguments prefixed by "-" excluding "-c", while
-# the latter include all remaining passed arguments.
-local -a zsh_options zeshy_args
-zsh_options=( "${@[1,${zsh_option_last_index}]}" )
-zeshy_args=( "${@[${zsh_nonoption_first_index},-1]}" )
-#print "options: ${zsh_options[@]}"
-#print "nonoptions: ${zeshy_args[@]}"
+# --                     halt parsing options
+# --                     stop parsing options
+#FUXME: [[ "${0:t}" == 'zeshy-login' ]] should do the trick more optimally.
+#[[ "${0}" == (|*/)zeshy-login ]] && set -- -l "${@}"
 
-# For efficiently sensible process trees, replace the process running the
-# current shell with a new process running Zeshy under a new Zsh shell.
-exec zsh "${zsh_options[@]}" --\
-    "${ZESHY_HOME_SCRIPT}" "${zeshy_args[@]}"
-
-# --------------------( WASTELANDS                         )--------------------
 #FUXME: No reason to leave this as a Zsh script, really. "sh" is considerably
 #lighter weight, and seems inherently much more appropriate for this sort-o'-
 #thing. Consider switching. Hard. Well... actually, we *DO* benefit from Zsh-
diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -51,23 +51,18 @@
 # * Incorporate grml-zshrc functionality where helpful, currently available at:
 #   http://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
 
-# ....................{ SANITY                             }....................
+# ....................{ SANITY ~ version                   }....................
 # Oldest Zsh version under which Zeshy runs without error.
 export ZESHY_ZSH_VERSION_REQUIRED=5.0.0
 
-# Exit with fatal error if not running such version.
+# If *NOT* running under such version, fail with non-zero exit status.
 autoload -U is-at-least
 is-at-least ${ZESHY_ZSH_VERSION_REQUIRED} || {
     # Print an error message to standard error.
-    print\
-        "zeshy: installed zsh ${ZSH_VERSION} < required zsh ${ZESHY_ZSH_VERSION_REQUIRED}" 1>&2
+    print "zeshy: installed zsh ${ZSH_VERSION} < required zsh ${ZESHY_ZSH_VERSION_REQUIRED}" 1>&2
 
-    # If interactive, immediately return back to Zsh; otherwise, exit the
-    # current script.
-    if [[ -o interactive ]]
-    then return 1
-    else   exit 1
-    fi
+    # Return rather than exiting to avoid exiting interactive shells.
+    return 1
 }
 
 # Prohibit duplicate paths from being added to canonical global lists, removing
@@ -130,6 +125,8 @@ ZESHY_USER_VERSION_FILE="${ZESHY_USER_DIR}/version"
 # Enforce strictness, as under conventional high-level languages.
 setopt no_unset           # exception on attempting to expand unset parameters
 setopt warn_create_global # warning on attempting to set undeclared parameters
+setopt no_err_exit        # Zeshy implements more robust error handling
+setopt no_err_return      # Zeshy implements more robust error handling
 
 # Variable assignment.
 setopt no_global_export   # prevent "typeset -x" from implying "typeset -xg"
@@ -255,17 +252,18 @@ setopt no_list_ambiguous # only list matches if ambiguous
 # implicitly loading their parent module on the first call to such function, we
 # explicitly load no other modules.
 
-# Stat module wrapping the stat() system call with the zstat() Zsh function. Do
-# not load this module via "zmodload zsh/stat", as that wraps the stat() system
-# call with a stat() Zsh function conflicting with the "stat" command.
+# Wrap system call stat() with Zsh function zstat(). Do not load this module
+# with "zmodload zsh/stat", as that wraps such call with Zsh function stat()
+# conflicting with external POSIX command "stat".
 zmodload -F zsh/stat b:zstat
 
-# Black box module exposing Zsh's C-based internal dictionaries as Zsh-based
+# Expose several of Zsh's internal C-based dictionaries as external Zsh-based
 # associative arrays, including:
 #
-# * ${funcstack}, having the current function call stack for user inspection.
-# * ${functions}, having the current set of all functions for redefinition and
-#   subsequent restoration of alternate function definitions.
+# * ${funcstack}, the stack of functions, scripts, and "eval" statements on the
+#   current call path.
+# * ${functions}, the set of all currently defined functions, permitting
+#   redefinition and subsequent restoration of new function implementations.
 zmodload zsh/parameter
 
 #FIXME: Add ANSI coloring to sayed messages if on an ANSI-capable terminal.
@@ -711,7 +709,10 @@ function print_call_stack() {
 #    return $(( 128 + ${signal_number} ))
 #}
 
-# ....................{ SOURCERS                           }....................
+# ....................{ OPTIONS                            }....................
+#FIXME: Parse options here!
+
+# ....................{ BOOTSTRAP                          }....................
 # void source_zeshy_script(string filename1, string filename2, ...)
 #
 # Source the passed Zeshy scripts with no arguments in the passed order.
@@ -730,12 +731,76 @@ function source_zeshy_script() {
     }
 }
 
-# ....................{ BOOTSTRAP                          }....................
 # If the current shell is a login shell, perform essential login-specific logic.
 # Specifically, set global string ${PATH} and a sane umask and source the
 # expected startup scripts (e.g., under "/etc/profile.d/").
 [[ -o login ]] && source_zeshy_script login
 
+# ....................{ BOOTSTRAP ~ reload                 }....................
+# If sourcing the current script under Zsh startup logic (e.g., from a Zsh
+# script with basename matching either ".zlogin", ".zprofile", or ".zshrc"),
+# prevent Zsh from reloading Zeshy if already loaded earlier during such logic.
+#
+# Ideally, the current script should only ever be sourced by the "zeshy" script
+# installed with Zeshy. Ideally, Zsh startup logic should avoid sourcing the
+# current script. Since Zeshy is valid Zsh, however, this script is sourceable
+# as is by any Zsh script or shell -- including Zsh startup scripts. In such a
+# case, failing to prevent Zsh from reloading Zeshy induces the following:
+#
+# * Some process runs the "zeshy" script as a new child process.
+# * This process runs under "zsh" due to such script's shebang line.
+# * This process sources at least ".zshrc" and possibly also ".zlogin" and
+#   ".zprofile", depending on runtime context.
+# * Sourcing such script could source the current script, loading Zeshy.
+# * After sourcing the current script, control returns to the "zeshy" script,
+#   which either:
+#   * Sources the current script, reloading Zeshy.
+#   * Replaces this process with a new process running "zsh" passed the current
+#     script as its first argument and hence reloading Zeshy twice:
+#     * Once by Zsh startup logic, as above.
+#     * Once by the first argument passed to such script.
+#
+# In either case, Zsh loads Zeshy at least twice and possibly more. Avoid this!
+
+#FIXME: We really need such boolean? Hmmm. Probably. But let's make sure.
+# If non-empty, load Zeshy; otherwise, only handle passed arguments.
+export ZESHY_IS_LOADING=1
+
+#FIXME: This conditional needs testing, clearly.
+#FIXME: Damn. It's broken. Zsh doesn't set it as I expected; hence, we need to
+#manually parse an option "--no-reload". Do so above and test for
+#"(( ${+arg_options[--no-reload]} ))" here. I'm fairly sure we can just replace
+#the "false &&" with the above test... and everything (might) just work. Ah;
+#well, yes. *TECHNICALLY*, the logic below would work -- but it's overkill.
+#Wait...no, it's not. It's the option name that's wrong: it's too succinct.
+#Rename such option to "--no-reload-by-current-process". Bit if a mouthful, but
+#that accurately describes what we *REALLY* want. And given that crazy name,
+#I'm happy to leave this option undocumented, you know?
+
+# If sourcing the current script under Zsh startup logic...
+#print "zeshy: funcstack[1]=${funcstack[1]}"
+print "zeshy: process ID (current)=$$"
+print "zeshy: process ID (parent!)=${PPID}"
+print "zeshy: process ID (cached.)=${ZESHY_PID_IF_ZSH_STARTUP-}"
+
+# Process ID of the last zsh process to previously source this script.
+export -i ZESHY_PID_LAST_LOADED_UNDER
+
+#FIXME: Actually handle the disabling of this boolean, below!
+
+# If such process is the current zsh process, Zeshy has already been loaded.
+# In such case, avoid doing so again.
+if (( ${+arg_options[--no-reload-by-current-process]} &&
+     ZESHY_PID_LAST_LOADED_UNDER == $ ))
+then ZESHY_IS_LOADING=
+# Otherwise, Zeshy has not yet been loaded. Set such process ID to that of
+# the current process for detecting such situation on the next sourcing by
+# the current process of this script.
+else ZESHY_PID_LAST_LOADED_UNDER=$$
+fi
+print "zeshy: ZESHY_IS_LOADING=${ZESHY_IS_LOADING}"
+
+# ....................{ BOOTSTRAP ~ startup                }....................
 # Bootstrap Zeshy by loading core aliases, globals, and autoloads, the minimal
 # clique of Zeshy components. All subsequent Zeshy functions are implicitly
 # loaded on the first call to such functions by the autoload system.
@@ -768,6 +833,27 @@ startup_zeshy
 setup_zeshy
 
 # --------------------( WASTELANDS                         )--------------------
+    #FUXME: Do we need test against *BOTH* $$ and ${PPID}? It can't hurt, of
+    #course... but it would be nice to ascertain which we require.
+#   if [[ "${ZESHY_PID_IF_ZSH_STARTUP}" == ($$|${PPID}) ]]
+
+#[[ "${funcstack[1]}" == */(.|)(zshrc|zprofile|zlogin) ]] && {
+#* If [[ "${ZESHY_PID_IF_ZSH_STARTUP-}" -eq "${PPID}" ]], then:
+#  * Zeshy has already been loaded by the parent process and hence (hopefully)
+#    inherited by the current process. Return immediately.
+#* If [[ "${funcstack[1]}" == "*/(.|)(zprofile|zshrc)" ]], then:
+#  * Set ${ZESHY_PID_IF_ZSH_STARTUP} as a global export in "src/main" ala:
+#    typeset -igx ZESHY_PID_IF_ZSH_STARTUP="${PID}"
+
+# Due to portability
+# concerns, avoid exporting globals via "export" prior to enabling
+    # If interactive, immediately return back to Zsh; otherwise, exit the
+    # current script.
+#   if [[ -o interactive ]]
+#   then return 1
+#   else   exit 1
+#   fi
+
 #   print "defaulting \"ZESHY_HOME\" to \"${ZESHY_HOME}\"" 1>&2
 #   print "consider running \"zeshy\" rather than sourcing \"${0}\"" 1>&2
 
