Utter insanity. Completed "zeshy" invocation.
The "zeshy" wrapper script now correctly invokes Zeshy as a proper
shell, effectively mimicing *MOST* zsh command-line options and hence
serving as a login and/or interactive shell alternative to zsh itself.

The digital pie grows moist and sweet with unsufferably glistening zest.

diff --git a/bin/zeshy b/bin/zeshy
--- a/bin/zeshy
+++ b/bin/zeshy
@@ -45,50 +45,52 @@ setopt err_return no_unset warn_create_global
 #  but... *shrug*.) The at sign "@" is particularly helpful for this
 #  purpose, as it appears to have no current reserved uses in Zsh.
 
-# Absolute path of the root Zeshy overlay (i.e., topmost Zeshy directory). The
+# Absolute path of the main Zeshy overlay (i.e., topmost Zeshy directory). The
 # Zeshy installation script defaults this path to the corresponding path passed
 # to such script by the current system or user during Zeshy installation.
+#
+# Export such path for reuse by the main Zeshy script sourced below.
 export ZESHY_HOME='@ZESHY_HOME@'
 
 # If such path has not been replaced, the user failed to install Zeshy (e.g.,
 # due to legitimately running Zeshy under a cloned "git" repository), detect
 # this and attempt to respond rationally.
-[[ "${ZESHY_HOME}" == '@ZESHY_HOME@' ]] && {
+if [[ "${ZESHY_HOME}" == '@ZESHY_HOME@' ]]; then
     # Absolute path of the the current script. Since the following statement
     # erroneously interprets a trailing "(:A)" as a literal string rather than
     # shell word modifier, embed the trailing "(:A)" in a command substitution:
     # e.g.,
     #
     #     # This utterly fails. (Thanks, Zsh.)
-    #     >>> ZESHY_FILENAME="${0}"(:A) && print ${ZESHY_FILENAME}
+    #     >>> ZESHY_SCRIPT="${0}"(:A) && print ${ZESHY_SCRIPT}
     #     /usr/bin/zeshy(:A)
-    local ZESHY_FILENAME; ZESHY_FILENAME="$(print -- "${0}"(:A))"
-    #print "ZESHY_FILENAME: ${ZESHY_FILENAME}"
+    local ZESHY_SCRIPT; ZESHY_SCRIPT="$(print -- "${0}"(:A))" &>/dev/null || {
+        print "zeshy: current script \"${0}\" not found" 1>&2
+        exit 1
+    }
+    #print "ZESHY_SCRIPT: ${ZESHY_SCRIPT}"
 
     # Absolute path of the directory containing this script.
-    local ZESHY_COMMAND_DIR="${ZESHY_FILENAME:h}"
+    local ZESHY_COMMAND_DIR="${ZESHY_SCRIPT:h}"
 
-    # Absolute path of the main Zeshy overlay.
-    ZESHY_HOME="$(print -- "${ZESHY_COMMAND_DIR}/../src"(:A))"
-}
-#print "ZESHY_HOME: ${ZESHY_HOME}"
-
-# If such path is not found, fail with error.
-[[ -d "${ZESHY_HOME}" ]] || {
-    print "zeshy: main overlay \"${ZESHY_HOME}\" not found" 1>&2
-
-    # If the default value for ${ZESHY_HOME} was not replaced, the Zeshy
-    # installation script was probably not run. (Kindly notify the user.)
-    [[ "${ZESHY_HOME}" == '@ZESHY_HOME@' ]] && {
-        print 'zeshy: "@"-style substitution not substituted' 1>&2
-        print 'zeshy: not installed or installed incorrectly' 1>&2
+    # Set the absolute path of the main Zeshy overlay, given such paths.
+    ZESHY_HOME="$(print -- "${ZESHY_COMMAND_DIR}/../src"(:A))" &>/dev/null || {
+        print "zeshy: main overlay \"${ZESHY_COMMAND_DIR}/../src\" not found" 1>&2
+        print "zeshy: current script \"${0}\" not installed or installed incorrectly" 1>&2
+        exit 1
     }
-
+# If such path is not found, fail with error.
+elif [[ -d "${ZESHY_HOME}" ]]; then
+    print "zeshy: main overlay \"${ZESHY_HOME}\" not found" 1>&2
     exit 1
-}
+fi
+#print "ZESHY_HOME: ${ZESHY_HOME}"
 
 # Absolute path of the root Zeshy overlay's startup script, which when sourced
 # loads all Zeshy aliases, functions, and globals specific to the current user.
+#
+# Export such path for reuse by Zeshy dot directory scripts implicitly sourced
+# below, when opening interactive and login zsh shells.
 export ZESHY_HOME_SCRIPT="${ZESHY_HOME}/main"
 
 # If such path is not found, fail with error.
@@ -98,16 +100,6 @@ export ZESHY_HOME_SCRIPT="${ZESHY_HOME}/main"
 }
 
 # ....................{ OPTIONS                            }....................
-# If passed no arguments and...
-(( # )) ||
-    # If standard input to the current shell is attached to a terminal, drop the
-    # caller into an interactive Zeshy shell.
-    if [[ -t 0 ]]
-    then set -- -i
-    # Otherwise, drop the caller off the Tarabithian bridge.
-    else die 'expected at least one argument when called non-interactively'
-    fi
-
 # If called as "zeshy-login", prepend option "-l" to the passed arguments.
 # Ideally, this script would itself ascertain whether or not it was run as a
 # login shell by a process running "login". Such process reliably prefixes the
@@ -115,11 +107,36 @@ export ZESHY_HOME_SCRIPT="${ZESHY_HOME}/main"
 # signifying this shell to be a login shell. Unfortunately, Zsh squelches such
 # "-" unless explicitly running this script under "zsh" rather than an implicit
 # shebang line (e.g., as "- zsh /usr/bin/zeshy" rather than "- /usr/bin/zeshy").
+#
 # While replacing this script with a customary C-based binary would rectify such
 # issue, "the best laid schemes of mice and men/often go awry."
-#
-# Prepend such option *AFTER* setting default options above.
 [[ "${0:t}" == 'zeshy-login' ]] && set -- -l "${@}"
+
+#FIXME: Not right. Revise this test (and only this test, I believe) to test for
+#whether the caller passed either "-c", "-i", "-l", or a non-"-"-prefixed
+#option. If any is the case, do *NOT* prepend "-i" to the argument list;
+#otherwise, do. Since we prefer "||"-style testing, this should be fairly
+#straightforward to test in the positive statement above.
+#[[ -n "${@:#([^-]*|-([^-]|)[a-z]#[cil][a-z]#)}" ]]
+#(( # )) || print 'zeshy: no runnable args passed!'
+
+# If passed no arguments specifying a course of action, prepend option "-i" to
+# the passed arguments (i.e., default to opening an interactive shell). Prepend
+# such option *AFTER* testing whether we were called as a login shell.
+# Dismantled, this is:
+#
+# * "${@[(i)...]}", expanding to the 1-based index of the first passed argument
+#   matching such glob or to the number of such arguments plus 1 if no argument
+#   matches such glob.
+# * "#", expanding to the number of such arguments.
+(( ${@[(i)([^-]*|-[a-z]#[chilv][a-z]#|--(command=*|help|interactive|login|version))]} <= # )) ||
+    # If standard input to the current shell is attached to a terminal, drop the
+    # caller into an interactive Zeshy shell.
+    if [[ -t 0 ]]
+    then set -- -i "${@}"
+    # Otherwise, drop the caller off the Tarabithian bridge.
+    else die 'expected at least one argument when called non-interactively'
+    fi
 
 # Load module "zutil", defining zparseargs() and other core builtins.
 zmodload zsh/zutil
@@ -129,6 +146,11 @@ zmodload zsh/zutil
 # standard error and exit with non-zero status. See parse_arg_options() for
 # further details. While it *SHOULD* be theoretically infeasible for parsing of
 # such simple options to fail, one just never knows.
+#
+# Map long- to short-form options (e.g., "--interactive" to "-i") rather than
+# the other way around to simplify Zsh interaction below. If such options were
+# passed, we in turn pass such options to Zsh. Since Zsh may or may not expect
+# long-form options depending on platform or version, prefer short-form options.
 local -A arg_options
 zparseopts -M -D -E -A arg_options -- i l -interactive=i -login=l || {
     print -- "zeshy: passed invalid or unknown options" 1>&2
@@ -136,13 +158,6 @@ zparseopts -M -D -E -A arg_options -- i l -interactive=i -login=l || {
 }
 
 # ....................{ MAIN                               }....................
-# To avoid reloading Zeshy if already loaded by startup Zsh logic, pass an
-# option to the main Zeshy script instructing such script to avoid doing so.
-# Since only the current script should ever pass such option, avoid publicly
-# documenting such option in the above help text. For details, see corresponding
-# comments in the main Zeshy script.
-set -- "${@}" --no-zeshy-reload-by-same-process
-
 # If passed either "-l" or "-i", replace the current process with a new process
 # running zsh under such options. Since changing such options changes zsh's
 # startup behavior, such options cannot be changed at runtime but must be
@@ -151,14 +166,57 @@ set -- "${@}" --no-zeshy-reload-by-same-process
 # Dismantled, this is:
 #
 # * "(k)", listing all map keys and thus options "-l" and/or "-i" if passed.
-if (( ${#arg_options} ))
-then exec zsh ${(k)arg_options} -- "${ZESHY_HOME_SCRIPT}" "${@}"
+if (( ${#arg_options} )); then
+    # Absolute path of the system-wide Zeshy-specific dot directory.
+    local ZESHY_ZDOTDIR
+    ZESHY_ZDOTDIR="$(print -- "${ZESHY_HOME}/../etc"(:A))" &>/dev/null || {
+        print "zeshy: dot directory \"${ZESHY_HOME}/../etc\" not found" 1>&2
+        exit 1
+    }
+
+    # Replace the non-interactive zsh process sourcing this script with an
+    # interactive zsh process sourcing Zeshy.
+    ZESHY_USER_ZDOTDIR="${ZDOTDIR:-${HOME}}"\
+    ZDOTDIR="${ZESHY_ZDOTDIR}"\
+    ZESHY_ARGS="${@}"
+        exec zsh ${(k)arg_options}
 # Else source the main Zeshy script with the passed arguments under the current
 # zsh process.
 else source -- "${ZESHY_HOME_SCRIPT}" "${@}"
 fi
 
 # --------------------( WASTELANDS                         )--------------------
+    #FUXME: Great! Unfortunately, this discards ${@}. Due to the insanity of the
+    #redirection below, we'll need to store the current argument list in a Zeshy
+    #global: how about simply ${ZESHY_ARGS}? "etc/zshrc" will then need to pass
+    #such list when sourcing ${ZESHY_HOME_SCRIPT}. Easy; just willfully tedious.
+
+    # If the default value for ${ZESHY_HOME} was not replaced, the Zeshy
+    # installation script was probably not run. (Kindly notify the user.)
+#   [[ "${ZESHY_HOME}" == '@ZESHY_HOME@' ]] && {
+#       print 'zeshy: "@"-style substitution not substituted' 1>&2
+#       print 'zeshy: not installed or installed incorrectly' 1>&2
+#   }
+
+    # If such path is not found, fail with error.
+#   [[ -d "${ZESHY_ZDOTDIR}" ]] || {
+#       print "zeshy: dot directory \"${ZESHY_ZDOTDIR}\" not found" 1>&2
+#       exit 1
+#   }
+
+#   local ZESHY_ZDOTDIR
+#   (( ${+ZDOTDIR} )) && ZDOTDIR_old="${ZDOTDIR}"
+
+#then exec zsh ${(k)arg_options} -s -- "${ZESHY_HOME_SCRIPT}" "${@}"
+#then exec zsh ${(k)arg_options} -- "${@}"
+
+# To avoid reloading Zeshy if already loaded by startup Zsh logic, pass an
+# option to the main Zeshy script instructing such script to avoid doing so.
+# Since only the current script should ever pass such option, avoid publicly
+# documenting such option in the above help text. For details, see corresponding
+# comments in the main Zeshy script.
+#set -- "${@}" --no-zeshy-reload-by-same-process
+
 #passed unexpected or invalid options
 #elif (( ${+arg_options[-i]} ))
 #then exec zsh -i -- "${ZESHY_HOME_SCRIPT}" "${@}"
diff --git a/src/login b/src/login
--- a/src/login
+++ b/src/login
@@ -65,39 +65,25 @@ function set_shell_login_defaults() {
     else umask u=rwx,g=rx,o=
     fi
 
-    #FIXME: source_shell_script() probably shouldn't implicitly append ${FPATH}
-    #to ${PATH}, which induces subtle bugs as below. Was the only reason for
-    #doing this to force searches for scripts to run against both ${FPATH} and
-    #${PATH}. Silly; stop doing such appending and call source_shell_script()
-    #below.
-
     # If "/etc/profile.env" exists, source such script.
     #
     # Avoid calling source_shell_script(), which implicitly appends ${FPATH} to
     # ${PATH} and in this context permanently pollutes ${PATH}.
     [[ -f '/etc/profile.env' ]] && source '/etc/profile.env'
 
-    # Configure global string ${PATH} and global list ${path} *AFTER* sourcing
-    # all shell scripts expected to set default values for such globals.
-    set_shell_login_path
+    # Configure global string ${PATH} and list ${path} *AFTER* sourcing all
+    # scripts expected to set default values for such globals.
+    set_shell_login_default_path
 
     # If "/etc/profile.d/" exists, source all Bourne shell scripts under such
-    # directory. Since most distributions supply csh shell scripts under such
-    # directory not readily sourceable by Zsh, avoid sourcing everything: e.g.,
-    #
-    #    for profile_script ( '/etc/profile.d/'*.[^.]#sh(.) ) {
-    [[ -d '/etc/profile.d' ]] && for shell_script ('/etc/profile.d/'*.sh) {
-        #FIXME: I hope we don't really need source_shell_script() here...
-        #but suspect we do. *sigh*
-        source "${shell_script}"
-#       source_shell_script "${shell_script}"
-    }
+    # directory *AFTER* configuring the command path.
+    set_shell_login_default_profile
 }
 
-# void set_shell_login_path(void)
+# void set_shell_login_default_path(void)
 #
 # Configure global list ${path} and global string ${PATH} with sane defaults.
-function set_shell_login_path() {
+function set_shell_login_default_path() {
     # Validate sanity.
     (( # == 0 )) || die 'expected no arguments'
 #   print "PATH: ${PATH}"
@@ -139,10 +125,46 @@ function set_shell_login_path() {
     fi
 }
 
+# void set_shell_login_default_profile(void)
+#
+# Configure the current shell with the default system-wide login profile.
+# Specifically, source all Bourne shell scripts under "/etc/profile.d" if such
+# directory exists.
+function set_shell_login_default_profile() {
+    # Validate sanity. Unless "/etc/profile.d/" exists, immediately return.
+    (( # == 0 )) || die 'expected no arguments'
+    [[ -d '/etc/profile.d' ]] || return 0
+
+    # Emulate Bourne shell prior to sourcing Bourne shell scripts below by
+    # temporarily enabling Bourne shell options and builtins and ignoring
+    # rather than throwing exceptions on non-zero exit status.
+    emulate -LR sh
+    TRAPZERR() { return $(( 128 + ${1} )) }
+
+    # Source all Bourne shell scripts under "/etc/profile.d". Since most
+    # distributions also bundle csh shell scripts under such directory not
+    # readily sourceable by Zsh, explicitly match only Bourne scripts: e.g.,
+    #
+    #     # Don't do this.
+    #     for profile_script ('/etc/profile.d/'*.[^.]#sh(.)) {
+    for shell_script ('/etc/profile.d/'*.sh) {
+        source "${shell_script}" or die "\"${shell_script}\" not sourceable"
+    }
+}
+
 # ....................{ MAIN                               }....................
 set_shell_login_defaults
 
 # --------------------( WASTELANDS                         )--------------------
+    #FUXME: source_shell_script() probably shouldn't implicitly append ${FPATH}
+    #to ${PATH}, which induces subtle bugs as below. Was the only reason for
+    #doing this to force searches for scripts to run against both ${FPATH} and
+    #${PATH}. Silly; stop doing such appending and call source_shell_script()
+    #below.
+
+        #FUXME: I hope we don't really need source_shell_script() here...
+        #but suspect we do. *sigh*
+#       source_shell_script "${shell_script}"
     # Store the prior ${PATH} if any for subsequent interpolation.
 #   list path_old
 #   if (( EUID == 0 )) and [[ -n "${ROOTPATH-}" ]]
@@ -244,5 +266,5 @@ set_shell_login_defaults
 #    integer_global_export SAVEHIST="${SAVEHIST:-1024}"
 #
 #    # Absolute path of the file persisting Zsh command-line history.
-#    string_global_export  HISTFILE="${HISTFILE:-${ZESHY_USER_DIR}/history}"
+#    string_global_export  HISTFILE="${HISTFILE:-${ZESHY_DOT_DIR}/history}"
 #}
