Added further documentation on future changes.
In particular, documented a sensible means of handling system-specific
configuration files.

diff --git a/bin/zeshy b/bin/zeshy
--- a/bin/zeshy
+++ b/bin/zeshy
@@ -25,23 +25,28 @@
 # zsh, on the other hand, ignores non-zero exit status where not explicitly
 # handled (e.g., by appending "|| { print 'command failed' 1>&2; exit 1 }" to
 # commands expected to fail).
-#
-# --------------------( TODO                               )--------------------
-# * Document somewhere that setting zeshy as a user's default "/etc/passwd"
-#   shell requires adding "zeshy-login" to "/etc/shells" under Linux and
-#   "zeshy-login" as the corresponding shell field.
-# * The fact that zsh squelches "-" prefixes on ${argv[0]} is a clue that we
-#   probably want to reimplement this script in POSIX C. (Could be quite fun,
-#   actually, aside from the fact that it'll require a substantially smarter
-#   zeshy makefile.) Shouldn't be a terribly large file; everything we're doing
-#   here *SHOULD* have a direct C analogue. The potential startup speedup makes
-#   this a particularly worthwhile improvement.
+
+#FIXME: Document somewhere that setting zeshy as a user's default "/etc/passwd"
+#shell requires adding "zeshy-login" to "/etc/shells" under Linux and
+#"zeshy-login" as the corresponding shell field.
+#FIXME: The fact that zsh squelches "-" prefixes on ${argv[0]} is a clue that we
+#probably want to reimplement this script in POSIX C. (Could be quite fun,
+#actually, aside from the fact that it'll require a substantially smarter zeshy
+#makefile.) Shouldn't be a terribly large file; everything we're doing here has
+#a direct C analogue. The potential startup speedup makes this a particularly
+#worthwhile improvement.
+#FIXME: O.K.; make this happen. The refactoring suggested below strongly implies
+#we should go this road. Naturally, contemplate a CMake makefile.
+#FIXME: The only difficult aspect of doing so will be reimplementing the
+#parameter expansion "${(qq)@}" in C. Not a pretty thought, actually. Wait!
+#Actually, since zsh itself is C, such implementation would be trivial. Ya!
+
 #print "[${0}] starting zeshy wrapper"
 
 # ....................{ SHELL                              }....................
 # Enable shell strictness. While zeshy replaces such crude options with
 # considerably more robust error handling (e.g., printing stack traces and help
-# documentation on errors), this beats the default laissez faire looseness.
+# documentation on errors), this beats zsh's default laissez faire laxity.
 #
 # Enable extended glob expressions for use in option checking.
 setopt err_return no_unset warn_create_global extended_glob
@@ -61,6 +66,8 @@ export ZESHY_HOME="${ZESHY_HOME:-@ZESHY_HOME@}"
 # due to legitimately running zeshy under a cloned "git" repository). Detect
 # this and attempt to respond rationally.
 if [[ "${ZESHY_HOME}" == '@ZESHY_HOME@' ]] {
+    local zeshy_filename zeshy_bin_dir
+
     # Absolute path of the the current script. Since the following statement
     # erroneously interprets a trailing "(:A)" as a literal string rather than
     # shell word modifier, embed the trailing "(:A)" in a command substitution:
@@ -69,23 +76,23 @@ if [[ "${ZESHY_HOME}" == '@ZESHY_HOME@' ]] {
     #     # This utterly fails. (Thanks, zsh.)
     #     >>> zeshy_filename="${0}"(:A) && print "${zeshy_filename}"
     #     /usr/bin/zeshy(:A)
-    local zeshy_filename; zeshy_filename="$(print -- "${0}"(:A))" &>/dev/null || {
-        print "zeshy: current script \"${0}\" not found" 1>&2
+    zeshy_filename="$(print -- "${0}"(:A))" &>/dev/null || {
+        print "zeshy: Current script \"${0}\" not found." 1>&2
         exit 1
     }
     #print "zeshy_filename: ${zeshy_filename}"
 
     # Absolute path of the directory containing this script.
-    local zeshy_bin_dir="${zeshy_filename:h}"
+    zeshy_bin_dir="${zeshy_filename:h}"
 
     # Absolute path of the main zeshy overlay, given such paths.
     ZESHY_HOME="$(print -- "${zeshy_bin_dir}/../src"(:A))" &>/dev/null || {
-        print "zeshy: main overlay \"${zeshy_bin_dir}/../src\" not found" 1>&2
+        print "zeshy: Main overlay \"${zeshy_bin_dir}/../src\" not found." 1>&2
         exit 1
     }
 # If such path is not found, fail with error.
-} elif ! [[ -d "${ZESHY_HOME}" ]] {
-    print "zeshy: main overlay \"${ZESHY_HOME}\" not found" 1>&2
+} elif [[ ! -d "${ZESHY_HOME}" ]] {
+    print "zeshy: Main overlay \"${ZESHY_HOME}\" not found." 1>&2
     exit 1
 }
 #print "ZESHY_HOME: ${ZESHY_HOME}"
@@ -96,7 +103,7 @@ ZESHY_MAIN_SCRIPT="${ZESHY_HOME}/main"
 
 # If such path is not found, fail with error.
 [[ -f "${ZESHY_MAIN_SCRIPT}" ]] || {
-    print "zeshy: main script \"${ZESHY_MAIN_SCRIPT}\" not found" 1>&2
+    print "zeshy: Main script \"${ZESHY_MAIN_SCRIPT}\" not found." 1>&2
     exit 1
 }
 
@@ -134,9 +141,9 @@ if [[ "${0:t}" == 'zeshy-login' ]] {
     # caller into an interactive zeshy shell.
     if [[ -t 0 ]] {
         set -- -i "${@}"
-    # Else, drop the caller off the Tarabithian bridge.
+    # Else, drop the caller off the Tarabithian bridge. (Spoiler alert.)
     } else {
-        print "zeshy: expected at least one argument when called non-interactively" 1>&2
+        print "zeshy: Expected at least one argument when called non-interactively." 1>&2
         exit 1
     }
 }
@@ -156,7 +163,7 @@ zmodload zsh/zutil
 # long-form options depending on platform or version, prefer short-form options.
 local -A arg_options
 zparseopts -M -D -E -A arg_options -- i l -interactive=i -login=l || {
-    print -- "zeshy: passed invalid or unknown options" 1>&2
+    print -- "zeshy: Passed invalid or unknown options." 1>&2
     exit 1
 }
 
@@ -171,7 +178,7 @@ if (( ${#arg_options} )) {
     #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     #Order of globals is important here. In particular, declaring ${ZDOTDIR}
     #prior to ${ZESHY_ZDOTDIR_USER} results in the latter copying the former,
-    #resulting in infinite recursion. (Yes, it's a dangerous world we live in.)
+    #resulting in infinite recursion. (Aye, 'tis a dangerous world we live in.)
     #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     #
     # Replace the non-interactive zsh process sourcing this script with an
@@ -186,15 +193,49 @@ if (( ${#arg_options} )) {
     # * ${ZESHY_ARGS}, the list of all arguments passed to this script,
     #   losslessly converted into a string for subsequent conversion back to a
     #   list. Export for subsequent importation by zeshy's ".zshrc". See
-    #   convert_list_to_string() for further details on such conversion.
-    #   Separate such export's declaration and definition to avoid errors
-    #   resembling
+    #   :convert_list_to_string() for further details on such conversion.
+    #   Separate such export's declaration and definition to avoid errors like
     #   "/usr/bin/zeshy:export:179: not valid in this context: '--version'".
     # * ${ZDOTDIR}. See "man zshparam".
     #
     # Dismantled, this is:
     #
     # * "(k)", listing all map keys and thus options "-l" and/or "-i" if passed.
+
+    #FIXME: *OH, BOY*. I'm sure this all *SEEMED* like a good idea at the time,
+    #but it's simply overkill now. Like, *WAY* overkill. And also probably the
+    #completely wrong thing to do. For one thing, we absolutely do *NOT* want
+    #either system or user dotfiles to be sourced prior to sourcing zeshy. While
+    #zeshy is implemented in and runs on zsh, the family resemblance ends there.
+    #System and/or user dotfiles almost certainly contain code that will either
+    #break subsequently autoloaded zeshy code or which subsequently autoloaded
+    #zeshy code will break. In other case, code is breaking. If system
+    #administrators and/or users would like to incorporate existing zsh dotfile
+    #functionality into zeshy, we're afraid they'll simply have to port such
+    #functionality into zeshy manually (e.g., by adding arbitrary files and code
+    #to "~/.zeshy/overlay"). There's no reasonable alternative, given zeshy's
+    #increasingly divergent codebase.
+    #
+    #Given this, we *REALLY* need to ensure the following:
+    #
+    #1. That option "NO_RCS" is enabled on the zsh interpreter interpreting the
+    #   current script *BEFORE* such interpreter's startup. Can we pass such
+    #   option in the shebang line? No idea. If not, that's one more compelling
+    #   reason to reimplement this entire script as a C frontend. (This is
+    #   becoming an increasingly enticing thought.)
+    #2. That option "NO_RCS" is passed to the zsh interpreter forked below.
+    #FIXME: We almost certainly no longer require ${ZESHY_ZDOTDIR_USER}. Since
+    #we don't intend to source system and/or user dotfiles, there's little point
+    #in defining such variable below.
+    #FIXME: Removing such variable effectively reduces "src/.zprofile" and
+    #"src/.zlogin" to the empty string, suggesting we remove such files as well.
+    #That said, the following are almost certainly still necessary:
+    #
+    #* ${ZESHY_ARGS}, as there appears to be no other way of passing interactive
+    #  zsh interpreters "arguments."
+    #* ${ZDOTDIR}, for the above reason.
+    #* "src/.zshrc", for the above reason.
+
     ZESHY_ZDOTDIR_USER="${ZDOTDIR:-${HOME}}"\
     ZESHY_ARGS="${(qq)@}"\
     ZDOTDIR="${ZESHY_HOME}"\
