::script_zsh.source_or_unwind_call_stack() fixed.
Such utility function now attempts to find the passed script if relative under
the directory containing the current script, which seems patently sensible.

diff --git a/bin/zeshy b/bin/zeshy
--- a/bin/zeshy
+++ b/bin/zeshy
@@ -71,7 +71,7 @@
 # standard input (e.g., as a here-document). Defining such script as a here-
 # document permits such script to be defined significantly more naturally than
 # were such script defined with customary single or double quotes.
-
+#
 # Unlike zsh, Bourne shell prohibits arbitrary code blocks from accepting here-
 # documents (or any redirections, for that matter). Like zsh, however, Bourne
 # shell does permit function calls from accepting here-documents. Hence, the
@@ -126,9 +126,9 @@ ZESHY_HOME="${ZESHY_HOME:-@ZESHY_HOME@}"
 # If such path has not been replaced, the user failed to install zeshy (e.g.,
 # due to legitimately running zeshy under a cloned "git" repository). Detect
 # this and attempt to respond rationally.
-if [[ "${ZESHY_HOME}" == '@ZESHY_HOME@' ]] {
-    local zeshy_wrapper_filename zeshy_bin_dir
-    local -a placeholder_list
+if [[ ${ZESHY_HOME} == '@ZESHY_HOME@' ]] {
+    local zeshy_wrapper_filename zeshy_bin_dir zeshy_src_dir
+    local -a pathname_canonical
 
     # Absolute or relative path of the Bourne script wrapping the current zsh
     # script. To prevent syntax errors in the event such path contains either
@@ -137,32 +137,44 @@ if [[ "${ZESHY_HOME}" == '@ZESHY_HOME@' ]] {
     # event such path contains a "}" character.  Since this is substantially
     # less likely than such path containing quote characters, however, we
     # currently ignore such edge case.
-    zeshy_wrapper_filename="${ZESHY_BOURNE_WRAPPER_FILENAME}"
+    zeshy_wrapper_filename=${ZESHY_BOURNE_WRAPPER_FILENAME}
 
     # If such path is relative to the current working directory of the wrapping
     # Bourne script, prepend such path with such directory.
-    [[ "${zeshy_wrapper_filename}" == '/'* ]] ||
+    [[ ${zeshy_wrapper_filename} == '/'* ]] ||
         : "${zeshy_wrapper_filename::=${ZESHY_BOURNE_PWD}/${ZESHY_BOURNE_WRAPPER_FILENAME}}"
 
     # If such script does not exist, fail. (This should never happen.)
-    [[ -f "${zeshy_wrapper_filename}" ]] || {
+    [[ -f ${zeshy_wrapper_filename} ]] || {
         print 'zeshy: Wrapper script "'${zeshy_wrapper_filename}'" not found or not a file.' 1>&2
         exit 1
     }
 
     # Canonicalize such path (i.e., resolve all intermediate symbolic links).
-    # See :convert_path_to_parcel() for further details.
-    placeholder_list=( "${zeshy_wrapper_filename}"(:A) )
-    zeshy_wrapper_filename="${placeholder_list[1]}"
+    # Since the current script necessarily exists, such canonicalization is
+    # guaranteed to succeed and hence need *NOT* be validated (unlike below).
+    pathname_canonical=( "${zeshy_wrapper_filename}"(:A) )
+    zeshy_wrapper_filename="${pathname_canonical[1]}"
     # print "zeshy_wrapper_filename: ${zeshy_wrapper_filename}"
 
-    # Absolute path of the directory containing such script. See
-    # :set_string_to_path_dirname() for further details.
+    # Absolute path of the directory containing such script.
     zeshy_bin_dir="${zeshy_wrapper_filename:h}"
 
-    # Absolute path of the main zeshy overlay directory, given such paths.
-    placeholder_list=( "${zeshy_bin_dir}/../src"(:A) )
-    ZESHY_HOME="${placeholder_list[1]}"
+    # Relative path of the main zeshy overlay directory.
+    zeshy_src_dir="${zeshy_bin_dir}/../src"
+
+    # Absolute path of the main zeshy overlay directory.
+    pathname_canonical=( "${zeshy_src_dir}"(:A) )
+
+    # If such path does *NOT* exist, report failure. See the main zeshy script
+    # for similar logic (and further explanation).
+    (( ${#pathname_canonical} )) || {
+        print 'Main overlay "'${zeshy_src_dir}'/" not found.' 1>&2
+        exit 1
+    }
+
+    # Else, set such global accordingly.
+    ZESHY_HOME="${pathname_canonical[1]}"
 }
 
 # Absolute path of zeshy's entry script, conditionally compiling and
@@ -318,6 +330,9 @@ ZESHY_BOURNE_PWD="${PWD}" \
     exec zsh -o no_rcs -c "${ZESHY_ZSH_WRAPPER}"
 
 # --------------------( WASTELANDS                         )--------------------
+    # Absolute path of the directory containing such script. See
+    # :set_string_to_path_dirname() for further details.
+    # See :convert_path_to_parcel() for further details.
 # -o err_return -o no_unset -o warn_create_global -o extended_glob 
     # ZESHY_MAIN_SCRIPT="${ZESHY_MAIN_SCRIPT}"\
 
