Substantially improved parcel handling.
Such handling is as yet incomplete, but so nearly there it's tastefully
tangy. "25-global" documents a significant flaw, to be amended shortly
(hopefully). Burn, burn!!!! *ahem*

diff --git a/src/always/00-startup/00-declare/05-parcel b/src/always/00-startup/00-declare/05-parcel
--- a/src/always/00-startup/00-declare/05-parcel
+++ b/src/always/00-startup/00-declare/05-parcel
@@ -33,6 +33,13 @@
 #performing an upfront "print -lr -- **/*": that is, caching the set of all
 #absolute paths of all zeshy scripts compiled into the current user digest file.
 #Indeed, caching such set into a map should provide reasonably efficient lookup.
+#FIXME: Ah! We've divorced parcels from scripts. Before, there was a one-to-one
+#relationship between parcels and scripts; now, there's basically a many-to-many
+#relationship, where each script can declare arbitrarily many parcels and
+#parcels can be distributed across multiple files. Hence, the set of all parcel
+#names (which should, of course, be formatted as "/"-delimited pathnames, which
+#need not necessarily exist but typically will under the conventional one-to-one
+#scenario) is easily iterated as the *KEYS* of map ${ZESHY_PARCEL_NAME_TO_HELP}.
 #FIXME: Ah! We could even do one better, by caching into a map whose keys are
 #script basenames and whose values are a null-delimited string list of all
 #absolute dirnames containing such basename, *SORTED* alphabetically. The
@@ -101,14 +108,21 @@ typeset -Agx\
     ZESHY_PARCEL_NAME_TO_GLOBAL_NAMES
 
 # Current parcel name. Since the value of such global is typically specific to
-# the most recent zeshy script to have called declare_parcel(), avoid exporting
+# the most recent zeshy script to have called declare_parcel_to_script(), avoid exporting
 # such global to caller scripts.
 typeset -g ZESHY_PARCEL_NAME
 
 # ....................{ EXCEPTIONS                         }....................
-#FIXME: Document!
+function die_if_parcel_name() {
+    (( # == 1 || # == 2 )) ||
+        die 'expected one parcel name and optional error message'
+    string parcel_name="${1}"
+    is_parcel "${parcel_name}" and
+        die "${2:-parcel \"${parcel_name}\" already declared}"
+}
+
 function die_unless_parcel() {
-    (( # == 1 | # == 2 )) ||
+    (( # == 1 || # == 2 )) ||
         die 'expected one parcel name and optional error message'
     string parcel_name="${1}"
     is_parcel "${parcel_name}" or
@@ -116,13 +130,14 @@ function die_unless_parcel() {
 }
 
 # ....................{ TESTERS                            }....................
-#FIXME: Document!
 function is_parcel() {
+    # See is_map_key() for further details.
     (( # == 1 )) || die 'expected one parcel name'
     (( ${+ZESHY_PARCEL_NAME_TO_HELP[${1}]} ))
 }
 
 # ....................{ GETTERS                            }....................
+#FIXME: Shift these into a new component; they're simply not required here.
 #FIXME: Document!
 function get_parcel() {
     # Validate passed arguments.
@@ -131,21 +146,37 @@ function get_parcel() {
 }
 
 # ....................{ SETTERS                            }....................
-#FIXME: Use in "25-global"!
+#FIXME: Shift these into a new component; they're simply not required here.
 #FIXME: Document!
 function set_parcel() {
+    # Validate passed arguments. If such name is not an absolute path (i.e., is
+    # either not prefixed by "/" or contains null characters), such name is
+    # invalid as a parcel name, so throw an exception. See @{parcel} for further
+    # details.
+    (( # == 1 )) || die 'expected one parcel name'
+    local parcel_name="${1}"
+    die_unless_parcel "${parcel_name}"
+
+    # Set the current parcel to such script, canonicalized to avoid ambiguity
+    # when cross-referencing parcels. See canonicalize_path() for further
+    # details. For efficiency, avoid calling set_parcel().
+    ZESHY_PARCEL_NAME="${parcel_name}"
+}
+
+#FIXME: Document!
+function set_parcel_to_script() {
     # Validate passed arguments.
     (( # == 1 )) || die 'expected one script name'
     local script_name="${1}"
     [[ -f "${script_name}" ]] || die "\"${script_name}\" not a zeshy script"
 
     # Set the current parcel to such script, canonicalized to avoid ambiguity
-    # when cross-referencing parcels. See canonicalize_path() for details.
+    # when cross-referencing parcels. See canonicalize_path() for further
+    # details. For efficiency, avoid calling set_parcel().
     ZESHY_PARCEL_NAME="$(print -- "${script_name}"(:A))"
 }
 
 # ....................{ ADDERS                             }....................
-#FIXME: Document!
 #FIXME: Technically, suffix aliases reside in a separate namespace and hence
 #require separate handling. I can't really be bothered at the moment. Shouldn't
 #be a terribly difficult change; just keep it in mind. For simplicity and
@@ -162,7 +193,6 @@ function add_parcel_alias() {
     ZESHY_PARCEL_NAME_TO_ALIAS_NAMES[${parcel_name}]+=$'\0'"${2//$'\0'/\\$'\0'}"
 }
 
-#FIXME: Document!
 function add_parcel_function() {
     # Since function names can contain any character including null, escape
     # nulls in such name.
@@ -172,7 +202,6 @@ function add_parcel_function() {
     ZESHY_PARCEL_NAME_TO_FUNCTION_NAMES[${parcel_name}]+=$'\0'"${2//$'\0'/\\$'\0'}"
 }
 
-#FIXME: Document!
 function add_parcel_global() {
     # Since global names can only contain identifier characters and hence *NOT*
     # null, nulls need not be escaped.
@@ -183,30 +212,52 @@ function add_parcel_global() {
 }
 
 # ....................{ DECLARERS                          }....................
+#FIXME: Rename this to declare_parcel_script() and likewise below. Then, have
+#such functions call a new declare_script() function, which should call a new
+#set_parcel() function. declare_parcel_script() should thus perform the expected
+#die_unless_file() routine. (See below.)
+#FIXME: Rename set_parcel() to set_parcel_script(). Then, define a new
+#set_parcel() function. For efficiency, set_parcel_script() should *NOT* call
+#set_parcel().
+
+#FIXME: Document!
 function declare_parcel() {
+    # Validate passed arguments. If such parcel has already been declared, throw
+    # an exception. Since parcels are typically associated with absolute paths,
+    # this shouldn't ever occur. Make sure it doesn't!
+    (( # == 2 )) || die 'expected one parcel name and one help string'
+    local  parcel_name="${1}" help="${2}"
+    die_if_parcel_name "${parcel_name}"
+
+    # If such name is not an absolute path (i.e., is either not prefixed by "/"
+    # or contains null characters), such name is not a valid parcel name; throw
+    # an exception! See @{parcel} for further details.
+    [[ "${parcel_name}" != '/'* || "${parcel_name}" == *$'\0'* ]] &&
+        die "parcel \"${parcel_name}\" invalid (i.e., not an absolute path)"
+
+    # Set the current parcel.
+    ZESHY_PARCEL_NAME="${parcel_name}"
+
+    # Map such parcel name to such help string.
+    ZESHY_PARCEL_NAME_TO_HELP[${parcel_name}]="${help}"
+}
+
+# ....................{ DECLARERS ~ script                 }....................
+#FIXME: Document!
+function declare_parcel_to_script() {
     # Validate passed arguments.
-    (( # == 1 | # == 2 )) ||
+    (( # == 1 || # == 2 )) ||
         die 'expected optional script name and one help string'
     local script_name="${ZESHY_SCRIPT_NAME}" help="${argv[-1]}"
     is_args_2 and script_name="${1}"
 
-    # Set the current parcel to such script. This internally converts such
-    # script to a parcel name, necessitating we subsequently use
-    # ${ZESHY_PARCEL_NAME} rather than ${script_name}.
-    set_parcel "${script_name}"
-
-    # If such parcel has already been declared, throw an exception. Since
-    # parcels are typically associated with unique paths, this should never
-    # happen. Make sure it doesn't! See is_map_key() for further details.
-    (( ${+ZESHY_PARCEL_NAME_TO_HELP[${ZESHY_PARCEL_NAME}]} )) and
-        die "parcel \"${ZESHY_PARCEL_NAME}\" already declared"
-
-    # Map such parcel name to such help string.
-    ZESHY_PARCEL_NAME_TO_HELP[${ZESHY_PARCEL_NAME}]="${help}"
+    # Declare such parcel as such script path, canonicalized to avoid ambiguity
+    # between parcels. See set_parcel_to_script() for further details.
+    declare_parcel "$(print -- "${script_name}"(:A))" "${help}"
 }
 
-function declare_parcel_with_stdin() {
-    run_runnable_with_stdin declare_parcel "${@}"
+function declare_parcel_to_script_with_stdin() {
+    run_runnable_with_stdin declare_parcel_to_script "${@}"
 }
 
 # ....................{ RUNNERS                            }....................
@@ -231,6 +282,26 @@ function run_runnable_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+    # Due to implementation details, avoid calling declare_parcel().
+    # Nonetheless, ensure this function implements similar logic.
+
+    # If such parcel has already been declared, throw an exception.
+#   die_if_parcel_name "${parcel_name}"
+
+    # Map such parcel name to such help string.
+#   ZESHY_PARCEL_NAME_TO_HELP[${parcel_name}]="${help}"
+
+    # Set the current parcel to such script. This internally converts such
+    # script to a parcel name, necessitating we subsequently use
+    # ${ZESHY_PARCEL_NAME} rather than ${script_name}.
+#   set_parcel_to_script "${script_name}"
+
+    # If such parcel has already been declared, throw an exception. Since
+    # parcels are typically associated with unique paths, this should never
+    # happen. Make sure it doesn't! See is_map_key() for further details.
+#   (( ${+ZESHY_PARCEL_NAME_TO_HELP[${parcel_name}]} )) and
+#       die "parcel \"${parcel_name}\" already declared"
+
 #FUXME: Shift all such adders as well as die_unless_parcel(), is_parcel(), and
 #whatever else we don't explicitly require here into new parcel "zsh/parcel".
     # Validate passed arguments.
@@ -268,14 +339,14 @@ function run_runnable_with_stdin() {
 #logically related units.
 # ....................{ DECLARERS                          }....................
 #declare_function_with_stdin <<'________________<heredoc?>________________'
-#void declare_parcel(string documentation)
+#void declare_parcel_to_script(string documentation)
 #
 #Declare the current shell script to be a new parcel documented with the passed
-#help string. See declare_parcel() for further details.
+#help string. See declare_parcel_to_script() for further details.
 #________________<heredoc?>________________
-#function declare_parcel() {
+#function declare_parcel_to_script() {
 #    (( # == 1 )) || die 'expected one help string'
-#    declare_parcel "${ZESHY_SCRIPT_NAME}" "${1}"
+#    declare_parcel_to_script "${ZESHY_SCRIPT_NAME}" "${1}"
 #}
 
 #FUXME: Are we not overthinking this? Why not simply rename "parcels" to
