Improved startup declaration handling.
Such handling now associates each alias, function, and global with the
parcel declaring such object. And it was good!

diff --git a/src/always/00-startup/00-declare/05-parcel b/src/always/00-startup/00-declare/05-parcel
--- a/src/always/00-startup/00-declare/05-parcel
+++ b/src/always/00-startup/00-declare/05-parcel
@@ -79,45 +79,130 @@
 #  I suppose we should give precedence to subdirectories rather than parent
 #  directories, yes? *sigh*
 
+# See @{global} and @{function} for help strings for all globals and functions
+# defined below, respectively.
+
 # ....................{ GLOBALS                            }....................
-# Global map from parcel names to the help strings documenting such parcels.
-# Avoid formally documenting such map, which zeshy precompilation subsequently
-# undefines to conserve space. See also the following lists specific to top-
-# level components, which precompilation converts into elements of related maps:
+# Map from parcel names to help strings documenting such parcels. Avoid formally
+# documenting such map, which zeshy precompilation subsequently undefines (to
+# conserve space). See also the following lists specific to top-level
+# components, which precompilation converts into elements of related maps:
 # ${ZESHY_CORE_HELP_ALIASES}, ${ZESHY_CORE_HELP_FUNCTIONS}, and
 # ${ZESHY_CORE_HELP_GLOBALS}.
 typeset -Ag ZESHY_PARCEL_NAME_TO_HELP
 
+#FIXME: Use!
+#FIXME: Document!
+# Map from parcel names to null-delimited string lists of all aliases,
+# functions, and globals declared by such parcel, respectively.
+typeset -Agx\
+    ZESHY_PARCEL_NAME_TO_ALIAS_NAMES\
+    ZESHY_PARCEL_NAME_TO_FUNCTION_NAMES\
+    ZESHY_PARCEL_NAME_TO_GLOBAL_NAMES
+
 # Current parcel name. Since the value of such global is typically specific to
 # the most recent zeshy script to have called declare_parcel(), avoid exporting
-# such global to caller scripts. See @{global} for such global's documentation.
-typeset -g ZESHY_PARCEL_NAME_CURRENT
+# such global to caller scripts.
+typeset -g ZESHY_PARCEL_NAME
+
+# ....................{ EXCEPTIONS                         }....................
+#FIXME: Document!
+function die_unless_parcel() {
+    (( # == 1 | # == 2 )) ||
+        die 'expected one parcel name and optional error message'
+    string parcel_name="${1}"
+    is_parcel "${parcel_name}" or
+        die "${2:-parcel \"${parcel_name}\" undeclared}"
+}
+
+# ....................{ TESTERS                            }....................
+#FIXME: Document!
+function is_parcel() {
+    (( # == 1 )) || die 'expected one parcel name'
+    (( ${+ZESHY_PARCEL_NAME_TO_HELP[${1}]} ))
+}
+
+# ....................{ GETTERS                            }....................
+#FIXME: Document!
+function get_parcel() {
+    # Validate passed arguments.
+    (( # == 0 )) || die 'expected no arguments'
+    print -r -- "${ZESHY_PARCEL_NAME}"
+}
+
+# ....................{ SETTERS                            }....................
+#FIXME: Use in "25-global"!
+#FIXME: Document!
+function set_parcel() {
+    # Validate passed arguments.
+    (( # == 1 )) || die 'expected one script name'
+    local script_name="${1}"
+    [[ -f "${script_name}" ]] || die "\"${script_name}\" not a zeshy script"
+
+    # Set the current parcel to such script, canonicalized to avoid ambiguity
+    # when cross-referencing parcels. See canonicalize_path() for details.
+    ZESHY_PARCEL_NAME="$(print -- "${script_name}"(:A))"
+}
+
+# ....................{ ADDERS                             }....................
+#FIXME: Document!
+#FIXME: Technically, suffix aliases reside in a separate namespace and hence
+#require separate handling. I can't really be bothered at the moment. Shouldn't
+#be a terribly difficult change; just keep it in mind. For simplicity and
+#orthogonality with nomenclature elsewhere, retain this function and simply add
+#a new function add_parcel_alias_suffix(). Note we'll probably want to add a new
+#subdirectory "15-alias/" containing the existing file "15-alias" and a new file
+#"suffix" containing new declare_alias_suffix() functions.
+function add_parcel_alias() {
+    # Since alias names can contain any character including null, escape nulls
+    # in such name. See define_alias() for further details.
+    (( # == 2 )) || die 'expected one parcel name and one alias name'
+    local parcel_name="${1}"
+    die_unless_parcel "${parcel_name}"
+    ZESHY_PARCEL_NAME_TO_ALIAS_NAMES[${parcel_name}]+=$'\0'"${2//$'\0'/\\$'\0'}"
+}
+
+#FIXME: Document!
+function add_parcel_function() {
+    # Since function names can contain any character including null, escape
+    # nulls in such name.
+    (( # == 2 )) || die 'expected one parcel name and one function name'
+    local parcel_name="${1}"
+    die_unless_parcel "${parcel_name}"
+    ZESHY_PARCEL_NAME_TO_FUNCTION_NAMES[${parcel_name}]+=$'\0'"${2//$'\0'/\\$'\0'}"
+}
+
+#FIXME: Document!
+function add_parcel_global() {
+    # Since global names can only contain identifier characters and hence *NOT*
+    # null, nulls need not be escaped.
+    (( # == 2 )) || die 'expected one parcel name and one global name'
+    local parcel_name="${1}"
+    die_unless_parcel "${parcel_name}"
+    ZESHY_PARCEL_NAME_TO_GLOBAL_NAMES[${parcel_name}]+=$'\0'"${2}"
+}
 
 # ....................{ DECLARERS                          }....................
-# See @{function} for help strings for all functions below.
-
 function declare_parcel() {
     # Validate passed arguments.
-    (( # == 2 )) || die 'expected one script name and one help string'
-    local script_name="${ZESHY_SCRIPT_NAME_CURRENT}" help="${argv[-1]}"
+    (( # == 1 | # == 2 )) ||
+        die 'expected optional script name and one help string'
+    local script_name="${ZESHY_SCRIPT_NAME}" help="${argv[-1]}"
     is_args_2 and script_name="${1}"
-    die_unless_file "${script_name}"
 
-    # If such path is relative, throw an exception. Permitting relative parcels
-    # invites ambiguity issues.
-    die_unless_path_absolute "${script_name}"
+    # Set the current parcel to such script. This internally converts such
+    # script to a parcel name, necessitating we subsequently use
+    # ${ZESHY_PARCEL_NAME} rather than ${script_name}.
+    set_parcel "${script_name}"
 
     # If such parcel has already been declared, throw an exception. Since
     # parcels are typically associated with unique paths, this should never
     # happen. Make sure it doesn't! See is_map_key() for further details.
-    (( ${+ZESHY_PARCEL_NAME_TO_HELP[${script_name}]} )) and
-        die "parcel \"${script_name}\" already declared"
+    (( ${+ZESHY_PARCEL_NAME_TO_HELP[${ZESHY_PARCEL_NAME}]} )) and
+        die "parcel \"${ZESHY_PARCEL_NAME}\" already declared"
 
     # Map such parcel name to such help string.
-    ZESHY_PARCEL_NAME_TO_HELP[${script_name}]="${help}"
-
-    # Set the current parcel to such name.
-    ZESHY_PARCEL_NAME_CURRENT="${script_name}"
+    ZESHY_PARCEL_NAME_TO_HELP[${ZESHY_PARCEL_NAME}]="${help}"
 }
 
 function declare_parcel_with_stdin() {
@@ -146,9 +231,33 @@ function run_runnable_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+#FUXME: Shift all such adders as well as die_unless_parcel(), is_parcel(), and
+#whatever else we don't explicitly require here into new parcel "zsh/parcel".
+    # Validate passed arguments.
+#   (( # == 2 )) || die 'expected one script name and one help string'
+#   local script_name="${ZESHY_SCRIPT_NAME}" help="${argv[-1]}"
+#   is_args_2 and script_name="${1}"
+#   die_unless_file "${script_name}"
+
+    # Canonicalize such path to avoid ambiguity when cross-referencing parcels.
+    # See canonicalize_path() for further details.
+#   script_name="$(print -- "${script_name}"(:A))"
+
+    # If such parcel has already been declared, throw an exception. Since
+    # parcels are typically associated with unique paths, this should never
+    # happen. Make sure it doesn't! See is_map_key() for further details.
+#   (( ${+ZESHY_PARCEL_NAME_TO_HELP[${script_name}]} )) and
+#       die "parcel \"${script_name}\" already declared"
+
+    # Map such parcel name to such help string.
+#   ZESHY_PARCEL_NAME_TO_HELP[${script_name}]="${help}"
+
+    # Set the current parcel to such name.
+#   ZESHY_PARCEL_NAME="${script_name}"
+
     #FUXME: O.K.; convert the script to a parcel name by stripping the prefix
     #corresponding to the current overlay root from such name. Again, we'll need
-    #a similar global to "${ZESHY_SCRIPT_NAME_CURRENT}" expanding to the
+    #a similar global to "${ZESHY_SCRIPT_NAME}" expanding to the
     #absolute path of the current overlay root. Simple!
     #FUXME: Set the current parcel, as well.
 
@@ -166,7 +275,7 @@ function run_runnable_with_stdin() {
 #________________<heredoc?>________________
 #function declare_parcel() {
 #    (( # == 1 )) || die 'expected one help string'
-#    declare_parcel "${ZESHY_SCRIPT_NAME_CURRENT}" "${1}"
+#    declare_parcel "${ZESHY_SCRIPT_NAME}" "${1}"
 #}
 
 #FUXME: Are we not overthinking this? Why not simply rename "parcels" to
