Completed initial parcel implementation.
Parcel documentation remains incomplete, I'm afraid.

diff --git a/src/always/00-startup/00-declare/05-parcel b/src/always/00-startup/00-declare/05-parcel
--- a/src/always/00-startup/00-declare/05-parcel
+++ b/src/always/00-startup/00-declare/05-parcel
@@ -111,7 +111,7 @@ typeset -Agx\
 #desired (since the empty string is not an existing parcel -- hopefully, anyway!).
 
 # Current parcel name. Since the value of such global is typically specific to
-# the most recent zeshy script to have called declare_parcel_to_script(), avoid exporting
+# the most recent zeshy script to have called declare_parcel_as_script(), avoid exporting
 # such global to caller scripts.
 typeset -g ZESHY_PARCEL_NAME
 
@@ -137,6 +137,81 @@ function is_parcel() {
     # See is_map_key() for further details.
     (( # == 1 )) || die 'expected one parcel name'
     (( ${+ZESHY_PARCEL_NAME_TO_HELP[${1}]} ))
+}
+
+# ....................{ SETTERS                            }....................
+#FIXME: declare_parcel_as_script() should call this function. WAIT. No. Full
+#stop. We need a new convert_script_to_parcel() function. (I know, I know.) Just
+#go gonzo, yo!
+#FIXME: Shift documentation to "10-function".
+declare_function_with_stdin <<'-\-'
+string convert_path_to_parcel(string pathname)
+
+Convert the passed existing absolute or relative path to the parcel name
+corresponding to such path. If such path does _not_ exist, an exception is
+thrown. Relative paths will be converted to absolute paths. Symbolic link path
+components will be replaced with their transitive targets. If such path begins
+with an overlay directory, such system-specific directory will be replaced with
+a system-agnostic parcel scheme as discussed below (e.g., from
+`/usr/share/zeshy/always/zsh/zsh` to `zeshy://always/zsh/zsh`).
+
+All `zeshy` scripts reside in one of two `zeshy` overlays:
+
+* ${ZESHY_OVERLAY_DIR}, the system-wide overlay of official scripts.
+* ${ZESHY_USER_OVERLAY_DIR}, the user-specific overlay of third-party scripts.
+
+In either case, the overlay directories prefixing script paths are system-
+specific. For portability, this function replaces such prefixes with the
+following system-agnostic schemes:
+
+* `zeshy://`, for paths prefixed by ${ZESHY_OVERLAY_DIR}.
+* `zeshy.user://`, for paths prefixed by ${ZESHY_USER_OVERLAY_DIR}.
+
+For example:
+
+.convert_path_to_parcel()
+==========================================
+[source]
+------------------------------------------
+>>> set_dir "${ZESHY_OVERLAY_DIR}"
+>>> convert_path_to_parcel "is_pathable/mutt"
+zeshy://is_pathable/mutt
+>>> convert_path_to_parcel "${ZESHY_OVERLAY_DIR}/is_pathable/mutt"
+zeshy://is_pathable/mutt
+>>> convert_path_to_parcel "${ZESHY_USER_OVERLAY_DIR}/is_pathable/awesome"
+zeshy.user://is_pathable/awesome
+------------------------------------------
+==========================================
+-\-
+function convert_path_to_parcel() {
+    # Validate passed arguments.
+    (( # == 1 )) || die 'expected one pathname'
+    local parcel_name="${1}"
+    [[ -e "${parcel_name}" ]] || die "\"${parcel_name}\" not found"
+
+    # Canonicalize such path. See canonicalize_path() for further details.
+    parcel_name="$(print -r -- "${parcel_name}"(:A))"
+
+    # Replace system-specific overlay prefixes with system-agnostic labels.
+    # Note the lack of an "else" branch in the logic below. If such parcel is a
+    # symbolic link to a script physically residing outside of a zeshy overlay,
+    # both of the branches below fail. This is hardly ideal (due to portability
+    # issues) but currently ignorable. Since most parcels reside in the system-
+    # wide overlay, attempt to match such overlay first. Dismantled, this is:
+    #
+    # * "(#b)(*)", matching the fragment of such path following the unmatched
+    #   directory of the overlay containing such path into ${match[1]}.
+        if [[ parcel_name == "${ZESHY_OVERLAY_DIR}"(#b)(*) ]] {
+        parcel_name="zeshy://${match[1]}"
+    } elif [[ parcel_name == "${ZESHY_USER_OVERLAY_DIR}"(#b)(*) ]] {
+        parcel_name="zeshy.user://${match[1]}"
+    }
+
+    # If such parcel does not exist, throw an exception.
+    die_unless_parcel "${parcel_name}"
+
+    # Else, set the current parcel to such parcel.
+    ZESHY_PARCEL_NAME="${parcel_name}"
 }
 
 # ....................{ ADDERS                             }....................
@@ -175,7 +250,6 @@ function add_parcel_global() {
 }
 
 # ....................{ DECLARERS                          }....................
-#FIXME: Document!
 function declare_parcel() {
     # Validate passed arguments. If such parcel has already been declared, throw
     # an exception. Since parcels are typically associated with absolute paths,
@@ -185,8 +259,8 @@ function declare_parcel() {
     die_if_parcel "${parcel_name}"
 
     # If such name is not an absolute path (i.e., is either not prefixed by "/"
-    # or contains null characters), such name is not a valid parcel name; throw
-    # an exception! See @{parcel} for further details.
+    # or contains null characters), such name is invalid as a parcel name, so
+    # throw an exception. See documentation for further details.
     [[ "${parcel_name}" != '/'* || "${parcel_name}" == *$'\0'* ]] &&
         die "parcel \"${parcel_name}\" invalid (i.e., not an absolute path)"
 
@@ -198,22 +272,21 @@ function declare_parcel() {
 }
 
 # ....................{ DECLARERS ~ script                 }....................
-#FIXME: Rename "parcel_to_script" to "parcel_as_script" everywhere.
 #FIXME: Document!
-function declare_parcel_to_script() {
+function declare_parcel_as_script() {
     # Validate passed arguments.
     (( # == 1 || # == 2 )) ||
         die 'expected optional script name and one help string'
     local script_name="${ZESHY_SCRIPT_NAME}" help="${argv[-1]}"
     is_args_2 and script_name="${1}"
 
-    # Declare such parcel as such script path, canonicalized to avoid ambiguity
-    # between parcels. See set_parcel_to_script() for further details.
-    declare_parcel "$(print -- "${script_name}"(:A))" "${help}"
+    # Convert from the absolute path of such script to a parcel name and declare
+    # such parcel with such documentation.
+    declare_parcel "$(convert_path_to_parcel "${script_name}")" "${help}"
 }
 
-function declare_parcel_to_script_with_stdin() {
-    run_runnable_with_stdin declare_parcel_to_script "${@}"
+function declare_parcel_as_script_with_stdin() {
+    run_runnable_with_stdin declare_parcel_as_script "${@}"
 }
 
 # ....................{ RUNNERS                            }....................
@@ -238,101 +311,44 @@ function run_runnable_with_stdin() {
 }
 
 # ....................{ DOCUMENTERS                        }....................
-declare_parcel_to_script_with_stdin <<'-\-'
-Handle *parcel* (i.e., a `zeshy`-specific abstraction encapsulating all aliases,
-globals, and functions declared by a `zeshy` script) declarers. See
-declare_parcel() for further details.
-
-While most high-
-level languages provide native support for declaring such abstractions (e.g.,
-`perl` packages, `python` modules, `ruby` gems), `zsh` does not. Even if `zsh`
-did, however, `zeshy`\'s compilation into unstructured digest files would likely
-render such abstractions moot. Hence, the necessity of a `zeshy`-specific
-abstraction allowing for such compilation.
-
-Parcels implement a useful (if limited) pure-`zsh` facsimile of the typical
-package motif, aggregating logically related `zsh` objects into abstract units.
-Under most high-level languages, such units form a language-specific topology
-of both reusable components (for programming purposes) and exportable
-documentation (for specification purposes). Under `zsh`, however, only the
-latter applies. Since `zsh` digest files dispense with structure (and hence
-reusable components), parcels principally form a `zsh`-specific topology of
-documentation -- both offline and on.
-
-== Parcel Names ==
-
-All parcel names are *absolute paths* (i.e., prefixed and internally delimited
-by the directory separator '/' and containing no null characters). Since parcels
-are abstractions, such paths need _not_ actually exist. Assuming the customary
-one-to-one relationship between parcels and scripts
-<<parcel.relations.1to1,documented below>>, however, each parcel name is the
-absolute path of the existing shell script declaring such parcel.
-
-== Parcel-script Relationships ==
-
-Parcels are abstractions related to but _not_ necessarily synonymous with the
-physical `zeshy` scripts declaring such parcels.
-
-[[parcel.relations.1to1]]
-=== One-to-one Parcel-script Relationships ===
-
-There typically exists a one-to-one relationship between parcels and scripts.
-For each such script, there exists a corresponding parcel whose name is the
-absolute path of such script -- both guaranteeing uniqueness between parcel
-names and establishing a convenient means of associating parcels with scripts.
-With such relationships, a script's absolute path identifies its parcel and a
-parcel's name its script's absolute path.
-
-To implement such relationship, such scripts should call a *parcel declarer*
-(e.g., declare_parcel_to_script(), declare_parcel_script_with_stdin()) before calling any
-other declarers (e.g., declare_alias(), declare_function_with_stdin()).
-
-=== One-to-many Parcel-script Relationships ===
-
-A one-to-many relationship between parcels and scripts, in which one parcel is
-distributed across multiple scripts (hereafter referred to as the *swarm* of
-scripts declaring and defining such parcel), is also feasible. As with aliases,
-functions, and variables, parcels are typically only declared once. Hence, for
-one script in each such swarm, there exists a corresponding parcel whose name
-is the absolute path of such script. All other scripts in such swarm non-
-ambiguously refer to such parcel by such path.
-
-To implement such relationship, the declaring script in such swarm should call
-a parcel declarer before calling any parcel-specific declarers. All other
-scripts in such swarm should call a *parcel setter* (e.g., set_parcel(),
-set_parcel_script()) before calling any parcel-specific declarers.
-
-=== Many-to-one Parcel-script Relationships ===
-
-A many-to-one relationship between parcels and scripts, in which multiple
-parcels (hereafter referred to as the *passel* of parcels being declared and
-defined) are centralized into one script, is also feasible. For each such
-script, there exist multiple corresponding parcels. To guarantee uniqueness
-between parcel names, only one such parcel name may be the absolute path of
-such script. All other parcel names in such passel must be arbitrary (probably
-nonextant) absolute paths (e.g., by appending arbitrary integers to the path of
-such script).
-
-To implement such relationship, such script should be internally subdivided into
-such parcels, calling a parcel declarer for each such parcel before calling all
-declarers specific to such parcel.
-
-=== Many-to-many Parcel-script Relationships ===
-
-Lastly, a many-to-many relationship between parcels and scripts, in which
-multiple parcels are distributed across multiple scripts, is also feasible.
-Since such relationships blend one-to-many and many-to-one relationships, see
-prior sections for further details. (Given the subtle complexities of such
-relationships, many-to-many parcel-script relationships are rather uncommon.)
-
-=== Parcel-script Relationships in zeshy ===
-
-Since one-to-one relationships tend to conform more closely to user expectations
-than one-to-many, many-to-one, or many-to-many relationships, all scripts in the
-`zeshy` codebase declare and define exactly one parcel.
+declare_parcel_as_script_with_stdin <<'-\-'
+Handle parcel declarers. See declare_parcel() for further details.
 -\-
 
 # --------------------( WASTELANDS                         )--------------------
+#FUXME: O.K.; we don't actually require this here. Shift to "zeshy/parcel" and
+#shift its documentation (currently in "10-function") with it. Huzzah!
+    # Convert
+#   parcel_name=
+
+    # Since the implementation below fails to cleanly integrate with that of
+    # declare_parcel(), reimplement rather than call such function.
+    #
+    # Map such parcel name to such help string *BEFORE* calling
+    # set_parcel_as_script(), which throws an exception if this is not the case.
+#   ZESHY_PARCEL_NAME_TO_HELP[${parcel_name}]="${help}"
+
+    # Set the current parcel to such parcel.
+#   set_parcel_as_script "${parcel_name}"
+
+    # Declare such parcel as such script path, canonicalized to avoid ambiguity
+    # between parcels. See set_parcel_as_script() for further details.
+#is absolute (e.g., `/usr/src/zeshy/always/os/os`), such path need _not_
+#exist. Otherwise
+    # Declare such parcel as such script path, canonicalized to avoid ambiguity
+    # between parcels. See set_parcel_as_script() for further details.
+#   declare_parcel "$(print -- "${script_name}"(:A))" "${help}"
+
+#FUXME: Rename "parcel_as_script" to "parcel_as_script" everywhere.
+#FUXME: Fairly important: shift set_parcel() back here and augment such function
+#to replace ${ZESHY_OVERLAY_DIR} and ${ZESHY_USER_OVERLAY_DIR} when prefixing
+#parcel names with "/zeshy/" and "/user/" prefixes, respectively.
+#the directory of the overlay containing the passed script
+#with a system-agnostic label indicating the overlay:
+#FUXME: Yes, in hindsight, we probably want a separate string global
+#${ZESHY_OVERLAY_DIR}, currently initialized to just ${ZESHY_HOME}. It's easy to
+#conceive of scenarios in which such directory is a ${ZESHY_HOME} subdirectory,
+#justifying such choice.
 #documentation.
 #While parcels have no bearing 
 #Since digest files `zeshy`\'s user digest files 
@@ -363,7 +379,7 @@ than one-to-many, many-to-one, or many-to-many relationships, all scripts in the
     # Set the current parcel to such script. This internally converts such
     # script to a parcel name, necessitating we subsequently use
     # ${ZESHY_PARCEL_NAME} rather than ${script_name}.
-#   set_parcel_to_script "${script_name}"
+#   set_parcel_as_script "${script_name}"
 
     # If such parcel has already been declared, throw an exception. Since
     # parcels are typically associated with unique paths, this should never
@@ -408,14 +424,14 @@ than one-to-many, many-to-one, or many-to-many relationships, all scripts in the
 #logically related units.
 # ....................{ DECLARERS                          }....................
 #declare_function_with_stdin <<'-\-'
-#void declare_parcel_to_script(string documentation)
+#void declare_parcel_as_script(string documentation)
 #
 #Declare the current shell script to be a new parcel documented with the passed
-#help string. See declare_parcel_to_script() for further details.
+#help string. See declare_parcel_as_script() for further details.
 #-\-
-#function declare_parcel_to_script() {
+#function declare_parcel_as_script() {
 #    (( # == 1 )) || die 'expected one help string'
-#    declare_parcel_to_script "${ZESHY_SCRIPT_NAME}" "${1}"
+#    declare_parcel_as_script "${ZESHY_SCRIPT_NAME}" "${1}"
 #}
 
 #FUXME: Are we not overthinking this? Why not simply rename "parcels" to
