Corrected numerous regressions.
While zeshy remains moderately broken, the tide is surely (if not
entirely swiftly) shifting.

diff --git a/src/always/00-startup/00-declare/05-parcel b/src/always/00-startup/00-declare/05-parcel
--- a/src/always/00-startup/00-declare/05-parcel
+++ b/src/always/00-startup/00-declare/05-parcel
@@ -119,16 +119,16 @@ typeset -g ZESHY_PARCEL_NAME
 function die_if_parcel() {
     (( # == 1 || # == 2 )) ||
         die 'expected one parcel name and optional error message'
-    string parcel_name="${1}"
-    is_parcel "${parcel_name}" and
+    local parcel_name="${1}"
+    is_parcel "${parcel_name}" &&
         die "${2:-parcel \"${parcel_name}\" already declared}"
 }
 
 function die_unless_parcel() {
     (( # == 1 || # == 2 )) ||
         die 'expected one parcel name and optional error message'
-    string parcel_name="${1}"
-    is_parcel "${parcel_name}" or
+    local parcel_name="${1}"
+    is_parcel "${parcel_name}" ||
         die "${2:-parcel \"${parcel_name}\" undeclared}"
 }
 
@@ -140,49 +140,33 @@ function is_parcel() {
 }
 
 # ....................{ SETTERS                            }....................
-#FIXME: declare_parcel_as_script() should call this function. WAIT. No. Full
-#stop. We need a new convert_script_to_parcel() function. (I know, I know.) Just
-#go gonzo, yo!
-#FIXME: Shift documentation to "10-function".
-declare_function_with_stdin <<'-\-'
-string convert_path_to_parcel(string pathname)
+# To avoid tiresome timing issues, such functions are not called by this parcel
+# Since such functions are called by top-level parcel "global", they cannot be
+# relegated to "always/zeshy/parcel".
 
-Convert the passed existing absolute or relative path to the parcel name
-corresponding to such path. If such path does _not_ exist, an exception is
-thrown. Relative paths will be converted to absolute paths. Symbolic link path
-components will be replaced with their transitive targets. If such path begins
-with an overlay directory, such system-specific directory will be replaced with
-a system-agnostic parcel scheme as discussed below (e.g., from
-`/usr/share/zeshy/always/zsh/zsh` to `zeshy://always/zsh/zsh`).
+function set_parcel() {
+    # Validate passed arguments.
+    (( # == 1 )) || die 'expected one parcel name'
+    local parcel_name="${1}"
+    die_unless_parcel "${parcel_name}"
 
-All `zeshy` scripts reside in one of two `zeshy` overlays:
+    # Set such parcel.
+    ZESHY_PARCEL_NAME="${parcel_name}"
+}
 
-* ${ZESHY_OVERLAY_DIR}, the system-wide overlay of official scripts.
-* ${ZESHY_USER_OVERLAY_DIR}, the user-specific overlay of third-party scripts.
+function set_parcel_as_script() {
+    # Validate passed arguments.
+#   print -r -- "args: ${*}"
+    (( # == 1 )) || die 'expected one parcel name'
+    local script_name="${1}" parcel_name
+    [[ -f "${script_name}" ]] || die "\"${script_name}\" not a script"
 
-In either case, the overlay directories prefixing script paths are system-
-specific. For portability, this function replaces such prefixes with the
-following system-agnostic schemes:
+    # Set the current parcel to the absolute path of such script converted into
+    # a parcel name.
+    set_parcel "$(convert_path_to_parcel "${script_name}")"
+}
 
-* `zeshy://`, for paths prefixed by ${ZESHY_OVERLAY_DIR}.
-* `zeshy.user://`, for paths prefixed by ${ZESHY_USER_OVERLAY_DIR}.
-
-For example:
-
-.convert_path_to_parcel()
-==========================================
-[source]
-------------------------------------------
->>> set_dir "${ZESHY_OVERLAY_DIR}"
->>> convert_path_to_parcel "is_pathable/mutt"
-zeshy://is_pathable/mutt
->>> convert_path_to_parcel "${ZESHY_OVERLAY_DIR}/is_pathable/mutt"
-zeshy://is_pathable/mutt
->>> convert_path_to_parcel "${ZESHY_USER_OVERLAY_DIR}/is_pathable/awesome"
-zeshy.user://is_pathable/awesome
-------------------------------------------
-==========================================
--\-
+# ....................{ CONVERTERS                         }....................
 function convert_path_to_parcel() {
     # Validate passed arguments.
     (( # == 1 )) || die 'expected one pathname'
@@ -207,11 +191,8 @@ function convert_path_to_parcel() {
         parcel_name="zeshy.user://${match[1]}"
     }
 
-    # If such parcel does not exist, throw an exception.
-    die_unless_parcel "${parcel_name}"
-
-    # Else, set the current parcel to such parcel.
-    ZESHY_PARCEL_NAME="${parcel_name}"
+    # Return such parcel.
+    print -r -- "${parcel_name}"
 }
 
 # ....................{ ADDERS                             }....................
@@ -223,30 +204,48 @@ function convert_path_to_parcel() {
 #subdirectory "15-alias/" containing the existing file "15-alias" and a new file
 #"suffix" containing new declare_alias_suffix() functions.
 function add_parcel_alias() {
-    # Since alias names can contain any character including null, escape nulls
-    # in such name. See define_alias() for further details.
+    # Validate passed arguments. Since alias names can contain any character and
+    # hence null used below to delimit alias names, escape nulls in such name.
+    # See define_alias() for further details.
     (( # == 2 )) || die 'expected one parcel name and one alias name'
-    local parcel_name="${1:-${ZESHY_PARCEL_NAME}}"
-    die_unless_parcel "${parcel_name}"
-    ZESHY_PARCEL_NAME_TO_ALIAS_NAMES[${parcel_name}]+=$'\0'"${2//$'\0'/\\$'\0'}"
+    local parcel_name__apa="${1}" alias_name__apa="${2//$'\0'/\\$'\0'}"
+    die_unless_parcel "${parcel_name__apa}"
+
+    # If this is the first alias to be added to such parcel, initialize such
+    # list to simply this alias.
+    if (( ${+ZESHY_PARCEL_NAME_TO_ALIAS_NAMES[${parcel_name__apa}]} )) {
+        ZESHY_PARCEL_NAME_TO_ALIAS_NAMES[${parcel_name__apa}]="${alias_name__apa}"
+    # Else, at least one alias has already been added to such parcel. Delimit
+    # this alias from prior aliases with a null.
+    } else {
+        ZESHY_PARCEL_NAME_TO_ALIAS_NAMES[${parcel_name__apa}]+=$'\0'"${alias_name__apa}"
+    }
 }
 
 function add_parcel_function() {
-    # Since function names can contain any character including null, escape
-    # nulls in such name.
+    # See add_parcel_alias() for further details.
     (( # == 2 )) || die 'expected one parcel name and one function name'
-    local parcel_name="${1:-${ZESHY_PARCEL_NAME}}"
-    die_unless_parcel "${parcel_name}"
-    ZESHY_PARCEL_NAME_TO_FUNCTION_NAMES[${parcel_name}]+=$'\0'"${2//$'\0'/\\$'\0'}"
+    local parcel_name__apf="${1}" function_name__apf="${2//$'\0'/\\$'\0'}"
+    die_unless_parcel "${parcel_name__apf}"
+    if (( ${+ZESHY_PARCEL_NAME_TO_FUNCTION_NAMES[${parcel_name__apf}]} )) {
+        ZESHY_PARCEL_NAME_TO_FUNCTION_NAMES[${parcel_name__apf}]="${function_name__apf}"
+    } else {
+        ZESHY_PARCEL_NAME_TO_FUNCTION_NAMES[${parcel_name__apf}]+=$'\0'"${function_name__apf}"
+    }
 }
 
 function add_parcel_global() {
     # Since global names can only contain identifier characters and hence *NOT*
-    # null, nulls need not be escaped.
+    # null, nulls need not be escaped. See add_parcel_alias() for further
+    # details.
     (( # == 2 )) || die 'expected one parcel name and one global name'
-    local parcel_name="${1:-${ZESHY_PARCEL_NAME}}"
-    die_unless_parcel "${parcel_name}"
-    ZESHY_PARCEL_NAME_TO_GLOBAL_NAMES[${parcel_name}]+=$'\0'"${2}"
+    local parcel_name__apg="${1}" global_name__apg="${2}"
+    die_unless_parcel "${parcel_name__apg}"
+    if (( ${+ZESHY_PARCEL_NAME_TO_GLOBAL_NAMES[${parcel_name__apg}]} )) {
+        ZESHY_PARCEL_NAME_TO_GLOBAL_NAMES[${parcel_name__apg}]="${global_name__apg}"
+    } else {
+        ZESHY_PARCEL_NAME_TO_GLOBAL_NAMES[${parcel_name__apg}]+=$'\0'"${global_name__apg}"
+    }
 }
 
 # ....................{ DECLARERS                          }....................
@@ -258,11 +257,10 @@ function declare_parcel() {
     local  parcel_name="${1}" help="${2}"
     die_if_parcel "${parcel_name}"
 
-    # If such name is not an absolute path (i.e., is either not prefixed by "/"
-    # or contains null characters), such name is invalid as a parcel name, so
-    # throw an exception. See documentation for further details.
-    [[ "${parcel_name}" != '/'* || "${parcel_name}" == *$'\0'* ]] &&
-        die "parcel \"${parcel_name}\" invalid (i.e., not an absolute path)"
+    # If such name is not a path (i.e., contains null characters), throw an
+    # exception. See documentation for further details.
+    [[ "${parcel_name}" == *$'\0'* ]] &&
+        die "parcel name \"${parcel_name}\" not a path (due to embedded null characters)"
 
     # Set the current parcel. See set_parcel() for further details.
     ZESHY_PARCEL_NAME="${parcel_name}"
@@ -272,13 +270,13 @@ function declare_parcel() {
 }
 
 # ....................{ DECLARERS ~ script                 }....................
-#FIXME: Document!
 function declare_parcel_as_script() {
     # Validate passed arguments.
     (( # == 1 || # == 2 )) ||
         die 'expected optional script name and one help string'
     local script_name="${ZESHY_SCRIPT_NAME}" help="${argv[-1]}"
-    is_args_2 and script_name="${1}"
+    (( # == 2 )) && script_name="${1}"
+    [[ -f "${script_name}" ]] || die "\"${script_name}\" not a script"
 
     # Convert from the absolute path of such script to a parcel name and declare
     # such parcel with such documentation.
@@ -296,7 +294,7 @@ function run_runnable_with_stdin() {
     (( # == 1 )) || die 'expected one function name'
     read -t 0 || die 'standard input empty'
     local function_name__rrws="${1}"
-    shift_arg
+    shift
 
     # Unless such function exists, throw an exception. See is_runnable() for
     # further details.
@@ -316,6 +314,21 @@ Handle parcel declarers. See declare_parcel() for further details.
 -\-
 
 # --------------------( WASTELANDS                         )--------------------
+# If such name is not an absolute path (i.e., is
+    # either not prefixed by "/" or contains null characters), such name is
+    # invalid as a parcel name, so throw an exception. See @{parcel} for further
+    # details.
+    # If such parcel does not exist, throw an exception.
+#   die_unless_parcel "${parcel_name}"
+
+    # Else, set the current parcel to such parcel.
+#   ZESHY_PARCEL_NAME="${parcel_name}"
+#FUXME: declare_parcel_as_script() should call this function. WAIT. No. Full
+#stop. We need a new convert_script_to_parcel() function. (I know, I know.) Just
+#go gonzo, yo!
+#is either not prefixed by "/" or 
+#   [[ "${parcel_name}" != '/'* || "${parcel_name}" == *$'\0'* ]] &&
+#       die "parcel \"${parcel_name}\" invalid (i.e., not an absolute path)"
 #FUXME: O.K.; we don't actually require this here. Shift to "zeshy/parcel" and
 #shift its documentation (currently in "10-function") with it. Huzzah!
     # Convert
