Improved parcel "00-declare/15-alias".
In particular, declare_alias() now accepts an optional alias expansion
to initialize such alias to. Corrected numerous startup regressions,
such that zeshy now actually starts up with a reasonable facsimile of
prior working functionality. "It's been a long day, folks."

diff --git a/src/always/00-startup/00-declare/15-alias b/src/always/00-startup/00-declare/15-alias
--- a/src/always/00-startup/00-declare/15-alias
+++ b/src/always/00-startup/00-declare/15-alias
@@ -61,20 +61,76 @@ typeset -Ag ZESHY_ALIAS_NAME_TO_HELP
 
 # ....................{ DECLARERS                          }....................
 declare_function_with_stdin <<'/---'
-void declare_alias(string documentation)
+void declare_alias(
+    string alias_prototype = "",
+    string alias_expansion = "",
+    string documentation)
 
-Declare the alias named by the alias prototype prefixing the passed help string
-to be contained by the current parcel and documented by such string. Alias help
-strings consist of:
+Declare the specified alias to be contained by the current parcel and documented
+by the passed help string, where such alias is specified by either:
 
-. An *alias prototype* in `zeshy`-specific C-like syntax consisting of one or
-  more alias return types, one alias name, and zero or more alias arguments
-  (e.g., `string the_parable_of_the_box(integer derrick, character jensen)`).
+* The passed alias prototype, if such argument is passed.
+* The alias prototype prefixing the passed help string, otherwise.
+
+If an alias expansion is passed, define such alias to expand to such string;
+else, such alias must be subsequently defined: e.g,
+
+.declare_alias()
+==========================================
+[source]
+------------------------------------------
+>>> declare_alias "string on_activism(void)" 'print_string\
+...    "It is not enough to fight for the land; it is even more important to
+...     enjoy it. While you can. While it's still here. So get out there and
+...     hunt and fish and mess around with your friends, ramble out yonder and
+...     explore the forests, climb the mountains, bag the peaks, run the rivers,
+...     breathe deep of that yet sweet and lucid air, sit quietly for a while
+...     and contemplate the precious stillness, the lovely, mysterious, and
+...     awesome space."\
+...    "Enjoy yourselves, keep your brain in your head and your head firmly
+...     attached to the body, the body active and alive, and I promise you this
+...     much; I promise you this one sweet victory over our enemies, over those
+...     desk-bound men and women with their hearts in a safe deposit box, and
+...     their eyes hypnotized by desk calculators. I promise you this; You will
+...     outlive the bastards."
+>>> declare_alias\
+...    "string on_purpose(void)
+...
+...     But the profoundest implications of the decreased work week were
+...     philosophical and ecological: mankind, the Ecotopians assumed, was not
+...     meant for production, as the 19th and 20th centuries believed. Instead,
+...     humans were meant to take their modest place in the seamless, stable-
+...     state web of living organisms, disturbing that web as little as
+...     possible. This would mean sacrifice of present consumption, but it would
+...     ensure future survival."
+>>> alias on_purpose='print_string\
+...    "People were to be happy not to the extent they dominated their fellow
+...     creatures on the earth, but to the extent they lived in balance with
+...     them. As a basic philosophy, the idea of political power is to put
+...     technology and social structure at the service of humankind, rather than
+...     the other way around."'
+>>> get_string_line "$(on_activism)" 1
+It is not enough to fight for the land; it is even more important to
+>>> get_string_line "$(on_purpose)" -1
+the other way around.
+------------------------------------------
+==========================================
+
+== Alias Documentation ==
+
+Alias help strings consist of:
+
+. An optional *alias prototype* in `zeshy`-specific C-like syntax consisting of
+  one or more alias return types, one alias name, and zero or more alias
+  arguments (e.g.,
+  `string the_parable_of_the_box(integer derrick, character jensen)`), if such
+  prototype was _not_ passed as an argument already.
 . An *alias description* in http://asciidoc.org[AsciiDoc] syntax, augmented with
-  `zeshy`-specific markup for cross-referencing other `zeshy` documentation.
-  (e.g., `The *box* is +full+ of salmon, and a *man* sits +atop+ the box.`)
-
-== Alias Documentation Grammar ==
+  `zeshy`-specific markup for cross-referencing other `zeshy` documentation
+  (e.g., `The *box* is +full+ of salmon, and a *man* sits +atop+ the box.`).
+  Since single- and double-quoted `zsh` string syntax conflicts with such syntax,
+  consider passing such description to declare_alias_with_stdin() as a
+  here-document on standard input instead.
 
 For completeness, we specify such syntax as a
 http://en.wikipedia.org/wiki/Parsing_expression_grammar[Parser Expression Grammar (PEG)].
@@ -171,19 +227,43 @@ alias set_args_to_string_split_on_words_from='
 /---
 function declare_alias() {
     # Validate passed arguments.
-    (( # == 1 )) || die 'expected one help string'
-    local help__da="${1}"
+    (( # == 1 || # == 3 )) || die\
+        'expected either one help string or one alias prototype, one alias expansion, and one help string'
+    local help__da="${argv[-1]}"\
+        alias_prototype__da alias_expansion__da alias_name__da
 
-    # Unless such string matches the function help PCRE, throw an exception.
-    [[ "${help__da}" =~\
-       "${ZESHY_HELP_PCRE_ALIAS_PROTOTYPE_NAME}" ]] ||
-        die_for_declarator_type_with_help 'alias' "${help__da}"
-#   for ((match_index=1; match_index <= ${#match}; ++match_index)) {
-#       print "match ${match_index}: ${match[${match_index}]}"
-#   }
+    # If passed an alias prototype and expansion and help string, localize such
+    # arguments. As this is the common case, handle this condition first.
+    if (( # == 3 )) {
+        # Localize such arguments.
+        alias_prototype__da="${1}"
+        alias_expansion__da="${2}"
 
-    # Alias name matched from such string.
-    local alias_name__da="${match[1]}"
+        # Prepend such help string with such alias prototype.
+        help__da="${alias_prototype__da}"$'\n\n'"${help__da}"
+
+        # Match the alias name from such prototype prefixing such string or
+        # throw an exception if such match fails.
+        [[ "${alias_prototype__da}" =~\
+           "${ZESHY_HELP_PCRE_ALIAS_PROTOTYPE_NAME}" ]] ||
+            die_for_declarator_type_with_help 'alias' "${help__da}"
+
+        # Localize such alias name.
+        alias_name__da="${match[1]}"
+
+        # Define such alias.
+        define_alias "${alias_name__da}" "${alias_expansion__da}"
+    # Else, only a help string was passed.
+    } else {
+        # Match the alias name from the alias prototype prefixing such string or
+        # throw an exception if such match fails.
+        [[ "${help__da}" =~\
+           "${ZESHY_HELP_PCRE_ALIAS_PROTOTYPE_NAME}" ]] ||
+            die_for_declarator_type_with_help 'alias' "${help__da}"
+
+        # Localize such alias name.
+        alias_name__da="${match[1]}"
+    }
 
     # Map such alias to such help string.
     ZESHY_ALIAS_NAME_TO_HELP[${alias_name__da}]="${help__da}"
@@ -193,15 +273,17 @@ function declare_alias() {
 }
 
 declare_function_with_stdin <<'/---'
-void declare_alias_with_stdin[stdin: string documentation]
+void declare_alias_with_stdin[
+    args: (string alias_prototype = "",
+           string alias_expansion = ""),
+    stdin: string documentation]
 
-Set the documentation for the alias named by the variable declaration prefixing
-standard input to such input. Consider calling this rather than declare_alias(),
-which requires passing a string argument rather than standard input. See
-declare_function_with_stdin() for further details.
+Declare the specified alias to be contained by the current parcel and documented
+by the passed help string, where such alias is specified as under
+declare_alias(). See declare_function_with_stdin() for further details.
 /---
 function declare_alias_with_stdin() {
-    run_runnable_with_stdin declare_alias
+    run_runnable_with_stdin declare_alias "${@}"
 }
 
 # ....................{ DEFINERS                           }....................
@@ -226,7 +308,7 @@ hence is neither intuitive or safe. This function amends this: e.g.,
 ...     Ministry of Propaganda is the Ministry of Explanation. The idea being
 ...     that our position on everything is so obviously correct that if we only
 ...     explain it to people, they will see that it is right."'
->>> get_line $("propaganda = explanation") -1
+>>> get_string_line $("propaganda = explanation") -1
 explain it to people, they will see that it is right.
 ------------------------------------------
 ==========================================
@@ -268,6 +350,21 @@ filetype is in command position).
 alias alias_suffix="alias -s"
 
 # --------------------( WASTELANDS                         )--------------------
+#Set the documentation for the alias named by the variable declaration prefixing
+#standard input to such input. Consider calling this rather than declare_alias(),
+#which requires passing a string argument rather than standard input. See
+#declare_function_with_stdin() for further details.
+        #FUXME: This could probably be generalized to support "="-delimited
+        #assignment, but I have doubts as to whether that'd be widely useful.
+
+    # Unless such string matches the function help PCRE, throw an exception.
+#   [[ "${help__da}" =~\
+#      "${ZESHY_HELP_PCRE_ALIAS_PROTOTYPE_NAME}" ]] ||
+#       die_for_declarator_type_with_help 'alias' "${help__da}"
+#   for ((match_index=1; match_index <= ${#match}; ++match_index)) {
+#       print "match ${match_index}: ${match[${match_index}]}"
+#   }
+
 #Set the documentation for the alias named by the alias prototype prefixing the
 #passed string to such string. 
 #by association with 
diff --git a/src/always/00-startup/00-declare/25-global b/src/always/00-startup/00-declare/25-global
--- a/src/always/00-startup/00-declare/25-global
+++ b/src/always/00-startup/00-declare/25-global
@@ -34,17 +34,93 @@ Declare the specified variable to be an exported global contained by the current
 parcel and documented by the passed help string, where such variable is
 specified by either:
 
-* The passed type and name arguments, preferably.
-* The variable declaration prefixing the passed help string, as fallback.
+* The passed variable type and name arguments, if such arguments are passed.
+* The variable declaration prefixing the passed help string, otherwise.
 
-Such help string consists of:
+If a variable name is passed, a `zeshy`-specific variable type must also be
+passed (e.g., `boolean`, `string`).
+
+If a variable name is passed _and_ such name contains a `=` delimiter,
+initialize such variable to the concatenation of the remainder of such name
+following such delimiter and all additional arguments (excluding the last
+argument, specifying the help string). If the passed variable type is nonscalar
+(i.e., either `list` or `map`), both such remainder and the second-to-last
+arguments are ignored. `zsh` reserves the nonscalar delimiters `(` and `)` for
+itself, requiring such delimiters either be quoted (e.g., `\'(\'`, `\')\'`),
+escaped (e.g., `\(`, `\)`), or simply replaced with delimiters _not_ reserved
+by `zsh` in this context (e.g., `[`, `]`): e.g.,
+
+.declare_global()
+==========================================
+[source]
+------------------------------------------
+>>> declare_global string on_restoration=\
+...    "As I conclude I reflect on my childhood experience when I would visit a
+...     stream next to our home to fetch water for my mother. I would drink
+...     water straight from the stream. Playing among the arrowroot leaves I
+...     tried in vain to pick up the strands of frogs' eggs, believing they were
+...     beads. But every time I put my little fingers under them they would
+...     break. Later, I saw thousands of tadpoles: black, energetic and
+...     wriggling through the clear water against the background of the brown
+...     earth. This is the world I inherited from my parents."\
+...    "Today, over 50 years later, the stream has dried up, women walk long
+...     distances for water, which is not always clean, and children will never
+...     know what they have lost. The challenge is to restore the home of the
+...     tadpoles and give back to our children a world of beauty and wonder."
+>>> declare_global map on_industry=[
+...     "If"    "a man walk in the woods for love of them half of each day,"
+...     "he"    "is in danger of being regarded as a loafer; but if he spends"
+...     "his"   "whole day as a speculator, shearing off those woods and making"
+...     "Earth" "bald before her time, he is esteemed an industrious"
+...     "and"   "enterprising citizen. As if a town had no interest in
+...     "its"   "forests but to cut them down!" ]\
+...     "Most men would feel insulted if it were proposed to employ them in
+...      throwing stones over a wall, and then in throwing them back, merely
+...      that they might earn their wages. But many are no more worthily
+...      employed now."
+>>> declare_global "list on_anarchism
+...
+...      Anarchism is not a romantic fable but the hardheaded realization, based
+...      on five thousand years of experience, that we cannot entrust the
+...      management of our lives to kings, priests, politicians, generals, and
+...      county commissioners."
+>>> on_anarchism=(
+...      "Anarchism is founded on the observation that since few men are wise"
+...      "enough to rule themselves, even fewer are wise enough to rule others."
+... )
+>>> get_string_line "${on_restoration}" -1
+earth. This is the world I inherited from my parents.
+>>> print_string "${on_industry[If]}"
+a man walk in the woods for love of them half of each day,
+>>> print_string "${on_anarchism[1]}"
+Anarchism is founded on the observation that since few men are wise
+------------------------------------------
+==========================================
+
+== Variable Type ==
+
+A variable's type may be any alphanumeric string for which an alias of the same
+name suffixed by `_global_export` exists. Hence, `file_descriptor` is a valid
+variable type but `order_of_the_blackened_denarius` is not, since
+file_descriptor_global_export() is an existing alias but
+order_of_the_blackened_denarius_global_export() is (hopefully) not.
+
+`zeshy` provides numerous such aliases and hence variable types, including:
+boolean(), character(), file_descriptor(), float(), integer(), list(),
+list_set(), map(), and string().
+
+== Variable Documentation ==
+
+Variable help strings consist of:
 
 . A *variable declaration* in `zeshy`-specific C-like syntax consisting of one
-  variable type and name (e.g., `list DOG_EAT_DOG_WORLD`).
+  variable type and name (e.g., `list DOG_EAT_DOG_WORLD`), if such type and name
+  were _not_ passed as arguments already.
 . A *variable description* in http://asciidoc.org[AsciiDoc] syntax, augmented
   with `zeshy`-specific markup for cross-referencing other `zeshy` documentation.
-
-== Variable Documentation Grammar ==
+  Since single- and double-quoted `zsh` string syntax conflicts with such syntax,
+  consider passing such description to declare_global_with_stdin() as a
+  here-document on standard input instead.
 
 For completeness, we specify such syntax as a
 http://en.wikipedia.org/wiki/Parsing_expression_grammar[Parser Expression Grammar (PEG)]:
@@ -58,51 +134,43 @@ derives for all productions not listed here (e.g., AsciiDoc, Type, Whitespace):
 | GlobalDeclaration     | <- | Whitespace* Type Whitespace+ GlobalName
 | GlobalName            | <- | AlphanumericString
 |===============================================================================
-
-== Variable Type ==
-
-A variable's type may be any alphanumeric string for which an alias of the same
-name suffixed by `_global_export` exists. Hence, `file_descriptor` is a valid
-variable type but `order_of_the_blackened_denarius` is not, since
-file_descriptor_global_export() is an existing alias but
-order_of_the_blackened_denarius_global_export() is (hopefully) not.
-
-`zeshy` provides numerous such aliases and hence variable types, including:
-boolean(), character(), file_descriptor(), float(), integer(), list(),
-list_set(), map(), and string().
 /---
 function declare_global() {
     # Validate passed arguments.
-    (( # )) || die\
-        'expected one help string, optional type, optional global name, and optional values'
-    local help__dg="${@[-1]}" type__dg name__dg value__dg declarator__dg
+    (( # == 1 || # >= 3 )) || die\
+        'expected either one help string or one variable type, one variable type, zero or more initial variable values, and one help string'
+    local help__dg="${argv[-1]}"\
+        global_type__dg\
+        global_name__dg\
+        global_value__dg\
+        declarator__dg
 
     # Remove such help string from the argument list. See pop_arg() for further
     # details.
     argv[-1]=()
 
-    # If passed a help string and global type and name, localize such arguments.
-    # As this is the common case, handle this condition before those below.
+    # If passed a variable type and name and help string, localize such
+    # arguments. As this is the common case, handle this condition first. Note
+    # this test accounts for the prior removal of the last argument.
     if (( # >= 2 )) {
-        type__dg="${1}"
-        name__dg="${2}"
+        # Localize such arguments.
+        global_type__dg="${1}"
+        global_name__dg="${2}"
 
         # Remove such type and name from the argument list. All remaining
         # arguments comprise such global's initial value, if any.
         shift 2
-    # If passed only a help string and global name, default such type to string.
-    } elif (( # == 1 )) {
-        # Avoid shifting such argument, as no subsequent value was passed.
-        type__dg='string'
-        name__dg="${1}"
+
+        # Prepend such help string with such variable declaration.
+        help__dg="${global_type__dg} ${global_name__dg}"$'\n\n'"${help__dg}"
     # Else, only a help string was passed. Dynamically parse such type and name
     # from the variable declaration prefixing such string.
     } else {
         #FIXME: This could probably be generalized to support "="-delimited
         #assignment, but I have doubts as to whether that'd be widely useful.
+
         # Match the variable type and name from such declaration or throw an
-        # exception if the help string contains no declaration. Dismantled, this
-        # is:
+        # exception if such match fails. Dismantled, this is:
         #
         # * "(#b)", capturing match groups into list global ${match}.
         # * "[[:space:]]#", matching optional whitespace.
@@ -114,34 +182,35 @@ function declare_global() {
             die_for_declarator_type_with_help 'global' "${help__dg}"
 
         # Localize such type and name.
-        type__dg="${match[1]}"
-        name__dg="${match[2]}"
+        global_type__dg="${match[1]}"
+        global_name__dg="${match[2]}"
     }
 
     # If such type is empty, throw an exception.
-    [[ -n "${type__dg}" ]] || die 'expected nonempty global type'
+    [[ -n "${global_type__dg}" ]] || die 'expected nonempty global type'
 
     # If such name contains a "=", split such name on the first "=" into the
     # genuine name and initial value (respectively). Since zsh prohibits
     # variable names from containing "=", such logic is inherently safe.
-    [[ "${name__dg}" == (#b)([[:IDENT:]]##)'='(*) ]] && {
-        name__dg="${match[1]}"
-        value__dg="${match[2]}"
+    [[ "${global_name__dg}" == (#b)([[:IDENT:]]##)'='(*) ]] && {
+        global_name__dg="${match[1]}"
+        global_value__dg="${match[2]}"
+#       print "global type: ${global_type__dg}\nglobal name: ${global_name__dg}\nglobal type: ${global_type__dg}"
     }
 
     # If such name is syntactically invalid, throw an exception.
-    [[ "${name__dg}" == ${~ZESHY_VARIABLE_NAME_GLOB} ]] ||
-        die "global name \"${name__dg}\" syntactically invalid"
+    [[ "${global_name__dg}" == ${~ZESHY_VARIABLE_NAME_GLOB} ]] ||
+        die "global name \"${global_name__dg}\" syntactically invalid"
 
     # Alias declaring globals of such type.
-    declarator__dg="${type__dg}_global_export"
+    declarator__dg="${global_type__dg}_global_export"
 
     # If such alias does not exist, throw an exception. Since such alias
     # could technically also be a function, match both. See is_runnable()
     # for further details.
-#   print "global type: ${type__dg}; global name: ${name__dg}; declarator: ${declarator__dg}"
+#   print "global type: ${global_type__dg}; global name: ${global_name__dg}; declarator: ${declarator__dg}"
     whence -- "${declarator__dg}" &>/dev/null ||
-        die "global \"${name__dg}\" type \"${type__dg}\" unrecognized (${declarator__dg}() undefined)"
+        die "global \"${global_name__dg}\" type \"${global_type__dg}\" unrecognized (${declarator__dg}() undefined)"
 
     # Declare such global. Since the declarator is typically an alias rather
     # than function or pathable, zsh requires evaluating rather than running
@@ -158,16 +227,16 @@ function declare_global() {
     # is not an infrequent purpose.
     #
     # If passed an initial value, declare such global set to such value.
-    if [[ -n "${value__dg}" ]] {
+    if [[ -n "${global_value__dg}" ]] {
         # If passed at least two initial values, such global must be nonscalar
         # (e.g., list, map). Sadly, defining the initial value for a nonscalar is
         # somewhat more subtle than defining the initial value for a scalar.
         if (( # )) {
             # If such type is actually scalar, throw an exception.
-            [[ "${type__dg}" == (list|map|list_*|map_*) ]] ||
-                die "scalar global \"${name__dg}\" initialized to nonscalar value: ${value__dg} ${*}"
+            [[ "${global_type__dg}" == (list|map|list_*|map_*) ]] ||
+                die "scalar global \"${global_name__dg}\" initialized to nonscalar value: ${global_value__dg} ${*}"
 
-            # Ignore the first (i.e., ${value__dg}) and last (i.e., ${argv[-1]})
+            # Ignore the first (i.e., ${global_value__dg}) and last (i.e., ${argv[-1]})
             # elements of such value. Such elements signify ignorable zeshy-
             # specific delimiters (e.g., "\(", "\)", "[", "]"). See pop_arg()
             # for further details.
@@ -175,25 +244,24 @@ function declare_global() {
 
             # Quote-protect each remaining element of such value, manually re-
             # delimiting such value with zsh-specific delimiters "(" and ")".
-            eval "${declarator__dg} ${name__dg}; ${name__dg}=(" "${(q)@}" ')'
+            eval "${declarator__dg} ${global_name__dg}; ${global_name__dg}=(" "${(q)@}" ')'
         # Else, such global is scalar. For safety, quote-protect such value.
         } else {
-            eval ${declarator__dg} ${name__dg}=${(q)value__dg}
+            eval ${declarator__dg} ${global_name__dg}=${(q)global_value__dg}
         }
     # Else, declare such global with no such value (i.e., set to the default
     # value for its type).
     } else {
-        eval ${declarator__dg} ${name__dg}
+        eval ${declarator__dg} ${global_name__dg}
     }
 
     # Map such global to such help string.
-    ZESHY_GLOBAL_NAME_TO_HELP[${name__dg}]="${help__dg}"
+    ZESHY_GLOBAL_NAME_TO_HELP[${global_name__dg}]="${help__dg}"
 
     # Add such global to the current parcel.
-    add_parcel_global "${ZESHY_PARCEL_NAME}" "${name__dg}"
+    add_parcel_global "${ZESHY_PARCEL_NAME}" "${global_name__dg}"
 }
 
-#FIXME: Correct documentation.
 declare_function_with_stdin <<'/---'
 void declare_global_with_stdin[
     args: (string global_type = "",
@@ -201,10 +269,10 @@ void declare_global_with_stdin[
            string global_value1 = "", string global_value2, ...),
     stdin: string documentation]
 
-Set the documentation for the global exported variable named by the variable
-declaration prefixing standard input to such input. Consider calling this rather
-than declare_global(), which requires passing a string argument rather than
-standard input. See declare_function_with_stdin() for further details.
+Declare the specified variable to be an exported global contained by the current
+parcel and documented by the passed help string, where such variable is
+specified as under declare_global(). See declare_function_with_stdin() for
+further details.
 /---
 function declare_global_with_stdin() {
     run_runnable_with_stdin declare_global "${@}"
@@ -306,6 +374,25 @@ on_vietnam: war_crimes
 }
 
 # --------------------( WASTELANDS                         )--------------------
+#   if (( # >= 2 )) { print "argv[1]: ${1}\nargv[2]: ${2}\nargv[3]: ${3}" }
+#Set the documentation for the global exported variable named by the variable
+#declaration prefixing standard input to such input. Consider calling this rather
+#than declare_global(), which requires passing a string argument rather than
+#standard input. See declare_function_with_stdin() for further details.
+#...     "The ways by which you may get money almost without exception lead
+#...      downward. To have done anything by which you earned money merely is to
+#...      have been truly idle or worse. If the laborer gets no more than the
+#...      wages which his employer pays him, he is cheated, he cheats himself."
+        # Else, no type was passed. Default such type to string.
+#       } elif (( # == 2 )) {
+            # Avoid shifting the argument list. By definition, no initial value
+            # was passed.
+#           type__dg='string'
+#           name__dg="${1}"
+#       }
+    #FUXME: When passed a global type and name (rather than embedded in such
+    #help string), prepend such type and name to such help string.
+
 #FUXME: The documentation introduction is also completely wrong, both here and
 #below. *sigh*
 #Set the documentation for the global exported variable named by the variable
