Refactored Zeshy Mount.
Specifically, split the mammoth mount_safely() function into constituent
functions. Also, added parity testing to Zeshy Integer and corrected its
random number generation. Also, corrected the return_exit_status alias
of and added Perl-inspired pop_* functions to ZeshyInit Alias.

diff --git a/src/autoload/always/device/disk/mount b/src/autoload/always/device/disk/mount
--- a/src/autoload/always/device/disk/mount
+++ b/src/autoload/always/device/disk/mount
@@ -6,10 +6,26 @@
 # Zeshy Mount, implementing filesystem mounting and unmounting functionality.
 
 # ....................{ ALIASES                            }....................
+#FIXME: Alias "mount" to "mount_safely", or perhaps simply rename the latter the
+#former and improve such function so as to defer to "command mount" when non-
+#interactive (much like grep()).
 interactive_alias mo='mount_safely'
 interactive_alias umo='umount'
 
 # ....................{ EXCEPTIONS                         }....................
+# void die_if_mount_point(
+#   char *pathname, char *error_message = 'currently mounted')
+#
+# Raise an exception if the passed path is a mount point.
+die_if_mount_point() {
+    die_unless_one_or_two_args\
+        'expected one pathname and optional error message'
+    string pathname="${1}"
+    #FIXME: Print what it's actually mounted to, for clarity.
+    is_mount_point "${pathname}" and
+        die "${2:-\"${pathname}\" mounted}"
+}
+
 # void die_unless_unmounted_disk(
 #   char *pathname, char *error_message = 'currently mounted')
 #
@@ -20,7 +36,7 @@ die_unless_unmounted_disk() {
         'expected one pathname and optional error message'
     string pathname="${1}"
     is_disk_device "${pathname}" and not is_disk_mounted "${pathname}" or
-        die "${2:-\"${pathname}\" not found or not a mounted disk}"
+        die "${2:-\"${pathname}\" not found or not an unmounted disk}"
 }
 
 # ....................{ TESTS                              }....................
@@ -51,7 +67,7 @@ is_device_mounted_to() {
     
     # If the passed pathname does not correspond to an existing directory, it
     # cannot correspond to a valid mount point.
-    { is_disk_device "${device_filename}" and is_dir "${mount_dirname}" } or
+    is_disk_device "${device_filename}" and is_dir "${mount_dirname}" or
         return_failure
 
     #FIXME: Also implement without "mountpoint", if feasible.
@@ -83,7 +99,7 @@ is_mount_point() {
             return_exit_status
     # Otherwise, manually match "mount" output.
     else
-        mount | awk -v DIR="${mount_dirname}"\
+        command mount | awk -v DIR="${mount_dirname}"\
             'BEGIN {CODE=1} $3 == DIR {CODE=0} END {exit CODE}' |
             return_exit_status
     fi
@@ -113,7 +129,7 @@ END { exit CODE }' '/proc/mounts' | return_exit_status
 #       utter 'failed...'
     # Otherwise, manually match "mount" output.
     else
-        mount | awk -v DIR="${mount_dirname}" '
+        command mount | awk -v DIR="${mount_dirname}" '
 BEGIN { CODE = 1 }
 $3 == DIR && $NF ~ /(,|\()rw(,|\))/ { CODE = 0 }
 END { exit CODE }' | return_exit_status
@@ -174,7 +190,7 @@ print_mount_points() {
     (
         print 'device directory type flags'
         print '???'
-        LC_ALL=C mount | awk '{$2=$4=""; print}'
+        LC_ALL=C command mount | awk '{$2=$4=""; print}'
     ) | column -t | awk -v BANNER="$(utter_banner)" -F'[ ]' '
 NR == 1 { print }
 NR == 2 { print BANNER }
@@ -206,18 +222,22 @@ END { exit CODE }' '/etc/fstab'; then
         # test failed to return), remount "/boot" read-write; otherwise, simply
         # mount "/boot" read-write.
         if is_mount_point '/boot'
-        then mount -o remount,rw '/boot'
-        else mount -o         rw '/boot'
+        then mount_point -o remount,rw '/boot'
+        else mount_point -o         rw '/boot'
         fi
     # Otherwise, raise an exception unless "/boot/" is already writable.
-    else
-	    die_unless_writable_dir '/boot'
+    elif not is_writable_dir '/boot'; then
+        die '"/boot" neither writable or listed by "/etc/fstab"'
     fi
 }
 
+# void mount_safely(void) --OR--
+# void mount_safely(char *mount_dirname) --OR--
 # void mount_safely(
-#   char *device_filename, char *mount_dirname,
-#   char *mount_option1, char *mount_option2, ...)
+#   char *mount_option1, char *mount_option2, ..., char *device_filename) --OR--
+# void mount_safely(
+#   char *mount_option1, char *mount_option2, ...,
+#   char *device_filename, char *mount_dirname)
 #
 # Mount the device with the passed filename to the mount point with the passed
 # dirname and options. This function safely (and sanely) interprets the passed
@@ -243,94 +263,121 @@ END { exit CODE }' '/etc/fstab'; then
 # In other words, this function quasi-intelligently accepts darn near anything.
 mount_safely() {
     #FIXME: Add a dash of commentary, here and below.
-    if not is_args and is_interactive_directly; then
-        print_mount_points
+#   if not is_args and is_interactive_directly; then
+    if not is_args
+    then print_mount_points
+    elif is_one_arg
+    then mount_point "${1}"
+    else mount_disk  "${@}"
+    fi
+}
+
+# void mount_point(
+#   char *mount_option1, char *mount_option2, ..., char *mount_dirname)
+#
+# Mount the device that "/etc/fstab" maps to the passed dirname to that
+# directory with the passed options.
+mount_point() {
+    # Localize and validate passed arguments.
+    die_unless_args 'expected optional mount options and one mount dirname'
+    string mount_dirname="${@[-1]}"
+    die_if_mount_point "${mount_dirname}"
+
+    #FIXME: O.K.; for orthogonality with mount_disk(), we should really avoid
+    #remounting to an already mounted directory only if such mount point
+    #corresponds to the current mapping defined by /etc/fstab. (Annoying, but
+    #certainly feasible.)
+    # Mount.
+    make_dir_safely         "${mount_dirname}" 
+    die_unless_writable_dir "${mount_dirname}"
+    interactively utter\
+        "mounting via \"/etc/fstab\" to \"${mount_dirname}\"..."
+    command mount "${@}"
+}
+
+# void mount_disk(
+#   char *mount_option1, char *mount_option2, ..., char *device_filename) --OR--
+# void mount_disk(
+#   char *mount_option1, char *mount_option2, ...,
+#   char *device_filename, char *mount_dirname)
+mount_disk() {
+    # Localize passed arguments.
+    die_unless_args\
+        'expected optional mount options and one device filename and optional mount dirname'
+    string device_filename mount_dirname
+
+    if is_writable_dir "${@[-1]}"; then
+        die_unless_at_least_two_args\
+            'expected optional mount options and one device filename and one mount dirname'
+        device_filename="${@[-2]}"
+        mount_dirname="${@[-1]}"
+        pop_two_args
     else
-        # Localize and validate passed arguments.
-        die_unless_args\
-            'expected one device filename and/or mount dirname and optional mount options'
+        device_filename="${@[-1]}"
+        mount_dirname="$(get_mount_home)/$(get_basename "${device_filename}")"
+        pop_one_arg
+    fi
 
-        #FIXME: This and the following conditional are effectively distinct
-        #functions, and could reasonably be separated as such..... Perhaps.
-        #Ah. Yes. Then, our calling of "mount -o rw /boot" above should be
-        #replaced by calls to, say, "mount_point -o rw /boot". Note we'd need
-        #define such function to take the last argument as the mount_dirname,
-        #but that's certainly no issue.
-        if is_one_arg; then
-            string mount_dirname="${1}"
+    if not is_found "${device_filename}"; then
+        is_absolute_path "${device_filename}" and
+            die "\"${device_filename}\" not found"
 
-            make_dir_safely         "${mount_dirname}" 
-            die_unless_writable_dir "${mount_dirname}"
-            interactively utter\
-                "mounting to \"${mount_dirname}\" via \"/etc/fstab\"..."
-            mount "${mount_dirname}"
-        #FIXME: Yup. How 'bout naming this one mount_disk()? Sensible.
-        else
-            string device_filename="${1}" mount_dirname
-            shift_one_arg
+        #FIXME (new): O.K.; we need a new function testify(). (Clever, no?
+        #Also consider falsify(), though that name doesn't accurately describe
+        #its purpose.) Call it like this:
+        #device_filename="$(testify get_first_device "/dev/disk/by-label/${device_filename}" "/dev/${device_filename}")" or die "device \"${device_filename}\" not found"
+        #Simple. testify() calls the passed command via the typical run()
+        #construct *BUT WRAPPED IN AN EXCEPTION HANDLER* implicitly squelching
+        #any caught exception and simply converting it into a false return value.
+        #That then causes the entire equality to evaluate to "false" and hence
+        #implicitly throw an exception. Phew! Solved.
+        #
+        #FIXME: Hmm; this doesn't appear to behave as expected. If
+        #get_first_device() raises an exception, I'd expect that to unwind
+        #this function's stack frame as well. It doesn't. Instead, "device_filename"
+        #just gets the output of get_first_device(), which in the case of a
+        #raised exception is a stack trace. Of course, that isn't a file, so
+        #the subsequent call to die_unless_disk_device() fails as well. This
+        #strikes me as a bug, perhaps corrected by a subsequent Zsh update?
+        device_filename="$(get_first_device "/dev/disk/by-label/${device_filename}" "/dev/mapper/${device_filename}" "/dev/vg/${device_filename}" "/dev/${device_filename}")"
+    fi
 
-            if not is_found "${device_filename}"; then
-                # If the passed
-                is_absolute_path "${device_filename}" and
-                    die "\"${device_filename}\" not found"
+    # If the passed device is already mounted to the passed directory, noop.
+    # By default, "mount" unhelpfully fails with error.
+    if is_device_mounted_to "${device_filename}" "${mount_dirname}"; then
+        interactively utter "\"${device_filename}\" already mounted to \"${mount_dirname}\"."
+        return_success
+    fi
 
-                #FIXME (new): O.K.; we need a new function testify(). (Clever, no?
-                #Also consider falsify(), though that name doesn't accurately describe
-                #its purpose.) Call it like this:
-                #device_filename="$(testify get_first_device "/dev/disk/by-label/${device_filename}" "/dev/${device_filename}")" or die "device \"${device_filename}\" not found"
-                #Simple. testify() calls the passed command via the typical run()
-                #construct *BUT WRAPPED IN AN EXCEPTION HANDLER* implicitly squelching
-                #any caught exception and simply converting it into a false return value.
-                #That then causes the entire equality to evaluate to "false" and hence
-                #implicitly throw an exception. Phew! Solved.
-                #
-                #FIXME: Hmm; this doesn't appear to behave as expected. If
-                #get_first_device() raises an exception, I'd expect that to unwind
-                #this function's stack frame as well. It doesn't. Instead, "device_filename"
-                #just gets the output of get_first_device(), which in the case of a
-                #raised exception is a stack trace. Of course, that isn't a file, so
-                #the subsequent call to die_unless_disk_device() fails as well. This
-                #strikes me as a bug, perhaps corrected by a subsequent Zsh update?
-                device_filename="$(get_first_device "/dev/disk/by-label/${device_filename}" "/dev/mapper/${device_filename}" "/dev/vg/${device_filename}" "/dev/${device_filename}")"
-            fi
-            die_unless_disk_device "${device_filename}"
+    # Make the mount point if non-extant.
+    die_if_mount_point "${mount_dirname}"
+    make_dir_safely         "${mount_dirname}" 
+    die_unless_writable_dir "${mount_dirname}"
+    interactively utter\
+        "mounting \"${device_filename}\" to \"${mount_dirname}\"..."
 
-            if is_args; then
-                mount_dirname="${1}"
-                shift_one_arg
-            else
-                mount_dirname="$(get_mount_home)/$(get_basename "${device_filename}")"
-            fi
-
-            if is_mount_point "${mount_dirname}"; then
-                # If the passed device is already mounted to the passed directory, noop.
-                # By default, "mount" unhelpfully fails with error.
-                is_device_mounted_to "${device_filename}" "${mount_dirname}" and
-                    return
-
-                #FIXME: Print what it's actually mounted to, for assistance.
-                # Otherwise, raise an exception.
-                die "\"${mount_dirname}\" already mounted"
-            fi
-
-            make_dir_safely         "${mount_dirname}" 
-            die_unless_writable_dir "${mount_dirname}"
-            interactively utter\
-                "mounting \"${device_filename}\" to \"${mount_dirname}\"..."
-
-            if is_device "${device_filename}"; then
-                mount "${@}" "${device_filename}" "${mount_dirname}"
-            elif is "${device_filename}" == *.iso si; then
-                mount "${@}" -t iso9660 -o 'exec,loop'\
-                    "${device_filename}" "${mount_dirname}"
-            else
-                die "\"${device_filename}\" neither a device or ISO file"
-            fi
-        fi
+    # Mount.
+    if is_device "${device_filename}"; then
+        die_unless_unmounted_disk "${device_filename}"
+        command mount "${@}" "${device_filename}" "${mount_dirname}"
+    #FIXME: This globs case-insensitively, no?
+    elif is "${device_filename}" == *.iso si; then
+        command mount "${@}" -t iso9660 -o 'exec,loop'\
+            "${device_filename}" "${mount_dirname}"
+    else die "\"${device_filename}\" neither a device or ISO file"
     fi
 }
 
 #FIXME: Obsolete.
+#       mountpoint -q "${mount_dirname}" | true; return_exit_status
+#       print 'here'
+#       mountpoint -q "${mount_dirname}"
+#       print "returned: $?"
+#       mountpoint -q "${mount_dirname}" and return_success or return_failure
+#       mountpoint -q "${mount_dirname}" | true and return ${pipestatus[-2]}
+#       mountpoint -q "${mount_dirname}" | return 1
+#       mountpoint -q "${mount_dirname}" | return_exit_status
+#       print 'there'
 #   else is_nonempty "$(mount | awk '$3 == "/boot" {print $3}')"
 
 #NR == 1 {
