Added additional precautions to declarators.
Alias and function declarators now print nonfatal warnings if such
alias and function has already been declared. The final output
refactoring is largely underway, endeavoring to both eliminate
print_string() and centralize exception printing logic into a new
print_exception() function.

diff --git a/src/always/00-core/00-declare/10-function b/src/always/00-core/00-declare/10-function
--- a/src/always/00-core/00-declare/10-function
+++ b/src/always/00-core/00-declare/10-function
@@ -188,7 +188,7 @@ typeset -Agx ZESHY_FUNCTION_NAME_SYNONYM_TO_FUNCTION_NAME
 # See below for function documentation.
 function die_for_declarator_type_with_help() {
     # Validate passed arguments.
-    (( # == 2 )) || die 'expected one type string and one help string'
+    (( # == 2 )) || die 'Expected one type string and one help string.'
 #   print -r -- "arg count: ${#}; args: ${*}"
     local type="${1}" help="${2}"
 
@@ -209,7 +209,7 @@ function die_for_declarator_type_with_help() {
     }
 
     # Throw an exception suffixed by such prototype.
-    die "${type} documentation invalid (see \"print_help declare_${type}\"):
+    die "${(C)type} documentation invalid (see \"print_help declare_${type}\"):
 ${help_prototype}"
 }
 
@@ -217,7 +217,7 @@ ${help_prototype}"
 # See below for function documentation.
 function declare_function() {
     # Validate passed arguments.
-    (( # == 1 )) || die 'expected one help string'
+    (( # == 1 )) || die 'Expected one help string.'
     local help__df="${1}"
 
     # Unless such string matches the function help PCRE, throw an exception.
@@ -238,9 +238,15 @@ function declare_function() {
     # Current function name iterated in such list.
     local function_name__df
 
-    # If such function has only a single name, match such name.
-    if [[ -n "${help_match__df[2]}" ]] {
-        function_names__df=( "${help_match__df[2]}" )
+    # If such function only has one name, match such name.
+    function_name__df="${help_match__df[2]-}"
+    if [[ -n "${function_name__df}" ]] {
+        function_names__df=( "${function_name__df}" )
+
+        # If such function has already been declared, print a warning.
+        if (( ${+ZESHY_FUNCTION_NAME_TO_HELP[${function_name__df}]} )) {
+            print "zeshy: function ${function_name__df}() in parcel @{${ZESHY_PARCEL_NAME}} already declared" 1>&2
+        }
     # Else, such function has multiple names. Since single- and double-quoted
     # function names may contain commas, such names cannot be split on commas as
     # with function attributes above. Rather, match such names with iteration.
@@ -253,13 +259,16 @@ function declare_function() {
         # name matched above. See for_string_matches_pcre() for further details.
         local ZPCRE_OP='0 0'
         while { pcre_match -b -n ${ZPCRE_OP[(w)2]} -- "${help_match__df[3]}" } {
-            function_names__df+="${match[1]}"
-            ZESHY_FUNCTION_NAME_SYNONYM_TO_FUNCTION_NAME[${match[1]}]="${function_names__df[1]}"
+            function_name__df="${match[1]}"
+            function_names__df+="${function_name__df}"
+            ZESHY_FUNCTION_NAME_SYNONYM_TO_FUNCTION_NAME[${function_name__df}]="${function_names__df[1]}"
+
+            # If such function has already been declared, print a warning.
+            if (( ${+ZESHY_FUNCTION_NAME_TO_HELP[${function_name__df}]} )) {
+                print "zeshy: function ${function_name__df}() in parcel @{${ZESHY_PARCEL_NAME}} already declared" 1>&2
+            }
         }
     }
-#   for ((match_index=1; match_index <= ${#names}; ++match_index)) {
-#       print "name ${match_index}: ${names[${match_index}]}"
-#   }
 
     # If such function has attributes, match such attributes.
     if [[ -n "${help_match__df[1]}" ]] {
@@ -315,9 +324,9 @@ Define the passed function to run the passed *function body* (i.e., such
 function's implementation excluding `function ${function_name} () {` prefix and
 `}` suffix). If such function has already been declared, throw an exception.
 
-Since `zsh` already offers intuitive syntax for defining
-functions -- even those with names containing shell-reserved characters. This
-function is largely useful only for defining functions dynamically: e.g.,
+Unlike aliases, functions with names containing shell-reserved characters may be
+readily defined by double-quoting such names. Hence, this function is largely
+useful only for defining functions dynamically: e.g.,
 
 .define_function()
 ==========================================
@@ -337,14 +346,15 @@ With the myth of the State out of the way, the real mutuality and
 ==========================================
 /---
 function define_function() {
-    # Validate passed arguments.
-    (( # == 2 )) || die 'expected one function name and one function body'
+    # Validate sanity.
+    (( # == 2 )) || die 'Expected one function name and one function body.'
     local function_name__df="${1}"
 
     # If such function already exists, throw an exception. See is_function()
     # for further details.
-    typeset -f -- "${function_name__df}" &>/dev/null &&
+    if { typeset -f -- "${function_name__df}" &>/dev/null } {
         die "function ${function_name__df}() already exists:"$'\n'"$(which -- "${function_name__df}")"
+    }
 
     # Declare such function.
     redefine_function "${@}"
@@ -380,10 +390,10 @@ With the housing crash, the falling dollar, and the decline in middle
 ==========================================
 /---
 function redefine_function() {
-    # Validate passed arguments.
-    (( # == 2 )) || die 'expected one function name and one function body'
+    # Validate sanity.
+    (( # == 2 )) || die 'Expected one function name and one function body.'
     local function_name__rf="${1}" function_body__rf="${2}"
-    [[ -n "${function_name__rf}" ]] || die 'expected nonempty function name'
+    [[ -n "${function_name__rf}" ]] || die 'Expected nonempty function name.'
 #   is_zeshy_debug_and print "zeshy: defining ${function_name__rf}()..."
 
     # Function to be defined. For obscure error handling reasons, the eval()
@@ -1385,6 +1395,14 @@ same proportion is the proletariat, the modern working class, developed
 /---
 
 # --------------------( WASTELANDS                         )--------------------
+#   for ((match_index=1; match_index <= ${#names}; ++match_index)) {
+#       print "name ${match_index}: ${names[${match_index}]}"
+#   }
+
+#`zsh` already provides intuitive syntax for defining functions (even those
+#with names containing shell-reserved characters), this function is largely
+#useful only for defining functions dynamically: e.g.,
+
         # * "read -t 0", reading standard input only if such input is nonempty.
         #   See is_stdin_readable_sans_blocking() for further details.
 #   }" |& { read -t 0 && IFS='' read -r -d '' function_error__rf }
