Added global synonym support.
declare_global() now permits multiple "="-suffixed global names to be supplied
for each such declaration, in which case all such globals are assigned the same
initial value and help string. (Swag, surely.)

diff --git a/src/always/00-core/00-declare/25-global b/src/always/00-core/00-declare/25-global
--- a/src/always/00-core/00-declare/25-global
+++ b/src/always/00-core/00-declare/25-global
@@ -8,22 +8,48 @@ Handle global declarers.
 /---
 
 # ....................{ GLOBALS                            }....................
+#FIXME: Declare a new map ${ZESHY_GLOBAL_NAME_TO_GLOBAL_NAME_FIRST}. While
+#recording synonyms will (of course) be nice, the principal use of such map
+#should be in printing a warning or dying entirely if such global has already
+#been declared... which I believe we currently don't check!
+#FIXME: Waaait! No. See @{10-function}.
+
 # Global map from global names to the help strings documenting such globals. See
 # ${ZESHY_FUNCTION_NAME_TO_HELP} for further details.
 typeset -Ag ZESHY_GLOBAL_NAME_TO_HELP
 
-# Glob matching zsh variable names. Dismantled, this is:
+# Global glob matching zsh variable names. Dismantled, this is:
 #
 # * "[a-zA-Z_]", matching the first character of a valid zsh variable name.
 # * "[a-zA-Z0-9_]#", matching all remaining characters of such name.
 typeset -g ZESHY_VARIABLE_NAME_GLOB='[a-zA-Z_][a-zA-Z0-9_]#'
 
 # ....................{ DECLARERS                          }....................
+#FIXME: We need to support a disjunctive prototypes. Consider this function,
+#which can be called in at least two fundamentally distinct ways. To permit
+#this, I suggest extending our "{...,...}" syntax yet again as follows:
+#
+#    {void declare_global(
+#        string global_type,
+#        string global_name_with_optional_value,
+#        string documentation),
+#     void declare_global(string documentation)}
+#
+#We *REALLY* don't want to have to implement a non-regular context-free parser.
+#Fortunately, we won't have to. Simply hard-code an outermost "(...|...)"-style
+#PCRE, where the first sub-PCRE in such PCRE matches the conventional singular
+#prototype (i.e., lacking exterior "{" and "}" delimeters) and the final
+#sub-PCRE in such PCRE matches the above plural prototype (i.e., with exterior
+#"{" and "}" delimeters).
+#FIXME: Document the fact that global values may actually be delimited by an
+#arbiratry number of "=" delimiters, in which case this function defines *ALL*
+#such globals to be synonyms of each other assigned the same initial value.
+#Required elsewhere. Sweet, eh?
+
 declare_function_with_stdin <<'/---'
 void declare_global(
     string global_type = "",
-    string global_name = "",
-    string global_value1 = "", string global_value2, ...,
+    string global_name_with_optional_value = "",
     string documentation)
 
 Declare the specified variable to be an exported global contained by the current
@@ -137,17 +163,19 @@ derives for all productions not listed here (e.g., AsciiDoc, Type, Whitespace):
 function declare_global() {
     # Validate passed arguments.
     (( # == 1 || # == 3 )) || die\
-        'expected either one help string or one variable type, one variable name (with optional "="-delimited variable value), and one help string'
+        'Expected either: one help string; or one variable type, one variable name (with optional "="-delimited variable value), and one help string.'
     local\
         help__dg="${@[-1]}"\
         global_type__dg\
         global_name__dg\
+        global_names_string__dg\
         global_value__dg\
         declarator__dg
     integer is_global_type_nonscalar__dg
+    list global_names__dg
 
-    # Remove such help string from the argument list. See pop_arg() for further
-    # details.
+    # Truncate such help string from the argument list. See pop_arg() for
+    # further details.
     argv[-1]=()
 
     # If passed a variable type and name and help string, localize such
@@ -156,13 +184,53 @@ function declare_global() {
     if (( # == 2 )) {
         # Localize such arguments.
         global_type__dg="${1}"
-        global_name__dg="${2}"
+        global_names_string__dg="${2}"
 
         # Prepend such help string with such variable declaration.
-        help__dg="${global_type__dg} ${global_name__dg}"$'\n\n'"${help__dg}"
+        help__dg="${global_type__dg} ${global_names_string__dg}"$'\n\n'"${help__dg}"
+
+        # If such variable names string matches "="-delimited variable
+        # assignment syntax, split such string on the final "=" into one
+        # substring of one or more variable names and one variable value.
+        #
+        # Since zsh prohibits variable names but *NOT* values from containing
+        # "=", attempting to split such names on "=" via parameter expansion
+        # flag "(s)" does *NOT* suffice. Instead, match such names iteratively
+        # with predefined PCREs.
+        if [[ "${global_names_string__dg}" =~\
+              "${ZESHY_DECLARATION_PCRE_GLOBAL_NAMES}" ]] {
+            # Such variable names string reduced to only such names.
+            global_names_string__dg="${match[1]}"
+
+            # Such variable value.
+            global_value__dg="${match[2]}"
+
+            # Prepare to match such names from such string. See
+            # for_string_matches_pcre() for further details.
+            pcre_compile -- "${ZESHY_DECLARATION_PCRE_GLOBAL_NAME}"
+            pcre_study
+
+            # Append each such name to such list.
+            local ZPCRE_OP='0 0'
+            while {
+                pcre_match -b -n ${ZPCRE_OP[(w)2]} -- "${global_names_string__dg}"
+            } {
+                global_names__sltrpn+="${match[1]}"
+            }
+        # Else if such variable names string matches a single variable name,
+        # set the list of such names to such name.
+        } elif [[ "${global_names_string__dg}" ==\
+            ${~ZESHY_VARIABLE_NAME_GLOB} ]] {
+            global_names__sltrpn=( "${global_names_string__dg}" )
+        # Else, such variable names string is invalid. Throw an exception.
+        } else {
+            die "Global declaration \"${global_type__dg} ${global_names_string__dg}\" invalid."
+        }
     # Else, only a help string was passed. Dynamically parse such type and name
     # from the variable declaration prefixing such string.
     } else {
+        #FIXME: Generalize to support variable name synonyms, as with aliases
+        #and functions.
         #FIXME: This could probably be generalized to support "="-delimited
         #assignment, but I have doubts as to whether that'd be widely useful.
 
@@ -173,31 +241,24 @@ function declare_global() {
         # * "[[:space:]]#", matching optional whitespace.
         # * "([^[:space:]]##)", matching the variable type into ${match[1]}.
         # * "[[:space:]]##", matching mandatory whitespace.
-        # * "([[:IDENT:]]##)", matching the variable name into ${match[2]}.
         [[ "${help__dg}" ==\
-            (#b)[[:space:]]#([^[:space:]]##)[[:space:]]##([[:IDENT:]]##)* ]] ||
+            (#b)[[:space:]]#([^[:space:]]##)[[:space:]]##(${~ZESHY_VARIABLE_NAME_GLOB})* ]] ||
             die_for_declarator_type_with_help 'global' "${help__dg}"
 
         # Localize such type and name.
         global_type__dg="${match[1]}"
-        global_name__dg="${match[2]}"
+        global_names__dg=( "${match[2]}" )
     }
 
     # If such type is empty, throw an exception.
-    [[ -n "${global_type__dg}" ]] || die 'expected nonempty global type'
+    [[ -n "${global_type__dg}" ]] || die 'Expected nonempty global type.'
 
-    # If such name contains a "=", split such name on the first "=" into the
-    # genuine name and initial value (respectively). Since zsh prohibits
-    # variable names from containing "=", such logic is inherently safe.
-    if [[ "${global_name__dg}" == (#b)([[:IDENT:]]##)'='(*) ]] {
-        global_name__dg="${match[1]}"
-        global_value__dg="${match[2]}"
-#       print -r -- "global type: ${global_type__dg}; name: ${global_name__dg}; value: ${global_value__dg}"
+    # If such value is nonempty and such type is nonscalar, throw an exception.
+    # See function documentation for further details.
+    if [[ -n "${global_value__dg}" &&\
+             "${global_type__dg}" == (list|map)(_*|) ]] {
+        die "${global_type__dg} global \"${global_name__dg}\" nonscalar and hence not initializable to \"${global_value__dg}\"."
     }
-
-    # If such name is syntactically invalid, throw an exception.
-    [[ "${global_name__dg}" == ${~ZESHY_VARIABLE_NAME_GLOB} ]] ||
-        die "global name \"${global_name__dg}\" syntactically invalid"
 
     # Set the name of the alias declaring globals of such type. Since nonscalar
     # globals cannot be exported and since unconditionally exporting all scalar
@@ -212,9 +273,9 @@ function declare_global() {
     # for further details.
 #   print "global type: ${global_type__dg}; global name: ${global_name__dg}; declarator: ${declarator__dg}"
     whence -- "${declarator__dg}" &>/dev/null ||
-        die "global \"${global_name__dg}\" type \"${global_type__dg}\" unrecognized (${declarator__dg}() undefined)"
+        die "Global type \"${global_type__dg}\" unrecognized (i.e., ${declarator__dg}() undefined)."
 
-    # Declare such global. Since the declarator is typically an alias rather
+    # Declare such globals. Since the declarator is typically an alias rather
     # than function or pathable, zsh requires evaluating rather than running
     # such declarator. While acceptable, this is somewhat... annoying.
     #
@@ -223,31 +284,29 @@ function declare_global() {
     # there exists no efficient means of implementing such test. While there do
     # exist efficient means of testing whether a variable either local or global
     # exists and whether such variable in the *CURRENT* scope is local or global,
-    # the only means of testing whether a global exists is to parse the output of
-    # "typeset -gx +" for a line matching such global's name. While such parsing
-    # could conceivably be efficient for infrequent purposes, declaring globals
-    # is not an infrequent purpose.
-    #
-    # If passed an initial value, declare such global set to such value.
-    if [[ -n "${global_value__dg}" ]] {
-        # If such type is nonscalar, throw an exception. See function
-        # documentation for further details.
-        [[ "${global_type__dg}" == (list|map)(_*|) ]] &&
-            die "${global_type__dg} global \"${global_name__dg}\" nonscalar and thus not initializable to \"${global_value__dg}\""
+    # the only means of testing whether a global exists is to parse the output
+    # of "typeset -gx +" for a line matching such global's name. While such
+    # parsing could conceivably be efficient for infrequent purposes, declaring
+    # globals is not an infrequent purpose.
+    for global_name__dg ("${global_names__dg[@]}") {
+        # If such value exists, declare such global initialized to such value.
+        # Since such name *MUST* be expanded before evaluating such statement,
+        # this eval() *CANNOT* be extracted outside this "for" loop as would
+        # commonly be the case.
+        if [[ -n "${global_value__dg}" ]] {
+            eval ${declarator__dg}' '${global_name__dg}'="${global_value__dg}"'
+        # Else, declare such global initialized to a default value.
+        } else {
+            eval ${declarator__dg}' '${global_name__dg}
+        }
 
-        # Declare such global initialized to such value.
-        eval "${declarator__dg} ${global_name__dg}=\"\${global_value__dg}\""
-    # Else, declare such global initialized to the default value for such type.
-    } else {
-        eval "${declarator__dg} ${global_name__dg}"
+        # Map such global to such help string.
+        ZESHY_GLOBAL_NAME_TO_HELP[${global_name__dg}]="${help__dg}"
+
+        # Add such global to the current parcel.
+        add_parcel_global "${ZESHY_PARCEL_NAME}" "${global_name__dg}"
     }
 #   print -r -- "${declarator__dg} ${global_name__dg}=\"${(P)global_name__dg}\""
-
-    # Map such global to such help string.
-    ZESHY_GLOBAL_NAME_TO_HELP[${global_name__dg}]="${help__dg}"
-
-    # Add such global to the current parcel.
-    add_parcel_global "${ZESHY_PARCEL_NAME}" "${global_name__dg}"
 }
 
 declare_function_with_stdin <<'/---'
@@ -377,6 +436,48 @@ value). See ZESHY_FUNCTION_NAME_TO_FUNCTION_NAME_FIRST() for further details.
 }
 
 # --------------------( WASTELANDS                         )--------------------
+        #FUXME: Improper. As with aliases and functions, we instead want to
+        #define a 
+        # Declare such global initialized to such value. Note that such value
+        # defaults to the empty string if undefined. If such type is numeric, zsh will silently "do the
+        # right thing" and cast from the empty string to the intended default
+        # numeric value on its assignment below.
+        # declare such globals initialized to such value.
+
+    # declare such globals initialized to such value.
+#    if [[ -n "${global_value__dg}" ]] {
+#        # If such type is nonscalar, throw an exception. See function
+#        # documentation for further details.
+#        [[ "${global_type__dg}" == (list|map)(_*|) ]] &&
+#            die "${global_type__dg} global \"${global_name__dg}\" nonscalar and hence not initializable to \"${global_value__dg}\"."
+#
+#        # Initialize such globals.
+#        for global_name__dg ("${global_names__dg[@]}") {
+#            eval ${declarator__dg}' '${global_name__dg}'="${global_value__dg}"'
+#        }
+#    # Else, declare such globals initialized to default values.
+#    } else {
+#        for global_name__dg ("${global_names__dg[@]}") {
+#            eval ${declarator__dg}' '${global_name__dg}
+#        }
+#    }
+
+#       die "Global \"${global_name__dg}\" type \"${global_type__dg}\" unrecognized (${declarator__dg}() undefined)."
+        # * "([[:IDENT:]]##)", matching the variable name into ${match[2]}.
+    # If such name is syntactically invalid, throw an exception.
+#    [[ "${global_name__dg}" == ${~ZESHY_VARIABLE_NAME_GLOB} ]] ||
+#        die "Global name \"${global_name__dg}\" syntactically invalid."
+#           (#b)[[:space:]]#([^[:space:]]##)[[:space:]]##([[:IDENT:]]##)* ]] ||
+
+    # If such name contains a "=", split such name on the first "=" into the
+    # genuine name and initial value (respectively). Since zsh prohibits
+    # variable names from containing "=", such logic is inherently safe.
+#    if [[ "${global_name__dg}" == (#b)([[:IDENT:]]##)'='(*) ]] {
+#        global_name__dg="${match[1]}"
+#        global_value__dg="${match[2]}"
+##       print -r -- "global type: ${global_type__dg}; name: ${global_name__dg}; value: ${global_value__dg}"
+#    }
+
 #Map *synonymized function names* (i.e., function names for functions with
 #multiple names) to the first function names declared for such functions. Since
 #all first function names thus map to themselves, this map contains the identity
