Improved Zeshy wget URL resolution.
Also improved core error handling and regular expression matching.
"A luxurious (life) in flux
 Sways {core} aptitudes
 Attitudinally.

 Stains of humanity
 [Lain] along this humblest city,
 Lest we sift that past-ambling
 Wresting if conditionality,
 Blessedly."

diff --git a/src/zeshy/command/wget b/src/zeshy/command/wget
--- a/src/zeshy/command/wget
+++ b/src/zeshy/command/wget
@@ -9,14 +9,18 @@
 zimport zeshy/regex
 
 # ....................{ URLS                               }....................
-# char *resolve_url(url)
+# Aliases.
+alias wgetru='wget_resolve_url'
+
+#FIXME: This is also implementable via 'curl -sI "${url}"'.
+# char *wget_resolve_url(char *url)
 #
 # Transitively resolve the passed URL of all intermediary redirects. For
 # example, if "http://dieoff.com" redirected to "http://holoceneextinction.com"
 # redirected to "http://raiazome.com", then this function prints the final URL,
 # "http://raiazome.com".
-resolve_url() {
-    [[ "${#}" -eq 1 ]] || die 'expected exactly one URL'
+wget_resolve_url() {
+    die_unless_one_argument 'expected exactly one URL'
 
     # Run "wget" with options:
     #
@@ -24,9 +28,23 @@ resolve_url() {
     # * "--spider" to prevent actual retrieval of page content.
     # * "-O -" to permit redirection to a pipe. 
     #
-    # Also, redirect stderr to stdout because *WE HAVE TO*. (Yes, this is dumb.)
-    try wget -t 1 --spider -O - "${1}" 2>&1 |
-        match_multiline_first_group '^Location: ([^ ]+) '
+    # Avoid running under "try" as that currently fails to interpret shell
+    # sensitive characters properly (e.g., "&"), and redirect stderr to stdout
+    # as *WE HAVE TO* (which seems fairly dumb).
+    local url="${1}"
+    local wget_output="$(wget --max-redirect=0 --spider --tries=1 -O - "${url}" 2>&1)"
+    is_ok || die "\"${url}\" not resolved; \"wget\" failed with:\n${wget_output}"
+
+    # Match the resolved URL from the "wget" output.
+    local url_resolved  # separate to capture return code
+          url_resolved="$(match_multiline_first_group '^Location: ([^ ]+) ' "${wget_output}")"
+
+    # If the passed URL does redirect to another URL, print that; otherwise,
+    # print the URL as is.
+    if is_ok
+    then print "${url_resolved}"
+    else print "${url}"
+    fi
 }
 
 # --------------------( COPYRIGHT AND LICENSE              )--------------------
