Substantially improved device handling.
Specifically, improved Zeshy Mount with "/boot" partition support, Zeshy
Terminal with a page_safely() regression fix, and ZeshyInit Alias with
exit status and return value handling. Also, added a conditional Zeshy
GRUB2 component.

diff --git a/src/autoload/always/shell/terminal b/src/autoload/always/shell/terminal
--- a/src/autoload/always/shell/terminal
+++ b/src/autoload/always/shell/terminal
@@ -46,12 +46,17 @@ get_terminal_width() {
     print "${COLUMNS}"  # also retrievable with "tput columns" (...overkill)
 }
 
+#FIXME: Rename page_safely() to page_nicely(). Rename all other *_safely()-style
+#functions, as well. (Other possible suffixes: page_well(), page_truly()). Hmmm;
+#no, page_nicely is the best fit. It reads well and best describes the
+#underlying intent.
 # ....................{ REDIRECTS                          }....................
 # char *page_safely(
 #   char *command_name, char *command_arg1, char *command_arg2, ...)
 #
 # Run the passed command with standard output and error piped to the current
-# pager if exceeding the terminal height or as is (i.e., without paging) if not.
+# pager if exceeding the terminal height or as is (i.e., without paging) if not,
+# returning the exit status of this command as its own.
 #
 # Customary pager commands block on standard input, thus delaying output until
 # after the input command completes operation. Resource-intensive commands not
@@ -69,7 +74,11 @@ page_safely() {
     #   only captures the former, this immediately prints all output produced by
     #   running such command.
     die_unless_at_least_one_arg 'expected a command'
-    string output="$(run "${(q)@}" 1>&1 1>&2)"
+    integer exit_status=${ZESHY_SUCCESS_CODE}
+    string output; output="$(run "${(q)@}" 1>&1 1>&2)" or exit_status=${?}
+
+    # Exit status of this command.
+#   integer exit_status="${?}"
 #   string output="$(eval "${(q)@}" 1>&1 1>&2)"
 #   string output="$((eval "${@}") 1>&1 1>&2)"
 #   utter "running: ${*}"
@@ -78,7 +87,7 @@ page_safely() {
 #   utter "terminal_height: $(get_terminal_height)"
 
     # If not outputting to a terminal of height less than the height of the
-    # output produced by such command, immediately return; otherwise, page.
+    # output produced by this command, immediately return; otherwise, page.
     if is_terminal and
       (( $(get_line_length "${output}") > $(get_terminal_height) )); then
         # Pager command to be run.
@@ -94,6 +103,11 @@ page_safely() {
         # Page.
         print "${output}" | "${pager[@]}"
     fi
+
+    # Return the exit status of this command.
+#   false
+#   utter "running: ${*}"
+    return "${exit_status}"
 }
 
 # ....................{ SETUP                              }....................
