Yet-another-extensive-commit.
I'm rather tired. Succinctly, this corrects the expected regressions
introduced by the prior commit's introduction of TRAPINT and TRAPZERR
signal trapping. The codebase is looking considerably stabler, if not
quite stable.

diff --git a/src/zeshy/shell/shell b/src/zeshy/shell/shell
--- a/src/zeshy/shell/shell
+++ b/src/zeshy/shell/shell
@@ -7,13 +7,193 @@
 #
 # * Command-line argument parsing fuctionality for specifying and obtaining
 #   shell script arguments. 
+
+# ....................{ DEPENDENCIES                       }....................
+zimport zeshy/file/file
+
+# ....................{ ARGUMENT PARSING                   }....................
+# void parse_arguments(char *argument_spec1, char *argument_spec2, ...)
 #
-# --------------------( TODO                               )--------------------
-# * Shell-specific components (e.g., "shell", "terminal", "style") should
-#   probably be centralized under a new "src/zeshy/shell" directory and this
-#   component renamed to ".main". Yes, this is *AWESOME*!
+# Parse command-line arguments according to the passed list of argument
+# specifications into the "${ARGS}" global associative array. For convenience,
+# this function always registers the "-h" and "--help" options as valid options.
+# This function delegates to the zparseopts() built-in function and thus expects
+# argument specifications in the same (relatively simple) format: e.g.,
+#
+#   # Parse command-line options, with "--ad" a long option accepting no
+#   # argument, "--crest" a long option requiring an argument, and "--wing" a
+#   # long argument accepting an optional argument.
+#   >>> set -- -d --ad --crest "glass arm shattering"
+#   >>> parse_arguments d e -ad -crest: -wing::
+#   >>> (( ${+ARGS[-d]} )) && echo 'option "-d" passed!'
+#   option "-d" passed!
+#   >>> (( ${+ARGS[-d]} + ${+ARGS[--ad]} )) &&
+#   >>>     echo 'option "-d" AND/OR option "--ad" passed!'
+#   option "-d" AND/OR option "--ad" passed!
+#   >>> echo "-d: ${ARGS[-d]}\n--ad: ${ARGS[--crest]}\n--wing: ${ARGS[--wing]}"
+#   -d:
+#   --crest: glass arm shattering
+#   --wing:
+#
+# For details, see the "zparseopts" section of "man zshmodules".
+alias parse_arguments='zparseopts -D -E -A ARGS -- h -help' 
+
+# void check_parsed_arguments(char *help_message)
+#
+# Check the set of all parsed arguments for unknown options. If the caller
+# passed at least one unknown option OR the "-h" or "--help" options, die with
+# the passed help message. This function expects to be called immediately after
+# calling the parse_arguments() function.
+check_parsed_arguments() {
+    #FIXME: This no longer works as intended, due to TRAPZERR(). Contemplate.
+    # If the immediately prior command failed, assume that was a call to the
+    # parse_arguments() function and enable a boolean noting this fact.
+    is_ok and bool is_parse_arguments_failed=1
+    
+    die_unless_one_argument 'expected exactly one help string'
+    string help_message="${1}"
+    
+    # If the caller passed the "-h" or "--help" options, die without error.
+    if (( "${+ARGS[-h]}" + "${+ARGS[--help]}" )); then
+        print "${help_message}"
+        exit_with_success
+    # If the caller passed unknown options, die without error.
+    elif (( "${+is_parse_arguments_failed}" )); then
+        print "${help_message}"
+        exit_with_failure
+    fi
+}
+
+# ....................{ SOURCING                           }....................
+#FIXME: Hmm. zimport() should probably do this by default for non-Zsh scripts.
+# char *source_safely(char *script_filename)
+#
+# Safely source the passed shell script by emulating the shell environment
+# expected by that script with default shell options and traps (e.g., a script
+# "mandibles_of_joy.sh" expects a Bourne rather than Zsh shell environment).
+source_safely() {
+    # Localize and validate arguments.
+    die_unless_arguments 'expected at least one filename'
+    string script_filename="${1}"
+    die_unless_file "${script_filename}"
+    string script_filetype="$(get_filetype "${script_filename}")"
+#   print "filetype: ${script_filetype}"
+
+    # Identify the shell to be emulated. If the passed filename's type
+    # identifies an emulatable shell, assume that. 
+    string script_shell='zsh' script_shells='zsh|sh|ksh|csh'
+    if is "${script_filetype}" == ${~script_shells} si; then
+        script_shell="${script_filetype}"
+    # Otherwise, grep the passed file's shebang line for an emulatable shell.
+    else
+        string script_shebang_regex="^#.*[/ ](${script_shells})($| )"
+        string script_shebang="$(head -1 "${script_filename}")"
+#       print "regex::: ${script_shebang_regex}"
+#       print "shebang: ${script_shebang}"
+#       match_first_group "${script_shebang_regex}" "${script_shebang}"
+        script_shell="$(match_first_group "${script_shebang_regex}" "${script_shebang}")" # or true
+    fi
+   
+    # Safely source the passed shell script. Dismantled, this is:
+    # 
+    # * "-R", resetting shell options to the default expected by such shell.
+    # * "-c", run the following command under such emulation.
+    emulate -R "${script_shell}" -c "source ${@}"
+}
+
+# ....................{ BIRTH ~ path                       }....................
+# void PATH_init(void)
+#
+# Set the ${PATH} for the current user.
+PATH_init() {
+    die_unless_no_arguments
+
+    # Store the prior ${PATH}, if any, for subsequent interpolation.
+    string PATH_old=
+    if is_nonempty "${ROOTPATH}" and is_superuser
+    then PATH_old="${ROOTPATH}"
+    else PATH_old="${PATH}"
+    fi
+
+    # Reset ${PATH} and conditionally append user-agnostic paths.
+    PATH_append '/usr/lib/colorgcc/bin'
+    PATH_append '/usr/local/bin'
+    PATH_append '/usr/bin'
+    PATH_append '/bin'
+
+    # If root, conditionally append root-specific paths.
+    if is_superuser; then
+        PATH_append '/usr/local/sbin'
+        PATH_append '/usr/sbin'
+        PATH_append '/sbin'
+    fi
+
+    # Append the prior $PATH.
+    PATH+=":${PATH_old}"
+
+    # Append the user-specific "~/bin/".
+    PATH_append "${HOME}/bin"
+
+    # Append Zeshy's "bin/".
+    string bin_dir="${ZESHY_HOME}/bin"
+    PATH_append "${bin_dir}"
+
+    # Append each command in Zeshy's "bin/command/" installed on this machine,
+    # matching all subdirectories of that directory via the "(/)" modifier.
+    string bin_command_dir bin_command_name
+    for    bin_command_dir in "${bin_dir}/command"/*(/); do
+        bin_command_name=$(basename "${bin_command_dir}")
+        is_installed "${bin_command_name}" and PATH_append "${bin_command_dir}"
+    done
+
+    # Export!
+    export PATH
+}
+
+# void PATH_append(char *dirname)
+#
+# Append the passed dirname onto the ${PATH}, if the corresponding directory
+# exists, is readable, and has not already been appended.
+PATH_append() {
+    die_unless_one_argument 'expected exactly one dirname'
+    string dirname="${1}"
+
+    if is -d "${dirname}" && -r "${dirname}" &&
+        ! "${PATH}" =~ "(^|:)${dirname}($|:)" si; then
+        if is_nonempty "${PATH}"
+        then PATH+=":${dirname}"
+        else PATH="${dirname}"
+        fi
+    fi
+}
 
 # ....................{ DEATH                              }....................
+# void return_success(void)
+#
+# Return from the current function with success.
+alias return_success="return ${ZESHY_SUCCESS_CODE}"
+
+# void return_failure(void)
+#
+# Return from the current function with failure.
+alias return_failure="return ${ZESHY_FAILURE_CODE}"
+
+# int exit_with_success(void)
+# 
+# Exit the current process with a successful return code.
+exit_with_success() {
+    die_unless_no_arguments
+    exit ${ZESHY_SUCCESS_CODE}
+}
+
+# int exit_with_failure(void)
+# 
+# Exit the current process with a failure return code.
+exit_with_failure() {
+    die_unless_no_arguments
+    exit ${ZESHY_FAILURE_CODE}
+}
+
 # void kill_callables(void)
 #
 # Destroy all existing aliases and functions. This is, of course, fairly
@@ -51,10 +231,8 @@ redot() {
     # this function definition calls no Zeshy-specific aliases or functions; the
     # the above call to the kill_callables() function has already killed them.
     source_if_found() {
-        [[ ${#} -eq 1 ]] || die 'expected exactly one filename'
         string script_name="${1}"
         if [[ -f "${script_name}" && -r "${script_name}" ]]; then
-            # Do not call the utter_import() function!
             print "redot: loading \"${script_name}\"..."
             source "${script_name}"
         fi
@@ -66,145 +244,24 @@ redot() {
     source_if_found "${HOME}/.zshrc"
     source_if_found '/etc/zsh/zlogin'
     source_if_found "${HOME}/.zlogin"
-}
 
-# ....................{ REBIRTH ~ path                     }....................
-# void PATH_init(void)
-#
-# Set the $PATH for the current user.
-PATH_init() {
-    die_unless_no_arguments
-
-    # Prior $PATH, if any.
-    string PATH_old=
-    if is_nonempty "${ROOTPATH}" and is_superuser
-    then PATH_old="${ROOTPATH}"
-    else PATH_old="${PATH}"
-    fi
-
-    # Reset $PATH, having recorded the prior $PATH.
-    PATH=
-
-    # Append all user-agnostic paths.
-    PATH_append '/usr/lib/colorgcc/bin'
-    PATH_append '/usr/local/bin'
-    PATH_append '/usr/bin'
-    PATH_append '/bin'
-
-    if is_superuser; then
-        PATH_append '/usr/local/sbin'
-        PATH_append '/usr/sbin'
-        PATH_append '/sbin'
-    fi
-
-    # Append the prior $PATH.
-    PATH+=":${PATH_old}"
-
-    # Append the user-specific "~/bin/".
-    PATH_append "${HOME}/bin"
-
-    # Append Zeshy's "bin/".
-    string zeshy_bin_dir="${ZESHY_HOME}/bin"
-    PATH_append "${zeshy_bin_dir}"
-
-    # Append each command in Zeshy's "bin/command/" installed on this machine,
-    # matching all subdirectories of that directory via the "(/)" modifier.
-    for zeshy_command_bin_dir in "${zeshy_bin_dir}/command"/*(/); do
-        command_name=$(basename "${zeshy_command_bin_dir}")
-        is_installed "${command_name}" and PATH_append "${zeshy_command_bin_dir}"
-    done
-
-    # Export!
-    export PATH
-}
-
-# void PATH_append(char *dirname)
-#
-# Append the passed dirname onto the $PATH, if the corresponding directory
-# exists, is readable, and has not already been appended.
-PATH_append() {
-    die_unless_one_argument 'expected exactly one argument'
-    string dirname="${1}"
-
-    if is -d "${dirname}" && -r "${dirname}" &&
-        ! "${PATH}" =~ "(^|:)${dirname}($|:)" si; then
-        if is_nonempty "${PATH}"
-        then PATH+=":${dirname}"
-        else PATH="${dirname}"
-        fi
-    fi
-}
-
-# ....................{ ARGUMENT PARSING                   }....................
-# void parse_arguments(char *argument_spec1, char *argument_spec2, ...)
-#
-# Parse command-line arguments according to the passed list of argument
-# specifications into the "${ARGS}" global associative array. For convenience,
-# this function always registers the "-h" and "--help" options as valid options.
-# This function delegates to the zparseopts() built-in function and thus expects
-# argument specifications in the same (relatively simple) format: e.g.,
-#
-#   # Parse command-line options, with "--ad" a long option accepting no
-#   # argument, "--crest" a long option requiring an argument, and "--wing" a
-#   # long argument accepting an optional argument.
-#   % set -- -d --ad --crest "glass arm shattering"
-#   % parse_arguments d e -ad -crest: -wing::
-#   % (( ${+ARGS[-d]} )) && echo 'option "-d" passed!'
-#   option "-d" passed!
-#   % (( ${+ARGS[-d]} + ${+ARGS[--ad]} )) &&
-#   %     echo 'option "-d" AND/OR option "--ad" passed!'
-#   option "-d" AND/OR option "--ad" passed!
-#   % echo "-d: ${ARGS[-d]}\n--ad: ${ARGS[--crest]}\n--wing: ${ARGS[--wing]}"
-#   -d:
-#   --crest: glass arm shattering
-#   --wing:
-#
-# For details, see the "zparseopts" section of "man zshmodules".
-alias parse_arguments='zparseopts -D -E -A ARGS -- h -help' 
-
-# void check_parsed_arguments(char *help_message)
-#
-# Check the set of all parsed arguments for unknown options. If the caller
-# passed at least one unknown option OR the "-h" or "--help" options, die with
-# the passed help message. This function expects to be called immediately after
-# calling the parse_arguments() function.
-check_parsed_arguments() {
-    # If the immediately prior command failed, assume that was a call to the
-    # parse_arguments() function and enable a boolean noting this fact.
-    is_ok and bool is_parse_arguments_failed=1
-    
-    die_unless_one_argument 'expected exactly one help string'
-    string help_message="${1}"
-    
-    # If the caller passed the "-h" or "--help" options, die without error.
-    if (( "${+ARGS[-h]}" + "${+ARGS[--help]}" )); then
-        print "${help_message}"
-        exit_with_success
-    # If the caller passed unknown options, die without error.
-    elif (( "${+is_parse_arguments_failed}" )); then
-        print "${help_message}"
-        exit_with_failure
-    fi
-}
-
-# ....................{ SHUTDOWN                           }....................
-# int exit_with_success(void)
-# 
-# Exit the current process with a successful return code.
-exit_with_success() {
-    die_unless_no_arguments
-    exit ${ZESHY_SUCCESS_CODE}
-}
-
-# int exit_with_failure(void)
-# 
-# Exit the current process with a failure return code.
-exit_with_failure() {
-    die_unless_no_arguments
-    exit ${ZESHY_FAILURE_CODE}
+    unfunction source_if_found
 }
 
 #FIXME: Obsolete.
+#   print "shell: ${script_shell}"
+#   emulate -R ${script_shell} -c "ls"
+#   emulate -R ${script_shell} -c "${@}"
+#   emulate -LR "${script_shell}"
+#   source ${@}
+
+    # Disable shell strictness for the duration of the sourcing. External shell
+    # scripts often assume laxness thus breaking under strictness.
+#   setopt nounset            # attempting to expand unset parameters raises an error
+#   setopt warn_create_global # attempting to set untyped parameters raises an error
+ 
+    # Reenable shell strictness. 
+
 #   of $(whence -w "${1}") =~ ': alias$' fo
 
 #   if [[ "${type}" == none ]]; then
