Significant revisions.
This commit is in support of "rtorrentd", an example Zeshy script
for daemonizing a popular command-line torrent client via "screen".

diff --git a/doc/examples/rtorrentd b/doc/examples/rtorrentd
--- a/doc/examples/rtorrentd
+++ b/doc/examples/rtorrentd
@@ -153,11 +153,17 @@
 #   (say, "VERBOSE") is also enabled.
 # * Perform automatic logging to a file when operating as a cronjob. (See
 #   "hg-cohere" for assistance, eh?)
+# * Consider enabling the "multiuser" screen option rather than using
+#   ZESHY_RUN_AS-style sudoing. That has several benefits, of which one is the
+#   ability to allow other users to open the deattached rtorrent session.
+
+# ....................{ IMPORTS                            }....................
+import zeshy/process
 
 # ....................{ CONFIGURATION ~ defaults           }....................
 # User under which screen is to be run. Ideally, this is the user intending to
 # foreground and actually use rtorrent.
-USER=$(whoami)
+ZESHY_RUN_AS=$(whoami)
 
 # Absolute path to the rtorrent binary.
 RTORRENT=$(which_binary rtorrent)
@@ -168,12 +174,11 @@ SCREEN=$(which_binary screen)
 # Screen session under which rtorrent is to be run.
 SCREEN_SESSION=rtorrent
 
-# File persisting the process ID (PID) for the run rtorrent process.
-PIDFILE="/var/run/rtorrent.${USER}.pid"
-
-# If non-empty, use the start-stop-daemon binary to automate process management
-# rather than manually managing processes.
-IS_USING_START_STOP_DAEMON=$(one_if is_installed start-stop-daemon)
+# Absolute path to the file persisting the process ID (PID) of the run rtorrent.
+if [[ "${ZESHY_RUN_AS}" == root ]]
+then RTORRENT_PIDFILE="/var/run/rtorrent-${USER}.pid"
+else RTORRENT_PIDFILE="${HOME}/.rtorrent-${USER}.pid"
+fi
 
 # ....................{ IMPLEMENTATION                     }....................
 restart() {
@@ -183,178 +188,203 @@ restart() {
 
 start() {
     # Wipe all outstanding "dead screens" for the target user.
-    quietly run_as "${USER}" "${SCREEN} -wipe"
-#   su -c "$SCREEN -wipe" "$USER" 1>/dev/null 2>&1 
+    quietly run "${SCREEN} -wipe"
 
     # If there are other rtorrent screen sessions running, warn and press on.
-    SCREEN_SESSION_COUNT=$(run_as "${USER}" su -c \
-        "$SCREEN -list | grep --count '\.${SCREEN_SESSION}[[:space:]]'" "$USER")
-    [ "$SCREEN_SESSION_COUNT" -eq 0 ] ||
-        ewarn "$SCREEN_SESSION_COUNT rtorrent screen session(s) already started."
+    local screen_session_count=$(run "${SCREEN} -list" |\
+        grep --count '\.${SCREEN_SESSION}[[:space:]]')
+    [[ "${screen_session_count}" -eq "${ZESHY_SUCCESS_CODE}" ]] ||
+        curse "${screen_session_count} rtorrent screen session(s) already started"
 
-    # Start rtorrent as a "start-stop-daemon"-managed screen session.
+    # Start rtorrent as a screen session. Note that screen's argument passing
+    # engine is fragile... Order is important in its list of arguments.
+    utter "starting rtorrent..."
+    run "${SCREEN}" -d -m -fa -U -S "${SCREEN_SESSION}" "${RTORRENT}"
+    
+    # If rtorrent fails to start, emit the cause thereof and fail.
+    local RTORRENT_RETURN_CODE="${?}"
+    [[ "${RTORRENT_RETURN_CODE}" -ne "${ZESHY_SUCCESS_CODE}" ]] &&\
+        curse_rtorrent_start_error
+
+    # Grep the PID of the screen process corresponding to the now-detached
+    # rtorrent session by asking screen itself.
+    local screen_pid=$(run "${SCREEN} -list" |\
+        grep --max-count=1 "\.${SCREEN_SESSION}[[:space:]]" |\
+        sed "s/^[[:space:]]*\([0-9][0-9]*\)\.${SCREEN_SESSION}[[:space:]].*$/\1/" -)
+    
+    # If "screen" lists no such rtorrent session for this user, fail.
+    if echo "${screen_pid}" | grep --quiet "^[[:space:]]*$"; then
+        curse "screen lists no rtorrent sessions"
+        curse_rtorrent_start_error
+    fi
+    
+    #FIXME: This is generally useful. Shift into the Zeshy Process component.
+    # Unfortunately, "$screen_pid" gives the process ID of the screen process
+    # hosting this rtorrent process rather than that rtorrent process itself. As
+    # halting this rtorrent process requires we have its ID rather than screen's
+    # ID, we now grep for that.
     #
-    # Note: screen's argument passing engine is... erroneous. Order is important
-    # in the list of arguments, below.
-    ebegin "Starting rtorrent"
-    start-stop-daemon --start --user "$USER" --chuid "$USER" --pidfile "$PIDFILE" \
-        --env HOME="/home/$USER" \
-        --exec "$SCREEN" -- -d -m -fa -U -S "$SCREEN_SESSION" "$RTORRENT"
+    # Note, however, that this rtorrent process may not yet have actually started
+    # up. Therefore, we wait a reasonable (!) number of seconds for it to start
+    # up; if it fails to do so, fail.
+    local rtorrent_pid
+    local start_time=$(date +"%s")          # current time in seconds since the Epoch
+    local close_time=(( $start_time + 8 ))  # current time plus eight seconds
+    while [[ $(date +"%s") -le ${close_time} ]]; do
+        rtorrent_pid=$(pgrep -P "${screen_pid}" -fx "${RTORRENT}")
+        
+        # If rtorrent is now running, break; otherwise, sleep and try again.
+        [[ "${?}" -eq "${ZESHY_SUCCESS_CODE}" ]] && break
+        sleep 1s
+    done
+    
+    # If rtorrent is still not running, fail.
+    if [[ -z "${rtorrent_pid}" ]]; then
+        curse "screen lists zombie rtorrent processes"
+        curse_rtorrent_start_error
+    fi
+    
+    # Store its PID into an external file for later use in shutting it down.
+    make_parent_directory_if_not_found "${RTORRENT_PIDFILE}"
+    try echo "${rtorrent_pid}" > "${RTORRENT_PIDFILE}"
 
-  # If rtorrent fails to start, fail and emit the cause thereof.
-        RTORRENT_RETURN_CODE=$?
-  if [ $RTORRENT_RETURN_CODE -ne 0 ]; then
-    eend $RTORRENT_RETURN_CODE "rtorrent could not be started!"
-    echo_rtorrent_start_error
-    return $RTORRENT_RETURN_CODE
-  fi
-
-  # "start-stop-daemon" makes a PID file having the (blatantly) wrong screen PID,
-  # when passing the "--make-pidfile" option. So we (cleverly) grep for the
-  # right screen PID and make a PID file having that PID, instead.
-  SCREEN_PID=$(su -c "$SCREEN -list" "$USER" | \
-    grep --max-count=1 "\.${SCREEN_SESSION}[[:space:]]" | \
-    sed "s/^[[:space:]]*\([0-9][0-9]*\)\.${SCREEN_SESSION}[[:space:]].*$/\1/" -)
-
-  # If "screen" lists no rtorrent session for the user under which
-  # "start-stop-daemon" should have started such an rtorrent session, fail.
-  if echo "$SCREEN_PID" | grep --quiet "^[[:space:]]*$"; then
-    eend   1 "screen lists no rtorrent sessions!"
-    echo_rtorrent_start_error
-    return 1
-  fi
-
-  # Unfortunately, "$SCREEN_PID" gives the process ID of the screen process
-  # hosting this rtorrent process rather than that rtorrent process itself. As
-  # halting this rtorrent process requires we have its ID rather than screen's
-  # ID, we now grep for that.
-  #
-  # Note, however, that this rtorrent process may not yet have actually started
-  # up. Therefore, we wait a reasonable (!) number of seconds for it to start
-  # up; if it fails to do so, fail.
-  START_TIME=$(date +"%s")            # current time in seconds since the Epoch
-  CLOSE_TIME=$(expr $START_TIME + 8)  # current time plus eight seconds
-  while [ $(date +"%s") -le $CLOSE_TIME ]; do
-    RTORRENT_PID=$(pgrep -P "$SCREEN_PID" -fx "$RTORRENT")
-
-    # If an rtorrent process is found, break out of this while loop;
-    # otherwise, sleep for one second and try again.
-    [ $? -eq 0 ] && break
-    sleep 1s
-  done
-
-  # If rtorrent is not running under the above user and screen process, then
-  # something went ghastly wrong! We fail with error. 
-  if [ -z "$RTORRENT_PID" ]; then
-    eend   1 "screen not running any rtorrent processes!"
-    echo_rtorrent_start_error
-    return 1
-  fi
-
-  # Store the rtorrent process ID grepped above into an external "$PIDFILE" for
-  # later use in shutting down the process.
-  echo "$RTORRENT_PID" > "$PIDFILE"
-  eend $?
+    utter "detached rtorrent PID ${rtorrent_pid} to screen PID ${screen_pid}"
 }
 
 stop() {
-  ebegin "Stopping rtorrent"
+    utter "stopping rtorrent..."
   
-  # Is rtorrent running?
-  RTORRENT_PIDS=$(pgrep -d ' ' -u "$USER" -fx "$RTORRENT")
-  RTORRENT_RUNNING=$?
+    # If not currently running, curse and return.
+    if ! is_running_as "${USER}" "${RTORRENT}"; then
+        curse "rtorrent not running"
+        return "${ZESHY_FAILURE_CODE}"
+    fi 
+    
+    # Signal numbers corresponding to soft and hard process termination.
+    local sigint=2 sigkill=9
 
-  # Is the rtorrent PID file found? If so, what are its contents?
-  $([ -f "$PIDFILE" ])
-  RTORRENT_PIDFILE_FOUND=$?
-  if [ $RTORRENT_PIDFILE_FOUND -eq 0 ]; then
-    RTORRENT_PID=$(cat "$PIDFILE")
+    # Number of seconds to wait after softly killing rtorrent before attempting
+    # to hardly kill it. (Sorry; puns galore.)
+    wait_seconds=10
+    
+    # Is the rtorrent PID file still exists, kill the corresponding process.
+    if [[ -f "${RTORRENT_PIDFILE}" ]]; then
+        # All rtorrent PIDs under this user.
+        local rtorrent_pids=$(get_pids_for_running_as "${USER}" "${RTORRENT}")
+        
+        # rtorrent PID as persisted in this file.
+        local rtorrent_pid=$(cat "${RTORRENT_PIDFILE}")
+        
+        # If the latter no longer corresponds to the former, curse and return.
+        if ! echo "${rtorrent_pids}" | grep --quiet "${rtorrent_pid}"; then
+            curse "user ${USER} no longer running rtorrent PID ${rtorrent_pid}"
+            return "${ZESHY_FAILURE_CODE}"
+        fi
+       
+        #FIXME: This is generally useful. Shift into the Zeshy Process component.
+        # Send the rtorrent session started above signal 2 (i.e., INT: interrupt) to
+        # persuade rtorrent to shutdown cleanly. Calling this same command without
+        # passing "--signal 2" causes rtorrent to shutdown non-cleanly, which
+        # customarily causes the next rtorrent session to hash-check the integrity of
+        # all incomplete torrents. That, in turn, can be a very time consuming
+        # process: one hour for each torrent gigabyte is a very long time indeed!
+        #
+        # Lastly note that this waits 10 seconds (e.g., "--retry 10") for the rtorrent
+        # session to shutdown cleanly before sending a definitive KILL signal. Since
+        # rtorrent documentation insists that rtorrent always shuts down cleanly
+        # within 5 seconds of an initial request, this should be more than long enough.
+        try kill -${sigint} "${rtorrent_pid}"
+        if is_running_pid "${rtorrent_pid}"; then
+            utter "waiting on rtorrent PID ${rtorrent_pid}..."
+            sleep ${wait_seconds}
 
-    #FIXME: Should "start-stop-daemon" handle this, or should I?
-    # Is the rtorrent PID stored in the above file actually the PID of a running
-    # rtorrent process? (If not, fail!)
-#   if ! echo "$RTORRENT_PIDS" | grep "$RTORRENT_PID" 1>/dev/null 2>&1; then
-#     eend   1 "rtorrent (PID $RTORRENT_PID) not running for user $USER!"
-#     return 1
-#   fi
-  else
-    RTORRENT_PID="???"
-  fi
+            if is_running_pid "${rtorrent_pid}"; then
+                utter "stopping rtorrent forcefully..."
+                try kill -${sigkill} "${rtorrent_pid}"
+            fi
+        fi
+        
+        # Remove the rtorrent PID file.
+        rm "${RTORRENT_PIDFILE}"
+    # Otherwise, the file has since been deleted, renamed, or otherwise moved. In
+    # that case, kill all rtorrents under this user.
+    else
+        utter "stopping all rtorrent processes under user ${USER}..."
+        quietly pkill -${sigint} -u "${USER}" -fx "${RTORRENT}"
 
-  # Send the rtorrent session started above signal 2 (i.e., INT: interrupt) to
-  # persuade rtorrent to shutdown cleanly. Calling this same command without
-  # passing "--signal 2" causes rtorrent to shutdown non-cleanly, which
-  # customarily causes the next rtorrent session to hash-check the integrity of
-  # all incomplete torrents. That, in turn, can be a very time consuming
-  # process: one hour for each torrent gigabyte is a very long time indeed!
-  #
-  # Lastly note that this waits 10 seconds (e.g., "--retry 10") for the rtorrent
-  # session to shutdown cleanly before sending a definitive KILL signal. Since
-  # rtorrent documentation insists that rtorrent always shuts down cleanly
-  # within 5 seconds of an initial request, this should be more than long enough.
-  SIGINT=2
-  WAIT_SECONDS=10
-  start-stop-daemon --stop --signal $SIGINT --pidfile "$PIDFILE" \
-    --retry $WAIT_SECONDS
-  RETURN_CODE=$?
-
-  # If rtorrent is not currently running, fail with a more specific error.
-  if [ $RTORRENT_RUNNING -ne 0 ]; then
-    eerror "rtorrent not currently running!"
-  # Otherwise, it is currently running.
-  else
-    # "start-stop-daemon" returns success when rtorrent is currently running
-    # but "$PIDFILE" does not exist; it should return failure, since it will
-    # have been unable to shutdown rtorrent in this case.
-    #
-    # We force failure in this case so as to gracefully recover later.
-    if [ $RTORRENT_PIDFILE_FOUND -ne 0 ]; then RETURN_CODE=1; fi
-
-    # If "start-stop-daemon" returned failure, attempt to gracefully recover.
-    if [ $RETURN_CODE -ne 0 ]; then
-      # Print an appropriate error message.
-      if [ $RTORRENT_PIDFILE_FOUND -ne 0 ]; then
-        eend $RETURN_CODE "rtorrent could not be stopped, since "\
-          "PID file '$PIDFILE' not found!"
-      else
-        eend $RETURN_CODE "rtorrent (PID $RTORRENT_PID) could not be stopped!"
-      fi
-
-      # If the above "start-stop-daemon" command failed it was probably due to the
-      # $PIDFILE having the PID for the previously started rtorrent process having
-      # since been deleted, renamed, or otherwise moved. In that case, killing all
-      # rtorrent processes owned by the target user should have the same effect.
-      ebegin "Stopping rtorrent forcefully..."
-      pkill -signal "$SIGINT" -u "$USER" -fx "$RTORRENT"
-
-      # Wait several seconds to ensure rtorrent shutdown cleanly.
-      sleep ${WAIT_SECONDS}s
-
-      # Grep the process list to check rtorrent shutdown cleanly.
-      pgrep -u "$USER" -fx "$RTORRENT"
-      RETURN_CODE=$?
+        if is_running_as "${USER}" "${RTORRENT}"; then
+            utter "waiting on all rtorrent processes under user ${USER}..."
+            sleep ${wait_seconds}
+             
+            if is_running_as "${USER}" "${RTORRENT}"; then
+                utter "stopping all rtorrent processes under user ${USER} forcefully..."
+                quietly pkill -${sigkill} -u "${USER}" -fx "${RTORRENT}"
+            fi
+        fi
     fi
-  fi
-
-    eend $RETURN_CODE
-  return $RETURN_CODE
 }
 
 # ....................{ UTILITIES                          }....................
-# void echo_rtorrent_start_error()
+# void curse_rtorrent_start_error()
 #
 # If rtorrent failed to run for any reason other than it is already running
 # under an existing "screen" session, then print this reason by re-running
 # rtorrent as the target user.
-echo_rtorrent_start_error() {
-    if [[ -n "${SCREEN_PID}" ]]
-    then einfo "rtorrent (for user ${USER} and screen PID ${SCREEN_PID}) fails with:"
-    else einfo "rtorrent (for user ${USER}) fails with:"
+curse_rtorrent_start_error() {
+    if [[ -n "${screen_pid}" ]]
+    then curse "rtorrent startup error for user ${USER} under screen PID ${screen_pid}:"
+    else curse "rtorrent startup error for user ${USER}:"
     fi
-
-    [[ -z "${SCREEN_SESSION_COUNT}" || "${SCREEN_SESSION_COUNT}" -eq 0 ]] && \
-        su -c "${RTORRENT" "$USER}"
+    
+    # Print the error, then die.
+    [[ -z "${screen_session_count}" || "${screen_session_count}" -eq 0 ]] &&\
+        run "${RTORRENT}"
+    exit "${ZESHY_FAILURE_CODE}"
 }
+
+# ....................{ MAIN                               }....................
+[[ "${#}" -eq 1 ]] || die 'expected exactly one action'
+
+# Action requested by the user.
+ACTION="${1}"
+
+# Ensure sanity.
+case "${ACTION}" in
+    start)   start ;;
+    stop)    stop ;;
+    restart) restart ;;
+    *) die "\"${ACTION}\" not a recognized action" ;;
+esac
+
+#FIXME: Obsolete.
+# If non-empty, use the start-stop-daemon binary to automate process management
+# rather than manually managing processes.
+#IS_USING_START_STOP_DAEMON=$(one_if is_installed start-stop-daemon)
+
+#   start-stop-daemon --start --user "$USER" --chuid "$USER" --pidfile "$RTORRENT_PIDFILE" \
+#       --env HOME="/home/$USER" \
+#       --exec "$SCREEN" -- -d -m -fa -U -S "$SCREEN_SESSION" "$RTORRENT"
+
+    # "start-stop-daemon" makes a PID file having the (blatantly) wrong screen PID,
+    # when passing the "--make-pidfile" option. So we (cleverly) grep for the
+    # right screen PID and make a PID file having that PID, instead.
+
+    # "start-stop-daemon" returns success when rtorrent is currently running
+    # but "$RTORRENT_PIDFILE" does not exist; it should return failure, since it will
+    # have been unable to shutdown rtorrent in this case.
+    #
+    # We force failure in this case so as to gracefully recover later.
+#   if [ $rtorrent_pidfile_found -ne 0 ]; then RETURN_CODE=1; fi
+
+#   # If "start-stop-daemon" returned failure, attempt to gracefully recover.
+#   if [ $RETURN_CODE -ne 0 ]; then
+#     # Print an appropriate error message.
+#     if [ $rtorrent_pidfile_found -ne 0 ]; then
+#       eend $RETURN_CODE "rtorrent could not be stopped, since "\
+#         "PID file '$RTORRENT_PIDFILE' not found!"
+#     else
+#       eend $RETURN_CODE "rtorrent (PID $rtorrent_pid) could not be stopped!"
+#     fi
 
 # --------------------( COPYRIGHT AND LICENSE              )--------------------
 # The information below applies to everything in this distribution,
diff --git a/src/zeshy/core b/src/zeshy/core
--- a/src/zeshy/core
+++ b/src/zeshy/core
@@ -15,8 +15,6 @@
 # * Use the "vcs_info" Zsh module for displaying VCS-specific metadata in a VCS-
 #   agnostic fashion.
 # * Incorporate ZSH-lovers fixes, including:
-#   * Use "zparseopts" instead of "getopt" for script functions intended to be
-#     called from the command-line as well as for external shell scripts. Nice!
 #   * Use suffix aliases.
 
 # ....................{ PATHS                              }....................
@@ -112,14 +110,15 @@ zsh-mime-setup
 
 # ....................{ MODULES                            }....................
 # Zsh modules are C-implemented shared libraries optionally loadable at runtime.
-# Zeshy loads the following Zsh modules.
+# Zeshy loads the following Zsh modules by default, due to their common
+# helpfulness.
 
-# Parameter module exposing Zsh's C-based internal hashes via Zsh-based
-# associative arrays. We are particularly interested in these:
+# Module exposing Zsh's C-based internal dictionaries as Zsh-based associative
+# arrays, including:
 #
 # * "$funcstack", having the current function call stack for user inspection.
 # * "$functions", having the current set of all functions for redefinition and
-# later restoration of differing function definitions.
+#   later restoration of differing function definitions.
 zmodload zsh/parameter
 
 # Perl-Compatible Regular Expression (PCRE) module. Note that, although
@@ -133,9 +132,21 @@ zmodload zsh/pcre
 
 # Stat module wrapping the stat() system call with the zstat() Zsh function. Do
 # not load this module via "zmodload zsh/stat", as that wraps the stat() system
-# call with the default stat() Zsh function, which conflicts with "stat"
+# call with the default stat() Zsh function, conflicting with the "stat"
 # binary.
 zmodload -F zsh/stat b:zstat
+
+# Utility module adding additional built-ins, including:
+#
+# * "zparseopts", parsing command-line arguments. This built-in is similar in
+#   function if not style to the "getopts" binary, and typically used like so:
+#
+#   >>> set -- -d --ad "glass arm shattering"
+#   >>> zparseopts -A args -- d e -ad: -wing:
+#   >>> echo "-d: ${args[-d]}\n--ad: ${args[--ad]}"
+#   -d:
+#   --ad: glass arm shattering
+zmodload zsh/zutil
 
 # ....................{ OPTIONS                            }....................
 # Command history.
@@ -187,8 +198,8 @@ setopt prompt_subst
 # http://zsh.sourceforge.net/Doc/Release/Zsh-Modules.html#SEC192
 #
 # Note that traditional glob matching is always available via the "==" test
-# operator: e.g., [[ $(whence -cp fahey) == *" not found" ]] && echo
-# "Farewell."
+# operator: e.g.,
+#     [[ $(whence -cp fahey) == *" not found" ]] && echo "Farewell."
 setopt rematch_pcre      # prefer Perl-Compatible Regular Expression matching
 
 # Tab completion.
@@ -319,9 +330,9 @@ die() {
     # If the return code of the prior command signifies an error, exit with
     # that return code; otherwise, exit with generic error code 1.
     local return_code
-    if [[ ${?} -gt 0 ]]
-    then return_code=${?}
-    else return_code=1
+    if [[ "${?}" -ne "${ZESHY_SUCCESS_CODE}" ]]
+    then return_code="${?}"
+    else return_code="${ZESHY_FAILURE_CODE}"
     fi
     
     # A pox on ye, buggy fiend!
@@ -339,6 +350,15 @@ die() {
 }
 
 # ....................{ COMMANDS                           }....................
+# bool is_callable(char *name)
+#
+# Return true if there exists an alias or function with the passed name.
+is_callable() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one name"
+    [[ $(whence -w "${1}") =~ ': (alias|builtin|function)$' ]]
+}
+
+# ....................{ COMMANDS                           }....................
 # Aliases.
 alias is_available="is_runnable"
 alias is_installed="is_runnable"
@@ -351,18 +371,6 @@ alias is_installed="is_runnable"
 #     >>> is_runnable bash && echo "Alas, but Bash is installed!" Alas, but
 #     Bash is installed!
 is_runnable() { quietly which_binary_nonfatal "${@}" }
-
-# bool is_running(char *command)
-#
-# Return true if there exists a process running under the passed binary name:
-# e.g.,
-#
-#     >>> is_running zsh && echo "The zealous zephyr has landed." The zealous
-#     zephyr has landed.
-is_running() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one command"
-    quietly pidof -s "${1}"
-}
 
 # void try_as_superuser(char *command)
 #
@@ -390,13 +398,14 @@ run_as_superuser() {
 run_as() {
     [[ "${#}" -ge 2 ]] || die 'expected exactly one username and one command'
 
-    # Locally set ${RUN_AS}. The run() function notes this variable as being
+    # Locally set ${ZESHY_RUN_AS}. The run() function notes this variable as being
     # set and behaves accordingly.
-    local RUN_AS="${1}"
+    local ZESHY_RUN_AS="${1}"
 
     # Remove the passed user from the argument list and call "run" with all
     # remaining arguments: namely the command to be run.
-    shift run "${@}"
+    shift
+    run "${@}"
 }
 
 # void run(char *command)
@@ -427,29 +436,37 @@ run() {
     #
     # The '#' parameter expansion returns the number of such words. (Phew!)
     local argument_count=${#${=@}}
-    [[ "${argument_count}" -ge 1 ]] ||
-        die 'expected exactly one command'
+    [[ "${argument_count}" -ge 1 ]] || die 'expected exactly one command'
     
-    # If the passed command to run actually exists, run it under it "nice" and
-    # "ionice"; otherwise, the command is probably a builtin shell command and
-    # must be run inside an eval() statement. (If the passed shell command is
-    # run outside of such a statement, strange and horrible things happen.)
-    if is_runnable "${1}"; then
+    # Command to be run, which is the first word of the first passed parameter.
+    local command_name="${1[(w)1]}"
+    
+    # If the passed command to run actually exists, run it as a shell command.
+    if is_runnable "${command_name}"; then
         # If the caller requests this command be run under a different user,
         # attempt to do so.
-        if [[ -n "${RUN_AS}" && "${RUN_AS}" != $(whoami) ]]; then
+        if [[ -n "${ZESHY_RUN_AS}" && "${ZESHY_RUN_AS}" != $(whoami) ]]; then
             # If the desired user is the superuser, use "sudo" to take
             # advantage of password caching.
-            if [[ "${RUN_AS}" == 'root' ]] && is_runnable sudo
+            if [[ "${ZESHY_RUN_AS}" == 'root' ]] && is_runnable sudo
             then sudo -E "${NICE} ${IONICE} ${@}"
             # Otherwise, use "su".
             else su --preserve-environment\
-                    --command "${NICE} ${IONICE} ${@}" "${RUN_AS}"
+                    --command "${NICE} ${IONICE} ${@}" "${ZESHY_RUN_AS}"
         fi
         # Otherwise, run this command as the current user.
         else eval "${NICE} ${IONICE} ${@}"
+#       else "${NICE}" "${IONICE}" "${@}"
         fi
-    else eval "${@}"
+    # Otherwise, if the passed command is a shell built-in, run it inside an
+    # eval statement. (If this command is run outside of such a statement,
+    # strange and hideous things occur.)
+    elif is_callable "${command_name}"; then
+        eval "${@}"
+    # Otherwise, fail.
+    else 
+        die "\"${command_name}\" not found"
+#       die "\"${command_name}\" not found, so cannot run:\n\t${@}"
     fi
 }
 
@@ -462,15 +479,15 @@ run() {
 #     >>> IS_MUTT_INSTALLED=$(one_if is_installed mutt)
 #     >>> echo "${IS_MUTT_INSTALLED}"
 #     1
-#     >>> [[ -n "${IS_MUTT_INSTALLED}" ]] && echo
-#     "mutt!" mutt!
+#     >>> (( "${+IS_MUTT_INSTALLED}" )) && echo 'mutt\!'
+#     mutt!
 # 
 # Note, commands should be passed as quoted strings to prevent the calling
 # shell from evaluating pipes, redirections, et al. prior to passing the
 # command. (See the run() function, above.)
 one_if() {
     quietly "${@}"
-    [[   "${?}" -eq 0 ]] && echo 1
+    [[ "${?}" -eq 0 ]] && echo 1
 }
 
 # void quietly(char *command)
@@ -508,6 +525,17 @@ get_current_process_id() {
 canonicalize_path() {
     [[ "${#}" -eq 1 ]] || die "expected exactly one path"
     try readlink --canonicalize-existing "${1}"
+}
+
+# char *canonicalize_path_nonfatal(char *path)
+#
+# Get the canonicalized form of the passed absolute path. Unlike the
+# canonicalize_path() function, this function does not raise an exception when
+# the passed path does not exist; it simply canonicalizes as much of this path
+# as exists.
+canonicalize_path_nonfatal() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one path"
+    try readlink --canonicalize-missing "${1}"
 }
 
 # int get_path_mtime(char *path)
@@ -635,19 +663,29 @@ make_directory_if_not_found() {
 #     # Actually imports "zeshy/os/main".
 #     >>> import zeshy/os
 import() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one script name"
+    [[ "${#}" -ge 1 ]] || die "expected one script name"
     
-    # Passed script name.
+    # Passed script name. Shift it off the argument stack, to allow us to pass
+    # this script the set of all remaining arguments on sourcing it below.
     local script_name="${1}" 
+    shift
 
     # Absolute path to this script.
     local script_path 
+    
+    # If the passed script name is an absolute path, canonicalize the path so as
+    # to ensure the dictionary lookup below successfully compares the path
+    # against a previously canonicalized entry in this dictionary.
+    if [[ "${script_name[1]}" == '/' ]]; then
+        script_path="$(canonicalize_path "${script_name}")"
+    # Otherwise, if the passed script is an existing relative path, again
+    # canonicalize this path.
+    else
+        script_path="$(canonicalize_path_nonfatal "${script_name}")"
 
-    # If the passed script name is not an absolute path, use it.
-    if [[ "${script_name[1]}" == '/' ]]
-    then script_path="${script_name}"
-    # Otherwise, it is a basename. Resolve this into an absolute path.
-    else script_path="${ZESHY_HOME}/${script_name}"
+        # Otherwise, the passed script is a Zeshy component, in which case no
+        # additional canonicalization is required.
+        [[ -e "${script_path}" ]] || script_path="${ZESHY_HOME}/${script_name}"
     fi
     
     # If the absolute path refers to a directory, assume the caller wants a
@@ -656,11 +694,6 @@ import() {
     
     # If this path does not exist, die.
     [[ -f "${script_path}" ]] || die "\"${script_path}\" not found"
-    
-    # Canonicalize the passed path. Failing to do this could hypothetically
-    # prevent the passed path from being successfully looked up in the path
-    # dictionary, below.
-    script_path="$(canonicalize_path "${script_path}")"
     
     # Modification time of this script.
     local script_mtime="$(get_path_mtime "${script_path}")"
@@ -677,7 +710,7 @@ import() {
          
         # Do so.
         utter_import "${script_path}"
-        source "${script_path}"
+        source "${script_path}" "${@}"
     fi
 }
 
diff --git a/src/zeshy/process b/src/zeshy/process
--- a/src/zeshy/process
+++ b/src/zeshy/process
@@ -6,6 +6,73 @@
 # Zeshy Process. This Zeshy component implements supplementary process-handling
 # functionality, over and above that already implemented by Zeshy Core.
 
+# ....................{ JOBS                               }....................
+# int[] get_pids_for_running_as(char *username, char *command)
+#
+# Get the process IDs for all processes running under the passed username having
+# the passed binary name.
+get_pids_for_running_as() {
+    [[ "${#}" -eq 2 ]] || die "expected exactly one username and one command"
+    pgrep -u "${1}" -fx "${2}" 2>/dev/null
+}
+
+# ....................{ JOBS ~ booleans                    }....................
+# bool is_previous_process_failed(void)
+#
+# Return success if the previous process failed. Otherwise, return failure.
+is_previous_process_failed() {
+    [[ "${#}" -eq 0 ]] || die "expected no arguments"
+    if [[ "${?}" -ne "${ZESHY_SUCCESS_CODE}" ]]
+    then return "${ZESHY_SUCCESS_CODE}"
+    else return "${ZESHY_FAILURE_CODE}"
+    fi
+}
+
+# bool is_previous_process_succeeded(void)
+#
+# Return success if the previous process succeeded. Otherwise, return failure.
+is_previous_process_succeeded() {
+    [[ "${#}" -eq 0 ]] || die "expected no arguments"
+    if [[ "${?}" -eq "${ZESHY_SUCCESS_CODE}" ]]
+    then return "${ZESHY_SUCCESS_CODE}"
+    else return "${?}"
+    fi
+}
+
+# bool is_running(char *command)
+#
+# Return true if there exists a process running under any user having the
+# passed binary name: e.g.,
+#
+#     >>> is_running zsh && echo "The zealous zephyr is lousy."
+#     The zealous zephyr is lousy.
+is_running() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one command"
+    quietly pidof -s "${1}"
+}
+
+# bool is_running_as(char *username, char *command)
+#
+# Return true if there exists a process running under the passed username
+# having the passed binary name.
+is_running_as() {
+    [[ "${#}" -eq 2 ]] || die "expected exactly one username and one command"
+    quietly get_pids_for_running_as "${@}"
+}
+
+# bool is_running_pid(int pid)
+#
+# Return true if there exists a process running under the passed process ID:
+# e.g.,
+#
+#     >>> sleep 10s &
+#     >>> is_running_pid $! && echo "Sleepy, so sleepy..."
+#     Sleepy, so sleepy...
+is_running_pid() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one process ID"
+    quietly kill -0 "${1}"
+}
+
 # --------------------( COPYRIGHT AND LICENSE              )--------------------
 # The information below applies to everything in this distribution,
 # except where noted.
