Fixed additional issues in "rtorrentd".

diff --git a/src/zeshy/core b/src/zeshy/core
--- a/src/zeshy/core
+++ b/src/zeshy/core
@@ -382,7 +382,9 @@ try_as_superuser() { run_as_superuser "${@}" || die }
 #
 # Run the passed command and, if it fails with error, terminate the current
 # execution environment with the same error.
-try() { run "${@}" || die }
+try() {
+    run "${@}" || die "\"${@}\" returned error code ${?}"
+}
 
 # void run_as_superuser(char *command)
 #
@@ -446,13 +448,18 @@ run() {
         # If the caller requests this command be run under a different user,
         # attempt to do so.
         if [[ -n "${ZESHY_RUN_AS}" && "${ZESHY_RUN_AS}" != $(whoami) ]]; then
+            #FIXME: Not quite right. If "${@}" contains double quotes, that
+            #conflicts with our use of double quotes here. The solution is to
+            #translate all non-escaped double quotes to single quotes. Simple?
             # If the desired user is the superuser, use "sudo" to take
             # advantage of password caching.
-            if [[ "${ZESHY_RUN_AS}" == 'root' ]] && is_runnable sudo
-            then sudo -E "${NICE} ${IONICE} ${@}"
+            if [[ "${ZESHY_RUN_AS}" == 'root' ]] && is_runnable sudo; then
+                sudo -E "${NICE} ${IONICE} ${@}"
             # Otherwise, use "su".
-            else su --preserve-environment\
-                    --command "${NICE} ${IONICE} ${@}" "${ZESHY_RUN_AS}"
+            else
+#               echo "suing: ${@} ${ZESHY_RUN_AS}"
+                su --preserve-environment\
+                   --command "${NICE} ${IONICE} ${@}" "${ZESHY_RUN_AS}"
         fi
         # Otherwise, run this command as the current user.
         else eval "${NICE} ${IONICE} ${@}"
