Extensive mimetype-centric commit.
This commit introduces two new Zeshy components, Zeshy Mime and
dot2tex, as well as a variety of new tests, utility functions, and
extraneous usefulness.

diff --git a/src/zeshy/core b/src/zeshy/core
--- a/src/zeshy/core
+++ b/src/zeshy/core
@@ -10,6 +10,10 @@
 # * Core Zsh modules and options.
 # * Core I/O-, error-, file-, and path-handling functions.
 #
+# --------------------( SEE ALSO                           )--------------------
+# http://www.bash2zsh.com/essays/essay1_file_manager.html
+#   Brilliant introduction to suffix aliases, mime types, and file magic.
+#
 # --------------------( TODO                               )--------------------
 # * Add "$IS_CRON" support.
 # * Use the "vcs_info" Zsh module for displaying VCS-specific metadata in a VCS-
@@ -92,18 +96,10 @@ export ZESHY_SCRIPT_NAME=
 # the current file. This is a history modifier extracting each file's filename
 # sans absolute path.
 # 
-for autoload_function_name in $^fpath/*(N-.r:t); do
+for autoload_function_name in ${^fpath}/*(N-.r:t); do
+#   print "autoloading \"${autoload_function_name}\"..."
     autoload -U "${autoload_function_name}"
 done
-
-# Suffix aliases. (This enables BSD-style file opening, by associating file
-# suffixes with an application responsible for opening files of that suffix.
-# Thus, for example, you may open some PDF-file "/tmp/blandishment.pdf" by
-# simply typing that filename at the shell prompt. You must, however, edit
-# "/etc/mailcap" to add MIME-type handlers custom for your system: by adding,
-# for example, a new "application/pdf;/usr/local/bin/acroread %s" line to this
-# file, to open PDF-files with Adobe Acrobat.)
-zsh-mime-setup
 
 # zmv. "zmv" is a built-in shell function applying extended glob patterns to
 # the usual "mv" command, thus allowing batch renaming of file- and path-names.
@@ -167,9 +163,10 @@ setopt pushdignoredups   # don't push dups on stack
 setopt pushdsilent       # be quiet about pushds and popds
 
 # File globbing.
-setopt extendedglob      # use extended globbing (#, ~, ^)
-setopt globdots          # don't require a dot ('.') to be specifically
-setopt no_nomatch        # don't emit an error for non-matching globs
+unsetopt caseglob        # glob case-insensitively, as this is usually desirable
+setopt extendedglob      # enable extended globbing (#, ~, ^)
+setopt globdots          # ???
+setopt no_nomatch        # don't print errors on non-matching globs
 
 # I/O.
 setopt interactivecomments  # allow '#' comments in interactive commands
@@ -217,12 +214,101 @@ setopt nolistambiguous   # only list matches if ambiguous
 # commands and thus always returns success.
 alias noop=':'
 
-# ....................{ ENVIRONMENT                        }....................
+# ....................{ ALIASES ~ arguments                }....................
+# Define critical argument-specific aliases prior to defining functions
+# expanding these aliases. Otherwise, error ensues.
+
+#FIXME: The word "arguments" should probably be truncated to "args", here.
+#Rewriting "arguments" every function is slightly silly (and cumbersome).
+
+# bool is_no_arguments(void)
+#
+# Return success if this function was called with no arguments. Otherwise,
+# return failure.
+alias is_no_arguments='[[ ${#} -eq 0 ]]'
+
+# bool is_one_argument(void)
+#
+# Return success if this function was called with one argument. Otherwise,
+# return failure.
+alias is_one_argument='[[ ${#} -eq 1 ]]'
+
+# bool is_two_argument(void)
+#
+# Return success if this function was called with two arguments. Otherwise,
+# return failure.
+alias is_two_arguments='[[ ${#} -eq 2 ]]'
+
+# bool is_at_least_one_argument(void)
+#
+# Return success if this function was called with at least one argument.
+# Otherwise, return failure.
+alias is_at_least_one_argument='[[ ${#} -ge 1 ]]'
+
+# bool is_at_least_two_arguments(void)
+#
+# Return success if this function was called with at least two arguments.
+# Otherwise, return failure.
+alias is_at_least_two_arguments='[[ ${#} -ge 2 ]]'
+
+# ....................{ ALIASES ~ arguments ~ errors       }....................
+# As a convenience, all argument aliases except die_unless_no_arguments() first
+# attempt to read their argument from stdin when the caller passed no explicit
+# argument. This implies all functions expanding these aliases implicitly "get"
+# piped input support, which is nice.
+
+# void die_unless_no_arguments(void)
+#
+# Die with a canonical error message unless the caller passed no arguments.
+alias die_unless_no_arguments='[[ ${#} -eq 0 ]] || die "expected no arguments"'
+
+# void die_unless_one_argument(void)
+#
+# Die with the passed error message unless the caller passed exactly one
+# argument.
+alias die_unless_one_argument='if [[ ${#} -eq 0 ]]; then set -- "$(< /dev/stdin)"; fi; [[ ${#} -eq 1 ]] || die'
+
+# void die_unless_two_arguments(void)
+#
+# Die with the passed error message unless the caller passed exactly two
+# arguments.
+alias die_unless_two_arguments='if [[ ${#} -eq 1 ]]; then set -- "${1}" "$(< /dev/stdin)"; fi; [[ ${#} -eq 2 ]] || die'
+
+# void die_unless_at_least_one_argument(void)
+#
+# Die with the passed error message unless the caller passed at least one
+# argument.
+alias die_unless_at_least_one_argument='if [[ ${#} -eq 0 ]]; then set -- "$(< /dev/stdin)"; fi; [[ ${#} -ge 1 ]] || die'
+
+# void die_unless_at_least_two_arguments(void)
+#
+# Die with the passed error message unless the caller passed at least one
+# argument.
+alias die_unless_at_least_two_arguments='if [[ ${#} -eq 1 ]]; then set -- "${1}" "$(< /dev/stdin)"; fi; [[ ${#} -ge 2 ]] || die'
+
+# ....................{ TESTS                              }....................
+# bool is(char *string)
+#
+# Return success if the passed string is non-empty.
+is() {
+    die_unless_one_argument 'expected exactly one string'
+    [[ -n "${1}" ]]
+}
+
+# bool is_not(char *string)
+#
+# Return success if the passed string is empty.
+is_not() {
+    die_unless_one_argument 'expected exactly one string'
+    [[ -z "${1}" ]]
+}
+
 # bool is_cronjob(void)
 #
 # Return success if the current shell is a cronjob (i.e., is the grandchild of
 # a "cron" process).
 is_cronjob() {
+    die_unless_no_arguments
     [[ -n "${ZESHY_IS_CRONJOB}" ]]
 }
 
@@ -230,6 +316,7 @@ is_cronjob() {
 #
 # Return success if the current shell is interactive or is a login shell.
 is_shell_interactive() {
+    die_unless_no_arguments
     [[ -o interactive || -o login ]]
 }
 
@@ -242,6 +329,7 @@ is_shell_interactive() {
 #
 #     stty: standard input: Invalid argument
 is_terminal() {
+    die_unless_no_arguments
     [[ -t 0 ]]
 }
 
@@ -347,7 +435,7 @@ curse() {
 # imported. This function should be called prior to actually importing that
 # script if feasible.
 utter_import() {
-    [[ ${#} -eq 1 ]] || die "expected exactly one script name"
+    die_unless_one_argument 'expected exactly one script name'
 
     # If the caller has supplied no explicit "${ZESHY_SCRIPT_NAME}", supply a
     # default.  Failing to do this encourages the utter() function to use the
@@ -384,75 +472,6 @@ die() {
     else exit ${return_code}
     fi
 }
-
-# ....................{ ARGUMENTS ~ tests                  }....................
-# Define critical argument-specific aliases prior to defining functions
-# expanding these aliases. Otherwise, error ensues.
-
-# bool is_no_arguments(void)
-#
-# Return success if this function was called with no arguments. Otherwise,
-# return failure.
-alias is_no_arguments='[[ ${#} -eq 0 ]]'
-
-# bool is_one_argument(void)
-#
-# Return success if this function was called with one argument. Otherwise,
-# return failure.
-alias is_one_argument='[[ ${#} -eq 1 ]]'
-
-# bool is_two_argument(void)
-#
-# Return success if this function was called with two arguments. Otherwise,
-# return failure.
-alias is_two_arguments='[[ ${#} -eq 2 ]]'
-
-# bool is_at_least_one_argument(void)
-#
-# Return success if this function was called with at least one argument.
-# Otherwise, return failure.
-alias is_at_least_one_argument='[[ ${#} -ge 1 ]]'
-
-# bool is_at_least_two_arguments(void)
-#
-# Return success if this function was called with at least two arguments.
-# Otherwise, return failure.
-alias is_at_least_two_arguments='[[ ${#} -ge 2 ]]'
-
-# ....................{ ARGUMENTS ~ exceptions             }....................
-# As a convenience, all argument aliases except die_unless_no_arguments() first
-# attempt to read their argument from stdin when the caller passed no explicit
-# argument. This implies all functions expanding these aliases implicitly "get"
-# piped input support, which is nice.
-
-# void die_unless_no_arguments(void)
-#
-# Die with a canonical error message unless the caller passed no arguments.
-alias die_unless_no_arguments='[[ ${#} -eq 0 ]] || die "expected no arguments"'
-
-# void die_unless_one_argument(void)
-#
-# Die with the passed error message unless the caller passed exactly one
-# argument.
-alias die_unless_one_argument='if [[ ${#} -eq 0 ]]; then set -- "$(< /dev/stdin)"; fi; [[ ${#} -eq 1 ]] || die'
-
-# void die_unless_two_arguments(void)
-#
-# Die with the passed error message unless the caller passed exactly two
-# arguments.
-alias die_unless_two_arguments='if [[ ${#} -eq 1 ]]; then set -- "${1}" "$(< /dev/stdin)"; fi; [[ ${#} -eq 2 ]] || die'
-
-# void die_unless_at_least_one_argument(void)
-#
-# Die with the passed error message unless the caller passed at least one
-# argument.
-alias die_unless_at_least_one_argument='if [[ ${#} -eq 0 ]]; then set -- "$(< /dev/stdin)"; fi; [[ ${#} -ge 1 ]] || die'
-
-# void die_unless_at_least_two_arguments(void)
-#
-# Die with the passed error message unless the caller passed at least one
-# argument.
-alias die_unless_at_least_two_arguments='if [[ ${#} -eq 1 ]]; then set -- "${1}" "$(< /dev/stdin)"; fi; [[ ${#} -ge 2 ]] || die'
 
 # ....................{ ERRORS ~ paths                     }....................
 # void die_unless_dir(char *dirname)
@@ -679,8 +698,6 @@ run_as_superuser() {
 }
 
 # ....................{ COMMANDS ~ quietly                 }....................
-alias is=quietly
-
 # int one_if(char *command)
 #
 # Run the passed command and, if it exits successfully, echo "1". Otherwise,
@@ -978,12 +995,21 @@ which_command_nonfatal() {
 }
 
 # ....................{ FILES ~ directories                }....................
+# bool is_path(char *path)
+# 
+# Return success if the passed path simply exists. Otherwise, failure.
+is_path() {
+    die_unless_one_argument 'expected exactly one path'
+    [[ -e "${1}" ]]
+}
+
+#
 # bool is_dir(char *path)
 # 
 # Return success if the passed path is an existing directory. Otherwise,
 # failure.
 is_dir() {
-    die_unless_one_argument 'expected exactly one path'
+    die_unless_one_argument 'expected exactly one dirname'
     [[ -d "${1}" ]]
 }
 
@@ -991,10 +1017,11 @@ is_dir() {
 # 
 # Return success if the passed path is an existing file. Otherwise, failure.
 is_file() {
-    die_unless_one_argument 'expected exactly one path'
+    die_unless_one_argument 'expected exactly one filename'
     [[ -f "${1}" ]]
 }
 
+#FIXME: Rename. Condense. Simplify.
 # void make_parent_directory_if_not_found(char *path)
 #
 # Make the parent directory of the passed path, if not found.
@@ -1003,6 +1030,7 @@ make_parent_directory_if_not_found() {
     make_directory_if_not_found "$(dirname "${1}")"
 }
 
+#FIXME: Rename. Condense. Simplify.
 # void make_directory_if_not_found(char *dirname1, char *dirname2, ...)
 #
 # Examine each of the passed absolute paths and, for each non-existant path,
@@ -1017,7 +1045,7 @@ make_directory_if_not_found() {
         new_path="${1}"
         shift
 
-        if [[ ! -d "${new_path}" ]]; then
+        if ! is_dir "${new_path}"; then
             utter "making \"${new_path}\"..."
             try mkdir --parents "${new_path}"
         fi
@@ -1142,6 +1170,8 @@ zeshy_initialize_imports() {
 
 # ....................{ MAIN                               }....................
 _zeshy_core() {
+    die_unless_no_arguments
+
     # Initialize the imports dictionary used by the zimport() function.
     zeshy_initialize_imports
     
