Extensive core changes.
The die_unless_*() family of aliases now implicitly read arguments
from stdin, thus conferring all other Zeshy functions implicit
support for such reading. (This is *AWESOME*, in that highly
isolate and geek-impounded sense of the word.)

Also, added a variety of new line matching functions to Zeshy Regex.

diff --git a/src/zeshy/core b/src/zeshy/core
--- a/src/zeshy/core
+++ b/src/zeshy/core
@@ -385,7 +385,46 @@ die() {
     fi
 }
 
-# ....................{ ERRORS ~ arguments                 }....................
+# ....................{ ARGUMENTS ~ tests                  }....................
+# Define critical argument-specific aliases prior to defining functions
+# expanding these aliases. Otherwise, error ensues.
+
+# bool is_no_arguments(void)
+#
+# Return success if this function was called with no arguments. Otherwise,
+# return failure.
+alias is_no_arguments='[[ ${#} -eq 0 ]]'
+
+# bool is_one_argument(void)
+#
+# Return success if this function was called with one argument. Otherwise,
+# return failure.
+alias is_one_argument='[[ ${#} -eq 1 ]]'
+
+# bool is_two_argument(void)
+#
+# Return success if this function was called with two arguments. Otherwise,
+# return failure.
+alias is_two_arguments='[[ ${#} -eq 2 ]]'
+
+# bool is_at_least_one_argument(void)
+#
+# Return success if this function was called with at least one argument.
+# Otherwise, return failure.
+alias is_at_least_one_argument='[[ ${#} -ge 1 ]]'
+
+# bool is_at_least_two_arguments(void)
+#
+# Return success if this function was called with at least two arguments.
+# Otherwise, return failure.
+alias is_at_least_two_arguments='[[ ${#} -ge 2 ]]'
+
+# ....................{ ARGUMENTS ~ exceptions             }....................
+# As a convenience, all argument aliases except die_unless_no_arguments() first
+# attempt to read their argument from stdin when the caller passed no explicit
+# argument. This implies all functions expanding these aliases implicitly "get"
+# piped input support, which is nice.
+
 # void die_unless_no_arguments(void)
 #
 # Die with a canonical error message unless the caller passed no arguments.
@@ -395,25 +434,25 @@ alias die_unless_no_arguments='[[ ${#} -eq 0 ]] || die "expected no arguments"'
 #
 # Die with the passed error message unless the caller passed exactly one
 # argument.
-alias die_unless_one_argument='[[ ${#} -eq 1 ]] || die'
+alias die_unless_one_argument='if [[ ${#} -eq 0 ]]; then set -- "$(< /dev/stdin)"; fi; [[ ${#} -eq 1 ]] || die'
 
 # void die_unless_two_arguments(void)
 #
 # Die with the passed error message unless the caller passed exactly two
 # arguments.
-alias die_unless_two_arguments='[[ ${#} -eq 2 ]] || die'
+alias die_unless_two_arguments='if [[ ${#} -eq 1 ]]; then set -- "${1}" "$(< /dev/stdin)"; fi; [[ ${#} -eq 2 ]] || die'
 
 # void die_unless_at_least_one_argument(void)
 #
 # Die with the passed error message unless the caller passed at least one
 # argument.
-alias die_unless_at_least_one_argument='[[ ${#} -ge 1 ]] || die'
+alias die_unless_at_least_one_argument='if [[ ${#} -eq 0 ]]; then set -- "$(< /dev/stdin)"; fi; [[ ${#} -ge 1 ]] || die'
 
 # void die_unless_at_least_two_arguments(void)
 #
 # Die with the passed error message unless the caller passed at least one
 # argument.
-alias die_unless_at_least_two_arguments='[[ ${#} -ge 2 ]] || die'
+alias die_unless_at_least_two_arguments='if [[ ${#} -eq 1 ]]; then set -- "${1}" "$(< /dev/stdin)"; fi; [[ ${#} -ge 2 ]] || die'
 
 # ....................{ ERRORS ~ paths                     }....................
 # void die_unless_dir(char *dirname)
@@ -421,7 +460,7 @@ alias die_unless_at_least_two_arguments='[[ ${#} -ge 2 ]] || die'
 # Die with a canonical error message unless the passed string corresponds to an
 # existing directory.
 die_unless_dir() {
-    die_unless_one_argument
+    die_unless_one_argument 'expected exactly one dirname'
     [[ -d "${1}" ]] || die "\"${1}\" not found or not a directory"
 }
 
@@ -430,7 +469,7 @@ die_unless_dir() {
 # Die with a canonical error message unless the passed string corresponds to an
 # existing file.
 die_unless_file() {
-    die_unless_one_argument
+    die_unless_one_argument 'expected exactly one filename'
     [[ -f "${1}" ]] || die "\"${1}\" not found or not a file"
 }
 
@@ -439,7 +478,7 @@ die_unless_file() {
 # Die with a canonical error message unless the passed string corresponds to an
 # existing device file (i.e., a block- or character-special file).
 die_unless_device_file() {
-    die_unless_one_argument
+    die_unless_one_argument 'expected exactly one filename'
     [[ -b "${1}" || -c "${1}" ]] ||
         die "\"${1}\" not found or not a device file"
 }
@@ -449,9 +488,11 @@ die_unless_device_file() {
 #
 # Die with the passed error message unless the previous command succeeded.
 die_unless_ok() {
-    die_unless_one_argument
-    [[ -b "${1}" || -c "${1}" ]] ||
-        die "\"${1}\" not found or not a device file"
+    # Cache the prior command's return code, as our initial sanity check on
+    # arguments replaces this code with its own.
+    local prior_command_return_code=${?}
+    die_unless_one_argument 'expected exactly one error message'
+    [[ ${prior_command_return_code} -eq ${ZESHY_SUCCESS_CODE} ]] || die "${1}"
 }
 
 # ....................{ FUNCTIONS                          }....................
@@ -578,7 +619,7 @@ run() {
           command_path="$(whence "${command_name}")"
     
     # If the passed command does not exist, fail.
-    is_ok || "\"${command_name}\" not found; cannot run \"${command}\""
+    die_unless_ok "\"${command_name}\" not found; cannot run \"${command}\""
 
     # Otherwise, if the passed command has not been overridden by a shell alias
     # or function, run it as a command. Do not call the customary is_installed()
@@ -586,7 +627,7 @@ run() {
     if is_absolute_path "${command_path}"; then
         # If the caller requests this command be run under a different user,
         # attempt to do so.
-        if [[ -n "${ZESHY_RUN_AS}" && "${ZESHY_RUN_AS}" != $(whoami) ]]; then
+        if [[ -n "${ZESHY_RUN_AS}" && "${ZESHY_RUN_AS}" != "$(whoami)" ]]; then
             # If the target user is the superuser, use "sudo" to take
             # advantage of password caching.
             #
@@ -778,22 +819,16 @@ exit_with_success() {
 #     >>> echo "${MATCH}" 
 #     1
 match() {
-#   pcre_compile "${1}" || die "\"${1}\" not a valid regular expression"
-#   pcre_match "${2}" || return ${?}
-#   return ${ZESHY_SUCCESS_CODE}
-    local string
-
     # If no string was passed, attempt to read "stdin" for piped input.
-    if [[ ${#} -eq 1 ]]; then
-        string="$(< /dev/stdin)"
-        set -- "${1}" "${string}"
+    if is_one_argument; then
+        set -- "${1}" "$(< /dev/stdin)"
     fi
    
     # Parse parameters.
-    [[ ${#} -ge 2 ]] ||
-        die 'expected at least one regular expression and one string'
+    die_unless_at_least_two_arguments\
+        'expected at least one regular expression and one string'
     local regex="${1}"
-          string="${2}"
+    local string="${2}"
     local match_variable_name="${3:-MATCH}"
     local group_array_name="${4:-match}"
 #   print "pattern: "${(q)regex}" | string: ${string} | match_variable_name: ${match_variable_name} | group_array_name: ${group_array_name} "
@@ -815,7 +850,6 @@ match() {
     pcre_match -v "${match_variable_name}" -a "${group_array_name}" --\
         "${string}" || return ${?}
 #   pcre_match "${string}" || return ${?}
-    return ${ZESHY_SUCCESS_CODE}
 }
 
 # void match_multiline(...)
@@ -836,7 +870,7 @@ match_multiline() {
 # Get the PID (process ID) for the current process. This is an integer uniquely
 # identifying this process.
 get_current_pid() {
-    [[ "${argument_count}" -eq 0 ]] || die 'expected no arguments'
+    die_unless_no_arguments
     echo "${$}"
 }
 
@@ -845,7 +879,7 @@ get_current_pid() {
 #
 # Return success if the passed path is absolute (i.e., begins with an "/").
 is_absolute_path() {
-    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    die_unless_one_argument 'expected exactly one path'
     [[ "${1[1]}" == / ]]
 }
 
@@ -863,7 +897,7 @@ is_absolute_path() {
 # * Expands every symlink in every component of the passed path recursively,
 #   until the resulting path contains no symlinks.
 canonicalize_path() {
-    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    die_unless_one_argument 'expected exactly one path'
     try readlink --canonicalize-existing "${1}"
 }
 
@@ -874,7 +908,7 @@ canonicalize_path() {
 # the passed path does not exist; it simply canonicalizes as much of this path
 # as exists.
 canonicalize_path_nonfatal() {
-    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    die_unless_one_argument 'expected exactly one path'
     try readlink --canonicalize-missing "${1}"
 }
 
@@ -894,7 +928,7 @@ canonicalize_path_nonfatal() {
 #
 # The return value is an integer, suitable for testing with "-ge" and "-le".
 get_path_mtime() {
-    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    die_unless_one_argument 'expected exactly one path'
     try zstat +mtime "${1}"
 }
 
@@ -920,8 +954,8 @@ which_command() {
     # Call the whence() built-in outside of "local" so as to retain the return
     # code. (ZSH == FAIL on that one.) 
     local command_path
-          command_path=$(which_command_nonfatal "${@}")
-    is_previous_command_succeeded || die "\"${1}\" not found"
+          command_path="$(which_command_nonfatal "${@}")"
+    die_unless_ok "\"${1}\" not found"
     echo "${command_path}"
 }
 
@@ -930,7 +964,7 @@ which_command() {
 # Identical to the which_command() function except that, if the passed command
 # does not exist, returns nothing rather than dies.
 which_command_nonfatal() {
-    [[ ${#} -eq 1 ]] || die "expected exactly one command name"
+    die_unless_one_argument 'expected exactly one command name'
     
     # First word of the first passed parameter, and the absolute path to return.
     local command_name="${1[(w)1]}" command_path
@@ -939,7 +973,8 @@ which_command_nonfatal() {
     # code. (ZSH == FAIL on that one.) 
     command_path="$(whence -cp "${command_name}")"
     
-    if is_previous_command_succeeded; then
+    #FIXME: Clean this up.
+    if is_ok; then
         echo "${command_path}"
         return ${ZESHY_SUCCESS_CODE}
     fi
@@ -953,7 +988,7 @@ which_command_nonfatal() {
 # Return success if the passed path is an existing directory. Otherwise,
 # failure.
 is_dir() {
-    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    die_unless_one_argument 'expected exactly one path'
     [[ -d "${1}" ]]
 }
 
@@ -961,7 +996,7 @@ is_dir() {
 # 
 # Return success if the passed path is an existing file. Otherwise, failure.
 is_file() {
-    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    die_unless_one_argument 'expected exactly one path'
     [[ -f "${1}" ]]
 }
 
@@ -969,7 +1004,7 @@ is_file() {
 #
 # Make the parent directory of the passed path, if not found.
 make_parent_directory_if_not_found() {
-    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    die_unless_one_argument 'expected exactly one path'
     make_directory_if_not_found "$(dirname "${1}")"
 }
 
@@ -978,7 +1013,7 @@ make_parent_directory_if_not_found() {
 # Examine each of the passed absolute paths and, for each non-existant path,
 # make that path and all non-existant parent paths of that path.
 make_directory_if_not_found() {
-    [[ ${#} -ge 1 ]] || die "expected at least one dirname"
+    die_unless_one_argument 'expected exactly one dirname'
 
     # While there are more paths to consider, shift the current path to be
     # considered to a local variable "new_path" and make it when not found.
@@ -1031,7 +1066,7 @@ make_directory_if_not_found() {
 # * "zeshy_script_path", having the absolute path to the imported script.
 # * "zeshy_script_mtime", having the modification time of the imported script.
 zimport() {
-    [[ ${#} -ge 1 ]] || die "expected exactly one script name"
+    die_unless_at_least_one_argument 'expected exactly one script name'
     
     # Passed script name. Shift it off the argument stack, to allow us to pass
     # this script the set of all remaining arguments on sourcing it below.
@@ -1105,7 +1140,7 @@ zimport() {
 # [A]ssociative array (i.e., a dictionary) and e[x]ported to the global
 # environment for later access.
 zeshy_initialize_imports() {
-    [[ ${#} -eq 0 ]] || die "expected no arguments"
+    die_unless_no_arguments
     typeset -Ax ZESHY_IMPORTED_PATH_TO_MTIME
     ZESHY_IMPORTED_PATH_TO_MTIME=()
 }
@@ -1165,6 +1200,10 @@ _zeshy_core() {
 _zeshy_core
 
 #FIXME: Obsolete.
+#   pcre_compile "${1}" || die "\"${1}\" not a valid regular expression"
+#   pcre_match "${2}" || return ${?}
+#   return ${ZESHY_SUCCESS_CODE}
+
 # This function returns success 
 # If this regular expression matched at least one group, this function returns
 # this group as a string for caller convenience... Else, this function returns
