Significant commit.
This commit amends a great many outstanding issues, too numerous to
mention. Notable non-issues include the addition of:

* "bin/zscreenshot", a Zeshy script for capturing screenshots.
* "zeshy/command", a Zeshy component for importing external command-
  specific components.

diff --git a/src/zeshy/core b/src/zeshy/core
--- a/src/zeshy/core
+++ b/src/zeshy/core
@@ -41,8 +41,8 @@ export ZESHY_COMPINIT_DUMP_FILE="${ZESHY_CACHE_HOME}/zcompdump"
 # a caller attempts to import a path rather than a file: e.g.,
 #
 #     # Actually imports "zeshy/${ZESHY_MAIN_SCRIPT_BASENAME}", instead.
-#     >>> import zeshy
-export ZESHY_MAIN_SCRIPT_BASENAME='_main'
+#     >>> zimport zeshy
+export ZESHY_MAIN_SCRIPT_BASENAME='.main'
 
 # ....................{ BOOLEANS                           }....................
 # If non-empty, the current process is running as a cronjob. (Set below.)
@@ -325,8 +325,6 @@ utter_import() {
     # name of this function as its script name, producing an unaesthetic
     # result.
     [[ -n "${ZESHY_SCRIPT_NAME}" ]] || local ZESHY_SCRIPT_NAME='zeshy'
-#   local ZESHY_SCRIPT_NAME='zeshy'
-#   which utter
     utter "loading \"${1}\"..."
 }
 
@@ -358,7 +356,7 @@ die() {
     fi
 }
 
-# ....................{ COMMANDS                           }....................
+# ....................{ FUNCTIONS                          }....................
 # bool is_callable(char *name)
 #
 # Return true if there exists an alias or function with the passed name.
@@ -381,26 +379,12 @@ alias is_installed="is_runnable"
 #     Bash is installed!
 is_runnable() { quietly which_binary_nonfatal "${@}" }
 
-# void try_as_superuser(char *command)
-#
-# Run the passed command as the superuser and, if it fails with error,
-# terminate the current execution environment with the same error.
-try_as_superuser() { run_as_superuser "${@}" || die }
-
 # void try(char *command)
 #
 # Run the passed command and, if it fails with error, terminate the current
 # execution environment with the same error.
 try() {
     run "${@}" || die "\"${@}\" returned error code ${?}"
-}
-
-# void run_as_superuser(char *command)
-#
-# Run the passed command as the superuser.
-run_as_superuser() {
-    [[ "${#}" -ge 1 ]] || die 'expected exactly one command'
-    run_as root "${@}"
 }
 
 # void run_as(char *username, char *command)
@@ -486,7 +470,24 @@ run() {
     fi
 }
 
-# ....................{ STREAMERS                          }....................
+# ....................{ COMMANDS ~ superuser               }....................
+# bool is_superuser(void)
+#
+# Return success if the current user is the "superuser" (i.e., root).
+is_superuser() { [[ "${EUID}" == 0 || "${USER}" == root ]] }
+
+# void try_as_superuser(char *command)
+#
+# Run the passed command as the superuser and, if it fails with error,
+# terminate the current execution environment with the same error.
+try_as_superuser() { run_as_superuser "${@}" || die }
+
+# void run_as_superuser(char *command)
+#
+# Run the passed command as the superuser.
+run_as_superuser() { run_as root "${@}" }
+
+# ....................{ COMMANDS ~ helpers                 }....................
 # bool one_if(char *command)
 #
 # Run the passed command and, if it exits successfully, echo "1". Otherwise,
@@ -668,7 +669,7 @@ which_command_nonfatal() {
     fi
 }
 
-# ....................{ DIRECTORIES                        }....................
+# ....................{ FILES ~ directories                }....................
 # void make_parent_directory_if_not_found(char *path)
 #
 # Make the parent directory of the passed path, if not found.
@@ -699,7 +700,7 @@ make_directory_if_not_found() {
 }
 
 # ....................{ IMPORTS                            }....................
-# void import(char *script_name)
+# void zimport(char *script_name)
 # 
 # Import the passed script name as a dependency of the current script.
 # 
@@ -721,9 +722,12 @@ make_directory_if_not_found() {
 # imports a file named "main" under that directory: e.g.,
 #
 #     # Actually imports "zeshy/os/main".
-#     >>> import zeshy/os
-import() {
-    [[ "${#}" -ge 1 ]] || die "expected one script name"
+#     >>> zimport zeshy/os
+# 
+# This function is named "zimport" so as not to conflict with ImageMagick's
+# brashly named "import" command.
+zimport() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one script name"
     
     # Passed script name. Shift it off the argument stack, to allow us to pass
     # this script the set of all remaining arguments on sourcing it below.
@@ -758,13 +762,13 @@ import() {
     
     # If the script has not yet been imported or has been imported but has
     # changed since being imported, do so.
-    if [[ -z "${IMPORTED_SCRIPT_PATH_TO_MTIME["${script_path}"]}" ||\
-        "${IMPORTED_SCRIPT_PATH_TO_MTIME["${script_path}"]}" -ne\
+    if [[ -z "${ZESHY_IMPORTED_PATH_TO_MTIME["${script_path}"]}" ||\
+        "${ZESHY_IMPORTED_PATH_TO_MTIME["${script_path}"]}" -ne\
         "${script_mtime}" ]]; then
         # Prior to doing so, record the script as being imported. This prevents
         # reimportation, should this script or another script imported by this
         # script attempt to import this script again.
-        IMPORTED_SCRIPT_PATH_TO_MTIME["${script_path}"]="${script_mtime}"
+        ZESHY_IMPORTED_PATH_TO_MTIME["${script_path}"]="${script_mtime}"
          
         # Do so.
         utter_import "${script_path}"
@@ -772,11 +776,11 @@ import() {
     fi
 }
 
-# void initialize_imports(void)
+# void zeshy_initialize_imports(void)
 #
-# Initialize the imports dictionary, used by the import() function. This is a
+# Initialize the imports dictionary, used by the zimport() function. This is a
 # global dictionary mapping from imported script name to the mtime (i.e.,
-# modification time) of the script at the time of importation. The import()
+# modification time) of the script at the time of importation. The zimport()
 # function adds script names to this dictionary on importing those scripts so
 # as to record having done so. This record keeping allows that function to
 # avoid importing already imported scripts.
@@ -784,31 +788,35 @@ import() {
 # The "-Ax" option to the "typeset" commands defines each such variable as an
 # [A]ssociative array (i.e., a dictionary) and e[x]ported to the global
 # environment for later access.
-initialize_imports() {
+zeshy_initialize_imports() {
     [[ "${#}" -eq 0 ]] || die "expected no arguments"
-    typeset -Ax IMPORTED_SCRIPT_PATH_TO_MTIME
-    IMPORTED_SCRIPT_PATH_TO_MTIME=()
+    typeset -Ax ZESHY_IMPORTED_PATH_TO_MTIME
+    ZESHY_IMPORTED_PATH_TO_MTIME=()
 }
 
 # ....................{ MAIN                               }....................
-_core() {
-    # Initialize the imports dictionary used by the import() function.
-    initialize_imports
+_zeshy_core() {
+    # Initialize the imports dictionary used by the zimport() function.
+    zeshy_initialize_imports
     
     # Add this script to the set of all imported scripts, to prevent subsequent
     # imports from (accidentally) reimporting it. Do not add this to the
     # initialize_imports() function, due to largely inexplicable dragons.
-    IMPORTED_SCRIPT_PATH_TO_MTIME["${zeshy_core_path}"]="$(get_path_mtime "${zeshy_core_path}")"
-
+    ZESHY_IMPORTED_PATH_TO_MTIME["${zeshy_core_path}"]="$(get_path_mtime "${zeshy_core_path}")"
+    
     # Inform the user that this script is being imported. This script is usually
-    # sourced via the Zsh source() built-in rather than the Zeshy import()
+    # sourced via the Zsh source() built-in rather than the Zeshy zimport()
     # function; thus, our failure to do this here would require callers do this
     # there, prior to their sourcing this script.
-    utter_import "${zeshy_core_path}"
+    #
+    # Distinguish the former from the latter by noting whether the
+    # "${script_mtime}" variable has been set or not; if it has, this script
+    # was sourced via zimport() rather than source().
+    [[ -n "${script_mtime}" ]] || utter_import "${zeshy_core_path}"
     
     # Import the Zeshy OS component, providing the OS-specific
     # get_current_process_basename() function called above.
-    import zeshy/os
+    zimport zeshy/os
     
     #echo "PID: $$"
     #echo "current_process_basename:"
@@ -845,10 +853,24 @@ _core() {
 #   ZESHY_IS_CRONJOB=$(one_if "echo '${cron_pids}' | grep '${grandparent_pid}'")
 #   echo "cron: ${ZESHY_IS_CRONJOB}; cron_pids: ${cron_pids}; gpid: ${grandparent_pid}"
 }
-_core
+_zeshy_core
 
 #FIXME: Obsolete.
-# Enable variable substitution in prompt expansions in a "synchronous" fashion.
+# ....................{ GLOB EXPRESSIONS                   }....................
+# char **glob_non_dotfiles_in(char *dirname)
+#
+# Glob all non-dotfiles (i.e., all files and directories whose first character
+# is not a '.' dot) in the passed directory.
+#glob_non_dotfiles_in() {
+#    [[ "${#}" -eq 1 ]] || die "expected exactly one directory name"
+#    local dirname="${1}"
+#    [[ -d "${dirname}" ]] || "\"${dirname}\" not a directory"
+#
+#    # Glob all non-dotfiles via the "(^D)" modifier.
+#    echo "${dirname}"/*(^D)
+#}
+
+ # Enable variable substitution in prompt expansions in a "synchronous" fashion.
 # Enabling this re-evaluates each prompt expansion after perform each
 # interactive command with the current values of those variables without
 # having to manually recreate the prompt each time.
diff --git a/src/zeshy/file b/src/zeshy/file
--- a/src/zeshy/file
+++ b/src/zeshy/file
@@ -88,6 +88,66 @@ which_binaries_nonfatal() {
     return ${ZESHY_FAILURE_CODE}
 }
 
+# ....................{ FILES ~ mounts                     }....................
+# bool is_mount_point(char *dirname)
+#
+# Return success if the passed directory name is an existing mount point (i.e.,
+# if "something" is currently mounted under this directory).
+is_mount_point() {
+    # Ensure sanity.
+    [[ "${#}" -eq 1 ]] || die "expected exactly one pathname"
+    local mount_point="${1}"
+    
+    # If the passed pathname does not correspond to an existing directory, it
+    # cannot correspond to a valid mount point.
+    [[ -d "${mount_point}" ]] || return "${ZESHY_FAILURE_CODE}"
+
+    # If the "mountpoint" binary is available, use that.
+    if is_runnable mountpoint; then
+        mountpoint -q "${mount_point}"
+    # Otherwise, manually grep "${ZESHY_MOUNT_POINTS_FILE}".
+    else
+        grep -q "${mount_point}" "${ZESHY_MOUNT_POINTS_FILE}"
+    fi
+}
+
+# void mount_iso(char *filename)
+#
+# Mount the passed ISO filename to the "${ZESHY_MOUNT_ISO_PATH}" directory. If
+# something is already mounted to this path, this function iteratively appends
+# numbers (starting at 1), until discovering a directory name to which nothing
+# is currently mounted.
+mount_iso() {
+    # Ensure sanity.
+    [[ "${#}" -eq 1 ]] || die "expected exactly one ISO filename"
+    local iso_filename="${1}"
+    [[ "${iso_filename}" == *.iso ]] ||
+        die "\"${iso_filename}\" not an ISO filename"
+    [[ -f "${iso_filename}" ]] ||
+        die "\"${iso_filename}\" not found"
+    local SCRIPT_NAME='mount-iso'
+
+    # Find a suitable mount path.
+    local iso_mount_path_prefix="${ZESHY_MOUNT_ISO_PATH}"
+    local iso_mount_path_suffix=0
+    local iso_mount_path="${iso_mount_path_prefix}"
+    utter "searching for an available mount point..."
+    while is_mount_point "${iso_mount_path}"; do
+        iso_mount_path_suffix=$(( iso_mount_path_suffix + 1 ))
+        iso_mount_path="${iso_mount_path_prefix}${iso_mount_path_suffix}"
+    done
+    
+    # Mount the passed ISO filename to the desired mount path.
+    #
+    # Note that this does not pass the ",user" option when mounting, as doing so
+    # would implicitly enables unhelpful mount options (e.g., "noexec").
+    utter "mounting \"${iso_filename}\" to \"${iso_mount_path}\"..."
+    run_as_superuser make_directory_if_not_found "${iso_mount_path}" 
+    run_as_superuser mount -t iso9660 -o 'exec,loop'\
+        "${iso_filename}" "${iso_mount_path}" ||
+        die "\"${iso_filename}\" not mountable to \"${iso_mount_path}\""
+}
+
 # ....................{ FILES ~ temporary                  }....................
 # void move_to_temporary_directory(char *path1, char *path2, ...)
 #
