Fully integrated "hg-cohere" into Zeshy.
Also, a myriad small bugfixes here and thereabouts.

diff --git a/src/zeshy/core b/src/zeshy/core
--- a/src/zeshy/core
+++ b/src/zeshy/core
@@ -226,6 +226,14 @@ setopt nolistambiguous   # only list matches if ambiguous
 alias noop=':'
 
 # ....................{ ENVIRONMENT                        }....................
+# bool is_cronjob(void)
+#
+# Return success if the current shell is a cronjob (i.e., is the grandchild of
+# a "cron" process).
+is_cronjob() {
+    [[ -n "${ZESHY_IS_CRONJOB}" ]]
+}
+
 # bool is_shell_interactive(void)
 #
 # Return success if the current shell is interactive or is a login shell.
@@ -261,7 +269,6 @@ is_terminal && stty -ixon -ixoff
 # this original definition (since functions are not inherited via script
 # calls).
 get_script_name() {
-#   echo "getting..."
     if [[ -n "${ZESHY_SCRIPT_NAME}" ]]; then
         echo "${ZESHY_SCRIPT_NAME}"
     # If the current process is an interactive shell, then return the name of
@@ -271,7 +278,6 @@ get_script_name() {
     # the function two calls earlier in the function callstack). Insert magical
     # handwaving here.
     elif is_shell_interactive; then
-#       echo "uh-oh..."
         # Ignore all intermediary I/O- and error handling-specific function
         # calls. As the first element of "${funcstack}" is the name of the
         # current function (and we are not particularly interested in that),
@@ -283,7 +289,6 @@ get_script_name() {
                 *)                  break ;;
             esac
         done
-#       echo "bah!"
          
         # If after ignoring non-relevant functions there still exists at least
         # one function on the callstack, return that function's name.
@@ -350,7 +355,7 @@ curse() {
 # imported. This function should be called prior to actually importing that
 # script if feasible.
 utter_import() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one script name"
+    [[ ${#} -eq 1 ]] || die "expected exactly one script name"
 
     # If the caller has supplied no explicit "${ZESHY_SCRIPT_NAME}", supply a
     # default.  Failing to do this encourages the utter() function to use the
@@ -393,14 +398,14 @@ die() {
 #
 # Return true if there exists an alias or function with the passed name.
 is_callable() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one name"
+    [[ ${#} -eq 1 ]] || die "expected exactly one name"
     [[ $(whence -w "${1}") =~ ': (alias|builtin|function)$' ]]
 }
 
 # ....................{ COMMANDS                           }....................
 # Aliases.
-alias is_available="is_runnable"
-alias is_installed="is_runnable"
+alias is_available=is_runnable
+alias is_installed=is_runnable
 
 # bool is_runnable(char *command)
 #
@@ -421,7 +426,7 @@ is_runnable() {
 # Run the passed command as the passed user quietly and, if it fails with error,
 # terminate the current execution environment with the same error.
 try_as() {
-    [[ "${#}" -ge 2 ]] || die 'expected exactly one username and one command'
+    [[ ${#} -ge 2 ]] || die 'expected exactly one username and one command'
 
     # Locally set "${ZESHY_RUN_AS}". The run() function notes this variable as
     # set and behaves accordingly...
@@ -437,7 +442,7 @@ try_as() {
 #
 # Run the passed command as the passed user.
 run_as() {
-    [[ "${#}" -ge 2 ]] || die 'expected exactly one username and one command'
+    [[ ${#} -ge 2 ]] || die 'expected exactly one username and one command'
 
     # Locally set "${ZESHY_RUN_AS}". The run() function notes this variable as
     # set and behaves accordingly...
@@ -571,23 +576,9 @@ run_as_superuser() {
 }
 
 # ....................{ COMMANDS ~ quietly                 }....................
-# void try_quietly(char *command)
-#
-# Run the passed command quietly and, if it fails with error, terminate the
-# current execution environment with the same error.
-try_quietly() {
-    quietly try "${@}" || die "\"${@}\" returned error code ${?}"
-}
+alias is=quietly
 
-# void try_quietly_as(char *username, char *command)
-#
-# Run the passed command as the passed user quietly and, if it fails with error,
-# terminate the current execution environment with the same error.
-try_quietly_as() {
-    quietly try_as "${@}" || die "\"${@}\" returned error code ${?}"
-}
-
-# bool one_if(char *command)
+# int one_if(char *command)
 #
 # Run the passed command and, if it exits successfully, echo "1". Otherwise,
 # nothing. To guarantee this, this function squelches all other output: e.g.,
@@ -603,7 +594,7 @@ try_quietly_as() {
 # command. (See the run() function, above.)
 one_if() {
     quietly "${@}"
-    if [[ "${?}" -eq "${ZESHY_SUCCESS_CODE}" ]]
+    if [[ ${?} -eq ${ZESHY_SUCCESS_CODE} ]]
     then echo 1
     else echo
     fi
@@ -624,8 +615,24 @@ quietly() {
     run "${(q)@}" 1>/dev/null 2>&1
 }
 
-# ....................{ COMMANDS ~ tests                   }....................
-#FIXME: Alias "previous_command_return_value" to "${?}". What sort of alias?
+# void try_quietly(char *command)
+#
+# Run the passed command quietly and, if it fails with error, terminate the
+# current execution environment with the same error.
+try_quietly() {
+    quietly try "${@}" || die "\"${@}\" returned error code ${?}"
+}
+
+# void try_quietly_as(char *username, char *command)
+#
+# Run the passed command as the passed user quietly and, if it fails with error,
+# terminate the current execution environment with the same error.
+try_quietly_as() {
+    quietly try_as "${@}" || die "\"${@}\" returned error code ${?}"
+}
+
+# ....................{ COMMANDS ~ return codes            }....................
+alias get_previous_command_return_code=is_previous_command_succeeded
 
 # bool is_previous_command_failed(void)
 #
@@ -643,10 +650,7 @@ is_previous_command_failed() {
 # Return success if the previous command succeeded. Otherwise, return failure.
 is_previous_command_succeeded() {
     [[ ${#} -eq 0 ]] || die "expected no arguments"
-    if [[ ${?} -eq ${ZESHY_SUCCESS_CODE} ]]
-    then return ${ZESHY_SUCCESS_CODE}
-    else return ${?}
-    fi
+    return ${?}
 }
 
 # ....................{ REGULAR EXPRESSIONS                }....................
@@ -729,7 +733,7 @@ get_current_pid() {
 #
 # Return success if the passed path is absolute (i.e., begins with an "/").
 is_absolute_path() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one path"
+    [[ ${#} -eq 1 ]] || die "expected exactly one path"
     [[ "${1[1]}" == / ]]
 }
 
@@ -747,7 +751,7 @@ is_absolute_path() {
 # * Expands every symlink in every component of the passed path recursively,
 #   until the resulting path contains no symlinks.
 canonicalize_path() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one path"
+    [[ ${#} -eq 1 ]] || die "expected exactly one path"
     try readlink --canonicalize-existing "${1}"
 }
 
@@ -758,7 +762,7 @@ canonicalize_path() {
 # the passed path does not exist; it simply canonicalizes as much of this path
 # as exists.
 canonicalize_path_nonfatal() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one path"
+    [[ ${#} -eq 1 ]] || die "expected exactly one path"
     try readlink --canonicalize-missing "${1}"
 }
 
@@ -778,7 +782,7 @@ canonicalize_path_nonfatal() {
 #
 # The return value is an integer, suitable for testing with "-ge" and "-le".
 get_path_mtime() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one path"
+    [[ ${#} -eq 1 ]] || die "expected exactly one path"
     try zstat +mtime "${1}"
 }
 
@@ -814,7 +818,7 @@ which_command() {
 # Identical to the which_command() function except that, if the passed command
 # does not exist, returns nothing rather than dies.
 which_command_nonfatal() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one command name"
+    [[ ${#} -eq 1 ]] || die "expected exactly one command name"
     
     # First word of the first passed parameter, and the absolute path to return.
     local command_name="${1[(w)1]}" command_path
@@ -832,12 +836,29 @@ which_command_nonfatal() {
 }
 
 # ....................{ FILES ~ directories                }....................
+# bool is_dir(char *path)
+# 
+# Return success if the passed path is an existing directory. Otherwise,
+# failure.
+is_dir() {
+    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    [[ -d "${1}" ]]
+}
+
+# bool is_file(char *path)
+# 
+# Return success if the passed path is an existing file. Otherwise, failure.
+is_file() {
+    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    [[ -f "${1}" ]]
+}
+
 # void make_parent_directory_if_not_found(char *path)
 #
 # Make the parent directory of the passed path, if not found.
 make_parent_directory_if_not_found() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one path"
-    make_directory_if_not_found $(dirname "${1}")
+    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    make_directory_if_not_found "$(dirname "${1}")"
 }
 
 # void make_directory_if_not_found(char *dirname1, char *dirname2, ...)
@@ -845,7 +866,7 @@ make_parent_directory_if_not_found() {
 # Examine each of the passed absolute paths and, for each non-existant path,
 # make that path and all non-existant parent paths of that path.
 make_directory_if_not_found() {
-    [[ "${#}" -ge 1 ]] || die "expected at least one dirname"
+    [[ ${#} -ge 1 ]] || die "expected at least one dirname"
 
     # While there are more paths to consider, shift the current path to be
     # considered to a local variable "new_path" and make it when not found.
@@ -898,7 +919,7 @@ make_directory_if_not_found() {
 # * "zeshy_script_path", having the absolute path to the imported script.
 # * "zeshy_script_mtime", having the modification time of the imported script.
 zimport() {
-    [[ "${#}" -ge 1 ]] || die "expected exactly one script name"
+    [[ ${#} -ge 1 ]] || die "expected exactly one script name"
     
     # Passed script name. Shift it off the argument stack, to allow us to pass
     # this script the set of all remaining arguments on sourcing it below.
@@ -960,7 +981,7 @@ zimport() {
 # [A]ssociative array (i.e., a dictionary) and e[x]ported to the global
 # environment for later access.
 zeshy_initialize_imports() {
-    [[ "${#}" -eq 0 ]] || die "expected no arguments"
+    [[ ${#} -eq 0 ]] || die "expected no arguments"
     typeset -Ax ZESHY_IMPORTED_PATH_TO_MTIME
     ZESHY_IMPORTED_PATH_TO_MTIME=()
 }
@@ -1051,7 +1072,7 @@ _zeshy_core
 # Glob all non-dotfiles (i.e., all files and directories whose first character
 # is not a '.' dot) in the passed directory.
 #glob_non_dotfiles_in() {
-#    [[ "${#}" -eq 1 ]] || die "expected exactly one directory name"
+#    [[ ${#} -eq 1 ]] || die "expected exactly one directory name"
 #    local dirname="${1}"
 #    [[ -d "${dirname}" ]] || "\"${dirname}\" not a directory"
 #
diff --git a/src/zeshy/file b/src/zeshy/file
--- a/src/zeshy/file
+++ b/src/zeshy/file
@@ -24,7 +24,16 @@ alias fsck.vfat="fsck.vfat ${ZESHY_FSCK_OPTIONS}"
 baobab()    { command baobab    "${@}" & }
 filelight() { command filelight "${@}" & }
 
-# ....................{ FILES                              }....................
+# ....................{ FILENAMES                          }....................
+# bool is_path_absolute(char *path)
+#
+# Return success if the passed path is absolute (i.e., begins with a '/'
+# character). Otherwise, failure.
+is_path_absolute() {
+    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    [[ "${1[1]}" == / ]]
+}
+
 # char *get_basename_sans_filetype(char *filename)
 #
 # Get the basename sans filetype of the passed filename. If this filename has no
@@ -34,7 +43,7 @@ filelight() { command filelight "${@}" & }
 #     >>> get_basename_sans_filetype('hastur.tar.gz')
 #     hastur.tar
 get_basename_sans_filetype() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one filename"
+    [[ ${#} -eq 1 ]] || die "expected exactly one filename"
     echo "${1%.*}"
 }
 
@@ -46,7 +55,7 @@ get_basename_sans_filetype() {
 #     >>> get_filetype('hastur.tar.gz')
 #     gz
 get_filetype() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one filename"
+    [[ ${#} -eq 1 ]] || die "expected exactly one filename"
     local filename="${1}"
     local filetype="${filename##*.}"
 
@@ -55,14 +64,14 @@ get_filetype() {
     [[ "${filetype}" == "${filename}" ]] || echo "${filetype}"
 }
 
-# ....................{ FILES ~ types                      }....................
+# ....................{ FILETYPES                          }....................
 # bool is_file_binary(char *filename)
 #
 # Return success if the passed filename corresponds to a binary file (i.e., not
 # a text file). (If the passed filename corresponds to a directory instead, this
 # function always returns failure.)
 is_file_binary() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one filename"
+    [[ ${#} -eq 1 ]] || die "expected exactly one filename"
     local filename="${1}"
 
     if [[ -f "${filename}" ]]
@@ -77,7 +86,7 @@ is_file_binary() {
 # binary file). (If the passed filename corresponds to a directory instead, this
 # function always returns failure.)
 is_file_text() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one filename"
+    [[ ${#} -eq 1 ]] || die "expected exactly one filename"
     local filename="${1}"
 
     # Do not simply do "! is_file_binary", as that incorrectly returns success
@@ -88,13 +97,13 @@ is_file_text() {
     fi
 }
 
-# ....................{ FILES ~ mounts                     }....................
+# ....................{ MOUNT POINTS                       }....................
 # bool is_directory_mount_point(char *dirname)
 #
 # Return success if the passed directory name is an existing mount point (i.e.,
 # if "something" is currently mounted under this directory).
 is_directory_mount_point() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one dirname"
+    [[ ${#} -eq 1 ]] || die "expected exactly one dirname"
     local mount_point="${1}"
     
     # If the passed pathname does not correspond to an existing directory, it
@@ -117,7 +126,7 @@ is_directory_mount_point() {
 # is currently mounted.
 mount_iso() {
     # Ensure sanity.
-    [[ "${#}" -eq 1 ]] || die "expected exactly one ISO filename"
+    [[ ${#} -eq 1 ]] || die "expected exactly one ISO filename"
     local iso_filename="${1}"
     [[ "${iso_filename}" == *.iso ]] ||
         die "\"${iso_filename}\" not an ISO filename"
@@ -146,80 +155,16 @@ mount_iso() {
         die "\"${iso_filename}\" not mountable to \"${iso_mount_path}\""
 }
 
-# ....................{ FILES ~ temporary                  }....................
-# void move_to_temporary_directory(char *path1, char *path2, ...)
-#
-# Move the passed set of files and/or directories to the "/tmp" directory. For
-# Additionally, this suffixing all files and
-# paths that already exist in "/tmp/" with the current time. 
-move_to_temporary_directory() {
-    local target_path source_path source_basename
-    for source_path in "${@}"; do
-        source_basename=$(basename "${source_path}")
-        target_path="/tmp/${source_basename}"
-        
-        [[ -e "${target_path}" ]] &&
-            target_path="/tmp/$source_basename~$(date +'%F_%H-%M-%S')"
-        
-        try mv "${source_path}" "${target_path}"
-    done
-}
-
-# char *which_temporary_path(char *prefix)
-#
-# Print the absolute path to a temporary path having the passed prefix: e.g.,
-#
-#     >>> which_temporary_path git_patches
-#     /tmp/git_patches~2011-04-18_22-58-34  # assuming today is 2011-04-18
-#
-# While subtle race conditions may arise with concurrent processing, this path
-# is generally unique. This should probably not be depended upon for mission
-# critical ZSH scripts, however. (Of course, if you're coding such a mission
-# critical script in ZSH, you've probably already gone too far.)
-which_temporary_path() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one path prefix"
-    
-    local which_temporary_path
-    while true; do
-        which_temporary_path="/tmp/${1}.path~$(date +'%F_%H-%M-%S')"
-        if [[ ! -d "${which_temporary_path}" ]]; then
-            echo   "${which_temporary_path}"
-            break
-        fi
-    done
-}
-
-# char *which_temporary_file(char *prefix)
-#
-# Print the absolute path to a temporary file having the passed prefix: e.g.,
-#
-#   # Prints "/tmp/git_patch_file~2011-12-01_18-37-41", for example.
-#   which_temporary_file git_patch_file
-#
-# Subtle race conditions may arise, as above.
-which_temporary_file() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one file prefix"
-    
-    local which_temporary_file
-    while true; do
-        which_temporary_file="/tmp/${1}.file~"$(date +'%F_%H-%M-%S')
-        if [[ ! -f "${which_temporary_file}" ]]; then
-            echo   "${which_temporary_file}"
-            break
-        fi
-    done
-}
-
-# ....................{ FILES ~ which                      }....................
+# ....................{ FINDERS                            }....................
 # char *which_files_nonfatal(char *filename1, *filename2, ...)
 #
-# Print the absolute path to the first filename in the list of passed filenames
+# Get the absolute path to the first filename in the list of passed filenames
 # which exists: e.g.,
 #
 #     >>> which_files_nonfatal '/the_ancient.one' '/the_king_in.yellow' '/tmp'
 #     /tmp
 which_files_nonfatal() {
-    [[ "${#}" -ge 1 ]] || die "expected at least one filename"
+    [[ ${#} -ge 1 ]] || die "expected at least one filename"
     
     # While there are more filenames to consider, shift the current filename to
     # be considered to a local variable "path".
@@ -229,8 +174,8 @@ which_files_nonfatal() {
         shift
 
         # If this filename exists and is readable, return it.
-        if [[ -r "${filename}" ]]; then
-            echo "${filename}"
+        if [[ -r  "${filename}" ]]; then
+            print "${filename}"
             return ${ZESHY_SUCCESS_CODE}
         fi
     done
@@ -241,7 +186,7 @@ which_files_nonfatal() {
 
 # char *which_binaries_nonfatal(char *binary_name1, *binary_name2, ...)
 #
-# Print the absolute path to the first binary in the list of passed binaries
+# Get the absolute path to the first binary in the list of passed binaries
 # which exists: e.g.,
 #
 #     >>> which_binaries_nonfatal Council_of_Nicea Constantinople zsh
@@ -252,7 +197,7 @@ which_files_nonfatal() {
 # "Council_of_Nicea" binary would be selected before all following binaries on
 # systems having the binary.)
 which_binaries_nonfatal() {
-    [[ "${#}" -ge 1 ]] || die "expected at least one binary name"
+    [[ ${#} -ge 1 ]] || die "expected at least one binary name"
     
     # While there are more binaries to consider, shift the current binary to be
     # considered to a local variable "binary_name".
@@ -264,13 +209,98 @@ which_binaries_nonfatal() {
         # If this binary exists, return the absolute path to it.
         binary_path=$(which_binary_nonfatal "${binary_name}")
         if [[ ${?} -eq ${ZESHY_SUCCESS_CODE} ]]; then
-            echo "${binary_path}"
+            print "${binary_path}"
             return ${ZESHY_SUCCESS_CODE}
         fi
     done
     
     # No binaries in the list of passed binaries exist. Return with failure.
     return ${ZESHY_FAILURE_CODE}
+}
+
+# ....................{ TEMPORARIES                        }....................
+#FIXME: This is probably OS-specific, but perhaps good enough for now.
+# char *which_temporary_dir(void)
+#
+# Get the absolute path to the temporary directory. This is, in descending order
+# of preference:
+#
+# * "${HOME}/tmp", if the current user's home directory has such a subdirectory. 
+# * "/tmp", otherwise.
+which_temporary_dir() {
+    [[ ${#} -eq 0 ]] || die "expected no arguments"
+    
+    local user_temporary_dir="${HOME}/tmp" root_temporary_dir="/tmp"
+    if [[ -d   "${user_temporary_dir}" ]]
+    then print "${user_temporary_dir}"
+    elif [[ -d "${root_temporary_dir}" ]]
+    then print "${root_temporary_dir}"
+    else die "no temporary directory found; neither "\
+        "\"${user_temporary_dir}\" or \"${root_temporary_dir}\" found"
+    fi
+}
+
+# char *which_temporary_path(char *prefix)
+#
+# Get the absolute path to a temporary path having the passed prefix: e.g.,
+#
+#     >>> which_temporary_path git_patches
+#     /tmp/git_patches~2011-04-18_22-58-34  # assuming today is 2011-04-18
+#
+# While subtle race conditions may arise with concurrent processing, this path
+# is generally unique. This should probably not be depended upon for mission
+# critical ZSH scripts, however. (Of course, if you're coding such a mission
+# critical script in ZSH, you've probably already gone too far.)
+which_temporary_path() {
+    [[ ${#} -eq 1 ]] || die "expected exactly one path prefix"
+    
+    local which_temporary_path
+    while true; do
+        which_temporary_path="$(which_temporary_dir)/${1}.path~$(date +'%F_%H-%M-%S')"
+        if [[ ! -d "${which_temporary_path}" ]]; then
+            print  "${which_temporary_path}"
+            break
+        fi
+    done
+}
+
+# char *which_temporary_file(char *prefix)
+#
+# Get the absolute path to a temporary file having the passed prefix: e.g.,
+#
+#   # Prints "/tmp/git_patch_file~2011-12-01_18-37-41", for example.
+#   which_temporary_file git_patch_file
+#
+# Subtle race conditions may arise, as above.
+which_temporary_file() {
+    [[ ${#} -eq 1 ]] || die "expected exactly one file prefix"
+    
+    local which_temporary_file
+    while true; do
+        which_temporary_file="$(which_temporary_dir)/${1}.file~"$(date +'%F_%H-%M-%S')
+        if [[ ! -f "${which_temporary_file}" ]]; then
+            print  "${which_temporary_file}"
+            break
+        fi
+    done
+}
+
+# ....................{ TEMPORARIES ~ mutators             }....................
+# void move_to_temporary_directory(char *path1, char *path2, ...)
+#
+# Move the passed set of files and/or directories to the "/tmp" directory. For
+# Additionally, this suffixing all files and
+# paths that already exist in "/tmp/" with the current time. 
+move_to_temporary_directory() {
+    local target_path source_path source_basename
+    for source_path in "${@}"; do
+        source_basename=$(basename "${source_path}")
+        target_path="/tmp/${source_basename}"
+        [[ -e "${target_path}" ]] &&
+            target_path="$(which_temporary_dir)/$source_basename~$(date +'%F_%H-%M-%S')"
+        
+        try mv "${source_path}" "${target_path}"
+    done
 }
 
 # --------------------( COPYRIGHT AND LICENSE              )--------------------
