Immense commit improving strictness.
Specifically, we enable several hitherto disabled strictness
settings (-u and WARN_CREATE_GLOBAL) -- unsurprisingly breaking Zeshy
Core and related components. Correcting such breakage showed several
subtle bugs lying about, now explicitly uncovered. Take that!

Also, added functionality for distinguishing unset from empty variables
and substantially improved map and list handling.

diff --git a/src/zeshy/core b/src/zeshy/core
--- a/src/zeshy/core
+++ b/src/zeshy/core
@@ -20,6 +20,28 @@
 #   agnostic fashion.
 # * Incorporate ZSH-lovers fixes, including:
 #   * Use suffix aliases.
+# * It would be helpful to trap on INT (i.e., interrupt, <Ctrl-C>) and
+#   possibly conditionally on EXIT for non-zero exit status, printing a stack
+#   trace in such cases. It's unclear, however, how we can differentiate between
+#   a function call exiting with non-zero status but not erroneously (e.g., an
+#   ask_bool() call) and an external process exiting erroneously. Perhaps we
+#   can't, and I suspect that's the case. We can at least handle INT, however,
+#   and that seems worthwhile. URLs follow:
+#   * http://zsh.sourceforge.net/Doc/Release/Functions.html
+#   * http://fvue.nl/wiki/Bash:_Error_handling#The_tools
+#   Here's the most helpful example; replace function contents with stack trace
+#   printing:
+#       
+#       TRAPINT() {
+#           print "Caught SIGINT, aborting."
+#           return $(( 128 + $1 ))
+#       }
+#
+#   Important notes. We don't need to call the "trap" command. Simply defining
+#   this function notifies Zsh to set this trap. We need to return a non-zero
+#   result (any non-zero result will do) to notify Zsh that we didn't really
+#   handle the signal and that it should do so per normal. (Function traps are
+#   also nice in that subshells implicitly inherit them. Bingo!)
 
 # ....................{ PATHS                              }....................
 # Absolute path to the current script.
@@ -37,7 +59,7 @@ local zeshy_core_path=$(readlink --canonicalize-existing "${0}")
 # If "${HOME}" is the root directory, then this Zeshy process is probably
 # running as a cronjob, in which case this directory should reside under the
 # "/var" subsystem rather than the "/home" subsystem.
-if [[ "${HOME}" == / ]]
+if [[ "${HOME}" == '/' ]]
 then export ZESHY_CACHE_HOME="/var/cache/zeshy"
 else export ZESHY_CACHE_HOME="${HOME}/.zsh"
 fi
@@ -208,6 +230,12 @@ setopt rematch_pcre      # prefer Perl-Compatible Regular Expression matching
 setopt automenu          # use menu completion after 2 tabs
 setopt completeinword    # complete inside words
 setopt nolistambiguous   # only list matches if ambiguous
+
+# Variable expansion.
+#
+# Enforce strictness for safety as under conventional high-level languages.
+setopt nounset           # attempting to expand unset parameters raises an error
+setopt warn_create_global # attempting to set untyped parameters raises an error
 
 # ....................{ DECLARATORS ~ aliases              }....................
 # void global_alias(char *name, char *value)
@@ -467,35 +495,76 @@ alias die_unless_at_most_three_arguments="$(make_die_unless_alias '${#} -le 3')"
 unfunction make_die_unless_alias
 
 # ....................{ TESTS                              }....................
-#FIXME: The following two commands should work transparently on lists. Do they?
-# bool is_set(char *string)
+# bool is_set_nonempty(char *variable_name)
 #
-# Return success if the passed string is non-empty (i.e., not "").
+# Return true if the variable with the passed name is set and non-empty.
+is_set_nonempty() {
+    die_unless_one_argument 'expected exactly one variable name'
+    is -n "${(P)1-}" si    # See below.
+}
+
+# bool is_set(char *variable_name)
+#
+# Return true if the variable with the passed name is set (i.e., declared).
 is_set() {
-    is -n "${1}" si
+    die_unless_one_argument 'expected exactly one variable name'
+
+    # Decompacted:
+    # 
+    # * "1", the passed name.
+    # * "(P)", the variable the passed name refers to.
+    # * "+x", the value to expand this variable to if this variable is set.
+    #   Since any non-empty value will due, we arbitrarily use "x".
+    # * "-n", true only if this variable is "x" and hence set.
+    is -n "${(P)1+x}" si
 }
 
 # bool is_unset(char *string)
 #
-# Return success if the passed string is empty (i.e., "").
+# Return true if the  variable with the passed name is unset (i.e., undeclared).
 is_unset() {
+    die_unless_one_argument 'expected exactly one variable name'
+
+    # Decompacted:
+    # 
+    # * "1", the passed name.
+    # * "(P)", the variable the passed name refers to.
+    # * "-", the value to expand this variable to if this variable is unset.
+    #   For brevity, we use the empty string.
+    # * "-z", true only if this variable is the empty string and hence unset.
+    is -z "${(P)1-}" si
+}
+
+# bool is_nonempty(char *string)
+#
+# Return true if the passed string is non-empty (i.e., not "").
+is_nonempty() {
+    die_unless_one_argument 'expected exactly one string'
+    is -n "${1}" si
+}
+
+# bool is_empty(char *string)
+#
+# Return true if the passed string is empty (i.e., "").
+is_empty() {
+    die_unless_one_argument 'expected exactly one string'
     is -z "${1}" si
 }
 
 # bool is_cronjob(void)
 #
-# Return success if the current shell is a cronjob (i.e., is the grandchild of
+# Return true if the current shell is a cronjob (i.e., is the grandchild of
 # a "cron" process).
 is_cronjob() {
     die_unless_no_arguments
-    is_set "${ZESHY_IS_CRONJOB}"
+    is_nonempty "${ZESHY_IS_CRONJOB}"
 }
 
 # ....................{ TESTS ~ shell                      }....................
 #FIXME: Move to "shell", mayhap?
 # bool is_shell_interactive(void)
 #
-# Return success if the current shell is interactive or is a login shell.
+# Return true if the current shell is interactive or is a login shell.
 is_shell_interactive() {
     die_unless_no_arguments
     is -o interactive || -o login si
@@ -503,7 +572,7 @@ is_shell_interactive() {
 
 # bool is_terminal(void)
 #
-# Return success if the current shell is outputting to a terminal (i.e., 
+# Return true if the current shell is outputting to a terminal (i.e., 
 # interactive display). All calls to the "stty" binary should be wrapped in a
 # test for an active terminal; otherwise, one receives the following error
 # under non-terminals (e.g., under cron):
@@ -530,7 +599,7 @@ is_terminal && stty -ixon -ixoff
 # this original definition (since functions are not inherited via script
 # calls).
 get_script_name() {
-    if is_set "${ZESHY_SCRIPT_NAME}"; then
+    if is_nonempty "${ZESHY_SCRIPT_NAME}"; then
         echo  "${ZESHY_SCRIPT_NAME}"
     # If the current process is an interactive shell, then return the name of
     # the function that called this function excluding all intermediary I/O-
@@ -576,7 +645,7 @@ utter() {
     # Message to utter. (Yes, its definition must be in a separate command.)
     string message; message="$(get_script_name): ${@}"
     
-    if is_set "${ZESHY_IS_CRONJOB}"
+    if is_nonempty "${ZESHY_IS_CRONJOB}"
     then logger -p cron.notice -- "${message}"
     else echo "${message}"
     fi
@@ -591,7 +660,7 @@ mutter() {
     # Message to mutter. (Yes, its definition must be in a separate command.)
     string message; message="$(get_script_name): ${@}"
     
-    if is_set "${ZESHY_IS_CRONJOB}"
+    if is_nonempty "${ZESHY_IS_CRONJOB}"
     then logger -p cron.notice -- "${message}"
     else echo -n "${message}"
     fi
@@ -612,7 +681,7 @@ curse() {
     # Message to curse. (Yes, its definition must be in a separate command.)
     string message; message="$(get_script_name): ${@}"
     
-    if is_set "${ZESHY_IS_CRONJOB}"
+    if is_nonempty "${ZESHY_IS_CRONJOB}"
     then logger -p cron.err -- "${message}"
     else echo "${message}" 1>&2
     fi
@@ -629,7 +698,7 @@ utter_import() {
     # If the caller has supplied no explicit "${ZESHY_SCRIPT_NAME}", supply a
     # default.  Failing to do this encourages the utter() function to use the
     # name of this function as its script name, producing unaesthetic results.
-    is_set "${ZESHY_SCRIPT_NAME}" or string ZESHY_SCRIPT_NAME='zeshy'
+    is_nonempty "${ZESHY_SCRIPT_NAME}" or string ZESHY_SCRIPT_NAME='zeshy'
     utter "loading \"${1}\"..."
 }
 
@@ -827,7 +896,8 @@ run() {
     if is_absolute_path "${command_path}"; then
         # If the caller requests this command be run under a different user,
         # attempt to do so.
-        if is -n "${ZESHY_RUN_AS}" && "${ZESHY_RUN_AS}" != "$(whoami)" si; then
+        if is_set_nonempty 'ZESHY_RUN_AS' and
+           is "${ZESHY_RUN_AS}" != "${USER}" si; then
             # If the target user is the superuser, use "sudo" to take
             # advantage of password caching.
             #
@@ -1012,7 +1082,7 @@ match() {
 
     # Compile the match. (Yes, ZSH requires this regardless of whether we intend
     # to actually reuse this match.)
-    if is_set "${ZESHY_MATCH_OPTIONS}"; then 
+    if is_nonempty "${ZESHY_MATCH_OPTIONS}"; then 
 #       print "ZESHY_MATCH_OPTIONS: ${ZESHY_MATCH_OPTIONS}"
 #       pcre_compile -m "${pattern}" ||
         pcre_compile "${ZESHY_MATCH_OPTIONS[@]}" "${regex}" or
@@ -1168,7 +1238,7 @@ make_directory_if_not_found() {
     # While there are more paths to consider, shift the current path to be
     # considered to a local variable "new_path" and make it when not found.
     string new_path
-    while is_set "${1}"; do
+    while is "${#@}" -ne 0 si; do
         new_path="${1}"; shift
 
         if is -f "${new_path}" si; then
@@ -1299,16 +1369,7 @@ zimport_file() {
     string zeshy_script_path="${1}"; shift
     is -f "${zeshy_script_path}" si or
         die "\"${zeshy_script_path}\" not a file or not found"
-
-    #FIXME: Old.
-    # If the passed path is a directory, only import filename
-    # "${ZESHY_MAIN_SCRIPT_BASENAME}" in this directory.
-#   is -d "${zeshy_script_path}" si and
-#       zeshy_script_path="${zeshy_script_path}/${ZESHY_MAIN_SCRIPT_BASENAME}"
-    
-    # If this path does not exist, die.
-#   is -f "${zeshy_script_path}" si or die "\"${zeshy_script_path}\" not found"
-    
+   
     # Canonicalize the path so as to ensure the dictionary lookup below
     # successfully compares it against a previously canonicalized path.
     zeshy_script_path="$(canonicalize_path "${zeshy_script_path}")"
@@ -1318,7 +1379,8 @@ zimport_file() {
     
     # If the script has not yet been imported or has been imported but has
     # changed since being imported, do so.
-    if is -z "${ZESHY_IMPORTED_PATH_TO_MTIME["${zeshy_script_path}"]}" ||\
+#   if is_unset "ZESHY_IMPORTED_PATH_TO_MTIME["${zeshy_script_path}"]}" or\
+    if is -z "${ZESHY_IMPORTED_PATH_TO_MTIME[(I)"${zeshy_script_path}"]}" ||\
         "${ZESHY_IMPORTED_PATH_TO_MTIME["${zeshy_script_path}"]}" -ne\
         "${zeshy_script_mtime}" si; then
         # If the script corresponds to a command-specific script under
@@ -1393,16 +1455,16 @@ _zeshy_core() {
     # there, prior to their sourcing this script.
     #
     # Distinguish the former from the latter by noting whether the
-    # "${script_mtime}" variable has been set or not; if it has, this script
+    # "${zeshy_script_mtime}" variable has been set or not; if it has, this script
     # was sourced via zimport() rather than source().
-    is_set "${script_mtime}" or utter_import "${zeshy_core_path}"
+    is_unset 'zeshy_script_mtime' or utter_import "${zeshy_core_path}"
     
     # Set the default script name prior to all other logic, as any logic
     # raising an error requires this name for logging that error. Only do this
     # if the current process is not an interactive Zsh shell as, in that case,
     # the get_script_name() function dynamically inspects the script name from
     # the function call stack.
-    if is_unset "${ZESHY_SCRIPT_NAME}" and not is_shell_interactive; then
+    if is_empty "${ZESHY_SCRIPT_NAME}" and not is_shell_interactive; then
         # Import Zeshy components required below.
         zimport zeshy/os
         
@@ -1424,6 +1486,16 @@ _zeshy_core
 unset _zeshy_core
 
 #FIXME: Obsolete.
+
+    #FIXME: Old.
+    # If the passed path is a directory, only import filename
+    # "${ZESHY_MAIN_SCRIPT_BASENAME}" in this directory.
+#   is -d "${zeshy_script_path}" si and
+#       zeshy_script_path="${zeshy_script_path}/${ZESHY_MAIN_SCRIPT_BASENAME}"
+    
+    # If this path does not exist, die.
+#   is -f "${zeshy_script_path}" si or die "\"${zeshy_script_path}\" not found"
+ #
 #FIXME: Impossible to remember, I'm afraid. Perhaps "fail_if_error", instead?
 # int fail_if_previous_command_failed(void)
 # 
