Yet-another-unctuous-commit.
I genuinely expect this to constitute the last of the obvious
regressions. Excised a great deal of core cruft made redundant by the
recent move to TRAPZERR(). Also, added split_on_first() to Zeshy String
for additional string munging goodness.

diff --git a/src/zeshy/core b/src/zeshy/core
--- a/src/zeshy/core
+++ b/src/zeshy/core
@@ -22,8 +22,8 @@
 # * Incorporate ZSH-lovers fixes, including:
 #   * Use suffix aliases.
 # * The new trap support obsoletes an astonishing quantity of prior
-#   functionality (e.g., try(), die_unless_ok()). Such functionality should be
-#   retained, but exported out of this component into a new component: say,
+#   functionality (e.g., try()). Such functionality should be retained (???...
+#   perhaps not), but exported out of this component into a new component: say,
 #   "zeshy/shell/job".
 # * zimport() can profitably be renamed require(). The latter captures the
 #   intent and implementation much more succinctly and without the awkward
@@ -65,6 +65,35 @@ export ZESHY_COMPINIT_DUMP_FILE="${ZESHY_CACHE_HOME}/zcompdump"
 #     # Actually imports "zeshy/${ZESHY_MAIN_SCRIPT_BASENAME}", instead.
 #     >>> zimport zeshy
 export ZESHY_MAIN_SCRIPT_BASENAME='.main'
+
+# ....................{ BOOLEANS                           }....................
+# If non-empty, the current process is running as a cronjob. (Set below.)
+export ZESHY_IS_CRONJOB=
+
+#FIXME: Shift to "zeshy/shell/shell", after confirming die()'s FIXME comment.
+# ....................{ INTEGERS                           }....................
+# Success code, as returned by successful processes on process completion.
+export ZESHY_SUCCESS_CODE=0
+
+# Failure code, as returned by failed processes on process completion. Note
+# that, technically, any return code greater than or equal to this value
+# constitutes a process failure.
+export ZESHY_FAILURE_CODE=1
+
+# ....................{ STRINGS                            }....................
+# Human-readable name of the current script. This is used only for output.
+# Scripts are welcome to redefine it globally; likewise, functions are welcome
+# to redefine it locally. (Set below.)
+export ZESHY_SCRIPT_NAME=
+
+# ....................{ TESTS                              }....................
+# bool is_shell_interactive(void)
+#
+# Return true if the current shell is interactive or is a login shell.
+is_shell_interactive() {
+    [[ ${#} -eq 0 ]] || die 'expected no arguments'
+    [[ -o interactive || -o login ]]
+}
 
 # ....................{ CALL STACK                         }....................
 # For safety, trap functions and functions transitively called by such functions
@@ -216,6 +245,38 @@ curse() {
     fi
 }
 
+# ....................{ EXCEPTIONS                         }....................
+# void die(char *message = '')
+#
+# Echo the passed text according to the curse() function and exit the currently
+# executed script with error.
+die() {
+    # If the return code of the prior command signified an error, exit with
+    # that return code; otherwise, exit with generic error code 1.
+    integer return_code=${?}
+    [[ ${return_code} -eq ${ZESHY_SUCCESS_CODE} ]] &&
+              return_code=${ZESHY_FAILURE_CODE}
+    
+    # Print the passed error message and a complete stack trace.
+    curse "${@}"
+    print_stack_trace
+
+    # Die with the prior return code.
+    die_with ${return_code}
+}
+
+# void die_with(int return_code = 1)
+#
+# Exit the currently executed script or function with the passed return code.
+die_with() {
+    # If the current context is a function called from an interactive and/or
+    # login shell, unwind the call stack; otherwise, kill the current process.
+    if is_shell_interactive
+    then throw ZeshyException
+    else exit ${1:-${ZESHY_FAILURE_CODE}}
+    fi
+}
+
 # ....................{ TRAPS                              }....................
 # int TRAPINT(int signal_number = SIGINT)
 #
@@ -270,26 +331,6 @@ TRAPZERR() {
     # terminating the current shell on SIGZERR signals).
     die_with ${return_code}
 }
-
-# ....................{ BOOLEANS                           }....................
-# If non-empty, the current process is running as a cronjob. (Set below.)
-export ZESHY_IS_CRONJOB=
-
-#FIXME: Shift to "zeshy/shell/shell", after confirming die()'s FIXME comment.
-# ....................{ INTEGERS                           }....................
-# Success code, as returned by successful processes on process completion.
-export ZESHY_SUCCESS_CODE=0
-
-# Failure code, as returned by failed processes on process completion. Note
-# that, technically, any return code greater than or equal to this value
-# constitutes a process failure.
-export ZESHY_FAILURE_CODE=1
-
-# ....................{ STRINGS                            }....................
-# Human-readable name of the current script. This is used only for output.
-# Scripts are welcome to redefine it globally; likewise, functions are welcome
-# to redefine it locally. (Set below.)
-export ZESHY_SCRIPT_NAME=
 
 # ....................{ AUTOLOADS                          }....................
 # Autoload all autoloadable files. This permits all subsequent code to call
@@ -562,7 +603,7 @@ global_alias and='&&'
 # Negate the passed command's return code.
 alias not='!'
 
-# ....................{ FUNCTIONS ~ arguments              }....................
+# ....................{ ARGUMENTS ~ tests                  }....................
 # Define critical argument-specific aliases prior to defining functions
 # expanding these aliases. Otherwise, error ensues.
 
@@ -571,35 +612,31 @@ alias not='!'
 
 # bool is_no_arguments(void)
 #
-# Return success if this function was called with no arguments. Otherwise,
-# return failure.
-alias is_no_arguments='[[ ${#} -eq 0 ]]'
+# Return true only if the caller was called with no arguments.
+alias is_no_arguments='is ${#} -eq 0 si'
 
-# bool is_one_argument(void)
+# bool is_arguments(void)
 #
-# Return success if this function was called with one argument. Otherwise,
-# return failure.
-alias is_one_argument='[[ ${#} -eq 1 ]]'
-
-# bool is_two_argument(void)
-#
-# Return success if this function was called with two arguments. Otherwise,
-# return failure.
-alias is_two_arguments='[[ ${#} -eq 2 ]]'
-
-# bool is_at_least_one_argument(void)
-#
-# Return success if this function was called with at least one argument.
-# Otherwise, return failure.
-alias is_at_least_one_argument='[[ ${#} -ge 1 ]]'
+# Return true only if the caller was called with at least one argument.
+alias is_arguments='is ${#} -ne 0 si'
+alias is_at_least_one_argument=is_arguments
 
 # bool is_at_least_two_arguments(void)
 #
-# Return success if this function was called with at least two arguments.
-# Otherwise, return failure.
-alias is_at_least_two_arguments='[[ ${#} -ge 2 ]]'
+# Return true only if the caller was called with at least two arguments.
+alias is_at_least_two_arguments='is ${#} -ge 2 si'
 
-# ....................{ ALIASES ~ arguments ~ errors       }....................
+# bool is_one_argument(void)
+#
+# Return true only if the caller was called with exactly one argument.
+alias is_one_argument='is ${#} -eq 1 si'
+
+# bool is_two_arguments(void)
+#
+# Return true only if the caller was called with exactly two arguments.
+alias is_two_arguments='is ${#} -eq 2 si'
+
+# ....................{ ARGUMENTS ~ exceptions             }....................
 # As a convenience, all argument aliases except die_unless_no_arguments() first
 # attempt to read their argument from stdin when the caller passed no explicit
 # argument. This implies all functions expanding these aliases implicitly "get"
@@ -612,13 +649,13 @@ alias is_at_least_two_arguments='[[ ${#} -ge 2 ]]'
 # parameters if such input exists (i.e., if another function piped input to
 # this function) and the caller passed insufficient parameters.
 make_die_unless_alias() {
-    print "[[ -p /dev/stdin && ! ( ${1} ) ]] && set -- "'"$(< /dev/stdin)"'"; [[ ${1} ]] || die"
+    print "is -p /dev/stdin && ! ( ${1} ) si and set -- "'"$(< /dev/stdin)"'"; is ${1} si or die"
 }
 
 # void die_unless_no_arguments(void)
 #
 # Die with a canonical message unless the caller passed no arguments.
-alias die_unless_no_arguments='[[ ${#} -eq 0 ]] || die "expected no arguments"'
+alias die_unless_no_arguments='is ${#} -eq 0 si or die "expected no arguments"'
 
 # void die_unless_arguments(char *error_message)
 #
@@ -639,6 +676,11 @@ alias die_unless_two_arguments="$(make_die_unless_alias '${#} -eq 2')"
 #
 # Die with the passed message unless the caller passed exactly three arguments.
 alias die_unless_three_arguments="$(make_die_unless_alias '${#} -eq 3')"
+
+# void die_unless_four_arguments(char *error_message)
+#
+# Die with the passed message unless the caller passed exactly four arguments.
+alias die_unless_four_arguments="$(make_die_unless_alias '${#} -eq 4')"
 
 # void die_unless_one_or_two_arguments(char *error_message)
 #
@@ -753,100 +795,31 @@ is_cronjob() {
     is_nonempty "${ZESHY_IS_CRONJOB}"
 }
 
-# ....................{ TESTS ~ shell                      }....................
-#FIXME: Move to "shell", mayhap?
-# bool is_shell_interactive(void)
-#
-# Return true if the current shell is interactive or is a login shell.
-is_shell_interactive() {
-    die_unless_no_arguments
-    is -o interactive || -o login si
-}
-
-# bool is_terminal(void)
-#
-# Return true if the current shell is outputting to a terminal (i.e., 
-# interactive display). All calls to the "stty" binary should be wrapped in a
-# test for an active terminal; otherwise, one receives the following error
-# under non-terminals (e.g., under cron):
-#
-#     stty: standard input: Invalid argument
-is_terminal() {
-    die_unless_no_arguments
-    is -t 0 si
-}
-
-# Disable flow control key bindings, as these increasingly conflict with those
-# of popular CLI applications (e.g., irssi, rtorrent). Specifically, prevent
-# <Ctrl-s> and <Ctrl-q> from disabling and re-enabling flow control.
-is_terminal and stty -ixon -ixoff
-
-# ....................{ ERRORS                             }....................
-# void die(char *message = '')
-#
-# Echo the passed text according to the curse() function and exit the currently
-# executed script with error.
-die() {
-    # If the return code of the prior command signified an error, exit with
-    # that return code; otherwise, exit with generic error code 1.
-    integer return_code=${?}
-    is ${return_code} -eq ${ZESHY_SUCCESS_CODE} si and
-              return_code=${ZESHY_FAILURE_CODE}
-    
-    # Print the passed error message and die with the prior return code.
-    curse "${@}"
-    die_with ${return_code}
-}
-
-# void die_with(int return_code = 1)
-#
-# Exit the currently executed script or function with the passed return code.
-die_with() {
-    # If the current context is a function called from an interactive and/or
-    # login shell, unwind the call stack; otherwise, kill the current process.
-    if is_shell_interactive
-    then throw ZeshyException
-    else exit ${1:-${ZESHY_FAILURE_CODE}}
-    fi
-}
-
-#FIXME: No longer meaningful under TRAPZERR(); excise.
-# void die_unless_ok(char *error_message)
-#
-# Die with the passed error message unless the previous command succeeded.
-die_unless_ok() {
-    # Cache the prior command's return code, as our initial sanity check on
-    # arguments replaces this code with its own.
-    integer prior_command_return_code=${?}
-    die_unless_one_argument 'expected exactly one error message'
-    is ${prior_command_return_code} -eq ${ZESHY_SUCCESS_CODE} si or die "${1}"
-}
-
 # ....................{ COMMANDS                           }....................
-# bool is_installed(char *command)
+# bool is_installed(char *command_name)
 #
-# Return true if the passed command is installed on this system.
+# Return true if the command with the passed name is installed on this system.
 is_installed() {
     # Do not call the quietly() function, as that calls the run() function which
     # calls *THIS* function which induces an infinitely recursive loop. Agathoth 
     # and Memnon!
-    which_command_nonfatal "${@}" 1>/dev/null 2>&1
+    which_command "${@}" 1>/dev/null 2>&1
 }
 
-# void try_quietly_as(char *username, char *command)
+# char *which_command(char *command_name)
 #
-# Run the passed command as the passed user quietly and, if it fails with error,
-# terminate the current execution environment with the same error.
-try_as() {
-    die_unless_at_least_two_arguments\
-        'expected exactly one username and one command'
-
-    # Locally set "${ZESHY_RUN_AS}". The run() function notes this variable as
-    # set and behaves accordingly...
-    string ZESHY_RUN_AS="${1}"; shift
-
-    # Call try() with all remaining arguments: the command to be run.
-    try "${(q)@}"
+# If found, print the absolute path to the command with the passed name;
+# otherwise, return false. All but the first whitespace-delimited word of this
+# string is ignored: e.g.,
+#
+#     >>> which_command zsh
+#     /bin/zsh
+#     >>> which_command "zsh -x -o shwordsplit scr"
+#     /bin/zsh
+which_command() {
+    die_unless_one_argument 'expected exactly one command name'
+    string command_path command_name="${1[(w)1]}"
+    command_path="$(whence -cp "${command_name}")" and print "${command_path}"
 }
 
 # void run_as(char *username, char *command)
@@ -862,6 +835,23 @@ run_as() {
 
     # Call run() with all remaining arguments: the command to be run.
     run "${(q)@}"
+}
+
+#FIXME: This and try() now obsolete by TRAPZERR(). Excise everywhere.
+# void try_quietly_as(char *username, char *command)
+#
+# Run the passed command as the passed user quietly and, if it fails with error,
+# terminate the current execution environment with the same error.
+try_as() {
+    die_unless_at_least_two_arguments\
+        'expected exactly one username and one command'
+
+    # Locally set "${ZESHY_RUN_AS}". The run() function notes this variable as
+    # set and behaves accordingly...
+    string ZESHY_RUN_AS="${1}"; shift
+
+    # Call try() with all remaining arguments: the command to be run.
+    try "${(q)@}"
 }
 
 # void try(char *command)
@@ -920,11 +910,11 @@ run() {
     string command_name="${(Q)command[1]}"
     
     # Absolute path to the command to be run or the command name if this command
-    # is a built-in, alias, or function rather than an external command.
-    string command_path; command_path="$(whence "${command_name}")"
-    
-    # If the passed command does not exist, fail.
-    die_unless_ok "\"${command_name}\" not found; cannot run \"${command}\""
+    # is a built-in, alias, or function rather than an external command. If this
+    # command does not exist, fail.
+    string command_path
+    command_path="$(whence "${command_name}")" or
+        "\"${command_name}\" not found; cannot run \"${command}\""
 
     # Otherwise, if the passed command has not been overridden by a shell alias
     # or function, run it as a command. Do not call the customary is_installed()
@@ -1211,45 +1201,6 @@ get_path_mtime() {
     try zstat +mtime "${1}"
 }
 
-# ....................{ FILES ~ binaries                   }....................
-# Aliases.
-alias which_binary="which_command"
-alias which_binary_nonfatal="which_command_nonfatal"
-
-#FIXME: This function appears to be functionally obsolete now. If so, kill and
-#rename which_command_nonfatal() to this.
-
-# char *which_command(char *command)
-#
-# Print the absolute path to the passed command: e.g.,
-#
-#     >>> which_command zsh /bin/zsh
-#
-# If the passed command is a string, all but the first whitespace-delimited word
-# of the string is ignored: e.g.,
-#
-#     >>> which_command "zsh -x -o shwordsplit scr" /bin/zsh
-#
-# If the passed command is not found, if multiple binaries are passed, or if no
-# command is passed, prints an error and dies.
-which_command() {
-    # Call the whence() built-in outside of "local" so as to retain the return
-    # code. (ZSH == FAIL on that one.) 
-    string command_path; command_path="$(which_command_nonfatal "${@}")"
-    die_unless_ok "\"${1}\" not found"
-    print "${command_path}"
-}
-
-# char *which_command_nonfatal(char *command_name)
-#
-# Identical to the which_command() function except that, if the passed command
-# does not exist, returns nothing rather than dies.
-which_command_nonfatal() {
-    die_unless_one_argument 'expected exactly one command name'
-    string command_path command_name="${1[(w)1]}"
-    command_path="$(whence -cp "${command_name}")" and print "${command_path}"
-}
-
 # ....................{ FILES ~ directories                }....................
 #FIXME: Rename "make_dirs_recursively".
 # void make_directory_if_not_found(char *dirname1, char *dirname2, ...)
@@ -1507,9 +1458,51 @@ _zeshy_core() {
 
 # Call and then immediately unset (i.e., delete) _zeshy_core().
 _zeshy_core
-unset _zeshy_core
+unfunction _zeshy_core
 
 #FIXME: Obsolete.
+#FIXME: This function appears to be functionally obsolete now. If so, kill and
+#rename which_command() to this.
+# Aliases.
+#alias which_binary="which_command"
+#alias which_binary_nonfatal="which_command"
+
+# char *which_command(char *command)
+#
+# Print the absolute path to the passed command: e.g.,
+#
+#     >>> which_command zsh /bin/zsh
+#
+# If the passed command is a string, all but the first whitespace-delimited word
+# of the string is ignored: e.g.,
+#
+#     >>> which_command "zsh -x -o shwordsplit scr" /bin/zsh
+#
+# If the passed command is not found, if multiple binaries are passed, or if no
+# command is passed, prints an error and dies.
+#which_command() {
+#Call the whence() built-in outside of "local" so as to retain the return
+    # code. (ZSH == FAIL on that one.) 
+#    string command_path; command_path="$(which_command "${@}")"
+#    die_unless_ok "\"${1}\" not found"
+#    print "${command_path}"
+#}
+#
+# Identical to the which_command() function except that, if the passed command
+# does not exist, returns nothing rather than dies.
+
+#FIXME: No longer meaningful under TRAPZERR(); excise.
+# void die_unless_ok(char *error_message)
+#
+# Die with the passed error message unless the previous command succeeded.
+#die_unless_ok() {
+#    # Cache the prior command's return code, as our initial sanity check on
+#    # arguments replaces this code with its own.
+#    integer prior_command_return_code=${?}
+#    die_unless_one_argument 'expected exactly one error message'
+#    is ${prior_command_return_code} -eq ${ZESHY_SUCCESS_CODE} si or die "${1}"
+#}
+
 # void utter_import(char *script_name)
 #
 # Echo a message informing the user that the passed script name is being
