Substantial changes.
Added Zeshy Keychain and Zeshy Number. Also, augmented Zeshy OS with
additional memory usage getters, migrated $PATH-handling
functionality from "zprofile" to Zeshy Shell, and updated all
copyright notices with reference to 2011.

diff --git a/src/zeshy/core b/src/zeshy/core
--- a/src/zeshy/core
+++ b/src/zeshy/core
@@ -25,7 +25,7 @@ local zeshy_core_path=$(readlink --canonicalize-existing "${0}")
 # been permanently added to the current system on Zeshy installation. If it was
 # not, however, ensure that it at least temporarily exists now.
 [[ -n "${ZESHY_HOME}" ]] ||
-    export ZESHY_HOME=$(readlink --canonicalize-existing $(dirname "${zeshy_core_path}")"/..")
+    export ZESHY_HOME=$(readlink --canonicalize-existing $(dirname "${zeshy_core_path}")"/../..")
 
 # Directory to which Zeshy caches Zsh metadata. Note that Zsh itself is unaware
 # of this path until Zeshy explicitly instructs it to cache metadata here.
@@ -641,17 +641,7 @@ is_previous_command_succeeded() {
 }
 
 # ....................{ REGULAR EXPRESSIONS                }....................
-# void match_multiline(...)
-#
-# Match the passed string against the passed Perl-compatible regular expression
-# (PCRE) in a multi-line fashion (e.g., matching '^' and '$' at both newline and
-# the beginning and end of the string, respectively). In all other respects,
-# this function is identical to the match() function.
-match_multiline() {
-    local ZESHY_MATCH_OPTIONS
-          ZESHY_MATCH_OPTIONS=( -m )
-    match "${@}"
-}
+# For additional regular expression functionality, see "zeshy/string".
 
 # void match(
 #   char *regular_expression, char *string,
@@ -666,9 +656,14 @@ match_multiline() {
 # * The array corresponding to the passed array name to the list of all matched
 #   groups, defaulting to the global variable "${match}".
 #
-# Also, this function accepts a hidden "fifth parameter": the global variable
+# This function also accepts a hidden "fifth parameter": the global variable
 # "${ZESHY_MATCH_OPTIONS}", which when set causes this function to pass those
 # options to the pcre_compile() built-in when compiling the passed pattern.
+#
+# This function returns a string if and only if the passed regular expression
+# only matched one group. If it did not match or matched more than one groups,
+# this function returns nothing; in the latter case, callers must retrieve
+# these groups via the "${match}" array. (See above.)
 match() {
     [[ "${#}" -ge 2 ]] ||
         die 'expected at least one regular expression and one string'
@@ -683,6 +678,21 @@ match() {
     pcre_compile "${ZESHY_MATCH_OPTIONS[@]}" "${regular_expression}" ||
         die "\"${regular_expression}\" not a valid regular expression"
     pcre_match -v "${match_variable_name}" -a "${group_array_name}" -- "${string}"
+
+    # If this match matched only one group, return that. Otherwise, nil.
+    if ${#!group_array_name}
+}
+
+# void match_multiline(...)
+#
+# Match the passed string against the passed Perl-compatible regular expression
+# (PCRE) in a multi-line fashion (e.g., matching '^' and '$' at both newline and
+# the beginning and end of the string, respectively). In all other respects,
+# this function is identical to the match() function.
+match_multiline() {
+    local ZESHY_MATCH_OPTIONS
+          ZESHY_MATCH_OPTIONS=( -m )
+    match "${@}"
 }
 
 # ....................{ PROCESSES                          }....................
@@ -852,60 +862,69 @@ make_directory_if_not_found() {
 # * If none of the above are found, die.
 #
 # This function also accepts a directory rather than file, in which case it
-# imports a file named "main" under that directory: e.g.,
+# imports a file named ".main" under that directory: e.g.,
 #
-#     # Actually imports "zeshy/os/main".
+#     # Actually imports "zeshy/os/.main".
 #     >>> zimport zeshy/os
-# 
+#
 # This function is named "zimport" so as not to conflict with ImageMagick's
 # brashly named "import" command.
+#
+# --------------------( VARIABLES                          )--------------------
+# This function defines local variables, which imported scripts may safely
+# access for informative path metadata: namely,
+#
+# * "zeshy_script_name", having the relative path to the imported script under
+#   "${ZESHY_HOME}/src".
+# * "zeshy_script_path", having the absolute path to the imported script.
+# * "zeshy_script_mtime", having the modification time of the imported script.
 zimport() {
     [[ "${#}" -ge 1 ]] || die "expected exactly one script name"
     
     # Passed script name. Shift it off the argument stack, to allow us to pass
     # this script the set of all remaining arguments on sourcing it below.
-    local script_name="${1}" 
+    local zeshy_script_name="${1}" 
     shift
 
     # Absolute path to this script.
-    local script_path 
+    local zeshy_script_path 
     
     # If the passed script name is either an absolute path or existing relative
     # path, try to import it as is.
-    if [[ "${script_name[1]}" == '/' || -e "${script_name}" ]]
-    then script_path="${script_name}"
+    if [[ "${zeshy_script_name[1]}" == '/' || -e "${zeshy_script_name}" ]]
+    then zeshy_script_path="${zeshy_script_name}"
     # Otherwise, try to import a Zeshy component having that script name.
-    else script_path="${ZESHY_HOME}/${script_name}"
+    else zeshy_script_path="${ZESHY_HOME}/src/${zeshy_script_name}"
     fi
     
     # If the absolute path refers to a directory, assume the caller wants a
     # script named "_main" under this directory.
-    [[ -d "${script_path}" ]] &&
-        script_path="${script_path}/${ZESHY_MAIN_SCRIPT_BASENAME}"
+    [[ -d "${zeshy_script_path}" ]] &&
+        zeshy_script_path="${zeshy_script_path}/${ZESHY_MAIN_SCRIPT_BASENAME}"
     
     # If this path does not exist, die.
-    [[ -f "${script_path}" ]] || die "\"${script_path}\" not found"
+    [[ -f "${zeshy_script_path}" ]] || die "\"${zeshy_script_path}\" not found"
     
     # Canonicalize the path so as to ensure the dictionary lookup below
     # successfully compares it against a previously canonicalized path.
-    script_path="$(canonicalize_path "${script_path}")"
+    zeshy_script_path="$(canonicalize_path "${zeshy_script_path}")"
 
     # Modification time of this script.
-    local script_mtime="$(get_path_mtime "${script_path}")"
+    local zeshy_script_mtime="$(get_path_mtime "${zeshy_script_path}")"
     
     # If the script has not yet been imported or has been imported but has
     # changed since being imported, do so.
-    if [[ -z "${ZESHY_IMPORTED_PATH_TO_MTIME["${script_path}"]}" ||\
-        "${ZESHY_IMPORTED_PATH_TO_MTIME["${script_path}"]}" -ne\
-        "${script_mtime}" ]]; then
+    if [[ -z "${ZESHY_IMPORTED_PATH_TO_MTIME["${zeshy_script_path}"]}" ||\
+        "${ZESHY_IMPORTED_PATH_TO_MTIME["${zeshy_script_path}"]}" -ne\
+        "${zeshy_script_mtime}" ]]; then
         # Prior to doing so, record the script as being imported. This prevents
         # reimportation, should this script or another script imported by this
         # script attempt to import this script again.
-        ZESHY_IMPORTED_PATH_TO_MTIME["${script_path}"]="${script_mtime}"
+        ZESHY_IMPORTED_PATH_TO_MTIME["${zeshy_script_path}"]="${zeshy_script_mtime}"
          
         # Do so.
-        utter_import "${script_path}"
-        source "${script_path}" "${@}"
+        utter_import "${zeshy_script_path}"
+        source "${zeshy_script_path}" "${@}"
     fi
 }
 
@@ -1040,7 +1059,7 @@ _zeshy_core
 # The information below applies to everything in this distribution,
 # except where noted.
 #              
-# Copyleft 2007-2010 by Cecil Curry.
+# Copyleft 2007-2011 by Cecil Curry.
 #   
 #   http://www.raiazome.com
 # 
