Added Zeshy regex and rsync components.
Also, added a number of helpful shell- and string-handling utilities.

diff --git a/src/zeshy/core b/src/zeshy/core
--- a/src/zeshy/core
+++ b/src/zeshy/core
@@ -147,16 +147,8 @@ zmodload zsh/pcre
 # binary.
 zmodload -F zsh/stat b:zstat
 
-# Utility module adding additional built-ins, including:
-#
-# * "zparseopts", parsing command-line arguments. This built-in is similar in
-#   function if not style to the "getopts" binary, and typically used like so:
-#
-#   >>> set -- -d --ad "glass arm shattering"
-#   >>> zparseopts -A args -- d e -ad: -wing:
-#   >>> echo "-d: ${args[-d]}\n--ad: ${args[--ad]}"
-#   -d:
-#   --ad: glass arm shattering
+# Utility module adding additional built-ins, including the commonly called
+# "zformat", "zparseopts", and "zstyle" functions.
 zmodload zsh/zutil
 
 # ....................{ OPTIONS                            }....................
@@ -638,7 +630,7 @@ alias get_previous_command_return_code=is_previous_command_succeeded
 #
 # Return success if the previous command failed. Otherwise, return failure.
 is_previous_command_failed() {
-    [[ ${#} -eq 0 ]] || die "expected no arguments"
+    [[ ${#} -eq 0 ]] || die 'expected no arguments'
     if [[ ${?} -ne ${ZESHY_SUCCESS_CODE} ]]
     then return ${ZESHY_SUCCESS_CODE}
     else return ${ZESHY_FAILURE_CODE}
@@ -649,8 +641,24 @@ is_previous_command_failed() {
 #
 # Return success if the previous command succeeded. Otherwise, return failure.
 is_previous_command_succeeded() {
-    [[ ${#} -eq 0 ]] || die "expected no arguments"
+    [[ ${#} -eq 0 ]] || die 'expected no arguments'
     return ${?}
+}
+
+# int exit_with_failure(void)
+# 
+# Exit the current process with a failure return code.
+exit_with_failure() {
+    [[ ${#} -eq 0 ]] || die 'expected no arguments'
+    exit ${ZESHY_FAILURE_CODE}
+}
+
+# int exit_with_success(void)
+# 
+# Exit the current process with a successful return code.
+exit_with_success() {
+    [[ ${#} -eq 0 ]] || die 'expected no arguments'
+    exit ${ZESHY_SUCCESS_CODE}
 }
 
 # ....................{ REGULAR EXPRESSIONS                }....................
@@ -975,6 +983,14 @@ zimport() {
     if [[ -z "${ZESHY_IMPORTED_PATH_TO_MTIME["${zeshy_script_path}"]}" ||\
         "${ZESHY_IMPORTED_PATH_TO_MTIME["${zeshy_script_path}"]}" -ne\
         "${zeshy_script_mtime}" ]]; then
+        # If the script corresponds to a command-specific script (i.e., a script
+        # under "zeshy/command"), ensure the command is actually installed.
+        if [[ "${zeshy_script_path}" == */zeshy/command/* ]]; then
+            local command_name="${zeshy_script_path#*/zeshy/command/}"
+            is_installed "${command_name}" ||
+                die "\"${command_name}\" not installed or not found on \$PATH"
+        fi
+
         # Prior to doing so, record the script as being imported. This prevents
         # reimportation, should this script or another script imported by this
         # script attempt to import this script again.
diff --git a/src/zeshy/shell b/src/zeshy/shell
--- a/src/zeshy/shell
+++ b/src/zeshy/shell
@@ -6,8 +6,10 @@
 # Zeshy Shell. This Zeshy component implements shell-handling functionality.
 # This includes:
 #
-# * Reflection functionality for dynamically inspecting functions and aliases as
-#   "first-class constructs."
+# * Command-line argument parsing fuctionality for specifying and obtaining
+#   shell script arguments. 
+# * Reflection functionality for dynamically inspecting functions and aliases
+#   like first-class constructs.
 
 # --------------------( ALIASES                            )--------------------
 # Mimes.
@@ -40,33 +42,7 @@ is_function() {
     [[ $(whence -w "${1}") =~ ': function$' ]]
 }
 
-# ....................{ PASS-BY-VALUE                      }....................
-#FIXME: Document!
-return_value() {
-    [[ "${#}" -ge 1 ]] || die "expected at least one value"
-    echo "echo \"${@}\"; return ${ZESHY_SUCCESS_CODE}"
-}
-
-return_array() {
-    #FIXME: Test to make sure the passed array name actually is. How?
-    [[ "${#}" -ge 1 ]] || die "expected exactly one array name"
-    local array_name="${1}"
-    echo "echo \"${${(@qqkv)array_name}[@]}\"; return ${ZESHY_SUCCESS_CODE}"
-}
-
-obtain_array() {
-    #FIXME: Test to make sure the passed array name actually is. How?
-    [[ "${#}" -ge 2 ]] || die "expected one array name and one runnable command"
-    local array_name="${1}"; shift
-    local command="${@}"
-
-    #FIXME: Die if return code is failure?
-    echo "local _zeshy_obtained_array_as_scalar=\$(${command}); "
-    echo "${array_name}=( "${(Q@)${(z)_zeshy_obtained_array_as_scalar}}" ); "
-    echo "unset _zeshy_obtained_array_as_scalar"
-}
-
-# ....................{ UNSETTERS                          }....................
+# ....................{ DEATH                              }....................
 # void kill_callables(void)
 #
 # Destroy all existing aliases and functions. This is, of course, fairly
@@ -77,7 +53,7 @@ kill_callables() {
     unfunction -m '*'
 }
 
-# ....................{ SOURCES                            }....................
+# ....................{ REBIRTH                            }....................
 # void redot(void)
 #
 # Resource all Zsh startup scripts in the same order Zsh sources these scripts
@@ -120,7 +96,7 @@ redot() {
     source_if_found "${HOME}/.zlogin"
 }
 
-# ....................{ PATH                               }....................
+# ....................{ REBIRTH ~ path                     }....................
 # void PATH_init(void)
 #
 # Set the $PATH for the current user.
@@ -183,6 +159,84 @@ PATH_append() {
         else PATH="${dirname}"
         fi
     fi
+}
+
+# ....................{ ARGUMENT PARSING                   }....................
+# void parse_arguments(char *argument_spec1, char *argument_spec2, ...)
+#
+# Parse command-line arguments according to the passed list of argument
+# specifications into the "${ARGS}" global associative array. For convenience,
+# this function always registers the "-h" and "--help" options as valid options.
+# This function delegates to the zparseopts() built-in function and thus expects
+# argument specifications in the same (relatively simple) format: e.g.,
+#
+#   # Parse command-line options, with "--ad" a long option accepting no
+#   # argument, "--crest" a long option requiring an argument, and "--wing" a
+#   # long argument accepting an optional argument.
+#   % set -- -d --ad --crest "glass arm shattering"
+#   % parse_arguments d e -ad -crest: -wing::
+#   % (( ${+ARGS[-d]} )) && echo 'option "-d" passed!'
+#   option "-d" passed!
+#   % (( ${+ARGS[-d]} + ${+ARGS[--ad]} )) &&
+#   %     echo 'option "-d" AND/OR option "--ad" passed!'
+#   option "-d" AND/OR option "--ad" passed!
+#   % echo "-d: ${ARGS[-d]}\n--ad: ${ARGS[--crest]}\n--wing: ${ARGS[--wing]}"
+#   -d:
+#   --crest: glass arm shattering
+#   --wing:
+#
+# For details, see the "zparseopts" section of "man zshmodules".
+parse_arguments="zparseopts -D -E -A ARGS -- h -help" 
+
+# void check_parsed_arguments(char *help_message)
+#
+# Check the set of all parsed arguments for unknown options. If the caller
+# passed at least one unknown option OR the "-h" or "--help" options, die with
+# the passed help message. This function expects to be called immediately after
+# calling the parse_arguments() function.
+check_parsed_arguments() {
+    # If the immediately prior command failed, assume that was a call to the
+    # parse_arguments() function and enable a boolean noting this fact.
+    is_previous_command_succeeded && local is_parse_arguments_failed=1
+    
+    [[ ${#} -eq 1 ]] || die 'expected exactly one help string'
+    local help_message="${1}"
+    
+    # If the caller passed the "-h" or "--help" options, die without error.
+    if (( "${+ARGS[-h]}" + "${+ARGS[--help]}" )); then
+        print "${help_message}"
+        exit_with_success
+    # If the caller passed unknown options, die without error.
+    elif (( "${+is_parse_arguments_failed}" )); then
+        print "${help_message}"
+        exit_with_failure
+    fi
+}
+
+# ....................{ PASS-BY-VALUE                      }....................
+#FIXME: Document!
+return_value() {
+    [[ ${#} -ge 1 ]] || die 'expected at least one value'
+    echo "echo \"${@}\"; return ${ZESHY_SUCCESS_CODE}"
+}
+
+return_array() {
+    #FIXME: Test to make sure the passed array name actually is. How?
+    [[ ${#} -ge 1 ]] || die 'expected exactly one array name'
+    local array_name="${1}"
+    echo "echo \"${${(@qqkv)array_name}[@]}\"; return ${ZESHY_SUCCESS_CODE}"
+}
+
+obtain_array() {
+    #FIXME: Test to make sure the passed array name actually is. How?
+    [[ ${#} -ge 2 ]] || die 'expected one array name and one runnable command'
+    local array_name="${1}"; shift
+    local command="${@}"
+
+    #FIXME: Die if return code is failure?
+    echo "local _zeshy_obtained_array_as_scalar=\$(${command}); "
+    echo "${array_name}=( "${(Q@)${(z)_zeshy_obtained_array_as_scalar}}" ); "
+    echo "unset _zeshy_obtained_array_as_scalar"
 }
 
 #FIXME: Obsolete.
diff --git a/src/zeshy/string b/src/zeshy/string
--- a/src/zeshy/string
+++ b/src/zeshy/string
@@ -107,67 +107,16 @@ to_uppercase() {
     print "${(U)1}"
 }
 
-# ....................{ REGULAR EXPRESSIONS                }....................
-# char *match_first_group(...)
+# ....................{ MUTATORS                           }....................
+# char *suffix_if_not_already(char *string, char *suffix)
 #
-# Match the passed string against the passed Perl-compatible regular expression
-# (PCRE) and return the first matched group, if at least one such group matched,
-# or the empty string otherwise.
+# Suffix the passed string with the passed suffix, if not already: e.g.,
 #
-# In all other respects, this function is identical to the match() function.
-# In particular, note groups may still be obtained via the "${match}" array.
-match_first_group() {
-    match "${@}" || return ${?}
-
-    # Parse parameters.
-    local group_array_name="${4:-match}"
-
-    #FIXME: Uncommenting this causes *HORRIBLE, UTTERLY IMPOSSIBLE TO DEBUG*
-    #issues. And it shouldn't. But there it is.
-    # Localize the group array.
-#   typeset -Ag ${group_array_name}
-
-    # Retrieve the first group.
-    local first_group_name="${group_array_name}[1]"
-
-    # If this match matched at least one group, return that. Otherwise, nil.
-#   print "first_group_name: ${first_group_name}"
-    local first_group="${(P)first_group_name}"
-#   print "first_group: ${first_group}"
-    [[ -n "${first_group}" ]] && print "${first_group}"
-
-    return ${ZESHY_SUCCESS_CODE}
-}
-
-#FIXME: Does this actually work?
-# char *match_last_group(char *regular_expression, char *string)
-#
-# Match the passed string against the passed Perl-compatible regular expression
-# (PCRE) and return the last matched group, if at least one such group matched.
-match_last_group() {
-    [[ ${#} -eq 2 ]] ||
-        die 'expected exactly one regular expression and one string'
-        
-    # Parse parameters.
-    local pattern="${1}"
-    local string="${2}"
-
-    # Match. For simplicity, use "grep" rather than Zsh's "pcre" module.
-    try "echo '${string}' | tac | grep --extended-regexp -m 1 '${pattern}'"
-}
-
-# void match_multiline_first_group(...)
-#
-# Match the passed string against the passed Perl-compatible regular expression
-# (PCRE) in a multi-line fashion (e.g., matching '^' and '$' at both newline and
-# the beginning and end of the string, respectively) and return the first
-# matched group, if at least one such group matched, or the empty string
-# otherwise. In all other respects, this function is identical to the
-# match_multiline() function.
-match_multiline_first_group() {
-    local -a ZESHY_MATCH_OPTIONS
-             ZESHY_MATCH_OPTIONS=( -m )
-    match_first_group "${@}"
+#     >>> suffix_if_not_already '/habitat/failing/flailing/habits' '/'
+#     /habitat/failing/flailing/habits/
+suffix_if_not_already() {
+    [[ ${#} -eq 2 ]] || die 'expected exactly one string and one suffix'
+    print "${1%${2}}${2}"
 }
 
 # --------------------( COPYRIGHT AND LICENSE              )--------------------
