Substantial changes.
Added the "doc/examples/drupal-cohere" script, for scheduling rotated
backups of Drupal. Also, changed all instances of "Copyleft" to
"Copyright".

diff --git a/src/zeshy/file b/src/zeshy/file
--- a/src/zeshy/file
+++ b/src/zeshy/file
@@ -24,6 +24,25 @@ alias fsck.vfat="fsck.vfat ${ZESHY_FSCK_OPTIONS}"
 baobab()    { command baobab    "${@}" & }
 filelight() { command filelight "${@}" & }
 
+# ....................{ EXCEPTIONS                         }....................
+# void die_unless_installed(char *command_name)
+#
+# Raise an exception unless the passed command exists.
+die_unless_installed() {
+    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    local dirname="${1}"
+    is_installed "${dirname}" || die "\"${dirname}\" not found"
+}
+
+# void die_unless_dir(char *dirname)
+#
+# Raise an exception unless the passed directory exists.
+die_unless_dir() {
+    [[ ${#} -eq 1 ]] || die "expected exactly one path"
+    local dirname="${1}"
+    is_dir "${dirname}" || die "\"${dirname}\" not found"
+}
+
 # ....................{ FILENAMES                          }....................
 # bool is_path_absolute(char *path)
 #
@@ -307,7 +326,7 @@ move_to_temporary_directory() {
 # The information below applies to everything in this distribution,
 # except where noted.
 #              
-# Copyleft 2007-2011 by Cecil Curry.
+# Copyright 2007-2011 by Cecil Curry.
 #   
 #   http://www.raiazome.com
 # 
