Added recursive line counting to Zeshy Command.
This should be a help in concocting my Master's Thesis!

diff --git a/src/zeshy/file b/src/zeshy/file
--- a/src/zeshy/file
+++ b/src/zeshy/file
@@ -13,89 +13,88 @@ alias mvt="move_to_temporary_directory"
 # Filesystem checking (fsck). Note we do not implicitly pass the "-a" or "-p"
 # options to fsck, as fsck ignores some filesystem errors (e.g., superblock
 # mount time in the future) when those options are passed.
-FSCK_OPTIONS="-C -M -T"
-alias fsck="fsck ${FSCK_OPTIONS}"
-alias fsck.ext2="fsck.ext2 ${FSCK_OPTIONS}"
-alias fsck.ext3="fsck.ext3 ${FSCK_OPTIONS}"
-alias fsck.vfat="fsck.vfat ${FSCK_OPTIONS}"
+export ZESHY_FSCK_OPTIONS="-C -M -T"
+alias fsck="fsck ${ZESHY_FSCK_OPTIONS}"
+alias fsck.ext2="fsck.ext2 ${ZESHY_FSCK_OPTIONS}"
+alias fsck.ext3="fsck.ext3 ${ZESHY_FSCK_OPTIONS}"
+alias fsck.vfat="fsck.vfat ${ZESHY_FSCK_OPTIONS}"
 
 # ....................{ ALIASES ~ guis                     }....................
 # Disk usage.
-baobab()    { baobab    "${@}" & }
-filelight() { filelight "${@}" & }
+baobab()    { command baobab    "${@}" & }
+filelight() { command filelight "${@}" & }
 
 # ....................{ FILES                              }....................
-# char *which_files_nonfatal(char *filename1, *filename2, ...)
+# char *get_basename_sans_filetype(char *filename)
 #
-# Print the absolute path to the first filename in the list of passed filenames
-# which exists: e.g.,
+# Get the basename sans filetype of the passed filename. If this filename has no
+# filetype, this is the filename itself. Note this only excludes the rightmost
+# filetype: e.g.,
 #
-#     >>> which_files_nonfatal '/the_ancient.one' '/the_king_in.yellow' '/tmp'
-#     /tmp
-which_files_nonfatal() {
-    [[ "${#}" -ge 1 ]] || die "expected at least one filename"
-    
-    # While there are more filenames to consider, shift the current filename to
-    # be considered to a local variable "path".
-    local filename
-    while [[ -n "${1}" ]]; do
-        filename="${1}"
-        shift
-
-        # If this filename exists and is readable, return it.
-        if [[ -r "${filename}" ]]; then
-            echo "${filename}"
-            return ${ZESHY_SUCCESS_CODE}
-        fi
-    done
-    
-    # No filenames in the list of passed filenames exist. Return with failure.
-    return ${ZESHY_FAILURE_CODE}
+#     >>> get_basename_sans_filetype('hastur.tar.gz')
+#     hastur.tar
+get_basename_sans_filetype() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one filename"
+    echo "${1%.*}"
 }
 
-# ....................{ FILES ~ binaries                   }....................
-# char *which_binaries_nonfatal(char *binary_name1, *binary_name2, ...)
+# char *get_filetype(char *filename)
 #
-# Print the absolute path to the first binary in the list of passed binaries
-# which exists: e.g.,
+# Get the filetype of the passed filename. If this filename has no filetype,
+# this is the empty string. Note the only matches the rightmost filetype: e.g.,
 #
-#     >>> which_binaries_nonfatal Council_of_Nicea Constantinople zsh
-#     /bin/zsh
-# 
-# This function is intended to automate selection of binaries, in descending
-# order of preference. (In the above example, the hypothetical
-# "Council_of_Nicea" binary would be selected before all following binaries on
-# systems having the binary.)
-which_binaries_nonfatal() {
-    [[ "${#}" -ge 1 ]] || die "expected at least one binary name"
-    
-    # While there are more binaries to consider, shift the current binary to be
-    # considered to a local variable "binary_name".
-    local binary_name binary_path
-    while [[ -n "${1}" ]]; do
-        binary_name="${1}"
-        shift
+#     >>> get_filetype('hastur.tar.gz')
+#     gz
+get_filetype() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one filename"
+    local filename="${1}"
+    local filetype="${filename##*.}"
 
-        # If this binary exists, return the absolute path to it.
-        binary_path=$(which_binary_nonfatal "${binary_name}")
-        if [[ ${?} -eq ${ZESHY_SUCCESS_CODE} ]]; then
-            echo "${binary_path}"
-            return ${ZESHY_SUCCESS_CODE}
-        fi
-    done
-    
-    # No binaries in the list of passed binaries exist. Return with failure.
-    return ${ZESHY_FAILURE_CODE}
+    # If this filename has no filetype, then the above parameter expansion
+    # matched the filename itself, in which case we test for and ignore this. 
+    [[ "${filetype}" == "${filename}" ]] || echo "${filetype}"
+}
+
+# ....................{ FILES ~ types                      }....................
+# bool is_file_binary(char *filename)
+#
+# Return success if the passed filename corresponds to a binary file (i.e., not
+# a text file). (If the passed filename corresponds to a directory instead, this
+# function always returns failure.)
+is_file_binary() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one filename"
+    local filename="${1}"
+
+    if [[ -f "${filename}" ]]
+    then file --mime-encoding "${filename}" | grep --quiet ': binary$'
+    else return "${ZESHY_FAILURE_CODE}"
+    fi
+}
+
+# bool is_file_text(char *filename)
+#
+# Return success if the passed filename corresponds to a text file (i.e., not a
+# binary file). (If the passed filename corresponds to a directory instead, this
+# function always returns failure.)
+is_file_text() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one filename"
+    local filename="${1}"
+
+    # Do not simply do "! is_file_binary", as that incorrectly returns success
+    # on non-files.
+    if [[ -f "${filename}" ]]
+    then file --mime-encoding "${filename}" | grep --invert-match --quiet ': binary$'
+    else return "${ZESHY_FAILURE_CODE}"
+    fi
 }
 
 # ....................{ FILES ~ mounts                     }....................
-# bool is_mount_point(char *dirname)
+# bool is_directory_mount_point(char *dirname)
 #
 # Return success if the passed directory name is an existing mount point (i.e.,
 # if "something" is currently mounted under this directory).
-is_mount_point() {
-    # Ensure sanity.
-    [[ "${#}" -eq 1 ]] || die "expected exactly one pathname"
+is_directory_mount_point() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one dirname"
     local mount_point="${1}"
     
     # If the passed pathname does not correspond to an existing directory, it
@@ -103,11 +102,10 @@ is_mount_point() {
     [[ -d "${mount_point}" ]] || return "${ZESHY_FAILURE_CODE}"
 
     # If the "mountpoint" binary is available, use that.
-    if is_runnable mountpoint; then
-        mountpoint -q "${mount_point}"
+    if is_installed mountpoint
+    then mountpoint -q "${mount_point}"
     # Otherwise, manually grep "${ZESHY_MOUNT_POINTS_FILE}".
-    else
-        grep -q "${mount_point}" "${ZESHY_MOUNT_POINTS_FILE}"
+    else grep -q "${mount_point}" "${ZESHY_MOUNT_POINTS_FILE}"
     fi
 }
 
@@ -125,14 +123,14 @@ mount_iso() {
         die "\"${iso_filename}\" not an ISO filename"
     [[ -f "${iso_filename}" ]] ||
         die "\"${iso_filename}\" not found"
-    local SCRIPT_NAME='mount-iso'
+    local ZESHY_SCRIPT_NAME='mount_iso'
 
     # Find a suitable mount path.
     local iso_mount_path_prefix="${ZESHY_MOUNT_ISO_PATH}"
     local iso_mount_path_suffix=0
     local iso_mount_path="${iso_mount_path_prefix}"
     utter "searching for an available mount point..."
-    while is_mount_point "${iso_mount_path}"; do
+    while is_directory_mount_point "${iso_mount_path}"; do
         iso_mount_path_suffix=$(( iso_mount_path_suffix + 1 ))
         iso_mount_path="${iso_mount_path_prefix}${iso_mount_path_suffix}"
     done
@@ -210,6 +208,69 @@ which_temporary_file() {
             break
         fi
     done
+}
+
+# ....................{ FILES ~ which                      }....................
+# char *which_files_nonfatal(char *filename1, *filename2, ...)
+#
+# Print the absolute path to the first filename in the list of passed filenames
+# which exists: e.g.,
+#
+#     >>> which_files_nonfatal '/the_ancient.one' '/the_king_in.yellow' '/tmp'
+#     /tmp
+which_files_nonfatal() {
+    [[ "${#}" -ge 1 ]] || die "expected at least one filename"
+    
+    # While there are more filenames to consider, shift the current filename to
+    # be considered to a local variable "path".
+    local filename
+    while [[ -n "${1}" ]]; do
+        filename="${1}"
+        shift
+
+        # If this filename exists and is readable, return it.
+        if [[ -r "${filename}" ]]; then
+            echo "${filename}"
+            return ${ZESHY_SUCCESS_CODE}
+        fi
+    done
+    
+    # No filenames in the list of passed filenames exist. Return with failure.
+    return ${ZESHY_FAILURE_CODE}
+}
+
+# char *which_binaries_nonfatal(char *binary_name1, *binary_name2, ...)
+#
+# Print the absolute path to the first binary in the list of passed binaries
+# which exists: e.g.,
+#
+#     >>> which_binaries_nonfatal Council_of_Nicea Constantinople zsh
+#     /bin/zsh
+# 
+# This function is intended to automate selection of binaries, in descending
+# order of preference. (In the above example, the hypothetical
+# "Council_of_Nicea" binary would be selected before all following binaries on
+# systems having the binary.)
+which_binaries_nonfatal() {
+    [[ "${#}" -ge 1 ]] || die "expected at least one binary name"
+    
+    # While there are more binaries to consider, shift the current binary to be
+    # considered to a local variable "binary_name".
+    local binary_name binary_path
+    while [[ -n "${1}" ]]; do
+        binary_name="${1}"
+        shift
+
+        # If this binary exists, return the absolute path to it.
+        binary_path=$(which_binary_nonfatal "${binary_name}")
+        if [[ ${?} -eq ${ZESHY_SUCCESS_CODE} ]]; then
+            echo "${binary_path}"
+            return ${ZESHY_SUCCESS_CODE}
+        fi
+    done
+    
+    # No binaries in the list of passed binaries exist. Return with failure.
+    return ${ZESHY_FAILURE_CODE}
 }
 
 # --------------------( COPYRIGHT AND LICENSE              )--------------------
