Improved match counting in Zeshy Regex and String.
Specifically, added functionality for counting the number of
occurrences of one string in another via both glob and regular
expression-based approaches. Surprisingly non-trivial, in both
cases.

diff --git a/src/zeshy/regex b/src/zeshy/regex
--- a/src/zeshy/regex
+++ b/src/zeshy/regex
@@ -6,44 +6,154 @@
 # Zeshy Regex. This Zeshy component implements supplementary regular expression-
 # handling functionality. Note that Zeshy Core already implements basic support
 # for regular expressions.
+#
+# --------------------( CONVENTIONS                        )--------------------
+# All regular expressions matched by this component are Perl-compatible regular
+# expressions (PCRE), unless otherwise stated. Thus, we abbreviate such regular
+# expressions "regexes."
+# 
+# All functions defined by this component accept the same number and type of
+# parameters as the core match() function, unless otherwise stated. Thus, we
+# abbreviate such parameters "...". 
 
 # ....................{ IMPORTS                       }....................
-zimport zeshy/string
+#zimport zeshy/string
 
-# ....................{ MATCH ~ lines                      }....................
-# int get_matching_lines(...)
+# ....................{ MATCHES                            }....................
+# int get_number_of_matches(...)
 #
-# Return the number of lines matching the passed Perl-compatible regular
-# expression (PCRE). Unlike many other Zeshy matching functions, this function
-# uses "grep" rather than the "zsh/pcre" module. This is due to the fact that
-# the latter provides no efficient mechanism for obtaining all non-overlapping
-# matches.
+# Return the number of matches in the passed string. Among other uses, this
+# function counts occurrences of characters and substrings in strings: e.g.,
 #
-# Unfortunately, this means that groups may *NOT* be obtained via the "${match}"
-# array.
-get_matching_lines() {
+#     >>> get_number_of_matches 'rop[aeiou]' 'anthropocene tropes'
+#     2
+#
+# See also the get_number_of_glob_matches() function, which behaves similarly
+# but less efficiently -- matching via multiple glob rather than one regular
+# expression.
+get_number_of_matches() {
     die_unless_at_least_two_arguments\
         'expected at least one regular expression and one string'
+    local regex="${1}" string="${2}" string_newlined
 
+    # Escape """ and "~" characters in the passed string, in preparation for
+    # replacement by "sed".
+    string="${string//\"/\\\"}"
+    string="${string//\~/\\~}"
+
+    # This exceptionally clever (and frankly obscene) logic comes inspired by
+    # StackOverflow user "user216915" via this question:
+    #
+    #     http://stackoverflow.com/questions/1781329/count-the-number-of-occurrences-of-a-string-using-sed
+    #
+    # Sadly, neither sed, awk, grep, or zsh itself have any coherent means of
+    # matching individual occurences regardless of newline; rather, they only
+    # match each such occurence as a newline-specific group. This hack uses this
+    # newline obsession by replacing each match with that match suffixed by a
+    # newline. This guarantees no more than one match occupies each line.
+    #
+    # Finally, feeding the result into "grep -c" counts the number of such lines
+    # and hence the number of matches. (Yeth, this sucketh mightily.)
+#   print "sed expression: s/${(q)regex}/${(q)regex}\n/g"
+    string_newlined="$(print "${string}" | sed --regexp-extended "s~(${regex})~\1\n~g")"
+    die_unless_ok "string \"${string}\" or regular expression \"${regex}\" malformed"
+#   print "string_newlined: ${string_newlined}"
+
+    # If "sed" did nothing, then neither should we.
+    if [[ "${string}" == "${string_newlined}" ]]
+    then print 0
+    else try "print '${string_newlined}' | grep --perl-regexp --count '${regex}'"
+    fi
+}
+
+# ....................{ GROUPS ~ first                     }....................
+# char *match_first_group(...)
+#
+# Return the first group to successfully match in the passed string against the
+# passed regex. If no group matched, fail.
+#
+# In all other respects, this function is identical to the match() function.
+# In particular, note groups may still be obtained via the "${match}" array.
+match_first_group() {
+    # Match.
+    match "${@}" || return ${?}
+
+    # Parse parameters.
+    local group_array_name="${4:-match}"
+
+    #FIXME: Uncommenting this causes *HORRIBLE, UTTERLY IMPOSSIBLE TO DEBUG*
+    #issues. And it shouldn't. But there it is.
+    # Localize the group array.
+#   typeset -Ag ${group_array_name}
+
+    # Retrieve the first group.
+    local first_group_name="${group_array_name}[1]"
+
+    # If this match matched at least one group, return that. Otherwise, nil.
+#   print "first_group_name: ${first_group_name}"
+    local first_group="${(P)first_group_name}"
+#   print "first_group: ${first_group}"
+
+    # If there exists at least one group, print the first and return success;
+    # otherwise, print nothing and return failure.
+    is "${first_group}" && print "${first_group}"
+}
+
+# void match_multiline_first_group(...)
+#
+# Return the first group to successfully match in the passed string against the
+# passed regex, in a multi-line fashion (e.g., matching '^' and '$' at both
+# newline and the beginning and end of the string). If no group matched, fail.
+#
+# This function is otherwise identical to the match_multiline() function.
+match_multiline_first_group() {
+    local -a ZESHY_MATCH_OPTIONS
+             ZESHY_MATCH_OPTIONS=( -m )
+    match_first_group "${@}"
+}
+
+# ....................{ GROUPS ~ last                      }....................
+#FIXME: Does this actually work? And even if it does, we really should be using
+#the ZSH "pcre" facility to guarantee as-expected interpretation of the regex.
+# char *match_last_group(char *regular_expression, char *string)
+#
+# Match the passed string against the passed Perl-compatible regular expression
+# (PCRE) and return the last matched group, if at least one such group matched.
+match_last_group() {
+    die_unless_at_least_two_arguments\
+        'expected exactly one regular expression and one string'
+        
     # Parse parameters.
     local regexp="${1}"
     local string="${2}"
 
-    try "echo '${string}' | grep --perl-regexp '${regexp}'"
+    # Match. For simplicity, use "grep" rather than Zsh's "pcre" module.
+    try "echo '${string}' | tac | grep --perl-regexp -m 1 '${regexp}'"
+}
+
+# ....................{ LINES                              }....................
+# char *get_matching_lines(...)
+#
+# Return all lines matching the passed regex. Unlike most Zeshy matching
+# functions, this function uses "grep" rather than the "zsh/pcre" module as the
+# latter provides no efficient means of obtaining non-overlapping matches.
+#
+# Unfortunately, this implies groups are inaccessible.
+get_matching_lines() {
+    die_unless_at_least_two_arguments\
+        'expected at least one regular expression and one string'
+#   local regexp="${1}" string="${2}"
+    try "echo '${2}' | grep --perl-regexp '${1}'"
 }
 
 # int get_number_of_matching_lines(...)
 #
-# Return the number of lines matching the passed Perl-compatible regular
-# expression (PCRE). Unlike many other Zeshy matching functions, this function
-# uses "grep" rather than the "zsh/pcre" module. This is due to the fact that
-# the latter provides no efficient mechanism for obtaining all non-overlapping
-# matches.
-#
-# Unfortunately, this means that groups may *NOT* be obtained via the "${match}"
-# array.
+# Return the number of lines matching the passed regex. See the
+# get_matching_lines() function for caveats.
 get_number_of_matching_lines() {
-    try "get_matching_lines '${@}' | get_line_count"
+    die_unless_at_least_two_arguments\
+        'expected at least one regular expression and one string'
+    try "echo '${2}' | grep --perl-regexp --count '${1}'"
 }
 
 # char *match_first_line(...)
@@ -74,7 +184,7 @@ match_first_line() {
     # arguments, for convenience.
     set -- "${regex}" "${@}"
 
-    # Perform the match.
+    # Match.
     match_multiline "${@}" || return ${?}
 
     # Print the first matching line.
@@ -83,71 +193,23 @@ match_first_line() {
     return ${ZESHY_SUCCESS_CODE}
 }
 
-# ....................{ MATCH ~ groups                     }....................
-# char *match_first_group(...)
-#
-# Match the passed string against the passed Perl-compatible regular expression
-# (PCRE). If there exists at least one successful match group, return that;
-# otherwise, return failure.
-#
-# In all other respects, this function is identical to the match() function.
-# In particular, note groups may still be obtained via the "${match}" array.
-match_first_group() {
-    # Perform the match.
-    match "${@}" || return ${?}
+#FIXME: Obsolete.
+#   local regexp="${1}" string="${2}"
+#   try "get_matching_lines '${@}' | get_line_count"
+#   try "echo '${string}' | sed 's/${regex}/${regex}\n/g' | grep --perl-regexp --count '${regex}'"
+#   return
+#       die "\"${string}\" not matched by regular expression \"${regex}\""
+    # If the passed regex contains no groups, embed that regex in a group
+    # matching the entire prior regex.
+#   [[ "${1}" == *\(*\)* ]] || set -- "(${regex})" "${@}"
 
-    # Parse parameters.
-    local group_array_name="${4:-match}"
+    # Match.
+#   match "${@}" || return ${?}
+#   echo "${#match}"
 
-    #FIXME: Uncommenting this causes *HORRIBLE, UTTERLY IMPOSSIBLE TO DEBUG*
-    #issues. And it shouldn't. But there it is.
-    # Localize the group array.
-#   typeset -Ag ${group_array_name}
-
-    # Retrieve the first group.
-    local first_group_name="${group_array_name}[1]"
-
-    # If this match matched at least one group, return that. Otherwise, nil.
-#   print "first_group_name: ${first_group_name}"
-    local first_group="${(P)first_group_name}"
-#   print "first_group: ${first_group}"
-
-    # If there exists at least one group, print the first and return success;
-    # otherwise, print nothing and return failure.
-    [[ -n "${first_group}" ]] && print "${first_group}"
-}
-
-#FIXME: Does this actually work? And even if it does, we really should be using
-#the ZSH "pcre" facility to guarantee as-expected interpretation of the regex.
-# char *match_last_group(char *regular_expression, char *string)
-#
-# Match the passed string against the passed Perl-compatible regular expression
-# (PCRE) and return the last matched group, if at least one such group matched.
-match_last_group() {
-    die_unless_at_least_two_arguments\
-        'expected exactly one regular expression and one string'
-        
-    # Parse parameters.
-    local regexp="${1}"
-    local string="${2}"
-
-    # Match. For simplicity, use "grep" rather than Zsh's "pcre" module.
-    try "echo '${string}' | tac | grep --perl-regexp -m 1 '${regexp}'"
-}
-
-# void match_multiline_first_group(...)
-#
-# Match the passed string against the passed Perl-compatible regular expression
-# (PCRE) in a multi-line fashion (e.g., matching '^' and '$' at both newline and
-# the beginning and end of the string, respectively) and return the first
-# matched group, if at least one such group matched, or the empty string
-# otherwise. In all other respects, this function is identical to the
-# match_multiline() function.
-match_multiline_first_group() {
-    local -a ZESHY_MATCH_OPTIONS
-             ZESHY_MATCH_OPTIONS=( -m )
-    match_first_group "${@}"
-}
+    # Print the number of matches.
+#   local group_array_name="${4:-match}"
+#   print "${(P)#group_array_name}"
 
 # --------------------( COPYRIGHT AND LICENSE              )--------------------
 # The information below applies to everything in this distribution,
