Fixed a Zeshy Core bug in which_binary().
Also, moved the screenify() function into Zeshy Server.

diff --git a/src/zeshy/server b/src/zeshy/server
--- a/src/zeshy/server
+++ b/src/zeshy/server
@@ -75,6 +75,47 @@ mysql-set-password() {
     try mysqladmin -u "${username}" password "${password}"
 }
 
+# ....................{ SCREEN                             }....................
+# void screenify(char *command, char *username = $(whoami))
+#
+# Screenify the passed command. Specifically:
+#
+# * If no screen session named according to the basename of the passed command
+#   has been attached to the passed user, then attach a new screen session 
+#   having this name to this user running the passed command.
+# * Otherwise, reattach this existing screen session to this user.
+#
+# The username defaults to the current user, if not passed.
+screenify() {
+    [[ "${#}" -ge 1 ]] || die 'expected at least a command'
+
+    # Parse passed parameters.
+    local screen_command="${1}"
+    local screen_session="$(basename "${screen_command}")"
+    local screen_username="${2}"
+    [[ -z "${screen_username}" ]] || screen_username=$(whoami)
+    
+    # Locate "screen" and check whether or not a session already exists.
+    local screen=$(which_binary screen)
+    local screen_session_count=$(run_as "${screen_username}"\
+        "${screen} -list | command grep --count '\.${screen_session}[[:space:]]'")
+
+    # screen's argument passing engine is a wee faulty. Order is important in
+    # the argument list below, therefore.
+    if   [[ "${screen_session_count}" -eq 0 ]]; then
+        utter "attaching ${screen_session}..."
+        run_as "${screen_username}"\
+            ${screen} -m -fa -U -S "${screen_session}" "${screen_command}" ||
+            die "\"${screen_session}\" screen session could not be started"
+    elif [[ "${screen_session_count}" -eq 1 ]]; then
+        utter "reattaching ${screen_session}..."
+        run_as "${screen_username}" ${screen} -d -a -A -r "${screen_session}" 
+    else
+        die "${screen_session_count} \"${screen_session}\" screen sessions already started"
+    fi
+}
+
+
 # --------------------( COPYRIGHT AND LICENSE              )--------------------
 # The information below applies to everything in this distribution,
 # except where noted.
