Extreme large-scale revisions.
Changes too numerous to mention, ushering in the festive New Year
with a compatibility-breaking *BANG*! (So... there.)

diff --git a/src/zeshy/shell b/src/zeshy/shell
--- a/src/zeshy/shell
+++ b/src/zeshy/shell
@@ -3,88 +3,15 @@
 #                     [ Time-stamp: "2009-04-18 19:29:36 leycec" ]
 #
 # --------------------( SYNOPSIS                           )--------------------
-# Zeshy Shell. This Zeshy component implements shell-handling functionality.
-# This includes:
+# Zeshy Shell, implementing shell-handling functionality: e.g.,
 #
 # * Command-line argument parsing fuctionality for specifying and obtaining
 #   shell script arguments. 
-# * Reflection functionality for dynamically inspecting functions and aliases
-#   like first-class constructs.
-
-# ....................{ REFLECTION ~ tests                 }....................
-# bool is_builtin(char *builtin_name)
 #
-# Return true if there exists a built-in (i.e., C function accessible to all Zsh
-# shells and scripts) with the passed name.
-is_builtin() {
-    die_unless_one_argument 'expected exactly one name'
-    of $(whence -w "${1}") =~ ': builtin$' fo
-}
-
-# bool is_function(char *function_name)
-#
-# Return true if there exists a function with the passed name.
-is_function() {
-    die_unless_one_argument 'expected exactly one name'
-    of $(whence -w "${1}") =~ ': function$' fo
-}
-
-# ....................{ REFLECTION ~ tests ~ aliases       }....................
-# bool is_alias(char *alias_name)
-#
-# Return true if there exists an alias with the passed name.
-is_alias() {
-    die_unless_one_argument 'expected exactly one name'
-    quietly alias "${1}" 
-}
-
-# bool is_suffix_alias(char *alias_name)
-#
-# Return true if there exists a suffix alias with the passed name.
-is_suffix_alias() {
-    die_unless_one_argument 'expected exactly one name'
-    quietly suffix_alias "${1}" 
-}
-
-# ....................{ REFLECTION ~ tests ~ variable      }....................
-# bool is_variable(char *variable_name)
-#
-# Return true if there exists a variable with the passed name.
-is_variable() {
-    die_unless_one_argument 'expected exactly one name'
-    is "${(tP)1}"  # see get_type() for details
-}
-
-# bool is_local_variable(char *variable_name)
-#
-# Return true if there exists a local variable with the passed name.
-is_local_variable() {
-    die_unless_one_argument 'expected exactly one name'
-    string variable_type="${(tP)1}"  # see get_type() for details
-    is "${variable_type}" and of "${variable_type}" == *-local fo
-}
-
-# ....................{ REFLECTION ~ types                 }....................
-# char *get_type(void *name)
-#
-# Return the type of the object (e.g., function, variable) corresponding to the
-# passed variable name or "not-found" if there exists no such object.
-get_type() {
-    die_unless_one_argument 'expected exactly one name'
-    string name="${1}"
-    
-    # First, test if there exists a corresponding variable.
-    string type="${(tP)name}"
-
-    # Failing that, test if there exists a corresponding callable. Failing that,
-    # use the string returned by the whence() built-in: "none".
-    if is_not "${type}"; then
-        type="$(whence -w "${name}")"
-        type="${type##*: }"
-    fi
-    
-    echo "${type}"
-}
+# --------------------( TODO                               )--------------------
+# * Shell-specific components (e.g., "shell", "terminal", "style") should
+#   probably be centralized under a new "src/zeshy/shell" directory and this
+#   component renamed to ".main". Yes, this is *AWESOME*!
 
 # ....................{ DEATH                              }....................
 # void kill_callables(void)
@@ -124,11 +51,11 @@ redot() {
     # this function definition calls no Zeshy-specific aliases or functions; the
     # the above call to the kill_callables() function has already killed them.
     source_if_found() {
-        [[ "${#}" -eq 1 ]] || die 'expected exactly one filename'
-        local script_name="${1}"
+        [[ ${#} -eq 1 ]] || die 'expected exactly one filename'
+        string script_name="${1}"
         if [[ -f "${script_name}" && -r "${script_name}" ]]; then
             # Do not call the utter_import() function!
-            echo "redot: loading \"${script_name}\"..."
+            print "redot: loading \"${script_name}\"..."
             source "${script_name}"
         fi
     }
@@ -149,8 +76,8 @@ PATH_init() {
     die_unless_no_arguments
 
     # Prior $PATH, if any.
-    local PATH_old=
-    if [[ -n "${ROOTPATH}" ]] && is_superuser
+    string PATH_old=
+    if is_set "${ROOTPATH}" and is_superuser
     then PATH_old="${ROOTPATH}"
     else PATH_old="${PATH}"
     fi
@@ -177,14 +104,14 @@ PATH_init() {
     PATH_append "${HOME}/bin"
 
     # Append Zeshy's "bin/".
-    local zeshy_bin_dir="${ZESHY_HOME}/bin"
+    string zeshy_bin_dir="${ZESHY_HOME}/bin"
     PATH_append "${zeshy_bin_dir}"
 
     # Append each command in Zeshy's "bin/command/" installed on this machine,
     # matching all subdirectories of that directory via the "(/)" modifier.
     for zeshy_command_bin_dir in "${zeshy_bin_dir}/command"/*(/); do
         command_name=$(basename "${zeshy_command_bin_dir}")
-        is_installed "${command_name}" && PATH_append "${zeshy_command_bin_dir}"
+        is_installed "${command_name}" and PATH_append "${zeshy_command_bin_dir}"
     done
 
     # Export!
@@ -197,11 +124,11 @@ PATH_init() {
 # exists, is readable, and has not already been appended.
 PATH_append() {
     die_unless_one_argument 'expected exactly one argument'
-    local dirname="${1}"
+    string dirname="${1}"
 
-    if [[ -d "${dirname}" && -r "${dirname}" &&
-        ! "${PATH}" =~ "(^|:)${dirname}($|:)" ]]; then
-        if [[ -n "${PATH}" ]]
+    if is -d "${dirname}" && -r "${dirname}" &&
+        ! "${PATH}" =~ "(^|:)${dirname}($|:)" si; then
+        if is_set "${PATH}"
         then PATH+=":${dirname}"
         else PATH="${dirname}"
         fi
@@ -244,10 +171,10 @@ parse_arguments="zparseopts -D -E -A ARGS -- h -help"
 check_parsed_arguments() {
     # If the immediately prior command failed, assume that was a call to the
     # parse_arguments() function and enable a boolean noting this fact.
-    is_previous_command_succeeded && local is_parse_arguments_failed=1
+    is_ok && bool is_parse_arguments_failed=1
     
     die_unless_one_argument 'expected exactly one help string'
-    local help_message="${1}"
+    string help_message="${1}"
     
     # If the caller passed the "-h" or "--help" options, die without error.
     if (( "${+ARGS[-h]}" + "${+ARGS[--help]}" )); then
@@ -258,6 +185,23 @@ check_parsed_arguments() {
         print "${help_message}"
         exit_with_failure
     fi
+}
+
+# ....................{ SHUTDOWN                           }....................
+# int exit_with_success(void)
+# 
+# Exit the current process with a successful return code.
+exit_with_success() {
+    die_unless_no_arguments
+    exit ${ZESHY_SUCCESS_CODE}
+}
+
+# int exit_with_failure(void)
+# 
+# Exit the current process with a failure return code.
+exit_with_failure() {
+    die_unless_no_arguments
+    exit ${ZESHY_FAILURE_CODE}
 }
 
 #FIXME: Obsolete.
@@ -357,7 +301,7 @@ check_parsed_arguments() {
 # The information below applies to everything in this distribution,
 # except where noted.
 #              
-# Copyright 2007-2011 by Cecil Curry.
+# Copyright 2007-2012 by Cecil Curry.
 #   
 #   http://www.raiazome.com
 # 
