Significantly improved Zeshy Shell.
Specifically, added:
* Reflection facilities for testing callable and variable types.
* Array-handling facilities for returning arrays from functions.

diff --git a/src/zeshy/shell b/src/zeshy/shell
--- a/src/zeshy/shell
+++ b/src/zeshy/shell
@@ -11,29 +11,79 @@
 # * Reflection functionality for dynamically inspecting functions and aliases
 #   like first-class constructs.
 
-# ....................{ TESTS                              }....................
-# bool is_alias(char *alias)
+# ....................{ REFLECTION ~ tests                 }....................
+# bool is_builtin(char *builtin_name)
 #
-# Return true if there exists an alias with the passed alias name.
-is_alias() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one name"
-    [[ $(whence -w "${1}") =~ ': alias$' ]]
-}
-
-# bool is_builtin(char *builtin)
-#
-# Return true if there exists a builtin with the passed alias name.
+# Return true if there exists a built-in (i.e., a C function accessible to all
+# Zsh shells and scripts) with the passed name.
 is_builtin() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one name"
+    die_unless_one_argument 'expected exactly one name'
     [[ $(whence -w "${1}") =~ ': builtin$' ]]
 }
 
-# bool is_function(char *function)
+# bool is_alias(char *alias_name)
 #
-# Return true if there exists a function with the passed function name.
+# Return true if there exists a Zsh alias with the passed name.
+is_alias() {
+    die_unless_one_argument 'expected exactly one name'
+    [[ $(whence -w "${1}") =~ ': alias$' ]]
+}
+
+# bool is_function(char *function_name)
+#
+# Return true if there exists a Zsh function with the passed name.
 is_function() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one name"
+    die_unless_one_argument 'expected exactly one name'
     [[ $(whence -w "${1}") =~ ': function$' ]]
+}
+
+# ....................{ REFLECTION ~ tests ~ variable      }....................
+# bool is_variable(char *variable_name)
+#
+# Return true if there exists a Zsh variable with the passed name.
+is_variable() {
+    die_unless_one_argument 'expected exactly one name'
+    is "${(tP)1}"  # see get_type() for details
+}
+
+# bool is_array(char *array_name)
+#
+# Return true if the Zsh variable with the passed name is an array.
+is_array() {
+    die_unless_one_argument 'expected exactly one array name'
+    
+    # Global arrays have type "array". Local arrays have type "array-local".
+    # Consequently, we match for both.
+    [[ $(get_type "${1}") == array* ]]
+}
+
+# ....................{ REFLECTION ~ types                 }....................
+# char *get_type(void *name)
+#
+# Return the type of the object (e.g., function, variable) corresponding to the
+# passed variable name or "not-found" if there exists no such object.
+get_type() {
+    die_unless_one_argument 'expected exactly one name'
+    local name="${1}"
+    
+    # First, test if there exists a corresponding variable.
+    local type="${(tP)name}"
+
+    # Failing that, test if there exists a corresponding callable. Failing that,
+    # use the string returned by the whence() built-in: "none".
+    if is_not "${type}"; then
+        type="$(whence -w "${name}")"
+        type="${type##*: }"
+    fi
+    
+    echo "${type}"
+}
+
+# void die_unless_is_array(char *array_name)
+#
+# Die unless the variable corresponding to the passed name is an array.
+die_unless_is_array() {
+    is_array "${1}" or die "\"${1}\" not an array"
 }
 
 # ....................{ DEATH                              }....................
@@ -95,6 +145,8 @@ redot() {
 #
 # Set the $PATH for the current user.
 PATH_init() {
+    die_unless_no_arguments
+
     # Prior $PATH, if any.
     local PATH_old=
     if [[ -n "${ROOTPATH}" ]] && is_superuser
@@ -143,7 +195,7 @@ PATH_init() {
 # Append the passed dirname onto the $PATH, if the corresponding directory
 # exists, is readable, and has not already been appended.
 PATH_append() {
-    [[ "${#}" -eq 1 ]] || die 'expected exactly one argument'
+    die_unless_one_argument 'expected exactly one argument'
     local dirname="${1}"
 
     if [[ -d "${dirname}" && -r "${dirname}" &&
@@ -193,7 +245,7 @@ check_parsed_arguments() {
     # parse_arguments() function and enable a boolean noting this fact.
     is_previous_command_succeeded && local is_parse_arguments_failed=1
     
-    [[ ${#} -eq 1 ]] || die 'expected exactly one help string'
+    die_unless_one_argument 'expected exactly one help string'
     local help_message="${1}"
     
     # If the caller passed the "-h" or "--help" options, die without error.
@@ -207,33 +259,149 @@ check_parsed_arguments() {
     fi
 }
 
-# ....................{ PASS-BY-VALUE                      }....................
-#FIXME: Document!
-return_value() {
-    [[ ${#} -ge 1 ]] || die 'expected at least one value'
-    echo "echo \"${@}\"; return ${ZESHY_SUCCESS_CODE}"
-}
-
+# ....................{ PASS-BY-VALUE ~ array              }....................
+# char *return_array(char *array_name = 'array')
+#
+# Reduces the array corresponding to the passed array name to a scalar string.
+# Functions may safely return this string to callers, who may losslessly expand
+# the string back into its original array by calling either expand_Array() or
+# expand_array(): e.g.,
+#
+#   # A function returning a stringified array.
+#   a_ray_of_unlit_hope() {
+#     local -A array=( 'key 1' 'value 1' 'key 2' 'value 2' )
+#     echo "original array: ${array[@]}"
+#     return_array array
+#   }
+#
+#   # A convenient function expanding this stringified array back into an array.
+#   a_day_of_sunlit_sadness() {
+#     local Array="$(a_ray_of_unlit_hope)"'
+#     expand_Array
+#     echo "returned array: ${array[@]}"  # identical to the original array!
+#   }
+#
+#   # An equivalent function expanding the stringified array back into an array.
+#   a_day_of_sunlit_sadness() {
+#     local -A array
+#     eval 'expand_array array "$(a_ray_of_unlit_hope)"'
+#     echo "returned array: ${array[@]}"  # identical to the original array!
+#   }
 return_array() {
-    #FIXME: Test to make sure the passed array name actually is. How?
-    [[ ${#} -ge 1 ]] || die 'expected exactly one array name'
-    local array_name="${1}"
-    echo "echo \"${${(@qqkv)array_name}[@]}\"; return ${ZESHY_SUCCESS_CODE}"
+    die_unless_at_most_one_argument 'expected at most one array name'
+
+    # Let's dismantle this, one to two parameter expansion flags at a time:
+    # * '1:-array' expands to the passed array name or 'array' if no such name
+    #   was passed.
+    # * 'P' transitively expands this name to the actual name of the desired
+    #   associative array in the caller's scope.
+    # * '@' interprets this expansion as an array rather than scalar.
+    # * 'kv' reduces this array to a scalar string concatenating all array
+    #   element names and values, delimited by whitespace.
+    # * 'qq' protectively embeds all reserved shell characters in such names
+    #   and values in single quotes.
+    echo "${(qqkv@P)1:-array}"
 }
 
-obtain_array() {
-    #FIXME: Test to make sure the passed array name actually is. How?
-    [[ ${#} -ge 2 ]] || die 'expected one array name and one runnable command'
-    local array_name="${1}"; shift
-    local command="${@}"
+# char *expand_Array()
+#
+# Expands the scalar string "Array" into the array "array". This alias is a
+# convenience simplifying the more generalized expand_array() function. See the
+# reduce_array() function for an example.
+alias expand_Array='
+    is "${Array}" or die "No \"Array\" defined";
+    eval "$(expand_array array ${Array})"'
 
-    #FIXME: Die if return code is failure?
-    echo "local _zeshy_obtained_array_as_scalar=\$(${command}); "
-    echo "${array_name}=( "${(Q@)${(z)_zeshy_obtained_array_as_scalar}}" ); "
-    echo "unset _zeshy_obtained_array_as_scalar"
+# char *expand_array(char *array_name, char *string_array)
+#
+# Expands the second parameter, a scalar string produced by return_array(), into
+# the array corresponding to the passed array name. (Unlike return_array(), this
+# function must by dynamically evaluated by the eval() built-in. See the
+# expand_Array() alias for a simple alternative.)
+expand_array() {
+    die_unless_at_least_two_arguments 'expected one array name and one stringified array'
+    local array_name="${1}"; shift
+
+    # Let's dismantle this, one parameter expansion flag at a time:
+    # * '@' expands to all remaining passed parameters: the stringified array.
+    # * 'z' splits the stringified array into a numeric array of words,
+    #   effectively undoing the prior 'kv' flag.
+    echo "${array_name}=( ${(z)@} )"
 }
 
 #FIXME: Obsolete.
+#   if [[ "${type}" == none ]]; then
+#       echo "not-found"
+#   else
+#   is "${variable_type}" or die "\"${1}\" not a variable"
+#   if not is_array array; then local -A array; fi;
+#   local array_name="${1:-array}"
+#   die_unless_is_array "${array_name}"
+#   echo "${(qqkv@P)array_name}"
+
+#FIXME: Rename.
+#alias Return_array='eval return_array'
+#alias Obtain_array='eval obtain_array'
+#alias Return_array='eval "$(return_array array)"'
+#alias expand_stray_to_array='eval "$(obtain_array array ${stray})"'
+#alias Obtain_array_from_command='eval "$(obtain_array array $(command))"'
+
+    #FIXME: Die if return code is failure?
+#   local command="${@}"
+#   echo "local _zeshy_obtained_array_as_scalar=\$(${command}); "
+#   echo "${array_name}=( "${(Q@)${(z)_zeshy_obtained_array_as_scalar}}" ); "
+#   echo "unset _zeshy_obtained_array_as_scalar"
+
+#   echo "${${(qqkv@P)array_name}[@]}"
+#   echo "${${(@qqkvP)array_name}[@]}"
+#   "echo \"${${(@qqkvP)array_name}[@]}\""
+#   echo "echo \"${${(@qqkvP)array_name}[@]}\""   # ; return_success"
+
+#   echo "string_array=${@}"
+#   echo "${array_name}="'"'"${(z)@}"'"'
+#   echo "${array_name}=( ${(Q)${(z)@}} )"
+#   echo "${array_name}=( \"${(Q@)${(z)string_array}}\" )"
+#   echo "${array_name}=( ${(Q@)${(z)string_array}} )"
+#   echo "${array_name}=( "${(Q@)${(z)@}}" )"
+
+#obtain_array_from_command() {
+#    #FIXME: Test to make sure the passed array name actually is. How?
+#    die_unless_at_least_two_arguments 'expected one array name and one runnable command'
+#    local array_name="${1}"; shift
+#    local command="${@}"
+#
+#    echo "${array_name}=( "${(Q@)${(z)_zeshy_obtained_array_as_scalar}}" ); "
+#
+#    #FIXME: Die if return code is failure?
+#   echo "local _zeshy_obtained_array_as_scalar=\$(${command}); "
+#   echo "${array_name}=( "${(Q@)${(z)_zeshy_obtained_array_as_scalar}}" ); "
+#   echo "unset _zeshy_obtained_array_as_scalar"
+#
+#    # Let's dismantle this, one to two parameter expansion flags at a time:
+#    # * 'z' splits the passed string into a numeric array of words.
+#   echo "${array_name}=( ${(z)string_array} )"
+#}
+
+#oa() {
+#    #FIXME: Test to make sure the passed array name actually is. How?
+#    die_unless_at_least_two_arguments 'expected one array name and one stringified array'
+#    local string_array="${@}"
+#
+#    # Let's dismantle this, one to two parameter expansion flags at a time:
+#    # * 'z' splits the passed string into a numeric array of words.
+#    echo "${array_name}=( ${(z)string_array} )"
+#}
+
+    # * '@' splits the array of such words into (still quote-protected!) words.
+    # * 'Q' strips the single quotes protectively added by the prior 'qq' flag.
+    # * The second '@' refers to the passed 
+# ....................{ PASS-BY-VALUE                      }....................
+#FIXME: Document!
+#return_value() {
+#   [[ ${#} -ge 1 ]] || die 'expected at least one value'
+#   echo "echo \"${@}\"; return ${ZESHY_SUCCESS_CODE}"
+#}
+
 # void PATH_append_if_root(char *pathname)
 #
 # Add the passed pathname to this user's "$PATH", if the above conditions hold
