Moved Zeshy Inspect code into Zeshy Shell.
Also, the usual retinue of bug fixes.

diff --git a/src/zeshy/shell b/src/zeshy/shell
--- a/src/zeshy/shell
+++ b/src/zeshy/shell
@@ -4,16 +4,70 @@
 #
 # --------------------( SYNOPSIS                           )--------------------
 # Zeshy Shell. This Zeshy component implements shell-handling functionality.
+# This includes:
+#
+# * Reflection functionality for dynamically inspecting functions and aliases as
+#   "first-class constructs."
 
 # --------------------( ALIASES                            )--------------------
 # Mimes.
 #FIXME: Still desirable?
-alias zsh_mime_load="zsh-mime-setup -f"
-alias zsh_mime_edit="${EDITOR} /etc/mailcap; zsh-mime-load"
+#alias zsh_mime_load="zsh-mime-setup -f"
+#alias zsh_mime_edit="${EDITOR} /etc/mailcap; zsh-mime-load"
 
-# ....................{ CALLABLES                          }....................
-# void kill_callables(void)
+# ....................{ TESTS                              }....................
+# bool is_alias(char *alias)
 #
+# Return true if there exists an alias with the passed alias name.
+is_alias() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one name"
+    [[ $(whence -w "${1}") =~ ': alias$' ]]
+}
+
+# bool is_builtin(char *builtin)
+#
+# Return true if there exists a builtin with the passed alias name.
+is_builtin() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one name"
+    [[ $(whence -w "${1}") =~ ': builtin$' ]]
+}
+
+# bool is_function(char *function)
+#
+# Return true if there exists a function with the passed function name.
+is_function() {
+    [[ "${#}" -eq 1 ]] || die "expected exactly one name"
+    [[ $(whence -w "${1}") =~ ': function$' ]]
+}
+
+# ....................{ PASS-BY-VALUE                      }....................
+#FIXME: Document!
+return_value() {
+    [[ "${#}" -ge 1 ]] || die "expected at least one value"
+    echo "echo \"${@}\"; return ${ZESHY_SUCCESS_CODE}"
+}
+
+return_array() {
+    #FIXME: Test to make sure the passed array name actually is. How?
+    [[ "${#}" -ge 1 ]] || die "expected exactly one array name"
+    local array_name="${1}"
+    echo "echo \"${${(@qqkv)array_name}[@]}\"; return ${ZESHY_SUCCESS_CODE}"
+}
+
+obtain_array() {
+    #FIXME: Test to make sure the passed array name actually is. How?
+    [[ "${#}" -ge 2 ]] || die "expected one array name and one runnable command"
+    local array_name="${1}"; shift
+    local command="${@}"
+
+    #FIXME: Die if return code is failure?
+    echo "local _zeshy_obtained_array_as_scalar=\$(${command}); "
+    echo "${array_name}=( "${(Q@)${(z)_zeshy_obtained_array_as_scalar}}" ); "
+    echo "unset _zeshy_obtained_array_as_scalar"
+}
+
+# ....................{ UNSETTERS                          }....................
+# void kill_callables(void)
 #
 # Destroy all existing aliases and functions. This is, of course, fairly
 # destructive but does guard against desynchronization issues resulting from
@@ -23,7 +77,7 @@ kill_callables() {
     unfunction -m '*'
 }
 
-# --------------------( SOURCES                            )--------------------
+# ....................{ SOURCES                            }....................
 # void redot(void)
 #
 # Resource all Zsh startup scripts in the same order Zsh sources these scripts
