Documentation subsystem refactored.
Such subsystem has been generalized to associate operables (i.e., aliases,
globals, and functions) with arbitrary scalar metadata rather than merely only
prototypes and AsciiDoc -- which should prove moderately useful in future code.

diff --git a/src/00-start/00-declare/15-set/prototype b/src/00-start/00-declare/15-set/prototype
--- a/src/00-start/00-declare/15-set/prototype
+++ b/src/00-start/00-declare/15-set/prototype
@@ -13,7 +13,7 @@
 #     :string alias_prototype, ^:string string_name)
 function :alias_prototype.set_name() {
     (( # == 2 )) || :die 'Expected one alias prototype and one string name.'
-    ::runnable_prototype.set_name_of_label "${@}" 'Alias'
+    ::callable_prototype.set_name_of_label "${@}" 'Alias'
 }
 
 #FIXME: Document me.
@@ -26,26 +26,17 @@ function :alias_prototype.set_name() {
 function :alias_prototype.set_attrs,names,args() {
     (( # == 4 )) || :die\
         'Expected one alias prototype, one map name, one list name, and one string name.'
-    ::runnable_prototype.set_attrs,names,args_of_label "${@}" 'Alias'
+    ::callable_prototype.set_attrs,names,args_of_label "${@}" 'Alias'
 }
 
 # ....................{ SETTERS ~ func                     }....................
-#FIXME: Document me.
-
-# :void :func.set_prototype(
-#     :string+func func_name, ^:string string_name)
-function :func.set_prototype() {
-    (( # == 2 )) || :die 'Expected one function name and one string name.'
-    ::operable.set_prototype_of_type "${@}" 'func'
-}
-
 #FIXME: Document me.
 
 # :void :func_prototype.set_name(
 #     :string func_prototype, ^:string string_name)
 function :func.set_prototype_name() {
     (( # == 2 )) || :die 'Expected one function prototype and one string name.'
-    ::runnable_prototype.set_name_of_label "${@}" 'Function'
+    ::callable_prototype.set_name_of_label "${@}" 'Function'
 }
 
 #FIXME: Document me.
@@ -58,21 +49,20 @@ function :func.set_prototype_name() {
 function :func_prototype.set_attrs,names,args() {
     (( # == 4 )) || :die\
         'Expected one function prototype, one map name, one list name, and one string name.'
-    ::runnable_prototype.set_attrs,names,args_of_label "${@}" 'Function'
+    ::callable_prototype.set_attrs,names,args_of_label "${@}" 'Function'
 }
 
 # ....................{ SETTERS ~ global                   }....................
-#FIXME: Refactor to :global_prototype.set_names().
 #FIXME: Document me.
 
-# void :set_list_to_global_prototype_names(
-#     string list_name, string global_prototype)
-function :set_list_to_global_prototype_names() {
+# :void :global_prototype.set_names(
+#     :string global_prototype, ^:list list_name)
+function :global_prototype.set_names() {
     # Validate sanity.
-    (( # == 2 )) || :die 'Expected one list name and one global prototype.'
+    (( # == 2 )) || :die 'Expected one global prototype and one list name.'
     local\
-        global_names_list_name__sltgpn="${1}"\
-        global_prototype__sltgpn="${2}"\
+        global_prototype__sltgpn="${1}"\
+        global_names_name__sltgpn="${2}"\
         global_names_and_optional_value__sltgpn\
         placeholder__sltgpn
 
@@ -90,7 +80,7 @@ function :set_list_to_global_prototype_names() {
     # parse such global value despite the caller not requesting such value --
     # which we then promptly discard.
     :set_list,string,bool_to_global_names,value,is_value\
-        "${global_names_list_name__sltgpn}"\
+        "${global_names_name__sltgpn}"\
         placeholder__sltgpn\
         placeholder__sltgpn\
         "${global_names_and_optional_value__sltgpn}"
@@ -160,61 +150,35 @@ function :set_list,string,bool_to_global_names,value,is_value() {
     }
 }
 
-# ....................{ SETTERS ~ operable                 }....................
-#FIXME: Implement ::set_string_to_operable_type_asciidoc() along similar lines.
-#FIXME: Document me.
-
-# :void ::operable.set_prototype_of_type(
-#     :string/func operable_name,
+# ....................{ SETTERS ~ callable                 }....................
+# :void ::callable_prototype.set_name_of_label(
+#     :string callable_prototype,
 #     ^:string string_name,
-#     :string operable_type)
-function ::operable.set_prototype_of_type() {
+#     :string callable_label)
+function ::callable_prototype.set_name_of_label() {
     # Validate sanity.
     (( # == 3 )) || :die\
-        'Expected one operable name, one string name, and one operable type.'
-    local\
-        operable_name__sstrtp="${1}"\
-        string_name__sstrtp="${2}"\
-        operable_type__sstrtp="${3}"\
-        prototype_setter_name__sstrtp
-
-    # Name of the function setting such string to such operable's prototype.
-    # See ::document_operable_with_type,prototype,asciidoc() for such
-    # function's definition.
-    prototype_setter_name__sstrtp="::set_string_to_${operable_type__sstrtp}_prototype:${operable_name__sstrtp}"
-    :func.die_unless "${prototype_setter_name__sstrtp}"
-    "${prototype_setter_name__sstrtp}" "${string_name__sstrtp}"
-}
-
-# ....................{ SETTERS ~ runnable                 }....................
-# :void ::runnable_prototype.set_name_of_label(
-#     :string runnable_prototype,
-#     ^:string string_name,
-#     :string runnable_label)
-function ::runnable_prototype.set_name_of_label() {
-    # Validate sanity.
-    (( # == 3 )) || :die\
-        'Expected one runnable prototype, one string name, and one runnable label.'
+        'Expected one callable prototype, one string name, and one callable label.'
     local\
         prototype__sstrpn="${1}"\
         string_name__sstrpn="${2}"\
-        runnable_label__sstrpn="${3}"
+        label__sstrpn="${3}"
     [[ -n ${prototype__sstrpn} ]] || :die\
-        ${runnable_label__sstrpn}' prototype empty.'
+        ${label__sstrpn}' prototype empty.'
 
     # If such prototype is syntactically invalid, throw an exception.
     [[ ${prototype__sstrpn} =~\
-        ${ZESHY_PROTOTYPE_RUNNABLE_NAME_PCRE} ]] || :die\
-        ${runnable_label__sstrpn}' prototype'$(::parcel.get_preposition)' invalid or declares two or more '${(L)runnable_label__sstrpn}' names:'${prototype__sstrpn}
+       ${ZESHY_PROTOTYPE_RUNNABLE_NAME_PCRE} ]] || :die\
+        ${label__sstrpn}' prototype'$(::parcel.get_preposition)' invalid or declares two or more '${(L)label__sstrpn}' names:'${prototype__sstrpn}
 
     # If such name was *NOT* captured into ${match[1]}, throw an exception.
     (( ${#match} )) || :die\
-        ${runnable_label__sstrpn}' name unparsable from prototype:'${prototype__sstrpn}
+        ${label__sstrpn}' name unparsable from prototype:'${prototype__sstrpn}
 
     # If such name was captured but is empty, throw an exception. (While this
     # *SHOULD* be the case, guaranteeing this guards against regressions.)
     [[ -n ${match[1]} ]] || :die\
-        ${runnable_label__sstrpn}' name empty in prototype:'${prototype__sstrpn}
+        ${label__sstrpn}' name empty in prototype:'${prototype__sstrpn}
 
     # Set such string to such name.
     :string.set "${string_name__sstrpn}" "${match[1]}"
@@ -222,21 +186,21 @@ function ::runnable_prototype.set_name_of_label() {
 
 #FIXME: Document me.
 
-# :void ::runnable_prototype.set_names_of_label(
-#     :string runnable_prototype,
+# :void ::callable_prototype.set_names_of_label(
+#     :string callable_prototype,
 #     ^:list names_name,
-#     :string runnable_label)
-function ::runnable_prototype.set_names_of_label() {
+#     :string callable_label)
+function ::callable_prototype.set_names_of_label() {
     # Validate sanity.
     (( # == 3 )) || :die\
-        'Expected one runnable prototype, one list name, and one runnable label.'
+        'Expected one callable prototype, one list name, and one callable label.'
     local placeholder_args__sltrpn
     local -A placeholder_attrs__sltrpn
 
-    # Parse such runnable names from such prototype. To centralize logic, also
-    # parse such runnable attributes despite the caller not requesting such
+    # Parse such callable names from such prototype. To centralize logic, also
+    # parse such callable attributes despite the caller not requesting such
     # attributes -- which we then promptly discard.
-    ::runnable_prototype.set_attrs,names,args_of_label\
+    ::callable_prototype.set_attrs,names,args_of_label\
         "${1}"\
         placeholder_attrs__sltrpn\
         "${2}"\
@@ -244,6 +208,8 @@ function ::runnable_prototype.set_names_of_label() {
         "${3}"
 }
 
+#FIXME: Optimize such function, thus optimizing ::func_.start(). This is quite
+#crucial. See such function for specific details on what and how to optimize.
 #FIXME: Document me. In particular, note why this function parses such
 #arguments into a string variable rather than a nonscalar variable (namely,
 #because arguments are considerably more complex than either attributes or
@@ -251,36 +217,36 @@ function ::runnable_prototype.set_names_of_label() {
 #which zsh fails to support). Hence, the caller is responsible for parsing such
 #arguments but *NOT* attributes or names.
 
-# :void ::runnable_prototype.set_attrs,names,args_of_label(
-#     :string runnable_prototype,
+# :void ::callable_prototype.set_attrs,names,args_of_label(
+#     :string callable_prototype,
 #     ^:map attrs_name,
 #     ^:list names_name,
 #     ^:string args_name,
-#     :string runnable_label)
-function ::runnable_prototype.set_attrs,names,args_of_label() {
+#     :string callable_label)
+function ::callable_prototype.set_attrs,names,args_of_label() {
     # Validate sanity.
     (( # == 5 )) || :die\
-        'Expected one runnable prototype, one map name, one list name, one string name, and one runnable type.'
+        'Expected one callable prototype, one map name, one list name, one string name, and one callable type.'
     local\
         prototype__smltrpan="${1}"\
         attrs_name__smltrpan="${2}"\
         names_name___smltrpan="${3}"\
         args_name___smltrpan="${4}"\
-        runnable_label__smltrpan="${5}"
+        label__smltrpan="${5}"
     local -a prototype_matches__smltrpan
-    [[ -n "${prototype__smltrpan}" ]] || :die\
-        ${runnable_label__smltrpan}' prototype empty.'
+    [[ -n ${prototype__smltrpan} ]] || :die\
+        ${label__smltrpan}' prototype empty.'
 
     # If such prototype is syntactically invalid, throw an exception.
     [[ ${prototype__smltrpan} =~\
        ${ZESHY_PROTOTYPE_RUNNABLE_ATTRS_NAMES_ARGS_PCRE} ]] || :die\
-        ${runnable_label__smltrpan}' prototype'$(::parcel.get_preposition)' invalid:'$'\n\n'${prototype__smltrpan}
+        ${label__smltrpan}' prototype'$(::parcel.get_preposition)' invalid:'$'\n\n'${prototype__smltrpan}
 
-    # If such match failed to capture either such runnable's attributes or
+    # If such match failed to capture either such callable's attributes or
     # names, throw an exception.
     # print -r -- "matches: ${match[*]} (${#match})"
     (( ${#match} >= 2 )) || :die\
-        ${runnable_label__smltrpan}' attributes, names, and/or arguments unparsable from prototype:'$'\n\n'${prototype__smltrpan}
+        ${label__smltrpan}' attributes, names, and/or arguments unparsable from prototype:'$'\n\n'${prototype__smltrpan}
 
     # Preserve such matches *BEFORE* attempting attribute matching, which
     # unavoidably overwrites list global ${match}.
@@ -291,14 +257,13 @@ function ::runnable_prototype.set_attrs,names,args_of_label() {
     # and optional suffixing values into such map. Since single- and
     # double-quoted values may contain commas, such attributes must be
     # iteratively matched with a PCRE rather than split on commas.
-    if [[ -n "${prototype_matches__smltrpan[1]}" ]] {
-        #FIXME: Arguably, we should just define :clear_map() here.
+    if [[ -n ${prototype_matches__smltrpan[1]} ]] {
         # Validate sanity.
         local attrs_key__smltrpan
         :var.die_unless_type_map "${attrs_name__smltrpan}"
 
         # Clear such map. See :clear_map() for further details.
-        set -A "${attrs_name__smltrpan}"
+        set -A ${attrs_name__smltrpan}
 
         # Compile such PCRE. For efficiency, avoid optionally optimizing such
         # PCRE by calling pcre_study(). (Ad-hoc profiling suggests such
@@ -324,15 +289,14 @@ function ::runnable_prototype.set_attrs,names,args_of_label() {
     }
 
     # If such prototype only declares one name, set such list to such name.
-    if [[ -n "${prototype_matches__smltrpan[2]}" ]] {
+    if [[ -n ${prototype_matches__smltrpan[2]} ]] {
         :list.set_to_string\
             "${names_name___smltrpan}"\
             "${prototype_matches__smltrpan[2]}"
     # Else, such prototype declares multiple comma-delimited names. Since
-    # single- and double-quoted runnable names may contain commas, such names
+    # single- and double-quoted callable names may contain commas, such names
     # must be iteratively matched with a PCRE rather than split on commas.
     } else {
-        #FIXME: Arguably, we should just define :clear_list() here.
         # Validate sanity.
         local names_item__smltrpan
         integer names_index__smltrpan=0
@@ -340,10 +304,10 @@ function ::runnable_prototype.set_attrs,names,args_of_label() {
 
         # If such match failed to capture such names, throw an exception.
         (( ${#prototype_matches__smltrpan} >= 3 )) || :die\
-            ${runnable_label__smltrpan}' names unparsable from prototype:'$'\n\n'${prototype__smltrpan}
+            ${label__smltrpan}' names unparsable from prototype:'$'\n\n'${prototype__smltrpan}
 
         # Clear such list. See clear_list() for further details.
-        set -A "${names_name___smltrpan}"
+        set -A ${names_name___smltrpan}
 
         # Compile such PCRE. See above for further details.
         pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_NEXT_PCRE}"
@@ -354,6 +318,13 @@ function ::runnable_prototype.set_attrs,names,args_of_label() {
             pcre_match -b -n ${ZPCRE_OP[(w)2]} --\
                 "${prototype_matches__smltrpan[3]}"
         } {
+            #FIXME: Can we not inline such incrementation below: e.g., as
+            #
+            #    names_item__smltrpan=${names_name___smltrpan}'['$(( names_index__smltrpan++ ))']'
+            #
+            #Naturally, that will probably require initializing
+            #${names_index__smltrpan} to 1 rather than 0, above.
+
             # Index of the current non-existent list item to be appended.
             names_index__smltrpan+=1
 
@@ -366,7 +337,7 @@ function ::runnable_prototype.set_attrs,names,args_of_label() {
     }
 
     # Set such string to such arguments, defaulting to the empty string if
-    # such runnable accepts no arguments (e.g., "()").
+    # such callable accepts no arguments (e.g., "()").
     :string.set\
         "${args_name___smltrpan}" "${prototype_matches__smltrpan[4]-}"
 }
@@ -428,7 +399,7 @@ function run_runnable_with_stdin() {
     #broken. Ugh!
 
     # If standard input is empty, throw an exception. See
-    # :is_stdin_readable_sans_blocking() for further details.
+    # :stdin.is_nonempty() for further details.
     read -t 0 || die 'Standard input empty.'
 
     # Unless such function exists, throw an exception. See is_runnable() for
@@ -444,7 +415,10 @@ function run_runnable_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
-#FUXME: Refactor to ::runnable_prototype.set_name_of_type().
+        #FUXME: Arguably, we should just define :clear_map() here.
+        #FUXME: Arguably, we should just define :clear_list() here.
+
+#FUXME: Refactor to ::callable_prototype.set_name_of_type().
 
 #FUXME: To avoid redefining such logic thrice more (e.g., for the htree alias
 #subtypes), generalize such logic into a new low-level private utility function
@@ -580,13 +554,13 @@ function run_runnable_with_stdin() {
 
 #FUXME: Enormous woops. "read -t 0" is destructive and terrible. To genuinely
 #test this, we'll need to both inline *AND* call
-#:is_stdin_readable_sans_blocking() here. While absurdly annoying, this is
+#:stdin.is_nonempty() here. While absurdly annoying, this is
 #certainly feasible.
 #FUXME: Ugh. We'll need to load the module defining zselect(), then. And, of
 #course, this implies zeshy to then be limited to only OSes defining select().
 #Isn't that most of them, however?
 #FUXME: O.K.; this works. We'll need to define a new parcel @{10-test} and
-#rename this parcel to @{15-set}. Shift :is_stdin_readable_sans_blocking() to
+#rename this parcel to @{15-set}. Shift :stdin.is_nonempty() to
 #@{10-test}; then, refactor the setters below to call such function. We know;
 #this is terrible. But there you are!
 #FUXME: Don't forget to shift the zmodload() call below to @{10-test} too!
@@ -604,7 +578,7 @@ function run_runnable_with_stdin() {
 # #     string list_name, string alias_prototype)
 # function :set_list_to_alias_prototype_names() {
 #     (( # == 2 )) || :die 'Expected one list name and one alias prototype.'
-#     ::runnable_prototype.set_names_of_label "${@}" 'Alias'
+#     ::callable_prototype.set_names_of_label "${@}" 'Alias'
 # }
 
         #FUXME: *WOO*! We may have uncovered an even more efficient means of
@@ -669,7 +643,7 @@ function run_runnable_with_stdin() {
         # eval ${global_names_list_name__slsbtgnviv}'=( ${(s:=:)match[2]} )'
 
     # If standard input is either the empty string *OR* unreadable without
-    # blocking, throw an exception. See :is_stdin_readable_sans_blocking() for
+    # blocking, throw an exception. See :stdin.is_nonempty() for
     # further details.
     #
     # Since there exists no demonstrable reason to prohibit empty
