A rather sizable commit, by the ruddy looks of it.
I am sleepily steeped in the sanguine tides. Significant changes
include... well, I'm sure they're there. (I've certainly penned more
informative commit statements. I'm afraid this will have to do, however.)

diff --git a/src/autoload/always/process b/src/autoload/always/process
--- a/src/autoload/always/process
+++ b/src/autoload/always/process
@@ -10,23 +10,6 @@
 interactive_alias ka='killall'
 interactive_alias ka9='killall -9'
 
-# ....................{ SHUTDOWN                           }....................
-# int exit_with_success(void)
-# 
-# Exit the current process with a successful return code.
-exit_with_success() {
-    die_unless_no_arguments
-    exit ${ZESHY_SUCCESS_CODE}
-}
-
-# int exit_with_failure(void)
-# 
-# Exit the current process with a failure return code.
-exit_with_failure() {
-    die_unless_no_arguments
-    exit ${ZESHY_FAILURE_CODE}
-}
-
 # ....................{ TESTS                              }....................
 # bool is_cronjob(void)
 #
@@ -36,35 +19,35 @@ is_cronjob() {
     is_nonempty "${ZESHY_IS_CRONJOB}"
 }
 
-# bool is_running(char *filename)
+# bool is_running(char *command_name)
 #
 # Return true if some process is running the passed command.
 is_running() {
     die_unless_one_argument 'expected exactly one filename'
-    quietly get_pids_for_running "${@}"
+    quietly get_pids_running "${@}"
 }
 
-# bool is_running_as(char *username, char *filename)
+# bool is_running_as(char *username, char *command_name)
 #
 # Return true if some process is running the passed command under the passed
 # user.
 is_running_as() {
     die_unless_two_arguments 'expected exactly one username and filename'
-    quietly get_pids_for_running_as "${@}"
+    quietly get_pids_running_as "${@}"
 }
 
-# bool is_running_pid(int pid)
+# bool is_pid_running(int pid)
 #
-# Return success a process is running under the passed process ID: e.g.,
+# Return true if some process is running under the passed process ID: e.g.,
 #
-#     # sleep 10s &
-#     # is_running_pid $! and echo "Awaken."  # prints "Awaken."
-is_running_pid() {
+#     >>> sleep 10s &; is_running_pid $! and print "Awaken, Young Master."
+#     Awaken, Young Master.
+is_pid_running() {
     die_unless_one_argument 'expected exactly one process ID'
     quietly kill -0 "${1}"
 }
 
-# ....................{ GETTERS ~ id                       }....................
+# ....................{ GETTERS ~ process IDs              }....................
 # int get_pid(void)
 #
 # Return the PID (i.e., process ID) of the current process.
@@ -74,39 +57,39 @@ get_pid() {
 }
 
 #FIXME: Generalize to not require "pgrep".
-# char *get_pids_for_running(char *filename)
+# char *get_pids_running(char *command_name)
 #
 # Return a newline-delimited string of process IDs for all processes running the
 # passed command. If no such process exists, return the empty string and fail.
-get_pids_for_running() {
-    die_unless_one_argument 'expected exactly one filename'
+get_pids_running() {
+    die_unless_one_argument 'expected exactly one command name'
     die_unless_installed pgrep
 
     string command="${1}"
-    if is_pathname_absolute "${command}"
+    if is_absolute_path "${command}"
     then pgrep -fx "${command}" 2>/dev/null
     else pgrep  -x "${command}" 2>/dev/null
     fi
 }
 
 #FIXME: Generalize to not require "pgrep".
-# char *get_pids_for_running_as(char *username, char *filename)
+# char *get_pids_running_as(char *username, char *command_name)
 #
 # Return a newline-delimited string of process IDs for all processes having the
 # passed command name running under the passed user. If no such process exists,
 # return the empty string and a failure return code.
-get_pids_for_running_as() {
-    die_unless_two_arguments 'expected exactly one username and filename'
+get_pids_running_as() {
+    die_unless_two_arguments 'expected exactly one username and command name'
     die_unless_installed pgrep
 
     string username="${1}" command="${2}"
-    if is_pathname_absolute "${command}"
+    if is_absolute_path "${command}"
     then pgrep -u "${username}" -fx "${command}" 2>/dev/null
     else pgrep -u "${username}"  -x "${command}" 2>/dev/null
     fi
 }
 
-# ....................{ GETTERS ~ path                     }....................
+# ....................{ GETTERS ~ commands                 }....................
 #FIXME: This probably doesn't work as expected for scripts preceeded by set
 #variables (e.g., "TMP=~/.tmp script.zeshy"). Test; hack; fix!
 # char *get_process_command_name(int pid = PID)
@@ -137,11 +120,10 @@ get_process_command_name() {
     else command_path="${command_name}"
     fi
 
-    # If this command is "su", the absolute path is instead "-su". For sanity,
-    # strip the prefixing hyphen.
+    # If the command path is "-su" (as occurs under "su"), strip the hyphen.
     is "${command_path}" == '-'* si and command_path="${command_path[2,-1]}"
 
-    # Return the basename of this command.
+    # Return the basename of this command path.
 #   print "\ncommand_line_words: ${command_line_words[@]}"
 #   print "command_path: ${command_path}"
     get_basename "${command_path}"
@@ -242,8 +224,8 @@ one_if() {
 # ${PAGER} (e.g., "less", "more").
 page() {
     die_unless_at_least_one_argument 'expected a command'
-    print "page command line: ${*}"
-    print "page second arg: ${2}"
+#   print "page command line: ${*}"
+#   print "page second arg: ${2}"
     run "${(q)@} 2>&1 | '${PAGER:-less}'"
 }
 
@@ -344,7 +326,7 @@ run() {
     # If the passed command has not been overridden by a shell alias or
     # function, run it as a command. Do not call the customary is_installed()
     # function, as that does not test whether or not a command is overridden.
-    if is_pathname_absolute "${command_path}"; then
+    if is_absolute_path "${command_path}"; then
         # If running this command under a different user, do so.
         if is_set_nonempty 'ZESHY_RUN_AS' and
            is "${ZESHY_RUN_AS}" != "${USER}" si; then
@@ -375,6 +357,23 @@ run() {
         print "evaling: ${command[@]}"
         eval "${command[@]}"
     fi
+}
+
+# ....................{ SHUTDOWN                           }....................
+# int exit_with_success(void)
+# 
+# Exit the current process with a successful return code.
+exit_with_success() {
+    die_unless_no_arguments
+    exit ${ZESHY_SUCCESS_CODE}
+}
+
+# int exit_with_failure(void)
+# 
+# Exit the current process with a failure return code.
+exit_with_failure() {
+    die_unless_no_arguments
+    exit ${ZESHY_FAILURE_CODE}
 }
 
 #FIXME: Obsolete.
