Directory tree significantly restructured.
All top-level scripts excluding ={main} now reside under ={!!-seed}, an
ignorable suboverlay (i.e., a subdirectory explicitly ignored by ={compile} for
purposes of digest compilation). All unconditionally compiled top-level
suboverlays have been renamed in favour of "organic" nomenclature (e.g., from
={00-start} to ={00-soil}), as mute protest against the patent sterility
promulgated by most codebases. A nefarious retinue of other changes accompany.

diff --git a/src/if_pathable/ssh/if_pathable/sshfs/sshfs b/src/if_pathable/ssh/if_pathable/sshfs/sshfs
--- a/src/if_pathable/ssh/if_pathable/sshfs/sshfs
+++ b/src/if_pathable/ssh/if_pathable/sshfs/sshfs
@@ -32,7 +32,7 @@ function mount_ssh_host() {
     string\
         LOCAL_PATH="$ZESHY_SSH_HOST_TO_LOCAL_PATH[$SSH_HOST]"\
         REMOTE_PATH="$ZESHY_SSH_HOST_TO_REMOTE_PATH[$SSH_HOST]"
-    [ -n "$LOCAL_PATH" ] || die "\"$SSH_HOST\" not a recognized host!"
+    [ -n "$LOCAL_PATH" ] || :die "\"$SSH_HOST\" not a recognized host!"
 
     is_dir "${LOCAL_PATH}" or {
         print_message "creating \"$LOCAL_PATH\"..."
@@ -47,18 +47,18 @@ function mount_ssh_host() {
         # If the "/etc/init.d/fuse" initscript exists, preferentially run that.
         if [[ -x "/etc/init.d/fuse" ]]; then
             sudo  "/etc/init.d/fuse" restart  ||
-                die "\"fuse\" initscript cannot be started!"
+                :die "\"fuse\" initscript cannot be started!"
         # Otherwise, load the kernel module.
         else
             sudo modprobe --quiet fuse ||
-                die "\"fuse\" kernel module cannot be loaded!"
+                :die "\"fuse\" kernel module cannot be loaded!"
         fi
     }
 
     # Mount the passed SSH hostname.
     print_message "mounting \"$SSH_HOST\" to \"${LOCAL_PATH}\"..."
     sshfs "${SSH_HOST}:${REMOTE_PATH}" "${LOCAL_PATH}" ||
-      die "\"$SSH_HOST\" cannot be mounted to \"${LOCAL_PATH}\"!"
+      :die "\"$SSH_HOST\" cannot be mounted to \"${LOCAL_PATH}\"!"
 }
 
 # void unmount_ssh_host(string hostname)
@@ -69,13 +69,13 @@ function unmount_ssh_host() {
     die_unless_arg 'expected exactly one SSH hostname'
     string SSH_HOST="$1" LOCAL_PATH
     LOCAL_PATH="$ZESHY_SSH_HOST_TO_LOCAL_PATH[$SSH_HOST]"
-    [ -n "$LOCAL_PATH" ] || die "\"$SSH_HOST\" not a recognized host!"
+    [ -n "$LOCAL_PATH" ] || :die "\"$SSH_HOST\" not a recognized host!"
 
     # Unmount the passed SSH hostname only if already mounted.
     if grep "$LOCAL_PATH" /etc/mtab 2>&1 1>/dev/null; then
         print_message "unmounting \"$SSH_HOST\" from \"$LOCAL_PATH\"..."
         sshfs-umount "$LOCAL_PATH" or
-            die "\"$SSH_HOST\" cannot be unmounted from \"$LOCAL_PATH\"!"
+            :die "\"$SSH_HOST\" cannot be unmounted from \"$LOCAL_PATH\"!"
     fi
 }
 
diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -242,8 +242,8 @@ float ZESHY_TIME_START="${EPOCHREALTIME}"
 # at function definition rather than call time and hence guaranteed to exist
 # for all functions defined below.
 
-# [stderr: string] :output_warning(string text1)
-alias :output_warning='{
+# [stderr = :string] :warning.output(:string warning_message)
+alias :warning.output='{
     print -r -- "zeshy: $(< /dev/stdin)" 1>&2
 } <<<'
 
@@ -295,7 +295,7 @@ typeset -g ZESHY_VERSION='0.1.0'
 #
 # Fortunately, the following simpler method presents itself.
 if [[ "${ZSH_VERSION}" == <0-4>.* ]] {
-    :output_warning\
+    :warning.output\
         "zsh ${ZSH_VERSION} detected but zsh 5.0.0 or newer required."
     return 1
 }
@@ -573,7 +573,7 @@ function TRAPZERR() {
 #   print -r -- "TRAPZERR() triggered with ${exit_status}"
 
     #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-    # Synchronize with die().
+    # Synchronize with :die().
     #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
     # If this handler recursively triggered itself, halt such recursion by
@@ -596,8 +596,8 @@ function TRAPZERR() {
         # Print an exception message to standard error.
         {
             print
-            :output_warning 'TRAPZERR() threw exception: '${*}
-            :output_warning 'TRAPZERR() failed with exit status '${exit_status}
+            :warning.output 'TRAPZERR() threw exception: '${*}
+            :warning.output 'TRAPZERR() failed with exit status '${exit_status}
             print 'current call stack:'
 
             # Print an exception stack trace.
@@ -621,13 +621,13 @@ function TRAPZERR() {
     #
     #    if (( ${+functions[::store_exception_status]} )) { ... }
     typeset -f ::store_exception_status &>/dev/null || {
-        :output_warning '::store_exception_status() undefined in TRAPZERR().'
+        :warning.output '::store_exception_status() undefined in TRAPZERR().'
         return ${exit_status}
     }
 
     # If any list variable expanded below is undefined or not a list, fail.
     [[ "${(t)funcstack-}" == 'array-'* ]] || {
-        :output_warning '${funcstack} undefined in TRAPZERR().'
+        :warning.output '${funcstack} undefined in TRAPZERR().'
         return ${exit_status}
     }
 
@@ -673,15 +673,12 @@ function TRAPZERR() {
     return ${exit_status}
 }
 
-#FIXME: Honestly: we *NEVER* call throw_exception() anywhere, so what's the
-#point? Ditch such obfusctation.
-#FIXME: Excise die() as well. When we do, *DON'T* forget to remove "|die" from
-#globs below.
-
+# :void :die(:string... exception_messages?)
+#
 # To comply with existing zsh code, preserve the original exception global
 # rather than declaring a zeshy-specific alternative (e.g.,
 # ${ZESHY_EXCEPTION_MESSAGE}).
-function throw_exception die :die() {
+function :die() {
     # Get the exit status to be associated with such exception from the current
     # runtime environment rather than expecting such status to be explicitly
     # passed. Specifically, get the exit status of the prior command --
@@ -714,13 +711,13 @@ function throw_exception die :die() {
     # If this function is recursively calling itself, halt such recursion by
     # printing such exception without calling additional functionality and
     # immediately returning. See TRAPZERR() for further details.
-    if (( ${funcstack[(I)(:die|die)]-1} != 1 )) &&
-       [[ "${funcsourcetrace[${funcstack[(I)(:die|die)]}]-}" != *':0' ]] {
+    if (( ${funcstack[(I):die]-1} != 1 )) &&
+       [[ "${funcsourcetrace[${funcstack[(I):die]}]-}" != *':0' ]] {
         # Print an exception message to standard error.
         {
             print
-            :output_warning ':die() threw exception: '${*}
-            :output_warning ':die() failed with exit status '${exit_status}
+            :warning.output ':die() threw exception: '${*}
+            :warning.output ':die() failed with exit status '${exit_status}
             print 'current call stack:'
 
             # Print an exception stack trace.
@@ -760,14 +757,14 @@ function throw_exception die :die() {
 
 # string ::store_exception_status(string error_message, int exit_status)
 function ::store_exception_status() {
-    # Validate sanity. Since die() calls this function, avoid calling such
+    # Validate sanity. Since :die() calls this function, avoid calling such
     # function; in the event of an error, simply print a message to standard
     # error and report success. Do *NOT* report failure. Since this function is
-    # called by both die() and TRAPZERR(), reporting failure here could induce
-    # infinite recursion. Instead, allow whichever of die() or TRAPZERR()
+    # called by both :die() and TRAPZERR(), reporting failure here could induce
+    # infinite recursion. Instead, allow whichever of :die() or TRAPZERR()
     # called this function to continue throwing their exception.
     (( # == 2 )) || {
-        :output_warning '::store_exception_status() expected one exception message and one exit status.'
+        :warning.output '::store_exception_status() expected one exception message and one exit status.'
         return 0
     }
     local exception_message="${1}" exit_status="${2}"
@@ -778,15 +775,15 @@ function ::store_exception_status() {
     # If any canonical call stack list is undefined or not a list, fail.
     [[ "${(t)funcstack-}${(t)funcfiletrace-}${(t)funcsourcetrace-}" ==\
         'array-'*'array-'*'array-'* ]] || {
-        :output_warning '${funcstack}, ${funcfiletrace}, and/or ${funcsourcetrace} undefined or not lists for exception: '${EXCEPTION-}
+        :warning.output '${funcstack}, ${funcfiletrace}, and/or ${funcsourcetrace} undefined or not lists for exception: '${EXCEPTION-}
         return 0
     }
 
     # If this function is called directly from the command line, fail. (In this
-    # case, since this function cannot have been called by die(), there's no
+    # case, since this function cannot have been called by :die(), there's no
     # possibility of undesired recursion. Hence, report failure.)
     (( ${#funcstack} >= 2 )) || {
-        :output_warning '::store_exception_status() called directly from command line.'
+        :warning.output '::store_exception_status() called directly from command line.'
         return 1
     }
 
@@ -794,7 +791,7 @@ function ::store_exception_status() {
     # further details.
     { [[ "${exit_status}" == <-> ]] &&
       (( 0 <= exit_status && exit_status <= 255 )) } || {
-        :output_warning '::store_exception_status() exit status "'${exit_status}'" not an integer in [0, 255].'
+        :warning.output '::store_exception_status() exit status "'${exit_status}'" not an integer in [0, 255].'
         return 0
     }
 
@@ -812,7 +809,7 @@ function ::store_exception_status() {
     # exception is still defined to an integer, such stack and status could be
     # incorporated into such message as well. Since retrieving a human-readable
     # runnable name from such stack is nontrivial (e.g., due to necessarily
-    # ignoring runnables matching die(), TRAPZERR(), and so forth), such
+    # ignoring runnables matching :die(), TRAPZERR(), and so forth), such
     # incorporation is nontrivial. It currently isn't worth the effort.
     if (( ${+EXCEPTION} )) {
         exception_message+=$'\n\n''Uncaught exception:'$'\n'${EXCEPTION}
@@ -835,7 +832,7 @@ function ::store_exception_status() {
     ZESHY_EXCEPTION_FUNCSOURCETRACE=( ${funcsourcetrace[2,-1]} )
 
     # If this function was *NOT* called from within a ":try{...}:always{...}:always"
-    # block, the exception that TRAPZERR() or die() subsequently throws will
+    # block, the exception that TRAPZERR() or :die() subsequently throws will
     # induce zsh to silently unwind the call stack for the current shell
     # without printing such exception. To avoid that, print such exception here
     # *BEFORE* throwing such exception.
@@ -843,7 +840,7 @@ function ::store_exception_status() {
     if (( ${ZESHY_TRY_LEVEL[${SHLVL}]-0} <= 0 )) {
         # If such function is undefined, print a nonfatal warning.
         typeset -f ::print_exception_uncaught &>/dev/null || {
-            :output_warning '::print_exception_uncaught() undefined in ::store_exception_status().'
+            :warning.output '::print_exception_uncaught() undefined in ::store_exception_status().'
             return 0
         }
 
@@ -871,11 +868,11 @@ function ::print_exception_if_uncaught() {
     # exception: printing the stack trace!
 
     # Validate sanity.
-    (( # == 0 )) || die 'Expected no arguments.'
+    (( # == 0 )) || :die 'Expected no arguments.'
 
     # If not called from within an "}:always{...}:always" block, throw an
     # exception. See die_unless_in_always() for further details.
-    (( ${TRY_BLOCK_ERROR--1} >= 0 )) || die\
+    (( ${TRY_BLOCK_ERROR--1} >= 0 )) || :die\
         'Not in an "}:always{...}:always" block (or ${TRY_BLOCK_ERROR\} '${TRY_BLOCK_ERROR--1}' not in [0, 255] and hence an invalid exit status).'
 
     # Else if list global ${ZESHY_TRY_LEVEL} is undefined or has no item
@@ -890,9 +887,9 @@ function ::print_exception_if_uncaught() {
 
         # Throw an appropriate exception.
         if (( ${+ZESHY_TRY_LEVEL[${SHLVL}]} )) {
-            die '${ZESHY_TRY_LEVEL['${SHLVL}']} '${ZESHY_TRY_LEVEL[${SHLVL}]}' <= 0 (e.g., due to no preceding ":try{").'
+            :die '${ZESHY_TRY_LEVEL['${SHLVL}']} '${ZESHY_TRY_LEVEL[${SHLVL}]}' <= 0 (e.g., due to no preceding ":try{").'
         } else {
-            die '${ZESHY_TRY_LEVEL['${SHLVL}']} undefined (e.g., due to no preceding ":try").'
+            :die '${ZESHY_TRY_LEVEL['${SHLVL}']} undefined (e.g., due to no preceding ":try").'
         }
     }
 
@@ -914,7 +911,7 @@ function ::print_exception_if_uncaught() {
     if (( ${+EXCEPTION} && ZESHY_TRY_LEVEL[${SHLVL}] == 0 )) {
         # Print such exception and associated metadata.
         typeset -f ::print_exception_uncaught &>/dev/null ||
-            die '::print_exception_uncaught() undefined.'
+            :die '::print_exception_uncaught() undefined.'
         ::print_exception_uncaught
     }
 }
@@ -925,15 +922,15 @@ function ::print_exception_uncaught() {
     # suffixing "} 1>&2" actually suffices. You rock, zsh! (Sometimes.)
     {
         # Validate sanity.
-        (( # == 0 )) || die 'Expected no arguments.'
+        (( # == 0 )) || :die 'Expected no arguments.'
 
         # If ${funcstack} is undefined or not a list, throw an exception.
-        [[ "${(t)funcstack-}" == 'array-'* ]] || die\
-            '${funcstack} undefined for exception: '${EXCEPTION-}
+        [[ "${(t)funcstack-}" == 'array-'* ]] || :die\
+            'List global ${funcstack} undefined for exception: '${EXCEPTION-}
 
         # If called directly from the command line *OR* no exception is
         # currently thrown, throw an exception.
-        (( ${#funcstack} >= 2 && ${+EXCEPTION} )) || die\
+        (( ${#funcstack} >= 2 && ${+EXCEPTION} )) || :die\
             'No exception thrown (i.e., called directly from the command line and/or ${EXCEPTION} undefined).'
 
         # If print_exception() is defined, call such function.
@@ -943,8 +940,8 @@ function ::print_exception_uncaught() {
         # sufficiently early in zeshy startup, print_exception() will *NOT* have
         # been defined yet.
         } else {
-            :output_warning "${EXCEPTION}"
-            :output_warning 'Failed with exit status '${ZESHY_EXCEPTION_STATUS-1}'.'
+            :warning.output "${EXCEPTION}"
+            :warning.output 'Failed with exit status '${ZESHY_EXCEPTION_STATUS-1}'.'
 
             # Print a stack trace. Ideally, such trace would only be
             # conditionally printed when the current user configuration requests
@@ -1205,7 +1202,10 @@ if (( ${#arg_options} )) {
 typeset -g\
     ZESHY_HOME\
     ZESHY_MAIN_SCRIPT="${0}"\
-    ZESHY_DOT_DIR_BASENAME='.zeshy'
+    ZESHY_DOT_DIR\
+    ZESHY_DOT_DIR_BASENAME='.zeshy'\
+    ZESHY_SEED_DIRNAME\
+    ZESHY_OVERLAY_DIR
 
 #FIXME: Subshells are horrible. See "bin/zeshy" for a substantially improved
 #method leveraging list assignments.
@@ -1219,10 +1219,13 @@ typeset -g\
 #     /usr/bin/zeshy(:A)
 #
 # See "bin/zeshy" for related logic.
-[[ -n "${ZESHY_HOME}" ]] || ZESHY_HOME="$(print -- "${ZESHY_MAIN_SCRIPT:h}"(:A))" || {
-    :output_warning 'Main script "'${ZESHY_MAIN_SCRIPT}'" not found.'
+[[ -n "${ZESHY_HOME}" ]] || ZESHY_HOME="$(print -r -- "${ZESHY_MAIN_SCRIPT:h}"(:A))" || {
+    :warning.output 'Main script "'${ZESHY_MAIN_SCRIPT}'" not found.'
     return 1
 }
+
+# Default such directory to "~/.zeshy".
+ZESHY_DOT_DIR=${HOME}'/'${ZESHY_DOT_DIR_BASENAME}
 
 #FIXME: We're no longer satisfied with such nomenclature, particularly as it
 #diverges from internal local variable nomenclature. Rename "_DIR" to
@@ -1231,10 +1234,11 @@ typeset -g\
 
 # While ${ZESHY_OVERLAY_DIR} is currently synonymous with ${ZESHY_HOME}, it's
 # depressingly easy to conceive of contexts in which the two differ.
-typeset -g ZESHY_OVERLAY_DIR="${ZESHY_HOME}"
+ZESHY_OVERLAY_DIR=${ZESHY_HOME}
 
-# Default such directory to "~/.zeshy".
-typeset -g ZESHY_DOT_DIR="${HOME}/${ZESHY_DOT_DIR_BASENAME}"
+#FIXME: Document me.
+# Absolute path of the directory containing all top-level zeshy scripts.
+ZESHY_SEED_DIRNAME=${ZESHY_HOME}'/!!-seed'
 
 #FIXME: Replace "[[ -n "${ZESHY_DOT_DIR}" ]] ||" with a similar alias to
 #is_zeshy_debug_and<>, probably named is_zeshy_dot_dir_or<>. See below!
@@ -1327,6 +1331,38 @@ typeset -g\
 #Ludicrous. (And not ludicrous speed, either. That would be good. This isn't.)
 typeset -g ZESHY_USER_NAMES_FILE="${ZESHY_USER_CACHE_DIR}/names.zsh"
 
+# ....................{ SOURCERS                           }....................
+#FIXME: Shift to @{main}. Then, call such function wherever we currently call
+#builtin source().
+#FIXME: Document me.
+
+# :full ::script_zsh.source_or_unwind_call_stack(:string filename)
+#
+# The source() builtin currently appears to fail to signal TRAPZERR and hence
+# induce exceptions on script failures, possibly due to such builtin reporting
+# exit status of 126 on such failures. Until the underlying issue is resolved,
+# this function implements a reasonably suitable short-term solution.
+function ::script_zsh.source_or_unwind_call_stack() {
+    # Validate sanity.
+    (( # == 1 )) || :die 'Expected one script filename.'
+    local filename="${1}"
+
+    # Such builtin reports failure if such file does not exist but *NOT* if
+    # such file is a directory. Since this function accepts only files, test
+    # whether such file is actually a file *BEFORE* calling such builtin.
+    [[ -f ${filename} ]] || :die\
+        'Script "'${filename}'" not found or not a file.'
+
+    # Source such script. If such script fails, silently unwind the current
+    # call stack rather than verbosely throwing an exception. Why? If such
+    # script fails, a stack trace describing the fatal error or exception
+    # responsible for such failure will have already been printed; in such
+    # case, throwing an exception here would result in another such trace,
+    # obscuring the prior trace describing the real issue. (Less is more.)
+    builtin source -- "${filename}" || :unwind_call_stack
+    # source -- "${filename}"
+}
+
 # ....................{ LOAD                               }....................
 #FIXME: Right. The thing is, "bin/zeshy" should pass option "NO_RCS" to *ANY*
 #zsh interpreter it runs, including the zsh interpreter implicitly run due to
@@ -1377,8 +1413,8 @@ if (( ZESHY_PID_LAST_LOADED_BY == $$ )) {
     # previously loaded for the current shell. But the current conditional
     # implies zeshy was previously loaded for such shell! This contradiction can
     # only mean one thing: throw an exception.
-    typeset -f :is_version_at_least &>/dev/null or
-        die 'zeshy unexpectedly not loaded (i.e., ${ZESHY_PID_LAST_LOADED_BY} is current PID '$$' but :is_version_at_least() undefined).'
+    typeset -f :is_version_at_least &>/dev/null ||
+        :die 'zeshy unexpectedly unloaded (i.e., zeshy last loaded by current process '$$', but zeshy function :is_version_at_least() undefined).'
 # Else, zeshy has not yet been loaded. Do so! Specifically:
 #
 # * If such shell is a login shell, establish sensible login shell settings.
@@ -1397,7 +1433,7 @@ if (( ZESHY_PID_LAST_LOADED_BY == $$ )) {
 } else {
     # If the current shell is a login shell, set login-specific behavior.
     if { [[ -o login ]] } {
-        source -- "${ZESHY_HOME}/login"
+        ::script_zsh.source_or_unwind_call_stack "${ZESHY_SEED_DIRNAME}/login"
     }
 
     #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@@ -1408,7 +1444,7 @@ if (( ZESHY_PID_LAST_LOADED_BY == $$ )) {
     #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     #
     # Autoload zeshy's user digest file, recompiling such file if needed.
-    source -- "${ZESHY_HOME}/digest"
+    ::script_zsh.source_or_unwind_call_stack "${ZESHY_SEED_DIRNAME}/digest"
 
     #FIXME: Sadly, the following appears to no longer work as advertised, as
     #this file is now sourced from a function context by ".zshrc". Since such
@@ -1496,9 +1532,9 @@ if (( ${#arg_options} + ${#arg_shell_commands} + ${#arg_shell_options} )) {
     #   print usage help to standard error and return with non-zero exit status.
     # * Else, print help to standard output and return with zero exit status.
     if (( ${+arg_options[--help]} )) {
-        if [[ "${arg_options[--help]}" == 'failed' ]] {
-            run_redirecting_to_standard_error print_zeshy_help_usage
-            die 'Passed invalid or unknown options.'
+        if [[ ${arg_options[--help]} == 'failed' ]] {
+            print_zeshy_help_usage 1>&2
+            :die 'Passed invalid or unknown options.'
         } else {
             print_zeshy_help_usage
             return 0
@@ -1544,7 +1580,7 @@ if (( ${#arg_options} + ${#arg_shell_commands} + ${#arg_shell_options} )) {
 # first such argument as the path of a zeshy script and pass such script all
 # remaining such arguments. To avoid unfairly budgeting the time spent sourcing
 # such script to zeshy startup, do so *AFTER* printing zeshy's startup time.
-if [[ -n "${*}" ]] {
+if [[ -n ${*} ]] {
 #   :output_line_if_debugging "zeshy: sourcing \"${@}\"..."
 
     #FIXME: The output is still subpar. We *REALLY* just want to slightly tweak
@@ -1559,8 +1595,8 @@ if [[ -n "${*}" ]] {
     # /home/leycec/zsh/zeshy/src/main() failed with exit status 1
     #  "~/tmp/tmp.zeshy" { /home/leycec/zsh/zeshy/src/main: 1398 }
     #   "/home/leycec/zsh/zeshy/src/main" { /usr/local/bin/zeshy: 206 }
-    source -- "${@}" ||
-        die 'Script "'${*}'" failed with exit status '${status}'.'
+    ::script_zsh.source_or_unwind_call_stack "${@}" ||
+        :die 'Script "'${*}'" failed with exit status '${status}'.'
 }
 
 # ....................{ MAIN                               }....................
@@ -1570,8 +1606,13 @@ if [[ -n "${*}" ]] {
 return 0
 
 # --------------------( WASTELANDS                         )--------------------
+#FUXME: Honestly: we *NEVER* call throw_exception() anywhere, so what's the
+#point? Ditch such obfusctation.
+#FUXME: Excise die() as well. When we do, *DON'T* forget to remove "|die" from
+#globs below.
+
         #FUXME: The prevalence of such repeated logic has become fairly
-        #unctuous. Shift alias :output_warning() from
+        #unctuous. Shift alias :warning.output() from
         #@{*-start/*-alias/io/output} here.
 
 # , but running under zsh ${ZSH_VERSION}."
