Corrected numerous egregious regressions.
Corrected the *_arg_nonoption* family of aliases, run_paged(),
the list_path_*_recursively* family of functions, and numerous other
egregious mishaps.

"Into the deep --

Delving,
     we meld insouciant forms
     unformed of deviant ents
Melding,
     the last of
     a scintillating, upstart foment.

Into the breech --

Lamenting,
     we beseech
     the wit of souls herself
Laminating,
     the first of
     mirth-worn, holy hierophantics.

Fireworks in
the unleaven lathe of Heaven."

diff --git a/src/always/io/terminal/pager b/src/always/io/terminal/pager
--- a/src/always/io/terminal/pager
+++ b/src/always/io/terminal/pager
@@ -9,7 +9,6 @@
 # Handle paging ala "more" and "less".
 
 # ....................{ GETTERS                            }....................
-#FIXME: Rename to get_pager_command_path().
 document_function '
 string get_pager_command(void)
 
@@ -40,44 +39,34 @@ function get_pager_command() {
 #  Happily, "yppy" already has appropriate Unicode for the former arrows. In either case, I
 #  prefer the prefixing space on the wrapped line.
 
-#FIXME: Rename to page_string(). Since there's no possibility of a corresponding
-#curse_string_paged(), just truncate us up. This also helps with the absurdly
-#long function name below.
-
 document_function '
-string print_string_paged(string text1, string text2, ...)
+string page_string(string text1, string text2, ...)
 
 If the passed string exceeds the current terminal''s dimensions, print such
 string with the current user''s preferred pager; otherwise, only print such
 string as is (i.e., without paging). Therefore, this function implements an
 intelligent pager.
 '
-function print_string_paged() {
+function page_string() {
     prepend_args_with_standard_input_if_piped
-    print_string_paged_if_exceeds_terminal_dimensions "${@}" or print_string "${*}"
+    page_string_if_overlong "${@}" or print_string "${*}"
 }
 
-#FIXME: Rename to page_string_if_oversized(). Pretty sweet adjective in this
-#case and frankly the best I've come up with.
-
 document_function '
-string print_string_paged_if_exceeds_terminal_dimensions(
+string page_string_if_overlong(
   string text1, string text2, ...)
 
 If the passed string exceeds the current terminal''s dimensions, print such
 string with the current user''s preferred pager; otherwise, return false.
 '
-function print_string_paged_if_exceeds_terminal_dimensions() {
+function page_string_if_overlong() {
     # Validate passed arguments.
     prepend_args_with_standard_input_if_piped
     die_unless_args 'expected at least one string'
     string text="${*}"
 
     # If not called from a terminal, print_string such string without paging.
-    is_standard_output_terminal or {
-        print_string "${@}"
-        return_true
-    }
+    is_standard_output_terminal or return_string "${*}"
 
     # List of print_string lines.
     list lines; set_list_to_string_lines lines "${text}"
@@ -158,43 +147,63 @@ the passed command to standard error prior to paging such output, as needed.
 '
 function run_paged() {
     # If not called from a terminal, run such command without paging.
-    if not is_standard_output_terminal; then
-        run "${@}"
+    if not is_standard_output_terminal
+    then run "${@}"
     # If passed piped input and no arguments, page such input.
-    elif is_args_0 and is_standard_input_piped; then
-        print_string_paged
-    # Otherwise, run the passed command with redirection. Dismantled, this is:
-    #
-    # * "1>&1", preserving standard print_string prior to its subsequent redirection.
-    # * "1>&2", redirecting standard print_string to error. Since command substitution
-    #   only captures the former, this immediately prints all print_string produced by
-    #   running such command.
-    # * "2>&1", redirecting standard error to output. Since command substitution
-    #   only captures the latter, only such redirection captures standard error.
-    #
-    # Avoid the following seemingly efficient and certainly simpler alternative,
-    # which unfortunately discards non-zero exit status from run():
-    #
-    #   run "${@}" 1>&1 1>&2 | print_string_paged_if_exceeds_terminal_dimensions or true
+    elif is_args_0 and is_standard_input_piped
+    then page_string
+    # Otherwise, run the passed command with redirection.
     else
+        # Validate passed arguments.
         die_unless_args 'expected one command'
 #       print_string "run_paged: ${@}..."
-        print_string_paged_if_exceeds_terminal_dimensions\
-            "$(run "${@}" 1>&1 1>&2 2>&1)" | return_command_exit_status
+
+        # Run such command and capture its output. Dismantled, this is:
+        #
+        # * "1>&1", preserving standard output prior to redirection below.
+        # * "1>&2", redirecting standard output to error. Since command
+        #   substitution only captures the former, this immediately prints all
+        #   output produced by running such command.
+        # * "2>&1", redirecting standard error to output. Since command
+        #   substitution only captures the latter, only such redirection
+        #   captures standard error.
+        #
+        # Avoid the following efficient and certainly simpler alternative, which
+        # unfortunately discards non-zero exit status from run():
+        #
+        #   run "${@}" 1>&1 1>&2 | page_string_if_overlong or true
+        string output; output="$(run "${@}" 1>&1 1>&2 2>&1)"
+
+        # Page such output, ignoring a false return value if such output needs
+        # no paging.
+        page_string_if_overlong "${output}" or true
     fi
 }
 
 # --------------------( WASTELANDS                         )--------------------
+#FUXME: Rename to get_pager_command_path().
+# | return_command_exit_status
+#   is_standard_output_terminal or {
+#       print_string "${@}"
+#       return_true
+#   }
+#FUXME: Rename to page_string_if_overlong(). Pretty sweet adjective in this
+#case and frankly the best I've come up with.
+
+#FUXME: Rename to page_string(). Since there's no possibility of a corresponding
+#curse_string_paged(), just truncate us up. This also helps with the absurdly
+#long function name below.
+
     # * "or true", ignoring such function call when returning false, since the
     #   prior "1>&2" redirection already successfully printed such output.
-#       print_string_paged "$(get_standard_input_piped)"
+#       page_string "$(get_standard_input_piped)"
 #   get_and_set_string_global_if_unset_or_empty_to_evaluation
 #   set_string_if_unset_or_empty_to_evaluation\
 #       PAGER '$(get_pathable_path_first less more)'
 #   print_string "${PAGER}"
 
 #function get_string_global_and_set_if_unset_or_empty_to_evaluation() {
-#    die_unless_args_1 'expected one string variable name'
+#    die_unless_arg 'expected one string variable name'
 #    string __variable_name__="${1}"
 #    declare_string_global "${__variable_name__}"
 #    set_string_if_unset_or_empty_to_evaluation\
@@ -202,20 +211,20 @@ function run_paged() {
 #    print_string "${__variable_name__}"
 #}
 
-        #FIXME: Not quite right. Try prefixing or suffixing 2>&1.
-        #FIXME: Woops. This erroneously discards non-zero exit status from
+        #FUXME: Not quite right. Try prefixing or suffixing 2>&1.
+        #FUXME: Woops. This erroneously discards non-zero exit status from
         #run(). We only want to discard non-zero exit status from
         #print_...(). Hmmmm. Frak this. Revert to the prior logic, which
         #actually worked perfectly.
-#       run "${@}" 1>&1 1>&2 | print_string_paged_if_exceeds_terminal_dimensions or
+#       run "${@}" 1>&1 1>&2 | page_string_if_overlong or
 #           true
 #       string output; set_string_to_standard_input_piped output
-#       print_string_paged "${output}"
+#       page_string "${output}"
 #       line_sans_ansi_width="$(get_string_length "$(remove_ansi_color_codes "${line}")")"
 #       text_width=${#$(remove_ansi_color_codes "${line}")}
     # * "2>&1", redirecting standard error to output. Since command substitution
     #   only captures the latter, only such redirection captures standard error.
-#       run "${@}" 1>&1 1>&2 2>&1 | print_string_paged_if_exceeds_terminal_dimensions
+#       run "${@}" 1>&1 1>&2 2>&1 | page_string_if_overlong
 
 #   say 'here!' 
 #   is_standard_input_piped and {
@@ -239,22 +248,22 @@ function run_paged() {
         # print_string to standard error.
 #       if is_args_0; then
 #           set_string_to_standard_input_piped output
-#           print_string_paged "${output}"
+#           page_string "${output}"
         # ...at least one argument, run such arguments as a command and pipe the
         # input piped to this function to such command. See below for details.
 #       else
-            #FIXME: Not quite right. Revise run() to implicitly check for piped
+            #FUXME: Not quite right. Revise run() to implicitly check for piped
             #input and, if available, to close such input after use. That would
             #condense the following two conditional blocks into one.
 #           run_with_piped_input run "${@}" 1>&1 1>&2 2>&1 |
-#               print_string_paged_if_exceeds_terminal_dimensions
+#               page_string_if_overlong
 #           output="$(run_with_piped_input run "${@}" 1>&1 1>&2 2>&1)"
 
             # Per the "CAVEAT" described under Zeshy Pipe, manually ensure
             # is_standard_input_piped() now returns false.
 #           close_standard_input
 #       fi
-    #FIXME: Hmm; the documentation no longer reflects the reality. Fixmeup.
+    #FUXME: Hmm; the documentation no longer reflects the reality. Fixmeup.
     # Otherwise, run the passed command with redirection. Dismantled, this is:
     #
     # * "2>&2", preserving standard error prior to its subsequent redirection.
@@ -267,17 +276,17 @@ function run_paged() {
 #   else
 #       die_unless_args 'expected one command'
 #       print_string "run_paged: ${@}..."
-#       run "${@}" 1>&1 1>&2 2>&1 | print_string_paged_if_exceeds_terminal_dimensions
+#       run "${@}" 1>&1 1>&2 2>&1 | page_string_if_overlong
 #   fi
 #           die_if_args 'expected no command when passed piped input'
 #           output="$(get_standard_input_piped)"
 #           curse_string "${output}"
-#           print_string_paged_if_exceeds_terminal_dimensions "${output}"
+#           page_string_if_overlong "${output}"
 
-#FIXME: Woops! We've dramatically simplified this by now paging on *ANY*
+#FUXME: Woops! We've dramatically simplified this by now paging on *ANY*
 #line wrapping. That means we know longer need to determine displayed page
 #length. Clean up documentation.
-#FIXME: Actually, while this is decent, it'd be far better to:
+#FUXME: Actually, while this is decent, it'd be far better to:
 #
 #* Revert back to the prior logic of only paging when total displayed line
 #  length exceeds terminal height *AND*
