Function prototype standard input support.
Function prototype localization and validation is now in a respectable position
to support the standard input argument channel. (Formerly, we simply ignored
such channel; now, we at least syntactically parse such channel into an
appropriate string. (We still don't actually *DO* anything with that string, of
course. But we could, conceivably. Maybe.))

diff --git a/src/00-start/00-declare/30-set/prototype b/src/00-start/00-declare/30-set/prototype
--- a/src/00-start/00-declare/30-set/prototype
+++ b/src/00-start/00-declare/30-set/prototype
@@ -18,15 +18,19 @@ function :alias_prototype.set_name() {
 
 #FIXME: Document me.
 
-# :void :alias_prototype.set_attrs,names,args(
+# :void :alias_prototype.set_attrs,names(
 #     :string alias_prototype,
 #     ^:map    attrs_name,
-#     ^:list   names_name,
-#     ^:string args_name)
-function :alias_prototype.set_attrs,names,args() {
-    (( # == 4 )) || :die\
-        'Expected one alias prototype, one map name, one list name, and one string name.'
-    ::callable_prototype.set_attrs,names,args_of_label "${@}" 'Alias'
+#     ^:list   names_name)
+function :alias_prototype.set_attrs,names() {
+    # Validate sanity.
+    (( # == 3 )) || :die\
+        'Expected one alias prototype, one map name, and one list name.'
+    local placeholder__apsan
+
+    # Set such metadata.
+    ::callable_prototype.set_attrs,names,args,stdin_of_label\
+        "${@}" placeholder__apsan placeholder__apsan 'Alias'
 }
 
 # ....................{ SETTERS ~ func                     }....................
@@ -41,15 +45,16 @@ function :func.set_prototype_name() {
 
 #FIXME: Document me.
 
-# :void :func_prototype.set_attrs,names,args(
+# :void :func_prototype.set_attrs,names,args,stdin(
 #     :string func_prototype,
 #     ^:map    attrs_name,
 #     ^:list   names_name,
-#     ^:string args_name)
-function :func_prototype.set_attrs,names,args() {
-    (( # == 4 )) || :die\
-        'Expected one function prototype, one map name, one list name, and one string name.'
-    ::callable_prototype.set_attrs,names,args_of_label "${@}" 'Function'
+#     ^:string args_name,
+#     ^:string stdin_name)
+function :func_prototype.set_attrs,names,args,stdin() {
+    (( # == 5 )) || :die\
+        'Expected one function prototype, one map name, one list name, and two string names.'
+    ::callable_prototype.set_attrs,names,args,stdin_of_label "${@}" 'Function'
 }
 
 # ....................{ SETTERS ~ global                   }....................
@@ -114,7 +119,7 @@ function :set_list,string,bool_to_global_names,value,is_value() {
 
     # If such prototype is syntactically invalid, throw an exception.
     [[ "${global_names_and_value__slsbtgnviv}" =~\
-        "${ZESHY_PROTOTYPE_GLOBAL_NAMES_VALUE_PCRE}" ]] || :die\
+        "${ZESHY_GLOBAL_PROTOTYPE_NAMES_VALUE_PCRE}" ]] || :die\
         'Global declaration'$(::parcel.get_preposition)' invalid:'$'\n'${global_names_and_value__slsbtgnviv}
 
     # If such match failed to capture such global's names, throw an exception.
@@ -169,7 +174,7 @@ function ::callable_prototype.set_name_of_label() {
 
     # If such prototype is syntactically invalid, throw an exception.
     [[ ${prototype__sstrpn} =~\
-       ${ZESHY_PROTOTYPE_RUNNABLE_NAME_PCRE} ]] || :die\
+       ${ZESHY_RUNNABLE_PROTOTYPE_NAME_PCRE} ]] || :die\
         ${label__sstrpn}' prototype'$(::parcel.get_preposition)' invalid or declares two or more '${(L)label__sstrpn}' names:'${prototype__sstrpn}
 
     # If such name was *NOT* captured into ${match[1]}, throw an exception.
@@ -201,7 +206,7 @@ function ::callable_prototype.set_names_of_label() {
     # Parse such callable names from such prototype. To centralize logic, also
     # parse such callable attributes despite the caller not requesting such
     # attributes -- which we then promptly discard.
-    ::callable_prototype.set_attrs,names,args_of_label\
+    ::callable_prototype.set_attrs,names,args,stdin_of_label\
         "${1}"\
         placeholder_attrs__sltrpn\
         "${2}"\
@@ -213,7 +218,7 @@ function ::callable_prototype.set_names_of_label() {
 #crucial. See such function for specific details on what and how to optimize.
 #FIXME: One prominent way we could optimize such function, aside from the
 #obvious externalization of locals as globals, is to dramatically reduce PCRE
-#${ZESHY_PROTOTYPE_RUNNABLE_ATTRS_NAMES_ARGS_PCRE} to the absolute minimum
+#${ZESHY_RUNNABLE_PROTOTYPE_PCRE} to the absolute minimum
 #required for matching such syntactic constructs; at the moment, such PCRE does
 #that as well as validate the entirety of runnable prototype syntax. It's the
 #latter part we'd luck to cut. And while doing so is certainly feasible and
@@ -269,23 +274,25 @@ function ::callable_prototype.set_names_of_label() {
 #which zsh fails to support). Hence, the caller is responsible for parsing such
 #arguments but *NOT* attributes or names.
 
-# :void ::callable_prototype.set_attrs,names,args_of_label(
+# :void ::callable_prototype.set_attrs,names,args,stdin_of_label(
 #     :string callable_prototype,
 #     ^:map attrs_name,
 #     ^:list names_name,
 #     ^:string args_name,
+#     ^:string stdin_name,
 #     :string callable_label)
-function ::callable_prototype.set_attrs,names,args_of_label() {
+function ::callable_prototype.set_attrs,names,args,stdin_of_label() {
     # Validate sanity.
-    (( # == 5 )) || :die\
-        'Expected one callable prototype, one map name, one list name, one string name, and one callable type.'
+    (( # == 6 )) || :die\
+        'Expected one callable prototype, one map name, one list name, two string names, and one callable type.'
     local\
         prototype__smltrpan="${1}"\
         attrs_name__smltrpan="${2}"\
         names_name__smltrpan="${3}"\
         args_name__smltrpan="${4}"\
-        label__smltrpan="${5}"
-    local -a prototype_matches__smltrpan
+        stdin_name__smltrpan="${5}"\
+        label__smltrpan="${6}"
+    local -a matches__smltrpan
     :var.die_unless_type_list "${names_name__smltrpan}"
     :var.die_unless_type_map  "${attrs_name__smltrpan}"
     [[ -n ${prototype__smltrpan} ]] || :die\
@@ -296,27 +303,32 @@ function ::callable_prototype.set_attrs,names,args_of_label() {
     # only be conditionally cleared. It's complicated. And boring. Be gone!)
     set -A ${attrs_name__smltrpan}
 
+    #FIXME: In the optimized version of this function inlined into
+    #:func_.start(), use a new exception handler defined in @{*-func/die}
+    #rather than calling :die() everywhere below. Or perhaps leverage an
+    #existing exception handler already implemented, yes?
+
     # If such prototype is syntactically invalid, throw an exception.
     [[ ${prototype__smltrpan} =~\
-       ${ZESHY_PROTOTYPE_RUNNABLE_ATTRS_NAMES_ARGS_PCRE} ]] || :die\
+       ${ZESHY_RUNNABLE_PROTOTYPE_PCRE} ]] || :die\
         ${label__smltrpan}' prototype'$(::parcel.get_preposition)' invalid:'$'\n\n'${prototype__smltrpan}
 
     # If such match failed to capture either such callable's attributes or
     # names, throw an exception.
     # print -r -- "matches: ${match[*]} (${#match})"
-    (( ${#match} >= 2 )) || :die\
+    (( ${#match} >= ZESHY_RUNNABLE_PROTOTYPE_MATCH_INDEX_ARGS )) || :die\
         ${label__smltrpan}' attributes, names, and/or arguments unparsable from prototype:'$'\n\n'${prototype__smltrpan}
 
     # Preserve such matches *BEFORE* attempting attribute matching, which
     # unavoidably overwrites list global ${match}.
-    prototype_matches__smltrpan=( "${match[@]}" )
+    matches__smltrpan=( "${match[@]}" )
     # integer i__smltrpan; print -r "match prototype: ${prototype__smltrpan}"; for i__smltrpan ({1..${#match}}) { print -r "match ${i__smltrpan}: ${match[${i__smltrpan}]}" }
 
-    # If such prototype declares at least one attribute, parse such attributes
+    # If such prototype specifies at least one attribute, parse such attributes
     # and optional suffixing values into such map. Since single- and
     # double-quoted values may contain commas, such attributes must be
     # iteratively matched with a PCRE rather than split on commas.
-    if [[ -n ${prototype_matches__smltrpan[1]} ]] {
+    if [[ -n ${matches__smltrpan[${ZESHY_RUNNABLE_PROTOTYPE_MATCH_INDEX_ATTRS}]} ]] {
         # Validate sanity.
         local attrs_key__smltrpan
 
@@ -324,13 +336,13 @@ function ::callable_prototype.set_attrs,names,args_of_label() {
         # PCRE by calling pcre_study(). (Ad-hoc profiling suggests such
         # optimization to consume more time than it saves.) See
         # for_string_text_matching_pcre:() for further details.
-        pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_ATTRS_NEXT_PCRE}"
+        pcre_compile -- "${ZESHY_RUNNABLE_PROTOTYPE_ATTRS_NEXT_PCRE}"
 
         # Match and add each such attribute to such map.
         local ZPCRE_OP='0 0'
         while {
             pcre_match -b -n ${ZPCRE_OP[(w)2]} --\
-                "${prototype_matches__smltrpan[1]}"
+                "${matches__smltrpan[${ZESHY_RUNNABLE_PROTOTYPE_MATCH_INDEX_ATTRS}]}"
         } {
             # Map the current attribute to the colon-prefixed value suffixing
             # such attribute if such attribute is suffixed by such a value or
@@ -343,55 +355,95 @@ function ::callable_prototype.set_attrs,names,args_of_label() {
         }
     }
 
-    # If such prototype only declares one name, set such list to such name. See
+    # If such prototype only specifies one name, set such list to such name. See
     # :list.set_to_string().
-    if [[ -n ${prototype_matches__smltrpan[2]} ]] {
-        set -A ${names_name__smltrpan} "${prototype_matches__smltrpan[2]}"
-    # Else, such prototype declares multiple comma-delimited names. Since
+    if [[ -n ${matches__smltrpan[${ZESHY_RUNNABLE_PROTOTYPE_MATCH_INDEX_NAME}]} ]] {
+        set -A\
+            ${names_name__smltrpan}\
+            "${matches__smltrpan[${ZESHY_RUNNABLE_PROTOTYPE_MATCH_INDEX_NAME}]}"
+    # Else, such prototype specifies multiple comma-delimited names. Since
     # single- and double-quoted callable names may contain commas, such names
     # must be iteratively matched with a PCRE rather than split on commas.
     } else {
         local names_item__smltrpan
         integer names_index__smltrpan=0
 
-        # If such match failed to capture such names, throw an exception.
-        (( ${#prototype_matches__smltrpan} >= 3 )) || :die\
-            ${label__smltrpan}' names unparsable from prototype:'$'\n\n'${prototype__smltrpan}
-
         # Clear such list. See clear_list() for further details.
         set -A ${names_name__smltrpan}
 
-        # Compile such PCRE. See above for further details.
-        pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_NEXT_PCRE}"
+        # Index of the current non-existent list item to be appended.
+        names_index__smltrpan=1
 
-        # Match and append each such name to such list.
+        # Compile such PCRE. See above for further details.
+        pcre_compile -- "${ZESHY_RUNNABLE_PROTOTYPE_NAMES_NEXT_PCRE}"
+
+        # Match and append each such name to such list by indirection like that
+        # above. (An eval() statement would also suffice, if less efficiently.)
         local ZPCRE_OP='0 0'
         while {
             pcre_match -b -n ${ZPCRE_OP[(w)2]} --\
-                "${prototype_matches__smltrpan[3]}"
+                "${matches__smltrpan[${ZESHY_RUNNABLE_PROTOTYPE_MATCH_INDEX_NAMES}]}"
         } {
-            #FIXME: Can we not inline such incrementation below: e.g., as
-            #
-            #    names_item__smltrpan=${names_name__smltrpan}'['$(( names_index__smltrpan++ ))']'
-            #
-            #Naturally, that will probably require initializing
-            #${names_index__smltrpan} to 1 rather than 0, above.
-
-            # Index of the current non-existent list item to be appended.
-            names_index__smltrpan+=1
-
-            # Append such name to such list with indirection similar to that
-            # performed above. (An eval() statement would also suffice here, if
-            # less efficiently.)
-            names_item__smltrpan="${names_name__smltrpan}[${names_index__smltrpan}]"
+            names_item__smltrpan=${names_name__smltrpan}'['$(( names_index__smltrpan++ ))']'
             : "${(P)names_item__smltrpan::=${match[1]}}"
         }
     }
 
-    # Set such string to such arguments, defaulting to the empty string if
-    # such callable accepts no arguments (e.g., "()").
-    :string.set\
-        "${args_name__smltrpan}" "${prototype_matches__smltrpan[4]-}"
+    #FIXME: Since this will be inherently optimized by inlining such logic,
+    #ignore such inefficiencies for now.
+
+    # Initialize such argument and standard input lists to the empty string.
+    :string.set "${args_name__smltrpan}" ''
+    :string.set "${stdin_name__smltrpan}" ''
+
+    # If such prototype specifies an argument list, set such string.
+    if [[ -n ${matches__smltrpan[${ZESHY_RUNNABLE_PROTOTYPE_MATCH_INDEX_ARGS}]} ]] {
+        # Discard the ")" suffixing such match. See ={*-pcre}.
+        :string.set\
+            "${args_name__smltrpan}"\
+            "${matches__smltrpan[${ZESHY_RUNNABLE_PROTOTYPE_MATCH_INDEX_ARGS}][1,-2]}"
+    # Else, such prototype specifies one or two argument channels. Parse the
+    # argument lists for such channels into the corresponding strings.
+    } else {
+        # If such match failed to capture such channels, throw an exception.
+        (( ${#matches__smltrpan} >=\
+           ZESHY_RUNNABLE_PROTOTYPE_MATCH_INDEX_ARG_CHANNEL_FIRST_ARGS )) || :die\
+            ${label__smltrpan}' argument channels unparsable from prototype:'$'\n\n'${prototype__smltrpan}
+
+        # For the match indices corresponding to the names of the first and
+        # second argument channels (if any), ...
+        integer arg_channel_name_match_index__smltrpan
+        for     arg_channel_name_match_index__smltrpan (
+            ${ZESHY_RUNNABLE_PROTOTYPE_MATCH_INDEX_ARG_CHANNEL_FIRST_NAME}
+            ${ZESHY_RUNNABLE_PROTOTYPE_MATCH_INDEX_ARG_CHANNEL_SECOND_NAME}
+        ) {
+            # If such channel is either the argument list (as is the customary
+            # case) or the standard input list, set the corresponding string.
+            case ${matches__smltrpan[${arg_channel_name_match_index__smltrpan}]-} {
+            'args') {
+                # Discard the ")" suffixing such match. See ={*-pcre}.
+                :string.set\
+                    "${args_name__smltrpan}"\
+                    "${matches__smltrpan[$(( arg_channel_name_match_index + 1 ))][1,-2]}"
+                ;;
+            'stdin') {
+                # Discard the ")" suffixing such match. See ={*-pcre}.
+                :string.set\
+                    "${stdin_name__smltrpan}"\
+                    "${matches__smltrpan[$(( arg_channel_name_match_index + 1 ))][1,-2]}"
+                ;;
+            # Else if such channel name is empty, such channel *MUST* be an
+            # unspecified second channel. Since such channel is optional, this
+            # is *NOT* an error. (Simply ignore this.)
+            '')
+                ;;
+            # Else, such channel is unrecognized. Throw an exception!
+            *) {
+                :die\
+                    ${label__smltrpan}' argument channel '' unrecognized in prototype:'$'\n\n'${prototype__smltrpan}
+            }
+        }
+    }
 }
 
 # ....................{ OBSOLETE                           }....................
@@ -467,6 +519,50 @@ function run_runnable_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+        # local arg_channel_name__smltrpan
+
+            # Name of such channel.
+            # arg_channel_name__smltrpan=${matches__smltrpan[${arg_channel_name_match_index__smltrpan}]}
+
+            # # If such channel is either the argument list (as is the customary
+            # # case) or the standard input list, set the corresponding string.
+            # if [[ ${arg_channel_name__smltrpan} == 'args' ]] {
+            #     # Discard the ")" suffixing such match. See ={*-pcre}.
+            #     :string.set\
+            #         "${args_name__smltrpan}"\
+            #         "${matches__smltrpan[$(( arg_channel_name_match_index + 1 ))][1,-2]}"
+            # # Else if such channel is the standard input list, set such string.
+            # } elif [[ ${arg_channel_name__smltrpan} == 'stdin' ]] {
+
+        # If such match failed to capture such names, throw an exception.
+        # (( ${#matches__smltrpan} >=\
+        #    ZESHY_RUNNABLE_PROTOTYPE_MATCH_INDEX_NAMES )) || :die\
+        #     ${label__smltrpan}' names unparsable from prototype:'$'\n\n'${prototype__smltrpan}
+
+    # Set such string to such arguments, defaulting to the empty string if
+    # such callable accepts no arguments (e.g., "()").
+
+    # Parse such callable names from such prototype. To centralize logic, also
+    # parse such callable attributes despite the caller not requesting such
+    # attributes -- which we then promptly discard.
+    # ::callable_prototype.set_attrs,names,args,stdin_of_label\
+    #     "${1}"\
+    #     placeholder_attrs__sltrpn\
+    #     "${2}"\
+    #     placeholder_args__sltrpn\
+    #     "${3}"
+
+            #FUXME: Can we not inline such incrementation below: e.g., as
+            #
+            #    names_item__smltrpan=${names_name__smltrpan}'['$(( names_index__smltrpan++ ))']'
+            #
+            #Naturally, that will probably require initializing
+            #${names_index__smltrpan} to 1 rather than 0, above.
+
+            # Index of the current non-existent list item to be appended.
+            # names_index__smltrpan+=1
+            # names_item__smltrpan="${names_name__smltrpan}[${names_index__smltrpan}]"
+
 # Do *NOT* quote
         # the result of such split. 
         #FUXME: Arguably, we should just define :clear_map() here.
@@ -531,7 +627,7 @@ function run_runnable_with_stdin() {
 # 
 #         # Prepare to match such names. See for_string_text_matching_pcre:() for further
 #         # details.
-#         pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_NEXT_PCRE}"
+#         pcre_compile -- "${ZESHY_RUNNABLE_PROTOTYPE_NAMES_NEXT_PCRE}"
 #         # pcre_study
 # 
 #         # Match such names.
@@ -657,7 +753,7 @@ function run_runnable_with_stdin() {
 
         # # Compile such PCRE. See for_string_text_matching_pcre:() for further
         # # details.
-        # pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_NEXT_PCRE}"
+        # pcre_compile -- "${ZESHY_RUNNABLE_PROTOTYPE_NAMES_NEXT_PCRE}"
         # pcre_study
 
         # # Match and append each such name to such list.
@@ -796,7 +892,7 @@ function run_runnable_with_stdin() {
 # 
 #     # If such prototype is syntactically invalid, throw an exception.
 #     [[ "${global_prototype__sltgpn}" =~\
-#         "${ZESHY_PROTOTYPE_GLOBAL_TYPE_NAMES_VALUE_PCRE}" ]] || :die\
+#         "${ZESHY_GLOBAL_PROTOTYPE_TYPE_NAMES_VALUE_PCRE}" ]] || :die\
 #         'Global prototype invalid:'$'\n'${global_prototype__sltgpn}
 # 
 #     # If such match failed to capture such global's names, throw an exception.
@@ -932,7 +1028,7 @@ function run_runnable_with_stdin() {
 # 
 #     # If such prototype is syntactically invalid, throw an exception.
 #     [[ "${prototype__sltrpn}" =~\
-#         "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_PCRE}" ]] || :die\
+#         "${ZESHY_RUNNABLE_PROTOTYPE_NAMES_PCRE}" ]] || :die\
 #         'Runnable prototype "'${prototype__sltrpn}'" invalid.'
 # 
 #     # If no such names were captured, throw an exception.
@@ -953,7 +1049,7 @@ function run_runnable_with_stdin() {
 # 
 #         # Compile such PCRE. See for_string_text_matching_pcre:() for further
 #         # details.
-#         pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_NEXT_PCRE}"
+#         pcre_compile -- "${ZESHY_RUNNABLE_PROTOTYPE_NAMES_NEXT_PCRE}"
 #         pcre_study
 # 
 #         # Match and append each such name to such list.
