Copyright notice bumped.
Unrelatedly, corrected numerous early-time regressions introduced by recent
refactoring efforts. We're certainly *NOT* at a compiling codebase, but it does
imperceptibly waver in and out of foggy-brained focus.

diff --git a/src/00-start/00-declare/30-set/prototype b/src/00-start/00-declare/30-set/prototype
--- a/src/00-start/00-declare/30-set/prototype
+++ b/src/00-start/00-declare/30-set/prototype
@@ -1,6 +1,6 @@
 #!/usr/bin/env zsh
 # --------------------( LICENSE                            )--------------------
-# Copyright 2007-2013 by Cecil Curry.
+# Copyright 2007-2014 by Cecil Curry.
 # See "COPYING" for additional details.
 
 # Due to chicken-and-the-egg conundra, all operables defined below are
@@ -18,19 +18,6 @@
 function :alias_prototype.set_name() {
     (( # == 2 )) || :die 'Expected one alias prototype and one string name.'
     ::callable_prototype_of_label.set_name "${1}" 'Alias' "${2}"
-}
-
-#FIXME: Document me.
-
-# :void :alias_prototype.set_attrs,names(
-#     :string alias_prototype,
-#     ^:map attrs_name,
-#     ^:list names_name)
-function :alias_prototype.set_attrs,names() {
-    (( # == 3 )) || :die\
-        'Expected one alias prototype, one map name, and one list name.'
-    ::callable_prototype_of_label.set_attrs,names
-        "${1}" 'Alias' "${2}" "${3}"
 }
 
 # ....................{ SETTERS ~ func                     }....................
@@ -60,7 +47,7 @@ function :global_prototype.set_names() {
     # If such prototype is syntactically invalid, throw an exception.
     [[ ${prototype__gpsn} =~\
        ${ZESHY_GLOBAL_HELP_PROTOTYPE_NAMES_PCRE} ]] || :die\
-        $(::parcel.get_preposition)' global prototype invalid:'$'\n\n'${prototype__gpsn}
+        $(::parcel.get_current)' global prototype invalid:'$'\n\n'${prototype__gpsn}
 
     # If such prototype only specifies one name, set such list to such name.
     if [[ -n ${match[1]-} ]] {
@@ -100,7 +87,7 @@ function ::callable_prototype_of_label.set_name() {
     # runnable name, throw an exception.
     [[ ${prototype__cpsnol} =~\
        ${ZESHY_CALLABLE_PROTOTYPE_NAME_PCRE} ]] || :die\
-        ${label__cpsnol}' prototype'$(::parcel.get_preposition)' invalid or declares two or more '${(L)label__cpsnol}' names:'${prototype__cpsnol}
+        ${label__cpsnol}' prototype'$(::parcel.get_current)' invalid or declares two or more '${(L)label__cpsnol}' names:'${prototype__cpsnol}
 
     # If such match failed to capture such name, throw an exception.
     (( ${#match} )) || :die\
@@ -129,11 +116,7 @@ function ::callable_prototype_of_label.set_names() {
     # If such prototype is syntactically invalid, throw an exception.
     [[ ${prototype__cpolsn} =~\
        ${ZESHY_CALLABLE_PROTOTYPE_NAMES_PCRE} ]] || :die\
-        ${label__cpolsn}' prototype'$(::parcel.get_preposition)' invalid:'${prototype__cpolsn}
-
-    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-    # Synchronize with ::callable_prototype_of_label.set_attrs,names().
-    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+        $(::parcel.get_current)${label__cpolsn}' prototype invalid:'${prototype__cpolsn}
 
     # If such prototype only specifies one name, set such list to such name.
     if [[ -n ${match[1]-} ]] {
@@ -169,103 +152,6 @@ function ::callable_prototype_of_label.set_names() {
         while { pcre_match -b -n ${ZPCRE_OP[(w)2]} -- "${names__cpolsn}" } {
             names_item__cpolsn=${names_name__cpolsn}'['$(( names_index__cpolsn++ ))']'
             : "${(P)names_item__cpolsn::=${match[1]}}"
-        }
-    }
-}
-
-#FIXME: Document me.
-
-# :void ::callable_prototype_of_label.set_attrs,names(
-#     :string callable_prototype,
-#     :string callable_label,
-#     ^:map attrs_name,
-#     ^:list names_name)
-function ::callable_prototype_of_label.set_attrs,names() {
-    # Validate sanity.
-    (( # == 4 )) || :die\
-        'Expected one callable prototype, one callable label, one map name, and one list name.'
-    local\
-        prototype__cpolsan="${1}"\
-        label__cpolsan="${2}"\
-        attrs_name__cpolsan="${3}"\
-        names_name__cpolsan="${4}"
-    local -a match__cpolsan
-    :var.die_unless_type_map  "${attrs_name__cpolsan}"
-    :var.die_unless_type_list "${names_name__cpolsan}"
-
-    # Canonical string global ${ZPCRE_OP}, localized to avoid overwriting
-    # either global or caller-specific versions of such variable.
-    local ZPCRE_OP
-
-    # If such prototype is syntactically invalid, throw an exception.
-    [[ ${prototype__cpolsan} =~\
-       ${ZESHY_CALLABLE_PROTOTYPE_ATTRS_NAMES_PCRE} ]] || :die\
-        ${label__cpolsan}' prototype'$(::parcel.get_preposition)' invalid:'${prototype__cpolsan}
-
-    # Preserve such matches *BEFORE* matching attributes and hence overwriting
-    # canonical list global ${match}.
-    match__cpolsan=( "${match[@]}" )
-    # integer i__cpolsan; print -r "match prototype: ${prototype__cpolsan}"; for i__cpolsan ({1..${#match}}) { print -r "match ${i__cpolsan}: ${match[${i__cpolsan}]}" }
-
-    # If such prototype specifies at least one attribute, parse such attributes
-    # and optional suffixing values into such map. Since single- and
-    # double-quoted values may contain commas, such attributes must be
-    # iteratively matched with a PCRE rather than split on commas.
-    if [[ -n ${match__cpolsan[1]} ]] {
-        # Validate sanity.
-        local attrs_key__cpolsan
-
-        # Compile such PCRE. For efficiency, avoid optionally optimizing such
-        # PCRE by calling pcre_study(). (Ad-hoc profiling suggests such
-        # optimization to consume more time than it saves.) See
-        # for_string_text_matching_pcre:() for further details.
-        pcre_compile -- "${ZESHY_CALLABLE_PROTOTYPE_ATTRS_NEXT_PCRE}"
-
-        # Match and add each such attribute to such map.
-        ZPCRE_OP='0 0'
-        while { pcre_match -b -n ${ZPCRE_OP[(w)2]} -- "${match__cpolsan[1]}" } {
-            # Map the current attribute to the colon-prefixed value suffixing
-            # such attribute if such attribute is suffixed by such a value or
-            # to the empty string otherwise. Such indirection is required by
-            # zsh setting arbitrary map keys outside of eval() statements. (An
-            # eval() statement would also suffice here, if less efficiently.)
-            # See :set_map_key_to_string() for further details.
-            attrs_key__cpolsan="${attrs_name__cpolsan}[${match[1]}]"
-            : "${(P)attrs_key__cpolsan::=${match[2]-}}"
-        }
-    }
-
-    # If such prototype only specifies one name, set such list to such name.
-    if [[ -n ${match__cpolsan[2]-} ]] {
-        # If such match failed to capture such name, throw an exception.
-        (( ${#match} == 2 )) || :die\
-            ${label__cpolsan}' names unparsable from prototype:'$'\n\n'${prototype__cpolsan}
-
-        # Set such list. See :list.set_to_string().
-        set -A ${names_name__cpolsan} "${match__cpolsan[2]}"
-    # Else, such prototype specifies multiple comma-delimited names. Since
-    # single- and double-quoted callable names may contain commas, such names
-    # must be iteratively matched with a PCRE rather than split on commas.
-    } else {
-        local names_item__cpolsan
-
-        # Index of the current non-existent list item to be appended.
-        integer names_index__cpolsan=1
-
-        # If such match failed to capture such names, throw an exception.
-        (( ${#match__cpolsan} == 3 )) || :die\
-            ${label__cpolsan}' names unparsable from prototype:'$'\n\n'${prototype__cpolsan}
-
-        # Clear such list. See :list.clear() for further details.
-        set -A ${names_name__cpolsan}
-
-        # Match and append each such name to such list by indirection like that
-        # above. (An eval() statement would also suffice, if less efficiently.)
-        pcre_compile -- "${ZESHY_CALLABLE_PROTOTYPE_NAMES_NEXT_PCRE}"
-        ZPCRE_OP='0 0'
-        while { pcre_match -b -n ${ZPCRE_OP[(w)2]} -- "${match__cpolsan[3]}" } {
-            names_item__cpolsan=${names_name__cpolsan}'['$(( names_index__cpolsan++ ))']'
-            : "${(P)names_item__cpolsan::=${match[1]}}"
         }
     }
 }
@@ -343,6 +229,122 @@ function run_runnable_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+#FUXME: After shifting to ={alias}, is this still called anywhere? We suspect
+#not. If not, excise us up, please.
+#FUXME: Document me.
+
+# # :void ::callable_prototype_of_label.set_attrs,names(
+# #     :string callable_prototype,
+# #     :string callable_label,
+# #     ^:map attrs_name,
+# #     ^:list names_name)
+# function ::callable_prototype_of_label.set_attrs,names() {
+#     # Validate sanity.
+#     (( # == 4 )) || :die\
+#         'Expected one callable prototype, one callable label, one map name, and one list name.'
+#     local\
+#         prototype__cpolsan="${1}"\
+#         label__cpolsan="${2}"\
+#         attrs_name__cpolsan="${3}"\
+#         names_name__cpolsan="${4}"
+#     local -a match__cpolsan
+#     :var.die_unless_type_map  "${attrs_name__cpolsan}"
+#     :var.die_unless_type_list "${names_name__cpolsan}"
+# 
+#     # Canonical string global ${ZPCRE_OP}, localized to avoid overwriting
+#     # either global or caller-specific versions of such variable.
+#     local ZPCRE_OP
+# 
+#     # If such prototype is syntactically invalid, throw an exception.
+#     [[ ${prototype__cpolsan} =~\
+#        ${ZESHY_CALLABLE_PROTOTYPE_ATTRS_NAMES_PCRE} ]] || :die\
+#         $(::parcel.get_current)${label__cpolsan}' prototype invalid:'${prototype__cpolsan}
+# 
+#     # Preserve such matches *BEFORE* matching attributes and hence overwriting
+#     # canonical list global ${match}.
+#     match__cpolsan=( "${match[@]}" )
+#     # integer i__cpolsan; print -r "match prototype: ${prototype__cpolsan}"; for i__cpolsan ({1..${#match}}) { print -r "match ${i__cpolsan}: ${match[${i__cpolsan}]}" }
+# 
+#     # If such prototype specifies at least one attribute, parse such attributes
+#     # and optional suffixing values into such map. Since single- and
+#     # double-quoted values may contain commas, such attributes must be
+#     # iteratively matched with a PCRE rather than split on commas.
+#     if [[ -n ${match__cpolsan[1]} ]] {
+#         # Validate sanity.
+#         local attrs_key__cpolsan
+# 
+#         # Compile such PCRE. For efficiency, avoid optionally optimizing such
+#         # PCRE by calling pcre_study(). (Ad-hoc profiling suggests such
+#         # optimization to consume more time than it saves.) See
+#         # for_string_text_matching_pcre:() for further details.
+#         pcre_compile -- "${ZESHY_CALLABLE_PROTOTYPE_ATTRS_NEXT_PCRE}"
+# 
+#         # Match and add each such attribute to such map.
+#         ZPCRE_OP='0 0'
+#         while { pcre_match -b -n ${ZPCRE_OP[(w)2]} -- "${match__cpolsan[1]}" } {
+#             # Map the current attribute to the colon-prefixed value suffixing
+#             # such attribute if such attribute is suffixed by such a value or
+#             # to the empty string otherwise. Such indirection is required by
+#             # zsh setting arbitrary map keys outside of eval() statements. (An
+#             # eval() statement would also suffice here, if less efficiently.)
+#             # See :set_map_key_to_string() for further details.
+#             attrs_key__cpolsan="${attrs_name__cpolsan}[${match[1]}]"
+#             : "${(P)attrs_key__cpolsan::=${match[2]-}}"
+#         }
+#     }
+# 
+#     # If such prototype only specifies one name, set such list to such name.
+#     if [[ -n ${match__cpolsan[2]-} ]] {
+#         # If such match failed to capture such name, throw an exception.
+#         (( ${#match} == 2 )) || :die\
+#             ${label__cpolsan}' names unparsable from prototype:'$'\n\n'${prototype__cpolsan}
+# 
+#         # Set such list. See :list.set_to_string().
+#         set -A ${names_name__cpolsan} "${match__cpolsan[2]}"
+#     # Else, such prototype specifies multiple comma-delimited names. Since
+#     # single- and double-quoted callable names may contain commas, such names
+#     # must be iteratively matched with a PCRE rather than split on commas.
+#     } else {
+#         local names_item__cpolsan
+# 
+#         # Index of the current non-existent list item to be appended.
+#         integer names_index__cpolsan=1
+# 
+#         # If such match failed to capture such names, throw an exception.
+#         (( ${#match__cpolsan} == 3 )) || :die\
+#             ${label__cpolsan}' names unparsable from prototype:'$'\n\n'${prototype__cpolsan}
+# 
+#         # Clear such list. See :list.clear() for further details.
+#         set -A ${names_name__cpolsan}
+# 
+#         # Match and append each such name to such list by indirection like that
+#         # above. (An eval() statement would also suffice, if less efficiently.)
+#         pcre_compile -- "${ZESHY_CALLABLE_PROTOTYPE_NAMES_NEXT_PCRE}"
+#         ZPCRE_OP='0 0'
+#         while { pcre_match -b -n ${ZPCRE_OP[(w)2]} -- "${match__cpolsan[3]}" } {
+#             names_item__cpolsan=${names_name__cpolsan}'['$(( names_index__cpolsan++ ))']'
+#             : "${(P)names_item__cpolsan::=${match[1]}}"
+#         }
+#     }
+# }
+
+#FUXME: Document me.
+
+# # :void :alias_prototype.set_attrs,names(
+# #     :string alias_prototype,
+# #     ^:map attrs_name,
+# #     ^:list names_name)
+# function :alias_prototype.set_attrs,names() {
+#     (( # == 3 )) || :die\
+#         'Expected one alias prototype, one map name, and one list name.'
+#     ::callable_prototype_of_label.set_attrs,names
+#         "${1}" 'Alias' "${2}" "${3}"
+# }
+
+    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+    # Synchronize with ::callable_prototype_of_label.set_attrs,names().
+    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+
 #FUXME: Excise entirely.
 #FUXME: Refactor to :global_prototype.set_names,value,is_value().
 #FUXME: Actually, this function should simply be inlined into ={global}. Note
@@ -371,7 +373,7 @@ function run_runnable_with_stdin() {
 #     # If such prototype is syntactically invalid, throw an exception.
 #     [[ ${global_names_and_value__slsbtgnviv} =~\
 #        ${ZESHY_GLOBAL_PROTOTYPE_PCRE} ]] || :die\
-#         'Global declaration'$(::parcel.get_preposition)' invalid:'$'\n'${global_names_and_value__slsbtgnviv}
+#         'Global declaration'$(::parcel.get_current)' invalid:'$'\n'${global_names_and_value__slsbtgnviv}
 # 
 #     # If such match failed to capture such global's names, throw an exception.
 #     (( ${#match} )) || :die\
@@ -479,7 +481,7 @@ function run_runnable_with_stdin() {
 #     # If such prototype is syntactically invalid, throw an exception.
 #     [[ ${prototype__smltrpan} =~\
 #        ${ZESHY_CALLABLE_PROTOTYPE_PCRE} ]] || :die\
-#         ${label__smltrpan}' prototype'$(::parcel.get_preposition)' invalid:'$'\n\n'${prototype__smltrpan}
+#         ${label__smltrpan}' prototype'$(::parcel.get_current)' invalid:'$'\n\n'${prototype__smltrpan}
 # 
 #     # If such match failed to capture either such callable's attributes or
 #     # names, throw an exception.
@@ -694,7 +696,7 @@ function run_runnable_with_stdin() {
 #     # If such prototype is syntactically invalid, throw an exception.
 #     [[ ${prototype__cpolsn} =~\
 #        ${ZESHY_CALLABLE_PROTOTYPE_NAMES_PCRE} ]] || :die\
-#         ${label__cpolsn}' prototype'$(::parcel.get_preposition)' invalid:'${prototype__cpolsn}
+#         ${label__cpolsn}' prototype'$(::parcel.get_current)' invalid:'${prototype__cpolsn}
 # 
 #     #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 #     # Synchronize with ::callable_prototype_of_label.set_attrs,names().
@@ -1017,7 +1019,7 @@ function run_runnable_with_stdin() {
 #     if [[ -n "${runnable_name__sltrpn}" ]] {
 #         eval '
 #         # If such runnable is already declared, print a warning. See
-#         # is_map_key() for further details.
+#         # :map.is_key() for further details.
 #         if (( ${+'${map_name__sltrpn}'[${runnable_name__sltrpn}]} )) {
 #             :output_warning "${runnable_name__sltrpn}() in @{${ZESHY_PARCEL_NAME}} already declared."
 #         }
