Function prototype localization continued.
Improved exception handling and added support for C-style "*" indirection
syntax bookends the modest beast that is this commit. And so we linger on.

diff --git a/src/00-start/00-declare/40-func/func b/src/00-start/00-declare/40-func/func
--- a/src/00-start/00-declare/40-func/func
+++ b/src/00-start/00-declare/40-func/func
@@ -959,7 +959,7 @@ function ::func_.stop_parse_prototype() {
             # ignore the valid case that the current argument is both variadic
             # and optional. See above for further details.
             } elif (( arg_was_variadic )) {
-                ::func_.die_of_prototype\
+                ::func_.die_of_cause\
                     'accepts both optional and variadic arguments'
             # Else, such argument is validly optional.
             } else {
@@ -1011,7 +1011,7 @@ function ::func_.stop_parse_prototype() {
             # general means of deciding which such list a passed string was
             # intended to belong to.
             } elif (( arg_was_variadic )) {
-                ::func_.die_of_prototype\
+                ::func_.die_of_cause\
                     'accepts two or more variadic arguments'
             # If a prior argument is optional, throw an exception. Such case
             # implies such function to accept one or more optional arguments
@@ -1024,7 +1024,7 @@ function ::func_.stop_parse_prototype() {
             # following a prior variadic argument, the prior exception is more
             # explanatory than this exception.
             } elif (( arg_was_optional )) {
-                ::func_.die_of_prototype\
+                ::func_.die_of_cause\
                     'accepts both optional and variadic arguments'
             # Else, such argument is validly variadic.
             } else {
@@ -1047,25 +1047,19 @@ function ::func_.stop_parse_prototype() {
             if (( arg_is_optional )) { arg_was_optional=1 }
             if (( arg_is_variadic )) { arg_was_variadic=1 }
 
-            #FIXME: If such type is nonscalar (e.g., prefixed by either ":list"
-            #or ":map"), we need to throw an exception. Argument values are, by
-            #definition, *ONLY* scalar.
-
             # Argument name and type, localized for efficient reuse below.
             arg_name=${match[${ZESHY_RUNNABLE_ARG_MATCH_INDEX_NAME}]}
             arg_type=${match[${ZESHY_RUNNABLE_ARG_MATCH_INDEX_TYPE}]}
 
             #FIXME: Define a new exception handler
-            #::func_.die_of_prototype_argument_type() and call such handler
+            #::func_.die_of_cause_argument_type() and call such handler
             #everywhere below in place of the current logic.
 
             # If such type is nonscalar (i.e., list or map), throw an
             # exception. By definition, argument types are *ALWAYS* scalar.
             [[ "${arg_type}" != ':'('list'|'map')('_'*|) ]] ||
-                ::func_.die_of_prototype\
-                    'accepts both optional and variadic arguments'
-                (( ${+aliases[${arg_definer}]} )) || ::func_.die_of_prototype\
-                    'argument ${'${arg_name}'} type '${arg_type}' unrecognized (i.e., alias '${arg_type}'() undefined)'
+                ::func_.die_of_cause_arg_type\
+                    'nonscalar, but zsh only supports scalar argument types (e.g., `:bool`, `:char`, `:float`, `:int`, `:string`)'
 
             # If localizing such argument (i.e., if such argument name is
             # unrelaxed), note such fact by appending an initialization of such
@@ -1083,8 +1077,9 @@ function ::func_.stop_parse_prototype() {
 
                 # If such type is *NOT* the name of an existing alias, throw an
                 # exception. See :is_alias_simple() for details.
-                (( ${+aliases[${arg_definer}]} )) || ::func_.die_of_prototype\
-                    'argument ${'${arg_name}'} type '${arg_type}' unrecognized (i.e., alias '${arg_type}'() undefined)'
+                (( ${+aliases[${arg_definer}]} )) || 
+                    ::func_.die_of_cause_arg_type\
+                        'unrecognized, requiring undefined alias '${arg_definer}'() to locally declare such argument'
 
                 # Map such alias name to such argument definition.
                 arg_definer_to_definitions[${arg_definer}]+=' '${arg_name}'="${'${arg_index}'}"'
@@ -1125,15 +1120,66 @@ function ::func_.stop_parse_prototype() {
                 #
                 #Hence, "/" and "+" are both essential syntax. Neither
                 #obsoletes or obviates the other. Make it so, please!
+                #FIXME: Hey, it gets even better! The above syntax clearly
+                #obsoletes our existing (and frankly rather kludgy) handling of
+                #variable indirection. Specifically, arguments of type
+                #":string/var+${var_type}" clearly obsolete prior type
+                #":string:${var_type}". Hence, do away with *ALL* ":string:"
+                #handling below. However, note that repeating ":string/var+"
+                #everywhere in list- and map-centric function prototypes will
+                #get old fairly quickly. We might consider a new argument type
+                #prefix: ":*", shorthand for ":string/var+". Hence, the
+                #following prototypes are equivalent:
+                #
+                #    :void ::handle(:string/var+char char_name+__h)
+                #    :void ::handle(:*char char_name+__h)
+                #    :void ::handle(*:char char_name+__h)
+                #    :void ::handle(:char *char_name+__h)
+                #
+                #Well, three choices anyway. Contemplate a bit further.
+                #FIXME: O.K.; C adopted "char *p" syntax to imply that "*p" is
+                #the manner with which you access the data such pointer refers
+                #to. In zeshy, however, we have no pointers, so that doesn't
+                #apply; moreover, we've always thought such syntax to be
+                #inherently irrational, in that the "*" modifies the type of
+                #such variable and hence should be associated with such type
+                #rather than such pointer name. Hence, either ":*char" or
+                #"*:char" would be appropriate here. Indeed, for the same
+                #reason, "*:char" is probably the most appropriate choice.
+                #(Adopting C syntax would also be in poor taste here, as that
+                #would tacitly imply zeshy to support pointers, which it
+                #clearly does not.)
+                #
+                #However, "*:char" has one additional advantage over ":*char":
+                #the former supports custom user-defined types leveraging a
+                #user-specific prefix (e.g., "*@bytes"), whereas the latter
+                #obstructs such use. Right then! We shay go with:
+                #
+                #    :void ::handle(*:char char_name+__h)
+                #FIXME: If both "*" and a major subtype are specified, throw an
+                #exception. That is to say, prohibit the second argument here:
+                #
+                #    :void ::handle(:int number, :char/var char_name+__h)
 
-                # Argument subtype, localized for efficient reuse below.
-                arg_subtype="${match[${ZESHY_RUNNABLE_ARG_MATCH_INDEX_SUBTYPE}]}"
+                # Major and minor argument subtypes, localized for efficient
+                # reuse below.
+                arg_subtype_major="${match[${ZESHY_RUNNABLE_ARG_MATCH_INDEX_SUBTYPE_MAJOR}]}"
+                arg_subtype_minor="${match[${ZESHY_RUNNABLE_ARG_MATCH_INDEX_SUBTYPE_MINOR}]}"
 
                 # If such argument is a string referring to another variable's name,
-                # validate the latter to exist *AND* be of the expected type. For
-                # efficiency, obtain such type with raw string indices rather
-                # than globbed match groups (e.g., ':string:'(#b)(*)).
-                if [[ "${arg_type}" == ':string:'* ]] {
+                # validate the latter to exist *AND* be of the expected type.
+                # To implement the latter, validate such argument by calling a
+                # function :string.${arg_subtype_major}.
+                if [[ "${arg_subtype_major}" == 'var' ]] {
+                    # If such argument type is *NOT* ":string", throw an
+                    # exception. While integer arguments could technically
+                    # refer to variables whose names are themselves integers,
+                    # such edge-case seems both implausible and error-prone. In
+                    # practice, only strings refer to other variables.
+                    [[ "${arg_type}" == ':string' ]] ||
+                        ::func_.die_of_cause_arg_type\
+                            'not a string but indirectly refers to variables by name; consider prefixing such type by "*" or ":string/var" instead'
+
                     # If such argument is subtyped, such subtype constraints
                     # the value of the variable such argument refers to rather
                     # than such variable's type. In contrast to the customary
@@ -1157,8 +1203,9 @@ function ::func_.stop_parse_prototype() {
                         # If such function does *NOT* exist, throw an
                         # exception. For efficiency, inline such test. See
                         # :func.is() for further details.
-                        (( ${+functions[${arg_tester}]} )) || ::func_.die_of_prototype\
-                            'argument ${'${arg_name}'} type '${arg_type[9,-1]}$([[ -z "${arg_subtype}" ]] || print -r -- '+'${arg_subtype})' unrecognized (i.e., function '${arg_tester}'() undefined)'
+                        (( ${+functions[${arg_tester}]} )) ||
+                            ::func_.die_of_cause_arg_type\
+                                'unrecognized, requiring undefined function '${arg_tester}'() to validate the variable such argument refers to'
 
                         # Map such function name to such variable expansion.
                         #
@@ -1226,8 +1273,9 @@ function ::func_.stop_parse_prototype() {
 
                 # If such function does *NOT* exist, throw an exception.  For
                 # efficiency, inline such test. See :func.is() for details.
-                (( ${+functions[${arg_tester}]} )) || ::func_.die_of_prototype\
-                    'argument ${'${arg_name}'} type '${arg_type}$([[ -z "${arg_subtype}" ]] || print -r -- '+'${arg_subtype})' unrecognized (i.e., function '${arg_tester}'() undefined)'
+                (( ${+functions[${arg_tester}]} )) ||
+                    ::func_.die_of_cause_arg_type\
+                        'unrecognized, requiring undefined function '${arg_tester}'() to validate such argument'
 
                 # Map such function name to such argument expansion.
                 arg_tester_to_values[${arg_tester}]+=' "${'${arg_index}'}"'
@@ -1461,6 +1509,21 @@ function declare_function_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+                    # ::func_.die_of_cause\
+                    # 'argument ${'${arg_name}'} type '${arg_type}$([[ -z "${arg_subtype}" ]] || print -r -- '+'${arg_subtype})' unrecognized (i.e., function '${arg_tester}'() undefined)'
+                            # 'argument ${'${arg_name}'} type '${arg_type[9,-1]}$([[ -z "${arg_subtype}" ]] || print -r -- '+'${arg_subtype})' unrecognized (i.e., function '${arg_tester}'() undefined)'
+
+                    #FUXME: Ugh. Need a new argument exception handler.
+            #FUXME: If such type is nonscalar (e.g., prefixed by either ":list"
+            #or ":map"), we need to throw an exception. Argument values are, by
+            #definition, *ONLY* scalar.
+
+                # If such argument is a string referring to another variable's name,
+                # validate the latter to exist *AND* be of the expected type. For
+                # efficiency, obtain such type with raw string indices rather
+                # than globbed match groups (e.g., ':string:'(#b)(*)).
+                # if [[ "${arg_type}" == ':string:'* ]] {
+
     #FUXME: Correct comment in line with ${arg_definer_to_definitions}.
     # Map from argument variable type (i.e., the type of the variable referred
     # to by an argument) to space-delimited string of the indices of all
@@ -1710,7 +1773,7 @@ function declare_function_with_stdin() {
             # }
 
             # # If such function does *NOT* exist, throw a custom exception.
-            # :func.is "${arg_tester}" || ::func_.die_of_prototype\
+            # :func.is "${arg_tester}" || ::func_.die_of_cause\
             #     'argument type '${arg_type}' unrecognized (i.e., function '${arg_tester}'() undefined)'
 
                 #FUXME: Not quite. We need to test for argument types matching
@@ -1773,7 +1836,7 @@ function declare_function_with_stdin() {
             #     arg_tester=':'${arg_type}'.is'
             # }
 
-                # [[ -z "${arg_subtype}" ]] || ::func_.die_of_prototype\
+                # [[ -z "${arg_subtype}" ]] || ::func_.die_of_cause\
                 #     'argument type '${arg_type}'+'${arg_subtype}' '
 
         # validate all such arguments to be of such type.
@@ -1950,7 +2013,7 @@ function declare_function_with_stdin() {
             # } elif [[\
             #     -z "${match[${ZESHY_RUNNABLE_ARG_MATCH_INDEX_is_optional}]-}" ||
             #     -z "${match[${ZESHY_RUNNABLE_ARG_MATCH_INDEX_value}]-}" ]] ||\
-            #     ::func_.die_of_prototype\
+            #     ::func_.die_of_cause\
             #         'argument '${match[ZESHY_RUNNABLE_ARG_MATCH_INDEX_name]}' suffixed by both "?" and "="'
 
             #FUXME: This and the following test, as well as the setting of
@@ -2095,7 +2158,7 @@ function declare_function_with_stdin() {
     #     # implying there exists no general means of deciding which such
     #     # argument a passed string was intended to correspond to.
     #     } elif (( args_is_optional )) {
-    #         ::func_.die_of_prototype\
+    #         ::func_.die_of_cause\
     #             'accepts both optional and variadic arguments'
     #     # If a prior argument is also variadic, throw an exception.  Such
     #     # case implies such function to accept two or more variadic
@@ -2103,7 +2166,7 @@ function declare_function_with_stdin() {
     #     # general means of deciding which such list a passed string was
     #     # intended to belong to.
     #     } elif (( args_is_variadic )) {
-    #         ::func_.die_of_prototype\
+    #         ::func_.die_of_cause\
     #             'accepts two or more variadic argument lists'
     #     # Else, such argument is validly variadic. Note such fact and such
     #     # function to accept one variadic argument list.
@@ -2126,13 +2189,13 @@ function declare_function_with_stdin() {
     #     } elif [[\
     #         -z "${match[${ZESHY_RUNNABLE_ARG_MATCH_INDEX_is_optional}]-}" ||
     #         -z "${match[${ZESHY_RUNNABLE_ARG_MATCH_INDEX_value}]-}" ]] ||\
-    #        ::func_.die_of_prototype\
+    #        ::func_.die_of_cause\
     #            'argument '${match[ZESHY_RUNNABLE_ARG_MATCH_INDEX_name]}' suffixed by both "?" and "="'
     #     # If a prior argument is also variadic, throw an exception,
     #     # explicitly ignoring the valid case that the current argument is
     #     # both variadic and optional. See above for further details.
     #     } elif (( args_is_variadic && ! arg_is_variadic )) {
-    #         ::func_.die_of_prototype\
+    #         ::func_.die_of_cause\
     #             'accepts both optional and variadic arguments'
     #     # Else, such argument is validly optional. Note such fac and such
     #     # function to accept at least one optional argument.
@@ -2518,7 +2581,7 @@ function declare_function_with_stdin() {
             #FUXME: Excissively verbose, particularly when replicated across
             #*EVERY* single zeshy function. Encapsulate all functionality following
             #the first "||" below with new exception handlers resembling
-            #::func_.die_of_prototype(). However, such handlers should accept
+            #::func_.die_of_cause(). However, such handlers should accept
             #function names rather than prototypes; given the former, such handlers
             #may losslessly obtain the latter by calling the corresponding setter.
             #FUXME: O.K.; we've now drafted
@@ -2753,7 +2816,7 @@ function declare_function_with_stdin() {
     #current logic and variables *SHOULD* suffice. "Hey, ho! Off and away we go."
 
             # if (( args_is_variadic && arg_count_min != arg_count_max )) {
-            #     ::func_.die_of_prototype 'accepts both optional and variadic arguments'
+            #     ::func_.die_of_cause 'accepts both optional and variadic arguments'
             # }
 
 # and increment the minimum argument
@@ -2883,7 +2946,7 @@ function declare_function_with_stdin() {
     # arguments, and the inverse if the current argument is variadic), the
     # current approach is considerably more intelligible.
     # if (( args_is_variadic && arg_count_min != arg_count_max )) {
-    #     ::func_.die_of_prototype 'accepts both optional and variadic arguments'
+    #     ::func_.die_of_cause 'accepts both optional and variadic arguments'
     # }
 
 # arg_index_start arg_index_end
@@ -3140,7 +3203,7 @@ function declare_function_with_stdin() {
             #     #
             #     #No need to add or track a new boolean, which is nice.
 
-            #     ::func_.die_of_prototype:die ${(e)error_prefix}' accepts both optional and variadic arguments:'${(e)error_suffix}
+            #     ::func_.die_of_cause:die ${(e)error_prefix}' accepts both optional and variadic arguments:'${(e)error_suffix}
 
             # If such argument is suffixed by both an eroteme *AND* default
             # value, print a nonfatal warning. While redundant, such edge case
@@ -3148,7 +3211,7 @@ function declare_function_with_stdin() {
 
 # error_prefix error_suffix
     #FUXME: Nonsense. Just concoct a new private exception handler -- say,
-    # :void ::func_.die_of_prototype(:string exception_message)
+    # :void ::func_.die_of_cause(:string exception_message)
 
     # Substrings prefixing and suffixing all exception messages thrown below.
     # For efficiency, require such strings be expanded below with parameter
