Subtle bug fixes.
Oh, we are veritably crushin' 'em left and right.

diff --git a/src/zeshy/os/gnu-linux/distro/exherbo b/src/zeshy/os/gnu-linux/distro/exherbo
--- a/src/zeshy/os/gnu-linux/distro/exherbo
+++ b/src/zeshy/os/gnu-linux/distro/exherbo
@@ -23,69 +23,27 @@ CAVE_OPTIONS_UNSAFE=(
     "--permit-old-version '*/*'"
 )
 
-#FIXME: Remove.
-export INQUISITIO_OPTIONS="\
---log-level warning \
---matcher pcre \
-"
-
-#FIXME: Remove.
-# Note that default command-line arguments for Paludis are defined via the
-# ${PALUDIS_OPTIONS} environment variable, so as to expose these arguments to
-# these aliases and functions as well as dependent wrappers.
-export PALUDIS_OPTIONS="\
---continue-on-failure if-satisfied \
---dl-blocks accumulate \
---dl-circular error \
---dl-downgrade warning \
---dl-new-slots always \
---dl-reinstall never \
---dl-reinstall-scm never \
---dl-reinstall-targets auto \
---dl-suggested show \
---dl-upgrade always \
---log-level warning \
---multitask \
---show-reasons summary \
---show-use-descriptions all \
---show-package-descriptions new \
---with-unused-dependencies \
-"
-
 # ....................{ ALIASES                            }....................
-alias cav1="cave-install-lazy --preserve-world"
-alias cavfc="cave fix-cache"
-alias cavfl="cave-fix-linkage"
-alias cavn="cave-news"
+alias cav1="cave_install_lazy --preserve-world"
+alias cavar="cave_add_repository"
+alias cavfc="cave fix_cache"
+alias cavfl="cave_fix_linkage"
+alias cavn="cave_news"
 alias cavo="cave owner"
 alias cavs="cave show"
 alias cavse="cave search"
 alias cavsy="cave sync"
-alias cavi="cave-install-complete"
-alias cavil="cave-install-lazy"
-alias cavilu="cave-install-lazy-unsafely"
-alias caviu="cave-install-unsafely"
-alias cavr="cave-reinstall"
-alias cavru="cave-reinstall-unsafely"
-alias cavu="cave-uninstall"
-alias cavwr="cave-world-remove"
+alias cavi="cave_install_complete"
+alias cavil="cave_install_lazy"
+alias cavilu="cave_install_lazy_unsafely"
+alias caviu="cave_install_unsafely"
+alias cavr="cave_reinstall"
+alias cavru="cave_reinstall_unsafely"
+alias cavu="cave_uninstall"
+alias cavwr="cave_world_remove"
 alias ec="eclectic"
 alias ecci="eclectic config interactive"
 alias ecrc="eclectic rc"
-alias pal="paludis"
-alias pali="paludis --install"
-alias palo="paludis --owner"
-alias pals="paludis --sync"
-alias palu="paludis --uninstall"
-alias palq="paludis-query"
-alias palar="paludis-add-repository"
-alias palib="pali --dl-blocks discard"
-alias palip="pali --pretend"
-alias palit="palric; pali"
-alias palupuu="palu --permit-unsafe-uninstalls"
-alias palsedr="paludis-sed-recursive"
-alias palisupi="paludis-resume-install"
-alias palisupt="paludis-resume-test"
 
 # ....................{ ECLECTIC                           }....................
 function eclectic_java_select_gcj() { set_eclectic_jdk gcj }
@@ -115,42 +73,51 @@ get_eclectic_jdk_name() {
 }
 
 # ....................{ CAVE                               }....................
-cave-fix-linkage() {
+# void cave_add_repository(char *repository_name)
+#
+# Add the passed repository name to the set of all currently configured
+# repositories, then synchronize that repository.
+cave_add_repository() {
+    [[ ${#} -eq 1 ]] || die 'expected exactly one repository name'
+    try cave resolve repository/"${1}" -x
+}
+
+cave_fix_linkage() {
     try cave fix-linkage --execute --\
         "--permit-downgrade '*/*'"\
         "--permit-old-version '*/*'"\
         "${CAVE_OPTIONS[@]}" "${@}"
 }
 
-cave-install-complete() {
+cave_install_complete() {
     try cave resolve --complete --execute "${CAVE_OPTIONS[@]}" "${@}"
 }
 
-cave-install-lazy() {
+cave_install_lazy() {
     try cave resolve --lazy --execute "${CAVE_OPTIONS[@]}" "${@}"
 }
 
-cave-install-lazy-unsafely() {
+cave_install_lazy_unsafely() {
     try cave resolve --lazy --execute "${CAVE_OPTIONS_UNSAFE[@]}" "${@}"
 }
 
-cave-install-unsafely() {
-    cave-install-complete "${CAVE_OPTIONS_UNSAFE[@]}" "${@}"
+cave_install_unsafely() {
+    cave_install_complete "${CAVE_OPTIONS_UNSAFE[@]}" "${@}"
 }
 
-cave-reinstall() {
+cave_reinstall() {
     try cave resolve --everything --execute "${CAVE_OPTIONS[@]}" "${@}"
 }
 
-cave-reinstall-unsafely() {
-    try cave-reinstall "${CAVE_OPTIONS_UNSAFE[@]}" "${@}"
+cave_reinstall_unsafely() {
+    try cave_reinstall "${CAVE_OPTIONS_UNSAFE[@]}" "${@}"
 }
 
-cave-uninstall() {
+cave_uninstall() {
     try cave uninstall --execute "${CAVE_OPTIONS[@]}" "${@}"
 }
 
-cave-news() {
+cave_news() {
     page eclectic news read all
 }
 
@@ -188,6 +155,51 @@ cave-world-remove() {
     done
 }
 
+#FIXME: Obsolete.
+#alias pal="paludis"
+#alias pali="paludis --install"
+#alias palo="paludis --owner"
+#alias pals="paludis --sync"
+#alias palu="paludis --uninstall"
+#alias palq="paludis-query"
+#alias palar="paludis-add-repository"
+#alias palib="pali --dl-blocks discard"
+#alias palip="pali --pretend"
+#alias palit="palric; pali"
+#alias palupuu="palu --permit-unsafe-uninstalls"
+#alias palsedr="paludis-sed-recursive"
+#alias palisupi="paludis-resume-install"
+#alias palisupt="paludis-resume-test"
+
+#FIXME: Remove.
+#export INQUISITIO_OPTIONS="\
+#--log-level warning \
+#--matcher pcre \
+#"
+
+#FIXME: Remove.
+# Note that default command-line arguments for Paludis are defined via the
+# ${PALUDIS_OPTIONS} environment variable, so as to expose these arguments to
+# these aliases and functions as well as dependent wrappers.
+#export PALUDIS_OPTIONS="\
+#--continue-on-failure if-satisfied \
+#--dl-blocks accumulate \
+#--dl-circular error \
+#--dl-downgrade warning \
+#--dl-new-slots always \
+#--dl-reinstall never \
+#--dl-reinstall-scm never \
+#--dl-reinstall-targets auto \
+#--dl-suggested show \
+#--dl-upgrade always \
+#--log-level warning \
+#--multitask \
+#--show-reasons summary \
+#--show-use-descriptions all \
+#--show-package-descriptions new \
+#--with-unused-dependencies \
+#"
+
 # ....................{ PALUDIS                            }....................
 #FIXME: Rename all uses of "paludis-" with "exherbo-", and all uses of "pal"
 #with "exh". (This generalizes the move away from Paludis to Cave.)
@@ -202,22 +214,22 @@ cave-world-remove() {
 #
 # That is, it expects the repository to be registered under either the
 # "::unavailable" or "::unavailable-unofficial" pseudo-repositories. 
-paludis-add-repository() {
-    [[ "${#}" -eq 1 ]] || die "expected exactly one repository name"
-    cave resolve repository/"${1}" --execute
-}
-
-paludis-update-world() {
-    paludis --install --dl-reinstall if-use-changed world
-}
-
-paludis-sed-recursive() {
-    [[ "${#}" -eq 2 ]] ||
-        die "expected exactly one search pattern and one replace pattern"
-
-    set_git_globals
-    mv-pcre -cr "${1}" "${2}" "${GIT_ROOT}"/{exlibs,packages}/**/*.{exlib,exheres-0}
-}
+#paludis-add-repository() {
+#    [[ "${#}" -eq 1 ]] || die "expected exactly one repository name"
+#    cave resolve repository/"${1}" --execute
+#}
+#
+#paludis-update-world() {
+#    paludis --install --dl-reinstall if-use-changed world
+#}
+#
+#paludis-sed-recursive() {
+#    [[ "${#}" -eq 2 ]] ||
+#        die "expected exactly one search pattern and one replace pattern"
+#
+#    set_git_globals
+#    mv-pcre -cr "${1}" "${2}" "${GIT_ROOT}"/{exlibs,packages}/**/*.{exlib,exheres-0}
+#}
 
 # Resume a failed install from the install phase, rather than from the
 # beginning. This is generally safe - but should be used with caution. Also,
@@ -226,37 +238,37 @@ paludis-sed-recursive() {
 # that the vanilla install command does not already do. Most saliently, this
 # "Resume command" does not resume a failed install from the install phase. It
 # bloody starts over! This has bit me several times, but no more.
-paludis-resume-install() {
-    utter "forcefully skipping to the install phase for '$1'..."
-    paludis --install --skip-until-phase setup --abort-at-phase unpack "$1"
-    paludis --install --skip-until-phase install "$1"
-}
+#paludis-resume-install() {
+#    utter "forcefully skipping to the install phase for '$1'..."
+#    paludis --install --skip-until-phase setup --abort-at-phase unpack "$1"
+#    paludis --install --skip-until-phase install "$1"
+#}
 
 # Resume a failed install from the install phase, rather than from the
 # beginning. This is generally safe - but should be used with caution.
-paludis-resume-test() {
-    utter "forcefully skipping to the test phase for '$1'..."
-    paludis --install --skip-until-phase setup --abort-at-phase unpack "$1"
-    paludis --install --skip-until-phase test "$1"
-}
+#paludis-resume-test() {
+#    utter "forcefully skipping to the test phase for '$1'..."
+#    paludis --install --skip-until-phase setup --abort-at-phase unpack "$1"
+#    paludis --install --skip-until-phase test "$1"
+#}
 
 # Recache the ./Manifest file for some ebuild.
 # 
 # Note that, if that ebuild is fetch restricted (i.e., it contains a line
 # RESTRICT="fetch" and supplies a "pkg_nofetch" function), you may need to
 # disable the fetch restriction before calling this function.
-paludis-recache-manifest() {
-    utter "forcefully recaching Manifest entries for '$1'..."
-    ebuild --force "$1" manifest
-}
+#paludis-recache-manifest() {
+#    utter "forcefully recaching Manifest entries for '$1'..."
+#    ebuild --force "$1" manifest
+#}
 
 # Uninstall all unused ebuilds or exheres.
-paludis-uninstall-unused() {
-    utter "pretending to uninstall unused..."
-    paludis --uninstall-unused --pretend
-    utter "uninstalling unused..."
-    paludis --uninstall-unused
-}
+#paludis-uninstall-unused() {
+#    utter "pretending to uninstall unused..."
+#    paludis --uninstall-unused --pretend
+#    utter "uninstalling unused..."
+#    paludis --uninstall-unused
+#}
 
 #FIXME: Consider implementing an equivalent function to:
 # qlist ${EXHERES_NAME} | xargs scanelf -L -n -q -F '%n #F' | tr , ' ' | xargs qfile -C | sort -u
