Improved numerous minor subsystems.
I'm afraid it's "rather late": the moon dath wane and so too my exuberance.
But be certified! What lies within is undoubtedly a smooth pleasant commit.

diff --git a/src/always/variable/string/line b/src/always/variable/string/line
--- a/src/always/variable/string/line
+++ b/src/always/variable/string/line
@@ -28,8 +28,8 @@ Never trust anything that bleeds for four days but doesn't die.
 ==========================================
 /---
 function is_string_line() {
-    # Validate passed arguments.
-    die_unless_args_2 'expected one string and one line'
+    # Validate sanity.
+    die_unless_args_2 'Expected one string and one line.'
 
     # Test such string. Dismantled, this is:
     #
@@ -72,8 +72,8 @@ When I say I want to abolish work, I mean just what I say, but I want to
 ==========================================
 /---
 function get_string_line() {
-    # Validate passed arguments.
-    die_unless_args_2 'expected one string and one line number'
+    # Validate sanity.
+    die_unless_args_2 'Expected one string and one line number.'
     string text="${1}" line_number=${2} glob_line
     die_unless_integer_nonzero "${line_number}"
 
@@ -134,9 +134,9 @@ wall of the monoculture. This is the future. This is what we built.
 ==========================================
 /---
 function get_string_lines() {
-    # Validate passed arguments.
+    # Validate sanity.
     die_unless_args_3\
-        'expected one string, one start line number, and one end line number'
+        'Expected one string, one start line number, and one end line number.'
     string line_number_start="${2}" line_number_end="${3}"
     list lines
 
@@ -174,19 +174,23 @@ Get the total number of lines in the passed strings: e.g.,
 ==========================================
 /---
 function get_string_line_count() {
-    die_unless_args 'expected one or more strings'
+    die_unless_args 'Expected one or more strings.'
     list lines; lines=( "${(f)*}" )
     get_list_size lines
 }
 
 # ....................{ NUMBERERS                          }....................
+#FIXME: Poor nomenclature. Such functions will be rarely called and hence
+#should be accessible as either getters or converters -- say,
+#get_string_lines_numbered() (which coincides fairly nicely with existing
+#get_string_line() nomenclature.
 declare_function_with_stdin <<'/---'
-string number_string_lines(string text1, string text2, ...)
+string number_string_lines(string text1, ...)
 
 Prefix each line of the passed strings with such line's number.
 /---
 function number_string_lines() {
-    die_unless_args 'expected one or more strings'
+    die_unless_args 'Expected one or more strings.'
     output_string "${@}" |
         run_code_with_options 'run_code_paged command nl' ZESHY_OPTIONS_NL
 }
@@ -201,14 +205,14 @@ the passed line number. Since `nl` supports no highlighting, this function
 accepts no `nl`-specific options.
 /---
 function number_string_lines_highlighting() {
-    # Validate passed arguments.
-    die_unless_args_2 'expected one string and one line number'
+    # Validate sanity.
+    die_unless_args_2 'Expected one string and one line number.'
     string text="${1}" line_index="${2}"
     integer line_count
     die_unless_integer_positive "${line_index}"
 
     #FIXME: Actually, it's trivial to convert negative to positive line numbers.
-    # Validate passed arguments. Negative line numbers are impermissible.
+    # Validate sanity. Negative line numbers are impermissible.
     line_count="$(get_string_line_count "${text}")"
 #   print_message "line length: ${line_count}"
     (( 1 <= line_index && line_index <= line_count )) or
@@ -266,34 +270,11 @@ function remove_string_line_duplicates() {
     #
     # * "f", splitting passed strings into lines.
     # * "u", excluding duplicate lines.
-    die_unless_args 'expected one or more strings'
-    join_strings_on_newline "${(uf)*}"    # this... this is ridiculous
+    die_unless_args 'Expected one or more strings.'
+    join_strings_on_newline "${(uf)*}"   # this... this is ridiculous
 }
 
 # ....................{ ITERATORS                          }....................
-#FIXME: O.K.; this is really a general comment on "eval" statements, but this is
-#the function in which the issue first arose. When zsh encounters a parse error
-#in such statements, it simply prints a context-less line to stderr resembling:
-#
-#    for_string_lines:19: bad math expression: illegal character: "
-#
-#Unsurprisingly, this is pretty much useless. Hence, we pretty much need to call
-#run_code() rather than "eval". Then, we need to substantially improve the
-#run_code() implementation to instead tee stderr to a string local and,
-#after executing such command, test such local. If such local is nonempty and
-#matches the following glob pattern:
-#
-#    (#b)($'\n'|)"$(get_caller):([[:digit:]]##): ([^$'\n']##)"($'\n'|)
-#
-#Then ${match[1]} supplies the failing line number and ${match[2]} the error
-#message. Since such line number is relative to the caller function rather than
-#"eval" statement by default under zsh, run_code() needs to locally disable
-#such shell option for the duration of such "eval" statement, ensuring such line
-#number is relative to the "eval" statement instead.
-#
-#If such glob matches, throw a well-formatted exception, calling
-#number_string_lines_highlighting(). (Not the best nomenclature, incidentally.)
-
 declare_function_with_stdin <<'/---'
 string for_string_lines(
     string text,
@@ -321,13 +302,13 @@ Worse, you cling with might and main to such absurdities as 'race,'
 ==========================================
 /---
 function for_string_lines() {
-    # Validate passed arguments.
+    # Validate sanity.
     die_unless_args_2_to_3\
-        'expected one string, optional line string name, and one command'
+        'Expected one string, optional line string name, and one command.'
     string text__fsl="${1}" line_string_name__fsl='LINE' command__fsl="${@[-1]}"
     is_args_3 and line_string_name__fsl="${2}"
     die_unless_variable_name "${line_string_name__fsl}"
-    die_unless_string_nonempty "${command__fsl}" 'expected nonempty command'
+    die_unless_string_nonempty "${command__fsl}" 'Expected nonempty command.'
 
     # Currently matched line.
     string ${line_string_name__fsl}
@@ -343,8 +324,7 @@ function for_string_lines() {
         # Split such string into lines and iterate such lines. For efficiency,
         # inline such splitting, evaluate the loop once rather than
         # on each loop iteration, and capture each line to ${MATCH}.
-        string eval__fsl='
-        for '${line_string_name__fsl}' ("${(f)text__fsl}") {
+        string eval__fsl='for '${line_string_name__fsl}' ("${(f)text__fsl}") {
             '${command__fsl}'
         }'
 #       output_string "for_string_lines (short text):${ZESHY_ASCII_NEWLINE}${eval__fsl}"
@@ -352,8 +332,7 @@ function for_string_lines() {
     # Else, dynamically iterate PCRE line matches.
     } else {
 #       output_call_stack
-        string eval__fsl='
-        '${line_string_name__fsl}'="${MATCH}"
+        string eval__fsl=${line_string_name__fsl}'="${MATCH}"
         '${command__fsl}
 #       output_string "for_string_lines (long text):${ZESHY_ASCII_NEWLINE}${eval__fsl}"
 
@@ -363,6 +342,75 @@ function for_string_lines() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+#FUXME: O.K.; this is really a general comment on "eval" statements, but this is
+#the function in which the issue first arose. When zsh encounters a parse error
+#in such statements, it simply prints a context-less line to stderr resembling:
+#
+#    for_string_lines:19: bad math expression: illegal character: "
+#
+#Unsurprisingly, this is pretty much useless. Hence, we pretty much need to call
+#run_code() rather than "eval". Then, we need to substantially improve the
+#run_code() implementation to instead tee stderr to a string local and,
+#after executing such command, test such local. If such local is nonempty and
+#matches the following glob pattern:
+#
+#    ($'\n'|)"$(get_caller):"(#b)(<->##)': '([^$'\n']##)"($'\n'|)
+#
+#Then ${match[1]} supplies the failing line number and ${match[2]} the error
+#message. Since such line number is relative to the caller function rather than
+#"eval" statement by default under zsh, run_code() needs to locally disable
+#shell option "EVAL_LINENO" for the duration of such "eval" statement, ensuring
+#such line number is relative to the "eval" statement instead. Naturally,
+#replace $'\n' with ${ZESHY_ASCII_NEWLINE}.
+#
+#If such glob matches, throw a well-formatted exception, calling
+#number_string_lines_highlighting(). (Not the best nomenclature, incidentally.)
+#FUXME: Hmm. If the zsh parser behaves sensibly, any syntax error should be
+#caught... Interesting. O.K.; I tested this. As expected, zsh reports top-level
+#syntax errors before executing anything: e.g.,
+#
+#    >>> eval '
+#    ...     print ko 1>&2
+#    ...     [[ "ohoh" == "hoho" ]] or print "okok" 1>&2'
+#    (eval):3: condition expected: ===
+#    TRAPZERR() failed with exit status 1
+#     TRAPZERR() { /bin/zsh: 22 }
+#
+#Note the "ko" is *NOT* printed. However, zsh reports sub-level syntax errors
+#(e.g., glob errors) at the actual point of execution: e.g.,
+#
+#    >>> eval '
+#    ...     print ko 1>&2
+#    ...     [[ "ohoh" == (#zzz)"hoho" ]] or print "okok" 1>&2'
+#    ko
+#    (eval):3: (eval):3: bad pattern: (#zzz)hoho
+#    TRAPZERR() failed with exit status 1
+#     TRAPZERR() { /bin/zsh: 22 }
+#
+#Hence, the prior regular expression is substantially correct: an invalid syntax
+#error may be raised at any point.
+#FUXME: When implementing the above approach, it'd be nice to get the
+#redirection right. First, I'll note that we should redirect the eval() call
+#rather than the evaluated code to stderr. But that doesn't quite get us there.
+#Ideally, ... oh, heck. It's probably the best we can do without going into the
+#coprocess zone though, isn't it?
+#FUXME: O.K.; we probably don't want to impose such logic on *EVERY* run_code()
+#call. While such logic is demonstrably great, it's somewhat inefficient as well
+#as (more importantly) requiring capturing stderr from a command executed in the
+#current shell -- which, as we well know, requires the coprocess. Hence, we want
+#a new function run_code_validated() (or some such) itself calling
+#run_code_and_set_string_to_stderr() and then matching on the contents of such
+#string variable.
+#FUXME: run_code_validated() is decent, but how about...
+#FUXME: Interesting. While I still admit the prior idea to be relevant, it's not
+#quite as relevant as it otherwise could be. Why? Because zsh *ALREADY* signals
+#SIGZERR() for pretty much every syntax error I tested with only one exception.
+#Guess the exception! That's right, the very cause of this entire line of
+#reasoning: double-quotes in math expressions. Given the heavyweight nature of
+#this idea, it hardly seems reasonable to implement such logic merely to catch
+#such errors, particularly when zsh guaranteeably catches everything else. Pass
+#for now, I should think.
+
 #...    "This is what we wanted. It must have been. Because we all had the
 #...     fucking choice, didn't we? It is only our money that allows commercial
 #...     culture to flower. If we didn't want to live like this, we could have
@@ -407,7 +455,7 @@ function for_string_lines() {
 #...     the methods of the Inquisition to a new flowering."
 # for use by such command
 #   append_stdin_piped_to_args
-    # Validate passed arguments, treating piped input as the passed string.
+    # Validate sanity. treating piped input as the passed string.
 #   string __error_message__='expected one list name and one string'\
 #       __text__ list_name
 #   if is_stdin_pipe; then
@@ -424,7 +472,7 @@ function for_string_lines() {
 #   set_list_to_evaluation ${list_name} '${(f)__text__}'
 #   string text="${1}" line="${2}"
 #   is "${text}" == (|*$'\n')"${line}"(|$'\n'*) si
-    # Validate passed arguments, treating piped input as the passed string.
+    # Validate sanity. treating piped input as the passed string.
 #   string text line error_message='expected one string and one line'
 #   if is_stdin_pipe; then
 #       die_unless_arg "${error_message}"
diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -398,7 +398,7 @@ function TRAPZERR() {
 
     # Handle such exception and return such command's exit status, mimicking the
     # action of "setopt ERR_RETURN". (See "man zshoptions" for further details.)
-    die_with_exit_status "${exit_status}"
+    die_with_status "${exit_status}"
     return ${exit_status}
 }
 
@@ -447,10 +447,10 @@ function die() {
     (( ${exit_status} == 0 )) && exit_status=1
 
     # Handle such exception.
-    die_with_exit_status "${@}" "${exit_status}"
+    die_with_status "${@}" "${exit_status}"
 
     #FIXME: Suffix the exception name by the name of the function directly
-    #responsible for throwing this exception. See curse_exception_exit_status()
+    #responsible for throwing this exception. See curse_exception_status()
     #for simple logic getting this function name.
 
     # If canonical function throw() is defined, unwind the current call stack,
@@ -468,14 +468,14 @@ function die() {
 }
 
 ZESHY_CORE_HELP_FUNCTIONS+='
-string die_with_exit_status(
+string die_with_status(
     string error_message1 = "", string error_message2, ..., integer exit_status)
 
 Print the passed exception message (defaulting to the empty string) and related
 metadata requested by the current user to standard error. See die() for further
 details, which calls this function to perform such printing.
 '
-function die_with_exit_status() {
+function die_with_status() {
     # Redirect all output printed below to standard error. Yes, a single
     # suffixing "} 1>&2" actually suffices. You rock, zsh! (Sometimes.)
     {
@@ -488,7 +488,7 @@ function die_with_exit_status() {
         # do so efficiently, search from the end (i.e., root) of such stack; if
         # the first matching caller is not the first, a witch! As below, return
         # success to avoid triggering TRAPZERR and hence another exception.
-        if (( ${funcstack[(I)die_with_exit_status]} != 1 )) {
+        if (( ${funcstack[(I)die_with_status]} != 1 )) {
             # Print a synopsis of such exception.
             print
             print "zeshy: exception handler threw exception: ${*}"
@@ -530,8 +530,8 @@ function die_with_exit_status() {
 
         # Print a description of the passed non-zero exit status.
         # If print_exception_message() is defined, call such function.
-        if { typeset -f print_error_exit_status &>/dev/null } {
-            print_error_exit_status "${exit_status}"
+        if { typeset -f print_error_status &>/dev/null } {
+            print_error_status "${exit_status}"
         # Else, print such message with a one-liner.
         } else {
             print
@@ -1683,7 +1683,7 @@ return 0
 #   fi
 
 #       print 1>&2  # print a blank line to standard error
-#       print_exception_exit_status "${1}"
+#       print_exception_status "${1}"
 #then ZESHY_IS_LOADING=
 #print "zeshy: ZESHY_IS_LOADING=${ZESHY_IS_LOADING}"
 
@@ -2130,12 +2130,12 @@ return 0
 #   return $(( ${exit_status} + 128 + ${signal_number} ))
 
     # Die with the prior return code.
-#   die_with_exit_status ${exit_status}
+#   die_with_status ${exit_status}
 
-# void die_with_exit_status(int exit_status = 1)
+# void die_with_status(int exit_status = 1)
 #
 # Exit the currently executed script or function with the passed return code.
-#die_with_exit_status() {
+#die_with_status() {
 #   for ((i = 1; i <= ${#funcstack}; i++)) { print "${i}: ${funcstack[${i}]}" }
 #   if is_interactive; then
 #   then print 'throwing exception'; throw ZeshyException
@@ -2144,7 +2144,7 @@ return 0
     # login shell, unwind the call stack; otherwise, kill the current process.
 #    if is_interactive
 #    then throw ZeshyException
-#    else exit ${1:-${ZESHY_EXIT_STATUS_FAILURE}}
+#    else exit ${1:-${ZESHY_STATUS_FAILURE}}
 #    fi
 #    print 'still here!'
 #}
@@ -2170,7 +2170,7 @@ return 0
     # command. This effectively enables "set -e" (i.e., the ERR_EXIT option,
     # terminating the current shell on SIGZERR signals).
 #   eval 'throw ZeshyException'; return ${exit_status}
-#   die_with_exit_status ${exit_status}
+#   die_with_status ${exit_status}
 
 # * Uhm; how did I never see this? zsh supports loop syntax resembling:
 #   for d (../**/*) {
@@ -2381,10 +2381,10 @@ return 0
 #    run_as_superuser "${@}" or die
 #}
 
-# int get_last_exit_status(void)
+# int get_last_status(void)
 # 
 # Return the return code returned by the previous command.
-#alias get_last_exit_status='is_ok'
+#alias get_last_status='is_ok'
 
 # bool is_ok(void)
 #
@@ -2392,9 +2392,9 @@ return 0
 #is_ok() {
 #    # Cache the prior command's return code, as our initial sanity check on
 #    # arguments replaces this code with its own.
-#    integer prior_command_exit_status=${?}
+#    integer prior_command_status=${?}
 #    die_unless_no_args
-#    return ${prior_command_exit_status}
+#    return ${prior_command_status}
 #}
 
 # bool is_error(void)
@@ -2403,9 +2403,9 @@ return 0
 #is_error() {
 #    # Cache the prior command's return code, as our initial sanity check on
 #    # arguments replaces this code with its own.
-#    integer prior_command_exit_status=${?}
+#    integer prior_command_status=${?}
 #    die_unless_no_args
-#    is ${prior_command_exit_status} -ne ${ZESHY_EXIT_STATUS_SUCCESS} si
+#    is ${prior_command_status} -ne ${ZESHY_STATUS_SUCCESS} si
 #}
 
 # string canonicalize_path_nonfatal(string pathname)
@@ -2512,9 +2512,9 @@ return 0
 #die_unless_ok() {
 #    # Cache the prior command's return code, as our initial sanity check on
 #    # arguments replaces this code with its own.
-#    integer prior_command_exit_status=${?}
+#    integer prior_command_status=${?}
 #    die_unless_one_arg 'expected exactly one error message'
-#    is ${prior_command_exit_status} -eq ${ZESHY_EXIT_STATUS_SUCCESS} si or die "${1}"
+#    is ${prior_command_status} -eq ${ZESHY_STATUS_SUCCESS} si or die "${1}"
 #}
 
 # void say_import(string script_name)
@@ -2558,7 +2558,7 @@ return 0
 # 
 # Return from the current function with failure if the previous command or
 # function also returned with failure.
-#alias fail_if_previous_command_failed="is_ok || return ${ZESHY_EXIT_STATUS_FAILURE}"
+#alias fail_if_previous_command_failed="is_ok || return ${ZESHY_STATUS_FAILURE}"
 
 #; ZESHY_IMPORTED_PATH_TO_MTIME=( )
 #   typeset -Ax ZESHY_IMPORTED_PATH_TO_MTIME; ZESHY_IMPORTED_PATH_TO_MTIME=( )
@@ -2579,7 +2579,7 @@ return 0
 
 #   pcre_compile "${1}" || die "\"${1}\" not a valid regular expression"
 #   pcre_match "${2}" || return ${?}
-#   return ${ZESHY_EXIT_STATUS_SUCCESS}
+#   return ${ZESHY_STATUS_SUCCESS}
 
 # This function returns success 
 # If this regular expression matched at least one group, this function returns
@@ -2593,10 +2593,10 @@ return 0
     # here, since setting a local variable always forces the return code to 0
     # (i.e., success). 
 #   if [[ "${command_path}" == *" not found" ]]; then
-#       return ${ZESHY_EXIT_STATUS_FAILURE}
+#       return ${ZESHY_STATUS_FAILURE}
 #   else
 #       echo "${command_path}"
-#       return ${ZESHY_EXIT_STATUS_SUCCESS}
+#       return ${ZESHY_STATUS_SUCCESS}
 #   fi
 
     # O.K., this is tricksy: if the eventual caller explicitly quote-protected
