Eliminated the top-level "global" component.
This commit has been quite a long time coming. It feels fairly good to
have sufficiently deferred this aspect of Zeshy startup to digest
compilation. Onward to the elimination of "alias"! Yeee-ha!

diff --git a/src/always/terminal/output/pager b/src/always/terminal/output/pager
--- a/src/always/terminal/output/pager
+++ b/src/always/terminal/output/pager
@@ -20,6 +20,25 @@ function get_pager_command() {
 }
 
 # ....................{ PRINTERS                           }....................
+#FIXME: It'd be great to implement the following swag idea:
+#
+#* When not paging, to visually demarcate wrapped lines (ideally with color? or
+#  perhaps simply with a simple prefix). So, rather than printing:
+#udev                 /dev                      devtmpfs     rw nosuid relatime size=10240k nr_in
+#odes=497142 mode=755
+#  Instead, printing:
+#udev                 /dev                      devtmpfs     rw nosuid relatime size=10240k nr_in
+# ^-> odes=497142 mode=755
+#  Or perhaps simply:
+#udev                 /dev                      devtmpfs     rw nosuid relatime size=10240k nr_in
+# ...odes=497142 mode=755
+#  Or the slightly cleverer:
+#udev                 /dev                      devtmpfs     rw nosuid relatime size=10240k nr...
+# ..._inodes=497142 mode=755
+#  Actually, no. That reads awkwardly. One "..." is sufficient, I should think.
+#  Happily, "yppy" already has appropriate Unicode for the former arrows. In either case, I
+#  prefer the prefixing space on the wrapped line.
+
 # string output_paged(string text1, string text2, ...)
 #
 # If the passed string exceeds the current terminal's dimensions, print such
@@ -41,6 +60,12 @@ function output_paged_if_exceeds_terminal_dimensions() {
     prepend_args_with_piped_input
     die_unless_args 'expected at least one string'
     string text="${*}"
+
+    # If not called from a terminal, output such string without paging.
+    is_shell_terminal or {
+        output "${@}"
+        return_true
+    }
 
     # List of output lines.
     list lines; set_list_to_string_lines lines "${text}"
@@ -104,27 +129,8 @@ function output_paged_if_exceeds_terminal_dimensions() {
 }
 
 # ....................{ RUNNERS                            }....................
-#FIXME: It'd be great to implement the following swag idea:
-#
-#* When not paging, to visually demarcate wrapped lines (ideally with color? or
-#  perhaps simply with a simple prefix). So, rather than printing:
-#udev                 /dev                      devtmpfs     rw nosuid relatime size=10240k nr_in
-#odes=497142 mode=755
-#  Instead, printing:
-#udev                 /dev                      devtmpfs     rw nosuid relatime size=10240k nr_in
-# ^-> odes=497142 mode=755
-#  Or perhaps simply:
-#udev                 /dev                      devtmpfs     rw nosuid relatime size=10240k nr_in
-# ...odes=497142 mode=755
-#  Or the slightly cleverer:
-#udev                 /dev                      devtmpfs     rw nosuid relatime size=10240k nr...
-# ..._inodes=497142 mode=755
-#  Actually, no. That reads awkwardly. One "..." is sufficient, I should think.
-#  Happily, "yppy" already has appropriate Unicode for the former arrows. In either case, I
-#  prefer the prefixing space on the wrapped line.
-
 # string run_paged(
-#   string command_name, string command_arg1, string command_arg2, ...)  --OR--
+#   string command_name, string command_arg1, string command_arg2, ...)
 #
 # Run the passed command with standard output and error piped to the current
 # pager if such output exceeds either the current terminal height or width or as
@@ -137,32 +143,45 @@ function output_paged_if_exceeds_terminal_dimensions() {
 # interface woes, this function immediately prints all output as received from
 # the passed command to standard error prior to paging such output, as needed.
 function run_paged() {
-    # If not called from a terminal, run the passed command without paging.
+    # If not called from a terminal, run such command without paging.
     if not is_shell_terminal; then
         run "${@}"
-    # If passed piped input and no arguments, simply print such output as is.
-    # If not attached to a terminal, run the passed command as is and
-    # immediately return without paging.
+    # If passed piped input and no arguments, output such input without paging.
     elif is_no_args and is_piped_input; then
-        string output; set_string_to_piped_input output
-        output_paged "${output}"
+        output_paged "$(get_piped_input)"
     # Otherwise, run the passed command with redirection. Dismantled, this is:
     #
     # * "1>&1", preserving standard output prior to its subsequent redirection.
     # * "1>&2", redirecting standard output to error. Since command substitution
     #   only captures the former, this immediately prints all output produced by
     #   running such command.
+    # * "2>&1", redirecting standard error to output. Since command substitution
+    #   only captures the latter, only such redirection captures standard error.
     # * "or true", ignoring such function call when returning false, since the
     #   prior "1>&2" redirection already successfully printed such output.
+    #
+    # Avoid the following seemingly efficient and certainly simpler alternative,
+    # which unfortunately discards non-zero exit status from run():
+    #
+    #   run "${@}" 1>&1 1>&2 | output_paged_if_exceeds_terminal_dimensions or true
     else
         die_unless_args 'expected one command'
 #       output "run_paged: ${@}..."
-        run "${@}" 1>&1 1>&2 | output_paged_if_exceeds_terminal_dimensions or
-            true
+        output_paged_if_exceeds_terminal_dimensions\
+            "$(run "${@}" 1>&1 1>&2 2>&1)" or true
     fi
 }
 
 # --------------------( WASTELANDS                         )--------------------
+        #FIXME: Not quite right. Try prefixing or suffixing 2>&1.
+        #FIXME: Woops. This erroneously discards non-zero exit status from
+        #run(). We only want to discard non-zero exit status from
+        #output_...(). Hmmmm. Frak this. Revert to the prior logic, which
+        #actually worked perfectly.
+#       run "${@}" 1>&1 1>&2 | output_paged_if_exceeds_terminal_dimensions or
+#           true
+#       string output; set_string_to_piped_input output
+#       output_paged "${output}"
 #       line_sans_ansi_width="$(get_string_length "$(remove_ansi_color_codes "${line}")")"
 #       text_width=${#$(remove_ansi_color_codes "${line}")}
     # * "2>&1", redirecting standard error to output. Since command substitution
