Corrected Zeshy Patch regressions.
Notably, the "diff" binary returns non-zero exit status 1 on success.
This utterly nonsensical decision complicates patch handling
considerably more that is logical. Up the bit irons, plainly insensate
"diff" dastards!

diff --git a/src/autoload/always/file/content/patch b/src/autoload/always/file/content/patch
--- a/src/autoload/always/file/content/patch
+++ b/src/autoload/always/file/content/patch
@@ -1,5 +1,5 @@
 #!/usr/bin/env zsh
-# ====================[ content                            ]====================
+# ====================[ patch                              ]====================
 #
 # --------------------( SYNOPSIS                           )--------------------
 # Zeshy File Patch, handling patch files (i.e., files containing "diff" output).
@@ -113,11 +113,32 @@ make_patch_file() {
 #   utter "removing \"${patch_filename}\"..."
     remove_file_if_found "${patch_filename}"
 
-    # Difference.
-    interactively utter\
-        "from \"${old_pathname}\" to \"${new_pathname}\" into \"${patch_filename}\"..."
-    run_with_options diff 'zeshy_diff_options'\
-        "${old_pathname}" "${new_pathname}" > "${patch_filename}"
+    # Make the passed patch. If interactive, redirect standard output to error
+    # to assist the current user review the patch. Oddly, "diff" returns exit
+    # status 1 on successfully differencing non-identical files (!?) and exit
+    # status 2 on fatal error. Thanks for being idiotically different, "diff".
+    #
+    # Fortunately, the return_exit_status() approach helps revise such idiocy.
+    # Unfortunately, this approach requires manually reimplementing both
+    # run_with_options() and return_exit_status() here.
+    #
+    # *crudely blows both nostrils at the "diff" authors' pale-faced cupidity*
+    list diff; diff=( diff "${zeshy_diff_options[@]}" )
+    if is_interactive; then
+        diff+=( "${ZESHY_DIFF_OPTIONS_IF_INTERACTIVE[@]}" )
+        utter "from \"${old_pathname}\" to \"${new_pathname}\" into \"${patch_filename}\"..."
+    else
+        diff+=( "${ZESHY_DIFF_OPTIONS_IF_NON_INTERACTIVE[@]}" )
+    fi
+
+    # Coerce non-zero exit status of 1 to 0.
+    integer diff_status
+    "${diff[@]}" "${old_pathname}" "${new_pathname}" >"${patch_filename}" |
+        cat and diff_status="${pipestatus[-2]}"
+    if (( diff_status == 1 ))
+    then return_success
+    else return ${diff_status}
+    fi
 }
 
 # char *make_patch_file_for_new_path(char *new_pathname, char *patch_filename)
@@ -146,6 +167,13 @@ make_patch_file_for_new_path() {
 }
 
 # ....................{ WASTELANDS                         }....................
+#   string redirect_to_screen
+#   and redirect_to_screen='1>&2'
+#   run_with_options diff 'zeshy_diff_options'\
+#       "${old_pathname}" "${new_pathname}"\
+#        ${redirect_to_screen} >"${patch_filename}" | true and
+#       utter ${pipestatus[@]}
+
 # function thus is intended for describing new
 # files added to a project.
 # By precedent, the old pathname in the resulting patch
