Refactored numerous getters to setters.
Refactored functions include :convert_path_to_parcel() and :canonicalize_path().
Numerous issues relating to path canonicalization and symbolic links have also
been addressed (e.g., attempting to canonicalize broken symbolic links now
throws exceptions rather than silently nooping).

diff --git a/src/00-start/00-declare/10-parcel b/src/00-start/00-declare/10-parcel
--- a/src/00-start/00-declare/10-parcel
+++ b/src/00-start/00-declare/10-parcel
@@ -125,24 +125,24 @@ typeset -g ZESHY_PARCEL_NAME
 # ....................{ EXCEPTIONS                         }....................
 function die_if_parcel() {
     (( # == 1 || # == 2 )) ||
-        die 'expected one parcel name and optional error message'
+        die 'Expected one parcel name and optional error message.'
     local parcel_name="${1}"
     is_parcel "${parcel_name}" &&
-        die "${2:-parcel \"${parcel_name}\" already declared}"
+        die "${2-Parcel \"${parcel_name}\" already declared.}"
 }
 
 function die_unless_parcel() {
     (( # == 1 || # == 2 )) ||
-        die 'expected one parcel name and optional error message'
+        die 'Expected one parcel name and optional error message.'
     local parcel_name="${1}"
     is_parcel "${parcel_name}" ||
-        die "${2:-parcel \"${parcel_name}\" undeclared}"
+        die "${2-Parcel \"${parcel_name}\" undeclared.}"
 }
 
 # ....................{ TESTERS                            }....................
 function is_parcel() {
     # See is_map_key() for further details.
-    (( # == 1 )) || die 'expected one parcel name'
+    (( # == 1 )) || die 'Expected one parcel name.'
     (( ${+ZESHY_PARCEL_NAME_TO_HELP[${1}]} ))
 }
 
@@ -152,8 +152,8 @@ function is_parcel() {
 # relegated to "always/zeshy/parcel".
 
 function set_parcel() {
-    # Validate passed arguments.
-    (( # == 1 )) || die 'expected one parcel name'
+    # Validate sanity.
+    (( # == 1 )) || die 'Expected one parcel name.'
     local parcel_name="${1}"
     die_unless_parcel "${parcel_name}"
 
@@ -162,26 +162,52 @@ function set_parcel() {
 }
 
 function set_parcel_as_script() {
-    # Validate passed arguments.
+    # Validate sanity.
 #   print -r -- "args: ${*}"
-    (( # == 1 )) || die 'expected one parcel name'
-    local script_name="${1}" parcel_name
-    [[ -f "${script_name}" ]] || die "\"${script_name}\" not a script"
+    (( # == 1 )) || die 'Expected one parcel name.'
+    local parcel_name="${1}"
+    [[ -f "${parcel_name}" ]] || die 'Script "'${parcel_name}'" not found.'
 
-    # Set the current parcel to the absolute path of such script converted into
-    # a parcel name.
-    set_parcel "$(convert_path_to_parcel "${script_name}")"
+    # Convert the absolute path of such script to a parcel name.
+    :convert_path_to_parcel parcel_name
+
+    # Set the current parcel to such name.
+    set_parcel "${parcel_name}"
 }
 
 # ....................{ CONVERTERS                         }....................
-function convert_path_to_parcel() {
-    # Validate passed arguments.
-    (( # == 1 )) || die 'expected one pathname'
-    local parcel_name="${1}"
-    [[ -e "${parcel_name}" ]] || die "\"${parcel_name}\" not found"
+#FIXME: Fix documentation, now that such function behaves completely
+#differently (i.e., in-place on a passed string variable name).
+function :convert_path_to_parcel() {
+    # Validate sanity.
+    (( # == 1 )) || die 'Expected one string name.'
+    local string_name__cptp="${1}" parcel_name__cptp
+    local -a parcel_name_list__cptp
 
-    # Canonicalize such path. See canonicalize_path() for further details.
-    parcel_name="$(print -r -- "${parcel_name}"(:A))"
+    # If such string variable does not exist, throw an exception. See
+    # :die_unless_string() for further details.
+    [[ "${(tP)string_name__cptp-}" == 'scalar'* ]] || die\
+        'Variable ${'${string_name__cptp}'} not found or not a string.'
+
+    # Absolute or relative path of such parcel.
+    parcel_name__cptp="${(P)string_name__cptp}"
+    [[ -e "${parcel_name__cptp}" ]] || die\
+        'Parcel "'${parcel_name__cptp}'" not found.'
+
+    # Canonicalize such path. Unfortunately, the simplistic approach performed
+    # by :set_string_to_path_canonical() cannot simply be copied here (due to
+    # the unavailability of other functions such function calls at this time).
+    # Instead, we reimplement such approach in low-level zsh by applying
+    # history expansion modifier "(:A)" in a nonscalar (e.g., list assignment)
+    # rather than scalar (e.g., string assignment) context. See
+    # :set_string_to_path_canonical() for further details.
+    #
+    # Technically, such operation is also implementable with the following
+    # somewhat simpler but dramatically slower approach:
+    #
+    #     parcel_name__cptp="$(print -r -- "${parcel_name__cptp}"(:A))"
+    parcel_name_list__cptp=( "${parcel_name__cptp}"(:A) )
+    parcel_name__cptp="${parcel_name_list__cptp[1]}"
 
     # Replace system-specific overlay prefixes with system-agnostic labels.
     # Note the lack of an "else" branch in the logic below. If such parcel is a
@@ -195,21 +221,24 @@ function convert_path_to_parcel() {
     # * "${match[1]#/}", removing a prefixing "/" from such path if present to
     #   avoid parcel names prefixed an extraneous "/" (e.g.,
     #   "zeshy:///always/zsh/zsh").
-        if [[ "${parcel_name}" == "${ZESHY_OVERLAY_DIR}"(#b)(*) ]] {
-        parcel_name="zeshy://${match[1]#/}"
-    } elif [[ "${parcel_name}" == "${ZESHY_USER_OVERLAY_DIR}"(#b)(*) ]] {
-        parcel_name="zeshy.user://${match[1]#/}"
-    } elif [[ "${parcel_name}" == "${ZESHY_USER_CONFIG_DIRNAME}"(#b)(*) ]] {
-        parcel_name="zeshy.user.config://${match[1]#/}"
+    case "${parcel_name__cptp}" {
+    ("${ZESHY_OVERLAY_DIR}"(#b)(*))
+        parcel_name__cptp="zeshy://${match[1]#/}";;
+    ("${ZESHY_USER_OVERLAY_DIR}"(#b)(*))
+        parcel_name__cptp="zeshy.user://${match[1]#/}";;
+    ("${ZESHY_USER_CONFIG_DIRNAME}"(#b)(*))
+        parcel_name__cptp="zeshy.user.config://${match[1]#/}";;
     # Else, such parcel resides under no canonical overlay. While this should
     # never happen, parcels are hardly essential to zeshy operation. Print a
     # warning to standard error rather than throwing an exception.
-    } else {
-        print -r -- "parcel \"${parcel_name}\" system-specific (due to not residing in a zeshy overlay)" 2>&1
+    (*)
+        :output_warning\
+            'Parcel "'${parcel_name__cptp}'" in no zeshy overlay and hence system-specific.'
     }
 
-    # Return such parcel.
-    print -r -- "${parcel_name}"
+    # Set such string to such name. See :set_string_to_string() for further
+    # details.
+    : "${(P)string_name__cptp::=${parcel_name__cptp}}"
 }
 
 # ....................{ ADDERS                             }....................
@@ -220,11 +249,12 @@ function convert_path_to_parcel() {
 #a new function add_parcel_alias_suffix(). Note we'll probably want to add a new
 #subdirectory "15-alias/" containing the existing file "15-alias" and a new file
 #"suffix" containing new declare_alias_suffix() functions.
+
 function add_parcel_alias() {
-    # Validate passed arguments. Since alias names can contain any character and
+    # Validate sanity. Since alias names can contain any character and
     # hence null used below to delimit alias names, escape nulls in such name.
     # See :define_alias() for further details.
-    (( # == 2 )) || die 'expected one parcel name and one alias name'
+    (( # == 2 )) || die 'Expected one parcel name and one alias name.'
     local parcel_name__apa="${1}" alias_name__apa="${2//$'\0'/\\$'\0'}"
     die_unless_parcel "${parcel_name__apa}"
 
@@ -241,7 +271,7 @@ function add_parcel_alias() {
 
 function add_parcel_function() {
     # See add_parcel_alias() for further details.
-    (( # == 2 )) || die 'expected one parcel name and one function name'
+    (( # == 2 )) || die 'Expected one parcel name and one function name.'
     local parcel_name__apf="${1}" function_name__apf="${2//$'\0'/\\$'\0'}"
     die_unless_parcel "${parcel_name__apf}"
     if (( ${+ZESHY_PARCEL_NAME_TO_FUNCTION_NAMES[${parcel_name__apf}]} )) {
@@ -255,7 +285,7 @@ function add_parcel_global() {
     # Since global names can only contain identifier characters and hence *NOT*
     # null, nulls need not be escaped. See add_parcel_alias() for further
     # details.
-    (( # == 2 )) || die 'expected one parcel name and one global name'
+    (( # == 2 )) || die 'Expected one parcel name and one global name.'
     local parcel_name__apg="${1}" global_name__apg="${2}"
     die_unless_parcel "${parcel_name__apg}"
     if (( ${+ZESHY_PARCEL_NAME_TO_GLOBAL_NAMES[${parcel_name__apg}]} )) {
@@ -267,18 +297,18 @@ function add_parcel_global() {
 
 # ....................{ DECLARERS                          }....................
 function declare_parcel() {
-    # Validate passed arguments. If such parcel has already been declared, throw
+    # Validate sanity. If such parcel has already been declared, throw
     # an exception. Since parcels are typically associated with absolute paths,
     # this shouldn't ever occur. Make sure it doesn't!
-    (( # == 2 )) || die 'expected one parcel name and one help string'
+    (( # == 2 )) || die 'Expected one parcel name and one help string.'
     local  parcel_name="${1}" help="${2}"
 #   print -r -- "declaring parcel \"${parcel_name}\""
     die_if_parcel "${parcel_name}"
 
     # If such name is not a path (i.e., contains null characters), throw an
     # exception. See documentation for further details.
-    [[ "${parcel_name}" == *$'\0'* ]] &&
-        die "parcel name \"${parcel_name}\" not a path (due to embedded null characters)"
+    [[ "${parcel_name}" != *$'\0'* ]] || die\
+        'Parcel "'${parcel_name}'" not a path (due to embedded null characters).'
 
     # Set the current parcel. See set_parcel() for further details.
     ZESHY_PARCEL_NAME="${parcel_name}"
@@ -289,41 +319,24 @@ function declare_parcel() {
 
 # ....................{ DECLARERS ~ script                 }....................
 function declare_parcel_as_script() {
-    # Validate passed arguments.
+    # Validate sanity.
     (( # == 1 || # == 2 )) ||
-        die 'expected optional script name and one help string'
+        die 'Expected optional script name and one help string.'
     local script_name="${ZESHY_SCRIPT_NAME}" help="${@[-1]}"
-    (( # == 2 )) && script_name="${1}"
-    [[ -f "${script_name}" ]] || die "\"${script_name}\" not a script"
+    if (( # == 2 )) {
+        script_name="${1}"
+    }
+    [[ -f "${script_name}" ]] || die 'Script "'${script_name}'" not found.'
 
-    # Convert from the absolute path of such script to a parcel name and declare
-    # such parcel with such documentation.
-    declare_parcel "$(convert_path_to_parcel "${script_name}")" "${help}"
+    # Convert the absolute path of such script to a parcel name.
+    :convert_path_to_parcel script_name
+
+    # Declare such parcel with such documentation.
+    declare_parcel "${script_name}" "${help}"
 }
 
 function declare_parcel_as_script_with_stdin() {
     run_runnable_with_stdin declare_parcel_as_script "${@}"
-}
-
-# ....................{ RUNNERS                            }....................
-function run_runnable_with_stdin() {
-    # Validate passed arguments. If standard input is empty, throw an exception.
-    # See is_stdin_readable_sans_blocking() for further details.
-    (( # )) || die 'expected one runnable name and optional arguments'
-    read -t 0 || die 'standard input empty'
-    local runnable_name__rrws="${1}"
-    shift
-
-    # Unless such function exists, throw an exception. See is_runnable() for
-    # further details.
-    whence -- "${runnable_name__rrws}" &>/dev/null ||
-        die "runnable \"${runnable_name__rrws}\" undefined"
-
-    # Run such runnable. See get_stdin() for further details.
-    "${runnable_name__rrws}" "${@}" "$(< /dev/stdin)"
-
-    # Close standard input. See close_stdin() for further details.
-    exec 0<&-
 }
 
 # ....................{ DOCUMENTERS                        }....................
@@ -332,6 +345,9 @@ Handle parcel declarers. See declare_parcel() for further details.
 /---
 
 # --------------------( WASTELANDS                         )--------------------
+    #FUXME: Both horrible and inefficient. See :set_string_to_path_canonical()
+    #for a non-subshell-based approach.
+
 #FUXME: I'd rather not add another ad-hoc overlay to handle "~/.zeshy/config/"
 #script parcels. To avoid this, we'll want to have the *REAL* directory
 #containing such scripts be a new "~/.zeshy/overlay/if_config/" directory,
@@ -438,14 +454,14 @@ Handle parcel declarers. See declare_parcel() for further details.
 
 #FUXME: Shift all such adders as well as die_unless_parcel(), is_parcel(), and
 #whatever else we don't explicitly require here into new parcel "zsh/parcel".
-    # Validate passed arguments.
+    # Validate sanity.
 #   (( # == 2 )) || die 'expected one script name and one help string'
 #   local script_name="${ZESHY_SCRIPT_NAME}" help="${argv[-1]}"
 #   is_args_2 and script_name="${1}"
 #   die_unless_file "${script_name}"
 
     # Canonicalize such path to avoid ambiguity when cross-referencing parcels.
-    # See canonicalize_path() for further details.
+    # See :canonicalize_path() for further details.
 #   script_name="$(print -- "${script_name}"(:A))"
 
     # If such parcel has already been declared, throw an exception. Since
