Global declarer refactored.
:declare_global() is somewhat half-complete and improving all the ever-while.
Expect grandiose -- nay, even grandiloquent -- things on the morrow's rise.

diff --git a/src/00-start/00-declare/10-set b/src/00-start/00-declare/10-set
--- a/src/00-start/00-declare/10-set
+++ b/src/00-start/00-declare/10-set
@@ -117,7 +117,7 @@ function :set_strings_to_help_prototype,asciidoc() {
     :set_string_to_string "${string_name_asciidoc__ssthp}"  "${match[2]}"
 }
 
-# ....................{ SETTERS ~ prototype : name         }....................
+# ....................{ SETTERS ~ alias                    }....................
 #FIXME: Document me.
 # void :set_string_to_alias_prototype_name(
 #     string string_name, string alias_prototype)
@@ -126,15 +126,6 @@ function :set_string_to_alias_prototype_name() {
     ::set_string_to_runnable_prototype_name_with_label "${@}" 'Alias'
 }
 
-#FIXME: Document me.
-# void :set_string_to_func_prototype_name(
-#     string string_name, string func_prototype)
-function :set_string_to_func_prototype_name() {
-    (( # == 2 )) || :die 'Expected one string name and one function prototype.'
-    ::set_string_to_runnable_prototype_name_with_label "${@}" 'Function'
-}
-
-# ....................{ SETTERS ~ prototype : names        }....................
 #FIXME: Document me.
 #FIXME: Actually, this function will probably be going away. Don't bother
 #documenting, for now.
@@ -147,66 +138,6 @@ function :set_list_to_alias_prototype_names() {
 }
 
 #FIXME: Document me.
-# void :set_list_to_global_prototype_names(
-#     string list_name, string global_prototype)
-function :set_list_to_global_prototype_names() {
-    # Validate sanity.
-    (( # == 2 )) || :die 'Expected one list name and one global prototype.'
-    local\
-        global_names_list_name___sltgpn="${1}"\
-        global_prototype__sltgpn="${2}"
-    [[ -n "${global_prototype__sltgpn}" ]] || :die 'Global prototype empty.'
-
-    # If any such variable is undefined or not of the expected type, throw an
-    # exception. See die_unless_list() for further details.
-    [[ "${(tP)global_names_list_name___sltgpn-}" == 'array'* ]] || :die\
-        'List ${'${global_names_list_name___sltgpn}'} undefined or not a list.'
-
-    # If such prototype is syntactically invalid, throw an exception.
-    [[ "${global_prototype__sltgpn}" =~\
-        "${ZESHY_PROTOTYPE_GLOBAL_TYPE_NAMES_VALUE_PCRE}" ]] || :die\
-        'Global prototype invalid:'$'\n'${global_prototype__sltgpn}
-
-    # If such match failed to capture such global's names, throw an exception.
-    (( ${#match} >= 4 )) || :die\
-        'Global names unparsable from prototype:'$'\n'${global_prototype__sltgpn}
-
-    # If such prototype only declares one name, set such list to such name.
-    if [[ -n "${match[2]}" ]] {
-        eval ${global_names_list_name___sltgpn}'=( "${match[2]}" )'
-    # Else, such prototype declares multiple equal sign-delimited names. Unlike
-    # runnable prototype names, such names are prohibited from containing equal
-    # signs and hence may be efficiently split on such delimiters.
-    } else {
-        #FIXME: Implement efficient splitting here.
-
-        # If such match failed to capture such names, throw an exception.
-        (( ${#prototype_matches__sltgpn} >= 3 )) || :die\
-            ${runnable_label__sltgpn}' names unparsable from prototype:'$'\n'${prototype__sltgpn}
-
-        # Compile such PCRE. See for_string_text_matching_pcre:() for further
-        # details.
-        pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_NEXT_PCRE}"
-        pcre_study
-
-        # Match and append each such name to such list.
-        local ZPCRE_OP='0 0'
-        eval 'while {
-            pcre_match -b -n ${ZPCRE_OP[(w)2]} --\
-                "${prototype_matches__sltgpn[3]}"
-        } {
-            '${runnable_names_list_name___sltgpn}'+="${match[1]}"
-        }
-
-        # If such list remains empty, throw an exception.
-        (( ${#'${runnable_names_list_name___sltgpn}'} )) || :die\
-            ${runnable_label__sltgpn}'' names unsplittable from prototype:''$''\n''${prototype__sltgpn}
-        '
-    }
-}
-
-# ....................{ SETTERS ~ prototype : attrs,names  }....................
-#FIXME: Document me.
 #void :set_map,list_to_alias_prototype_attrs,names(
 #     string alias_attrs_map_name,
 #     string alias_names_list_name,
@@ -215,6 +146,15 @@ function :set_map,list_to_alias_prototype_attrs,names() {
     (( # == 3 )) || :die\
         'Expected one map name, one list name, and one alias prototype.'
     ::set_map,list_to_runnable_prototype_attrs,names_with_label "${@}" 'Alias'
+}
+
+# ....................{ SETTERS ~ func                     }....................
+#FIXME: Document me.
+# void :set_string_to_func_prototype_name(
+#     string string_name, string func_prototype)
+function :set_string_to_func_prototype_name() {
+    (( # == 2 )) || :die 'Expected one string name and one function prototype.'
+    ::set_string_to_runnable_prototype_name_with_label "${@}" 'Function'
 }
 
 #FIXME: Document me.
@@ -228,7 +168,92 @@ function :set_map,list_to_func_prototype_attrs,names() {
     ::set_map,list_to_runnable_prototype_attrs,names_with_label "${@}" 'Function'
 }
 
-# ....................{ SETTERS ~ prototype : low-level    }....................
+# ....................{ SETTERS ~ global                   }....................
+#FIXME: Document me.
+# void :set_list_to_global_prototype_names(
+#     string list_name, string global_prototype)
+function :set_list_to_global_prototype_names() {
+    # Validate sanity.
+    (( # == 2 )) || :die 'Expected one list name and one global prototype.'
+    local placeholder__sltrpn
+
+    # Parse such global names from such prototype. To centralize logic, also
+    # parse such global value despite the caller not requesting such value --
+    # which we then promptly discard, along with the related exit status.
+    :set_list,string_to_global_prototype_names,value_if_value_or_names\
+        "${1}" placeholder__sltrpn "${2}" || true
+}
+
+#FIXME: Document me. Note that if such prototype defines no optional value,
+#such function reports failure whill still setting the first two passed
+#variables.
+
+#void :set_list,string,bool_to_global_names,value,is_value(
+#    string global_names_list_name,
+#    string global_value_string_name,
+#    string global_is_value_bool_name,
+#    string global_names_and_optional_value)
+function :set_list,string,bool_to_global_names,value,is_value() {
+    # Validate sanity.
+    (( # == 4 )) || :die\
+        'Expected one list name, one string name, one boolean name, and one "="-delimited string of one or more global names and optional value.'
+    local\
+        global_names_list_name___sltgpn="${1}"\
+        global_value_string_name___sltgpn="${2}"\
+        global_is_value_bool_name___sltgpn="${3}"\
+        global_names_and_value__sltgpn="${4}"
+    [[ -n "${global_names_and_value__sltgpn}" ]] || :die\
+        'Global names and optional value empty.'
+
+    # If any such variable is undefined or not of the expected type, throw an
+    # exception. Since we call :set_string_to_string() below to set string
+    # variables, avoid validating such variables here. See die_unless_list()
+    # for further details.
+    [[ "${(tP)global_names_list_name___sltgpn-}" == 'array'* ]] || :die\
+        'List ${'${global_names_list_name___sltgpn}'} undefined or not a list.'
+
+    #FIXME: This PCRE isn't *QUITE* as flexible as it should be. Ideally, such
+    #PCRE should accept *ANY* unquoted value not containing whitespace. At the
+    #moment, it only accepts integer unquoted values.
+
+    # If such prototype is syntactically invalid, throw an exception.
+    [[ "${global_names_and_value__sltgpn}" =~\
+        "${ZESHY_PROTOTYPE_GLOBAL_NAMES_VALUE_PCRE}" ]] || :die\
+        'Global names and/or value invalid:'$'\n'${global_names_and_value__sltgpn}
+
+    # If such match failed to capture such global's names, throw an exception.
+    (( ${#match} )) || :die\
+        'Global names unparsable from prototype:'$'\n'${global_names_and_value__sltgpn}
+
+    # If such prototype only declares one name, set such list to such name.
+    if [[ -n "${match[1]}" ]] {
+        eval ${global_names_list_name___sltgpn}'=( "${match[1]}" )'
+    # Else, such prototype declares multiple equal signs-delimited names.
+    # Unlike runnable prototype names, such names are prohibited from
+    # containing equals signs and hence may be efficiently split on such.
+    } else {
+        # If such match failed to capture such names, throw an exception.
+        (( ${#match} >= 2 )) || :die\
+            'Global names unparsable from prototype:'$'\n'${global_names_and_value__sltgpn}
+
+        # Set such list to such names by splitting on equals signs.
+        eval ${global_names_list_name___sltgpn}'=( ${(s:=:)match[2]} )'
+    }
+
+    # If such value is defined, set such value and set such boolean to true.
+    if (( ${#match} == 3 )) {
+        :set_string_to_string\
+            "${global_type_string_name___sltgpn}" "${match[3]}"
+        :set_string_to_string\
+            "${global_is_value_bool_name___sltgpn}" 1
+    # Else, set such boolean to false.
+    } else {
+        :set_string_to_string\
+            "${global_is_value_bool_name___sltgpn}" 0
+    }
+}
+
+# ....................{ SETTERS ~ runnable                 }....................
 # void ::set_string_to_runnable_prototype_name_with_label(
 #     string string_name,
 #     string runnable_prototype,
@@ -534,6 +559,99 @@ function run_runnable_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+#FIXME: Document me.
+
+#[status: bool]
+#    :set_string,list,string_to_global_prototype_type,names,value_if_value(
+#        string global_type_string_name,
+#        string global_names_list_name,
+#        string global_value_string_name,
+#        string global_prototype)
+# function :set_string,list,string_to_global_prototype_type,names,value_if_value() {
+#     # Validate sanity.
+#     (( # == 4 )) || :die\
+#         'Expected one string name, one list name, one string name, and one global prototype.'
+#     local\
+#         global_type_string_name___sltgpn="${1}"\
+#         global_names_list_name___sltgpn="${2}"\
+#         global_value_string_name___sltgpn="${3}"\
+#         global_prototype__sltgpn="${4}"
+#     [[ -n "${global_prototype__sltgpn}" ]] || :die 'Global prototype empty.'
+# 
+#     # If any such variable is undefined or not of the expected type, throw an
+#     # exception. Since we call :set_string_to_string() below to set string
+#     # variables, avoid validating such variables here. See die_unless_list()
+#     # for further details.
+#     [[ "${(tP)global_names_list_name___sltgpn-}" == 'array'* ]] || :die\
+#         'List ${'${global_names_list_name___sltgpn}'} undefined or not a list.'
+# 
+#     # If such prototype is syntactically invalid, throw an exception.
+#     [[ "${global_prototype__sltgpn}" =~\
+#         "${ZESHY_PROTOTYPE_GLOBAL_TYPE_NAMES_VALUE_PCRE}" ]] || :die\
+#         'Global prototype invalid:'$'\n'${global_prototype__sltgpn}
+# 
+#     # If such match failed to capture such global's names, throw an exception.
+#     (( ${#match} >= 2 )) || :die\
+#         'Global names unparsable from prototype:'$'\n'${global_prototype__sltgpn}
+# 
+#     # Set such type.
+#     :set_string_to_string "${global_type_string_name___sltgpn}" "${match[2]}"
+# 
+#     # If such prototype only declares one name, set such list to such name.
+#     if [[ -n "${match[2]}" ]] {
+#         eval ${global_names_list_name___sltgpn}'=( "${match[2]}" )'
+#     # Else, such prototype declares multiple equal signs-delimited names.
+#     # Unlike runnable prototype names, such names are prohibited from
+#     # containing equals signs and hence may be efficiently split on such.
+#     } else {
+#         # If such match failed to capture such names, throw an exception.
+#         (( ${#match} >= 3 )) || :die\
+#             'Global names unparsable from prototype:'$'\n'${global_prototype__sltgpn}
+# 
+#         # Set such list to such names by splitting on equals signs.
+#         eval ${global_names_list_name___sltgpn}'=( ${(s:=:)match[3]} )'
+#     }
+# 
+#     # Set such value if defined or report failure.
+#     if (( ${#match} == 4 )) {
+#         :set_string_to_string\
+#             "${global_type_string_name___sltgpn}" "${match[4]}"
+#     } else {
+#         return 1
+#     }
+# }
+
+#FUXME: Document me. Note that if such prototype declares no optional value,
+#such value will be set to the empty string if such type... No, wait; that
+#doesn't really work. Hmm. How can a nonextant value be reliably signified? A
+#number of possible ways:
+#
+#1. Such function preserves the current value of variable
+#   ${global_value_string_name}. Assuming the caller initializes such variable
+#   to an exceptionally unlikely value (e.g., $'\n\t\b\0'), the caller can then
+#   test whether such variable retains the same value to determine whether such
+#   global had a value passed. The downside, of course, is the inherent
+#   unreliability of such an approach.
+#2. Such function reports failure if no such value was provided.
+#
+#Honestly, the latter is the obvious route forward. What sort of nomenclature
+#should we concoct, however? Consider:
+#
+#* :set_string,list,string_to_global_prototype_type,names,value_if_value_or_type,names().
+#
+#We know; that's a *CRAZY* long nomenclature, but... *shrug*.
+#
+#Wait; why *CAN'T* we just set such value to the empty string? We mean, really;
+#is there any difference in the end at all? Hmm; yes, actually, there is. Go
+#with the above, we should think.
+
+    # If any such variable is undefined or not of the expected type, throw an
+    # exception. See die_unless_string() and die_unless_list() for further
+    # details.
+    # [[ "${(tP)global_type_string_name___sltgpn-}${(tP)global_value_string_name___sltgpn-}" ==\
+    #     'scalar'*'scalar'* ]] || :die\
+    #     'Strings ${'${global_type_string_name___sltgpn}'} and/or ${'${global_value_string_name___sltgpn}'} undefined or not strings.'
+
 #FUXME: If we're going to go this far (and we certainly are), we'd might as
 #well also define setters for lists and maps, which we should then leverage
 #below inplace of inlined eval() statements.
diff --git a/src/00-start/00-declare/50-alias b/src/00-start/00-declare/50-alias
--- a/src/00-start/00-declare/50-alias
+++ b/src/00-start/00-declare/50-alias
@@ -13,12 +13,14 @@ declarers and definers.
 # documented under @{help} in the main codebase.
 
 # ....................{ DECLARERS                          }....................
-declare_function_with_stdin <<'/---'
-void :declare_alias_simple[
+:declare_func_ 'void :declare_alias_simple[
     args: (string alias_prototype,
            string alias_expansion),
-    stdin: string alias_asciidoc]
-
+    stdin: string alias_asciidoc]' :declare_func{
+    (( # == 2 )) || :die\
+        'Expected one alias prototype and one alias expansion.'
+    ::declare_alias_type 'simple' "${@}"
+}:declare_func <<'/---'
 Declare one or more *simple aliases* (i.e., aliases expanded only in command
 position) identified by the passed prototype, expanding to the passed expansion
 and documented by the documentation passed on standard input (e.g., as a
@@ -47,17 +49,15 @@ It is not enough to fight for the land; it is even more important to
 ------------------------------------------
 ==========================================
 /---
-function :declare_alias_simple() {
-    (( # == 2 )) || :die 'Expected one alias prototype and one alias expansion.'
-    ::declare_alias_type 'simple' "${@}"
-}
 
-declare_function_with_stdin <<'/---'
-void :declare_alias_global[
+:declare_func_ 'void :declare_alias_global[
     args: (string alias_prototype,
            string alias_expansion),
-    stdin: string alias_asciidoc]
-
+    stdin: string alias_asciidoc]' :declare_func{
+    (( # == 2 )) || :die\
+        'Expected one alias prototype and one alias expansion.'
+    ::declare_alias_type 'global' "${@}"
+}:declare_func <<'/---'
 Declare one or more *global aliases* (i.e., aliases expanded in any position of
 a command) identified by the passed prototype, expanding to the passed
 expansion and documented by the documentation passed on standard input (e.g.,
@@ -86,17 +86,15 @@ You will outlive the bastards.
 ------------------------------------------
 ==========================================
 /---
-function :declare_alias_global() {
-    (( # == 2 )) || :die 'Expected one alias prototype and one alias expansion.'
-    ::declare_alias_type 'global' "${@}"
-}
 
-declare_function_with_stdin <<'/---'
-void :declare_alias_suffix[
+:declare_func_ 'void :declare_alias_suffix[
     args: (string alias_prototype,
            string alias_expansion),
-    stdin: string alias_asciidoc]
-
+    stdin: string alias_asciidoc]' :declare_func{
+    (( # == 2 )) || :die\
+        'Expected one alias prototype and one alias expansion.'
+    ::declare_alias_type 'suffix' "${@}"
+}:declare_func <<'/---'
 Declare one or more *suffix aliases* (i.e., aliases expanded when files of such
 filetype are in command position) identified by the passed prototype, expanding
 to the passed expansion and documented by the documentation passed on standard
@@ -132,19 +130,63 @@ Ernest Callenbach.pdf: application/pdf
 ------------------------------------------
 ==========================================
 /---
-function :declare_alias_suffix() {
-    (( # == 2 )) || :die 'Expected one alias prototype and one alias expansion.'
-    ::declare_alias_type 'suffix' "${@}"
-}
 
 # ....................{ DECLARERS ~ low-level              }....................
-declare_function_with_stdin <<'/---'
-void ::declare_alias_type[
+:declare_func_ 'void ::declare_alias_type[
     args: (string alias_type,
            string alias_prototype,
            string alias_expansion),
-    stdin: string alias_asciidoc]
+    stdin: string alias_asciidoc]' :declare_func{
+    # Validate sanity. Since ::document_alias_typed_with_prototype,asciidoc()
+    # already validates such type, do *NOT* bother doing so here.
+    (( # == 3 )) || :die\
+        'Expected one alias type, one alias prototype, and one alias expansion.'
+    local\
+        alias_type="${1}"\
+        alias_prototype="${2}"\
+        alias_code="${3}"\
+        alias_asciidoc
+    local -a alias_names
 
+    # Documentation passed on standard input.
+    :set_string_to_stdin_help alias_asciidoc
+
+    # List of all alias names declared by such prototype.
+    :set_list_to_alias_prototype_names alias_names "${alias_prototype}"
+
+    # For each such alias...
+    local alias_name
+    for   alias_name ("${alias_names[@]}") {
+        # Function defining such alias.
+        local alias_definer=":define_alias_${alias_type}"
+
+        # If such function does *NOT* exist, throw an exception. See
+        # :die_unless_func() for further details.
+        (( ${+functions[${alias_definer}]} )) || :die\
+            'Function '${alias_definer}'() undefined.'
+
+        # Define such alias.
+        "${alias_definer}" "${alias_name}" "${alias_code}"
+
+        #FIXME: This is fairly lame. For one, such function fails to
+        #distinguish between alias types; for another, a new function
+        #:add_parcel_current_alias_simple() should probably be defined passing
+        #canonical global "${ZESHY_PARCEL_NAME}" to a new function
+        #:add_parcel_alias_simple().
+
+        # Append such alias to the current parcel *AFTER* successfully defining
+        # such alias.
+        add_parcel_alias "${ZESHY_PARCEL_NAME}" "${alias_name}"
+    }
+
+    # Document such aliases with such documentation *AFTER* successfully
+    # defining such aliases above.
+    ::document_alias_typed_with_prototype,asciidoc\
+        "${alias_names[@]}"\
+        "${alias_type}"\
+        "${alias_prototype}"\
+        "${alias_asciidoc}"
+}:declare_func <<'/---'
 Declare an alias of the passed type residing in the current parcel with
 prototype and hence name parsed from either the passed optional prototype _or_
 the non-optional documentation passed on standard input (e.g., as a
@@ -302,62 +344,25 @@ alias set_args_to_string_split_on_words_from='
 ------------------------------------------
 ==========================================
 /---
-function ::declare_alias_type() {
-    # Validate sanity. Since ::document_alias_typed_with_prototype,asciidoc()
-    # already validates such type, do *NOT* bother doing so here.
-    (( # == 3 )) || :die\
-        'Expected one alias type, one alias prototype, and one alias expansion.'
-    local\
-        alias_type="${1}"\
-        alias_prototype="${2}"\
-        alias_code="${3}"\
-        alias_asciidoc
-    local -a alias_names
-
-    # Documentation passed on standard input.
-    :set_string_to_stdin_help alias_asciidoc
-
-    # List of all alias names declared by such prototype.
-    :set_list_to_alias_prototype_names alias_names "${alias_prototype}"
-
-    # For each such alias...
-    local alias_name
-    for   alias_name ("${alias_names[@]}") {
-        # Function defining such alias.
-        local alias_definer=":define_alias_${alias_type}"
-
-        # If such function does *NOT* exist, throw an exception. See
-        # :die_unless_func() for further details.
-        (( ${+functions[${alias_definer}]} )) || :die\
-            'Function '${alias_definer}'() undefined.'
-
-        # Define such alias.
-        "${alias_definer}" "${alias_name}" "${alias_code}"
-
-        #FIXME: This is fairly lame. For one, such function fails to
-        #distinguish between alias types; for another, a new function
-        #:add_parcel_current_alias_simple() should probably be defined passing
-        #canonical global "${ZESHY_PARCEL_NAME}" to a new function
-        #:add_parcel_alias_simple().
-
-        # Append such alias to the current parcel *AFTER* successfully defining
-        # such alias.
-        add_parcel_alias "${ZESHY_PARCEL_NAME}" "${alias_name}"
-    }
-
-    # Document such aliases with such documentation *AFTER* successfully
-    # defining such aliases above.
-    ::document_alias_typed_with_prototype,asciidoc\
-        "${alias_names[@]}"\
-        "${alias_type}"\
-        "${alias_prototype}"\
-        "${alias_asciidoc}"
-}
 
 # ....................{ DEFINERS                           }....................
-declare_function_with_stdin <<'/---'
-void :define_alias_simple(string alias_name, string alias_expansion)
+:declare_func_ 'void :define_alias_simple(
+    string alias_name, string alias_expansion)' :declare_func{
+    # Validate sanity.
+    (( # == 2 )) || :die 'Expected one alias name and one alias expansion.'
+    local alias_name="${1}" alias_code="${2}"
 
+    # If such alias already exists, throw an exception. See :is_alias_simple()
+    # for further details.
+    if (( ${+aliases[${alias_name}]} +\
+          ${+dis_aliases[${alias_name}]} )) {
+        :die "Simple alias ${alias_name}() already defined:
+$(alias -- "${alias_name}")"
+    }
+
+    # Define such alias.
+    :redefine_alias_simple "${alias_name}" "${alias_code}"
+}:declare_func <<'/---'
 Define the passed simple alias to expand to the passed expansion. If such alias
 has already been defined, an exception is thrown. See :declare_alias_simple()
 for further details: e.g.,
@@ -386,26 +391,24 @@ explicitly escaping alias-reserved characters (e.g., `"`, `=`, whitespace) in
 alias names and hence does _not_ constitute a general-purpose solution. As the
 prior example demonstrates, this function suffers no such deficiencies.
 /---
-function :define_alias_simple() {
+
+:declare_func_ 'void :define_alias_global(
+    string alias_name, string alias_expansion)' :declare_func{
     # Validate sanity.
     (( # == 2 )) || :die 'Expected one alias name and one alias expansion.'
     local alias_name="${1}" alias_code="${2}"
 
-    # If such alias already exists, throw an exception. See :is_alias_simple()
+    # If such alias already exists, throw an exception. See :is_alias_global()
     # for further details.
-    if (( ${+aliases[${alias_name}]} +\
-          ${+dis_aliases[${alias_name}]} )) {
-        :die "Simple alias ${alias_name}() already defined:
+    if (( ${+galiases[${alias_name}]} +\
+          ${+dis_galiases[${alias_name}]} )) {
+        :die "Global alias ${alias_name}() already defined:
 $(alias -- "${alias_name}")"
     }
 
     # Define such alias.
-    :redefine_alias_simple "${alias_name}" "${alias_code}"
-}
-
-declare_function_with_stdin <<'/---'
-void :define_alias_global(string alias_name, string alias_expansion)
-
+    :redefine_alias_global "${alias_name}" "${alias_code}"
+}:declare_func <<'/---'
 Define the passed global alias to expand to the passed expansion. If such alias
 has already been defined, an exception is thrown. See :declare_alias_global()
 and :define_alias_simple() for further details: e.g.,
@@ -426,26 +429,23 @@ People were to be happy not to the extent they dominated their
 ------------------------------------------
 ==========================================
 /---
-function :define_alias_global() {
-    # Validate sanity.
-    (( # == 2 )) || :die 'Expected one alias name and one alias expansion.'
-    local alias_name="${1}" alias_code="${2}"
 
-    # If such alias already exists, throw an exception. See :is_alias_global()
+:declare_func_ 'void :define_alias_suffix(
+    string filetype, string alias_expansion)' :declare_func{
+    # Validate sanity.
+    (( # == 2 )) || :die 'Expected one filetype and one alias expansion.'
+    local filetype="${1}" alias_code="${2}"
+
+    # If such alias already exists, throw an exception. See :is_alias_suffix()
     # for further details.
-    if (( ${+galiases[${alias_name}]} +\
-          ${+dis_galiases[${alias_name}]} )) {
-        :die "Global alias ${alias_name}() already defined:
-$(alias -- "${alias_name}")"
+    if (( ${+saliases[${filetype}]} +\
+          ${+dis_saliases[${filetype}]} )) {
+        :die 'Suffix alias for filetype "'${filetype}'" already defined:'$'\n'$(alias -s -- "${filetype}")
     }
 
     # Define such alias.
-    :redefine_alias_global "${alias_name}" "${alias_code}"
-}
-
-declare_function_with_stdin <<'/---'
-void :define_alias_suffix(string filetype, string alias_expansion)
-
+    :redefine_alias_suffix "${filetype}" "${alias_code}"
+}:declare_func <<'/---'
 Define the passed global alias to expand to the passed expansion. If such alias
 has already been defined, an exception is thrown. See :declare_alias_suffix()
 and :define_alias_simple() for further details: e.g.,
@@ -470,26 +470,29 @@ to die for it without hate.
 ------------------------------------------
 ==========================================
 /---
-function :define_alias_suffix() {
-    # Validate sanity.
-    (( # == 2 )) || :die 'Expected one filetype and one alias expansion.'
-    local filetype="${1}" alias_code="${2}"
-
-    # If such alias already exists, throw an exception. See :is_alias_suffix()
-    # for further details.
-    if (( ${+saliases[${filetype}]} +\
-          ${+dis_saliases[${filetype}]} )) {
-        :die 'Suffix alias for filetype "'${filetype}'" already defined:'$'\n'$(alias -s -- "${filetype}")
-    }
-
-    # Define such alias.
-    :redefine_alias_suffix "${filetype}" "${alias_code}"
-}
 
 # ....................{ REDEFINERS                         }....................
-declare_function_with_stdin <<'/---'
-void :redefine_alias_simple(string alias_name, string alias_expansion)
+:declare_func_ 'void :redefine_alias_simple(
+    string alias_name, string alias_expansion)' :declare_func{
+    # Validate sanity.
+    (( # == 2 )) || :die 'Expected one alias name and one alias expansion.'
+    local alias_name="${1}" alias_code="${2}"
+    [[ -n "${alias_name}" ]] || :die 'Alias name empty.'
 
+    # Declare such alias. Since zsh dynamically expands aliases at their point
+    # of use, alias() attempts no parsing or syntactic validation of the
+    # contents of such expansion. Such redefinition should *ALWAYS* succeed.
+    #
+    # Note such redefinition to also be implementable with the following
+    # less efficient and considerably more fragile alternative, requiring
+    # characters reserved for use in alias definitions (e.g., "=") to be
+    # explicitly escaped rather than merely double- or single-quoted:
+    #
+    #    alias_name="${alias_name//(#m)([\"=[:space:]])/\\${MATCH}}"
+    #    alias -- "${alias_name}"="${alias_code}"
+    aliases[${alias_name}]="${alias_code}"
+#   print "redefine alias name: ${alias_name__ra}"
+}:declare_func <<'/---'
 Define the passed simple alias to expand to the passed string, regardless of
 whether such alias has already been defined. See :declare_alias_simple() for
 further details: e.g.,
@@ -516,30 +519,18 @@ our feeling of alienation from the universe.
 ------------------------------------------
 ==========================================
 /---
-function :redefine_alias_simple() {
+
+:declare_func_ 'void :redefine_alias_global(
+    string alias_name, string alias_expansion)' :declare_func{
     # Validate sanity.
     (( # == 2 )) || :die 'Expected one alias name and one alias expansion.'
     local alias_name="${1}" alias_code="${2}"
     [[ -n "${alias_name}" ]] || :die 'Alias name empty.'
 
-    # Declare such alias. Since zsh dynamically expands aliases at their point
-    # of use, alias() attempts no parsing or syntactic validation of the
-    # contents of such expansion. Such redefinition should *ALWAYS* succeed.
-    #
-    # Note such redefinition to also be implementable with the following
-    # less efficient and considerably more fragile alternative, requiring
-    # characters reserved for use in alias definitions (e.g., "=") to be
-    # explicitly escaped rather than merely double- or single-quoted:
-    #
-    #    alias_name="${alias_name//(#m)([\"=[:space:]])/\\${MATCH}}"
-    #    alias -- "${alias_name}"="${alias_code}"
-    aliases[${alias_name}]="${alias_code}"
+    # Declare such alias. See :redefine_alias_suffix() for further details.
+    galiases[${alias_name}]="${alias_code}"
 #   print "redefine alias name: ${alias_name__ra}"
-}
-
-declare_function_with_stdin <<'/---'
-void :redefine_alias_global(string alias_name, string alias_expansion)
-
+}:declare_func <<'/---'
 Define the passed global alias to expand to the passed string regardless of
 whether such alias has already been defined. See :declare_alias_global() for
 further details: e.g.,
@@ -565,20 +556,18 @@ Anarchism is the destruction of misery, of superstitions, of hatred.
 ------------------------------------------
 ==========================================
 /---
-function :redefine_alias_global() {
+
+:declare_func_ 'void :redefine_alias_suffix(
+    string filetype, string alias_expansion)' :declare_func{
     # Validate sanity.
-    (( # == 2 )) || :die 'Expected one alias name and one alias expansion.'
-    local alias_name="${1}" alias_code="${2}"
-    [[ -n "${alias_name}" ]] || :die 'Alias name empty.'
+    (( # == 2 )) || :die 'Expected one filetype and one alias expansion.'
+    local filetype="${1}" alias_code="${2}"
+    [[ -n "${filetype}" ]] || :die 'Filetype empty.'
 
     # Declare such alias. See :redefine_alias_suffix() for further details.
-    galiases[${alias_name}]="${alias_code}"
-#   print "redefine alias name: ${alias_name__ra}"
-}
-
-declare_function_with_stdin <<'/---'
-void :redefine_alias_suffix(string filetype, string alias_expansion)
-
+    saliases[${filetype}]="${alias_code}"
+#   print "redefine alias name: ${filetype__ra}"
+}:declare_func <<'/---'
 Define the passed suffix alias to expand to the passed string regardless of
 whether such alias has already been defined. See :declare_alias_suffix() for
 further details: e.g.,
@@ -603,16 +592,6 @@ So long as they continued to work and breed, their other activities
 ------------------------------------------
 ==========================================
 /---
-function :redefine_alias_suffix() {
-    # Validate sanity.
-    (( # == 2 )) || :die 'Expected one filetype and one alias expansion.'
-    local filetype="${1}" alias_code="${2}"
-    [[ -n "${filetype}" ]] || :die 'Filetype empty.'
-
-    # Declare such alias. See :redefine_alias_suffix() for further details.
-    saliases[${filetype}]="${alias_code}"
-#   print "redefine alias name: ${filetype__ra}"
-}
 
 # --------------------( WASTELANDS                         )--------------------
 #FUXME: Excise!
