Prototype attributes accept optional values.
The PCREs matching and capturing prototype attributes have been improved to
accept optional ": "-prefixed values in conventional key-value format. While we
have yet to meaningfully leverage such values elsewhere, the capacity at least
remains a compelling tug onward.

diff --git a/src/00-start/00-declare/10-set b/src/00-start/00-declare/10-set
--- a/src/00-start/00-declare/10-set
+++ b/src/00-start/00-declare/10-set
@@ -143,7 +143,91 @@ function :set_string_to_runnable_prototype_name() {
     :set_string_to_string "${string_name__sstrpn}" "${match[1]}"
 }
 
-# ....................{ SETTERS ~ prototype : list         }....................
+#FIXME: Document me.
+
+# void :set_map_list_to_runnable_prototype_attrs_names(
+#     string map_name, string list_name, string runnable_prototype)
+function :set_map_list_to_runnable_prototype_attrs_names() {
+    # Validate sanity.
+    (( # == 3 )) || :die\
+        'Expected one map name, one list name, and one runnable prototype.'
+    local\
+        map_name_attrs__smltrpan="${1}"\
+        list_name_names___smltrpan="${2}"\
+        prototype__smltrpan="${3}"
+    [[ -n "${prototype__smltrpan}" ]] || :die 'Runnable prototype empty.'
+
+    # If any such variable is undefined or not of the expected type, throw an
+    # exception. See die_unless_map() and die_unless_list() for further details.
+    [[ "${(tP)map_name_attrs__smltrpan-}" == 'association'* ]] || :die\
+        '${'${map_name_attrs__smltrpan}'} undefined or not a list.'
+    [[ "${(tP)list_name_names___smltrpan-}" == 'array'* ]] || :die\
+        '${'${list_name_names___smltrpan}'} undefined or not a list.'
+
+    # If such prototype is syntactically invalid, throw an exception.
+    [[ "${prototype__smltrpan}" =~\
+        "${ZESHY_PROTOTYPE_RUNNABLE_ATTRS_NAMES_PCRE}" ]] || :die\
+        'Runnable prototype invalid:'$'\n'${prototype__smltrpan}
+
+    # If the prior match failed to capture either the attributes or names were
+    # of such prototype, throw an exception.
+    (( ${#match} == 3 )) || :die\
+        'Runnable prototype attributes and/or names not found:'$'\n'${prototype__smltrpan}
+
+    # If such prototype declares at least one attribute, match such attributes.
+    if [[ -n "${match[1]}" ]] {
+        #FIXME: Bad! Split the attribute string apart into its constituent
+        #components into such map. We'll need a PCRE-based loop, as below. Map:
+        #
+        #* Unvalued attributes (e.g., "<globbable>") to keys with empty values.
+        #* Valued attributes (e.g., "<deprecated = '3.0'>") to keys with the
+        #  corresponding values.
+
+        # List of attributes split from such string. Split on commas
+        # after truncating:
+        #
+        # * Optional whitespace surrounding commas (e.g., from " , " to ",").
+        # * Optional trailing commas and/or whitespace.
+        # eval ${map_name_attrs__smltrpan}'=(
+        #     "${(s:,:)${match[1]//[[:space:]]#,[[:space:]]#/,}%%[[:space:]]#,#[[:space:]]#}" )'
+#       for ((match_index=1; match_index <= ${#attrs}; ++match_index)) {
+#           print "attr ${match_index}: ${attrs[${match_index}]}"
+#       }
+    }
+
+    # If such prototype only declares one name, set such list to such name.
+    if [[ -n "${match[2]}" ]] {
+        eval ${list_name_names___smltrpan}'=( "${match[2]}" )'
+    # Else, such prototype declares multiple comma-delimited names. Since
+    # single- and double-quoted runnable names may contain commas, such names
+    # must be iteratively matched with a PCRE rather than split on commas.
+    } else {
+        # Preserve such names *BEFORE* matching, which overwrites ${match}.
+        local runnable_names__smltrpan="${match[3]}"
+
+        # Compile such PCRE. See for_string_text_matching_pcre:() for further
+        # details.
+        pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_NEXT_PCRE}"
+        pcre_study
+
+        # Match and append each such name to such list.
+        local ZPCRE_OP='0 0'
+        eval 'while {
+            pcre_match -b -n ${ZPCRE_OP[(w)2]} -- "${runnable_names__smltrpan}"
+        } {
+            '${list_name_names___smltrpan}'+="${match[1]}"
+        }
+
+        # If such list remains empty, throw an exception.
+        (( ${#'${list_name_names___smltrpan}'} )) || :die\
+            ''Runnable prototype names unparsed (despite detecting multiple ple names):''$''\n''${prototype__smltrpan}
+        '
+    }
+}
+
+#FIXME: Such function should be obsoleted in favor of
+#:set_map_list_to_runnable_prototype_attributes_names().
+
 # void :set_list_to_runnable_prototype_names(
 #     string list_name, string runnable_prototype)
 function :set_list_to_runnable_prototype_names() {
@@ -193,7 +277,7 @@ function :set_list_to_runnable_prototype_names() {
 
         # If such list remains empty, throw an exception.
         (( ${#'${list_name__sltrpn}'} )) || :die\
-            ''Runnable prototype "''${prototype__sltrpn}''" names uncaptured (despite multiple names being detected).'''
+            ''Runnable prototype "''${prototype__sltrpn}''" names unparsed (despite detecting multiple names).'''
     }
 }
 
@@ -247,6 +331,9 @@ function set_list_and_map_to_runnable_prototype_name_or_names: {
     # with runnable attributes elsewhere. Rather, iteratively match such names
     # with a PCRE.
     } else {
+        [[ -n "${runnable_names__sltrpn}" ]] || :die\
+            'Both singular and plural function names empty.'
+
         # Prepare to match such names. See for_string_text_matching_pcre:() for further
         # details.
         pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_NEXT_PCRE}"
@@ -270,7 +357,12 @@ function set_list_and_map_to_runnable_prototype_name_or_names: {
 
             # Map such name to the first such name for such runnable.
             '${map_name__sltrpn}'[${runnable_name__sltrpn}]="${'${list_name__sltrpn}'[1]}"
-        }'
+        }
+        
+        # If such list remains empty, throw an exception.
+        (( ${#'${list_name__sltrpn}'} )) || :die\
+            ''Runnable prototype names unparsed (despite detecting multiple names):''$''\n''${runnable_names__sltrpn}
+        '
     }
 }
 
