Alias prototype syntax enforced.
Alias prototypes passed to alias declarations are now required to strictly
conform to zeshy syntax. Naturally, this horribly breaks the codebase.

diff --git a/src/00-start/00-declare/10-set b/src/00-start/00-declare/10-set
--- a/src/00-start/00-declare/10-set
+++ b/src/00-start/00-declare/10-set
@@ -10,6 +10,9 @@
 #FIXME: Call such function elsewhere rather than manually inlining such logic
 #everywhere. We should have probably done this *MUCH* sooner.
 
+# void :set_string_to_string(
+#     string string_name,
+#     string text1, ...)
 function :set_string_to_string() {
     # Validate sanity.
     (( # >= 2 )) || :die 'Expected one string name and one or more strings.'
@@ -28,10 +31,6 @@ function :set_string_to_string() {
     # is required. Set such variable to the undelimited concatenation of all
     # such strings.
     } else {
-        # Shift such variable name from the argument list. See shift_arg() for
-        # further details.
-        argv[1]=()
-
         # Locally clear canonical string global ${IFS} (i.e., the internal
         # field separator). Since zsh implicitly delimits strings concatenated
         # with "*" by such global's value, clearing such global guarantees
@@ -42,15 +41,19 @@ function :set_string_to_string() {
         local IFS=
 
         # Set such string with undelimited concatenation.
-        noop "${(P)string_name__ssts::=${*}}"
+        noop "${(P)string_name__ssts::=${*[2,-1]}}"
     }
 }
 
+# ....................{ SETTERS ~ help                     }....................
 #FIXME: Replace *ALL* calls to run_runnable_with_stdin() with calls to this
 #function; then, excise the former.
 #FIXME: Document me.
 
-function :set_string_to_declarer_help() {
+# void :set_string_to_stdin_help[
+#     args:  string string_name,
+#     stdin: string documentation]
+function :set_string_to_stdin_help() {
     # Validate sanity.
     (( # == 1 )) || :die 'Expected one string name.'
     local string_name__sstdh="${1}"
@@ -88,7 +91,35 @@ function :set_string_to_declarer_help() {
     :set_string_to_string "${string_name__sstdh}" "$(< /dev/stdin)"
 }
 
+#FIXME: Document me.
+# void :set_string_to_help_prototype(
+#     string string_name, string documentation)
+function :set_string_to_help_prototype() {
+    # Validate sanity.
+    (( # == 2 )) || :die 'Expected one string name and one help string.'
+    local string_name__ssthp="${1}" help__ssthp="${2}"
+
+    #FIXME: Persist as a global to avoid such reconstruction on every call.
+    #Perhaps we want a new @{05-glob} parcel?
+
+    # Glob matching a blank line (i.e., two consecutive newlines optionally
+    # separated by zero or more tab or space characters).
+    local blank_line_glob=$'\n''[ '$'\t'']#'$'\n'
+    local ZESHY_HELP_PROTOTYPE_GLOB='[[:space:]]#(#b)(^'${blank_line_glob}')'${blank_line_glob}'*'
+
+    # If such documentation contains a blank line (i.e., "\n\n"), assume the
+    # substring preceding such line to be the expected prototype. Else, throw
+    # an exception.
+    [[ "${help__ssthp}" == ${~ZESHY_HELP_PROTOTYPE_GLOB} ]] || :die\
+        'Documentation "'${help__ssthp%%$'\n'*}'..." prefixed by no prototype.'
+
+    # Set such string to such prototype.
+    :set_string_to_string "${string_name__ssthp}" "${match[1]}"
+}
+
 # ....................{ SETTERS ~ prototype                }....................
+# void :set_string_to_runnable_prototype_name(
+#     string string_name, string runnable_prototype)
 function :set_string_to_runnable_prototype_name() {
     # Validate sanity.
     (( # == 2 )) || :die 'Expected one string name and one runnable prototype.'
@@ -114,6 +145,60 @@ function :set_string_to_runnable_prototype_name() {
     :set_string_to_string "${string_name__sstrpn}" "${match[1]}"
 }
 
+# ....................{ SETTERS ~ prototype : list         }....................
+# void :set_list_to_runnable_prototype_names(
+#     string list_name, string runnable_prototype)
+function :set_list_to_runnable_prototype_names() {
+    # Validate sanity.
+    (( # == 2 )) || :die 'Expected one list name and one runnable prototype.'
+    local list_name__sltrpn="${1}" prototype__sltrpn="${2}"
+    [[ -n "${prototype__sltrpn}" ]] || :die 'Runnable prototype empty.'
+
+    # If such variable is undefined or not a list, throw an exception. See
+    # die_unless_list() for further details.
+    [[ "${(tP)list_name__sltrpn-}" == 'array'* ]] || :die\
+        '${'${list_name__sltrpn}'} undefined or not a list.'
+
+    # If such prototype is syntactically invalid, throw an exception.
+    [[ "${prototype__sltrpn}" =~\
+        "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_PCRE}" ]] || :die\
+        'Runnable prototype "'${prototype__sltrpn}'" invalid.'
+
+    # If no such names were captured, throw an exception.
+    (( ${#match} )) || :die\
+        'Runnable prototype "'${prototype__sltrpn}'" names uncaptured.'
+
+    # If such runnable only has one name, set such list to such name.
+    if [[ -n "${match[1]}" ]] {
+        eval ${list_name__sltrpn}'=( "${match[1]}" )'
+    # Else, such runnable has multiple comma-delimited names. Since single- and
+    # double-quoted runnable names may themselves contain commas, such names
+    # must be iteratively matched with a PCRE rather than split on commas.
+    } else {
+        local runnable_names__sltrpn
+
+        # Preserve such names *BEFORE* such matching, which overwrites ${match}.
+        runnable_names__sltrpn="${match[1]}"
+
+        # Compile such PCRE. See for_string_text_matching_pcre:() for further
+        # details.
+        pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_NEXT_PCRE}"
+        pcre_study
+
+        # Match and append each such name to such list.
+        local ZPCRE_OP='0 0'
+        eval 'while {
+            pcre_match -b -n ${ZPCRE_OP[(w)2]} -- "${runnable_names__sltrpn}"
+        } {
+            '${list_name__sltrpn}'+="${match[1]}"
+        }'
+    }
+}
+
+# ....................{ OBSOLETE                           }....................
+#FIXME: Everything below should be excised after completing all refactorings in
+#this parent parcel.
+
 #FIXME: Since we really don't care terribly much about function and alias
 #synonyms, it's likely that we'll no longer require the passed map argument
 #*AFTER* implementing the refactorings in @{*-func}. Cut such argument and
@@ -135,7 +220,7 @@ function set_list_and_map_to_runnable_prototype_name_or_names: {
         runnable_names__sltrpn="${4}"
 
     # If any such variable is undefined or not of the expected type, throw an
-    # exception. See is_list() for further details.
+    # exception. See die_unless_list() for further details.
     [[ "${(tP)list_name__sltrpn-}" == 'array'* ]] || :die\
         '${'${list_name__sltrpn}'} undefined or not a list.'
     [[ "${(tP)map_name__sltrpn-}" == 'association'* ]] || :die\
@@ -162,7 +247,7 @@ function set_list_and_map_to_runnable_prototype_name_or_names: {
     } else {
         # Prepare to match such names. See for_string_text_matching_pcre:() for further
         # details.
-        pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_NAME_NEXT_PCRE}"
+        pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_NEXT_PCRE}"
         pcre_study
 
         # Match such names.
@@ -187,7 +272,6 @@ function set_list_and_map_to_runnable_prototype_name_or_names: {
     }
 }
 
-# ....................{ RUNNERS                            }....................
 function run_runnable_with_stdin() {
     # Validate sanity.
     (( # )) || :die 'Expected one runnable name and optional arguments.'
@@ -255,6 +339,48 @@ function run_runnable_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+#[[:space:]]#(#b)(^$'\n']##)$'\n'[[:space:]]#$'\n'*
+#FUXME: This is terrible. Excise!
+# function die_for_declarator_type_with_help() {
+#     # Validate sanity.
+#     (( # == 2 )) || :die 'Expected one type string and one help string.'
+# #   print -r -- "arg count: ${#}; args: ${*}"
+#     local type="${1}" help="${2}"
+# 
+#     # Function prototype prefixing such help string.
+#     local help_prototype
+# 
+#     # If such string contains a blank line (i.e., "\n\n"), crudely match the
+#     # substring preceding such line as the function prototype.
+#     if     [[ "${help}" == (#b)([^$'\n']##)$'\n\n'* ]] {
+#         help_prototype="${match[1]}"
+#     # Else if such string contains a newline (i.e., "\n"), crudely match the
+#     # substring preceding such newline as the function prototype.
+#     } elif [[ "${help}" == (#b)([^$'\n']##)$'\n'* ]] {
+#         help_prototype="${match[1]}"
+#     # Else, abandon all hope.
+#     } else {
+#         help_prototype="${help}"
+#     }
+# 
+#     # Throw an exception suffixed by such prototype.
+#     :die "${(C)type} documentation invalid (see \"print_help declare_${type}\"):
+# ${help_prototype}"
+# }
+
+    # If such documentation contains a newline (i.e., "\n"), assume the
+    # substring preceding such newline as the function prototype.
+    # } elif [[ "${help__ssthp}" == (#b)([^$'\n']##)$'\n'* ]] {
+    #     prototype__ssthp="${match[1]}"
+    # # Else, abandon all hope.
+    # } else {
+    #     prototype__ssthp="${help}"
+
+#FUXME: Rename to :set_string_to_stdin_help().
+        # Shift such variable name from the argument list. See shift_arg() for
+        # further details.
+        # argv[1]=()
+
 #FUXME: Document this parcel and all runnables such parcel declares.
 
     # If such variable is not a string, throw an exception. See
diff --git a/src/00-start/00-declare/30-parcel b/src/00-start/00-declare/30-parcel
--- a/src/00-start/00-declare/30-parcel
+++ b/src/00-start/00-declare/30-parcel
@@ -125,24 +125,25 @@ typeset -g ZESHY_PARCEL_NAME
 # ....................{ EXCEPTIONS                         }....................
 function die_if_parcel() {
     (( # == 1 || # == 2 )) ||
-        die 'Expected one parcel name and optional error message.'
+        :die 'Expected one parcel name and optional error message.'
     local parcel_name="${1}"
-    is_parcel "${parcel_name}" &&
-        die "${2-Parcel \"${parcel_name}\" already declared.}"
+    if { is_parcel "${parcel_name}" } {
+        :die "${2-Parcel \"${parcel_name}\" already declared.}"
+    }
 }
 
 function die_unless_parcel() {
     (( # == 1 || # == 2 )) ||
-        die 'Expected one parcel name and optional error message.'
+        :die 'Expected one parcel name and optional error message.'
     local parcel_name="${1}"
     is_parcel "${parcel_name}" ||
-        die "${2-Parcel \"${parcel_name}\" undeclared.}"
+        :die "${2-Parcel \"${parcel_name}\" undeclared.}"
 }
 
 # ....................{ TESTERS                            }....................
 function is_parcel() {
     # See is_map_key() for further details.
-    (( # == 1 )) || die 'Expected one parcel name.'
+    (( # == 1 )) || :die 'Expected one parcel name.'
     (( ${+ZESHY_PARCEL_NAME_TO_HELP[${1}]} ))
 }
 
@@ -153,7 +154,7 @@ function is_parcel() {
 
 function set_parcel() {
     # Validate sanity.
-    (( # == 1 )) || die 'Expected one parcel name.'
+    (( # == 1 )) || :die 'Expected one parcel name.'
     local parcel_name="${1}"
     die_unless_parcel "${parcel_name}"
 
@@ -164,9 +165,9 @@ function set_parcel() {
 function set_parcel_as_script() {
     # Validate sanity.
 #   print -r -- "args: ${*}"
-    (( # == 1 )) || die 'Expected one parcel name.'
+    (( # == 1 )) || :die 'Expected one parcel name.'
     local parcel_name="${1}"
-    [[ -f "${parcel_name}" ]] || die 'Script "'${parcel_name}'" not found.'
+    [[ -f "${parcel_name}" ]] || :die 'Script "'${parcel_name}'" not found.'
 
     # Convert the absolute path of such script to a parcel name.
     :convert_path_to_parcel parcel_name
@@ -180,18 +181,18 @@ function set_parcel_as_script() {
 #differently (i.e., in-place on a passed string variable name).
 function :convert_path_to_parcel() {
     # Validate sanity.
-    (( # == 1 )) || die 'Expected one string name.'
+    (( # == 1 )) || :die 'Expected one string name.'
     local string_name__cptp="${1}" parcel_name__cptp
     local -a parcel_name_list__cptp
 
     # If such string variable does not exist, throw an exception. See
     # :die_unless_string() for further details.
-    [[ "${(tP)string_name__cptp-}" == 'scalar'* ]] || die\
+    [[ "${(tP)string_name__cptp-}" == 'scalar'* ]] || :die\
         'Variable ${'${string_name__cptp}'} not found or not a string.'
 
     # Absolute or relative path of such parcel.
     parcel_name__cptp="${(P)string_name__cptp}"
-    [[ -e "${parcel_name__cptp}" ]] || die\
+    [[ -e "${parcel_name__cptp}" ]] || :die\
         'Parcel "'${parcel_name__cptp}'" not found.'
 
     # Canonicalize such path. Unfortunately, the simplistic approach performed
@@ -236,9 +237,8 @@ function :convert_path_to_parcel() {
             'Parcel "'${parcel_name__cptp}'" in no zeshy overlay and hence system-specific.'
     }
 
-    # Set such string to such name. See :set_string_to_string() for further
-    # details.
-    : "${(P)string_name__cptp::=${parcel_name__cptp}}"
+    # Set such path to such name.
+    :set_string_to_string "${string_name__cptp}" "${parcel_name__cptp}"
 }
 
 # ....................{ ADDERS                             }....................
@@ -254,7 +254,7 @@ function add_parcel_alias() {
     # Validate sanity. Since alias names can contain any character and
     # hence null used below to delimit alias names, escape nulls in such name.
     # See :define_alias_simple() for further details.
-    (( # == 2 )) || die 'Expected one parcel name and one alias name.'
+    (( # == 2 )) || :die 'Expected one parcel name and one alias name.'
     local parcel_name__apa="${1}" alias_name__apa="${2//$'\0'/\\$'\0'}"
     die_unless_parcel "${parcel_name__apa}"
 
@@ -271,7 +271,7 @@ function add_parcel_alias() {
 
 function add_parcel_function() {
     # See add_parcel_alias() for further details.
-    (( # == 2 )) || die 'Expected one parcel name and one function name.'
+    (( # == 2 )) || :die 'Expected one parcel name and one function name.'
     local parcel_name__apf="${1}" function_name__apf="${2//$'\0'/\\$'\0'}"
     die_unless_parcel "${parcel_name__apf}"
     if (( ${+ZESHY_PARCEL_NAME_TO_FUNCTION_NAMES[${parcel_name__apf}]} )) {
@@ -285,7 +285,7 @@ function add_parcel_global() {
     # Since global names can only contain identifier characters and hence *NOT*
     # null, nulls need not be escaped. See add_parcel_alias() for further
     # details.
-    (( # == 2 )) || die 'Expected one parcel name and one global name.'
+    (( # == 2 )) || :die 'Expected one parcel name and one global name.'
     local parcel_name__apg="${1}" global_name__apg="${2}"
     die_unless_parcel "${parcel_name__apg}"
     if (( ${+ZESHY_PARCEL_NAME_TO_GLOBAL_NAMES[${parcel_name__apg}]} )) {
@@ -300,14 +300,14 @@ function declare_parcel() {
     # Validate sanity. If such parcel has already been declared, throw
     # an exception. Since parcels are typically associated with absolute paths,
     # this shouldn't ever occur. Make sure it doesn't!
-    (( # == 2 )) || die 'Expected one parcel name and one help string.'
+    (( # == 2 )) || :die 'Expected one parcel name and one help string.'
     local  parcel_name="${1}" help="${2}"
 #   print -r -- "declaring parcel \"${parcel_name}\""
     die_if_parcel "${parcel_name}"
 
     # If such name is not a path (i.e., contains null characters), throw an
     # exception. See documentation for further details.
-    [[ "${parcel_name}" != *$'\0'* ]] || die\
+    [[ "${parcel_name}" != *$'\0'* ]] || :die\
         'Parcel "'${parcel_name}'" not a path (due to embedded null characters).'
 
     # Set the current parcel. See set_parcel() for further details.
@@ -321,12 +321,12 @@ function declare_parcel() {
 function declare_parcel_as_script() {
     # Validate sanity.
     (( # == 1 || # == 2 )) ||
-        die 'Expected optional script name and one help string.'
+        :die 'Expected optional script name and one help string.'
     local script_name="${ZESHY_SCRIPT_NAME}" help="${@[-1]}"
     if (( # == 2 )) {
         script_name="${1}"
     }
-    [[ -f "${script_name}" ]] || die\
+    [[ -f "${script_name}" ]] || :die\
         'Script "'${script_name}'" not found or not a file.'
 
     # Convert the absolute path of such script to a parcel name.
