Core documenters refactored.
Numerous @{*-start/*-declare/*-document} functions have been refactored for
both improved nomenclature and efficacy. Sadly, such refactoring exposed a core
error in :set_string_to_stdin_help(), which subsequent commits should
(...hopefully and not *TOO* terribly truculently) address.

diff --git a/src/00-start/00-declare/10-set b/src/00-start/00-declare/10-set
--- a/src/00-start/00-declare/10-set
+++ b/src/00-start/00-declare/10-set
@@ -46,7 +46,45 @@ function :set_string_to_string() {
     }
 }
 
-# ....................{ SETTERS ~ help                     }....................
+# ....................{ SETTERS ~ stdin                    }....................
+#FIXME: Document me.
+
+#FIXME: Enormous woops. "read -t 0" is destructive and terrible. To genuinely
+#test this, we'll need to both inline *AND* call
+#:is_stdin_readable_sans_blocking() here. While absurdly annoying, this is
+#certainly feasible.
+#FIXME: Ugh. We'll need to load the module defining zselect(), then. And, of
+#course, this implies zeshy to then be limited to only OSes defining select().
+#Isn't that most of them, however?
+#FIXME: O.K.; this works. We'll need to define a new parcel @{10-test} and
+#rename this parcel to @{15-set}. Shift :is_stdin_readable_sans_blocking() to
+#@{10-test}; then, refactor the setters below to call such function. We know;
+#this is terrible. But there you are!
+#FIXME: Don't forget to shift the zmodload() call below to @{10-test} too!
+
+# [status: bool] :set_string_to_stdin_help_if_found[
+#     args:  string string_name,
+#     stdin: string documentation]
+function :set_string_to_stdin_help_if_found() {
+    # Validate sanity.
+    (( # == 1 )) || :die 'Expected one string name.'
+
+    # Unfortunately, running "read -t 0" more than once on the same standard
+    # input stream appears to non-idempotently modify such stream in an
+    # unreliable manner (e.g., by erasing such stream). Since this is
+    # understandably horrible, avoid such bugs by inlining the implementation
+    # of :set_string_to_stdin_help() (rather than calling such function).
+    #
+    # If standard input is either the empty string *OR* unreadable without
+    # blocking, no such documentation was passed; in such case, report failure.
+    # See :set_string_to_stdin_help() for further details.
+    # read -t 0 || return 1
+    zselect -t 0 -a zselect_status -r 0 || return 1
+
+    # Set such string to standard input. See get_stdin() for further details.
+    :set_string_to_string "${1}" "$(< /dev/stdin)"
+}
+
 #FIXME: Replace *ALL* calls to run_runnable_with_stdin() with calls to this
 #function; then, excise the former.
 #FIXME: Document me.
@@ -57,7 +95,6 @@ function :set_string_to_string() {
 function :set_string_to_stdin_help() {
     # Validate sanity.
     (( # == 1 )) || :die 'Expected one string name.'
-    local string_name__sstdh="${1}"
 
     # If standard input is either the empty string *OR* unreadable without
     # blocking, throw an exception. See :is_stdin_readable_sans_blocking() for
@@ -84,12 +121,11 @@ function :set_string_to_stdin_help() {
     #
     # Given the earliness of this function, we adopt a single-line solution --
     # which, as an unfortunate by-product, prohibits empty documentation.
-    read -t 0 || :die\
+    zselect -t 0 -a zselect_status -r 0 || :die\
         'Documentation empty or not passed on standard input (e.g., as a here-document or -string).'
 
-    # Set such string to standard input and hence such documentation. See
-    # get_stdin() for further details.
-    :set_string_to_string "${string_name__sstdh}" "$(< /dev/stdin)"
+    # Set such string to standard input. See get_stdin() for further details.
+    :set_string_to_string "${1}" "$(< /dev/stdin)"
 }
 
 #FIXME: Document me.
@@ -175,19 +211,34 @@ function :set_map,list_to_func_prototype_attrs,names() {
 function :set_list_to_global_prototype_names() {
     # Validate sanity.
     (( # == 2 )) || :die 'Expected one list name and one global prototype.'
-    local placeholder__sltrpn
+    local 
+    local\
+        global_names_list_name__sltgpn="${1}"\
+        global_prototype__sltgpn="${2}"\
+        global_names_and_optional_value__sltgpn\
+        placeholder__sltgpn
+
+    # Strip the prefixing type (prefixed by optional whitespace and suffixed by
+    # mandatory spaces) from such prototype, thus leaving only the "="-
+    # delimited string of one or more global names and optional value required
+    # by the call below. Dismantled, this is:
+    #
+    # * "[[:space:]]#", matching optional prefixing whitespace.
+    # * "[^ ]##", matching such type.
+    # * " ##", matching one or more mandatory suffixing spaces.
+    global_names_and_optional_value__sltgpn="${global_prototype__sltgpn#[[:space:]]#[^ ]## ##}"
 
     # Parse such global names from such prototype. To centralize logic, also
     # parse such global value despite the caller not requesting such value --
-    # which we then promptly discard, along with the related exit status.
-    :set_list,string_to_global_prototype_names,value_if_value_or_names\
-        "${1}" placeholder__sltrpn "${2}" || true
+    # which we then promptly discard.
+    :set_list,string,bool_to_global_names,value,is_value\
+        "${global_names_list_name__sltgpn}"\
+        placeholder__sltgpn\
+        placeholder__sltgpn\
+        "${global_names_and_optional_value__sltgpn}"
 }
 
-#FIXME: Document me. Note that if such prototype defines no optional value,
-#such function reports failure whill still setting the first two passed
-#variables.
-
+#FIXME: Document me.
 #void :set_list,string,bool_to_global_names,value,is_value(
 #    string global_names_list_name,
 #    string global_value_string_name,
@@ -198,58 +249,58 @@ function :set_list,string,bool_to_global_names,value,is_value() {
     (( # == 4 )) || :die\
         'Expected one list name, one string name, one boolean name, and one "="-delimited string of one or more global names and optional value.'
     local\
-        global_names_list_name___sltgpn="${1}"\
-        global_value_string_name___sltgpn="${2}"\
-        global_is_value_bool_name___sltgpn="${3}"\
-        global_names_and_value__sltgpn="${4}"
-    [[ -n "${global_names_and_value__sltgpn}" ]] || :die\
+        global_names_list_name__slsbtgnviv="${1}"\
+        global_value_string_name__slsbtgnviv="${2}"\
+        global_is_value_bool_name__slsbtgnviv="${3}"\
+        global_names_and_value__slsbtgnviv="${4}"
+    [[ -n "${global_names_and_value__slsbtgnviv}" ]] || :die\
         'Global names and optional value empty.'
 
     # If any such variable is undefined or not of the expected type, throw an
     # exception. Since we call :set_string_to_string() below to set string
     # variables, avoid validating such variables here. See die_unless_list()
     # for further details.
-    [[ "${(tP)global_names_list_name___sltgpn-}" == 'array'* ]] || :die\
-        'List ${'${global_names_list_name___sltgpn}'} undefined or not a list.'
+    [[ "${(tP)global_names_list_name__slsbtgnviv-}" == 'array'* ]] || :die\
+        'List ${'${global_names_list_name__slsbtgnviv}'} undefined or not a list.'
 
     #FIXME: This PCRE isn't *QUITE* as flexible as it should be. Ideally, such
     #PCRE should accept *ANY* unquoted value not containing whitespace. At the
     #moment, it only accepts integer unquoted values.
 
     # If such prototype is syntactically invalid, throw an exception.
-    [[ "${global_names_and_value__sltgpn}" =~\
+    [[ "${global_names_and_value__slsbtgnviv}" =~\
         "${ZESHY_PROTOTYPE_GLOBAL_NAMES_VALUE_PCRE}" ]] || :die\
-        'Global names and/or value invalid:'$'\n'${global_names_and_value__sltgpn}
+        'Global names and/or value invalid:'$'\n'${global_names_and_value__slsbtgnviv}
 
     # If such match failed to capture such global's names, throw an exception.
     (( ${#match} )) || :die\
-        'Global names unparsable from prototype:'$'\n'${global_names_and_value__sltgpn}
+        'Global names unparsable from prototype:'$'\n'${global_names_and_value__slsbtgnviv}
 
     # If such prototype only declares one name, set such list to such name.
     if [[ -n "${match[1]}" ]] {
-        eval ${global_names_list_name___sltgpn}'=( "${match[1]}" )'
+        eval ${global_names_list_name__slsbtgnviv}'=( "${match[1]}" )'
     # Else, such prototype declares multiple equal signs-delimited names.
     # Unlike runnable prototype names, such names are prohibited from
     # containing equals signs and hence may be efficiently split on such.
     } else {
         # If such match failed to capture such names, throw an exception.
         (( ${#match} >= 2 )) || :die\
-            'Global names unparsable from prototype:'$'\n'${global_names_and_value__sltgpn}
+            'Global names unparsable from prototype:'$'\n'${global_names_and_value__slsbtgnviv}
 
         # Set such list to such names by splitting on equals signs.
-        eval ${global_names_list_name___sltgpn}'=( ${(s:=:)match[2]} )'
+        eval ${global_names_list_name__slsbtgnviv}'=( ${(s:=:)match[2]} )'
     }
 
     # If such value is defined, set such value and set such boolean to true.
     if (( ${#match} == 3 )) {
         :set_string_to_string\
-            "${global_type_string_name___sltgpn}" "${match[3]}"
+            "${global_type_string_name__slsbtgnviv}" "${match[3]}"
         :set_string_to_string\
-            "${global_is_value_bool_name___sltgpn}" 1
+            "${global_is_value_bool_name__slsbtgnviv}" 1
     # Else, set such boolean to false.
     } else {
         :set_string_to_string\
-            "${global_is_value_bool_name___sltgpn}" 0
+            "${global_is_value_bool_name__slsbtgnviv}" 0
     }
 }
 
@@ -541,6 +592,8 @@ function run_runnable_with_stdin() {
     #requires obtaining the transitive target of such file descriptor.
     #FIXME: Oh, *SCREW IT.* The current implementation is basically the only
     #sane implementation. We'll need to document why, of course. See above!
+    #FIXME: This is *HORRIBLY* broken. This so-called "test" is fundamentally
+    #broken. Ugh!
 
     # If standard input is empty, throw an exception. See
     # :is_stdin_readable_sans_blocking() for further details.
@@ -558,9 +611,17 @@ function run_runnable_with_stdin() {
     exec 0<&-
 }
 
-# --------------------( WASTELANDS                         )--------------------
-#FIXME: Document me.
+# ....................{ MAIN                               }....................
+# Load module "zselect", providing builtin zselect() required by standard
+# input-specific setters above (e.g., :set_string_to_stdin_help()).
+zmodload zsh/zselect
 
+# --------------------( WASTELANDS                         )--------------------
+# Note that if such prototype defines no optional value,
+#such function reports failure whill still setting the first two passed
+#variables.
+#, along with the related exit status.
+#FUXME: Document me.
 #[status: bool]
 #    :set_string,list,string_to_global_prototype_type,names,value_if_value(
 #        string global_type_string_name,
diff --git a/src/00-start/00-declare/20-document b/src/00-start/00-declare/20-document
--- a/src/00-start/00-declare/20-document
+++ b/src/00-start/00-declare/20-document
@@ -121,66 +121,127 @@
 # ....................{ GLOBALS                            }....................
 typeset -g ZESHY_HELP_SETTER_NAME_PREFIX=':set_string_to_help:'
 
-# ....................{ DOCUMENTERS                        }....................
+# ....................{ DOCUMENTERS ~ alias                }....................
 #FIXME: Document me.
 # void :document_alias_simple[stdin: string alias_documentation]
 function :document_alias_simple() {
     (( # == 0 )) || :die 'Expected no arguments.'
-    ::document_runnable_type_with_label 'alias_simple' 'Simple alias'
+    ::document_runnable_type,label_with_stdin 'alias_simple' 'Simple alias'
 }
 
 #FIXME: Document me.
 # void :document_alias_global[stdin: string alias_documentation]
 function :document_alias_global() {
     (( # == 0 )) || :die 'Expected no arguments.'
-    ::document_runnable_type_with_label 'alias_global' 'Global alias'
+    ::document_runnable_type,label_with_stdin 'alias_global' 'Global alias'
 }
 
 #FIXME: Document me.
 # void :document_alias_suffix[stdin: string alias_documentation]
 function :document_alias_suffix() {
     (( # == 0 )) || :die 'Expected no arguments.'
-    ::document_runnable_type_with_label 'alias_suffix' 'Suffix alias'
+    ::document_runnable_type,label_with_stdin 'alias_suffix' 'Suffix alias'
 }
 
+#FIXME: Document me.
+# void ::document_alias_with_type,prototype,stdin_if_found_or_noop[
+#    args: (
+#        string alias_name1, ...,
+#        string alias_type,
+#        string alias_prototype),
+#    stdin: string runnable_documentation]
+function ::document_alias_with_type,prototype,stdin_if_found_or_noop() {
+    # Validate sanity.
+    (( # >= 3 )) || :die\
+        'Expected one or more alias names, one alias type, and one alias prototype.'
+    local alias_type="${@[-2]}" alias_prototype="${@[-1]}"
+
+    # If such type is unrecognized, throw an exception.
+    [[ "${alias_type}" == ('simple'|'global'|'suffix') ]] || :die\
+        'Alias type "'${alias_type}'" unrecognized (i.e., neither "simple", "global", or "suffix").'
+
+    # If such documentation was passed, document such aliases.
+    ::document_operable_with_type,prototype,stdin_if_found_or_noop\
+        "${@[1,-3]}" "alias_${alias_type}" "${alias_prototype}"
+}
+
+# ....................{ DOCUMENTERS ~ func                 }....................
 #FIXME: Document me.
 # void :document_func[stdin: string func_documentation]
 function :document_func() {
     (( # == 0 )) || :die 'Expected no arguments.'
-    ::document_runnable_type_with_label 'func' 'Function'
+    ::document_runnable_type,label_with_stdin 'func' 'Function'
 }
 
+#FIXME: Document me.
+#FIXME: Replace with a new function ::document_func_with_type,prototype,stdin_if_found_or_noop() implemented as above.
+
+# void ::document_func_with_prototype,asciidoc(
+#     string func_name1, ...,
+#     string func_prototype,
+#     string func_asciidoc)
+function ::document_func_with_prototype,asciidoc() {
+    (( # >= 3 )) || :die\
+        'Expected one or more function names, one function prototype, and one asciidoc string.'
+    ::document_operable_with_type,prototype,asciidoc\
+        "${@[1,-3]}" 'func' "${@[-2]}" "${@[-1]}"
+}
+
+# ....................{ DOCUMENTERS ~ global               }....................
 #FIXME: Document me.
 # void :document_global[stdin: string global_documentation]
 function :document_global() {
     # Validate sanity.
     (( # == 0 )) || :die 'Expected no arguments.'
-    local global_help global_prototype global_asciidoc
-    local -a global_names
+    local global_help__dg global_prototype__dg global_asciidoc__dg
+    local -a global_names__dg
 
     # Documentation passed on standard input.
-    :set_string_to_stdin_help global_help
+    :set_string_to_stdin_help global_help__dg
 
     # Split such documentation into prototype and non-prototype portions.
     :set_strings_to_help_prototype,asciidoc\
-        global_prototype global_asciidoc "${global_help}"
-
-    #FIXME: Define such setter!
+        global_prototype__dg global_asciidoc__dg "${global_help__dg}"
 
     # Global name declared by such documentation's prototype.
-    :set_list_to_global_prototype_names global_names "${global_prototype}"
+    :set_list_to_global_prototype_names\
+        global_names__dg "${global_prototype__dg}"
 
     # Document such names.
-    ::document_operable_type_with_prototype,asciidoc\
-        "${global_names[@]}" 'global' "${global_prototype}" "${global_asciidoc}"
+    ::document_operable_with_type,prototype,asciidoc\
+        "${global_names__dg[@]}"\
+        'global'\
+        "${global_prototype__dg}"\
+        "${global_asciidoc__dg}"
 }
 
-# ....................{ DOCUMENTERS ~ private              }....................
+# ....................{ DOCUMENTERS ~ low-level            }....................
 #FIXME: Document me.
-# void ::document_runnable_type_with_label[
+# void ::document_operable_with_type,prototype,stdin_if_found_or_noop[
+#     args: (
+#        string operable_name1, ...,
+#        string operable_type,
+#        string operable_prototype),
+#     stdin: string runnable_documentation]
+function ::document_operable_with_type,prototype,stdin_if_found_or_noop() {
+    # Validate sanity.
+    (( # >= 3 )) || :die\
+        'Expected one or more operable names, one operable type, and one operable prototype.'
+    local operable_asciidoc__dotpwsifon
+
+    # If documentation was passed on standard input, document such operables
+    # with such documentation.
+    if { :set_string_to_stdin_help_if_found operable_asciidoc__dotpwsifon } {
+        ::document_operable_with_type,prototype,asciidoc\
+            "${@}" "${operable_asciidoc__dotpwsifon}"\
+    }
+}
+
+#FIXME: Document me.
+# void ::document_runnable_type,label_with_stdin[
 #     args: (string runnable_type, string runnable_label),
 #     stdin: string runnable_documentation]
-function ::document_runnable_type_with_label() {
+function ::document_runnable_type,label_with_stdin() {
     # Validate sanity.
     (( # == 2 )) || :die 'Expected one runnable type and one runnable label.'
     local\
@@ -203,59 +264,22 @@ function ::document_runnable_type_with_label() {
         runnable_names "${runnable_prototype}" "${runnable_label}"
 
     # Document such names.
-    ::document_operable_type_with_prototype,asciidoc\
+    ::document_operable_with_type,prototype,asciidoc\
         "${runnable_names[@]}"\
         "${runnable_type}"\
         "${runnable_prototype}"\
         "${runnable_asciidoc}"
 }
 
-#FIXME: Use of "typed" rather than "type" nomenclature is somewhat awkward.
-#Contemplate a global rename from the former to the latter.
-#FIXME: Indeed, rename to simply ::document_alias_type_prototype_asciidoc().
-
 #FIXME: Document me.
-# void ::document_alias_typed_with_prototype,asciidoc(
-#     string alias_name1, ...,
-#     string alias_type,
-#     string alias_prototype,
-#     string alias_asciidoc)
-function ::document_alias_typed_with_prototype,asciidoc() {
-    # Validate sanity.
-    (( # >= 4 )) || :die\
-        'Expected one or more alias names, one alias type, one alias prototype, and one asciidoc string.'
-    local alias_type="${@[-3]}"
+#FIXME: Suffix all locals with "__dotwpa", as globals are operables.
 
-    # If such type is unrecognized, throw an exception.
-    [[ "${alias_type}" == ('simple'|'global'|'suffix') ]] || :die\
-        'Alias type "'${alias_type}'" unrecognized (i.e., neither "simple", "global", or "suffix").'
-
-    # Document such alias.
-    ::document_operable_type_with_prototype,asciidoc\
-        "${@[1,-4]}" "alias_${alias_type}" "${@[-2]}" "${@[-1]}"
-}
-
-#FIXME: Rename to simply ::document_func_prototype_asciidoc().
-
-#FIXME: Document me.
-# void ::document_func_with_prototype,asciidoc(
-#     string func_name1, ...,
-#     string func_prototype,
-#     string func_asciidoc)
-function ::document_func_with_prototype,asciidoc() {
-    (( # >= 3 )) || :die\
-        'Expected one or more function names, one function prototype, and one asciidoc string.'
-    ::document_operable_type_with_prototype,asciidoc\
-        "${@[1,-3]}" 'func' "${@[-2]}" "${@[-1]}"
-}
-
-#FIXME: Document me.
-# void ::document_operable_type_with_prototype,asciidoc(
+# void ::document_operable_with_type,prototype,asciidoc(
 #     string operable_name1, ...,
 #     string operable_type,
 #     string operable_prototype,
 #     string operable_asciidoc)
-function ::document_operable_type_with_prototype,asciidoc() {
+function ::document_operable_with_type,prototype,asciidoc() {
     # Validate sanity.
     (( # >= 4 )) || :die\
         'Expected one or more operable names, one type string, one prototype string, and one asciidoc string.'
@@ -304,6 +328,70 @@ function ::document_operable_type_with_prototype,asciidoc() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+    # If standard input is either the empty string *OR* unreadable without
+    # blocking, no such documentation was passed; in such case, silently report
+    # succes. See :set_string_to_stdin_help() for further details.
+    # read -t 0 || return 0
+    # print 'stdin exists!'
+    # if { read -t 0 } {
+    #     print 'stdin exists.'
+    #     if { read -t 0 } {
+    #         print 'stdin still exists.'
+    #     }
+    # } else {
+    #     print 'stdin doesn''t exist!'
+    #     return 0
+    # }
+
+    # Documentation passed on standard input.
+    # :set_string_to_stdin_help operable_asciidoc__dotpwsifon
+
+    # # Document such names.
+    # ::document_operable_with_type,prototype,asciidoc\
+    #     "${@[1,-3]}"\
+    #     "${operable_type__dotpwsifon}"\
+    #     "${operable_prototype__dotpwsifon}"\
+    #     "${operable_asciidoc__dotpwsifon}"
+
+        # operable_type__dotpwsifon="${@[-2]}"\
+        # operable_prototype__dotpwsifon="${@[-1]}"\
+
+#FUXME: Use of "typed" rather than "type" nomenclature is somewhat awkward.
+#Contemplate a global rename from the former to the latter.
+#FUXME: Indeed, rename to simply ::document_alias_type_prototype,asciidoc().
+#FUXME: Actually, rename to
+#::document_stdin_with_alias_type,prototype,asciidoc_if_found_or_noop() and
+#refactor to internally call ::document_runnable_type,label_with_stdin() instead.
+#FUXME: Excise this.
+#FUXME: Document me.
+# void ::document_alias_typed_with_prototype,asciidoc(
+#     string alias_name1, ...,
+#     string alias_type,
+#     string alias_prototype,
+#     string alias_asciidoc)
+# function ::document_alias_typed_with_prototype,asciidoc() {
+#     # Validate sanity.
+#     (( # >= 4 )) || :die\
+#         'Expected one or more alias names, one alias type, one alias prototype, and one asciidoc string.'
+#     local alias_type="${@[-3]}"
+# 
+#     # If such type is unrecognized, throw an exception.
+#     [[ "${alias_type}" == ('simple'|'global'|'suffix') ]] || :die\
+#         'Alias type "'${alias_type}'" unrecognized (i.e., neither "simple", "global", or "suffix").'
+# 
+#     # Document such alias.
+#     ::document_operable_with_type,prototype,asciidoc\
+#         "${@[1,-4]}" "alias_${alias_type}" "${@[-2]}" "${@[-1]}"
+# }
+
+    # Shift such arguments off. See shift_arg_2() for further details.
+    # argv[1,2]=()
+
+    # (( # == 3 )) || :die\
+    #     'Expected one alias type, one alias prototype, and one asciidoc string.'
+#FUXME: Rename to ::document_func_prototype,asciidoc().
+    #FUXME: Define such setter!
+
     # # Validate sanity.
     # (( # >= 4 )) || :die\
     #     'Expected one or more alias names, one alias type, one alias prototype, and one asciidoc string.'
@@ -321,7 +409,7 @@ function ::document_operable_type_with_prototype,asciidoc() {
     #     'Alias type "'${alias_type}'" unrecognized (i.e., neither "simple", "global", or "suffix").'
 
     # # Document such alias.
-    # ::document_operable_type_with_prototype,asciidoc\
+    # ::document_operable_with_type,prototype,asciidoc\
     #     "${@}" "alias_${alias_type}" "${prototype}" "${asciidoc}"
 
     # # Validate sanity.
@@ -334,10 +422,10 @@ function ::document_operable_type_with_prototype,asciidoc() {
     # argv[-2,-1]=()
 
     # # Document such function.
-    # ::document_operable_type_with_prototype,asciidoc\
+    # ::document_operable_with_type,prototype,asciidoc\
     #     "${@}" 'func' "${prototype}" "${asciidoc}"
 
-#FUXME: Rename to ::document_operable_type_with_prototype,asciidoc().
+#FUXME: Rename to ::document_operable_with_type,prototype,asciidoc().
 #FUXME: Actually, rename to ::document_operable_with_prototype,asciidoc().
 
  # IMPORTANT: Note in such documentation that neither such
