:set_list_to_global_prototype_names().
A draft implementation of such function is complete.

diff --git a/src/00-start/00-declare/10-set b/src/00-start/00-declare/10-set
--- a/src/00-start/00-declare/10-set
+++ b/src/00-start/00-declare/10-set
@@ -7,6 +7,10 @@
 # are subsequently documented under @{help} in the main codebase.
 
 # ....................{ SETTERS                            }....................
+# Avoid defining comparable setters for non-scalar types (e.g., lists, maps)
+# here; such setters depend on considerably more functionality than we would be
+# willing to migrate here.
+
 # void :set_string_to_string(
 #     string string_name,
 #     string text1, ...)
@@ -142,6 +146,65 @@ function :set_list_to_alias_prototype_names() {
     ::set_list_to_runnable_prototype_names_with_label "${@}" 'Alias'
 }
 
+#FIXME: Document me.
+# void :set_list_to_global_prototype_names(
+#     string list_name, string global_prototype)
+function :set_list_to_global_prototype_names() {
+    # Validate sanity.
+    (( # == 2 )) || :die 'Expected one list name and one global prototype.'
+    local\
+        global_names_list_name___sltgpn="${1}"\
+        global_prototype__sltgpn="${2}"
+    [[ -n "${global_prototype__sltgpn}" ]] || :die 'Global prototype empty.'
+
+    # If any such variable is undefined or not of the expected type, throw an
+    # exception. See die_unless_list() for further details.
+    [[ "${(tP)global_names_list_name___sltgpn-}" == 'array'* ]] || :die\
+        'List ${'${global_names_list_name___sltgpn}'} undefined or not a list.'
+
+    # If such prototype is syntactically invalid, throw an exception.
+    [[ "${global_prototype__sltgpn}" =~\
+        "${ZESHY_PROTOTYPE_GLOBAL_TYPE_NAMES_VALUE_PCRE}" ]] || :die\
+        'Global prototype invalid:'$'\n'${global_prototype__sltgpn}
+
+    # If such match failed to capture such global's names, throw an exception.
+    (( ${#match} >= 4 )) || :die\
+        'Global names unparsable from prototype:'$'\n'${global_prototype__sltgpn}
+
+    # If such prototype only declares one name, set such list to such name.
+    if [[ -n "${match[2]}" ]] {
+        eval ${global_names_list_name___sltgpn}'=( "${match[2]}" )'
+    # Else, such prototype declares multiple equal sign-delimited names. Unlike
+    # runnable prototype names, such names are prohibited from containing equal
+    # signs and hence may be efficiently split on such delimiters.
+    } else {
+        #FIXME: Implement efficient splitting here.
+
+        # If such match failed to capture such names, throw an exception.
+        (( ${#prototype_matches__sltgpn} >= 3 )) || :die\
+            ${runnable_label__sltgpn}' names unparsable from prototype:'$'\n'${prototype__sltgpn}
+
+        # Compile such PCRE. See for_string_text_matching_pcre:() for further
+        # details.
+        pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_NAMES_NEXT_PCRE}"
+        pcre_study
+
+        # Match and append each such name to such list.
+        local ZPCRE_OP='0 0'
+        eval 'while {
+            pcre_match -b -n ${ZPCRE_OP[(w)2]} --\
+                "${prototype_matches__sltgpn[3]}"
+        } {
+            '${runnable_names_list_name___sltgpn}'+="${match[1]}"
+        }
+
+        # If such list remains empty, throw an exception.
+        (( ${#'${runnable_names_list_name___sltgpn}'} )) || :die\
+            ${runnable_label__sltgpn}'' names unsplittable from prototype:''$''\n''${prototype__sltgpn}
+        '
+    }
+}
+
 # ....................{ SETTERS ~ prototype : attrs,names  }....................
 #FIXME: Document me.
 #void :set_map,list_to_alias_prototype_attrs,names(
@@ -239,16 +302,16 @@ function ::set_map,list_to_runnable_prototype_attrs,names_with_label() {
     # If any such variable is undefined or not of the expected type, throw an
     # exception. See die_unless_map() and die_unless_list() for further details.
     [[ "${(tP)runnable_attrs_map_name__smltrpan-}" == 'association'* ]] || :die\
-        '${'${runnable_attrs_map_name__smltrpan}'} undefined or not a map.'
+        'Map ${'${runnable_attrs_map_name__smltrpan}'} undefined or not a map.'
     [[ "${(tP)runnable_names_list_name___smltrpan-}" == 'array'* ]] || :die\
-        '${'${runnable_names_list_name___smltrpan}'} undefined or not a list.'
+        'List ${'${runnable_names_list_name___smltrpan}'} undefined or not a list.'
 
     # If such prototype is syntactically invalid, throw an exception.
     [[ "${prototype__smltrpan}" =~\
         "${ZESHY_PROTOTYPE_RUNNABLE_ATTRS_NAMES_PCRE}" ]] || :die\
         ${runnable_label__smltrpan}' prototype invalid:'$'\n'${prototype__smltrpan}
 
-    # If such match failed to capture either such prototype's attributes or
+    # If such match failed to capture either such runnable's attributes or
     # names, throw an exception.
     # print -r -- "matches: ${match[*]} (${#match})"
     (( ${#match} >= 2 )) || :die\
@@ -471,6 +534,10 @@ function run_runnable_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+#FUXME: If we're going to go this far (and we certainly are), we'd might as
+#well also define setters for lists and maps, which we should then leverage
+#below inplace of inlined eval() statements.
+
 #FUXME: Call such function elsewhere rather than manually inlining such logic
 #everywhere. We should have probably done this *MUCH* sooner.
 
