Runnable prototype syntax expanded.
Such syntax now provides support for optional type validation (e.g.,
":string:list? list_name") and the return pseudotype ":full" (e.g.,
":full :return_everything(:void)"), ostensibly the antonym of existing return
pseudotype ":void". (And all's well, or as well as the present ever bides.)

diff --git a/src/00-start/00-declare/15-set b/src/00-start/00-declare/15-set
--- a/src/00-start/00-declare/15-set
+++ b/src/00-start/00-declare/15-set
@@ -11,9 +11,9 @@
 # here; such setters depend on considerably more functionality than we would be
 # willing to migrate here.
 
-# void :set_string_to_string(
-#     string string_name,
-#     string text1, ...)
+# :void :set_string_to_string(
+#     :string string_name,
+#     :string text1, ...)
 function :set_string_to_string() {
     # Validate sanity.
     (( # >= 2 )) || :die 'Expected one string name and one or more strings.'
@@ -227,13 +227,23 @@ function :set_list,string,bool_to_global_names,value,is_value() {
         'List ${'${global_names_list_name__slsbtgnviv}'} undefined or not a list.'
 
     #FIXME: This PCRE isn't *QUITE* as flexible as it should be. Ideally, such
-    #PCRE should accept *ANY* unquoted value not containing whitespace. At the
-    #moment, it only accepts integer unquoted values.
+    #PCRE should accept *ANY* unquoted value not containing whitespace. (Why?
+    #Because zsh assignments accept exactly that.) At the moment, it only
+    #accepts integer unquoted values.
 
     # If such prototype is syntactically invalid, throw an exception.
     [[ "${global_names_and_value__slsbtgnviv}" =~\
-        "${ZESHY_PROTOTYPE_GLOBAL_NAMES_VALUE_PCRE}" ]] || :die\
-        'Global declaration in parcel @{'${ZESHY_PARCEL_NAME}'} invalid:'$'\n'${global_names_and_value__slsbtgnviv}
+        "${ZESHY_PROTOTYPE_GLOBAL_NAMES_VALUE_PCRE}" ]] || {
+        # If such global resides in a parcel, state such parcel in the
+        # exception thrown below.
+        local in_parcel__slsbtgnviv
+        if [[ -n "${ZESHY_PARCEL_NAME-}" ]] {
+            in_parcel__slsbtgnviv='in parcel @{'${ZESHY_PARCEL_NAME}'}'
+        }
+
+        # Throw such exception.
+        :die 'Global declaration '${in_parcel__slsbtgnviv}' invalid:'$'\n'${global_names_and_value__slsbtgnviv}
+    }
 
     # If such match failed to capture such global's names, throw an exception.
     (( ${#match} )) || :die\
@@ -292,8 +302,17 @@ function ::set_string_to_runnable_prototype_name_with_label() {
 
     # If such prototype is syntactically invalid, throw an exception.
     [[ "${prototype__sstrpn}" =~\
-        "${ZESHY_PROTOTYPE_RUNNABLE_NAME_PCRE}" ]] || :die\
-        ${runnable_label__sstrpn}' prototype in parcel @{'${ZESHY_PARCEL_NAME}'} invalid or contains two or more runnable names:'${prototype__sstrpn}
+        "${ZESHY_PROTOTYPE_RUNNABLE_NAME_PCRE}" ]] || {
+        # If such runnable resides in a parcel, state such parcel in the
+        # exception thrown below.
+        local in_parcel__sstrpn
+        if [[ -n "${ZESHY_PARCEL_NAME-}" ]] {
+            in_parcel__sstrpn='in parcel @{'${ZESHY_PARCEL_NAME}'}'
+        }
+
+        # Throw such exception.
+        :die ${runnable_label__sstrpn}' prototype '${in_parcel__sstrpn}' invalid or contains two or more runnable names:'${prototype__sstrpn}
+    }
 
     # If such name was *NOT* captured into ${match[1]}, throw an exception.
     (( ${#match} )) || :die\
@@ -367,8 +386,17 @@ function ::set_map,list,string_to_runnable_prototype_attrs,names,args_with_label
 
     # If such prototype is syntactically invalid, throw an exception.
     [[ "${prototype__smltrpan}" =~\
-        "${ZESHY_PROTOTYPE_RUNNABLE_ATTRS_NAMES_ARGS_PCRE}" ]] || :die\
-        ${runnable_label__smltrpan}' prototype in parcel @{'${ZESHY_PARCEL_NAME}'} invalid:'$'\n'${prototype__smltrpan}
+        "${ZESHY_PROTOTYPE_RUNNABLE_ATTRS_NAMES_ARGS_PCRE}" ]] || {
+        # If such runnable resides in a parcel, state such parcel in the
+        # exception thrown below.
+        local in_parcel__smltrpan
+        if [[ -n "${ZESHY_PARCEL_NAME-}" ]] {
+            in_parcel__smltrpan='in parcel @{'${ZESHY_PARCEL_NAME}'}'
+        }
+
+        # Throw such exception.
+        :die ${runnable_label__smltrpan}' prototype '${in_parcel__smltrpan}' invalid:'$'\n'${prototype__smltrpan}
+    }
 
     # If such match failed to capture either such runnable's attributes or
     # names, throw an exception.
