New @{*-start/*-declare/*-test} functionality.
Such exception handler and tester functions obsolete similar functions defined
by subsequent parcel @{*-main/var/type}. Naturally, this breaks the latter,
which the subsequent commit intends to bleakly tidy up.

diff --git a/src/00-start/00-declare/15-set b/src/00-start/00-declare/15-set
--- a/src/00-start/00-declare/15-set
+++ b/src/00-start/00-declare/15-set
@@ -7,12 +7,35 @@
 # subsequently documented under @{help} in the main codebase.
 
 # ....................{ SETTERS                            }....................
-# Avoid defining comparable setters for non-scalar types (e.g., lists, maps)
-# here; such setters depend on considerably more functionality than we would be
-# willing to migrate here.
+# :void :set_int_to_int(:string:int int_name, :int number)
+function :set_int_to_int() {
+    # Validate sanity.
+    (( # >= 2 )) || :die 'Expected one integer name and one or more integers.'
+    local int_name__siti="${1}" int__siti="${2}"
+
+    #FIXME: Define such handlers. (Ugh.)
+    :die_unless_var_int "${int_name__siti}"
+    :die_unless_int "${int__siti}"
+
+    # Set such integer via assignment indirection.
+    : "${(P)int_name__siti::=${int__siti}}"
+}
+
+# :void :set_list_to_string(
+#     :string:list list_name,
+#     :string text1, ...)
+function :set_list_to_string() {
+    # Validate sanity.
+    (( # >= 2 )) || :die 'Expected one list name and one or more strings.'
+    local list_name__slts="${1}"
+    :die_unless_list "${list_name__slts}"
+
+    # Set such list to such strings.
+    set -A "${list_name__slts}" "${@[2,-1]}"
+}
 
 # :void :set_string_to_string(
-#     :string string_name,
+#     :string:string string_name,
 #     :string text1, ...)
 function :set_string_to_string() {
     # Validate sanity.
@@ -202,13 +225,6 @@ function :set_list,string,bool_to_global_names,value,is_value() {
     [[ -n "${global_names_and_value__slsbtgnviv}" ]] || :die\
         'Global names and optional value empty.'
 
-    # If any such variable is undefined or not of the expected type, throw an
-    # exception. Since we call :set_string_to_string() below to set string
-    # variables, avoid validating such variables here. See die_unless_list()
-    # for further details.
-    [[ "${(tP)global_names_list_name__slsbtgnviv-}" == 'array'* ]] || :die\
-        'List ${'${global_names_list_name__slsbtgnviv}'} undefined or not a list.'
-
     #FIXME: This PCRE isn't *QUITE* as flexible as it should be. Ideally, such
     #PCRE should accept *ANY* unquoted value not containing whitespace. (Why?
     #Because zsh assignments accept exactly that.) At the moment, it only
@@ -217,6 +233,15 @@ function :set_list,string,bool_to_global_names,value,is_value() {
     # If such prototype is syntactically invalid, throw an exception.
     [[ "${global_names_and_value__slsbtgnviv}" =~\
         "${ZESHY_PROTOTYPE_GLOBAL_NAMES_VALUE_PCRE}" ]] || {
+        #FIXME: Overly redundant. We probably want a new private getter (for
+        #simplicity, since efficiency doesn't matter here), resembling:
+        #function ::get_parcel_if_found_or_noop() {
+        #    (( # == 0 )) || :die 'Expected no arguments.'
+        #    if [[ -n "${ZESHY_PARCEL_NAME-}" ]] {
+        #        print -r 'in parcel @{'${ZESHY_PARCEL_NAME}'}'
+        #    }
+        #}
+
         # If such global resides in a parcel, state such parcel in the
         # exception thrown below.
         local in_parcel__slsbtgnviv
@@ -234,7 +259,8 @@ function :set_list,string,bool_to_global_names,value,is_value() {
 
     # If such prototype only declares one name, set such list to such name.
     if [[ -n "${match[1]}" ]] {
-        set -A "${global_names_list_name__slsbtgnviv}" "${match[1]}"
+        :set_list_to_string\
+            "${global_names_list_name__slsbtgnviv}" "${match[1]}"
     # Else, such prototype declares multiple equal signs-delimited names.
     # Unlike runnable prototype names, such names are prohibited from
     # containing equals signs and hence may be efficiently split on such.
@@ -244,25 +270,19 @@ function :set_list,string,bool_to_global_names,value,is_value() {
             'Global names unparsable from prototype:'$'\n'${global_names_and_value__slsbtgnviv}
 
         # Set such list to such names by splitting on equals signs.
-        set -A "${global_names_list_name__slsbtgnviv}" ${(s:=:)match[2]}
+        :set_list_to_string\
+            "${global_names_list_name__slsbtgnviv}" "${(s:=:)match[2]}"
     }
 
     # If such value is defined, set such value and set such boolean to true.
     if (( ${#match} == 3 )) {
         :set_string_to_string\
             "${global_type_string_name__slsbtgnviv}" "${match[3]}"
-
-        #FIXME: Such call *WILL* fail both here and below, as such variable is
-        #an integer rather than a string. We'll need to define a new
-        #:set_int_to_int() function -- which, happily, is quite a bit simpler
-        #than :set_string_to_string(), due to the former *NOT* supporting
-        #concatenation of multiple passed integers.
-
-        :set_string_to_string\
+        :set_int_to_int\
             "${global_is_value_bool_name__slsbtgnviv}" 1
     # Else, set such boolean to false.
     } else {
-        :set_string_to_string\
+        :set_int_to_int\
             "${global_is_value_bool_name__slsbtgnviv}" 0
     }
 }
@@ -360,13 +380,6 @@ function ::set_map,list,string_to_runnable_prototype_attrs,names,args_with_label
     [[ -n "${prototype__smltrpan}" ]] || :die\
         ${runnable_label__smltrpan}' prototype empty.'
 
-    # If any such variable is undefined or not of the expected type, throw an
-    # exception. See die_unless_map() and die_unless_list() for further details.
-    [[ "${(tP)runnable_attrs_map_name__smltrpan-}" == 'association'* ]] || :die\
-        'Map ${'${runnable_attrs_map_name__smltrpan}'} undefined or not a map.'
-    [[ "${(tP)runnable_names_list_name___smltrpan-}" == 'array'* ]] || :die\
-        'List ${'${runnable_names_list_name___smltrpan}'} undefined or not a list.'
-
     # If such prototype is syntactically invalid, throw an exception.
     [[ "${prototype__smltrpan}" =~\
         "${ZESHY_PROTOTYPE_RUNNABLE_ATTRS_NAMES_ARGS_PCRE}" ]] || {
@@ -396,7 +409,10 @@ function ::set_map,list,string_to_runnable_prototype_attrs,names,args_with_label
     # double-quoted values may contain commas, such attributes must be
     # iteratively matched with a PCRE rather than split on commas.
     if [[ -n "${prototype_matches__smltrpan[1]}" ]] {
+        #FIXME: Arguably, we should just define :clear_map() here.
+        # Validate sanity.
         local runnable_attrs_map_key__smltrpan
+        :die_unless_map "${runnable_attrs_map_name__smltrpan}"
 
         # Clear such map. See :clear_map() for further details.
         set -A "${runnable_attrs_map_name__smltrpan}"
@@ -425,15 +441,18 @@ function ::set_map,list,string_to_runnable_prototype_attrs,names,args_with_label
 
     # If such prototype only declares one name, set such list to such name.
     if [[ -n "${prototype_matches__smltrpan[2]}" ]] {
-        set -A\
+        :set_list_to_string\
             "${runnable_names_list_name___smltrpan}"\
             "${prototype_matches__smltrpan[2]}"
     # Else, such prototype declares multiple comma-delimited names. Since
     # single- and double-quoted runnable names may contain commas, such names
     # must be iteratively matched with a PCRE rather than split on commas.
     } else {
+        #FIXME: Arguably, we should just define :clear_list() here.
+        # Validate sanity.
         local runnable_names_list_item__smltrpan
         integer runnable_names_list_index__smltrpan=0
+        :die_unless_list "${runnable_names_list_name___smltrpan}"
 
         # If such match failed to capture such names, throw an exception.
         (( ${#prototype_matches__smltrpan} >= 3 )) || :die\
@@ -625,6 +644,32 @@ function run_runnable_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+    # # If any such variable is undefined or not of the expected type, throw an
+    # # exception. See die_unless_map() and die_unless_list() for further details.
+    # [[ "${(tP)runnable_attrs_map_name__smltrpan-}" == 'association'* ]] || :die\
+    #     'Map ${'${runnable_attrs_map_name__smltrpan}'} undefined or not a map.'
+    # [[ "${(tP)runnable_names_list_name___smltrpan-}" == 'array'* ]] || :die\
+    #     'List ${'${runnable_names_list_name___smltrpan}'} undefined or not a list.'
+
+        #FUXME: Such call *WILL* fail both here and below, as such variable is
+        #an integer rather than a string. We'll need to define a new
+        #:set_int_to_int() function -- which, happily, is quite a bit simpler
+        #than :set_string_to_string(), due to the former *NOT* supporting
+        #concatenation of multiple passed integers.
+
+#FUXME: Replace all calls to :set_list_to_string() with calls to this.
+
+    # If any such variable is undefined or not of the expected type, throw an
+    # exception. Since we call :set_string_to_string() below to set string
+    # variables, avoid validating such variables here. See die_unless_list()
+    # for further details.
+    # [[ "${(tP)global_names_list_name__slsbtgnviv-}" == 'array'* ]] || :die\
+    #     'List ${'${global_names_list_name__slsbtgnviv}'} undefined or not a list.'
+
+# Avoid defining comparable setters for non-scalar types (e.g., lists, maps)
+# here; such setters depend on considerably more functionality than we would be
+# willing to migrate here.
+
 #FUXME: Enormous woops. "read -t 0" is destructive and terrible. To genuinely
 #test this, we'll need to both inline *AND* call
 #:is_stdin_readable_sans_blocking() here. While absurdly annoying, this is
