Function definers defined earlier.
@{*-start/*-declare/*-func} now defines both :define_func() and
:redefine_func(), in orthogonal fashion to those @{*-alias} defines. Such
functions are core to the definition of :declare_func_() and cohorts.
Thankfully, they made the transition with little difficulty and much comfort.

diff --git a/src/00-start/00-declare/40-func b/src/00-start/00-declare/40-func
--- a/src/00-start/00-declare/40-func
+++ b/src/00-start/00-declare/40-func
@@ -103,9 +103,42 @@ defining, other functions).
 typeset -g ZESHY_DECLARE_FUNC_PROTOTYPE__
 
 # ....................{ ALIASES                            }....................
+#FIXME: O.K.; this is great, but there's a wee annoying flaw: syntax errors.
+#They'll be reported as errors for a function named "::func", which isn't
+#helpful in the least. Perhaps more importantly, they'll be largely unhelpful,
+#as current syntax errors are. Fortunately, both are correctable by:
+#
+#* Embedding such definition in a :try{...}:catch{...}:catch block. Yes, this
+#  *DOES* incur a slight performance penalty, but... *shrug* The demonstrable
+#  gain in significantly more readable syntax errors than we currently receive
+#  makes this an absolutely beneficial tradeoff.
+#* Ah! Sweet. Great. So, the "catch" portion of that block will need to match
+#  "${EXCEPTION}" against a glob matching only function definition errors.
+#  Fortunately, that's *VERY* easy to match. How? Just check :redefine_func().
+#  We already do it there.
+#* So, we'll need to strip that glob out into a new string global -- say,
+#  ${ZESHY_FUNC_ERROR_GLOB}.
+#* If '"${EXCEPTION}" == ${~ZESHY_FUNC_ERROR_GLOB}', we'll need to:
+#  * Catch such exception. Problem is, we haven't defined such functionality
+#    yet! *Ugh.* On the bright side, such functionality *SHOULD* be fairly
+#    simple to inline here. That said, do we *REALLY* want to walk that road?
+#    We might need such catching elsewhere in @{*-declare}. In such case,
+#    consider shifting such functionality to a new parcel here -- say,
+#    @{15-catch}.
+#  * Throw a new exception describing such error. Unfortunately, since the
+#    function failed to be defined, we can't reuse the core of :redefine_func()
+#    printing the function line of such syntax error. Well, shucks. We *COULD*
+#    conceivably get around that by examining the current call stack and
+#    manually parsing such file for such function definition. We'll probably
+#    have to end up doing that. But it's a bit overkill for the moment. For
+#    now, just replace the "::func" in such error message with the actual
+#    function name and clean the message up a bit (e.g., capitalizing such
+#    message), as :redefine_func() currently does. Nice!
+
 #FIXME: Document me. Probably the most interesting documentation to be included
 #is the commentary below beginning:
 #   "# Technically, doing so redefines such function at least twice:"
+
 alias ':declare_func{'='function ::func() {'
 
 #FIXME: Document me.
@@ -198,13 +231,13 @@ function ::declare_func() {
 
 #FIXME: Document me.
 # void :declare_func[
-#    args: (string func_prototype, string func_definition),
+#    args: (string func_prototype, string func_body),
 #    stdin: string func_asciidoc]
 function :declare_func() {
     # Validate sanity.
     (( # == 2 )) || :die\
-        'Expected one function prototype and one function definition.'
-    local func_prototype="${1}" func_code="${2}" func_asciidoc
+        'Expected one function prototype and one function body.'
+    local func_prototype="${1}" func_body="${2}" func_asciidoc
     local -A func_attrs
     local -a func_names
 
@@ -218,13 +251,8 @@ function :declare_func() {
     # For each such function...
     local func_name
     for   func_name ("${func_names[@]}") {
-        #FIXME: O.K.; we'll need to shift such functionality here. This is
-        #fairly important, as such functionality performs several nice safety
-        #checks on our behalf (e.g., ensuring such function isn't currently
-        #defined and such).
-
-        # Define such alias.
-        :define_func "${func_name}" "${func_code}"
+        # Define such function.
+        :define_func "${func_name}" "${func_body}"
 
         # If such prototype declared attributes, handle such attributes.
         if (( ${#func_attrs} )) {
@@ -247,6 +275,165 @@ function :declare_func() {
         # Add such function to the current parcel.
         add_parcel_function "${ZESHY_PARCEL_NAME}" "${func_name}"
     }
+}
+
+# ....................{ DEFINERS                           }....................
+# void :define_func(string function_name, string function_body)
+function :define_func() {
+    # Validate sanity.
+    (( # == 2 )) || :die 'Expected one function name and one function body.'
+    local function_name="${1}"
+
+    # If such function already exists, throw an exception.
+    if (( ${+functions[${function_name}]} )) {
+        :die "Function ${function_name}() already exists:"$'\n'"$(which -- "${function_name}")"
+    }
+
+    # Define such function.
+    :redefine_func "${@}"
+}
+
+# void :redefine_func(string function_name, string function_body)
+function :redefine_func() {
+    # Validate sanity.
+    (( # == 2 )) || :die 'Expected one function name and one function body.'
+    local func_name="${1}" func_body="${2}" func
+    [[ -n "${func_name}" ]] || :die 'Function name empty.'
+#   :output_line_if_debugging "zeshy: defining ${func_name}()..."
+
+    # Function to be redefined. For obscure error handling reasons, we
+    # interpolate such function into several eval() calls below. Dismantled,
+    # this is:
+    #
+    # * "(q)", quote protecting the name of such function. Since zsh permits
+    #   such name to contain arbitrary shell-reserved characters (e.g., "("),
+    #   such protection avoids obscure errors on names with such characters.
+    #
+    # Technically, such redefinition is also implementable with the following
+    # efficient alternative avoiding such eval() statements:
+    #
+    #    { unfunction "${func_name}" } :silent_stderr or ignore_failure
+    #    { functions[${func_name}]="${func_body}" } :silent_stderr
+    #    (( ${+functions[${func_name}]} )) or {
+    #         :string func_error; func_error="$({
+    #             functions[${func_name}]="${func_body}"
+    #         } to_stdout:)"
+    #
+    # Such alternative *DOES* work but omits line numbers in parse errors,
+    # preventing zeshy from throwing human-readable parse exceptions (e.g.,
+    # on syntactic errors, the above alternative prints errors resembling
+    # "zsh: parse error near `}'" rather than
+    # "(eval):2: parse error near `}'"). Since human-readability of exception
+    # messages is considerably more important than simplicity of implementation,
+    # we retain the current eval()-based approach.
+    func='function '${(q)func_name}' () {'$'\n'${func_body}$'\n''}'
+
+    # Redefine such function. If such redefinition fails, zsh emits an error to
+    # standard error and reports failure, inducing zeshy to throw an exception
+    # resembling "(eval):2: parse error near `]]'". For readability, capture
+    # and convert such error into a human-readable exception message.
+    { eval "${func}" } 2>/dev/null || {
+        local func_error
+
+        # Temporarily enable shell option "EVAL_LINENO", ensuring the line
+        # number zsh embeds in the error captured below will be relative to
+        # such function body rather than to this function redefine_error(). See
+        # :enable_option_local() for further details.
+        setopt -- local_options eval_lineno
+
+        # Capture such output, ignoring the expected failure.
+        func_error="$({ eval "${func}" } 1>2 || true)"
+        # output_string_to_stderr "error: ${func_error}"
+
+        # If such error message is in canonical zsh format (e.g.,
+        # "(eval):244: parse error near `()'"), convert such message to
+        # human-readable form. In particular, append the actual line of code in
+        # such function body inducing such error. Dismantled, this is:
+        #
+        # * "(#b)", enabling match group capturing.
+        # * "(<->##)", matching such line as one or more digits into
+        #   ${match[1]}. See :is_int() for further details.
+        # * "(*)", matching the actual error message into ${match[2]}.
+        if [[ "${func_error}" == (#b)'(eval):'(<->##)': '(*) ]] {
+            integer line_number line_number_start line_number_stop
+            local func_error_message func_context
+            local -a func_lines
+
+            # Line number of such error.
+            line_number="${match[1]}"
+
+            # Parse error emitted by zsh, stripped of delimiting whitespace.
+            func_error_message="${${match[2]##[[:space:]]##}%%[[:space:]]##}"
+
+            # Capitalize the first character of such error. (Unfortunately,
+            # parameter expansion flag "(C)" capitalizes the first character of all
+            # words of such parameter.)
+            func_error_message[1]="${(C)func_error_message[1]}"
+
+            # Line number of the second lines preceding and succeeding such error,
+            # for textual context.
+            line_number_start=$(( line_number - 2 ))
+            line_number_stop=$((  line_number + 2 ))
+
+            # List of function definition lines. See set_list_to_string_lines() for
+            # further details.
+            func_lines=( "${(@f)func}" )
+
+            # Constrain such numbers to [1, ${max_line_number}], where
+            # ${max_line_number} is the number of lines in such function body.
+            if (( line_number_start < 1 )) {
+                  line_number_start=1
+            }
+            if (( line_number_stop > ${#func_lines} )) {
+                  line_number_stop=${#func_lines}
+            }
+
+            # Constrain such start to be less than or equal to such stop.  While
+            # this shouldn't be necessary, a wee caution never hurts.
+            if (( line_number_start > line_number_stop )) {
+                  line_number_start=${line_number_stop}
+            }
+
+            #FIXME: Hardly an ideal implementation. Ideally, we should implement
+            #a function leveraging color styles printing such textual context
+            #with decent aesthetics. To do so, we'll need test here whether such
+            #function exists; if it does, call it, passing such call
+            #"${func_body}" and the desired function line; else, defer
+            #to the default implementation below. (Actually, don't we have an
+            #existing function for numbering arbitrary code lines? I recall such
+            #function requiring a bit of touch-up, as well...)
+
+            # Append each such line prefixed by its line number to such string.
+            # print 'ok'
+            # print "line_number: ${line_number}"
+            # print "line_number_start: ${line_number_start}"
+            # print "line_number_stop: ${line_number_stop}"
+            # print "#func_lines: ${#func_lines}"
+            # print "func:"
+            # output_string "${func}" | command nl
+            integer line_number
+            for     line_number ({${line_number_start}..${line_number_stop}}) {
+                # print "i: ${i}"
+                func_context+="${ZESHY_ASCII_NEWLINE} [${line_number}]  ${func_lines[${line_number}]}"
+            }
+            # print 'ko'
+
+            # Set such error message.
+            func_error="${func_error_message} on line ${line_number} of function ${func_name}():${ZESHY_ASCII_NEWLINE}${func_context}"
+        }
+
+        # Throw such exception.
+        :die "${func_error}"
+    }
+#    print -r -- "function \"${func_name}\" () {
+#    ${func_body}
+#}"
+
+    # If prior logic succeeded but such function remains undefined, throw an
+    # exception. Technically, this should never happen. Since it occasionally
+    # does, avoid silent regressions with efficient precautions.
+    (( ${+functions[${func_name}]} )) || :die\
+        "Function ${func_name}() undefinable (e.g., due to zeshy regressions):"$'\n'"${func_body}"
 }
 
 # ....................{ OBSOLETE                           }....................
@@ -357,6 +544,21 @@ function declare_function_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+        # # If such exception handler exists, defer to such handler.
+        # if (( ${+functions[::die_with_func_error]} )) {
+        #     ::die_with_func_error "${func}"
+        # # Else, redefine such function again. Since the prior exception handler
+        # # *SHOULD* always exist, this fallback will probably never see the
+        # # light of day. Which is good, because the output is terrible.
+        # } else {
+        #     eval "${func}"
+        # }
+
+        #FUXME: O.K.; we'll need to shift such functionality here. This is
+        #fairly important, as such functionality performs several nice safety
+        #checks on our behalf (e.g., ensuring such function isn't currently
+        #defined and such).
+
     # Such
     # correlation allows a raft of , including .
 
