Conditionally declared functions refactored.
Most function body prefixes for such functions no longer perform argument
validation, as low-level function declarers now do so implicitly.

diff --git a/src/00-start/00-declare/40-func b/src/00-start/00-declare/40-func
--- a/src/00-start/00-declare/40-func
+++ b/src/00-start/00-declare/40-func
@@ -103,6 +103,39 @@ defining, other functions).
 #    "void function").
 #  * It's the obvious antonym of void and equally as many characters, sufficing
 #    for the pendant in all of us.
+#FIXME: It could also be nice to concoct opt-in syntax for having zeshy
+#automatically synthesize argument localization on behalf of declared
+#functions. This should absolutely *NOT* happen by default (...just consider
+#functions accepting variable names, for example), necessitating we devise no
+#syntax. Since such syntax should apply to the *ENTIRE* argument list (i.e.,
+#either zeshy localizes *ALL* passed arguments or it localizes none), there
+#exist a number of approaches:
+#
+#1. A new runnable attribute "<localize>" (e.g.,
+#   "<localize> :void :my_func(:string my_arg)").
+#
+#O.K.; forget the other approaches. The above is pretty awesome. It's a wee
+#verbose, yes: but given the import, this doesn't seem horribly out of place.
+#Indeed, we could then provide a second related attribute for localizing
+#attributes suffixed by a function name-derived acronym. Wait; that's actually
+#*VERY* bad, as functions defined by such a function would silently alter their
+#definition (thus almost certainly breaking) on mere function renames, which is
+#horrible. So *NEVER, EVER* go down that road. (Thanks.)
+#
+#Anyway: the above approach fairly rocks. So, hey-ho: let's go.
+
+#FIXME: Replace the current "<globbable>" attribute by a new argument
+#pseudo-type ":glob", which function parsing should then internally detect and
+#set a local boolean if at least one argument has such type: e.g.,
+#
+#    # Shift from this...
+#    <globbable> [status = :bool] :is_string_matches_glob(
+#        :string text, :string glob)
+#
+#    # ...to this.
+#    [status = :bool] :is_string_matches_glob(:string text, :glob glob)
+#
+#I think we can all agree the latter to be demonstrably superior.
 
 #FIXME: I'm beginning to question the wisdom of maintaining separate
 #"_with_stdin" versions. Since AsciiDoc syntax *FUNDAMENTALLY* conflicts with
@@ -284,39 +317,6 @@ function ::declare_func_stop() {
     local func_preamble
     integer arg_count_min=0 arg_count_max=0 func_is_variadic=0
 
-    # Human-readable names of canonical list global ${match} indices. While
-    # such indices are both unnecessary and slightly inefficient, their use
-    # dramatically improves the readability and stability of argument parsing.
-    # Likewise, declaring such integer locals as globals would slightly
-    # mitigate such inefficiency at a cost of harming such stability (as such
-    # globals could be externally unset at any time). In the end, the current
-    # implementation seems a sensible tradeoff on all fronts.
-    #
-    # The current argument's mandatory type.
-    integer -r arg_match_index_type=1
-
-    # The current argument type's optional eroteme (i.e., "?"), signifying that
-    # such function's definition should *NOT* be prefixed by a call to an
-    # exception handler throwing an exception if such argument violates the
-    # constraints of such type (e.g., a non-numeric string passed where an
-    # integer was expected). If unspecified, such definition is prefixed by
-    # such a call.
-    integer -r arg_match_index_type_is_unvalidated=2
-
-    # The current argument's mandatory name.
-    integer -r arg_match_index_name=3
-
-    # The current argument's optional eroteme (i.e., "?"), signifying such
-    # argument to be optional. If unspecified, such argument is mandatory.
-    integer -r arg_match_index_is_optional=4
-
-    # The current argument's optional default value.
-    integer -r arg_match_index_value=5
-
-    # The current argument's optional ellipse (i.e., "..."), signifying such
-    # argument and hence function to be variadic.
-    integer -r arg_match_index_is_variadic=6
-
     #FIXME: Getting a bit old, honestly. Just declare appropriate type testers
     #and exception handlers in @{*-test}. Sadly, this implies pretty much
     #shifting the *ENTIRETY* of @{var/type} into @{*-test} -- but it's
@@ -326,60 +326,13 @@ function ::declare_func_stop() {
     # If any such variable is either undefined or of unexpected type, throw an
     # exception. See die_unless_string(), die_unless_map(), and
     # die_unless_list() for further details.
-    [[ "${(t)ZESHY_DECLARE_FUNC_PROTOTYPE__-}${(t)ZESHY_DECLARE_FUNC_ARGS__-}" == 'scalar'*'scalar'* ]] || :die\
-        'Strings ${ZESHY_DECLARE_FUNC_PROTOTYPE__} and/or ${ZESHY_DECLARE_FUNC_ARGS__} undefined or not strings (e.g., as :declare_func_() not previously called).'
-    [[ "${(t)ZESHY_DECLARE_FUNC_ATTRS__-}" == 'association'* ]] || :die\
-        'Map ${ZESHY_DECLARE_FUNC_ATTRS__} undefined or not a map.'
-    [[ "${(t)ZESHY_DECLARE_FUNC_NAMES__-}" == 'array'* ]] || :die\
-        'List ${ZESHY_DECLARE_FUNC_NAMES__} undefined or not a list.'
+    :die_unless_string ZESHY_DECLARE_FUNC_PROTOTYPE__ ZESHY_DECLARE_FUNC_ARGS__
+    :die_unless_map  ZESHY_DECLARE_FUNC_ATTRS__
+    :die_unless_list ZESHY_DECLARE_FUNC_NAMES__
 
-    # If such argument string is *NOT* the empty string, such function accepts
-    # at least one argument. In such case, parse such arguments.
-    [[ -n "${ZESHY_DECLARE_FUNC_ARGS__}" ]] || {
-        # Compile such PCRE. See for_string_text_matching_pcre:() for further
-        # details.
-        pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_ARGS_NEXT_PCRE}"
-        pcre_study
-
-        # Parse each such argument into canonical list global ${match}, whose
-        # indices we localize as human-readable integers above.
-        local ZPCRE_OP='0 0'
-        while {
-            pcre_match -b -n ${ZPCRE_OP[(w)2]} -- "${ZESHY_DECLARE_FUNC_ARGS__}"
-        } {
-            # Since the current argument may (but not necessarily) be passed,
-            # increment the maximum argument count.
-            arg_count_max+=1
-
-            # If such argument is mandatory (i.e., was neither suffixed by an
-            # eroteme *OR* a default value), increment the minimum argument
-            # count as well.
-            if [[ -z "${match[${arg_match_index_is_optional}]-}${match[${arg_match_index_value}]-}" ]] {
-                arg_count_min+=1
-            }
-
-            # If such argument is variadic (i.e., was suffixed by an ellipse),
-            # record such fact.
-            if [[ -n "${match[${arg_match_index_is_variadic}]-}" ]] {
-                # If a prior argument is also variadic, throw an exception.
-                # Such case implies such function to accept two or more
-                # variadic argument lists of arbitrary count. However, there
-                # exists no general-purpose means of differentiating which such
-                # list the caller intended *ANY* passed argument to belong to,
-                # itself implying this function cannot reliably validate the
-                # types of subsequent arguments. Given such quandries, the only
-                # sane response is to prohibit such prototypes altogether.
-                #
-                # For simplicity, print only the first function name in such
-                # exception message.
-                (( func_is_variadic == 0 )) || :die\
-                    'Function '${ZESHY_DECLARE_FUNC_NAMES__[1]}'() accepts two or more variadic argument lists:'$'\n\n"'${(qq)ZESHY_DECLARE_FUNC_PROTOTYPE__}
-
-                # Else, record such fact.
-                func_is_variadic=1
-            }
-        }
-    }
+    # Define integer locals declared above by parsing each argument in the
+    # argument list embedded in such function's prototype.
+    ::declare_func_stop:parse_args
 
     # Declare and redefine each such function to begin with such preamble.
     # Alias :declare_func{() previously defined such function, internally
@@ -485,6 +438,101 @@ function ::declare_func_stop() {
         ZESHY_DECLARE_FUNC_ATTRS__\
         ZESHY_DECLARE_FUNC_NAMES__\
         ZESHY_DECLARE_FUNC_ARGS__
+}
+
+# :void ::declare_func_stop:parse_args()
+function ::declare_func_stop:parse_args() {
+    # Validate sanity.
+    (( # == 0 )) || :die 'Expected no arguments.'
+
+    # Human-readable names of canonical list global ${match} indices. While
+    # such indices are both unnecessary and slightly inefficient, their use
+    # dramatically improves the readability and stability of argument parsing.
+    # Likewise, declaring such integer locals as globals would slightly
+    # mitigate such inefficiency at a cost of harming such stability (as such
+    # globals could be externally unset at any time). In the end, the current
+    # implementation seems a sensible tradeoff on all fronts.
+    #
+    # The current argument's mandatory type.
+    integer -r arg_match_index_type=1
+
+    # The current argument type's optional eroteme (i.e., "?"), signifying that
+    # such function's definition should *NOT* be prefixed by a call to an
+    # exception handler throwing an exception if such argument violates the
+    # constraints of such type (e.g., a non-numeric string passed where an
+    # integer was expected). If unspecified, such definition is prefixed by
+    # such a call.
+    integer -r arg_match_index_type_is_unvalidated=2
+
+    # The current argument's mandatory name.
+    integer -r arg_match_index_name=3
+
+    # The current argument's optional eroteme (i.e., "?"), signifying such
+    # argument to be optional. If unspecified, such argument is mandatory.
+    integer -r arg_match_index_is_optional=4
+
+    # The current argument's optional default value.
+    integer -r arg_match_index_value=5
+
+    # The current argument's optional ellipse (i.e., "..."), signifying such
+    # argument and hence function to be variadic.
+    integer -r arg_match_index_is_variadic=6
+
+    # If such argument string is *NOT* the empty string, such function accepts
+    # at least one argument. In such case, parse such arguments.
+    [[ -n "${ZESHY_DECLARE_FUNC_ARGS__}" ]] || {
+        # Compile such PCRE. See for_string_text_matching_pcre:() for further
+        # details.
+        pcre_compile -- "${ZESHY_PROTOTYPE_RUNNABLE_ARGS_NEXT_PCRE}"
+        pcre_study
+
+        # Parse each such argument into canonical list global ${match}, whose
+        # indices we localize as human-readable integers above.
+        local ZPCRE_OP='0 0'
+        while {
+            pcre_match -b -n ${ZPCRE_OP[(w)2]} -- "${ZESHY_DECLARE_FUNC_ARGS__}"
+        } {
+            # Since the current argument may (but not necessarily) be passed,
+            # increment the maximum argument count.
+            arg_count_max+=1
+
+            # If such argument is mandatory (i.e., was neither suffixed by an
+            # eroteme *OR* a default value), increment the minimum argument
+            # count as well.
+            if [[ -z "${match[${arg_match_index_is_optional}]-}${match[${arg_match_index_value}]-}" ]] {
+                arg_count_min+=1
+
+                # If such argument was suffixed by both an eroteme *AND*
+                # default value, print a nonfatal warning. While redundant,
+                # such edge case does *NOT* warrant a fatal exception.  For
+                # simplicity, print only the first function name in such
+                # warning message.
+                [[ -z "${match[${arg_match_index_is_optional}]-}" ||
+                   -z "${match[${arg_match_index_value}]-}" ]] ||
+                    :print_warning 'Function '${ZESHY_DECLARE_FUNC_NAMES__[1]}'() argument '${match[arg_match_index_name]}' redundantly suffixed by both "?" and "=":'$'\n\n'${ZESHY_DECLARE_FUNC_PROTOTYPE__}
+            }
+
+            # If such argument is variadic (i.e., was suffixed by an ellipse),
+            # record such fact.
+            if [[ -n "${match[${arg_match_index_is_variadic}]-}" ]] {
+                # If a prior argument is also variadic, throw an exception.
+                # Such case implies such function to accept two or more
+                # variadic argument lists of arbitrary count. However, there
+                # exists no general-purpose means of differentiating which such
+                # list the caller intended *ANY* passed argument to belong to,
+                # itself implying this function cannot reliably validate the
+                # types of subsequent arguments. Given such quandries, the only
+                # sane response is to prohibit such prototypes altogether. For
+                # simplicity, print only the first function name in such
+                # exception message.
+                (( func_is_variadic == 0 )) || :die\
+                    'Function '${ZESHY_DECLARE_FUNC_NAMES__[1]}'() accepts two or more variadic argument lists:'$'\n\n'${ZESHY_DECLARE_FUNC_PROTOTYPE__}
+
+                # Else, record such fact.
+                func_is_variadic=1
+            }
+        }
+    }
 }
 
 #FIXME: In liue of unit tests...
@@ -615,6 +663,14 @@ function declare_function_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+    # [[ "${(t)ZESHY_DECLARE_FUNC_ATTRS__-}" == 'association'* ]] || :die\
+    #     'Map ${ZESHY_DECLARE_FUNC_ATTRS__} undefined or not a map.'
+    # [[ "${(t)ZESHY_DECLARE_FUNC_NAMES__-}" == 'array'* ]] || :die\
+    #     'List ${ZESHY_DECLARE_FUNC_NAMES__} undefined or not a list.'
+
+    # [[ "${(t)ZESHY_DECLARE_FUNC_PROTOTYPE__-}${(t)ZESHY_DECLARE_FUNC_ARGS__-}" == 'scalar'*'scalar'* ]] || :die\
+    #     'Strings ${ZESHY_DECLARE_FUNC_PROTOTYPE__} and/or ${ZESHY_DECLARE_FUNC_ARGS__} undefined or not strings (e.g., as :declare_func_() not previously called).'
+
     #FUXME: O.K.; this is *GREAT* for parsing merely argument lists, but fails
     #to account for argument channels. We only care about the "args = "
     #argument channel, for obvious reasons. So, if such string is prefixed by
