Global variable declarations refactored.
Global variables are now declared by expanding aliases of the form
:${var_type}_global() (e.g., :string_global(), :int_global()).

diff --git a/src/00-start/00-declare/90-global b/src/00-start/00-declare/90-global
--- a/src/00-start/00-declare/90-global
+++ b/src/00-start/00-declare/90-global
@@ -19,77 +19,111 @@ Handle global variable declarers.
 #
 #Is such alias implementable? Possibly. Consider the following:
 #
-#    :alias_simple :declare_global_list{='
+#    :alias_command :declare_global_list{='
 #        : "${(zAP)ZESHY_DECLARE_GLOBAL_LIST_NAME__::='
-#    :alias_simple }:declare_global_list='}"'
+#    :alias_command }:declare_global_list='}"'
 #
 #Let's be honest: it probably won't work. But it's a fairly clever try. Shall
 #we at least try her out?
+#FIXME: If the above fails, preprocessor manipulation would clearly work.
 
-# ....................{ GLOBALS                            }....................
-# Due to a chicken-and-the-egg problem, all such globals are subsequently
-# documented under @{help} in the main codebase.
+# ....................{ GLOBALS ~ private                  }....................
+:global.document <<'/---'
+:string ZESHY__GLOBAL_NAMES_AND_VALUE
 
-#FIXME: Shift to @{*-glob}.
-#FIXME: Actually, shift this to @{*-main/zsh/var/var}.
-
-# Glob matching zsh variable names. Dismantled, this is:
-#
-# * "[a-zA-Z_]", matching the first character of a valid zsh variable name.
-# * "[a-zA-Z0-9_]#", matching all remaining characters of such name.
-typeset -g ZESHY_VAR_NAME_GLOB='[a-zA-Z_][a-zA-Z0-9_]#'
-
-#FIXME: Shift to @{*-glob}.
-#FIXME: Actually, just excise.
-
-# Glob matching zsh variable names preceding the value to initialize such names
-# to in "zeshy"-specific global declarations. Dismantled, this is:
-#
-# * '(#b)((...)#)', capturing all such names to ${match[1]}. 
-# * '(#B)(...=)', matching but *NOT* capturing each such "="-suffixed name.
-# * '(*)', capturing such value to ${match[2]}.
-typeset -g ZESHY_DECLARATION_GLOBAL_NAMES_AND_VALUE_GLOB='(#b)((#B)('${ZESHY_VAR_NAME_GLOB}'=)#)(*)'
-
-#FIXME: Declare a new map ${ZESHY_GLOBAL_NAME_TO_GLOBAL_NAME_FIRST}. While
-#recording synonyms will (of course) be nice, the principal use of such map
-#should be in printing a warning or dying entirely if such global has already
-#been declared... which I believe we currently don't check!
-#FIXME: Waaait! No. Probably just excise this global. See @{10-function}.
-
-# Map from global names to the help strings documenting such globals. See
-# ${ZESHY_FUNCTION_NAME_TO_HELP} for further details.
-typeset -Ag ZESHY_GLOBAL_NAME_TO_HELP
+Prototype for the currently declared function. This private global is intended
+to be referenced _only_ by :func_() and cohorts.
+/---
+typeset -g ZESHY__GLOBAL_NAMES_AND_VALUE
 
 # ....................{ DECLARERS                          }....................
-:func_ ':void :declare_global[
-    args =  (:string_nonempty global_type,
-             :string global_names_and_optional_value),
-    stdin = (:string global_asciidoc)]' :func{
-    # Localize arguments.
-    local\
-        global_type__dg="${1}"\
-        global_names_and_value__dg="${2}"\
-        global_value__dg\
-        global_definer__dg\
-        global_asciidoc__dg
-    integer is_global_value__dg
-    local -a global_names__dg
+# Since nonscalar globals cannot be exported (by POSIX mandate) *AND* since
+# unconditionally exporting scalar globals would introduce unwanted side
+# effects (e.g., implicit inheritance of such globals by children shells,
+# conflicting with discovery of zeshy-specific globals at digest compilation
+# time), declare all such globals to be non-exported.
+
+#FIXME: Ugh. Globally rename :bool_global to :bool_global and likewise below.
+
+:alias_command.declare ':void :bool_global(:string var_names_and_value)'\
+    "::global bool 'integer -g'"  <<'/---'
+Globally declare all passed `=`-delimited boolean variables, initialized to the
+last `=`-prefixed value if any or ${false} otherwise. See :string_global().
+/---
+
+:alias_command.declare ':void :string_global(:string var_names_and_value)'\
+    "::global string 'typeset -g'"  <<'/---'
+Globally declare all passed `=`-delimited string variables, initialized 
+to the last `=`-prefixed *value* (i.e., single- or double-quoted string,
+integer, or float) if any or the empty string otherwise: e.g.,
+
+.:string_global()
+==========================================
+[source]
+------------------------------------------
+>>> :string_global ON_DEBATE=ON_DISSIDENCE=\
+... "The smart way to keep people passive and obedient is to strictly limit the
+...  spectrum of acceptable opinion, but allow very lively debate within that
+...  spectrum - even encourage the more critical and dissident views." <<'//---'
+... That gives people the sense that there's free thinking going on, while all
+... the time the presuppositions of the system are being reinforced by the
+... limits put on the range of the debate.
+... //---
+>>> :string.is_equals "${ON_DEBATE}" "${ON_DISSIDENCE}" :and :string.output\
+...     "Those who are able to see beyond the shadows and lies of their
+...      culture will never be understood, let alone believed, by the masses."
+Those who are able to see beyond the shadows and lies of their
+culture will never be understood, let alone believed, by the masses.
+------------------------------------------
+==========================================
+/---
+
+# ....................{ DECLARERS ~ private                }....................
+#FIXME: The current implementation is rather horrid. Instead:
+#
+#* Rename this function to ::global() and modify the first argument
+#  accepted by such function to a zsh-specific builtin and optional
+#  arguments (e.g., "integer -g" for integer globals.
+#* Define one global declarer for each fundamental type (e.g.,
+#  :string_global() for string globals), internally calling ::global() and
+#  passing such function such zsh-specific type string for such type.
+#* Excise all existing aliases declaring globals of such type (e.g.,
+#  "string_global").
+#* All existing calls to ::global() should be replaced by calls to such
+#  type-specific global functions (e.g., replacing "::global string" by simply
+#  ":string_global").
+
+:func_ ':void ::global[
+    args =  (:string `global_type_zeshy,
+             :string `global_type_zsh,
+             :string `global_names_and_value),
+    stdin = (:string `global_asciidoc)]' :func{
+    #FIXME: Globalize all such locals, including those implicitly declared by
+    #such prototype.
+
+    local ZESHY__GLOBAL_TYPE_ZESHY ZESHY__GLOBAL_TYPE_ZSH ZESHY__GLOBAL_VALUE ZESHY__GLOBAL_ASCIIDOC ZESHY__GLOBAL_NAMES_AND_VALUE
+    local -a ZESHY__GLOBAL_NAMES
+    integer ZESHY__GLOBAL_VALUE_IS
+
+    ZESHY__GLOBAL_TYPE_ZESHY=${1}
+    ZESHY__GLOBAL_TYPE_ZSH=${2}
+    ZESHY__GLOBAL_NAMES_AND_VALUE=${3}
 
     # Documentation passed on standard input.
-    ::help.set_to_stdin global_asciidoc__dg
+    ::help.set_to_stdin ZESHY__GLOBAL_ASCIIDOC
+
+    # If such prototype is syntactically invalid, throw an exception.
+    [[ ${ZESHY__GLOBAL_NAMES_AND_VALUE} =~\
+       ${ZESHY_GLOBAL_PROTOTYPE_NAMES_VALUE_PCRE} ]] || :die\
+        'Global declaration'$(::parcel.get_preposition)' invalid:'$'\n'${ZESHY__GLOBAL_NAMES_AND_VALUE}
 
     # If one or more global names *AND* optional value was declared, note this.
-    :set_list,string,bool_to_global_names,value,is_value\
-        global_names__dg\
-        global_value__dg\
-        is_global_value__dg\
-        "${global_names_and_value__dg}"
 
     # If such value is nonempty and such type is nonscalar, throw an exception.
     # See function documentation for further details.
-    if (( is_global_value__dg )) &&
-       [[ "${global_type__dg}" == ':'('list'|'map')('_'*|) ]] {
-        :die ${global_type__dg}' global(s) "'${global_names__dg[*]}'" nonscalar and hence uninitializable to "'${global_value__dg}'".'
+    if (( is_global_value__g )) &&
+       [[ "${global_type__g}" == ':'('list'|'map')('_'*|) ]] {
+        :die ${global_type__g}' global(s) "'${global_names__g[*]}'" nonscalar and hence uninitializable to "'${global_value__g}'".'
     }
 
     # Name of the alias declaring globals of such type. Since nonscalar globals
@@ -97,13 +131,11 @@ typeset -Ag ZESHY_GLOBAL_NAME_TO_HELP
     # introduces unwanted side effects (e.g., inheritance of such globals by
     # child shells, conflicting with discovery of zeshy-specific globals at
     # digest file recompilation time), declare such global to be non-exported.
-    global_definer__dg="${global_type__dg}_global"
-
-    #FIXME: Start here on the morrow.
+    global_definer__g="${global_type__g}_global"
 
     # For each such global...
-    local global_name__dg
-    for   global_name__dg ("${global_names__dg[@]}") {
+    local global_name__g
+    for   global_name__g ("${global_names__g[@]}") {
         # Function defining such global.
         local global_definer=":define_global_${global_type}"
         :func.die_unless "${global_definer}"
@@ -113,15 +145,15 @@ typeset -Ag ZESHY_GLOBAL_NAME_TO_HELP
 
         # Append such global to the current parcel *AFTER* successfully defining
         # such global.
-        add_parcel_global "${ZESHY_PARCEL_NAME}" "${global_name__dg}"
+        add_parcel_global "${ZESHY_PARCEL_NAME}" "${global_name__g}"
     }
 
     # If such alias does not exist, throw an exception. Since such alias
     # could technically also be a function, match both. See is_runnable()
     # for further details.
-#   print "global type: ${global_type__dg}; global name: ${global_name__dg}; declarator: ${declarator__dg}"
-    whence -- "${declarator__dg}" &>/dev/null || :die\
-        'Global type "'${global_type__dg}'" unrecognized (i.e., '${declarator__dg}'() undefined).'
+#   print "global type: ${global_type__g}; global name: ${global_name__g}; declarator: ${declarator__g}"
+    whence -- "${declarator__g}" &>/dev/null || :die\
+        'Global type "'${global_type__g}'" unrecognized (i.e., '${declarator__g}'() undefined).'
 
     # Declare such globals. Since the declarator is typically an alias rather
     # than function or pathable, zsh requires evaluating rather than running
@@ -136,24 +168,21 @@ typeset -Ag ZESHY_GLOBAL_NAME_TO_HELP
     # of "typeset -gx +" for a line matching such global's name. While such
     # parsing could conceivably be efficient for infrequent purposes, declaring
     # globals is not an infrequent purpose.
-    local global_name__dg
-    for   global_name__dg ("${global_names__dg[@]}") {
+    local global_name__g
+    for   global_name__g ("${global_names__g[@]}") {
         # If such value exists, declare such global initialized to such value.
         # Since such name *MUST* be expanded before evaluating such statement,
         # this eval() *CANNOT* be extracted outside this "for" loop as would
         # commonly be the case.
-        if [[ -n "${global_value__dg}" ]] {
-            eval ${declarator__dg}' '${global_name__dg}'="${global_value__dg}"'
+        if [[ -n "${global_value__g}" ]] {
+            eval ${declarator__g}' '${global_name__g}'="${global_value__g}"'
         # Else, declare such global initialized to a default value.
         } else {
-            eval ${declarator__dg}' '${global_name__dg}
+            eval ${declarator__g}' '${global_name__g}
         }
 
-        # Map such global to such help string.
-        ZESHY_GLOBAL_NAME_TO_HELP[${global_name__dg}]="${help__dg}"
-
         # Add such global to the current parcel.
-        add_parcel_global "${ZESHY_PARCEL_NAME}" "${global_name__dg}"
+        add_parcel_global "${ZESHY_PARCEL_NAME}" "${global_name__g}"
     }
 
     # Document such globals with such documentation *AFTER* successfully
@@ -164,11 +193,133 @@ typeset -Ag ZESHY_GLOBAL_NAME_TO_HELP
         "${global_prototype}"\
         "${global_asciidoc}"
 }:func <<'/---'
-FIXME: Placeholder.
+Declare the passed global contained by the current
+parcel and documented by the passed help string, where such variable is
+specified by either:
+
+* The passed variable type and name arguments, if such arguments are passed.
+* The variable declaration prefixing the passed help string, otherwise.
+
+If a variable name is passed, a `zeshy`-specific variable type must also be
+passed (e.g., `boolean`, `string`). If such name contains a `=` delimiter _and_
+such type is:
+
+* *Scalar* (e.g., `integer`, `string`), the (possibly empty) substring of such
+  name following such delimiter defines the *initial value* to initialize such
+  global to: e.g.,
++
+.declare_global() Scalar Initialization
+==========================================
+[source]
+------------------------------------------
+>>> declare_global string on_industry=\
+...     "If a man walk in the woods for love of them half of each day, he is in
+...      danger of being regarded as a loafer; but if he spends his whole day as
+...      a speculator, shearing off those woods and making Earth bald before her
+...      time, he is esteemed an industrious and enterprising citizen. As if a
+...      town had no interest in its forests but to cut them down!"\
+...     "Most men would feel insulted if it were proposed to employ them in
+...      throwing stones over a wall, and then in throwing them back, merely
+...      that they might earn their wages. But many are no more worthily
+...      employed now."
+>>> get_string_line "${on_industry}" -1
+town had no interest in its forests but to cut them down!
+------------------------------------------
+==========================================
+* *Nonscalar* (e.g., `list`, `map`), an exception is thrown. As with customary
+  `zsh` variable declarations, nonscalar globals may only be initialized to an
+  initial value _after_ rather than when declaring such globals: e.g.,
++
+.declare_global() Nonscalar Initialization
+==========================================
+[source]
+------------------------------------------
+>>> declare_global "
+...     list on_anarchism
+...
+...     Anarchism is not a romantic fable but the hardheaded realization, based
+...     on five thousand years of experience, that we cannot entrust the
+...     management of our lives to kings, priests, politicians, generals, and
+...     county commissioners."
+>>> on_anarchism=(
+...     "Anarchism is founded on the observation that since few men are wise"
+...     "enough to rule themselves, even fewer are wise enough to rule others."
+... )
+>>> print_string "${on_anarchism[1]}"
+Anarchism is founded on the observation that since few men are wise
+------------------------------------------
+==========================================
+
+== Variable Type ==
+
+A global's type may be any alphanumeric string for which an alias of the same
+name suffixed by `_global_export` exists. Hence, `file_descriptor` is a valid
+global type but `order_of_the_blackened_denarius` is not, since
+file_descriptor_global_export() is an existing alias but
+order_of_the_blackened_denarius_global_export() is (hopefully) not.
+
+`zeshy` provides numerous such aliases and hence variable types, including:
+boolean(), character(), file_descriptor(), float(), integer(), list(),
+list_set(), map(), and string().
+
+== Variable Documentation ==
+
+Global help strings consist of:
+
+. A *variable declaration* in `zeshy`-specific C-like syntax consisting of one
+  variable type and name (e.g., `list DOG_EAT_DOG_WORLD`), if such type and name
+  were _not_ passed as arguments already.
+. A *variable description* in http://asciidoc.org[AsciiDoc] syntax, augmented
+  with `zeshy`-specific markup for cross-referencing other `zeshy` documentation.
+  Since single- and double-quoted `zsh` string syntax conflicts with such syntax,
+  consider passing such description to declare_global_with_stdin() as a
+  here-document on standard input instead.
+
+For completeness, we specify such syntax as a
+http://en.wikipedia.org/wiki/Parsing_expression_grammar[Parser Expression Grammar (PEG)]:
+See the <<declare_function.peg,function documentation PEG>> from which this PEG
+derives for all productions not listed here (e.g., AsciiDoc, Type, Whitespace):
+
+.Variable Documentation Grammar
+[cols=">strong,^,<"]
+|===============================================================================
+| GlobalDocumentation   | <- | GlobalDeclaration Whitespace+ AsciiDoc
+| GlobalDeclaration     | <- | Whitespace* Type Whitespace+ GlobalName
+| GlobalName            | <- | AlphanumericString
+|===============================================================================
 /---
 
 # ....................{ OBSOLETE                           }....................
-#FIXME: Excise *ALL* such functionality.
+#FIXME: Excise *ALL* such functionality, excluding ${ZESHY_VAR_NAME_GLOB},
+#which should be shifted to @{*-main/zsh/var/var}.
+
+#FIXME: Shift to @{*-glob}.
+#FIXME: Actually, shift this to @{*-main/zsh/var/var}.
+
+# Glob matching zsh variable names. Dismantled, this is:
+#
+# * "[a-zA-Z_]", matching the first character of a valid zsh variable name.
+# * "[a-zA-Z0-9_]#", matching all remaining characters of such name.
+typeset -g ZESHY_VAR_NAME_GLOB='[a-zA-Z_][a-zA-Z0-9_]#'
+
+#FIXME: Declare a new map ${ZESHY_GLOBAL_NAME_TO_GLOBAL_NAME_FIRST}. While
+#recording synonyms will (of course) be nice, the principal use of such map
+#should be in printing a warning or dying entirely if such global has already
+#been declared... which I believe we currently don't check!
+#FIXME: Waaait! No. Probably just excise this global. See @{10-function}.
+
+# Map from global names to the help strings documenting such globals. See
+# ${ZESHY_FUNCTION_NAME_TO_HELP} for further details.
+typeset -Ag ZESHY_GLOBAL_NAME_TO_HELP
+
+# Glob matching zsh variable names preceding the value to initialize such names
+# to in "zeshy"-specific global declarations. Dismantled, this is:
+#
+# * '(#b)((...)#)', capturing all such names to ${match[1]}. 
+# * '(#B)(...=)', matching but *NOT* capturing each such "="-suffixed name.
+# * '(*)', capturing such value to ${match[2]}.
+typeset -g ZESHY_DECLARATION_GLOBAL_NAMES_AND_VALUE_GLOB='(#b)((#B)('${ZESHY_VAR_NAME_GLOB}'=)#)(*)'
+
 #FIXME: Optional arguments are terrible. Require passed types *AND* names. (If
 #the caller only wants to document an existing global, they can very well call
 #:global.document() -- which, of course, is how we should have designed such
@@ -454,6 +605,25 @@ function declare_global_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+    # If one or more global names *AND* optional value was declared, note this.
+    # :set_list,string,bool_to_global_names,value,is_value\
+    #     global_names__g\
+    #     global_value__g\
+    #     is_global_value__g\
+    #     "${global_names_and_value__g}"
+
+# .declare_type,names_and_value
+
+# ....................{ GLOBALS                            }....................
+# Due to a chicken-and-the-egg problem, all such globals are subsequently
+# documented under @{help} in the main codebase.
+
+        # Map such global to such help string.
+        # ZESHY_GLOBAL_NAME_TO_HELP[${global_name__dg}]="${help__dg}"
+
+        # global_type__dg="${1}"\
+        # global_names_and_value__dg="${2}"\
+
     # Validate sanity.
     # (( # == 3 )) || :die\
     #     'Expected one one global type and one "="-delimited string of one or more global names and optional value.'
