Added ANSI and Zsh color code support.
Happily, run_paged() now implicitly excises such codes prior to
calculating line lengths.

diff --git a/src/always/shell/run/run b/src/always/shell/run/run
--- a/src/always/shell/run/run
+++ b/src/always/shell/run/run
@@ -92,26 +92,16 @@ run() {
         return_true
     }
 
-    #FIXME: This works, but is rather clumsy. For one, it fails to account for
-    #user-defined functions calling run(). For another, it's slow and abjectly
-    #error-prone. How about reducing this to:
-    #
-    #   string run_function_glob='run(|_*)'
-    #
-    #This simply and effectively matches user-defined functions, assuming they
-    #prefix such functions with "run_". This does not, however, match all of our
-    #functions. We'll need to systematically rename them all, I'm afraid (e.g.,
-    #run_quickly() to run_run_quickly()). Arguably, this is a good move *ANYWAY*.
-    #Consistency assists readability, and makes it explicit exactly what's
-    #happening when you call such functions.
-
-    # If running a Zeshy function recursively calling this function, do *NOT*
-    # "eval" the passed command as the second call to this function will do so
-    # already. Since each "eval" strips one level of quotes from such command,
-    # running such command as is avoids stripping of quote protection.
-    string run_function_glob='(run(|_as|as_superuser|_every|_paged|_with_options|_with_priorities)|run_quickly|run_quietly(|_as)|run_slowly|run_with_unified_output)'
+    #FIXME: Not quite right. We should probably call "$(get_command_line_name)"
+    #to get the name of the command in command position. *shrug, for the moment*
+    # If the argument in command position is either this function name or a
+    # "run_"-prefixed function name, assume such argument to be a call to a
+    # Zeshy-specific function recursively calling this function. In such case,
+    # do *NOT* "eval" such command as the recursive call to this function will
+    # do so already. Since each "eval" strips one level of quotes from such
+    # command, running such command as is avoids stripping quote protection.
     list command_line; command_line=( "${(z)@}" )
-    is "${command_line[1]}" == ${~run_function_glob} si and {
+    is "${command_line[1]}" == (run|run_?*) si and {
 #       sputter "run (direct): ${@}... (last arg: ${@[-1]})"
         "${@}"
         return_true
@@ -124,10 +114,8 @@ run() {
     # we implement a crude shell parser selectively quote-protecting only non-
     # evaluatable strings *NOT* containing reserved characters. YES, THIS IS
     # AAAAAAAAAABSOLUTELY CRAZY. Fix this, kind Zsh developers. (Fix this now.)
-#   eval ${(q)@}
-#   eval ${@}
-#   ${@}
-#   return $?
+
+    #FIXME: Shouldn't we be reusing the split apart "${command_line}" from above?
     list args; args=( "${@}" )
 #   list args; args=( "${(@)@[1,-1]}" )
 #   list arg_words
@@ -356,11 +344,6 @@ run_paged() {
             # is_piped_input() now returns false.
             close_standard_input
         fi
-
-        #FIXME: Excise this frivolous check after all's well above.
-#       exec {/dev/stdin}>&-
-#       exec 0<&-
-        is_piped_input and die 'uh-oh; still piped input!'
     #FIXME: Hmm; the documentation no longer reflects the reality. Fixmeup.
     # Otherwise, run the passed command with redirection. Dismantled, this is:
     #
@@ -373,8 +356,6 @@ run_paged() {
     #   running such command.
     else
         die_unless_args 'expected one command'
-#       list command_line; command_line=( "${@}" )
-#       sputter "run_paged: ${command_line[@]}..."
 #       sputter "run_paged: ${@}..."
         output="$(run "${@}" 1>&1 1>&2 2>&1)"
     fi
@@ -391,37 +372,29 @@ run_paged() {
     # total line length. This reduces an otherwise O(N) algorithm to effectively
     # O(1), assuming non-ludicrous terminal height and width.
     integer\
-        line_height="${#lines}" line_width\
+        output_height="${#lines}" output_width\
         terminal_height terminal_width
     terminal_height=$(get_terminal_height)
     terminal_width=$(get_terminal_width)
-#   sputter "lines=${lines[@]}\nline_height=${line_height}\nterminal_height=${terminal_height}"
-
-    #FIXME: Ugh. Broken. We need to ignore VT100 commands. I've been
-    #searching for a Zsh-specific solution, but have yet to find anything. Ah!
-    #It's not Zsh, but it'll do: sed!
-    #http://www.commandlinefu.com/commands/view/3584/remove-color-codes-special-characters-with-sed
-    #Looks like this should get us close. Let's research it a bit:
-    #sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
-    #sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g"
-    #I suspect the second is more accurate. Again, research.
+#   sputter "lines=${lines[@]}\noutput_height=${output_height}\nterminal_height=${terminal_height}"
 
     # If the output's line height does not exceed the terminal height, determine
     # whether or not its maximum line width exceeds the terminal width.
     # Accumulate wrapped line height and maximum line width until either exceeds
     # terminal height or width, at which point we know we need to page.
-    (( line_height > terminal_height )) or for line ("${lines[@]}") {
-        line_width=${#line}
-#       sputter "line (width: ${line_width}) ${line}"
-        (( line_width > terminal_width )) and break
+    (( output_height > terminal_height )) or for line ("${lines[@]}") {
+        # Remove ANSI color codes prior to testing line length.
+        output_width=${#$(remove_ansi_color_codes "${line}")}
+#       sputter "line (width: ${output_width}) ${line}"
+        (( output_width > terminal_width )) and break
     }
-#   sputter "line_height: ${line_height}\nterminal_height: ${terminal_height}"
-#   sputter "line_width: ${line_width}\nterminal_width: ${terminal_width}"
+#   sputter "output_height: ${output_height}\nterminal_height: ${terminal_height}"
+#   sputter "output_width: ${output_width}\nterminal_width: ${terminal_width}"
 
     # If the terminal suffices to display output without paging, do not page.
-#   utter "line length: ${line_height}\nterminal height: ${terminal_height}"
-    (( line_height > terminal_height )) or
-    (( line_width  > terminal_width  )) or return_true
+#   utter "line length: ${output_height}\nterminal height: ${terminal_height}"
+    (( output_height > terminal_height )) or
+    (( output_width  > terminal_width  )) or return_true
 
     # Pager command to be run.
     list pager; pager=( "${PAGER}" )
@@ -607,6 +580,50 @@ run_as() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+#   eval ${(q)@}
+#   eval ${@}
+#   ${@}
+#   return $?
+
+    #FIXME: This works, but is rather clumsy. For one, it fails to account for
+    #user-defined functions calling run(). For another, it's slow and abjectly
+    #error-prone. How about reducing this to:
+    #
+    #   string run_function_glob='run(|_*)'
+    #
+    #This simply and effectively matches user-defined functions, assuming they
+    #prefix such functions with "run_". This does not, however, match all of our
+    #functions. We'll need to systematically rename them all, I'm afraid (e.g.,
+    #run_quickly() to run_run_quickly()). Arguably, this is a good move *ANYWAY*.
+    #Consistency assists readability, and makes it explicit exactly what's
+    #happening when you call such functions.
+
+    # If running a Zeshy function recursively calling this function, do *NOT*
+    # "eval" the passed command as the second call to this function will do so
+    # already. Since each "eval" strips one level of quotes from such command,
+    # running such command as is avoids stripping of quote protection.
+#   string run_function_glob='(run(|_as|as_superuser|_every|_paged|_with_options|_with_priorities)|run_quickly|run_quietly(|_as)|run_slowly|run_with_unified_output)'
+#   list command_line; command_line=( "${(z)@}" )
+#   is "${command_line[1]}" == ${~run_function_glob} si and {
+
+#       list command_line; command_line=( "${@}" )
+#       sputter "run_paged: ${command_line[@]}..."
+    #FIXME: Ugh. Broken. We need to ignore VT100 commands. I've been
+    #searching for a Zsh-specific solution, but have yet to find anything. Ah!
+    #It's not Zsh, but it'll do: sed!
+    #http://www.commandlinefu.com/commands/view/3584/remove-color-codes-special-characters-with-sed
+    #Looks like this should get us close. Let's research it a bit:
+    #sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
+    #sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g"
+    #I suspect the second is more accurate. Again, research.
+#       output_width=${#"$(remove_ansi_color_codes "${line}")"}
+#       line="$(remove_ansi_color_codes "${line}")"
+#       output_width=${#line}
+
+        #FIXME: Excise this frivolous check after all's well above.
+#       exec {/dev/stdin}>&-
+#       exec 0<&-
+#       is_piped_input and die 'uh-oh; still piped input!'
     # Terminal width plus one to avoid treating maximally long lines as wrapped.
 # terminal_width_plus_one
 # (( terminal_width_plus_one = terminal_width + 1 ))
