Global variable declaration refactored.
Such declaration should now be nominally complete, if rather untested.

diff --git a/src/00-start/00-declare/80-global/global b/src/00-start/00-declare/80-global/global
--- a/src/00-start/00-declare/80-global/global
+++ b/src/00-start/00-declare/80-global/global
@@ -3,8 +3,9 @@
 # Copyright 2007-2013 by Cecil Curry.
 # See "COPYING" for additional details.
 
-declare_parcel_as_script_with_stdin <<'/---'
-Handle global variable declarers.
+:parcel <<'/---'
+Handle *global variable declarers* (i.e., functions declaring global
+variables).
 /---
 
 #FIXME: There may, after all, be a means of defining non-scalar globals in a
@@ -25,157 +26,104 @@ Handle global variable declarers.
 #
 #Let's be honest: it probably won't work. But it's a fairly clever try. Shall
 #we at least try her out?
-#FIXME: If the above fails, preprocessor manipulation would clearly work.
+#FIXME: If the above fails, preprocessor manipulation would clearly work -- and
+#clearly work *MUCH* cleaner.
 
 # ....................{ GLOBALS ~ private                  }....................
 :global.document <<'/---'
-:string ZESHY__GLOBAL_NAMES_AND_VALUE
+:string ZESHY__GLOBAL_TYPE_ZESHY
 
-Prototype for the currently declared function. This private global is intended
-to be referenced _only_ by :func_() and cohorts.
+*`zeshy` type* (i.e., `zeshy`-specific `:`-prefixed variable type) for the
+currently declared global. This private global is intended to be referenced
+_only_ by ::global() and cohorts.
 /---
-typeset -g ZESHY__GLOBAL_NAMES_AND_VALUE
+typeset -g ZESHY__GLOBAL_TYPE_ZESHY
+
+:global.document <<'/---'
+:string ZESHY__GLOBAL_TYPE_ZSH
+
+*`zsh` type* (i.e., `zsh`-specific builtin name and zero or more arguments
+declaring variables of such type) for the currently declared global. This
+private global is intended to be referenced _only_ by ::global() and cohorts.
+/---
+typeset -g ZESHY__GLOBAL_TYPE_ZSH
+
+:global.document <<'/---'
+:string ZESHY__GLOBAL_PROTOTYPE
+
+*Prototype* (i.e., `=`-delimited list of one or more variable names and
+optional value) for the currently declared global. This private global is
+intended to be referenced _only_ by ::global() and cohorts.
+/---
+typeset -g ZESHY__GLOBAL_PROTOTYPE
+
+:global.document <<'/---'
+:list ZESHY__GLOBAL_NAMES
+
+List of all variable names for the currently declared global, parsed from such
+global's prototype. This private global is intended to be referenced _only_ by
+::global() and cohorts.
+/---
+typeset -ga ZESHY__GLOBAL_NAMES
+
+:global.document <<'/---'
+:string ZESHY__GLOBAL_NAME
+
+Currently parsed name for the currently declared global. This private global is
+intended to be referenced _only_ by ::global() and cohorts.
+/---
+typeset -g ZESHY__GLOBAL_NAME
+
+:global.document <<'/---'
+:string ZESHY__GLOBAL_VALUE
+
+Initial value the currently declared global, parsed from such global's
+prototype. This private global is intended to be referenced _only_ by
+::global() and cohorts.
+/---
+typeset -g ZESHY__GLOBAL_VALUE
 
 # ....................{ DECLARERS                          }....................
-# Since nonscalar globals cannot be exported (by POSIX mandate) *AND* since
-# unconditionally exporting scalar globals would introduce unwanted side
-# effects (e.g., implicit inheritance of such globals by children shells,
-# conflicting with discovery of zeshy-specific globals at digest compilation
-# time), declare all such globals to be non-exported.
-
-:alias_command.declare ':void :bool_global(:string var_names_and_value)'\
-    "::global bool 'integer -g'" <<'/---'
-Globally declare all passed `=`-delimited boolean variables, initialized to the
-last `=`-prefixed value if any or ${false} otherwise. See :string_global().
-/---
-
-:alias_command.declare ':void :list_global(:string var_names_and_value)'\
-    "::global list 'typeset -ga'" <<'/---'
-Globally declare all passed `=`-delimited list variables, initialized to the
-empty list. See :string_global().
-
-== Caveats ==
-
-Unlike scalar globals, list globals are nonscalar and hence _cannot_ be
-initialized at declaration time (e.g., by suffixing the passed `=`-delimited
-variable names by a `=`-prefixed value). See :list().
-/---
-
-:alias_command.declare ':void :map_global(:string var_names_and_value)'\
-    "::global map 'typeset -gA'" <<'/---'
-Globally declare all passed `=`-delimited map variables, initialized to the
-empty map. See :string_global().
-
-== Caveats ==
-
-Unlike scalar globals, map globals are nonscalar and hence _cannot_ be
-initialized at declaration time (e.g., by suffixing the passed `=`-delimited
-variable names by a `=`-prefixed value). See :map().
-/---
-
-:alias_command.declare ':void :string_global(:string var_names_and_value)'\
-    "::global string 'typeset -g'" <<'/---'
-Globally declare all passed `=`-delimited string variables, initialized 
-to the last `=`-prefixed *value* (i.e., single- or double-quoted string,
-integer, or float) if any or the empty string otherwise: e.g.,
-
-.:string_global()
-==========================================
-[source]
-------------------------------------------
->>> :string_global ON_DEBATE=ON_DISSIDENCE=\
-... "The smart way to keep people passive and obedient is to strictly limit the
-...  spectrum of acceptable opinion, but allow very lively debate within that
-...  spectrum - even encourage the more critical and dissident views." <<'//---'
-... That gives people the sense that there's free thinking going on, while all
-... the time the presuppositions of the system are being reinforced by the
-... limits put on the range of the debate.
-... //---
->>> :string.is_equals "${ON_DEBATE}" "${ON_DISSIDENCE}" :and :string.output\
-...     "Those who are able to see beyond the shadows and lies of their
-...      culture will never be understood, let alone believed, by the masses."
-Those who are able to see beyond the shadows and lies of their
-culture will never be understood, let alone believed, by the masses.
-------------------------------------------
-==========================================
-/---
-
-# ....................{ DECLARERS ~ private                }....................
-#FIXME: The current implementation is rather horrid. Instead:
-#
-#* Rename this function to ::global() and modify the first argument
-#  accepted by such function to a zsh-specific builtin and optional
-#  arguments (e.g., "integer -g" for integer globals.
-#* Define one global declarer for each fundamental type (e.g.,
-#  :string_global() for string globals), internally calling ::global() and
-#  passing such function such zsh-specific type string for such type.
-#* Excise all existing aliases declaring globals of such type (e.g.,
-#  "string_global").
-#* All existing calls to ::global() should be replaced by calls to such
-#  type-specific global functions (e.g., replacing "::global string" by simply
-#  ":string_global").
-
 :func_ ':void ::global[
     args =  (:string `global_type_zeshy,
              :string `global_type_zsh,
              :string `global_names_and_value),
     stdin = (:string `global_asciidoc)]' :func{
-    #FIXME: Globalize all such locals, including those implicitly declared by
-    #such prototype.
-
-    local ZESHY__GLOBAL_TYPE_ZESHY ZESHY__GLOBAL_TYPE_ZSH ZESHY__GLOBAL_VALUE ZESHY__GLOBAL_ASCIIDOC ZESHY__GLOBAL_NAMES_AND_VALUE
-    local -a ZESHY__GLOBAL_NAMES
-    integer ZESHY__GLOBAL_VALUE_IS
-
+    # Localize arguments.
     ZESHY__GLOBAL_TYPE_ZESHY=${1}
     ZESHY__GLOBAL_TYPE_ZSH=${2}
-    ZESHY__GLOBAL_NAMES_AND_VALUE=${3}
-
-    # Documentation passed on standard input.
-    ::help.set_to_stdin ZESHY__GLOBAL_ASCIIDOC
+    ZESHY__GLOBAL_PROTOTYPE=${3}
 
     # If such prototype is syntactically invalid, throw an exception.
-    [[ ${ZESHY__GLOBAL_NAMES_AND_VALUE} =~\
-       ${ZESHY_GLOBAL_PROTOTYPE_NAMES_VALUE_PCRE} ]] || :die\
-        'Global declaration'$(::parcel.get_preposition)' invalid:'$'\n'${ZESHY__GLOBAL_NAMES_AND_VALUE}
+    [[ ${ZESHY__GLOBAL_PROTOTYPE} =~\
+       ${ZESHY_GLOBAL_PROTOTYPE_PCRE} ]] || :die\
+        'Global declaration'$(::parcel.get_preposition)' invalid:'$'\n\n'${ZESHY__GLOBAL_PROTOTYPE}
 
-    # If one or more global names *AND* optional value was declared, note this.
+    # If such prototype only declares one name, set such list to such name.
+    if [[ -n ${match[1]-} ]] {
+        ZESHY__GLOBAL_NAMES=( "${match[1]}" )
+    # Else, such prototype declares multiple equal signs-delimited names.
+    # Unlike runnable prototype names, such names are prohibited from
+    # containing equals signs and hence may be efficiently split on such.
+    } else {
+        # If such match failed to capture such names, throw an exception.
+        (( ${#match} >= 2 )) || :die\
+            'Global names unparsable from prototype:'$'\n\n'${ZESHY__GLOBAL_PROTOTYPE}
 
-    # If such value is nonempty and such type is nonscalar, throw an exception.
-    # See function documentation for further details.
-    if (( is_global_value__g )) &&
-       [[ "${global_type__g}" == ':'('list'|'map')('_'*|) ]] {
-        :die ${global_type__g}' global(s) "'${global_names__g[*]}'" nonscalar and hence uninitializable to "'${global_value__g}'".'
+        # Set such list to such names split on equals signs. See
+        # :list.set_to_string_split_on_string().
+        ZESHY__GLOBAL_NAMES=( "${(s:=:)match[2]}" )
     }
 
-    # Name of the alias declaring globals of such type. Since nonscalar globals
-    # cannot be exported *AND* since unconditionally exporting scalar globals
-    # introduces unwanted side effects (e.g., inheritance of such globals by
-    # child shells, conflicting with discovery of zeshy-specific globals at
-    # digest file recompilation time), declare such global to be non-exported.
-    global_definer__g="${global_type__g}_global"
+    # If such prototype declares an initial value, set such value.
+    if (( ${#match} == 3 )) {
+        ZESHY__GLOBAL_VALUE=${match[3]}
 
-    # For each such global...
-    local global_name__g
-    for   global_name__g ("${global_names__g[@]}") {
-        # Function defining such global.
-        local global_definer=":define_global_${global_type}"
-        :func.die_unless "${global_definer}"
-
-        # Define such global.
-        "${global_definer}" "${global_name}" "${global_code}"
-
-        # Append such global to the current parcel *AFTER* successfully defining
-        # such global.
-        add_parcel_global "${ZESHY_PARCEL_NAME}" "${global_name__g}"
+        # If such zeshy-specific type is nonscalar, throw an exception.
+        # Nonscalar variables *CANNOT* be initialized at declaration time.
+        [[ ${ZESHY__GLOBAL_TYPE_ZESHY} != ':'('list'|'map') ]] || :die\
+           ${ZESHY__GLOBAL_TYPE_ZESHY}' global ${'${ZESHY__GLOBAL_NAMES[1]}'}'$(::parcel.get_preposition)' nonscalar and hence uninitializable at declaration time:'$'\n\n'${ZESHY__GLOBAL_PROTOTYPE}
     }
-
-    # If such alias does not exist, throw an exception. Since such alias
-    # could technically also be a function, match both. See is_runnable()
-    # for further details.
-#   print "global type: ${global_type__g}; global name: ${global_name__g}; declarator: ${declarator__g}"
-    whence -- "${declarator__g}" &>/dev/null || :die\
-        'Global type "'${global_type__g}'" unrecognized (i.e., '${declarator__g}'() undefined).'
 
     # Declare such globals. Since the declarator is typically an alias rather
     # than function or pathable, zsh requires evaluating rather than running
@@ -189,31 +137,43 @@ culture will never be understood, let alone believed, by the masses.
     # the only means of testing whether a global exists is to parse the output
     # of "typeset -gx +" for a line matching such global's name. While such
     # parsing could conceivably be efficient for infrequent purposes, declaring
-    # globals is not an infrequent purpose.
-    local global_name__g
-    for   global_name__g ("${global_names__g[@]}") {
+    # globals is hardly infrequent.
+    for ZESHY__GLOBAL_NAME ("${ZESHY__GLOBAL_NAMES[@]}") {
+        #FIXME: Actually, I fail to understand why we can't simply shift such
+        #eval statements out. Given the commentary below, however, we should
+        #probably approach such an attempt with some trepidation.
+
         # If such value exists, declare such global initialized to such value.
-        # Since such name *MUST* be expanded before evaluating such statement,
-        # this eval() *CANNOT* be extracted outside this "for" loop as would
-        # commonly be the case.
-        if [[ -n "${global_value__g}" ]] {
-            eval ${declarator__g}' '${global_name__g}'="${global_value__g}"'
+        # Since such name must be expanded before evaluating such statement,
+        # such eval statements *CANNOT* be extracted outside this "for" loop as
+        # would commonly be the case.
+        #
+        #
+        # Note that, regardless of variable type, there exists no qualitative
+        # difference between explicitly initializing a global to the empty
+        # string and performing no such initialization; in the latter case,
+        # such global will be implicitly initialized to the empty string.
+        # Hence, we need not distinguish between such cases here.
+        if [[ -n ${ZESHY__GLOBAL_VALUE} ]] {
+            eval ${ZESHY__GLOBAL_TYPE_ZSH}' '${ZESHY__GLOBAL_NAME}'=${ZESHY__GLOBAL_VALUE}'
         # Else, declare such global initialized to a default value.
         } else {
-            eval ${declarator__g}' '${global_name__g}
+            eval ${ZESHY__GLOBAL_TYPE_ZSH}' '${ZESHY__GLOBAL_NAME}
         }
 
+        #FIXME: Fairly lame. See @{*-alias} for commentary.
+
         # Add such global to the current parcel.
-        add_parcel_global "${ZESHY_PARCEL_NAME}" "${global_name__g}"
+        add_parcel_global "${ZESHY_PARCEL_NAME}" "${ZESHY__GLOBAL_NAME}"
     }
 
-    # Document such globals with such documentation *AFTER* successfully
-    # defining such globals above.
-    ::global.document_typed_with_prototype,asciidoc\
-        "${global_names[@]}"\
-        "${global_type}"\
-        "${global_prototype}"\
-        "${global_asciidoc}"
+    #FIXME: Can this function benefit from similar optimization? The answer is
+    #almost certainly *YES*.
+
+    # Document such globals *AFTER* successfully defining such globals.
+    ::global.document_prototype_with_stdin_if_nonempty_or_noop\
+        "${ZESHY__GLOBAL_NAMES[@]}"\
+        "${ZESHY__GLOBAL_PROTOTYPE}"
 
 #FIXME: Documentation largelly outdated. *sigh*
 }:func <<'/---'
@@ -284,7 +244,7 @@ order_of_the_blackened_denarius_global_export() is (hopefully) not.
 
 `zeshy` provides numerous such aliases and hence variable types, including:
 boolean(), character(), file_descriptor(), float(), integer(), list(),
-list_set(), map(), and string().
+listset(), map(), and string().
 
 == Variable Documentation ==
 
@@ -422,7 +382,7 @@ order_of_the_blackened_denarius_global_export() is (hopefully) not.
 
 `zeshy` provides numerous such aliases and hence variable types, including:
 boolean(), character(), file_descriptor(), float(), integer(), list(),
-list_set(), map(), and string().
+listset(), map(), and string().
 
 == Variable Documentation ==
 
@@ -629,6 +589,85 @@ function declare_global_with_stdin() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+    #FUXME: Redundant, we should think.
+    # # For each such global...
+    # local global_name__g
+    # for   global_name__g ("${global_names__g[@]}") {
+    #     # Function defining such global.
+    #     local global_definer=":define_global_${global_type}"
+    #     :func.die_unless "${global_definer}"
+
+    #     # Define such global.
+    #     "${global_definer}" "${global_name}" "${global_code}"
+
+    #     # Append such global to the current parcel *AFTER* successfully defining
+    #     # such global.
+    #     add_parcel_global "${ZESHY_PARCEL_NAME}" "${global_name__g}"
+    # }
+
+#to "'${ZESHY__GLOBAL_VALUE}'"
+    # If such value is nonempty and such type is nonscalar, throw an exception.
+    # See function documentation for further details.
+    # if (( is_global_value__g )) &&
+    #    [[ "${global_type__g}" == ':'('list'|'map')('_'*|) ]] {
+    #     :die ${global_type__g}' global(s) "'${global_names__g[*]}'" nonscalar and hence uninitializable to "'${global_value__g}'".'
+    # }
+
+    # Name of the alias declaring globals of such type. Since nonscalar globals
+    # cannot be exported *AND* since unconditionally exporting scalar globals
+    # introduces unwanted side effects (e.g., inheritance of such globals by
+    # child shells, conflicting with discovery of zeshy-specific globals at
+    # digest file recompilation time), declare such global to be non-exported.
+    # global_definer__g="${global_type__g}_global"
+
+    # If such alias does not exist, throw an exception. Since such alias
+    # could technically also be a function, match both. See is_runnable()
+    # for further details.
+#   print "global type: ${global_type__g}; global name: ${global_name__g}; declarator: ${declarator__g}"
+    # whence -- "${declarator__g}" &>/dev/null || :die\
+    #     'Global type "'${global_type__g}'" unrecognized (i.e., '${declarator__g}'() undefined).'
+
+    # Document such globals with such documentation *AFTER* successfully
+    # defining such globals above.
+    # ::global.document_typed_with_prototype,asciidoc\
+    #     "${global_names[@]}"\
+    #     "${global_type}"\
+    #     "${global_prototype}"\
+    #     "${global_asciidoc}"
+
+# :global.document <<'/---'
+# :string ZESHY__GLOBAL_ASCIIDOC
+# 
+# *AsciiDoc* (i.e., documentation in human-readable http://asciidoc.org[AsciiDoc]
+# format) for the currently declared global. This private global is intended to
+# be referenced _only_ by ::global() and cohorts.
+# /---
+# typeset -g ZESHY__GLOBAL_ASCIIDOC
+
+# ::help.set_to_stdin ZESHY__GLOBAL_ASCIIDOC
+    #FUXME: Globalize all such locals, including those implicitly declared by
+    #such prototype.
+
+    # local ZESHY__GLOBAL_VALUE
+    # local -a ZESHY__GLOBAL_NAMES
+    # integer ZESHY__GLOBAL_VALUE_IS
+
+    # If one or more global names *AND* optional value was declared, note this.
+
+#FUXME: The current implementation is rather horrid. Instead:
+#
+#* Rename this function to ::global() and modify the first argument
+#  accepted by such function to a zsh-specific builtin and optional
+#  arguments (e.g., "integer -g" for integer globals.
+#* Define one global declarer for each fundamental type (e.g.,
+#  :string_global() for string globals), internally calling ::global() and
+#  passing such function such zsh-specific type string for such type.
+#* Excise all existing aliases declaring globals of such type (e.g.,
+#  "string_global").
+#* All existing calls to ::global() should be replaced by calls to such
+#  type-specific global functions (e.g., replacing "::global string" by simply
+#  ":string_global").
+
     # If one or more global names *AND* optional value was declared, note this.
     # :set_list,string,bool_to_global_names,value,is_value\
     #     global_names__g\
@@ -1082,7 +1121,7 @@ function declare_global_with_stdin() {
 #
 #Zeshy provides numerous such aliases and hence variable types, including:
 #`boolean`, `character`, `file_descriptor`, `float`, `integer`, `list`,
-#`list_set`, `map`, and `string`.
+#`listset`, `map`, and `string`.
 #/---
 #function declare_global() {
 #    # Validate passed arguments.
