Moved Linux-specific handling into Zeshy Linux.
Also, improved script name handling, error reporting, and module
importing in Zeshy Core.

diff --git a/src/zeshy/os/gnu-linux/main b/src/zeshy/os/gnu-linux/main
--- a/src/zeshy/os/gnu-linux/main
+++ b/src/zeshy/os/gnu-linux/main
@@ -8,14 +8,10 @@
 # ....................{ IMPORTS                            }....................
 import zeshy/os
 
-# void _import_all_os_gnu-linux(void)
+# void _import_os_gnu-linux(void)
 #
-# Import all Zeshy dependencies relevant for the current Linux system. This
-# means:
-#
-# * All scripts under "zeshy/distro" corresponding to the current distribution
-#   (e.g., "zeshy/distro/exherbo" on Exherbo systems).
-_import_all_os_gnu-linux() {
+# Import Zeshy components specific to the current Linux distribution.
+_import_os_gnu-linux() {
     local distro_script_path="${ZESHY_HOME}/zeshy/os/gnu-linux/distro/$(get_distro_name)"
     [[ -f "${distro_script_path}" ]] && import "${distro_script_path}"
 }
@@ -38,6 +34,63 @@ get_distro_name() {
     fi
 }
 
+# ....................{ PROCESSES ~ current                }....................
+# char *get_current_process_basename(void)
+#
+# Get the basename of the binary corresponding to the current process.
+get_current_process_basename() {
+    [[ "${#}" -eq 0 ]] || die 'expected no arguments'
+    local current_process_command_line="$(get_current_process_command_line)"
+    
+    #FIXME: This only strips one dash. How to strip more?
+    # Strip prefixing dashes from this string to prevent the "basename" command
+    # from intepreting such dashes as options to that command. This is actually
+    # a real-world concern. By convention, for example, Linux prefixes login
+    # shell command lines with one dash.
+    current_process_command_line="${current_process_command_line#-}"
+    
+    # Array of strings split on null bytes from the above command-line string.
+    # This is the Linux convention, and probably not applicable to other *nix.
+    current_process_command_line_parts=( "${(0)current_process_command_line}" )
+    
+    # If the current process is a Zsh script (and it better be!), then the path
+    # to this process is given by the third string in this array: e.g.,
+    #
+    #   # For a Zeshy script "h3110", this array resembles...
+    #   current_process_command_line_parts=( zsh /usr/bin/zeshy h3110 )
+    local current_process_path
+    if [[ "${current_process_command_line_parts[1]}" == zsh ]]
+    then current_process_path="${current_process_command_line_parts[3]}"
+    else current_process_path="${current_process_command_line_parts[1]}"
+    fi
+
+    # Return the basename of this binary.
+    basename "${current_process_path}"
+}
+
+# char *get_current_process_command_line(void)
+#
+# Get the command line under which the current process is executing. This is a
+# single string having these parts:
+#
+# * Absolute OR relative path to the executable file from which the process was
+#   executed. Note that, in the latter case, there is no reliable mechanism for
+#   converting the relative path into an absolute path.
+# * Set of all command line arguments passed to the above file, where each such
+#   argument including the first is prefixed by a null delimiter (i.e., "\x00").
+#
+# Due to the above unreliabilities, this string is best used for displaying non-
+# critical log and user interface labels rather than critical functionality.
+get_current_process_command_line() {
+    [[ "${#}" -eq 0 ]] || die 'expected no arguments'
+    
+    # Absolute path to the file having the command line for the current process.
+    local current_process_command_line_path="/proc/$(get_current_process_id)/cmdline"
+    [[ -r "${current_process_command_line_path}" ]] ||
+        die "\"${current_process_command_line_path}\" not found"
+    cat "${current_process_command_line_path}"
+}
+
 # ....................{ KERNEL                             }....................
 #FIXME: Implement! Should, in order:
 #* Accept either an absolute or relative pathname. If absolute, is assumed to be
@@ -55,7 +108,7 @@ get_distro_name() {
 #}
 
 # ....................{ MAIN                               }....................
-_import_all_os_gnu-linux
+_import_os_gnu-linux
 
 # --------------------( COPYRIGHT AND LICENSE              )--------------------
 # The information below applies to everything in this distribution,
