Improved processor handling (frequency scaling).
Reduced copyright minutia in source files. Substantially improved subtle
regressions throughout the codebase. (As ever, fun times abound.)

diff --git a/src/alias b/src/alias
--- a/src/alias
+++ b/src/alias
@@ -1,6 +1,10 @@
 #!/usr/bin/env zsh
 # ====================[ alias                              ]====================
 #
+# --------------------( LICENSE                            )--------------------
+# Copyright 2007-2012 by Cecil Curry.
+# See "COPYING" for additional details.
+#
 # --------------------( SYNOPSIS                           )--------------------
 # Zeshy Alias, handling Zeshy aliases. For efficiency, Zeshy is autoload-based.
 # Only functions are autoloadable, so aliases are not autoloadable. Only this
@@ -335,23 +339,11 @@ alias is_at_most_two_args='(( # <= 2 ))'
 alias is_at_most_three_args='(( # <= 3 ))'
 
 # ....................{ ARGUMENTS ~ exceptions             }....................
-# As a convenience, all argument aliases except die_unless_no_args() first
-# attempt to read their argument from stdin when the caller passed no explicit
-# argument. This implies all functions expanding these aliases implicitly "get"
-# piped input support, which is nice.
-
 # char *make_die_unless_alias(char *test_condition)
 #
-# Make a string suitable for use as the right-hand side of a "die_unless_*"-
-# specific alias statement. This string parses standard input into function
-# parameters if such input exists (i.e., if another function piped input to
-# this function) and the caller passed insufficient parameters.
+# Convert the passed math condition into a die_unless_*() alias expansion.
 make_die_unless_alias() {
-    # We can't quite recall why, but double quotes *MUST* be embedded in this
-    # expression via "'" rather than the customary \".
-    print\
-        "is -p /dev/stdin si and not (( ${1} )) and set -- "\
-        '"${@}" "$(< /dev/stdin)"'"; (( ${1} )) or die"
+    print -- "(( ${1} )) || die"
 }
 
 # void die_if_args(void)
@@ -368,7 +360,6 @@ alias die_unless_args="$(make_die_unless_alias '# > 0')"
 #
 # Die with the passed message unless the caller passed exactly one argument.
 alias die_unless_one_arg="$(make_die_unless_alias '# == 1')"
-#alias die_unless_one_arg='[[ $# -eq 1 ]] or print'
 
 # void die_unless_two_args(char *error_message)
 #
@@ -542,7 +533,7 @@ alias parse_args='zparseopts -D -E -A ARGS -- h -help'
 # aliased. Interactive aliases are inactive in non-interactive scripts and
 # functions, and hence helpful for applying human-readable options on that
 # builtin or command when run directly by a human. This function fails if the
-# builtin or command to be aliased does not exist. See 
+# builtin or command to be aliased does not exist. See
 # interactive_alias_if_installed() for an alternative not failing in such cases.
 #
 # The alias specification format is identical to that of normal aliases: e.g.,
@@ -559,7 +550,7 @@ alias parse_args='zparseopts -D -E -A ARGS -- h -help'
 interactive_alias() {
     die_unless_args
 
-    # Split the passed '='-divided alias specification into name and expansion.
+    # Split the passed '='-delimited alias declaration into name and expansion.
 #   print "args: ${*%%=*}"
     string alias_name=${*%%\=*} alias_expansion=${*#*\=}
 #   split_first "${@}" 'alias_name' 'alias_expansion' '='
@@ -579,11 +570,11 @@ interactive_alias() {
     #     that builtin or command name.
     #   * Otherwise, raise an exception.
     string command_name="${alias_expansion[(w)1]}"
-    string alias_expansion_if_not_interactive="${command_name}"
+    string alias_expansion_if_non_interactive="${command_name}"
     if is "$(whence -w   "${command_name}")" != *': '(builtin|command) si; then
         if is "$(whence -w "${alias_name}")" == *': '(builtin|command) si
-        then alias_expansion_if_not_interactive="${alias_name}"
-        else alias_expansion_if_not_interactive=
+        then alias_expansion_if_non_interactive="${alias_name}"
+        else alias_expansion_if_non_interactive=
         fi
     fi
 
@@ -591,28 +582,42 @@ interactive_alias() {
     alias_expansion+=' "${@}"'
 
     # The string to expand this alias to when called non-interactively.
-    if is -n "${alias_expansion_if_not_interactive}" si
-    then alias_expansion_if_not_interactive+=' "${@}"'
-    else alias_expansion_if_not_interactive="die 'neither \"${alias_name}\" or \"${command_name}\" are builtins or commands and hence cannot be called non-interactively'"
+    if is -n "${alias_expansion_if_non_interactive}" si
+    then alias_expansion_if_non_interactive+=' "${@}"'
+    else alias_expansion_if_non_interactive="die 'neither \"${alias_name}\" or \"${command_name}\" are builtins or commands and hence cannot be called non-interactively'"
     fi
+
+    #FIXME: Hmm; disabling the function makes piped calls such as:
+    #cat /proc/cpuinfo|cat
+    #...fail, which is clearly undesirable.
 
     # Define the desired alias as a function of the same name, which:
     #
     # * Temporarily disables this function to prevent infinite recursion on
     #   subsequently calling a builtin or command of the same name.
-    # * If this shell is interactive (thus excluding non-interactive scripts)
-    #   and this "alias" was called directly from the command line (thus
-    #   excluding non-interactive calls from function implementations), runs
-    #   the passed alias expansion.
-    # * Else if some non-interactive expansion exists, runs such expansion.
+    # * If:
+    #   * This shell is interactive, thus excluding non-interactive scripts.
+    #   * Standard output is attached to a terminal, thus excluding all
+    #     commands in pipe except the last such command.
+    #   * This "alias" was called directly from the command line, thus
+    #     excluding non-interactive calls from functions.
+    #   * Then run the passed alias expansion.
+    # * Else, run the desired non-interactive expansion.
     # * Regardless of whether such run throws an exception, always reenable this
     #   function for subsequent use.
     eval "function ${alias_name}() {
     {
         disable -f ${alias_name}
-        if is -o interactive and \${#funcstack} -eq 1 si
-        then ${alias_expansion}
-        else ${alias_expansion_if_not_interactive}
+        if [[ -o interactive && -t ${ZESHY_STDOUT} && \${#funcstack} -eq 1 ]]; then
+            if is_piped_input
+            then pass_piped_input_to ${alias_expansion}
+            else ${alias_expansion}
+            fi
+        else
+            if is_piped_input
+            then pass_piped_input_to ${alias_expansion_if_non_interactive}
+            else ${alias_expansion_if_non_interactive}
+            fi
         fi
     } always {
         enable -f ${alias_name}
@@ -621,6 +626,39 @@ interactive_alias() {
 }
 
 # --------------------( WASTELANDS                         )--------------------
+# As a convenience, all argument aliases except die_unless_no_args() first
+# attempt to read their argument from stdin when the caller passed no explicit
+# argument. This implies all functions expanding these aliases implicitly "get"
+# piped input support, which is nice.
+
+# Make a string suitable for use as the right-hand side of a "die_unless_*"-
+# specific alias statement. This string parses standard input into function
+# parameters if such input exists (i.e., if another function piped input to
+# this function) and the caller passed insufficient parameters.
+
+#   print --\
+#       '[[ -p /dev/stdin && ${#} -eq 0 ]] && '\
+#       'set -- "${@}" "$(< /dev/stdin)"'"; (( ${1} )) || die"
+    # We can't quite recall why, but double quotes *MUST* be embedded in this
+    # expression via "'" rather than the customary \".
+#       "is -p /dev/stdin si and not (( ${1} )) and set -- "\
+
+#       typeset command
+#       if [[ -o interactive && \${#funcstack} -eq 1 ]]
+#       then command=\"${(q)alias_expansion}\"
+#       else command=\"${(q)alias_expansion_if_non_interactive}\"
+#       fi
+#       if is_piped_input
+#       then pass_piped_input_to \${command}
+#       else                     \${command}
+#       fi
+
+#           if is_piped_input
+#           then pass_piped_input_to ${alias_expansion}
+#           else ${alias_expansion}
+#           fi
+#       then ${alias_expansion}
+#       else ${alias_expansion_if_not_interactive}
 # bool is_terminal(void)
 #
 # Return true if shell output is attached to a terminal device. Specifically,
@@ -742,24 +780,3 @@ interactive_alias() {
 #   string const fwtbt="ride the lightning"  # or...
 #   local -r     fwtbt="ride the lightning"  # equivalent!
 #global_alias const='-r'
-
-# --------------------( COPYRIGHT AND LICENSE              )--------------------
-# The information below applies to everything in this distribution,
-# except where noted.
-#
-# Copyright 2007-2012 by Cecil Curry.
-#
-#   http://www.raiazome.com
-#
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 3 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program. If not, see <http://www.gnu.org/licenses/>.
diff --git a/src/autoload/always/file/content/text b/src/autoload/always/file/content/text
--- a/src/autoload/always/file/content/text
+++ b/src/autoload/always/file/content/text
@@ -1,30 +1,51 @@
 #!/usr/bin/env zsh
 # ====================[ text                               ]====================
 #
+# --------------------( LICENSE                            )--------------------
+# Copyright 2007-2012 by Cecil Curry.
+# See "COPYING" for additional details.
+#
 # --------------------( SYNOPSIS                           )--------------------
-# Zeshy Text File.
+# Zeshy File Content Text, handling non-binary file contents.
 
 # ....................{ ALIASES                            }....................
 is_zeshy_wrapping_core_commands and
-interactive_alias cat='print_text_file_paged'
+interactive_alias cat='print_text_file'
 interactive_alias wclr="get_text_file_line_length_recursively"
 
 # ....................{ ALIASES                            }....................
-# char *print_text_file_paged(char *filename1, char *filename2, ...)
+# char *print_text_file(char *filename1, char *filename2, ...)
 #
 # Print the contents of the passed text files piped to the current pager if such
 # output exceeds the terminal height or as is (i.e., without paging) otherwise.
-print_text_file_paged() {
-    die_unless_args 'expected at least one filename'
-    run_paged cat -- "${@}"
+print_text_file() {
+    if is_piped_input; then
+        die_if_args
+        pass_piped_input_to run_paged command cat
+    else
+        die_unless_args 'expected at least one filename'
 
-    #FIXME: This probably isn't behaving as intended. It *SHOULD* be printing
-    #file contents to stderr while concatenating together file contents. In
-    #practice, it probably just exhumes an error. Hurk!
-#   string output
-#   for filename ("${@}") {
-#       output+="$(< "${filename}" 1>&1 1>&2)"
-#   }
+        # When passed one file, "cat" output unambiguously corresponds to such
+        # file. In such a case, "cat" suffices.
+        if is_one_arg
+        then run_paged command cat -- "${@}"
+        # When passed multiple files, "cat" fails to prepend the output from
+        # each with the corresponding filename. Correct this, scallywag "cat"!
+        else
+            {
+                # Print the first passed file.
+                utter_first_section "${1}"
+                command cat -- "${1}"
+                shift_one_arg
+
+                # Print all other passed files.
+                for filename ("${@}") {
+                    utter_next_section "${filename}"
+                    command cat -- "${filename}"
+                }
+            } | run_paged
+        fi
+    fi
 }
 
 # ....................{ EXCEPTIONS                         }....................
@@ -33,7 +54,7 @@ print_text_file_paged() {
 # Raise an exception unless the passed file exists and is a text file.
 die_unless_text_file() {
     die_unless_one_or_two_args\
-        'expected filename and optional error message'
+        'expected pathname and optional error message'
     string filename="${1}"
     is_text_file "${filename}" or
         die "${2:-\"${filename}\" not found or not a text file}"
@@ -64,17 +85,17 @@ is_text_file_contains() {
     is "${text_file_contents}" == *"${text}"* si
 }
 
-# bool is_text_file_line_matching_pcre(
+# bool is_text_file_pcre_line_match(
 #   char *filename, char *pcre, char *pcre_arg1, char *pcre_arg2, ...)
 #
 # Return true if the passed text file contains a line matching the passed PCRE
 # under option "-m" for multiline matching and the additional passed options.
 # This function implements a pure-Zsh analogue to "grep --perl-regexp".
-is_text_file_line_matching_pcre() {
+is_text_file_pcre_line_match() {
     # Localize.
     die_unless_two_or_three_args\
         'expected one filename, one regex, and optional regex options'
-    string filename="${1}" pcre="${2}" 
+    string filename="${1}" pcre="${2}"
     die_unless_text_file "${filename}"
     shift_one_arg
 
@@ -139,9 +160,9 @@ get_text_files_total_line_length_recursively() {
     #FIXME: Replace dependency on "find" and "wc" with pure Zsh.
     if is_dir "${find_path}"; then
         utter "summing line length for all text files in \"${find_path}\"..."
-        
+
         # Recursively find all files *NOT*:
-        # 
+        #
         # * Non-files (e.g., directories, device files).
         # * Dotfiles and dot directories (e.g., ".cvs/", ".git/", ".svn/").
         # * Binary files. We borrow this expression from is_text_file().
@@ -154,7 +175,7 @@ get_text_files_total_line_length_recursively() {
             convert_integer_to_comma_separated_string
     elif is_file "${find_path}"; then
         utter "getting line length for \"${find_path}\"..."
-        
+
         if is "$(get_filetype "${find_path}")" == pdf si; then
             pdftotext "${find_path}" - | wc -l | comma_separate_integer
         else
@@ -166,7 +187,14 @@ get_text_files_total_line_length_recursively() {
     fi
 }
 
-# ....................{ WASTELANDS                         }....................
+# --------------------( WASTELANDS                         )--------------------
+    #FIXME: This probably isn't behaving as intended. It *SHOULD* be printing
+    #file contents to stderr while concatenating together file contents. In
+    #practice, it probably just exhumes an error. Hurk!
+#   string output
+#   for filename ("${@}") {
+#       output+="$(< "${filename}" 1>&1 1>&2)"
+#   }
     # Test under the "mapfile" module for efficiency.
 #   load_mapfile
 #   is ${mapfile[${filename}]} == *"${text}"* si
@@ -199,24 +227,3 @@ get_text_files_total_line_length_recursively() {
 #is_text_file_find_compatible() {
 #    print "\-exec sh -c 'file --mime-encoding {} | grep --invert-match --quiet \": binary$\"' \\\;"
 #}
-
-# --------------------( COPYRIGHT AND LICENSE              )--------------------
-# The information below applies to everything in this distribution,
-# except where noted.
-#              
-# Copyright 2007-2012 by Cecil Curry.
-#   
-#   http://www.raiazome.com
-# 
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 3 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program. If not, see <http://www.gnu.org/licenses/>.
