Corrected outstanding path command regressions.
Path command-specific functions (e.g., copy_path()) now properly perform
such command without throwing unexpected exceptions.

"And the feeblest keenings of
     the littlest kindling of
     the human fray
 Did sway with indolence in
 The pellicles of rotten rust dinning
 Madly, a
 Smarmy phosphorescence without
 Essential warming lust."

diff --git a/src/compile b/src/compile
--- a/src/compile
+++ b/src/compile
@@ -551,7 +551,7 @@ Perform initialization before sourcing the `zeshy` codebase.
 '
 function compile_zeshy_setup() {
     # Validate sanity.
-    (( # )) && die 'expected no arguments'
+    (( # )) && die 'Expected no arguments.'
 
     # Since recursion is prohibitively expensive, perform a non-recursive depth-
     # first search of overlays starting from the following tree roots (in order):
@@ -605,7 +605,7 @@ Perform finalization after sourcing the `zeshy` codebase.
 '
 function compile_zeshy_names() {
     # Validate sanity.
-    (( # )) && die 'expected no arguments'
+    (( # )) && die 'Expected no arguments.'
 
     # Record the names of all currently defined aliases, functions, and globals.
     # See compile_zeshy_setup() for further details.
@@ -654,11 +654,11 @@ function compile_zeshy_names() {
     # since no core zeshy functionality depends on such aliases, their non-
     # existence does *NOT* constitute grounds for even a non-fatal warning.
     die_unless_list_nonempty ZESHY_ALIAS_NAMES\
-        'expected zeshy to define one or more aliases'
+        'zeshy defined no aliases (i.e., ${ZESHY_ALIAS_NAMES} empty).'
     die_unless_list_nonempty ZESHY_FUNCTION_NAMES\
-        'expected zeshy to define one or more functions'
+        'zeshy defined no functions (i.e., ${ZESHY_FUNCTION_NAMES} empty).'
     die_unless_list_nonempty ZESHY_GLOBAL_NAMES\
-        'expected zeshy to define one or more globals'
+        'zeshy defined no globals (i.e., ${ZESHY_GLOBAL_NAMES} empty).'
 }
 
 ZESHY_CORE_HELP_FUNCTIONS+='
@@ -671,7 +671,7 @@ specific functions to be subsequently compiled into Zeshy''s digest file.
 '
 function compile_zeshy_source() {
     # Validate sanity.
-    (( # )) && die 'expected no arguments'
+    (( # )) && die 'Expected no arguments.'
 
     # Inform the current user of such recompilation.
     if [[ -o interactive ]] {
@@ -694,8 +694,8 @@ function compile_zeshy_source() {
     # push such overlays onto the same stack of iterated overlays. To facilitate
     # this safely, iterate dynamically (e.g., with "for ((...))") rather than
     # statically (e.g., with "for overlay_dir (...)").
-    integer index
-    for ((  index = 1; index <= ${#ZESHY_OVERLAY_DIRNAME_STACK}; index++ )) {
+    integer index=1
+    for ((; index <= ${#ZESHY_OVERLAY_DIRNAME_STACK}; index++ )) {
         compile_zeshy_overlay "${ZESHY_OVERLAY_DIRNAME_STACK[index]}"
     }
 
@@ -744,7 +744,7 @@ compiled into such digest.)
 '
 function compile_zeshy_digest() {
     # Validate sanity.
-    (( # )) && die 'expected no arguments'
+    (( # )) && die 'Expected no arguments.'
 
     # If loading zeshy's user directory, compile all zeshy functions excluding
     # those defined by top-level components (e.g., "main", "digest") into
@@ -778,12 +778,13 @@ above in "OVERLAYS". For each:
     contain `zsh` scripts, but not both.)
 '
 function compile_zeshy_overlay() {
-    # Validate passed arguments.
-    (( # == 1 )) || die 'expected one overlay dirname'
+    # Validate sanity.
+    (( # == 1 )) || die 'Expected one overlay dirname.'
     local overlay_dirname="${1}"
-    [[ -d "${overlay_dirname}" ]] || die "\"${overlay_dirname}\" not a directory"
+    [[ -d "${overlay_dirname}" ]] ||
+            die "\"${overlay_dirname}\" not a directory."
 
-    # If the current user is a Zeshy developer and the current shell is
+    # If the current user is a zeshy developer and the current shell is
     # interactive, print such path to standard output.
     is_zeshy_debug_and print "zeshy: overlaying \"${overlay_dirname}\"..."
 #   print "overlaying \"${overlay_dirname}\"..."
@@ -835,10 +836,14 @@ overlay directory to `zeshy`\''s user configuration directory, if not already
 found in the latter.
 '
 function compile_zeshy_overlay_configuration() {
-    # Validate passed arguments. If such overlay contains no configuration
-    # subdirectory, return silently.
-    (( # == 1 )) || die 'expected one overlay dirname'
-    local overlay_config_dirname="${1}/if_config" source_filename
+    # Validate sanity. If such overlay contains no configuration subdirectory,
+    # return silently.
+    (( # == 1 )) || die 'Expected one overlay dirname.'
+    local\
+        overlay_config_dirname="${1}/if_config"\
+        source_filename\
+        target_filename\
+        filename_suffix
     [[ -d "${overlay_config_dirname}" ]] || return 0
 
     # If ignoring zeshy's user directory, source such files from such overlay
@@ -852,7 +857,6 @@ function compile_zeshy_overlay_configuration() {
     }
 
     # For each configuration file in the passed overlay, globbed recursively...
-    local source_filename filename_suffix target_filename
     for   source_filename (
         "${overlay_config_dirname}/"**/${~ZESHY_SCRIPT_NAME_GLOB}) {
         # Strip off the prefixing overlay configuration directory (e.g., from
@@ -896,7 +900,7 @@ Namely, append:
 '
 function compile_zeshy_overlay_commands() {
     # Validate sanity.
-    (( # == 1 )) || die 'expected one overlay dirname'
+    (( # == 1 )) || die 'Expected one overlay dirname.'
     local overlay_command_dirname="${1}/if_pathable"
     local -a overlay_command_paths
     [[ -d "${overlay_command_dirname}" ]] || return 0
@@ -949,7 +953,7 @@ Specifically, run all commands in list ${ZESHY_HOOKS_RUN_ON_ZESHY_PRECOMPILE}
 '
 function precompile_zeshy() {
     # Validate sanity.
-    (( # )) && die 'expected no arguments'
+    (( # )) && die 'Expected no arguments.'
 
     #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     #ORDER IS SUBTLY IMPORTANT HERE (i.e., cranky graemlins slumber within).
@@ -1024,7 +1028,7 @@ Declare and define startup_zeshy() and all remaining functions the following fun
 '
 function compile_zeshy_startup() {
     # Validate sanity.
-    (( # )) && die 'expected no arguments'
+    (( # )) && die 'Expected no arguments.'
 
     #FIXME: We should probably throw exceptions or print warnings if *ANY*
     #zeshy globals to be compiled into the digest are exported. I suspect we'll
@@ -1156,7 +1160,7 @@ Cache temporary files and directories specific to the current compilation of
 '
 function compile_zeshy_user_cache() {
     # Validate sanity.
-    (( # )) && die 'expected no arguments'
+    (( # )) && die 'Expected no arguments.'
 
     # Serialize such lists.
     write_file_with_variable\
