Completed the move_*() family of functions.
Renamed "if_installed" to "if_pathable".

diff --git a/src/compile b/src/compile
--- a/src/compile
+++ b/src/compile
@@ -60,7 +60,7 @@
 #   * Subdirectories with arbitrary names and nesting. (Zeshy automatically
 #     finds all scripts in such subdirectories. Subdirectory structure is
 #     insignificant and hence only for optional organization.)
-# * "if_installed", a subdirectory directly containing only:
+# * "if_pathable", a subdirectory directly containing only:
 #   * Zeshy scripts, each conditionally compiled into Zeshy's digest file *ONLY*
 #     if an executable file of the same case-sensitive basename currently exists
 #     in the user-specific ${PATH}.
@@ -542,6 +542,7 @@ function compile_zeshy_overlay() {
     # interactive, print such path to standard output.
     [[ -n "${ZESHY_IS_DEBUGGING-}" && -o interactive ]] &&
         say "overlaying \"${overlay_dir}\"..."
+#   say "overlaying \"${overlay_dir}\"..."
 
     # Absolute paths of overlay subdirectories.
     local\
@@ -585,41 +586,69 @@ function compile_zeshy_overlay() {
 document_function '
 void compile_zeshy_overlay_configs(string overlay_dirname)
 
-Prepare all user configuration files in the passed overlay directory. Namely:
-
-* Copy such files from such directory to Zeshy''s user configuration directory
-  for Zeshy, if not already there.
-* Source such files from such directory, thus allowing the user opportunity to
-  change such files.
+Recursively copy all files from the "if_config" subdirectory of the passed
+overlay directory to Zeshy''s user configuration directory, if not already found
+in the latter; then source such files.
 '
 function compile_zeshy_overlay_configs() {
     # Validate passed arguments.
     (( # == 1 )) || die 'expected one overlay dirname'
     local overlay_config_dir="${1}/if_config"
+
+    # If such overlay contains no configuration subdirectory, return silently.
     [[ -d "${overlay_config_dir}" ]] || return 0
 
     #FIXME: This'd be a nice place to add update handling for patching locally
     #modified config files against Zeshy-bundled config files on update.
-    # Handle each configuration file in the passed overlay.
-    local basename target_filename
-    for source_filename ("${overlay_config_dir}/"${~ZESHY_SCRIPT_GLOB}) {
-        basename="$(basename -- "${source_filename}")"
-        target_filename="${ZESHY_DOT_CONFIG_DIR}/${basename}"
+    #FIXME: Hmmmm; no, actually. We want to implement the upgrade process as
+    #a startup_zeshy_upgrade()-style function in the main Zeshy codebase. Why?
+    #Firstly, such upgrade will inevitably become a bit heavyweight, with
+    #functionality conditionally depending on which "diff"-style merge commands
+    #are installed and available to the current user (e.g., "gdiff", "vimdiff").
+    #Secondly, it's simply cleaner to defer upgrading until *AFTER* the Zeshy
+    #has fully bootstrapped itself. Since we already expand config globals
+    #defensively (e.g., ${ZESHY_THEME:-vanilla}), this should pose no issues
+    #even if we were to subsequently, say, rename ${ZESHY_THEME} to
+    #${ZESHY_USER_THEME}.
 
-        # Source such script.
-#       say "sourcing \"${target_filename}\"..."
-        source -- "${source_filename}"
-
-        # If loading Zeshy's user configuration directory and such directory
-        # does not already contain such script, copy such script from such
-        # overlay to such directory for subsequent user-specific editing.
-        [[ ! -f "${target_filename}" && -n "${ZESHY_DOT_DIR}" ]] && {
-            # If the current user is a Zeshy developer and the current shell is
-            # interactive, print such path to standard output.
-            [[ -n "${ZESHY_IS_DEBUGGING-}" && -o interactive ]] &&
-                say "defaulting \"${target_filename}\"..."
-            command cp -- "${source_filename}" "${target_filename}"
+    # For each configuration file in the passed overlay, globbed recursively...
+    local filename_suffix target_filename
+    for source_filename ("${overlay_config_dir}/"**/${~ZESHY_SCRIPT_GLOB}) {
+        # If ignoring Zeshy's user directory, source such file from such overlay
+        # without copying such file to such directory.
+        [[ -n "${ZESHY_DOT_DIR}" ]] || {
+            source -- "${source_filename}"
+            continue
         }
+
+        # Strip off the prefixing overlay configuration directory (e.g., from
+        # "/usr/share/zeshy/src/if_config/if_shell_interactive/00-alias" to.
+        # "if_shell_interactive/00-alias").
+        filename_suffix="${source_filename#${overlay_config_dir}}"
+
+        # Set the target filename appended with such suffix.
+        target_filename="${ZESHY_DOT_CONFIG_DIR}/${filename_suffix}"
+
+        # If Zeshy's user configuration directory already contains such file,
+        # continue to the next file without sourcing the current file. Zeshy's
+        # sourcing of component "config" previously sourced such file, already.
+        [[ -f "${target_filename}" ]] && continue
+
+        # If the current user is a Zeshy developer and the current shell is
+        # interactive, print such path to standard output.
+        [[ -n "${ZESHY_IS_DEBUGGING-}" && -o interactive ]] &&
+            say "defaulting \"${target_filename}\"..."
+#       say "defaulting \"${target_filename}\"..."
+
+        # Make such file's parent directory, if needed.
+        command mkdir -p -- "${target_filename:h}"
+
+        # Copy such file.
+        command cp -- "${source_filename}" "${target_filename}"
+
+        # Source such file.
+#       say "sourcing \"${target_filename}\"..."
+        source -- "${target_filename}"
     }
 }
 
@@ -637,7 +666,7 @@ Namely, append:
 function compile_zeshy_overlay_commands() {
     # Validate sanity.
     (( # == 1 )) || die 'expected one overlay dirname'
-    local overlay_command_dir="${1}/if_installed"
+    local overlay_command_dir="${1}/if_pathable"
     [[ -d "${overlay_command_dir}" ]] || return 0
 
     # List of all paths in this overlay's command directory corresponding to a
@@ -701,6 +730,26 @@ function compile_zeshy_overlay_commands() {
 compile_zeshy
 
 # --------------------( WASTELANDS                         )--------------------
+        # If Zeshy's user configuration directory does not already contain
+        # such file, copy such file from such overlay to such directory.
+#       [[ ! -f "${target_filename}" ]] && {
+#to Zeshy's user-specific configuration directory
+# Since upgrading occurs after digest
+    #compilation but "~/.zeshy/config/zeshy" would already exist,
+    #${ZESHY_USER_THEME} would not be found here, provoking a Zsh error (e.g.,
+    #"no such variable"). Simplest way to fix this:
+    #
+    #* Behave defensively. Never assume a global setting to exist (e.g., always
+    #  append "-" to parameter expansions). This probably needs to happen
+    #  anyway, for safety and robustness. Make it so!
+#FUXME: It'd be nice to harmonize config dirs "/usr/share/zeshy/src/if_config"
+#and "~/
+
+#Prepare all user configuration files in the passed overlay directory. Namely:
+#
+#* Recursively copy all such files not found in Zeshy''s user-specific
+#  configuration directory to such directory.
+#* Source such files.
     #FUXME: Rather than print each overlay, it would be *MUCH* more concise and
     #hence reasonable to only print the set of all sourced overlays after the
     #fact. To do so, simply iterate local list ${ZESHY_OVERLAY_STACK} after
@@ -995,7 +1044,7 @@ compile_zeshy
 #       if is -d "${autoload_distro_dir}" si; then
 #           ZESHY_AUTOLOAD_DIRNAMES+="${autoload_distro_dir}/always"
 #           ZESHY_AUTOLOAD_FILENAMES+=(
-#               "${autoload_distro_dir}/if_installed/"*(e{'[[ $REPLY:t:c == /* ]]'})
+#               "${autoload_distro_dir}/if_pathable/"*(e{'[[ $REPLY:t:c == /* ]]'})
 #           ) or true
 #       fi
 #   fi
@@ -1099,7 +1148,7 @@ compile_zeshy
     # Forcibly prevent harmful ${mapfile} and hence filesystem changes.
 #       typeset -r mapfile
 #       print ${mapfile[/tmp/config]}
-#       print -rl -- ${(f)mapfile[/usr/share/zeshy/src/autoload/if_installed/7z]}
+#       print -rl -- ${(f)mapfile[/usr/share/zeshy/src/autoload/if_pathable/7z]}
 
     # For each function declared in each file in the passed directory and
     # subdirectories of that directory, make a symbolical link in the digest
@@ -1186,13 +1235,13 @@ compile_zeshy
 #       zcompile "${ZESHY_DOT_DIGEST_FILE}" "${ZESHY_DOT_DIGEST_DIR}"/**/*(@)
 #               ${${${(M)${(f)mapfile[${autoload_function_filename}]}:#([[:alnum:]_-]##\(\) \{|interactive_alias [[:alnum:]_-]##=?)*}#interactive_alias }%%( \(|\=)*}
             #FIXME: I believe these two mappings can be condensed into one.
-#               ${(f)mapfile[/usr/share/zeshy/src/autoload/if_installed/7z]}
+#               ${(f)mapfile[/usr/share/zeshy/src/autoload/if_pathable/7z]}
 #               ${(f)mapfile[${autoload_function_filename}]}
 #               ${(M)${(f)mapfile[${autoload_function_filename}]}:#([[:alnum:]_-]##\(\) \{|interactive_alias [[:alnum:]_-]##=?)*}
 #               ${${${(M)${(f)mapfile[${autoload_function_filename}]}:#([[:alnum:]_-]##\(\) \{|interactive_alias [[:alnum:]_-]##=?)*}#interactive_alias }%%( \(|=)*}
 #               ${${${(M)${(f)mapfile[${autoload_function_filename}]}:#interactive_alias [[:alnum:]_-]##=?*}#interactive_alias }%%\=*}
 #               ${${(M)${(f)mapfile[${autoload_function_filename}]}:#[[:alnum:]_-]##\(\) \{}%%\(*}
-#               ${${${(M)${(f)mapfile[/usr/share/zeshy/src/autoload/if_installed/7z]}:#interactive_alias [[:alnum:]_-]##=?*}#interactive_alias }%%\=*}
+#               ${${${(M)${(f)mapfile[/usr/share/zeshy/src/autoload/if_pathable/7z]}:#interactive_alias [[:alnum:]_-]##=?*}#interactive_alias }%%\=*}
 #           print "interactive_aliases:"
 #           print -rl -- ${${${(M)${(f)mapfile[${autoload_function_filename}]}:#interactive_alias [[:alnum:]_-]##=*}#interactive_alias }%%\=*}
 
