Nominally completed @{compile} refactoring.
Such refactoring has yet to be strenuously tested but *SHOULD* hold up modestly
well. (Naturally, Murphy has yet to interject himself into the process.)

diff --git a/src/compile b/src/compile
--- a/src/compile
+++ b/src/compile
@@ -484,8 +484,8 @@ function :run_hook_on_zeshy_precompile() {
 }
 
 # ....................{ COMPILERS                          }....................
-# void compile_zeshy(void)
-function compile_zeshy() {
+# void :compile_zeshy(void)
+function :compile_zeshy() {
     # Validate sanity.
     (( # )) && die 'Expected no arguments.'
 
@@ -717,80 +717,72 @@ function :compile_zeshy_overlay() {
     # Validate sanity.
     (( # == 1 )) || die 'Expected one overlay dirname.'
     local dirname_overlay="${1}" dirname_overlay_main
+    typeset -a dirnames_suboverlay
     [[ -d "${dirname_overlay}" ]] ||
-        die "\"${dirname_overlay}\" not a directory."
-
-    # If the current user is a zeshy developer and the current shell is
-    # interactive, print such path to standard output.
+        die "Overlay \"${dirname_overlay}\" not found or not a directory."
     is_zeshy_debug_and print "zeshy: Overlaying \"${dirname_overlay}\"."
-#   print "overlaying \"${dirname_overlay}\"..."
 
-    # ~~~~~~~~~~~~~~~~< IMPORTANT ~ order is significant   >~~~~~~~~~~~~~~~~~~~~
-    # Order of operation is significant below. Later paths assume precedence
-    # over prior paths in corresponding lists.
-
-    # If such overlay is *NOT* the topmost system-wide overlay, append all
-    # scripts in such overlay's directory. The topmost system-wide overlay
-    # contains the current script among others and should *NOT* be resourced.
+    # If such overlay is *NOT* the topmost system-wide overlay, register all
+    # files in such directory. The topmost system-wide overlay contains the
+    # current script (among others) and must *NOT* be resourced.
     if [[ "${dirname_overlay}" != "${ZESHY_OVERLAY_DIR}" ]] {
         ZESHY_OVERLAY_FILENAMES+=(
             "${dirname_overlay}"/${~ZESHY_SCRIPT_NAME_GLOB} )
     }
 
-    # Absolute path of the main suboverlay.
-    dirname_overlay_main="${dirname_overlay}/always"
+    # List of the absolute paths of all subdirectories and hence suboverlays of
+    # such overlay in lexicographic order.
+    dirnames_suboverlay=( "${dirname_overlay}"/*(-/) )
+#   suboverlay_dirnames_ordered=( "${overlay_dirname}"/<->'-'?*(/) )
 
-    # If such suboverlay exists, register all `zsh` scripts in such directory
-    # and subdirectories of such directory.
-    if [[ -d "${dirname_overlay_main}" ]] {
-        ZESHY_OVERLAY_FILENAMES+=(
-            "${dirname_overlay_main}"/**/${~ZESHY_SCRIPT_NAME_GLOB} )
+    # Compile such suboverlays.
+    local dirname_suboverlay compile_suboverlay
+    for   dirname_suboverlay ("${dirnames_suboverlay[@]}") {
+        # Name of the function compiling such overlay if such overlay requires
+        # special handling. Dismantled, this is:
+        #
+        # * ":t", reducing such directory to its basename.
+        # * "##*-", reducing such basename to the substring following the last
+        #   "-" in such basename, if found.
+        compile_suboverlay=":compile_zeshy_suboverlay_${dirname_suboverlay:t##*-}"
+
+        # If such function does *NOT* exist, default such function to the
+        # standard function compiling overlays requiring no special handling.
+        # Such function is guaranteed to exist.
+        (( ${+functions[${compile_suboverlay}]} )) ||
+            compile_suboverlay=':compile_zeshy_suboverlay_simple'
+
+        # Compile such suboverlay.
+        "${compile_suboverlay}" "${dirname_suboverlay}"
     }
-
-    # Source all configuration files in such overlay's configuration directory.
-    # Do so prior to all other overlay logic depending on globals defined by
-    # such files.
-    :compile_zeshy_suboverlay_if_config "${dirname_overlay}"
-
-    # Append such overlay's command directory to appropriate lists, if found.
-    :compile_zeshy_suboverlay_if_pathable "${dirname_overlay}"
-
-    # Append the subdirectory of such overlay's distro directory matching the
-    # user's currently installed distro to the overlay stack, if found.
-    #
-    # Do this after all other overlay logic, allowing distro-specific
-    # redefinition of generic functionality.
-    :compile_zeshy_suboverlay_if_distro "${dirname_overlay}"
 }
 
-#    list suboverlay_dirnames_ordered
-#    suboverlay_dirnames_ordered=( "${overlay_dirname}"/<->'-'?*(/) )
-#
-#    local suboverlay_dirname_ordered suboverlay_type
-#    for   suboverlay_dirname_ordered ("${suboverlay_dirnames_ordered[@]}") {
-#       # Strip the prefixing integer from such suboverlay basename.
-#       suboverlay_type="${suboverlay_dirname_ordered:t#<->-}"
-#
-#       # Handle such suboverlay according to its type.
-#       case "${suboverlay_type}" {
-#       # Handle directories with special names in a special manner.
-#       if_config) ...;;
-#       if_pathable) ...;;
-#       # Handle all other directories as "always"-type overlays (e.g., simply
-#       # recursively source all files in such overlays).
-#       *) ...;;
-#       }
-#    }
-
-# void :compile_zeshy_suboverlay_if_config(string overlay_dirname)
-function :compile_zeshy_suboverlay_if_config() {
-    # Validate sanity. If such overlay contains no such suboverlay, return.
-    (( # == 1 )) || die 'Expected one overlay dirname.'
+# void :compile_zeshy_suboverlay_simple(string suboverlay_dirname)
+function :compile_zeshy_suboverlay_simple() {
+    # Validate sanity.
+    (( # == 1 )) || die 'Expected one suboverlay dirname.'
     local\
-        dirname_suboverlay="${1}/if_config"\
+        dirname_suboverlay="${1}"\
         filename_src\
         filename_trg
-    [[ -d "${dirname_suboverlay}" ]] || return 0
+    [[ -d "${dirname_suboverlay}" ]] ||
+        die "Suboverlay \"${dirname_suboverlay}\" not found or not a directory."
+
+    # Recursively register all `zsh` scripts in such directory.
+    ZESHY_OVERLAY_FILENAMES+=(
+        "${dirname_suboverlay}"/**/${~ZESHY_SCRIPT_NAME_GLOB} );;
+}
+
+# void :compile_zeshy_suboverlay_if_config(string suboverlay_dirname)
+function :compile_zeshy_suboverlay_if_config() {
+    # Validate sanity.
+    (( # == 1 )) || die 'Expected one suboverlay dirname.'
+    local\
+        dirname_suboverlay="${1}"\
+        filename_src\
+        filename_trg
+    [[ -d "${dirname_suboverlay}" ]] ||
+        die "Suboverlay \"${dirname_suboverlay}\" not found or not a directory."
 
     # For each configuration file recursively globbed in such suboverlay...
     for filename_src ("${dirname_suboverlay}/"**/${~ZESHY_SCRIPT_NAME_GLOB}) {
@@ -816,7 +808,7 @@ function :compile_zeshy_suboverlay_if_config() {
         #with no one the wiser.
         #
         #Catching such errors will require us to declare a local map in
-        #top-level function compile_zeshy() (for efficient lookup) from
+        #top-level function :compile_zeshy() (for efficient lookup) from
         #pathnames relative to "~/.zeshy/config" to the empty string: e.g.,
         #
         #    map ZESHY_OVERLAY_IF_CONFIG_FILENAMES
@@ -1067,9 +1059,60 @@ function :precompile_zeshy_cache() {
 
 # ....................{ MAIN                               }....................
 # Recompile zeshy's user digest file.
-compile_zeshy
+:compile_zeshy
 
 # --------------------( WASTELANDS                         )--------------------
+    #FUXME: Excise everything below. *simpering sigh*
+
+    # ~~~~~~~~~~~~~~~~< IMPORTANT ~ order is significant   >~~~~~~~~~~~~~~~~~~~~
+    # Order of operation is significant below. Later paths assume precedence
+    # over prior paths in corresponding lists.
+
+    # # Absolute path of the main suboverlay.
+    # dirname_overlay_main="${dirname_overlay}/always"
+
+    # # If such suboverlay exists, register all `zsh` scripts in such directory
+    # # and subdirectories of such directory.
+    # if [[ -d "${dirname_overlay_main}" ]] {
+    #     ZESHY_OVERLAY_FILENAMES+=(
+    #         "${dirname_overlay_main}"/**/${~ZESHY_SCRIPT_NAME_GLOB} )
+    # }
+
+    # # Source all configuration files in such overlay's configuration directory.
+    # # Do so prior to all other overlay logic depending on globals defined by
+    # # such files.
+    # :compile_zeshy_suboverlay_if_config "${dirname_overlay}"
+
+    # # Append such overlay's command directory to appropriate lists, if found.
+    # :compile_zeshy_suboverlay_if_pathable "${dirname_overlay}"
+
+    # # Append the subdirectory of such overlay's distro directory matching the
+    # # user's currently installed distro to the overlay stack, if found.
+    # #
+    # # Do this after all other overlay logic, allowing distro-specific
+    # # redefinition of generic functionality.
+    # :compile_zeshy_suboverlay_if_distro "${dirname_overlay}"
+
+    # If the current user is a zeshy developer and the current shell is
+    # interactive, print such path to standard output.
+#   print "overlaying \"${dirname_overlay}\"..."
+
+        # # For efficiency in matching below, strip such directory of its parent
+        # # directory and optional ordering prefix (e.g., "/usr/share/zeshy/00-").
+        # magic_suboverlay="${suboverlay_dirname_ordered:t#<->-}"
+
+        # # Handle such suboverlay according to its type.
+        # case "${magic_suboverlay}" {
+        # # Handle suboverlays suffixed by magic strings magically. For
+        # # efficiency, match in descending order of real-world likelihood.
+        # if_config)   :compile_zeshy_suboverlay_if_config   "${dirname_suboverlay}";;
+        # if_pathable) :compile_zeshy_suboverlay_if_pathable "${dirname_suboverlay}";;
+        # if_distro)   :compile_zeshy_suboverlay_if_distro   "${dirname_suboverlay}";;
+        # # Handle all other suboverlays non-magically (e.g., unconditionally
+        # # register all zsh scripts in such suboverlays).
+        # *) :compile_zeshy_suboverlay_simple "${dirname_suboverlay}";;
+        # }
+
     #FUXME: We can and should call remove_list_items_matching_glob() and
     #set_list_to_list_difference() below.
 
