More edits of print_string() to return_string().
The codebase is now converted "enough" to return_string() that I'm
contemplating a soft moritorium on further breakage. This implies: up
next, a loudly steaming pile of regression fixes.

diff --git a/src/digest b/src/digest
--- a/src/digest
+++ b/src/digest
@@ -16,7 +16,7 @@ Absolute path of the file to which Zeshy caches the list of all paths Zeshy''s
 user digest file depends on. See ${ZESHY_DIGEST_DEPENDENCY_PATHNAMES} for
 further details.
 '
-export ZESHY_CACHE_DIGEST_DEPENDENCIES_FILE="${ZESHY_DOT_CACHE_DIR}/digest.dependencies"
+export ZESHY_CACHE_DIGEST_DEPENDENCIES_FILE="${ZESHY_USER_CACHE_DIR}/digest.dependencies"
 
 ZESHY_GLOBAL_DOCUMENTATION+='
 list ZESHY_DIGEST_DEPENDENCY_PATHNAMES
@@ -55,7 +55,7 @@ the newest of:
   Installing or uninstalling commands requires recompiling command autoloads.
 
 For convenience, set integer global
-${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} to the modification
+${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} to the modification
 time of the newest path such digest depends upon.
 '
 function is_zeshy_digest_outdated() {
@@ -69,19 +69,19 @@ function is_zeshy_digest_outdated() {
     # configuration directory both exist *AND* the latter contains at least one
     # directory or file (i.e., is non-empty), return such digest to be outdated.
     [[ -n "${ZESHY_DOT_DIR}" &&\
-       -d "${ZESHY_DOT_CONFIG_DIR}" &&\
-       -f "${ZESHY_DOT_DIGEST_FILE}" &&\
+       -d "${ZESHY_USER_CONFIG_DIR}" &&\
+       -f "${ZESHY_USER_DIGEST_FILE}" &&\
        -f "${ZESHY_CACHE_DIGEST_DEPENDENCIES_FILE}" ]] && {
         local -a zeshy_dot_config_dir_if_nonempty
-        zeshy_dot_config_dir_if_nonempty=( "${ZESHY_DOT_CONFIG_DIR}"(/F) )
+        zeshy_dot_config_dir_if_nonempty=( "${ZESHY_USER_CONFIG_DIR}"(/F) )
         (( ${#zeshy_dot_config_dir_if_nonempty} ))
     } || {
         # Before returning, set global
-        # ${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} as
+        # ${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} as
         # required by this function's definition to the current time. This
         # guarantees the modification time for Zeshy's user digest file will be
         # coerced to the current time.
-        ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME="$(date +'%s')"
+        ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME="$(date +'%s')"
         return 0
     }
 
@@ -176,9 +176,9 @@ function is_zeshy_digest_outdated() {
     # While getting such times is mildly expensive, the alternative cost of
     # redefining user-configured interactive aliases on each Zeshy startup
     # outweighs such expense. See discussion below for implementation details.
-    [[ -d "${ZESHY_DOT_CONFIG_DIR}" ]] && {
-        zeshy_dependency_mtimes+="$(zstat +mtime "${ZESHY_DOT_CONFIG_DIR}")"
-        zeshy_dependency_mtimes+="$(zstat +mtime "${ZESHY_DOT_CONFIG_DIR}"/**/*(om[1]))"
+    [[ -d "${ZESHY_USER_CONFIG_DIR}" ]] && {
+        zeshy_dependency_mtimes+="$(zstat +mtime "${ZESHY_USER_CONFIG_DIR}")"
+        zeshy_dependency_mtimes+="$(zstat +mtime "${ZESHY_USER_CONFIG_DIR}"/**/*(om[1]))"
     }
 
     # If the current user is a Zeshy developer, obtain the last modification
@@ -190,7 +190,7 @@ function is_zeshy_digest_outdated() {
     # * "${...}"/**/*, all files and directories of this codebase.
     # * "om", sorting such files and directories by descending mtime.
     # * "[1]", the first and hence newest such file or directory.
-    [[ -n "${ZESHY_DOT_DIGEST_FILE_IS_DEPENDENT_ON_ZESHY_HOME}" ]] && {
+    [[ -n "${ZESHY_USER_DIGEST_FILE_IS_DEPENDENT_ON_ZESHY_HOME}" ]] && {
 #       print "adding Zeshy codebase \"${ZESHY_HOME}\" as a digest dependency..."
         zeshy_dependency_mtimes+="$(zstat +mtime "${ZESHY_HOME}"/**/*(om[1]))"
     }
@@ -205,25 +205,25 @@ function is_zeshy_digest_outdated() {
     # If the caller failed to declare such integer, do so locally. Ideally, the
     # caller declares such integer to subsequently set such file's modification
     # time using such integer. See digest_zeshy_compile() for further details.
-    [[ ${+ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} -eq 1 &&
-       "${(t)ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}" == 'integer'* ]] || {
-#       print 'localizing ${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}...'
-        local -i ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME
+    [[ ${+ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} -eq 1 &&
+       "${(t)ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}" == 'integer'* ]] || {
+#       print 'localizing ${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}...'
+        local -i ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME
     }
-    ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME="${${(nO@)zeshy_dependency_mtimes}[1]}"
+    ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME="${${(nO@)zeshy_dependency_mtimes}[1]}"
 
     # The modification time of Zeshy's digest.
     integer zeshy_digest_mtime
-    zeshy_digest_mtime="$(zstat +mtime "${ZESHY_DOT_DIGEST_FILE}")"
+    zeshy_digest_mtime="$(zstat +mtime "${ZESHY_USER_DIGEST_FILE}")"
 
     # If Zeshy's digest is older than its newest dependency, signify such digest
     # to be outdated by returning true.
 #   print "mtimes: ${dependency_mtimes[@]}"
 #   print "newest: ${ZESHY_NEWEST_DEPENDENCY_MTIME}"
 #   print "digest: ${zeshy_digest_mtime}"
-#   print "digest file: \"${ZESHY_DOT_DIGEST_FILE}\""
+#   print "digest file: \"${ZESHY_USER_DIGEST_FILE}\""
     (( zeshy_digest_mtime <\
-        ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME ))
+        ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME ))
 }
 
 # ....................{ SETUP                              }....................
@@ -251,27 +251,27 @@ function digest_zeshy() {
     # path such digest depends on; else 0. While this function itself does not
     # refer to this variable, explicitly declare this variable here to provide
     # shared access to this variable by functions this function calls. (Subtle!)
-    local -i ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME
+    local -i ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME
 
     # If Zeshy's user digest file is outdated or the caller demands recompiling
     # such file regardless of whether it's outdated or not, compile all Zeshy
     # functions applicable to the current user into such digest and render such
     # functions autoloadable. See "main" for declaration of the latter
-    # condition, "${ZESHY_DOT_DIGEST_FILE_IS_COMPILING}".
-#   print "detecting \"${ZESHY_DOT_DIGEST_FILE}\"..."
+    # condition, "${ZESHY_USER_DIGEST_FILE_IS_COMPILING}".
+#   print "detecting \"${ZESHY_USER_DIGEST_FILE}\"..."
     if is_zeshy_digest_outdated ||
-        [[ -n "${ZESHY_DOT_DIGEST_FILE_IS_COMPILING-}" ]]; then
+        [[ -n "${ZESHY_USER_DIGEST_FILE_IS_COMPILING-}" ]]; then
         digest_zeshy_compile
     # Otherwise, attempt to autoload the previously compiled digest for the
     # current user. If such autoload fails, (re)compile such digest and try
     # again.
-    else autoload -w -- "${ZESHY_DOT_DIGEST_FILE}" || digest_zeshy_compile
-#       print "autoloading \"${ZESHY_DOT_DIGEST_FILE}\"..."
+    else autoload -w -- "${ZESHY_USER_DIGEST_FILE}" || digest_zeshy_compile
+#       print "autoloading \"${ZESHY_USER_DIGEST_FILE}\"..."
     fi
 
     # Prefix the function path with the absolute path to the digest file to
     # ensure zsh searches such file for the definition of such functions first.
-    fpath=( "${ZESHY_DOT_DIGEST_FILE}" "${fpath[@]}" )
+    fpath=( "${ZESHY_USER_DIGEST_FILE}" "${fpath[@]}" )
 }
 
 ZESHY_FUNCTION_DOCUMENTATION+='
@@ -302,15 +302,15 @@ function digest_zeshy_compile() {
     # Validate sanity. Unless the modification time of the newest path Zeshy's
     # user digest file depends on was previously set, throw an exception.
     (( # == 0 )) || die 'expected no arguments'
-    (( ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME )) ||
-        die '"ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME" not set'
+    (( ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME )) ||
+        die '"ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME" not set'
 
     # If debugging Zeshy, print modification times for Zeshy's user digest file
     # and the newest path such file depends upon.
     is_zeshy_verbose_and {
-        [[ -f "${ZESHY_DOT_DIGEST_FILE}" ]] &&
-            print "zeshy: digest mtime:                   $(zstat +mtime "${ZESHY_DOT_DIGEST_FILE}")"
-            print "zeshy: digest newest dependency mtime: ${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}"
+        [[ -f "${ZESHY_USER_DIGEST_FILE}" ]] &&
+            print "zeshy: digest mtime:                   $(zstat +mtime "${ZESHY_USER_DIGEST_FILE}")"
+            print "zeshy: digest newest dependency mtime: ${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}"
     }
 
     # Source all applicable Zeshy scripts and hence functions.
@@ -319,21 +319,21 @@ function digest_zeshy_compile() {
     # Set the modification time of such digest to that of the newest
     # modification time to avoid recompilation on the next Zeshy run.
     touch -m\
-        --date=@${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}\
-        -- "${ZESHY_DOT_DIGEST_FILE}"
+        --date=@${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}\
+        -- "${ZESHY_USER_DIGEST_FILE}"
 
     # Declare all functions defined by such digest to be autoloadable.
-#   print "autoloading \"${ZESHY_DOT_DIGEST_FILE}\"..."
-    autoload -w -- "${ZESHY_DOT_DIGEST_FILE}" ||
-        die "\"${ZESHY_DOT_DIGEST_FILE}\" cannot be compiled"
+#   print "autoloading \"${ZESHY_USER_DIGEST_FILE}\"..."
+    autoload -w -- "${ZESHY_USER_DIGEST_FILE}" ||
+        die "\"${ZESHY_USER_DIGEST_FILE}\" cannot be compiled"
 }
 
 # ....................{ MAIN                               }....................
 digest_zeshy
 
 # --------------------( WASTELANDS                         )--------------------
-#FUXME: Rename ${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} to
-#${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}. Even the latter's longer than
+#FUXME: Rename ${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} to
+#${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}. Even the latter's longer than
 #I'd like, but at least it's not *OBSCENELY* long, as the former is. Consider
 #renaming "_modification_time" to "_mtime" everywhere, as well. As with "args",
 #"stdin", etc., "mtime" is a commonly recognized abbreviation. We just *CAN'T*
@@ -521,7 +521,7 @@ digest_zeshy
 # ....................{ ALIASES                            }....................
 # Define aliases subsequently expanded by Zeshy's user configuration files,
 # defined here rather than in "config" to avoid excessive global variables.
-# (Namely, a new global boolean ${ZESHY_DOT_DIGEST_FILE_IS_OUTDATED} would be
+# (Namely, a new global boolean ${ZESHY_USER_DIGEST_FILE_IS_OUTDATED} would be
 # required for tracking such state.)
 
 #ZESHY_FUNCTION_DOCUMENTATION+='
@@ -598,14 +598,14 @@ digest_zeshy
 
     # If true, recompile Zeshy's user digest file. If already set, inherit such
     # variable's value from the caller (e.g., component "main").
-#   local ZESHY_DOT_DIGEST_FILE_IS_COMPILING="${ZESHY_DOT_DIGEST_FILE_IS_COMPILING-}"
+#   local ZESHY_USER_DIGEST_FILE_IS_COMPILING="${ZESHY_USER_DIGEST_FILE_IS_COMPILING-}"
 
     # If Zeshy's user digest file is outdated, record such fact.
 #   is_zeshy_digest_outdated &&
-#       ZESHY_DOT_DIGEST_FILE_IS_COMPILING=${ZESHY_BOOLEAN_TRUE}
+#       ZESHY_USER_DIGEST_FILE_IS_COMPILING=${ZESHY_BOOLEAN_TRUE}
 
     # If compiling such file, prepare for such compilation.
-#   [[ -n "${ZESHY_DOT_DIGEST_FILE_IS_COMPILING}" ]] &&
+#   [[ -n "${ZESHY_USER_DIGEST_FILE_IS_COMPILING}" ]] &&
 
 #FUXME: This isn't right. *sigh* We need to do this *BEFORE* sourcing
 #configuration files, which call documentation methods. Unfortunately, that
@@ -672,7 +672,7 @@ digest_zeshy
 #Phew! That's quite a lot of requisite changes, but... well, we'll be
 #demonstrably better for each one.
     # If true, Zeshy''s user digest file is outdated. Defaults to false.
-#   local ZESHY_DOT_DIGEST_FILE_IS_OUTDATED=${ZESHY_BOOLEAN_FALSE}
+#   local ZESHY_USER_DIGEST_FILE_IS_OUTDATED=${ZESHY_BOOLEAN_FALSE}
 
 #FUXME: Third, is_zeshy_digest_outdated() needs to recursively depend on the
 #newest config file. Make it so, aye!
@@ -709,7 +709,7 @@ digest_zeshy
 #recompiling such functions into the Zeshy digest file for such user.
 
     # If true, Zeshy''s user digest file was outdated at Zeshy startup. See
-#   boolean ZESHY_DOT_DIGEST_FILE_IS_OUTDATED=${ZESHY_BOOLEAN_TRUE}
+#   boolean ZESHY_USER_DIGEST_FILE_IS_OUTDATED=${ZESHY_BOOLEAN_TRUE}
 
     # Unless Zeshy's user digest file is outdated, immediately return.
 #   is_zeshy_digest_outdated || return 0
@@ -726,13 +726,13 @@ digest_zeshy
         #  document_alias() or document_function() behave that way.
         #* It doesn''t really gain us anything... except brevity. *ALOT* of
         #  brevity. Hmm.
-#set_global_documentation ZESHY_DOT_DIGEST_FILE_IS_OUTDATED '
-#boolean ZESHY_DOT_DIGEST_FILE_IS_OUTDATED
+#set_global_documentation ZESHY_USER_DIGEST_FILE_IS_OUTDATED '
+#boolean ZESHY_USER_DIGEST_FILE_IS_OUTDATED
 #
 #If true, Zeshy''s user digest file was outdated at Zeshy startup. See
 #is_zeshy_digest_outdated() for further details.
 #'
-#export ZESHY_DOT_DIGEST_FILE_IS_OUTDATED=${ZESHY_BOOLEAN_FALSE}
+#export ZESHY_USER_DIGEST_FILE_IS_OUTDATED=${ZESHY_BOOLEAN_FALSE}
 
 #document_function '
 #void autoload_zeshy(void)
@@ -747,7 +747,7 @@ digest_zeshy
 
 #Render all Zeshy functions applicable to the current user autoloadable after
 #recompiling such functions into the Zeshy digest file for such user, setting
-#the modification time of such file to global ${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}
+#the modification time of such file to global ${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}
 
 #FUXME: This could be a nice opportunity to truncate "main" a bit. I'd
 #specifically like to see get_script_name() shifted into "shell/shell" and
@@ -781,27 +781,27 @@ digest_zeshy
         # below with no arguments results in an undecipherable error resembling
         # "source: not enough arguments".
 #       list user_config_filenames
-#       user_config_filenames=( "${ZESHY_DOT_CONFIG_DIR}/"* )
+#       user_config_filenames=( "${ZESHY_USER_CONFIG_DIR}/"* )
 #       (( #user_config_filenames )) or
-#           die "configuration dir \"${ZESHY_DOT_CONFIG_DIR}\" empty"
+#           die "configuration dir \"${ZESHY_USER_CONFIG_DIR}\" empty"
 
         # Otherwise, source the current user's Zeshy configuration files.
 #       source -- "${user_config_filenames[@]}"
 #   fi
 
-#   if [[ -d "${ZESHY_DOT_CONFIG_DIR}" ]]; then
+#   if [[ -d "${ZESHY_USER_CONFIG_DIR}" ]]; then
 #   source -- "${user_config_filenames[@]}"
 #       list zeshy_user_config_dir_if_nonempty
-#       zeshy_user_config_dir_if_nonempty=( "${ZESHY_DOT_CONFIG_DIR}"(/F) )
+#       zeshy_user_config_dir_if_nonempty=( "${ZESHY_USER_CONFIG_DIR}"(/F) )
 #       (( #zeshy_user_config_dir_if_nonempty )) or
-#           die "zeshy configuration dir \"${ZESHY_DOT_CONFIG_DIR}\" empty"
+#           die "zeshy configuration dir \"${ZESHY_USER_CONFIG_DIR}\" empty"
 
         #FUXME: O.K.; the dir could exist but have no files, in which case
         #source() spits out an error. Test this and die ourselves, since this
         #should never happen here! Test this here to avoid race conditions, in
         #case such files have been deleted since the similar test above.
-#       source "${ZESHY_DOT_CONFIG_DIR}/"*
-    #FUXME: Is ${ZESHY_DOT_CONFIG_DIR} guaranteed to exist at this point? If
+#       source "${ZESHY_USER_CONFIG_DIR}/"*
+    #FUXME: Is ${ZESHY_USER_CONFIG_DIR} guaranteed to exist at this point? If
     #not, returning true if such directory does not exist also seems sane.
 
     # ~~~~~~~~~~~~~~~~< ZSH                                >~~~~~~~~~~~~~~~~~~~~
@@ -810,10 +810,10 @@ digest_zeshy
 #       is -d '/bin'     si and digest_dependent_mtimes+=$(zstat +mtime '/bin')
 #       is -d '/usr/bin' si and digest_dependent_mtimes+=$(zstat +mtime '/usr/bin')
 
-#   is -f "${ZESHY_DOT_CONFIG_FILE}" si and
-#       digest_dependent_mtimes+=$(zstat +mtime "${ZESHY_DOT_CONFIG_FILE}")
-#        is -f "${ZESHY_DOT_DIGEST_FILE}" si and
-#        (( newest_mtime == $(zstat +mtime "${ZESHY_DOT_DIGEST_FILE}") )); then
+#   is -f "${ZESHY_USER_CONFIG_FILE}" si and
+#       digest_dependent_mtimes+=$(zstat +mtime "${ZESHY_USER_CONFIG_FILE}")
+#        is -f "${ZESHY_USER_DIGEST_FILE}" si and
+#        (( newest_mtime == $(zstat +mtime "${ZESHY_USER_DIGEST_FILE}") )); then
 #to synchronize function definitions
     # with current system and user state
         # Find the maximum of this and the prior modification time.
@@ -849,8 +849,8 @@ digest_zeshy
     # modification time, recompile this file to synchronize compiled function
     # definitions with newer Zeshy changes.
 #   integer\
-#         zeshy_mtime=$(zstat +mtime "${ZESHY_DOT_CONFIG_DIR}")\
-#         zeshy_mtime=$(zstat +mtime "${ZESHY_DOT_CONFIG_FILE}")\
+#         zeshy_mtime=$(zstat +mtime "${ZESHY_USER_CONFIG_DIR}")\
+#         zeshy_mtime=$(zstat +mtime "${ZESHY_USER_CONFIG_FILE}")\
 #           bin_mtime=$(zstat +mtime '/bin')\
 #       usr_bin_mtime=$(zstat +mtime '/usr/bin')
 #   ((     bin_mtime > zeshy_mtime )) and zeshy_mtime="${bin_mtime}"
