Began help usage generalization.
So... sleepy. So very sleeeeepy.

diff --git a/src/digest b/src/digest
--- a/src/digest
+++ b/src/digest
@@ -103,7 +103,7 @@ function is_zeshy_digest_outdated() {
         # required by this function's definition to the current time. This
         # guarantees the modification time for zeshy's user digest file will be
         # coerced to the current time.
-        ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME="$(date +'%s')"
+        ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME="$(command date +'%s')"
         return 0
     }
 
@@ -177,8 +177,9 @@ function is_zeshy_digest_outdated() {
         "${ZESHY_DIGEST_DEPENDENCY_PATHS[@]}"
     ) {
 #       print "adding mtime for dependency \"${dependency_pathname}\"..."
-        [[ -e "${dependency_pathname}" ]] &&
+        if [[ -e "${dependency_pathname}" ]] {
             zeshy_dependency_mtimes+="$(zstat +mtime "${dependency_pathname}")"
+        }
     }
 
     #FIXME: Interestingly, GNU-specific external command "du" provides option
@@ -204,16 +205,16 @@ function is_zeshy_digest_outdated() {
         zeshy_dependency_mtimes+="$(zstat +mtime "${ZESHY_USER_CONFIG_DIR}"/**/*(om[1]))"
     }
 
-    # If the current user is a zeshy developer, obtain the last modification
+    # If the current user requests , obtain the last modification
     # time of the zeshy codebase by sorting the set of all last modification
     # times of all files and directories in this codebase and selecting the
-    # largest such time. This is at best an O(n*lg(n)) operation, and hence
-    # confined to developers. Dismantled, this is:
+    # largest such time. This is at best an O(n*lg(n)) operation and hence
+    # typically confined to developers. Dismantled, this is:
     #
     # * "${...}"/**/*, all files and directories of this codebase.
     # * "om", sorting such files and directories by descending mtime.
     # * "[1]", the first and hence newest such file or directory.
-    if [[ -n "${ZESHY_USER_DIGEST_FILE_IS_DEPENDENT_ON_ZESHY_HOME-}" ]] {
+    if (( ${+ZESHY_USER_DIGEST_FILE_IS_DEPENDENT_ON_ZESHY_HOME} )) {
 #       print "adding zeshy codebase \"${ZESHY_HOME}\" as a digest dependency..."
         zeshy_dependency_mtimes+="$(zstat +mtime "${ZESHY_HOME}"/**/*(om[1]))"
     }
@@ -228,8 +229,8 @@ function is_zeshy_digest_outdated() {
     # If the caller failed to declare such integer, do so locally. Ideally, the
     # caller declares such integer to subsequently set such file's modification
     # time using such integer. See digest_zeshy_compile() for further details.
-    [[ ${+ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} -eq 1 &&
-       "${(t)ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}" == 'integer'* ]] || {
+    if ! [[ ${+ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} -eq 1 &&
+         "${(t)ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}" == 'integer'* ]] {
 #       print 'localizing ${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}...'
         local -i ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME
     }
@@ -255,7 +256,7 @@ void digest_zeshy(void)
 
 If `zeshy`\''s user digest file is *outdated* (i.e., older than such file''s
 newest dependency), recompile such file. In either case, source `zeshy`\''s user
-configuration files and autoload all functions defined by such digest.
+configuration files and autoload functions such digest defines.
 '
 function digest_zeshy() {
     # Validate sanity. Do *NOT* return silently if ignoring zeshy's user
@@ -266,7 +267,7 @@ function digest_zeshy() {
     # If ignoring zeshy's user directory, manually source all applicable zeshy
     # scripts and hence functions without autoloading zeshy's user digest file.
     [[ -n "${ZESHY_DOT_DIR}" ]] || {
-        digest_zeshy_without_dot_dir
+        digest_zeshy_sans_dot_dir
         return 0
     }
 
@@ -280,14 +281,13 @@ function digest_zeshy() {
     # such file regardless of whether it's outdated or not, compile all zeshy
     # functions applicable to the current user into such digest and render such
     # functions autoloadable. See "main" for declaration of the latter
-    # condition, "${ZESHY_USER_DIGEST_FILE_IS_COMPILING}".
+    # condition, ${ZESHY_USER_DIGEST_FILE_IS_INDEPENDENT}.
 #   print "detecting \"${ZESHY_USER_DIGEST_FILE}\"..."
     if { is_zeshy_digest_outdated ||
-        [[ -n "${ZESHY_USER_DIGEST_FILE_IS_COMPILING-}" ]] } {
+        (( ${+ZESHY_USER_DIGEST_FILE_IS_INDEPENDENT} )) } {
         digest_zeshy_compile
-    # Otherwise, attempt to autoload the previously compiled digest for the
-    # current user. If such autoload fails, (re)compile such digest and try
-    # again.
+    # Else, attempt to autoload the previously compiled digest for the current
+    # user. If this fails, (re)compile such digest and try again.
     } else {
         autoload -w -- "${ZESHY_USER_DIGEST_FILE}" || digest_zeshy_compile
 #       print "autoloading \"${ZESHY_USER_DIGEST_FILE}\"..."
@@ -299,12 +299,12 @@ function digest_zeshy() {
 }
 
 ZESHY_CORE_HELP_FUNCTIONS+='
-void digest_zeshy_without_dot_dir(void)
+void digest_zeshy_sans_dot_dir(void)
 
 Source all `zeshy` scripts and hence functions applicable to the current user
 without reading to or writing from such user''s `zeshy` dot directory.
 '
-function digest_zeshy_without_dot_dir() {
+function digest_zeshy_sans_dot_dir() {
     # Validate sanity.
     (( # == 0 )) || die 'expected no arguments'
 
@@ -331,7 +331,7 @@ function digest_zeshy_compile() {
 
     # If debugging zeshy, print modification times for zeshy's user digest file
     # and the newest path such file depends upon.
-    is_zeshy_verbose_and {
+    if_zeshy_debug {
         [[ -f "${ZESHY_USER_DIGEST_FILE}" ]] &&
             print "zeshy: digest mtime:                   $(zstat +mtime "${ZESHY_USER_DIGEST_FILE}")"
             print "zeshy: digest newest dependency mtime: ${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}"
@@ -342,7 +342,7 @@ function digest_zeshy_compile() {
 
     # Set the modification time of such digest to that of the newest
     # modification time to avoid recompilation on the next zeshy run.
-    touch -m\
+    command touch -m\
         --date=@${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}\
         -- "${ZESHY_USER_DIGEST_FILE}"
 
@@ -356,6 +356,9 @@ function digest_zeshy_compile() {
 digest_zeshy
 
 # --------------------( WASTELANDS                         )--------------------
+#   [[    ${+ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} -eq 1 &&
+#      "${(t)ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}" == 'integer'* ]] || {
+
 #FUXME: There exists a subtle race condition that will (probably) become
 #increasingly less subtle as zeshy development proceeds. If a second zeshy shell
 #is run while the first is still compiling its digest file, the second could
@@ -649,7 +652,7 @@ digest_zeshy
 #  digest is outdated *BEFORE* sourcing configuration files in order to define
 #  documentation aliases properly. (So, shift us back! Sorry, sorry.)
 #* Change the test in is_zeshy_digest_outdated() from expanding to
-#  is_zeshy_verbose_and() to... well, what? How about this:
+#  if_zeshy_debug() to... well, what? How about this:
 #  * Check whether or not the parent directory of ${ZESHY_HOME} contains a
 #    ".git" directory; if it does, consider that equivalent to "debugging."
 #FUXME: Nope! Nix all that. This is actually the way to go. So how do we enable
@@ -696,7 +699,7 @@ digest_zeshy
 #  option ${ZESHY_IS_DEBUG}. The latter turns out to have been a *REALLY*
 #  bad idea that's just not needed anymore and couldn't really be reliably
 #  supported in any case.
-#* Rename is_zeshy_verbose_and<> to is_zeshy_verbose_and<>.
+#* Rename if_zeshy_debug<> to if_zeshy_debug<>.
 #Phew! That's quite a lot of requisite changes, but... well, we'll be
 #demonstrably better for each one.
     # If true, Zeshy''s user digest file is outdated. Defaults to false.
