Substantially improved Zeshy startup.
Corrected numerous major but subtly invisible regressions between
"bin/zeshy", "src/.zshrc", and "src/main". Corrected numerous
configuration file and terminal color output-related regressions.
Added command-line option "--compile-digest" for forcing digest
compilation.

diff --git a/src/digest b/src/digest
--- a/src/digest
+++ b/src/digest
@@ -180,7 +180,7 @@ function is_zeshy_digest_outdated() {
     # * "${...}"/**/*, all files and directories of this codebase.
     # * "om", sorting such files and directories by descending mtime.
     # * "[1]", the first and hence newest such file or directory.
-    [[ -n "${ZESHY_HOME_IS_DIGEST_FILE_DEPENDENCY}" ]] && {
+    [[ -n "${ZESHY_DOT_DIGEST_FILE_IS_DEPENDENT_ON_ZESHY_HOME}" ]] && {
 #       say "adding Zeshy codebase \"${ZESHY_HOME}\" as a digest dependency..."
         zeshy_dependency_mtimes+="$(zstat +mtime "${ZESHY_HOME}"/**/*(om[1]))"
     }
@@ -237,25 +237,21 @@ function digest_zeshy() {
         return 0
     }
 
-    # If true, Zeshy''s user digest file is outdated. Defaults to false.
-    local ZESHY_DOT_DIGEST_FILE_IS_OUTDATED=${ZESHY_BOOLEAN_FALSE}
-
     # If such digest is outdated, this is the modification time of the newest
-    # path such digest depends on; else 0.
+    # path such digest depends on; else 0. While this function itself does not
+    # refer to this variable, explicitly declare this variable here to provide
+    # shared access to this variable by functions this function calls. (Subtle!)
     local -i ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME
 
-    # If Zeshy's user digest file is outdated, record such fact and prepare for
-    # subsequent compilation.
-    is_zeshy_digest_outdated && {
-        ZESHY_DOT_DIGEST_FILE_IS_OUTDATED=${ZESHY_BOOLEAN_TRUE}
-        digest_zeshy_setup
-    }
-
-    # If such digest is outdated, compile all Zeshy functions applicable to the
-    # current user into such digest and render such functions autoloadable.
+    # If Zeshy's user digest file is outdated or the caller demands recompiling
+    # such file regardless of whether it's outdated or not, compile all Zeshy
+    # functions applicable to the current user into such digest and render such
+    # functions autoloadable. See "main" for declaration of the latter
+    # condition, "${ZESHY_DOT_DIGEST_FILE_IS_COMPILING}".
 #   say "detecting \"${ZESHY_DOT_DIGEST_FILE}\"..."
-    if [[ -n "${ZESHY_DOT_DIGEST_FILE_IS_OUTDATED}" ]]
-    then digest_zeshy_compile
+    if is_zeshy_digest_outdated ||
+        [[ -n "${ZESHY_DOT_DIGEST_FILE_IS_COMPILING-}" ]]; then
+        digest_zeshy_compile
     # Otherwise, attempt to autoload the previously compiled digest for the
     # current user. If such autoload fails, (re)compile such digest and try
     # again.
@@ -285,81 +281,45 @@ function digest_zeshy_without_dot_dir() {
     unset -- HISTFILE
 }
 
-#FIXME: This isn't right. *sigh* We need to do this *BEFORE* sourcing
-#configuration files, which call documentation methods. Unfortunately, that
-#breeds a circularity conflict: configuration sources must be sourced *BEFORE*
-#calling is_zeshy_digest_outdated(). The solution is clear: retain the new
-#calling order, which is demonstrably superior; to solve the documentation
-#issue, simply define... Wait. That's not quite it. O.K.; here goes: the check
-#in is_zeshy_digest_outdated shouldn't depend on configuration file values. If
-#you think about it, this makes both inherent sense and improves the robustness
-#of the whole process (by eliminating yet-another-obscure-dependency). So:
-#
-#* Revert to the prior calling order. We *NEED* to determine whether or not the
-#  digest is outdated *BEFORE* sourcing configuration files in order to define
-#  documentation aliases properly. (So, shift us back! Sorry, sorry.)
-#* Change the test in is_zeshy_digest_outdated() from expanding to
-#  is_zeshy_verbose_and() to... well, what? How about this:
-#  * Check whether or not the parent directory of ${ZESHY_HOME} contains a
-#    ".git" directory; if it does, consider that equivalent to "debugging."
-#FIXME: Nope! Nix all that. This is actually the way to go. So how do we enable
-#documentation in config files then? Pretty simple, and, if you consider it, the
-#only reasonable way it can be done. Consider this: after upgrading Zeshy or
-#perhaps simply deleting existing config files, sourcing such files only once
-#prior to copying such files back during digest recompilation guarantees that
-#Zeshy will *NEVER* document globals in such files. In other words,
-#the way we were doing it could *NEVER* have reasonably worked. So what to do?
-#Simple: just source all config files *AT ONCE* by re-calling
-#source_zeshy_configuration() immediately *AFTER* compiling Zeshy's digest but
-#*BEFORE* calling make_zeshy() (for obvious reasons). The easiest way to
-#accomplish this, of course, is simply to prepend "source_zeshy_configuration"
-#to the beginning of global list ${ZESHY_COMMANDS_TO_MAKE_ZESHY}. Brilliant --
-#but should be voluminously documented, of course. It's *INCREDIBLY* subtle.
-#Not sure how I ever even caught on to all this...
-#FIXME: This suggests a few optimizations:
-#
-#* There's actually *NO* point to sourcing configuration files before
-#  recompiling the digest aside from ensuring ${ZESHY_IS_DEBUGGING} is set and
-#  debug messages are printed during such recompilation. To put it bluntly,
-#  there *MUST* be a simpler, faster way of ensuring the same functionality.
-#  Again, the simplest way is probably testing *ONCE* up-front for a sibling
-#  directory ".git" of the parent of "${ZESHY_HOME}"; it's a fast test: cache it
-#  *ONLY* if recompiling Zeshy and we move on. (If not recompiling Zeshy, we
-#  shouldn't need such shennanigans.)
-#* Given that, *STOP* sourcing configuration files as the first action performed
-#  on Zeshy startup. Instead:
-#  * If such digest is outdated, prepend "source_zeshy_configuration" to
-#    ${ZESHY_COMMANDS_TO_MAKE_ZESHY} as discussed above.
-#  * Else, call source_zeshy_configuration() manually. Hmm. We *could* simply
-#    prepend "source_zeshy_configuration" to ${ZESHY_COMMANDS_TO_STARTUP_ZESHY}.
-#    That has the sole downside of causing such configuration to be sourced twice
-#    when recompiling such digest. On the other hand, it's probably more readable.
-#    *shrug* It doesn't particularly matter which we adopt, honestly.
-#* Rename "setup" to "config". (See such component for details). That implies that
-#  we call "source_zeshy_component config" rather than "source_zeshy_configuration"
-#  above, in which case I don't really see the benefit to prepending such command
-#  to arrays. Just call "source_zeshy_component config" as is exactly where we
-#  require it.
-#* Shift source_zeshy_component() to "always/zeshy/zeshy". (Extremely silly to
-#  have such febrile functionality at the top-level, wasn't it?)
-#* Add new command-line option "-v, --verbose" and remove existing configuration
-#  option ${ZESHY_IS_DEBUGGING}. The latter turns out to have been a *REALLY*
-#  bad idea that's just not needed anymore and couldn't really be reliably
-#  supported in any case.
-#* Rename is_zeshy_verbose_and<> to is_zeshy_verbose_and<>.
-#* Replace "[[ -n "${ZESHY_DOT_DIR}" ]] ||" with a similar alias
-#  is_zeshy_dot_dir_or<>.
-#
-#Phew! That's quite a lot of requisite changes, but... well, we'll be
-#demonstrably better for each one.
+set_function_documentation digest_zeshy_compile '
+void digest_zeshy_compile(void)
 
-set_function_documentation digest_zeshy_setup '
+Compile Zeshy''s user digest file, coerce the modification time of such file to
+the modification time of the newest path such file depends on, and autoload all
+functions compiled into such file.
+'
+function digest_zeshy_compile() {
+    # Validate sanity. Unless the modification time of the newest path Zeshy's
+    # user digest file depends on was previously set, throw an exception.
+    (( # == 0 )) || die 'expected no arguments'
+    (( ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME )) ||
+        die '"ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME" not set'
+
+    # Prepare for such compilation.
+    digest_zeshy_compile_setup
+
+    # Source all applicable Zeshy scripts and hence functions.
+    source -- "${ZESHY_HOME}/compile"
+
+    # Set the modification time of such digest to that of the newest
+    # modification time to avoid recompilation on the next Zeshy run.
+    touch -m\
+        --date=@${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME}\
+        -- "${ZESHY_DOT_DIGEST_FILE}"
+
+    # Declare all functions defined by such digest to be autoloadable.
+#   say "autoloading \"${ZESHY_DOT_DIGEST_FILE}\"..."
+    autoload -w -- "${ZESHY_DOT_DIGEST_FILE}" ||
+        die "\"${ZESHY_DOT_DIGEST_FILE}\" cannot be compiled"
+}
+
+set_function_documentation digest_zeshy_compile_setup '
 void digest_zeshy_setup(void)
 
 Assuming Zeshy''s user digest file to be outdated, implement aliases and
 functions required only for compiling an outdated digest file.
 '
-function digest_zeshy_setup() {
+function digest_zeshy_compile_setup() {
     # Validate sanity.
     (( # == 0 )) || die 'expected no arguments'
 
@@ -513,35 +473,6 @@ Map variable type to the command prefix exporting globals of such type.
     } <<<'
 }
 
-set_function_documentation digest_zeshy_compile '
-void digest_zeshy_compile(void)
-
-Compile Zeshy''s user digest file, coerce the modification time of such file to
-the modification time of the newest path such file depends on, and autoload all
-functions compiled into such file.
-'
-function digest_zeshy_compile() {
-    # Validate sanity. Unless the modification time of the newest path Zeshy's
-    # user digest file depends on was previously set, throw an exception.
-    (( # == 0 )) || die 'expected no arguments'
-    (( ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME )) ||
-        die '"ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME" not set'
-
-    # Source all applicable Zeshy scripts and hence functions.
-    source -- "${ZESHY_HOME}/compile"
-
-    # Set the modification time of such digest to that of the newest
-    # modification time to avoid recompilation on the next Zeshy run.
-    touch -m\
-        --date=@${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME}\
-        -- "${ZESHY_DOT_DIGEST_FILE}"
-
-    # Declare all functions defined by such digest to be autoloadable.
-#   say "autoloading \"${ZESHY_DOT_DIGEST_FILE}\"..."
-    autoload -w -- "${ZESHY_DOT_DIGEST_FILE}" ||
-        die "\"${ZESHY_DOT_DIGEST_FILE}\" cannot be compiled"
-}
-
 # ....................{ MAIN                               }....................
 digest_zeshy
 
@@ -554,6 +485,95 @@ unfunction\
     set_global_documentation
 
 # --------------------( WASTELANDS                         )--------------------
+#FUXME: This file needs a bit of work. First, *NO* alias defined below should
+#induce a fatal error at Zeshy startup, even if the corresponding command does
+#not exist on the current system: print a warning and move. Currently, my whole
+#setup is dying because "lsmod" no longer exists due to the "kmod" switch; ugh.
+#FUXME: Second, I suddenly conceived this morning of why startup has become so
+#hideously slow. We're actually reparsing *ALL* such aliases on each Zeshy
+#startup. This is, to put it bluntly, insanity. We need instead to shift the
+#current startup function iteratively defining such aliases into make_zeshy(),
+#thus confining such definition to digest recompilation. Ideally, this should
+#see a significant improvement in runtime efficiency.
+
+    # If true, recompile Zeshy's user digest file. If already set, inherit such
+    # variable's value from the caller (e.g., component "main").
+#   local ZESHY_DOT_DIGEST_FILE_IS_COMPILING="${ZESHY_DOT_DIGEST_FILE_IS_COMPILING-}"
+
+    # If Zeshy's user digest file is outdated, record such fact.
+#   is_zeshy_digest_outdated &&
+#       ZESHY_DOT_DIGEST_FILE_IS_COMPILING=${ZESHY_BOOLEAN_TRUE}
+
+    # If compiling such file, prepare for such compilation.
+#   [[ -n "${ZESHY_DOT_DIGEST_FILE_IS_COMPILING}" ]] &&
+
+#FUXME: This isn't right. *sigh* We need to do this *BEFORE* sourcing
+#configuration files, which call documentation methods. Unfortunately, that
+#breeds a circularity conflict: configuration sources must be sourced *BEFORE*
+#calling is_zeshy_digest_outdated(). The solution is clear: retain the new
+#calling order, which is demonstrably superior; to solve the documentation
+#issue, simply define... Wait. That's not quite it. O.K.; here goes: the check
+#in is_zeshy_digest_outdated shouldn't depend on configuration file values. If
+#you think about it, this makes both inherent sense and improves the robustness
+#of the whole process (by eliminating yet-another-obscure-dependency). So:
+#
+#* Revert to the prior calling order. We *NEED* to determine whether or not the
+#  digest is outdated *BEFORE* sourcing configuration files in order to define
+#  documentation aliases properly. (So, shift us back! Sorry, sorry.)
+#* Change the test in is_zeshy_digest_outdated() from expanding to
+#  is_zeshy_verbose_and() to... well, what? How about this:
+#  * Check whether or not the parent directory of ${ZESHY_HOME} contains a
+#    ".git" directory; if it does, consider that equivalent to "debugging."
+#FUXME: Nope! Nix all that. This is actually the way to go. So how do we enable
+#documentation in config files then? Pretty simple, and, if you consider it, the
+#only reasonable way it can be done. Consider this: after upgrading Zeshy or
+#perhaps simply deleting existing config files, sourcing such files only once
+#prior to copying such files back during digest recompilation guarantees that
+#Zeshy will *NEVER* document globals in such files. In other words,
+#the way we were doing it could *NEVER* have reasonably worked. So what to do?
+#Simple: just source all config files *AT ONCE* by re-calling
+#source_zeshy_configuration() immediately *AFTER* compiling Zeshy's digest but
+#*BEFORE* calling make_zeshy() (for obvious reasons). The easiest way to
+#accomplish this, of course, is simply to prepend "source_zeshy_configuration"
+#to the beginning of global list ${ZESHY_COMMANDS_TO_MAKE_ZESHY}. Brilliant --
+#but should be voluminously documented, of course. It's *INCREDIBLY* subtle.
+#Not sure how I ever even caught on to all this...
+#FUXME: This suggests a few optimizations:
+#
+#* There's actually *NO* point to sourcing configuration files before
+#  recompiling the digest aside from ensuring ${ZESHY_IS_DEBUGGING} is set and
+#  debug messages are printed during such recompilation. To put it bluntly,
+#  there *MUST* be a simpler, faster way of ensuring the same functionality.
+#  Again, the simplest way is probably testing *ONCE* up-front for a sibling
+#  directory ".git" of the parent of "${ZESHY_HOME}"; it's a fast test: cache it
+#  *ONLY* if recompiling Zeshy and we move on. (If not recompiling Zeshy, we
+#  shouldn't need such shennanigans.)
+#* Given that, *STOP* sourcing configuration files as the first action performed
+#  on Zeshy startup. Instead:
+#  * If such digest is outdated, prepend "source_zeshy_configuration" to
+#    ${ZESHY_COMMANDS_TO_MAKE_ZESHY} as discussed above.
+#  * Else, call source_zeshy_configuration() manually. Hmm. We *could* simply
+#    prepend "source_zeshy_configuration" to ${ZESHY_COMMANDS_TO_STARTUP_ZESHY}.
+#    That has the sole downside of causing such configuration to be sourced twice
+#    when recompiling such digest. On the other hand, it's probably more readable.
+#    *shrug* It doesn't particularly matter which we adopt, honestly.
+#* Rename "setup" to "config". (See such component for details). That implies that
+#  we call "source_zeshy_component config" rather than "source_zeshy_configuration"
+#  above, in which case I don't really see the benefit to prepending such command
+#  to arrays. Just call "source_zeshy_component config" as is exactly where we
+#  require it.
+#* Shift source_zeshy_component() to "always/zeshy/zeshy". (Extremely silly to
+#  have such febrile functionality at the top-level, wasn't it?)
+#* Add new command-line option "-v, --verbose" and remove existing configuration
+#  option ${ZESHY_IS_DEBUGGING}. The latter turns out to have been a *REALLY*
+#  bad idea that's just not needed anymore and couldn't really be reliably
+#  supported in any case.
+#* Rename is_zeshy_verbose_and<> to is_zeshy_verbose_and<>.
+#Phew! That's quite a lot of requisite changes, but... well, we'll be
+#demonstrably better for each one.
+    # If true, Zeshy''s user digest file is outdated. Defaults to false.
+#   local ZESHY_DOT_DIGEST_FILE_IS_OUTDATED=${ZESHY_BOOLEAN_FALSE}
+
 #FUXME: Third, is_zeshy_digest_outdated() needs to recursively depend on the
 #newest config file. Make it so, aye!
 
