Corrected numerous file descriptor regressions.
Astonishingly, print_whitespace_if_needed() still remains felonious.
We've documented but have yet to implement the requisite fix, which
already seems needlessly burdensome. *sigh*

diff --git a/src/digest b/src/digest
--- a/src/digest
+++ b/src/digest
@@ -39,17 +39,41 @@ function add_zeshy_digest_dependency_path() {
 }
 
 # ....................{ TESTERS                            }....................
+#FIXME: The resolution of ${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}
+#should be improved from seconds to nanoseconds on systems supporting the latter
+#(e.g., BSD, Linux). Happily, this can be efficiently obtained as a float from
+#"date" with the command:
+#
+#   >>> date +'%s.%N'
+#   1369342075.472940831
+#
+#Naturally, this is sufficiently useful to be generalized into a new function
+#get_time_second_nanosecond() (whose name complies with "os/time" nomenclature).
+#FIXME: Retrieving file modification time denominated in nanoseconds isn't quite
+#as simple, unfortunately. We have an algorithm for doing so at "path/time",
+#which we'll need to move here. Both implementations are (probably) Linux-
+#specific. So, we'll also need to move the is_pathable_gnu() function here. I
+#know, I know; but it's really quite unavoidable.
+#FIXME: *UGH*. We *ALREADY* have the current time as a float in global
+#${ZESHY_STARTUP_TIME_SECONDS}. Hence, replace our current calling of "date"
+#below with simple expansion of such global.
+#FIXME: We already implement get_time() to return fractional seconds, so no
+#additional work needed there.
+#FIXME: We will still need to shift functionality here for getting fractional
+#file time. However, since zsh will (eventually) obsolete such functionality by
+#improving zstat(), this isn't really a significant long-term concern.
 #FIXME: Update documentation, now significantly outdated. (The irony.)
+
 ZESHY_CORE_HELP_FUNCTIONS+='
-boolean is_zeshy_digest_outdated(void)
+[status: boolean] is_zeshy_digest_outdated(void)
 
-Return true if Zeshy''s user digest file is outdated and requires recompilation.
-This is the case when such file either does not exist or does but is older than
-the newest of:
+Return success if `zeshy`\''s user digest file is outdated and requires
+recompilation. This is the case when such file either does not exist or does but
+is older than the newest of:
 
-* The main user-specific Zeshy configuration file. This file contains theme
+* The main user-specific `zeshy` configuration file. This file contains theme
   settings, which when edited require recompiling theme autoloads.
-* The main system-wide command directories (e.g., "/bin", "/usr/bin").
+* The main system-wide command directories (e.g., `/bin`, `/usr/bin`).
   Installing or uninstalling commands requires recompiling command autoloads.
 
 For convenience, set integer global
@@ -60,10 +84,10 @@ function is_zeshy_digest_outdated() {
     # Validate sanity.
     (( # == 0 )) || die 'expected no arguments'
 
-    #FIXME: Add support for Zeshy upgrading: namely, if upgrading Zeshy,
+    #FIXME: Add support for zeshy upgrading: namely, if upgrading zeshy,
     #immediately return 0 (i.e., true).
 
-    # Unless loading Zeshy's user directory *AND* Zeshy's user digest file and
+    # Unless loading zeshy's user directory *AND* zeshy's user digest file and
     # configuration directory both exist *AND* the latter contains at least one
     # directory or file (i.e., is non-empty), return such digest to be outdated.
     [[ -n "${ZESHY_DOT_DIR}" &&\
@@ -77,13 +101,13 @@ function is_zeshy_digest_outdated() {
         # Before returning, set global
         # ${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} as
         # required by this function's definition to the current time. This
-        # guarantees the modification time for Zeshy's user digest file will be
+        # guarantees the modification time for zeshy's user digest file will be
         # coerced to the current time.
         ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME="$(date +'%s')"
         return 0
     }
 
-    # Source the file to which Zeshy caches the list of all paths on which such
+    # Source the file to which zeshy caches the list of all paths on which such
     # digest depends, thus defining ${ZESHY_DIGEST_DEPENDENCY_PATHNAMES}.
     source -- "${ZESHY_CACHE_DIGEST_DEPENDENCIES_FILE}"
 
@@ -148,7 +172,7 @@ function is_zeshy_digest_outdated() {
         # All directories on the current user's ${PATH}.
         "${path[@]}"
 
-        # All paths other Zeshy components insist such digest depends on.
+        # All paths other zeshy components insist such digest depends on.
         "${ZESHY_DIGEST_DEPENDENCY_PATHNAMES[@]}"
     ) {
 #       print "adding mtime for dependency \"${dependency_pathname}\"..."
@@ -165,22 +189,22 @@ function is_zeshy_digest_outdated() {
 
     # Append to such list the modification times of the following paths:
     #
-    # * Zeshy's user configuration directory, ensuring digest recompilation on
+    # * zeshy's user configuration directory, ensuring digest recompilation on
     #   addition or deletion of configuration files.
-    # * Zeshy's newest user configuration file, ensuring digest recompilation on
+    # * zeshy's newest user configuration file, ensuring digest recompilation on
     #   changes to such files (e.g., edits to interactive alias names
     #   necessitating redefinition of the functions implementing such aliases).
     #
     # While getting such times is mildly expensive, the alternative cost of
-    # redefining user-configured interactive aliases on each Zeshy startup
+    # redefining user-configured interactive aliases on each zeshy startup
     # outweighs such expense. See discussion below for implementation details.
     [[ -d "${ZESHY_USER_CONFIG_DIR}" ]] && {
         zeshy_dependency_mtimes+="$(zstat +mtime "${ZESHY_USER_CONFIG_DIR}")"
         zeshy_dependency_mtimes+="$(zstat +mtime "${ZESHY_USER_CONFIG_DIR}"/**/*(om[1]))"
     }
 
-    # If the current user is a Zeshy developer, obtain the last modification
-    # time of the Zeshy codebase by sorting the set of all last modification
+    # If the current user is a zeshy developer, obtain the last modification
+    # time of the zeshy codebase by sorting the set of all last modification
     # times of all files and directories in this codebase and selecting the
     # largest such time. This is at best an O(n*lg(n)) operation, and hence
     # confined to developers. Dismantled, this is:
@@ -189,11 +213,11 @@ function is_zeshy_digest_outdated() {
     # * "om", sorting such files and directories by descending mtime.
     # * "[1]", the first and hence newest such file or directory.
     [[ -n "${ZESHY_USER_DIGEST_FILE_IS_DEPENDENT_ON_ZESHY_HOME}" ]] && {
-#       print "adding Zeshy codebase \"${ZESHY_HOME}\" as a digest dependency..."
+#       print "adding zeshy codebase \"${ZESHY_HOME}\" as a digest dependency..."
         zeshy_dependency_mtimes+="$(zstat +mtime "${ZESHY_HOME}"/**/*(om[1]))"
     }
 
-    # The newest modification time of all dependencies of Zeshy's digest.
+    # The newest modification time of all dependencies of zeshy's digest.
     # Technically, sorting such list is technically O(n lg(n)). Assuming a
     # sufficiently small ${PATH}, sorting is nearly O(n). Dismantled, this is:
     #
@@ -210,11 +234,11 @@ function is_zeshy_digest_outdated() {
     }
     ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME="${${(nO@)zeshy_dependency_mtimes}[1]}"
 
-    # The modification time of Zeshy's digest.
+    # The modification time of zeshy's digest.
     integer zeshy_digest_mtime
     zeshy_digest_mtime="$(zstat +mtime "${ZESHY_USER_DIGEST_FILE}")"
 
-    # If Zeshy's digest is older than its newest dependency, signify such digest
+    # If zeshy's digest is older than its newest dependency, signify such digest
     # to be outdated by returning true.
 #   print "mtimes: ${dependency_mtimes[@]}"
 #   print "newest: ${ZESHY_NEWEST_DEPENDENCY_MTIME}"
@@ -228,18 +252,18 @@ function is_zeshy_digest_outdated() {
 ZESHY_CORE_HELP_FUNCTIONS+='
 void digest_zeshy(void)
 
-If Zeshy''s user digest file is outdated (i.e., older than such file''s newest
-dependency), recompile such file. In either case, source Zeshy''s user
+If `zeshy`\''s user digest file is *outdated* (i.e., older than such file''s
+newest dependency), recompile such file. In either case, source `zeshy`\''s user
 configuration files and autoload all functions defined by such digest.
 '
 function digest_zeshy() {
-    # Validate sanity. Do *NOT* return silently if ignoring Zeshy's user
+    # Validate sanity. Do *NOT* return silently if ignoring zeshy's user
     # directory, both as all functions called below already do so and as the
     # logic below defines core globals required in either case.
     (( # == 0 )) || die 'expected no arguments'
 
-    # If ignoring Zeshy's user directory, manually source all applicable Zeshy
-    # scripts and hence functions without autoloading Zeshy's user digest file.
+    # If ignoring zeshy's user directory, manually source all applicable zeshy
+    # scripts and hence functions without autoloading zeshy's user digest file.
     [[ -n "${ZESHY_DOT_DIR}" ]] || {
         digest_zeshy_without_dot_dir
         return 0
@@ -251,21 +275,22 @@ function digest_zeshy() {
     # shared access to this variable by functions this function calls. (Subtle!)
     local -i ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME
 
-    # If Zeshy's user digest file is outdated or the caller demands recompiling
-    # such file regardless of whether it's outdated or not, compile all Zeshy
+    # If zeshy's user digest file is outdated or the caller demands recompiling
+    # such file regardless of whether it's outdated or not, compile all zeshy
     # functions applicable to the current user into such digest and render such
     # functions autoloadable. See "main" for declaration of the latter
     # condition, "${ZESHY_USER_DIGEST_FILE_IS_COMPILING}".
 #   print "detecting \"${ZESHY_USER_DIGEST_FILE}\"..."
-    if is_zeshy_digest_outdated ||
-        [[ -n "${ZESHY_USER_DIGEST_FILE_IS_COMPILING-}" ]]; then
+    if { is_zeshy_digest_outdated ||
+        [[ -n "${ZESHY_USER_DIGEST_FILE_IS_COMPILING-}" ]] } {
         digest_zeshy_compile
     # Otherwise, attempt to autoload the previously compiled digest for the
     # current user. If such autoload fails, (re)compile such digest and try
     # again.
-    else autoload -w -- "${ZESHY_USER_DIGEST_FILE}" || digest_zeshy_compile
+    } else {
+        autoload -w -- "${ZESHY_USER_DIGEST_FILE}" || digest_zeshy_compile
 #       print "autoloading \"${ZESHY_USER_DIGEST_FILE}\"..."
-    fi
+    }
 
     # Prefix the function path with the absolute path to the digest file to
     # ensure zsh searches such file for the definition of such functions first.
@@ -275,8 +300,8 @@ function digest_zeshy() {
 ZESHY_CORE_HELP_FUNCTIONS+='
 void digest_zeshy_without_dot_dir(void)
 
-Source all Zeshy scripts and hence functions applicable to the current user
-without reading to or writing from such user''s Zeshy directory.
+Source all `zeshy` scripts and hence functions applicable to the current user
+without reading to or writing from such user''s `zeshy` dot directory.
 '
 function digest_zeshy_without_dot_dir() {
     # Validate sanity.
@@ -292,18 +317,18 @@ function digest_zeshy_without_dot_dir() {
 ZESHY_CORE_HELP_FUNCTIONS+='
 void digest_zeshy_compile(void)
 
-Compile Zeshy''s user digest file, coerce the modification time of such file to
-the modification time of the newest path such file depends on, and autoload all
-functions compiled into such file.
+Compile `zeshy`\''s user digest file, coerce the modification time of such file
+to the modification time of the newest path such file depends on, and autoload
+all functions compiled into such file.
 '
 function digest_zeshy_compile() {
-    # Validate sanity. Unless the modification time of the newest path Zeshy's
+    # Validate sanity. Unless the modification time of the newest path zeshy's
     # user digest file depends on was previously set, throw an exception.
     (( # == 0 )) || die 'expected no arguments'
-    (( ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME )) ||
+    (( ${+ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME} )) ||
         die '"ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME" not set'
 
-    # If debugging Zeshy, print modification times for Zeshy's user digest file
+    # If debugging zeshy, print modification times for zeshy's user digest file
     # and the newest path such file depends upon.
     is_zeshy_verbose_and {
         [[ -f "${ZESHY_USER_DIGEST_FILE}" ]] &&
@@ -311,11 +336,11 @@ function digest_zeshy_compile() {
             print "zeshy: digest newest dependency mtime: ${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}"
     }
 
-    # Source all applicable Zeshy scripts and hence functions.
+    # Source all applicable zeshy scripts and hence functions.
     source -- "${ZESHY_HOME}/compile"
 
     # Set the modification time of such digest to that of the newest
-    # modification time to avoid recompilation on the next Zeshy run.
+    # modification time to avoid recompilation on the next zeshy run.
     touch -m\
         --date=@${ZESHY_USER_DIGEST_FILE_DEPENDENCY_NEWEST_MTIME}\
         -- "${ZESHY_USER_DIGEST_FILE}"
