Completed ::set_system_globals_os() in @{inspect}.
Ideally, such function should now reliably detect most if not all GNU/Linux
distribution names. Onward, my valiant zsh trenchmen!

diff --git a/src/inspect b/src/inspect
--- a/src/inspect
+++ b/src/inspect
@@ -121,6 +121,21 @@ function ::set_system_globals() {
 }
 
 # ....................{ SETTERS ~ os                       }....................
+# To add support for a new distribution, match such distribution's specific file
+# in the appropriate structures below. Specifically:
+#
+# * If such distribution provides "/etc/lsb-release", discover the value of
+#   canonical key "DISTRIB_ID" in such file. If such value requires munging
+#   (e.g., capitalization), do so explicitly.
+# * Else if such distribution provides "/etc/os-release", discover the value of
+#   canonical key "NAME" in such file. Again, munge such value if required.
+# * In either case, determine if such distribution installs a distribution-
+#   specific file (e.g., "/etc/gentoo-release" for Gentoo). If so, match such
+#   file into both the list and both below.
+#
+# For both maintainability and efficiency, officially discontinued distributions
+# should be removed as soon as possible from all such structures.
+
 # void ::set_system_globals_os(void)
 function ::set_system_globals_os() {
     # Validate sanity.
@@ -180,91 +195,158 @@ function ::set_system_globals_os() {
            [[ -f '/etc/os-release' && "${mapfile[/etc/os-release]}" =~\
             '(?m)^NAME='${pcre_value}'$' ]] {
             ZESHY_LINUX_DISTRO_NAME="${match[1]}"
+
+            # Canonicalize such distribution name. Do *NOT* implicitly
+            # capitalize such name, as numerous distribution names are intended
+            # to be lowercase (e.g., "elementary OS").
+            #
+            # Remove all instances of the current operating system from such
+            # name (e.g., the "Linux" in "Arch Linux ARM", "LinuxMint", and
+            # "Gentoo Linux"), unless such instance is absolutely critical to
+            # the understanding of such name (e.g., the "Linux" in "Linux From
+            # Scratch"). Dismantled, this is:
+            #
+            # * "(i)", matching case-insensitively. Several distributions
+            #   entirely capitalize such name (e.g., "SUSE LINUX").
+            if [[ "${ZESHY_LINUX_DISTRO_NAME}" != 'Linux From Scratch' ]] {
+                ZESHY_LINUX_DISTRO_NAME="${ZESHY_LINUX_DISTRO_NAME//(i)linux}"
+            }
+
+            # Map non-canonical to canonical distribution names. Numerous
+            # distributions set "DISTRIB_ID" in "/etc/lsb-release" to an either
+            # overly specific or ambiguous name, in either case resulting in
+            # related variants of the same distribution being erroneously
+            # treated as different distributions. Correct this.
+            case "${ZESHY_LINUX_DISTRO_NAME}" {
+            # If such name is either "Archarm" or prefixed by "Arch " (e.g.,
+            # "Arch ARM"), reduce such name to simply "Arch".
+            'Arch'('arm'|' '*)) ZESHY_LINUX_DISTRO_NAME='Arch';;
+            # If such name is either "CentOS" or prefixed by "RedHatEnterprise"
+            # (e.g., "RedHatEnterpriseWS", "RedHatEnterpriseServer"), reduce
+            # such name to simply "Red Hat Enterprise".
+            'CentOS'|'RedHatEnterprise'*) ZESHY_LINUX_DISTRO_NAME='Red Hat Enterprise';;
+            # If such name is "elementary", suffix such name by " OS".
+            'elementary') ZESHY_LINUX_DISTRO_NAME='elementary OS';;
+            # If such name is "frugalware", capitalize such name.
+            'frugalware') ZESHY_LINUX_DISTRO_NAME='Frugalware';;
+            # If such name is "openSUSE project", strip the latter word.
+            'openSUSE project') ZESHY_LINUX_DISTRO_NAME='openSUSE';;
+            }
         # Else, iteratively search for a distribution-specific "/etc" file
         # typically implying the current distribution (e.g., if
         # "/etc/DISTRO_SPECS" exists, such distribution is almost certainly
         # Puppy Linux).
         } else {
-            #FIXME: Implement me! And, yes: for our crude purposes here, merely
-            #detecting the existence of the first such file suffices. Yes, this
-            #is basically authoritative at this point, after grepping about a
-            #variety of sources both offline and online. Go, go, go!
+            # There exist two approaches to implementing such search:
+            #
+            # * The simplistic brute-force approach of iteratively searching for
+            #   each such file "one at a time."
+            # * The significantly more efficient approach of globbing for all
+            #   such files "all at once" into a local list. Since such files are
+            #   distribution-specific and hence mutually exclusive, such list
+            #   should contain either:
+            #   * Zero filenames if the current distribution is unrecognized.
+            #   * One filename specific to the current distribution.
+            #
+            # Since globbing for a small finite set of filenames is presumably
+            # efficient *AND* since mapping the globbed filename to the
+            # corresponding distribution name only requires a constant-time
+            # map lookup, such approach is usually much more efficient than
+            # manual iteration.
+            #
+            # Technically, the current filesystem could contain more than one
+            # distribution-specific file, in which case there exists no
+            # reasonable means of deciding which better describes the current
+            # distribution. In such cases, print a warning and arbitrarily
+            # select the first.
+            local distro_filename
+            local -a distro_filenames
+            local -A distro_filename_to_name
 
-            # { DB_PREFIX "fedora-release",       "fdra" },
-            # { DB_PREFIX "centos-release",       "Red Hat Enterprise" },
-            # { DB_PREFIX "SuSE-release",		"SUSE" },
-            # { DB_PREFIX "mageia-release",		"Mageia" },
-            # { DB_PREFIX "DISTRO_SPECS",		"Puppy"
-            # { DB_PREFIX "arch-release",         "Arch" },
-            # { DB_PREFIX "sabayon-release",      "Sabayon"  },
-            # { DB_PREFIX "gentoo-release",	"Gentoo"  },
-            # { DB_PREFIX "chakra-release",	"Chakra"  },
-            # { DB_PREFIX "slackware-version",	"Slackware"  },
-            # { DB_PREFIX "frugalware-release",	"Frugalware
-            # { DB_PREFIX "zenwalk-version",	"Zenwalk"  },
-            # /etc/pardus-release # Pardus
-            # /etc/redflag-release # Red Flag
-            # { DB_PREFIX "vine-release",         "Vine" },
-            # { DB_PREFIX "yellowdog-release",	"Yellow Dog"
-            # { DB_PREFIX "turbolinux-release",	"Turbolinux"
-            # { DB_PREFIX "distro-release",	"Foresight"
-            # { DB_PREFIX "enlisy-release",       "Enlisy"},
-            # /etc/system-release # Amazon AMI
-            # /etc/knoppix-version # Knoppix
-            # /etc/lfs-version # Linux From Scratch
-            #  /*
-            #  * RedHat must be the *last* one to be checked, since
-            #  * some distros (like Mandrake) includes a redhat-relase
-            #  * file too.
-            #  *
-            #  * Ditto with Debian-derived distros.
-            #  */
-            # { DB_PREFIX "debian_version",	"Debian" },
-            # { DB_PREFIX "redhat-release",	"Red Hat" },
+            # List of all recognized distribution-specific files in "/etc".
+            # Dismantled, this is:
+            #
+            # * "(.)", including only files that actually exist.
+            distro_filenames=(
+                # All recognized "-release"-suffixed files in arbitrary order,
+                # excluding "redhat-release". Several non-Red Hat distributions
+                # erroneously install such file (presumably for dubious backward
+                # compatibility), requiring such file only be used as a fallback.
+                /etc/{arch,chakra,centos,distro,enlisy,fedora,frugalware,gentoo,mageia,pardus,redflag,sabayon,SuSE,slackware,system,turbolinux,vine,yellowdog}-release(.)
 
-            #FIXME: Don't forget a last-ditch fallback, probably setting:
-            #ZESHY_LINUX_DISTRO_NAME='Unknown'
+                # All recognized "-version"-suffixed files in arbitrary order.
+                /etc/{knoppix,lfs,zenwalk}-version(.)
+
+                # All other distribution-specific files.
+                /etc/DISTRO_SPECS(.)
+            )
+
+            # Map from such files to corresponding distribution names.
+            distro_filename_to_name=(
+                '/etc/arch-release'       'Arch'
+                '/etc/centos-release'     'Red Hat Enterprise'
+                '/etc/chakra-release'     'Chakra'
+                '/etc/DISTRO_SPECS'       'Puppy'
+                '/etc/distro-release'     'Foresight'
+                '/etc/enlisy-release'     'Enlisy'
+                '/etc/fedora-release'     'Fedora'
+                '/etc/frugalware-release' 'Frugalware'
+                '/etc/gentoo-release'     'Gentoo'
+                '/etc/knoppix-version'    'Knoppix'
+                '/etc/lfs-version'        'Linux From Scratch'
+                '/etc/mageia-release'     'Mageia'
+                '/etc/pardus-release'     'Pardus'
+                '/etc/redflag-release'    'Red Flag'
+                '/etc/SuSE-release'       'SUSE'
+                '/etc/sabayon-release'    'Sabayon'
+                '/etc/slackware-release'  'Slackware'
+                '/etc/system-release'     'Amazon AMI'
+                '/etc/turbolinux-release' 'Turbolinux'
+                '/etc/vine-release'       'Vine'
+                '/etc/yellowdog-release'  'Yellow Dog'
+                '/etc/zenwalk-version'    'Zenwalk'
+            )
+
+            # If at least one such file exists...
+            if (( ${#distro_filenames} )) {
+                # If more than one such file exists, print a nonfatal warning.
+                if (( ${#distro_filenames} >= 2 )) {
+                    print 'zeshy: Multiple conflicting distribution-specific files found: ' 1>&2
+                    print "zeshy: ${distro_filenames[@]}" 1>&2
+                }
+
+                # Map the first such file to a corresponding distribution name.
+                # For safety, map to the empty string if we erroneously failed
+                # to map such file above.
+                ZESHY_LINUX_DISTRO_NAME="${distro_filename_to_name[${distro_filenames[1]}]-}"
+
+                # If such file was *NOT* mapped to such a name above, print a
+                # nonfatal warning. While there exist various means of testing
+                # whether map keys exist, this is the easiest when map values
+                # are guaranteed to be nonempty -- as inspection shows above.
+                [[ -n "${ZESHY_LINUX_DISTRO_NAME}" ]] ||
+                    print 'zeshy: Distribution-specific file "'${distro_filenames[1]}'" unmapped.' 1>&2
+            # Else, search for a non-distribution-specific file strongly
+            # implying the current distribution. Such files are provided by
+            # numerous distributions and hence must be tested for only as a
+            # fallback, after exhausting all other options above. Since there
+            # exist only a few such files, search for such files iteratively
+            # rather than via the above efficient but complex approach.
+            #
+            # If a Debian-specific file exists, this is that distribution.
+            } elif [[ -f '/etc/debian_version' ]] {
+                ZESHY_LINUX_DISTRO_NAME='Debian'
+            # If a Red Hat-specific file exists, this is that distribution.
+            } elif [[ -f '/etc/redhat-release' ]] {
+                ZESHY_LINUX_DISTRO_NAME='Red Hat'
+            # Else, such distribution name remains the empty string.
+            }
         }
     # Unload the previously loaded zsh module "mapfile", even in the event of
     # uncaught exceptions or unhandled errors. See :load_module_mapfile_stop()
     # for further details.
     } always {
         zmodload -ui zsh/mapfile
-    }
-
-    # Canonicalize such distribution name. Do *NOT* implicitly capitalize such
-    # name, as numerous distribution names are intended to be lowercase (e.g.,
-    # "elementary OS").
-    #
-    # Remove all instances of the current operating system from such name (e.g.,
-    # the "Linux" in "Arch Linux ARM", "LinuxMint", and "Gentoo Linux"), unless
-    # such instance is absolutely critical to the understanding of such name
-    # (e.g., the "Linux" in "Linux From Scratch"). Dismantled, this is:
-    #
-    # * "(i)", matching case-insensitively. Several distributions entirely
-    #   capitalize such name (e.g., "SUSE LINUX").
-    if [[ "${ZESHY_LINUX_DISTRO_NAME}" != 'Linux From Scratch' ]] {
-        ZESHY_LINUX_DISTRO_NAME="${ZESHY_LINUX_DISTRO_NAME//(i)linux}"
-    }
-
-    # Map non-canonical to canonical distribution names. Numerous distributions
-    # set "DISTRIB_ID" in "/etc/lsb-release" to an either overly specific or
-    # ambiguous name, in either case resulting in related variants of the same
-    # distribution to be treated as different distributions. Correct this.
-    case "${ZESHY_LINUX_DISTRO_NAME}" {
-    # If such name is either "Archarm" or prefixed by "Arch " (e.g., "Arch
-    # ARM"), reduce such name to simply "Arch".
-    'Arch'('arm'|' '*)) ZESHY_LINUX_DISTRO_NAME='Arch';;
-    # If such name is either "CentOS" or prefixed by "RedHatEnterprise" (e.g.,
-    # "RedHatEnterpriseWS", "RedHatEnterpriseServer"), reduce such name to
-    # simply "Red Hat Enterprise".
-    'CentOS'|'RedHatEnterprise'*) ZESHY_LINUX_DISTRO_NAME='Red Hat Enterprise';;
-    # If such name is "elementary", suffix such name by " OS".
-    'elementary') ZESHY_LINUX_DISTRO_NAME='elementary OS';;
-    # If such name is "frugalware", capitalize such name.
-    'frugalware') ZESHY_LINUX_DISTRO_NAME='Frugalware';;
-    # If such name is "openSUSE project", strip the latter word.
-    'openSUSE project') ZESHY_LINUX_DISTRO_NAME='openSUSE';;
     }
 }
 
@@ -499,6 +581,48 @@ function ::set_system_globals_gui_x() {
 ::set_system_globals
 
 # --------------------( WASTELANDS                         )--------------------
+            #FUXME: Don't forget a last-ditch fallback, probably setting:
+            #ZESHY_LINUX_DISTRO_NAME='Unknown'
+            #FUXME: Implement me! And, yes: for our crude purposes here, merely
+            #detecting the existence of the first such file suffices. Yes, this
+            #is basically authoritative at this point, after grepping about a
+            #variety of sources both offline and online. Go, go, go!
+            # /etc/pardus-release # Pardus
+            # /etc/redflag-release # Red Flag
+            # /etc/system-release # Amazon AMI
+            # /etc/knoppix-version # Knoppix
+            # /etc/lfs-version # Linux From Scratch
+
+                # Arbitrarily select the first such file. For easier mapping, strip
+                # the "/etc/" from such filename.
+                # distro_filename="${distro_filenames[1]#/etc/}"
+
+                # # Map such file to a corresponding human-readable distribution name.
+                # case "${distro_filename}" {
+                # 'slackware-release': 
+                # }
+
+                # If the first such file was mapped to a distribution name
+                # above, set the current distribution name to such name. While
+                # there exist various means of testing whether map keys exist,
+                # this is the easiest when map values are guaranteed nonempty.
+                # if [[ -n "${}" ]] {
+            # If more than one such file exists, arbitrarily map the first.
+            # * Match such distribution's specific file into the list below.
+
+            # List of all files in "/etc" suffixed by either "-release",
+            # "_version", or "-version". In case either "/etc/lsb-release" or
+            # "/etc/os-release" exist but do *NOT* contain the previously
+            # searched for keys (e.g., due to malformed syntax), exclude such
+            # files from such list. While command "lsb_release" and
+            # hence the latter should be unavailable here, better comfy than
+            # core-dumped. Dismantled, this is:
+            #
+            # * "~...", excluding all paths matching the following glob.
+            # * "(.)", excluding all paths except extant simple files.
+            # local -a filenames_release; filenames_release=(
+            #     /etc/*{-release,-version,_version}~/etc/(lsb|os)-release(#q.) )
+
         # The canonical command "lsb_release" reads "/etc/lsb-release" to print
         # the current Linux distribution name. Unfortunately, several
         # distributions scurrilously violate such standard by installing
