Shifted "login" to the topmost directory.
Revised login logic in accordance with conventional "/etc/profile"
behavior. Documented a number of critical revisions to be made prior to
official alpha release.

"And so/The slow train/Meanders in mountains lowing/On the fenceline of/
The day."

diff --git a/src/login b/src/login
--- a/src/login
+++ b/src/login
@@ -15,33 +15,32 @@
 # * A process running command "init" executed by...
 # * The current kernel.
 
-# ....................{ EXCEPTIONS                         }....................
-# void die_unless_shell_login(string error_message = 'current shell non-login')
+# ....................{ APPENDERS                          }....................
+# void append_path_with_dir_if_found(string dirname1, string dirname2, ...)
 #
-# Throw an exception unless the current shell is a login shell. See
-function die_unless_shell_login() {
-    die_unless_args_0_to_1 'expected optional error message'
-    is_shell_login or die "${1:-current shell non-login}"
+# Append passed directories to global list ${path} and global string ${PATH},
+# excluding all directories that either do not exist or do but have already been
+# appended to such globals.
+function append_path_with_dir_if_found() {
+    # Validate passed arguments.
+    (( # > 0 )) || die 'expected at least one dirname'
+
+    # Append each existing passed directory. By virtue of the prior call to
+    # "typeset -U path", this implicitly avoids appending duplicate directories.
+    # Dismantled, this is:
+    #
+    # * "(-/)", excluding passed paths that are neither extant directories or
+    #   symbolic links to extant directories.
+    for dirname ( "${@}"(-/) ) {
+#       say "appending \"${dirname}\"..."
+        path+="${dirname}"
+    }
 }
 
-# ....................{ TESTERS                            }....................
-# boolean is_shell_login(void)
-#
-# Return true if the first argument passed to the current shell was "-". The
-# startup process running the "login" command typically passes such argument to
-# startup shells on successful login.
-function is_shell_login() {
-    die_if_args
-    is_shell_option_enabled login
-}
+# ....................{ SOURCERS                           }....................
 
-# --------------------( WASTELANDS                         )--------------------
-# ....................{ MAIN                               }....................
-#append_zeshy_startup_command_if_shell_login startup_zeshy_login
-
-#FIXME: We really want to perform this at the topmost level -- probably in
-#"src/config".
-# void startup_zeshy_login(void)
+# ....................{ SETTERS                            }....................
+# void set_shell_login_defaults(void)
 #
 # Configure the current shell with sane defaults appropriate for login shells.
 # Specifically, if:
@@ -53,18 +52,18 @@ function is_shell_login() {
 #   based distributions, whose justifications are largely antiquated and in any
 #   case blatantly superfluous:
 #   http://www.debian.org/doc/debian-policy/ch-opersys.html#s9.9)
-#function startup_zeshy_login() {
+function set_shell_login_defaults() {
     # Validate sanity.
-#    die_if_args
+    (( # == 0 )) || die 'expected no arguments'
 
     #FIXME: We should only set such umasks only if the current umask remains the
     #default. If the user has changed the umask, then we clearly shouldn't change it
     #out from under them. Alternately, this should arguably be a configurable
-    #option in... hmmmmm; we'd probably want a new "~/.zeshy/config/login", no?
-#    if is_current_user_superuser
-#    then set_path_creation_mask u=rwx,g=rx,o=rx
-#    else set_path_creation_mask u=rwx,g=rx,o=
-#    fi
+    #option in... hmmmmm; we'd probably want a new "if_config/login", no?
+    if (( EUID == 0 ))
+    then umask u=rwx,g=rx,o=rx
+    else umask u=rwx,g=rx,o=
+    fi
 
     #FIXME: source_shell_script() probably shouldn't implicitly append ${FPATH}
     #to ${PATH}, which induces subtle bugs as below. Was the only reason for
@@ -76,77 +75,114 @@ function is_shell_login() {
     #
     # Avoid calling source_shell_script(), which implicitly appends ${FPATH} to
     # ${PATH} and in this context permanently pollutes ${PATH}.
-#    is_file '/etc/profile.env' and source '/etc/profile.env'
+    [[ -f '/etc/profile.env' ]] && source '/etc/profile.env'
 
     # Configure global string ${PATH} and global list ${path} *AFTER* sourcing
     # all shell scripts expected to set default values for such globals.
-#    startup_zeshy_login_globals_path
+    set_shell_login_path
 
     # If "/etc/profile.d/" exists, source all Bourne shell scripts under such
     # directory. Since most distributions supply csh shell scripts under such
     # directory not readily sourceable by Zsh, avoid sourcing everything: e.g.,
     #
     #    for profile_script ( '/etc/profile.d/'*.[^.]#sh(.) ) {
-#    is_dir '/etc/profile.d' and
-#        for profile_script ( '/etc/profile.d/'*.sh ) {
-#            source_shell_script "${profile_script}"
-#        }
-#}
+    [[ -d '/etc/profile.d' ]] && for shell_script ('/etc/profile.d/'*.sh) {
+        #FIXME: I hope we don't really need source_shell_script() here...
+        #but suspect we do. *sigh*
+        source "${shell_script}"
+#       source_shell_script "${shell_script}"
+    }
+}
 
-# void startup_zeshy_login_globals_path(void)
+# void set_shell_login_path(void)
 #
-# Configure global string ${PATH} and list ${path} with sane defaults.
-#function startup_zeshy_login_globals_path() {
+# Configure global list ${path} and global string ${PATH} with sane defaults.
+function set_shell_login_path() {
     # Validate sanity.
-#    die_if_args
+    (( # == 0 )) || die 'expected no arguments'
 #   print "PATH: ${PATH}"
 
-    #FIXME: I've decided the whole distinction between "/bin" and "/sbin" is
+    #FIXME: This helpfully allows us to cleanup hard-coded references to
+    #"/sbin" (e.g., "/sbin/ifconfig"). All such references should be hunted down
+    #and summarily extinguished. If one thinks about it, hard-coding such
+    #references is clearly a *DEPLORABLY ABOMINABLE IDEA*.
+
+    # Append user-specific prior to system-wide paths.
+    append_path_with_dir_if_found "${HOME}/bin"
+
+    # If the current user is effectively the superuser (e.g., due to temporary
+    # privelage escalation), append system-wide paths in a manner conducive to
+    # superuser activities. Namely, append superuser-specific prior to general-
+    # purpose paths.
+    if (( EUID == 0 )); then
+        append_path_with_dir_if_found\
+            '/usr/local/sbin'\
+            '/usr/local/bin'\
+            '/usr/sbin'\
+            '/usr/bin'\
+            '/sbin'\
+            '/bin'\
+            '/etc/init.d'
+    # Otherwise, the current user is normal. Append system-wide paths in a
+    # manner conducive to normal activities. Namely, append general-purpose
+    # prior to superuser-specific paths. Since the latter contain numerous
+    # commands callable by normal users in a read-only manner (e.g., "ip",
+    # "ifconfig"), appending such paths is critical to sane Zeshy function.
+    else
+        append_path_with_dir_if_found\
+            '/usr/local/bin'\
+            '/usr/bin'\
+            '/bin'\
+            '/usr/local/sbin'\
+            '/usr/sbin'\
+            '/sbin'
+    fi
+}
+
+# ....................{ MAIN                               }....................
+set_shell_login_defaults
+
+# --------------------( WASTELANDS                         )--------------------
+    # Store the prior ${PATH} if any for subsequent interpolation.
+#   list path_old
+#   if (( EUID == 0 )) and [[ -n "${ROOTPATH-}" ]]
+#   then path_old="${ROOTPATH}"
+#   else path_old="${path}"
+#   fi
+
+    #FUXME: Since adding "/sbin" to non-superuser paths somewhat goes against
+    #the conventional Linux grain, document why we've done so. Both arguments
+    #substantiante such reasoning.
+    #FUXME: I've decided the whole distinction between "/bin" and "/sbin" is
     #reprehensibly lame. I admit the underlying idea to be idealistically sound,
     #but it just falls down in the real world. In the real world, where we all
     #live, *MOST* "/sbin" commands are meaningfully executable by non-superusers
     #to read (but rarely write) system-wide metadata (e.g., IP address). Hence,
     #there's no meaningful reason to omit "/sbin" from a non-superuser ${PATH}.
     #Stop doing so.
-    #FIXME: This also helpfully allows us to cleanup hard-coded references to
-    #"/sbin" (e.g., "/sbin/ifconfig"). All such references should be hunted down
-    #and summarily extinguished. If one thinks about it, hard-coding such
-    #references is clearly a *DEPLORABLY ABOMINABLE IDEA*.
-    #FIXME: Since adding "/sbin" to non-superuser paths somewhat goes against
-    #the conventional Linux grain, document why we've done so. Both arguments
-    #substantiante such reasoning.
-
-    # Store the prior ${PATH} if any for subsequent interpolation.
-#    string last_PATH
-#    if is_current_user_superuser and is_variable_nonempty ROOTPATH
-#    then last_PATH="${ROOTPATH}"
-#    else last_PATH="${PATH}"
-#    fi
-
-    # Reset ${path} and hence ${PATH}. Avoid resetting ${PATH} directly via
-    # "PATH=", which prefixes ${PATH} with an empty ":" on the first "path+=".
-#    path=( )
-
     # Conditionally append system-wide paths.
-#    append_PATH_with_dir_if_found\
-#        '/usr/local/bin'\
-#        '/usr/bin'\
-#        '/bin'
 
     # If the superuser, conditionally append root-specific paths.
-#    is_current_user_superuser and append_PATH_with_dir_if_found\
-#        '/usr/local/sbin'\
-#        '/usr/sbin'\
-#        '/sbin'\
-#        '/etc/init.d'
+#   is_current_user_superuser and append_path_with_dir_if_found\
+#       '/usr/local/sbin'\
+#       '/usr/sbin'\
+#       '/sbin'\
+#       '/etc/init.d'
 
     # Append the prior $PATH.
-#    PATH+=":${last_PATH}"
+#   path+=( "${path_old}" )
 
-    # Append the user-specific "~/bin/".
-#    append_PATH_with_dir_if_found "${HOME}/bin"
-#}
+#   list path_old
+#   if (( EUID == 0 )) and [[ -n "${ROOTPATH-}" ]]
+#   then path_old="${ROOTPATH}"
+#   else path_old="${path}"
+#   fi
+    # Reset ${path} and hence ${PATH}. Avoid resetting ${PATH} directly via
+    # "PATH=", which prefixes ${PATH} with an empty ":" on the first "path+=".
+#   path=( )
 
+#FUXME: We really want to perform this at the topmost level -- probably in
+#"src/config".
     # Configure globals.
 #   startup_zeshy_login_globals
 #}
@@ -180,7 +216,7 @@ function is_shell_login() {
 #       is not "${PATH}" =~ "(^|:)${dirname}($|:)" si and
     # Append Zeshy's "bin/".
 #   string zeshy_bin_dir="${ZESHY_HOME}/bin"
-#   append_PATH_with_dir_if_found "${zeshy_bin_dir}"
+#   append_path_with_dir_if_found "${zeshy_bin_dir}"
 
     # Append each command in Zeshy's "bin/command/" installed on this machine,
     # matching all subdirectories of that directory via the "(/)" modifier.
@@ -188,7 +224,7 @@ function is_shell_login() {
 #   for zeshy_bin_command_dir ("${zeshy_bin_dir}/command"/*(/)) {
 #       zeshy_bin_command_name="$(get_path_basename "${zeshy_bin_command_dir}")"
 #       is_installed "${zeshy_bin_command_name}" and
-#           append_PATH_with_dir_if_found "${zeshy_bin_command_dir}"
+#           append_path_with_dir_if_found "${zeshy_bin_command_dir}"
 #   }
 # For each passed directory name, append such name onto ${PATH} if not already
 # and for which the corresponding directory exists and is readable.
