Completed "io/locale/encoding" hook additions.
Such parcel now compiles map global ${ZESHY_STYLE_TO_TEXT} into zeshy's
user digest file on the basis of whether or not the current locale at
the time of such compilation encodes UTF-8. And the elves did blather
about, witlessly, in the full moon's seared heat and pomp.

diff --git a/src/login b/src/login
--- a/src/login
+++ b/src/login
@@ -1,6 +1,4 @@
 #!/usr/bin/env zsh
-# ====================[ login                              ]====================
-#
 # --------------------( LICENSE                            )--------------------
 # Copyright 2007-2013 by Cecil Curry.
 # See "COPYING" for additional details.
@@ -15,13 +13,13 @@
 # * A process running command "init" executed by...
 # * The current kernel.
 
-#FIXME: If compiling Zeshy, this component should be sourced if not already
-#sourced to ensure such functions are compiled into Zeshy. Of course, this gets
+#FIXME: If compiling zeshy, this component should be sourced if not already
+#sourced to ensure such functions are compiled into zeshy. Of course, this gets
 #a bit tricky:
 #
 #* The bottom of this script calls login_zeshy(), which we don't really want to
-#  happen when compiling Zeshy under non-login shells.
-#* When compiling Zeshy under login shells, such functions will have already
+#  happen when compiling zeshy under non-login shells.
+#* When compiling zeshy under login shells, such functions will have already
 #  been defined and hence not recognized for compilation. *sigh*
 
 # ....................{ APPENDERS                          }....................
@@ -55,20 +53,20 @@ void login_zeshy(void)
 
 Configure the current shell with sane defaults appropriate for login shells.
 If global list ${path} and hence global string ${PATH} is non-empty, either
-the current user''s ".zprofile" or system-wide "/etc/zsh/zprofile" script has
+the current user''s `.zprofile` or system-wide `/etc/zsh/zprofile` script has
 already performed such configuration, in which case this function effectively
-returns immediately. Otherwise, no prior script has performed such
-configuration, in which case this function:
+returns immediately. Else, no prior script has performed such configuration, in
+which case this function:
 
 * Sets a default command path (i.e., global list ${path} and string ${PATH}).
-* Sets a default file creation mask (i.e., "umask").
-* If "/etc/profile.env" is an existing file, sources such script. (Specific
+* Sets a default file creation mask (i.e., `umask`).
+* If `/etc/profile.env` is an existing file, sources such script. (Specific
   to Gentoo Linux-based distributions and derivative friends.)
-* If "/etc/profile.d/" is an existing directory, sources all scripts under
+* If `/etc/profile.d/` is an existing directory, sources all scripts under
   such directory. (Supported by most Linux distributions excluding Debian-
-  based distributions, whose justifications are largely antiquated and in any
-  case blatantly superfluous:
-  http://www.debian.org/doc/debian-policy/ch-opersys.html#s9.9)
+  based distributions, whose
+  http://www.debian.org/doc/debian-policy/ch-opersys.html#s9.9[justifications]
+  are largely antiquated and in any case blatantly superfluous.)
 '
 function login_zeshy() {
     # Validate sanity.
@@ -108,10 +106,31 @@ function login_zeshy_profile() {
         umask u=rwx,g=rx,o=
     }
 
-    # If "/etc/profile.env" exists, source such script.
+    #FIXME: Such script is a Bourne shell script and hence should be sourced
+    #under emulation, as performed below. We probably want to create a new
+    #*ALIAS* emulate_shell_sh_locally() as follows:
     #
-    # Avoid calling source_shell_script(), which implicitly appends ${FPATH} to
-    # ${PATH} and in this context permanently pollutes ${PATH}.
+    #    alias emulate_shell_sh_locally='{
+    #        emulate -LR sh
+    #        TRAPZERR() { return $(( 128 + ${1} )) }
+    #    }'
+    #
+    #To expand such alias safely here, we'll need to segregate the following
+    #logic into a new function as follows:
+    #
+    #    function login_zeshy_profile_env() {
+    #        # Validate sanity.
+    #        (( # == 0 )) || die 'expected no arguments'
+    #        [[ -f '/etc/profile.env' ]] || return 0
+    #        emulate_shell_sh_locally
+    #        source '/etc/profile.env'
+    #    }
+    #
+    #Simple, eh?
+
+    # If "/etc/profile.env" exists, source such script. Avoid calling
+    # source_shell_script(), which implicitly appends ${FPATH} to ${PATH} and in
+    # this context permanently pollutes ${PATH}.
     if [[ -f   '/etc/profile.env' ]] {
         source '/etc/profile.env'
     }
@@ -160,7 +179,7 @@ function login_zeshy_path() {
     # manner conducive to normal activities. Namely, append general-purpose
     # prior to superuser-specific paths. Since the latter contain numerous
     # commands callable by normal users in a read-only manner (e.g., "ip",
-    # "ifconfig"), appending such paths is critical to sane Zeshy function.
+    # "ifconfig"), appending such paths is critical to sane zeshy function.
     } else {
         append_path_with_dir_if_found\
             '/usr/local/bin'\
@@ -176,8 +195,8 @@ ZESHY_CORE_HELP_FUNCTIONS+='
 void login_zeshy_profile_scripts(void)
 
 Configure the current shell with the default system-wide login profile.
-Specifically, source all Bourne shell scripts under "/etc/profile.d" if such
-directory exists.
+Specifically, source all shell scripts under `/etc/profile.d` if such directory
+exists.
 '
 function login_zeshy_profile_scripts() {
     # Validate sanity. Unless "/etc/profile.d/" exists, immediately return.
@@ -186,7 +205,8 @@ function login_zeshy_profile_scripts() {
 
     # Emulate Bourne shell prior to sourcing Bourne shell scripts below by
     # temporarily enabling Bourne shell options and builtins and ignoring
-    # rather than throwing exceptions on non-zero exit status.
+    # rather than throwing exceptions on non-zero exit status. See
+    # run_command_under_shell() for further details.
     emulate -LR sh
     TRAPZERR() { return $(( 128 + ${1} )) }
 
@@ -198,7 +218,7 @@ function login_zeshy_profile_scripts() {
     #     for profile_script ('/etc/profile.d/'*.[^.]#sh(.)) {
     local shell_script
     for   shell_script ('/etc/profile.d/'*.sh) {
-        source "${shell_script}" or die "\"${shell_script}\" not sourceable"
+        source -- "${shell_script}" or die "\"${shell_script}\" not sourceable"
     }
 }
 
