Substantially improved config file handling.
This commit decreases the load cost and code complexity associated with
Zeshy configurating files, and improves "grep" and "rsync" integration.

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -62,9 +62,12 @@
 #   * Perform all costly initialization in the functions requiring such
 #     initialization as the first line of such functions. You know that grind...
 
-# ....................{ PREAMBLE                           }....................
-# Absolute path to Zeshy's topmost directory, if not already set.
+# ....................{ PATHS                              }....................
+# Directory hosting the Zeshy codebase.
 [[ -n "${ZESHY_HOME-}" ]] || export ZESHY_HOME="${0:h}/.."(:A)
+
+# Directory hosting the Zeshy library.
+export ZESHY_SOURCE_DIR="${ZESHY_HOME}/src"
 
 # ....................{ OPTIONS                            }....................
 # Command history.
@@ -144,7 +147,7 @@ setopt nolistambiguous   # only list matches if ambiguous
 # Variable expansion.
 #
 # Enforce strictness for safety as under conventional high-level languages.
-setopt nounset           # attempting to expand unset parameters raises an error
+setopt nounset            # attempting to expand unset parameters raises an error
 setopt warn_create_global # attempting to set untyped parameters raises an error
 
 # ....................{ OPTIONS ~ shell                    }....................
@@ -419,41 +422,51 @@ TRAPZERR() {
     die_with ${exit_status}
 }
 
-# ....................{ MAIN                               }....................
+#FIXME: Zsh fails to trigger ZERR traps from within the sourcing of zprofile and
+#zshrc. I have no idea why. Since the following line does nothing to help,
+#however, I can only assume this is somehow the intended behavior. Nonetheless,
+#file a mailing list comment.
+#trap TRAPZERR ZERR
+
+# ....................{ BOOTSTRAP                          }....................
 # Bootstrap Zeshy by loading core aliases, globals, and autoloads, the minimal
 # clique of Zeshy components. All subsequent Zeshy functions are implicitly
 # loaded on the first call to such functions by the autoload system.
-source "${ZESHY_HOME}/src/alias"
-source "${ZESHY_HOME}/src/global"
-source "${ZESHY_HOME}/src/digest"
+#utter 'finalizing aliases...'
+source "${ZESHY_SOURCE_DIR}/alias"
+#utter 'finalizing globals...'
+source "${ZESHY_SOURCE_DIR}/global"
+#utter 'finalizing digest...'
+source "${ZESHY_SOURCE_DIR}/digest"
 #utter 'finalizing startup...'
 
-# If this shell is attached to a terminal device, set terminal-specific options.
-if is_shell_interactive; then
-#   utter 'setting mimetype aliases...'
-    set_default_mimetype_aliases
-#   utter 'setting color globals...'
-    set_global_colors
-#   utter 'setting key bindings...'
-    set_theme_key_bindings
-#   utter 'setting styles...'
-    set_theme_styles
-#   utter 'setting prompt...'
-    set_theme_prompt
-else
-    # Set the default script name prior to all other logic, as any logic
-    # raising an error requires this name for logging that error. Only do this
-    # if the current process is not an interactive Zsh shell as, in that case,
-    # the get_script_name() function dynamically inspects the script name from
-    # the function call stack.
-    if not is_shell_interactive; then
+# ....................{ MAIN                               }....................
+() {
+    # If this shell is attached to a terminal device, set terminal-specific options.
+    if is_shell_interactive; then
+    #   utter 'setting mimetype aliases...'
+        set_default_mimetype_aliases
+    #   utter 'setting color globals...'
+        set_global_colors
+    #   utter 'setting key bindings...'
+        set_theme_key_bindings
+    #   utter 'setting styles...'
+        set_theme_styles
+    #   utter 'setting prompt...'
+        set_theme_prompt
+    else
+        # Set the default script name prior to all other logic, as any logic
+        # raising an error requires this name for logging that error. Only do this
+        # if the current process is not an interactive Zsh shell as, in that case,
+        # the get_script_name() function dynamically inspects the script name from
+        # the function call stack.
         # Strip the filetype from this script's basename, if present.
         global_string ZESHY_SCRIPT_NAME="${$(get_process_command_name)%%.*}"
 
         # Default the script name to "zeshy", if "zsh".
         is "${ZESHY_SCRIPT_NAME}" == zsh si and ZESHY_SCRIPT_NAME=zeshy
     fi
-fi
+}
 
 #FIXME: Obsolete.
 # Math module supplementing Zsh's rudimentary math functionality with essential
