Defined :is_version_at_least() to @{main}.
Such function is both more robust and efficient than that provided by stock zsh
installations, but sufficiently verbose to warrant its moving into the main
zeshy codebase. For another day, my eager lads!

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -140,6 +140,175 @@ typeset -g ZESHY_ZSH_VERSION_REQUIRED='5.0.0'
 # ....................{ VERSION                            }....................
 #FIXME: Non-ideal. Ideally, replace this with a generic zeshy function accepting
 #two version specifiers and reporting success if the former exceeds the latter.
+#FIXME: For obvious reasons, such function should be defined and called *AFTER*
+#setting core shell options.
+#FIXME: Document such tester.
+#FIMXE: Wait. Such tester, while positively *BANGIN'*, is extreme overkill here.
+#But so was the prior tester. If you consider it, since there only exist a
+#finite number of prior zsh major version, the test below always reduces to:
+#
+#    if [[ "${ZSH_VERSION}" == <0-4>.* ]] {
+#        print "zeshy: zsh ${ZSH_VERSION} older than requisite version ${ZESHY_ZSH_VERSION_REQUIRED}." 1>&2
+#        return 1
+#    }
+#
+#That said, since :is_version_at_least() is awesome, shift such function to a
+#new parcel @{20-main/version}. Naturally, all other version-related functions
+#in the codebase should be shifted there as well. Sweet!
+
+# [status: bool] :is_version_at_least(string version, string minimum_version)
+function :is_version_at_least() {
+    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+    # To permit this function to be shifted to a top-level parcel should the
+    # need arise (e.g., to validate zsh versions), this function should be
+    # implemented as a low-level zsh rather than high-level zeshy function.
+    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+
+    # Validate sanity.
+    (( # == 2 )) || die 'Expected two version specifiers.'
+    local\
+        version_current="${1}"\
+        version_minimum="${2}"\
+        version_current_dots\
+        version_minimum_dots\
+        version_current_suffix\
+        version_minimum_suffix\
+        versions_current_item\
+        versions_minimum_item
+    integer\
+        versions_current_count\
+        versions_minimum_count\
+        versions_current_size
+    local -a versions_current versions_minimum
+
+    # Clear canonical list global ${match} in preparation for use below.
+    match=()
+
+    # Strip "-"-prefixed suffixes from such version specifiers (e.g., the "-rc1"
+    # in "8.4.2-rc1"), which typically contain non-numeric characters and a
+    # different delimiter (i.e., "-" rather than "."). Retaining such suffixes
+    # would complicate logic below iterating on lists split from such version
+    # specifiers on delimiting ".". Dismantled, this is:
+    #
+    # * "//", removing all substrings matching:
+    #   * "-[^0-9]#", a "-" followed by zero or more non-digits.
+    #   * "(#b)(<->##)", capturing one or more digits into ${match[1]}.
+    #   * "(#e)", anchoring such match to the end of the string.
+    # * "${match[1]-}", expanding to such suffixing digits or the empty string
+    #   if such version specifier has no such suffix.
+    version_current="${version_current//-[^0-9]#(#b)(<->##)(#e)}"
+    version_current_suffix="${match[1]-}"
+    version_minimum="${version_minimum//-[^0-9]#(#b)(<->##)(#e)}"
+    version_minimum_suffix="${match[1]-}"
+
+    #FIXME: This is actually a reasonably clever, efficient means for counting
+    #the number of instances of some character in a string. Generalize into a
+    #new setter :set_int_to_string_chars_equaling_count().
+
+    # Version specifiers stripped of all characters *EXCEPT* delimiting ".". To
+    # avoid special case errors when such specifiers contain no ".", this *MUST*
+    # be performed in a separate operation from the string counting performed
+    # below. See set_integer_to_string_length_printable() for further details.
+    version_current_dots="${version_current//[^.]}"
+    version_minimum_dots="${version_minimum//[^.]}"
+
+    # Number of items in each "."-delimited version specifier. See
+    # :set_int_to_string_chars_equaling_count() for further details.
+    versions_current_count=${#version_current_dots}
+    versions_minimum_count=${#version_minimum_dots}
+
+    # If such numbers differ, append the smaller version specifier with
+    # sufficiently many ".0" until the two contain the same number of items. See
+    # :repeat_string() for further details.
+    if (( versions_current_count != versions_minimum_count )) {
+        # Length of the appended substring containing sufficiently many ".0"'s.
+        # Dismantled, this is:
+        #
+        # * "abs(...)", the number of ".0" to be appended.
+        # * "2", the string length of ".0".
+        integer suffix_length; suffix_length="$((\
+            abs(versions_minimum_count - versions_current_count) * 2 ))"
+
+        # If the current version is smaller, append to such string.
+        if (( versions_current_count < versions_minimum_count )) {
+            version_current+="${(r~${suffix_length}~~.0~):-}"
+        # Else, the minimum version is smaller. Append to such string.
+        } else {
+            version_minimum+="${(r~${suffix_length}~~.0~):-}"
+        }
+    }
+
+    # Split such version on the canonical version specifier delimiter ".".  See
+    # :set_list_to_string_split_on_char() for further details.
+    local IFS='.'
+    versions_current=( "${=version_current}" )
+    versions_minimum=( "${=version_minimum}" )
+
+    # Sizes of the former list.
+    versions_current_size=${#versions_current}
+
+    #FIXME: Only perform such check under debug releases.
+    # If such lists have different sizes, throw an exception. Since the prior
+    # conditional should have guaranteed their equity, this is only a debug-
+    # specific sanity check.
+    (( versions_current_size == ${#versions_minimum} )) || die\
+        'Versions "'${versions_current}'" and "'${versions_minimum}'" differ in "." character counts.'
+
+    # Such current version is typically expanded from either a variable value or
+    # command output. In either case, such version is canonical and hence
+    # complete (i.e., is a syntactically valid version specifier for such
+    # command containing all expected fields). That being the case, iterate by
+    # the current rather than minimum version.
+    integer versions_current_index=0
+    for ((; versions_current_index <= versions_current_size;
+            versions_current_index++ )) {
+        # Currently iterated items in such version specifiers.
+        versions_current_item="${versions_current[versions_current_index]}"
+        versions_minimum_item="${versions_minimum[versions_minimum_index]}"
+
+        # If either the current or minimum item contains non-digits, throw an
+        # exception. For sanity, this function requires strictly formatted
+        # version specifiers.
+        [[ "${versions_current_item}${versions_minimum_item}" == <-> ]] || die\
+            'Versions "'${versions_current}'" and/or "'${versions_minimum}'" contain non-digits.'
+
+        # If such items differ, such version specifiers are immediately
+        # comparable without needing to compare subsequent items.
+        if (( versions_current_item != versions_minimum_item )) {
+            # If the current version is newer, report success; else, failure.
+            (( versions_current_item > versions_minimum_item )) &&
+                return 0 ||
+                return 1
+        }
+    }
+
+    # Such iteration completed without reporting, implying such version
+    # specifiers to be equal *EXCLUDING* "-"-prefixed suffixes. However, such
+    # suffixes could still differ.
+    #
+    # If both such suffixes exist, report their comparison. Unlike above,
+    # equality implies such version specifiers to be equal and hence the current
+    # version at least the minimum version.
+    if [[ -n "${version_current_suffix}" &&
+          -n "${version_minimum_suffix}" ]] {
+        (( version_current_suffix >= version_minimum_suffix )) &&
+            return 0 ||
+            return 1
+    # Else if only the current version is suffixed, report success (e.g.,
+    # "5.0.0-r2" >= "5.0.0").
+    } elif [[ -n "${version_current_suffix}" ]] {
+        return 0
+    # Else if only the minimum version is suffixed, report failure (e.g.,
+    # "5.0.0" < "5.0.0-r2").
+    } elif [[ -n "${version_minimum_suffix}" ]] {
+        return 1
+    }
+
+    # Else, neither version is suffixed. This implies such version specifiers to
+    # be equivalent and hence the current version at least the minimum version.
+    # Report success.
+    return 0
+}
 
 # If *NOT* running under such version, print an error message to standard error
 # and return rather than exiting to avoid exiting interactive shells with non-
@@ -1236,6 +1405,65 @@ if [[ -n "${*}" ]] {
 return 0
 
 # --------------------( WASTELANDS                         )--------------------
+    #FUXME: Pretty terrible. Let's unwind the double loop, yes? To do so, we'll
+    #need to guarantee the two lists to have an equal number of items. Or
+    #perhaps just iterate, defaulting not-found-items to 0?
+    #FUXME: Wait. This is silly, isn't it? Can't we just:
+    #
+    #* Find out how many items are in the current and minimum version
+    #  specifiers, as above.
+    #* Take the difference in the sizes of each such list, appending
+    #  sufficiently many 0's to the smaller list (if either is smaller) to
+    #  ensure they contain the same number of elements.
+    #* Join such lists on the empty string back into two strings. (See
+    #  join_list(). Yes!)
+    #* Strip all non-numeric characters from both strings.
+    #FUXME: Wait. That's obvious bollocks. Hmmmmm. Right. Nothing for it but
+    #manual iteration. That said, we should ensure that "5.0.0" >= "5.0.0-rc2".
+    #To do so, we'll have to handle "-"-prefixed suffixes in a special manner;
+    #namely:
+    #
+    #* Strip such suffixes off each such version into two local strings. Leave
+    #  such strings as the empty string if the corresponding version has no such
+    #  suffix. If iteration completes without terminating early, then and only
+    #  then do we compare such suffixes (stripped of non-numeric prefixes, of
+    #  course).
+    #* If both such strings are nonempty, report the result of comparing such
+    #  strings.
+    #* Else if such string for the current version is empty, report success
+    #  (e.g., "5.0.0" >= "5.0.0-rc2").
+    #* Else, report failure (e.g., "5.0.0-beta2" < "5.0.0").
+    #
+    #Sweet! Fairly simple.
+    #FUXME: Before doing so, if iteration fails to terminate, first check
+    #whether (( ${#versions_current} <= ${#versions_minimum} )). If so (e.g.,
+    #"5.0" <= "5.0.0"), ... ugh. To simplify this, we really should ensure such
+    #lists have the same size. Arguably, the simplest means of doing so would be
+    #to count 
+
+    # Such iteration completed without reporting, implying the two versions to
+    # be equal and hence the former to be at least the latter. Report success.
+    #* Else if such string for the current version is empty, report success
+    #  (e.g., "5.0.0" >= "5.0.0-rc2").
+    #* Else, report failure (e.g., "5.0.0-beta2" < "5.0.0").
+
+    #While
+    # counter-intuitive, "-"-prefixed suffixes commonly signify candidate
+    # releases and hence 
+    # If at least one such suffix exists...
+
+    # version_current="${version_current%%*-[^0-9]#}"
+    # version_minimum_suffix="${version_minimum%%*-[^0-9]#}"
+    # "-"-prefixed suffixes of such version specifiers (e.g., the "-rc1" in
+    # "8.4.2-rc1") stripped of non-numeric characters - including "-".
+    # version_current_suffix="${version_current%%*-[^0-9]#}"
+    # version_minimum_suffix="${version_minimum%%*-[^0-9]#}"
+
+    #FUXME: Great. Now that we have such counts, append as many instances of
+    #".0" as necessary to the smaller specifier. Simple! See repeat_string().
+    #FUXME: Why append 0 to ${version_current}?
+
+    # Split such version on customary version specifier delimiters "." and "-".
 # typeset -g ZESHY_USER_VERSION_FILE="${ZESHY_USER_CACHE_DIR}/version"
 
             # if (( ${ZESHY_ERROR_HANDLER_IS_PRINTING_CALL_STACK-0} )) ||
