Added new parcel @{*-main/version}.
Such parcel centralizes version specifier logic, particularly that of
:is_version_at_least(). Given such parcel, we've significantly reduced the up-
front work performed by @{main} to prevent execution under old zsh interpreters.

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -135,187 +135,27 @@ local -a\
     ZESHY_CORE_HELP_GLOBALS
 
 # ....................{ GLOBALS                            }....................
-typeset -g ZESHY_ZSH_VERSION_REQUIRED='5.0.0'
+typeset -g ZESHY_VERSION='0.1.0'
 
-# ....................{ VERSION                            }....................
-#FIXME: Non-ideal. Ideally, replace this with a generic zeshy function accepting
-#two version specifiers and reporting success if the former exceeds the latter.
-#FIXME: For obvious reasons, such function should be defined and called *AFTER*
-#setting core shell options.
-#FIXME: Document such tester.
-#FIMXE: Wait. Such tester, while positively *BANGIN'*, is extreme overkill here.
-#But so was the prior tester. If you consider it, since there only exist a
-#finite number of prior zsh major version, the test below always reduces to:
+# If the major version of the current zsh interpreter is less than 5, such
+# interpreter is older than zeshy requires. In such case, print an error message
+# to standard error and fail. If the current shell is interactive, avoid exiting
+# such shell (and hence hiding such message) by returning instead.
 #
-#    if [[ "${ZSH_VERSION}" == <0-4>.* ]] {
-#        print "zeshy: zsh ${ZSH_VERSION} older than requisite version ${ZESHY_ZSH_VERSION_REQUIRED}." 1>&2
-#        return 1
-#    }
+# Note that there exist various methods of comparing version specifiers, with
+# the customary tradeoffs in complexity versus efficiency. In particular, zsh
+# defines the autoloadable script "is-at-least" and zeshy the function
+# :is_version_at_least(). While either does reliably compare arbitrary version
+# specifiers, the former requires sourcing an external script iterating with
+# doubly nested "while" loops and the latter embedding a nearly 200-line
+# function in the root script sourced on every zeshy startup.
 #
-#That said, since :is_version_at_least() is awesome, shift such function to a
-#new parcel @{20-main/version}. Naturally, all other version-related functions
-#in the codebase should be shifted there as well. Sweet!
-
-# [status: bool] :is_version_at_least(string version, string minimum_version)
-function :is_version_at_least() {
-    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-    # To permit this function to be shifted to a top-level parcel should the
-    # need arise (e.g., to validate zsh versions), this function should be
-    # implemented as a low-level zsh rather than high-level zeshy function.
-    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-
-    # Validate sanity.
-    (( # == 2 )) || die 'Expected two version specifiers.'
-    local\
-        version_current="${1}"\
-        version_minimum="${2}"\
-        version_current_dots\
-        version_minimum_dots\
-        version_current_suffix\
-        version_minimum_suffix\
-        versions_current_item\
-        versions_minimum_item
-    integer\
-        versions_current_count\
-        versions_minimum_count\
-        versions_current_size
-    local -a versions_current versions_minimum
-
-    # Clear canonical list global ${match} in preparation for use below.
-    match=()
-
-    # Strip "-"-prefixed suffixes from such version specifiers (e.g., the "-rc1"
-    # in "8.4.2-rc1"), which typically contain non-numeric characters and a
-    # different delimiter (i.e., "-" rather than "."). Retaining such suffixes
-    # would complicate logic below iterating on lists split from such version
-    # specifiers on delimiting ".". Dismantled, this is:
-    #
-    # * "//", removing all substrings matching:
-    #   * "-[^0-9]#", a "-" followed by zero or more non-digits.
-    #   * "(#b)(<->##)", capturing one or more digits into ${match[1]}.
-    #   * "(#e)", anchoring such match to the end of the string.
-    # * "${match[1]-}", expanding to such suffixing digits or the empty string
-    #   if such version specifier has no such suffix.
-    version_current="${version_current//-[^0-9]#(#b)(<->##)(#e)}"
-    version_current_suffix="${match[1]-}"
-    version_minimum="${version_minimum//-[^0-9]#(#b)(<->##)(#e)}"
-    version_minimum_suffix="${match[1]-}"
-
-    #FIXME: This is actually a reasonably clever, efficient means for counting
-    #the number of instances of some character in a string. Generalize into a
-    #new setter :set_int_to_string_chars_equaling_count().
-
-    # Version specifiers stripped of all characters *EXCEPT* delimiting ".". To
-    # avoid special case errors when such specifiers contain no ".", this *MUST*
-    # be performed in a separate operation from the string counting performed
-    # below. See set_integer_to_string_length_printable() for further details.
-    version_current_dots="${version_current//[^.]}"
-    version_minimum_dots="${version_minimum//[^.]}"
-
-    # Number of items in each "."-delimited version specifier. See
-    # :set_int_to_string_chars_equaling_count() for further details.
-    versions_current_count=${#version_current_dots}
-    versions_minimum_count=${#version_minimum_dots}
-
-    # If such numbers differ, append the smaller version specifier with
-    # sufficiently many ".0" until the two contain the same number of items. See
-    # :repeat_string() for further details.
-    if (( versions_current_count != versions_minimum_count )) {
-        # Length of the appended substring containing sufficiently many ".0"'s.
-        # Dismantled, this is:
-        #
-        # * "abs(...)", the number of ".0" to be appended.
-        # * "2", the string length of ".0".
-        integer suffix_length; suffix_length="$((\
-            abs(versions_minimum_count - versions_current_count) * 2 ))"
-
-        # If the current version is smaller, append to such string.
-        if (( versions_current_count < versions_minimum_count )) {
-            version_current+="${(r~${suffix_length}~~.0~):-}"
-        # Else, the minimum version is smaller. Append to such string.
-        } else {
-            version_minimum+="${(r~${suffix_length}~~.0~):-}"
-        }
-    }
-
-    # Split such version on the canonical version specifier delimiter ".".  See
-    # :set_list_to_string_split_on_char() for further details.
-    local IFS='.'
-    versions_current=( "${=version_current}" )
-    versions_minimum=( "${=version_minimum}" )
-
-    # Sizes of the former list.
-    versions_current_size=${#versions_current}
-
-    #FIXME: Only perform such check under debug releases.
-    # If such lists have different sizes, throw an exception. Since the prior
-    # conditional should have guaranteed their equity, this is only a debug-
-    # specific sanity check.
-    (( versions_current_size == ${#versions_minimum} )) || die\
-        'Versions "'${versions_current}'" and "'${versions_minimum}'" differ in "." character counts.'
-
-    # Such current version is typically expanded from either a variable value or
-    # command output. In either case, such version is canonical and hence
-    # complete (i.e., is a syntactically valid version specifier for such
-    # command containing all expected fields). That being the case, iterate by
-    # the current rather than minimum version.
-    integer versions_current_index=0
-    for ((; versions_current_index <= versions_current_size;
-            versions_current_index++ )) {
-        # Currently iterated items in such version specifiers.
-        versions_current_item="${versions_current[versions_current_index]}"
-        versions_minimum_item="${versions_minimum[versions_minimum_index]}"
-
-        # If either the current or minimum item contains non-digits, throw an
-        # exception. For sanity, this function requires strictly formatted
-        # version specifiers.
-        [[ "${versions_current_item}${versions_minimum_item}" == <-> ]] || die\
-            'Versions "'${versions_current}'" and/or "'${versions_minimum}'" contain non-digits.'
-
-        # If such items differ, such version specifiers are immediately
-        # comparable without needing to compare subsequent items.
-        if (( versions_current_item != versions_minimum_item )) {
-            # If the current version is newer, report success; else, failure.
-            (( versions_current_item > versions_minimum_item )) &&
-                return 0 ||
-                return 1
-        }
-    }
-
-    # Such iteration completed without reporting, implying such version
-    # specifiers to be equal *EXCLUDING* "-"-prefixed suffixes. However, such
-    # suffixes could still differ.
-    #
-    # If both such suffixes exist, report their comparison. Unlike above,
-    # equality implies such version specifiers to be equal and hence the current
-    # version at least the minimum version.
-    if [[ -n "${version_current_suffix}" &&
-          -n "${version_minimum_suffix}" ]] {
-        (( version_current_suffix >= version_minimum_suffix )) &&
-            return 0 ||
-            return 1
-    # Else if only the current version is suffixed, report success (e.g.,
-    # "5.0.0-r2" >= "5.0.0").
-    } elif [[ -n "${version_current_suffix}" ]] {
-        return 0
-    # Else if only the minimum version is suffixed, report failure (e.g.,
-    # "5.0.0" < "5.0.0-r2").
-    } elif [[ -n "${version_minimum_suffix}" ]] {
-        return 1
-    }
-
-    # Else, neither version is suffixed. This implies such version specifiers to
-    # be equivalent and hence the current version at least the minimum version.
-    # Report success.
-    return 0
-}
-
-# If *NOT* running under such version, print an error message to standard error
-# and return rather than exiting to avoid exiting interactive shells with non-
-# zero exit status.
-autoload -U is-at-least
-is-at-least ${ZESHY_ZSH_VERSION_REQUIRED} || {
-    print "zeshy: zsh ${ZSH_VERSION} older than requisite version ${ZESHY_ZSH_VERSION_REQUIRED}." 1>&2
+# Fortunately, the following simpler method presents itself.
+if [[ "${ZSH_VERSION}" == <0-4>.* ]] {
+    {
+        print "zeshy: zsh 5.0.0 or newer required, but running under zsh ${ZSH_VERSION}."
+        print "zeshy: Consider upgrading, if feasible. (Sorry. Sumimasen. Entschuldigung.)"
+    } 1>&2
     return 1
 }
 
@@ -1190,30 +1030,39 @@ typeset -g ZESHY_USER_DIGEST_ROOT_DIRNAME="${ZESHY_USER_CACHE_DIR}/digest"
 typeset -g ZESHY_USER_NAMES_FILE="${ZESHY_USER_CACHE_DIR}/names.zsh"
 
 # ....................{ LOAD                               }....................
+#FIXME: Right. The thing is, "bin/zeshy" should pass option "NO_RCS" to *ANY*
+#zsh interpreter it runs, including the zsh interpreter implicitly run due to
+#the shebang line. (If need be, we can guarantee this by making "bin/zeshy" a
+#Bourne shell script running the true zsh script "bin/zeshy.zsh" with option
+#"NO_RCS"). In such case, zeshy will only ever be genuinely loaded once,
+#obviating any need for global ${ZESHY_PID_LAST_LOADED_BY} and the related
+#contortions both below and in "/bin/zeshy". In truth, this will probably have
+#to wait until we rewrite "/bin/zeshy" as a C driver.
+
 # If sourcing the current script under zsh startup logic (e.g., from a zsh
 # script with basename matching either ".zlogin", ".zprofile", or ".zshrc"),
-# prevent zsh from reloading Zeshy if already loaded earlier during such logic.
+# prevent zsh from reloading zeshy if already loaded earlier during such logic.
 #
 # Ideally, the current script should only ever be sourced by the "zeshy" script
-# installed with Zeshy. Ideally, zsh startup logic should avoid sourcing the
-# current script. Since Zeshy is valid zsh, however, this script is sourceable
+# installed with zeshy. Ideally, zsh startup logic should avoid sourcing the
+# current script. Since zeshy is valid zsh, however, this script is sourceable
 # as is by any zsh script or shell -- including zsh startup scripts. In such a
-# case, failing to prevent zsh from reloading Zeshy induces the following:
+# case, failing to prevent zsh from reloading zeshy induces the following:
 #
 # * Some process runs the "zeshy" script as a new child process.
 # * This process runs under "zsh" due to such script's shebang line.
 # * This process sources at least ".zshrc" and possibly also ".zlogin" and
 #   ".zprofile", depending on runtime context.
-# * Sourcing such script could source the current script, loading Zeshy.
+# * Sourcing such script could source the current script, loading zeshy.
 # * After sourcing the current script, control returns to the "zeshy" script,
 #   which either:
-#   * Sources the current script, reloading Zeshy.
+#   * Sources the current script, reloading zeshy.
 #   * Replaces this process with a new process running "zsh" passed the current
-#     script as its first argument and hence reloading Zeshy twice:
+#     script as its first argument and hence reloading zeshy twice:
 #     * Once by zsh startup logic, as above.
 #     * Once by the first argument passed to such script.
 #
-# In either case, zsh loads Zeshy at least twice and possibly more. Avoid this!
+# In either case, zsh loads zeshy at least twice and possibly more. Avoid this!
 #print "zeshy: argv[0]=$0}"
 #print "zeshy: command line=$(< /proc/$$/cmdline)"
 #print "zeshy: process ID (current)=$$"
@@ -1221,20 +1070,17 @@ typeset -g ZESHY_USER_NAMES_FILE="${ZESHY_USER_CACHE_DIR}/names.zsh"
 #print "zeshy: process ID (cached.)=${ZESHY_PID_LAST_LOADED_BY-}"
 #print "zeshy: passed option names=${(k)arg_options}"
 
-ZESHY_CORE_HELP_GLOBALS+='
-integer ZESHY_PID_LAST_LOADED_BY
-
-Process ID of the most recent `zsh` process in the call stack to load `zeshy`.
-'
 typeset -gi ZESHY_PID_LAST_LOADED_BY
 
 # If the caller requests not reloading zeshy when previously loaded under the
 # current shell and zeshy has indeed already been loaded, do not do so again.
 if (( ZESHY_PID_LAST_LOADED_BY == $$ )) {
-    # If zeshy has *NOT* been previously loaded under the current shell (as the
-    # the lack of get_zeshy_version() implies), throw an exception.
-    typeset -f get_zeshy_version &>/dev/null or
-        die "get_zeshy_version() not defined, so zeshy not previously loaded"
+    # If the following core function is undefined, zeshy cannot have been
+    # previously loaded for the current shell. But the current conditional
+    # implies zeshy was previously loaded for such shell! This contradiction can
+    # only mean one thing: throw an exception.
+    typeset -f :is_version_at_least &>/dev/null or
+        die 'zeshy unexpectedly not loaded (i.e., ${ZESHY_PID_LAST_LOADED_BY} is current PID '$$' but :is_version_at_least() undefined).'
 # Else, zeshy has not yet been loaded. Do so! Specifically:
 #
 # * If such shell is a login shell, establish sensible login shell settings.
@@ -1405,6 +1251,35 @@ if [[ -n "${*}" ]] {
 return 0
 
 # --------------------( WASTELANDS                         )--------------------
+#FUXME: Non-ideal. Ideally, replace this with a generic zeshy function accepting
+#two version specifiers and reporting success if the former exceeds the latter.
+#FUXME: For obvious reasons, such function should be defined and called *AFTER*
+#setting core shell options.
+#FIMXE: Wait. Such tester, while positively *BANGIN'*, is extreme overkill here.
+#But so was the prior tester. If you consider it, since there only exist a
+#finite number of prior zsh major version, the test below always reduces to:
+#
+#    if [[ "${ZSH_VERSION}" == <0-4>.* ]] {
+#        print "zeshy: zsh ${ZSH_VERSION} older than requisite version ${ZESHY_ZSH_VERSION_REQUIRED}." 1>&2
+#        return 1
+#    }
+#
+#That said, since :is_version_at_least() is awesome, shift such function to a
+#new parcel @{20-main/version}. Naturally, all other version-related functions
+#in the codebase should be shifted there as well. Sweet!
+
+# If *NOT* running under such version, print an error message to standard error
+# and return rather than exiting to avoid exiting interactive shells with non-
+# zero exit status.
+# autoload -U is-at-least
+# is-at-least ${ZESHY_ZSH_VERSION_REQUIRED} || {
+#     print "zeshy: zsh ${ZSH_VERSION} older than requisite version ${ZESHY_ZSH_VERSION_REQUIRED}." 1>&2
+#     return 1
+# }
+
+    # print "zeshy: zsh ${ZSH_VERSION} older than requisite version ${ZESHY_ZSH_VERSION_REQUIRED}." 1>&2
+    # return 1
+
     #FUXME: Pretty terrible. Let's unwind the double loop, yes? To do so, we'll
     #need to guarantee the two lists to have an equal number of items. Or
     #perhaps just iterate, defaulting not-found-items to 0?
