Improved kernel, terminal, and Gentoo handling.
Segregated Zeshy Kernel into "os/kernel/" and split off a new Zeshy
Kernel Module component. An enormous array of other minor feature
additions and regression fixes that have been brewing for a bit.

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -345,19 +345,18 @@ print_stack_trace() {
         funcstack_size=${#funcstack}
     local filename\
         funcname funcname_first\
-        frame_prefix='    \\_'\
-        ZESHY_SCRIPT_NAME='print_stack_trace'\
+        frame_prefix='    \\_'
+#       ZESHY_SCRIPT_NAME='print_stack_trace'\
 
     # Omit the current function call by starting from the second stack frame.
     # If there exists no such frame, return with failure.
     (( funcstack_size >= 2 )) || {
-        curse 'call stack empty'
+        print -- 'print_stack_trace: call stack empty.' 1>&2
         return_failure
     }
 
     # Print a prefixing header with the passed message.
-    print 2>&1
-    curse "${1:-}"
+    print -- "\nprint_stack_trace: ${1:-}" 1>&2
 
     # Print the current call stack.
     for (( i = 2; i <= funcstack_size; i++ )) {
@@ -380,7 +379,7 @@ print_stack_trace() {
         (( i == 3 )) && funcname_first="${funcname}"
 
         # Print the current stack frame to standard error.
-        print -- "${frame_prefix} ${funcname} { ${filename}: ${fileline} }" 2>&1
+        print -- "${frame_prefix} ${funcname} { ${filename}: ${fileline} }" 1>&2
 
         # Indent the next stack frame one space to the right.
         frame_prefix=" ${frame_prefix}"
@@ -420,8 +419,7 @@ print_stack_trace() {
     # declaring the function name, do *NOT* number the first printed line.
     if [[ -n "${ZESHY_IS_DEBUG-}" && -n "${funcname_first}" &&\
           "$(whence -w -- "${funcname_first}")" == *': function' ]]; then
-        print 2>&1
-        curse "${funcname_first}() failed on line ${fileline_first}."
+        print -- "\n${funcname_first}() failed on line ${fileline_first}."
         whence -f -- "${funcname_first}" | awk -vNRBAD=${fileline_first} '
 # If the function name, print a hyphen in place of the current line number
 # followed by the name.
@@ -477,7 +475,7 @@ TRAPINT() {
     #   misinterpreted as "print" command options.
     # * "${BUFFER}", the interrupted line.
     zle && print -sr -- "${BUFFER}"
-    
+
     # Arcanely uncanny bit-munging. Exit status is always a 1-byte integer.
     # Non-zero exit status with:
     #
@@ -502,16 +500,15 @@ TRAPINT() {
 # (e.g., non-interactive Zeshy functions or scripts) to the originating shell
 # (e.g., the interactive Zeshy or Zsh shell transitively responsible for running
 # the failed command).
-# 
+#
 # Unlike "setopt ERR_RETURN", this prints stack traces. Unlike "setopt
 # ERR_EXIT", this merely unwinds the call stack rather than coercively exiting
 # both intermediate subshells *AND* the originating shell.
 
 # int TRAPZERR(int signal_number = SIGZERR)
 #
-# Trap SIGZERR (i.e., signal error, as after Zsh functions or non-Zsh commands
-# returning non-zero exit statuss). This signal is Zsh-specific, as the function
-# name directly implies.
+# Trap SIGZERR, a Zsh-specific signal on non-zero exit status from Zsh builtins,
+# Zsh functions, and external commands.
 TRAPZERR() {
     # Save the return code of the prior command prior to overwriting this code
     # by printing a stack trace.
