Completed call stack output refactoring.
While thoroughly undebugged, output_call_stack_with_lists() now purports to
print call stacks with modestly aesthetic output. Time and Heaven's forfend
shall abey it.

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -606,13 +606,16 @@ function store_exception_with_status() {
     }
 
     # Store such metadata as documented above.
-    typeset -g EXCEPTION="${exception_message}"
-
-    #FIXME: Define these as fully fledged documented globals above.
-    integer -g ZESHY_EXCEPTION_STATUS="${exit_status}"
-    typeset -ag ZESHY_EXCEPTION_FUNCSTACK ZESHY_EXCEPTION_FUNCFILETRACE
-    ZESHY_EXCEPTION_FUNCSTACK=( "${funcstack[@]}" )
-    ZESHY_EXCEPTION_FUNCFILETRACE=( "${funcfiletrace[@]}" )
+    typeset -g\
+        EXCEPTION="${exception_message}"\
+        ZESHY_EXCEPTION_STATUS="${exit_status}"
+    typeset -ag\
+        ZESHY_EXCEPTION_FUNCSTACK\
+        ZESHY_EXCEPTION_FUNCFILETRACE\
+        ZESHY_EXCEPTION_FUNCSOURCETRACE
+    ZESHY_EXCEPTION_FUNCSTACK=(       "${funcstack[@]}" )
+    ZESHY_EXCEPTION_FUNCFILETRACE=(   "${funcfiletrace[@]}" )
+    ZESHY_EXCEPTION_FUNCSOURCETRACE=( "${funcsourcetrace[@]}" )
 }
 
 ZESHY_CORE_HELP_ALIASES+='
@@ -709,7 +712,7 @@ function print_exception_if_unhandled() {
         # status (i.e., ${TRY_BLOCK_ERROR}) to report such status to the shell.
         # See catch_exception_matching_glob_if_found() for further details.
         if (( ${+EXCEPTION} && ZESHY_TRY_LEVEL[${SHLVL}] == 0 )) {
-            print_exception
+            print_exception_unhandled
 #           print_exception_with_status "${EXCEPTION}" "${TRY_BLOCK_ERROR}"
 
             #FIXME: Don't forget to erase the other ${ZESHY_EXCEPTION_*} globals
@@ -725,24 +728,18 @@ function print_exception_if_unhandled() {
     }
 }
 
-#FIXME: Define new functions
-#print_call_stack_with_funcstack_and_funcfiletrace() and
-#print_exception_call_stack(). The former is the lowest-level function for
-#doing so; the latter calls the former with list globals storing such call
-#stacks for the currently thrown exception. Likewise, print_call_stack() should
-#call print_call_stack_with_funcstack_and_funcfiletrace() with the current such
-#globals. Sweet, yes?
 ZESHY_CORE_HELP_FUNCTIONS+='
-[stderr: string] print_exception(void)
+[stderr: string] print_exception_unhandled(void)
 
 Print the currently thrown exception to standard error. See
 store_exception_with_status() for further details.
 '
-function print_exception() {
+function print_exception_unhandled() {
     #FIXME: This requires a *MAJOR* simplification. For one, this function is
     #no longer passed anything and hence should reference globals. For another,
     #we really want to reduce the series of printer calls below to a single
     #printer function. It's time to just do it.
+    #FIXME: Actually, two printer calls: 
 
     # Redirect all output printed below to standard error. Yes, a single
     # suffixing "} 1>&2" actually suffices. You rock, zsh! (Sometimes.)
@@ -756,11 +753,11 @@ function print_exception() {
         # do so efficiently, search from the end (i.e., root) of such stack; if
         # the first matching caller is not the first, a witch! As below, return
         # success to avoid triggering TRAPZERR and hence another exception.
-        if (( ${funcstack[(I)print_exception_with_status]} != 1 )) {
+        if (( ${funcstack[(I)print_exception_unhandled]} != 1 )) {
             # Print a synopsis of such exception.
             print
-            print "zeshy: exception handler threw exception: ${*}"
-            print "zeshy: exception handler failed with exit status ${exit_status}"
+            print "zeshy: exception handler threw exception: ${EXCEPTION-}"
+            print "zeshy: exception handler failed with exit status ${TRY_BLOCK_ERROR-1}"
             print "zeshy: current call stack:"
 
             # Print a "mini" stack trace.
@@ -773,39 +770,48 @@ function print_exception() {
             return 0
         }
 
-        # Validate sanity. See is_integer_nonnegative() for details.
-        (( # )) || die 'Expected optional error message and one exit status.'
-        local exit_status="${@[-1]}"
-        { [[ "${exit_status}" == <-> ]] &&
-          (( 0 <= exit_status && exit_status <= 255 )) } ||
-            die "Exit status \"${exit_status}\" not an integer in [0, 255]."
+        # Validate sanity.
+        (( # == 0 )) || die 'Expected no arguments.'
+#        # See is_integer_nonnegative() for details.
+#        (( # )) || die 'Expected optional error message and one exit status.'
+#        local exit_status="${@[-1]}"
+#        { [[ "${exit_status}" == <-> ]] &&
+#          (( 0 <= exit_status && exit_status <= 255 )) } ||
+#            die "Exit status \"${exit_status}\" not an integer in [0, 255]."
 
         # Pop such status from the list of passed arguments.
-        set -- ${@[1,-2]}
+#        set -- ${@[1,-2]}
 
         # If called directly from the command line, no such exception exists.
         (( ${#funcstack} >= 2 )) || die 'No exception thrown.'
 
+        #FIXME: O.K.; so, fold the current print_error_status() function into a
+        #new print_exception() function and excise print_error_status(). For
+        #simplicity, in fact, rename all existing "print_error" functionality to
+        #"print_exception". (If we like, we can later differentiate a new
+        #print_error() function from such functionality.)
+
         # If such message exists, print such message.
         if (( # )) {
-            # If print_error() is defined, call such function.
-            if { typeset -f print_error &>/dev/null } {
-                print_error "${@}"
+            # If print_exception() is defined, call such function.
+            if { typeset -f print_exception &>/dev/null } {
+                print_exception "${@}"
             # Else, print such message with a one-liner.
             } else {
-                print "zeshy: ${*}"
+                print "zeshy: ${EXCEPTION}"
+                print "zeshy: failed with exit status ${ZESHY_EXCEPTION_STATUS-1}"
             }
         }
 
         # Print a description of the passed non-zero exit status.
         # If print_exception_message() is defined, call such function.
-        if { typeset -f print_error_status &>/dev/null } {
-            print_error_status "${exit_status}"
-        # Else, print such message with a one-liner.
-        } else {
-            print
-            print "zeshy: failed with exit status ${exit_status}"
-        }
+#        if { typeset -f print_error_status &>/dev/null } {
+#            print_error_status "${exit_status}"
+#        # Else, print such message with a one-liner.
+#        } else {
+#            print
+#            print "zeshy: failed with exit status ${exit_status}"
+#        }
 #       print "printed exit status"
 
         # If either the current user's zeshy configuration requests printing
@@ -814,15 +820,16 @@ function print_exception() {
         if (( ${ZESHY_ERROR_HANDLER_IS_PRINTING_CALL_STACK-0} +\
               ${ZESHY_IS_DEBUG-0} )) {
 #           print "printing call stack"
-            # If print_call_stack() is defined, call such function.
-            if { typeset -f print_call_stack &>/dev/null } {
-#               print "calling print_call_stack()"
-                print_call_stack
+            # If output_exception_call_stack() is defined, call such function.
+            if { typeset -f output_exception_call_stack &>/dev/null } {
+#               print "calling output_call_stack()"
+                output_exception_call_stack
             # Else, print such stack with an implementation distilled from
-            # print_call_stack(). See such function for further details.
+            # output_exception_call_stack(). See such function for further
+            # details.
             } else {
-                integer funcstack_size=${#funcstack} i caller_line
                 local frame_prefix='    \\_' filename caller_name
+                integer funcstack_size=${#funcstack} i caller_line
 #               print "printing stack frame"
 
                 for (( i = 1; i <= funcstack_size; i++ )) {
@@ -831,7 +838,7 @@ function print_exception() {
                        filename="${funcfiletrace[${i}]%:*}"
 
                     if { typeset -f -- "${caller_name}" &>/dev/null } {
-                        caller_name="${caller_name}()"
+                        caller_name+='()'
                     }
                     print -r --\
                         "${frame_prefix} ${caller_name} { ${filename}: ${caller_line} }"
@@ -883,7 +890,7 @@ metadata will be printed to standard error and failure returned from such stack.
 Such metadata includes the following:
 
 * If boolean ${ZESHY_ERROR_HANDLER_IS_PRINTING_CALL_STACK} is enabled, a stack
-  trace of the current call path. See print_call_stack() for further details.
+  trace of the current call path. See output_call_stack() for further details.
 * If boolean ${ZESHY_ERROR_HANDLER_IS_PRINTING_DOCUMENTATION} is enabled,
   documentation for the function or script throwing such exception. See
   print_exception_thrower_documentation() for further details.
@@ -1539,7 +1546,7 @@ if [[ -n "${*}" ]] {
 #   is_zeshy_debug_and print "zeshy: sourcing \"${@}\"..."
 
     #FIXME: The output is still subpar. We *REALLY* just want to slightly tweak
-    #print_call_stack() so that such function omits the first element on the
+    #output_call_stack() so that such function omits the first element on the
     #stack if such element is the absolute path of this "main" script. Very
     #simple. Just need to do it, as ever! Then, remove the "or die..." below.
 
@@ -1561,6 +1568,14 @@ if [[ -n "${*}" ]] {
 return 0
 
 # --------------------( WASTELANDS                         )--------------------
+#FUXME: Define new functions
+#output_call_stack_with_funcstack_and_funcfiletrace() and
+#print_exception_call_stack(). The former is the lowest-level function for
+#doing so; the latter calls the former with list globals storing such call
+#stacks for the currently thrown exception. Likewise, output_call_stack() should
+#call output_call_stack_with_funcstack_and_funcfiletrace() with the current such
+#globals. Sweet, yes?
+
 # Main entry point into zeshy, a shell programming language implemented in pure
 # zsh. This script initializes the current zsh environment with support for
 # zeshy.
@@ -1606,7 +1621,7 @@ return 0
     #
     #* If function 
 
-#FUXME: Rename print_call_stack() to print_call_stack(). I'm not really
+#FUXME: Rename output_call_stack() to output_call_stack(). I'm not really
 #concerned that such function fails to page output. It does pretty much
 #everything else expected of a high-level printer, so... There you go.
 #If this function was called from within the topmost `always {...}` block of the
