Corrected numerous additional regressions.
Nonetheless, zeshy startup remains broken. I suspect the issue to lie
with compilation of documentation globals, but only the morrow's grim
light will bear witness to a dismal truth.

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -474,17 +474,25 @@ function die_with_exit_status() {
         # do so efficiently, search from the end (i.e., root) of such stack; if
         # the first matching caller is not the first, a witch! As below, return
         # success to avoid triggering TRAPZERR and hence another exception.
-        (( ${funcstack[(I)die_with_exit_status]} == 1 )) || {
-            # For safety, print a mini rather than full stack trace.
+        if (( ${funcstack[(I)die_with_exit_status]} == 1 )) {
+            # Print a synopsis of such exception.
             print
             print "zeshy: exception handler threw exception: ${*}"
             print "zeshy: exception handler failed with exit status ${exit_status}"
-            print "zeshy: current call stack: ${funcstack[*]}"
+            print "zeshy: current call stack:"
+
+            # Print a "mini" stack trace.
+            local function_name
+            for   function_name ("${funcstack[@]}") {
+                print "  \\_ ${function_name}()"
+            }
+
+            # Return failure.
             return 0
         }
 
         # Validate passed arguments. See is_integer_nonnegative() for details.
-        (( # )) || die 'expected optional error messages and one exit status'
+        (( # )) || die 'expected optional error message and one exit status'
         local exit_status="${@[-1]}"
         [[ "${exit_status}" == <-> ]] ||
             die "exit status \"${exit_status}\" not a positive integer"
@@ -496,7 +504,7 @@ function die_with_exit_status() {
         (( ${#funcstack} >= 2 )) || die 'exception not thrown'
 
         # If such message exists, print such message.
-        (( # )) &&
+        if (( # )) {
             # If print_error() is defined, call such function.
             if { typeset -f print_error &>/dev/null } {
                 print_error "${@}"
@@ -504,6 +512,7 @@ function die_with_exit_status() {
             } else {
                 print "zeshy: ${*}"
             }
+        }
 
         # Print a blank line.
         print
@@ -518,12 +527,11 @@ function die_with_exit_status() {
         }
 #       print "printed exit status"
 
-        # If the current user's zeshy configuration requests printing stack
-        # traces on exceptions, do so. If the zeshy function to do so has not
-        # yet been defined, attempt a stub implementation... Printing such
-        # traces is essential *ESPECIALLY* at zeshy bootstrap, before such
-        # function is autoloaded from zeshy's user digest file.
-        [[ -n "${ZESHY_ERROR_HANDLER_IS_PRINTING_CALL_STACK-}" ]] && {
+        # If either the current user's zeshy configuration requests printing
+        # stack traces on exceptions *OR* zeshy is currently being debugged,
+        # print traces.
+        if (( ${ZESHY_ERROR_HANDLER_IS_PRINTING_CALL_STACK-0} +\
+              ${ZESHY_IS_DEBUG-0} )) {
 #           print "printing call stack"
             # If print_call_stack() is defined, call such function.
             if { typeset -f print_call_stack &>/dev/null } {
@@ -556,7 +564,7 @@ function die_with_exit_status() {
     # zeshy functions in catch logic.
     } always {
         # If an exception was thrown...
-        (( ${+EXCEPTION} )) &&
+        if (( ${+EXCEPTION} )) {
             # ...and if canonical function catch() is defined, catch such
             # exception and print a warning.
             if { typeset -f catch &>/dev/null } {
@@ -566,17 +574,19 @@ function die_with_exit_status() {
                 # rather than "catch '*'". However, note that the former fails
                 # with obscure errors when such alias is (either intentionally
                 # or unintentionally) deleted. For safety, quote such glob.
-                catch '*' &&
+                if { catch '*' } {
                     if [[ -n "${CAUGHT-}" ]] {
                         print "zeshy: exception handler threw exception \"${CAUGHT}\""
                     # Unfortunately, catch() may not set such global! *shrug*
                     } else {
                         print "zeshy: exception handler failed with non-zero exit status"
                     }
+                }
             # ...else, something awful. Print a despicable warning.
             } else {
                 print 'zeshy: catch() undefined, probably as exception handler threw exception'
             }
+        }
     } 1>&2
 
     # Return success to avoid triggering TRAPZERR and hence another exception.
@@ -670,7 +680,7 @@ local -a arg_shell_options
 # "--no-zeshy-dot-dir" to "--zeshy-dot-dir", thus implicitly setting the latter
 # to the empty string on parsing the former.
 zparseopts -M -D -E -A arg_options --\
-    h=-help -help \
+    h=-help -help\
     v=-verbose -verbose\
     -recompile-digest\
     -recompile-digest-if-zeshy-home-changed\
@@ -686,8 +696,8 @@ zparseopts -M -D -E -A arg_options --\
 ZESHY_CORE_HELP_GLOBALS+='
 string ZESHY_HOME
 
-Absolute path of the system-wide directory containing the codebase for the
-currently installed version of `zeshy`.
+Absolute path of the (typically system-wide) directory containing the `zeshy`
+codebase for the currently installed version of `zeshy`.
 '
 typeset -g ZESHY_HOME
 [[ -n "${ZESHY_HOME}" ]] || ZESHY_HOME="$(print -- "${0:h}"(:A))" || {
@@ -698,8 +708,8 @@ typeset -g ZESHY_HOME
 ZESHY_CORE_HELP_GLOBALS+='
 string ZESHY_OVERLAY_DIR
 
-Absolute path of the system-wide directory containing all `zeshy` scripts in the
-codebase for the currently installed version of `zeshy`.
+Absolute path of the (typically system-wide) directory containing all `zsh`
+scripts in the `zeshy` codebase for the currently installed version of `zeshy`.
 '
 # While currently synonymous with ${ZESHY_HOME}, it's depressingly easy to
 # conceive of situations in which the two differ.
@@ -821,11 +831,11 @@ Absolute path of the user-specific file caching `zeshy`\''s current version.
 typeset -g ZESHY_USER_VERSION_FILE="${ZESHY_USER_CACHE_DIR}/version"
 
 # ....................{ OPTIONS ~ startup                  }....................
-#FIXME: Zeshy's install script should replace such string with a value
+#FIXME: zeshy's install script should replace such string with a value
 #corresponding to whether or not a release or debug build is being installed.
 
 ZESHY_CORE_HELP_GLOBALS+='
-boolean ZESHY_IS_DEBUGGING
+boolean ZESHY_IS_DEBUG
 
 If true, enable expensive developer-specific logic. This includes:
 
@@ -835,15 +845,14 @@ If true, enable expensive developer-specific logic. This includes:
   `zeshy` developers, such recompilation is essential to fast development. For
   `zeshy` non-developers, detecting such changes is unnecessarily wasteful.
 '
-# zeshy's installation script defaults such boolean to "true" if installing a
-# debug build and to the empty string (i.e., false) otherwise. When uninstalled
-# (e.g., when run from a git repository), the non-empty placeholder value
-# effectively defaults such boolean to "true".
-typeset -g ZESHY_IS_DEBUGGING="${ZESHY_IS_DEBUGGING-@ZESHY_IS_DEBUGGING@}"
+# zeshy's installation script defaults such boolean to true if installing a
+# debug build and false otherwise. When uninstalled (e.g., run from a git
+# repository), such boolean defaults to true.
+integer -g ZESHY_IS_DEBUG=1 #@ZESHY_IS_DEBUG@
 
 # If debugging zeshy, forcefully enable debug-specific options *BEFORE* testing
 # whether or not at least one such option was passed.
-if [[ -n "${ZESHY_IS_DEBUGGING}" ]] {
+if (( ZESHY_IS_DEBUG )) {
     arg_options[--compile-digest-if-zeshy-home-changed]=
     arg_options[--verbose]=
 }
@@ -947,7 +956,7 @@ if (( ZESHY_PID_LAST_LOADED_BY == $$ )) {
     # the lack of get_zeshy_version() implies), throw an exception.
     typeset -f get_zeshy_version &>/dev/null or
         die "get_zeshy_version() not defined, so zeshy not previously loaded"
-# Otherwise, zeshy has not yet been loaded. Do so! Specifically:
+# Else, zeshy has not yet been loaded. Do so! Specifically:
 #
 # * If such shell is a login shell, establish sensible login shell settings.
 #   See set_shell_login_defaults() for further details.
@@ -967,6 +976,13 @@ if (( ZESHY_PID_LAST_LOADED_BY == $$ )) {
     [[ -o login ]] && source -- "${ZESHY_HOME}/login"
 
     # Autoload zeshy's user digest file, recompiling such file if needed.
+    #
+    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+    #Note: while such autoload *DOES* render all compiled zeshy functions
+    #immediately callable, calling most such functions (e.g., print_message())
+    #is inherently unsafe as zeshy has yet to be started up and hence has yet
+    #to define aliases and globals referenced by such functions.
+    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     source -- "${ZESHY_HOME}/digest"
 
     #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@@ -991,7 +1007,7 @@ if (( ZESHY_PID_LAST_LOADED_BY == $$ )) {
     #
     #     >>> is_list_nonempty ZESHY_GLOBAL_NAMES and  # must be "*" rather than "@"
     #     ...     undefine_variable_from "${ZESHY_GLOBAL_NAMES[*]}"
-    is_zeshy_verbose_and print_message 'zeshy: starting up...'
+    is_zeshy_verbose_and print 'zeshy: starting up...'
     if [[ -n "${ZESHY_GLOBAL_NAMES-}" ]] {
         typeset +r -- "${ZESHY_GLOBAL_NAMES[@]}"
         unset      -- "${ZESHY_GLOBAL_NAMES[@]}"
@@ -1000,7 +1016,7 @@ if (( ZESHY_PID_LAST_LOADED_BY == $$ )) {
     # Startup zeshy, having recompiled zeshy's user digest file above and hence
     # defined all autoloads applicable to such user.
     startup_zeshy
-    is_zeshy_verbose_and print_message 'zeshy: started up.'
+    is_zeshy_verbose_and print 'zeshy: started up.'
 
     # Ensure this conditional evaluates to true on the next attempt to load
     # zeshy under the current shell by setting such process ID to that of this
@@ -1069,22 +1085,22 @@ unset --\
 }
 
 # ....................{ PROFILING ~ end                    }....................
-# If debugging Zeshy, print a human-readable synopsis of Zeshy startup time. For
+# If debugging zeshy, print a human-readable synopsis of zeshy startup time. For
 # accuracy, minimize shell overhead by:
 #
 # * Printing such synopsis as a single statement.
-# * Avoiding calling Zeshy-specific functions to do so.
+# * Avoiding calling zeshy-specific functions to do so.
 is_zeshy_verbose_and printf\
     "zeshy: startup in %.4f seconds (wall clock)\n"\
     $(( EPOCHREALTIME - ZESHY_STARTUP_TIME_SECONDS ))
 
 # ....................{ ARGUMENTS                          }....................
-# If the caller passed at least one non-option, non-empty argument (i.e.,
-# neither prefixed by "-" or expanding to the empty string), source the first
-# such argument as the path of a Zeshy script and pass such script all remaining
-# such arguments. To avoid unfairly budgeting the time spent sourcing such
-# script to Zeshy startup, do so *AFTER* printing Zeshy's startup time.
-is_string_nonempty "${*}" and {
+# If the caller passed at least one nonempty non-option argument (i.e., an
+# argument neither prefixed by "-" or expanding to the empty string), source the
+# first such argument as the path of a zeshy script and pass such script all
+# remaining such arguments. To avoid unfairly budgeting the time spent sourcing
+# such script to zeshy startup, do so *AFTER* printing zeshy's startup time.
+if is -n "${*}" si {
 #   is_zeshy_verbose_and print "zeshy: sourcing \"${@}\"..."
     source -- "${@}"
 }
@@ -1096,6 +1112,15 @@ is_string_nonempty "${*}" and {
 return_true
 
 # --------------------( WASTELANDS                         )--------------------
+#FUXME: Actually use such alias in lieu of current is_zeshy_verbose_and() use.
+#is_zeshy_verbose_and command="print -r -- 'zeshy: 
+
+#FUXME: Rename to ${ZESHY_IS_DEBUG}. ${ZESHY_IS_DEBUG} 'tis a silly name.
+
+# Printing traces is essential, particularly at zeshy
+        # bootstrap (before such # function is autoloaded from zeshy's user digest file.
+#If the zeshy function to do so has not
+        # yet been defined, attempt a stub implementation... 
 # Explicitly load only the subset of requisite zsh modules (i.e., C-based shared
 # libraries bundled with zsh) for which no appropriate autoloadable function
 # exists. Since all other requisite zsh modules supply autoloadable functions
@@ -1279,14 +1304,14 @@ return_true
 #else alias is_zeshy_verbose_and='true ||'
 #fi
 #FUXME: This is terrible. I've since stumbled on the obvious solution: restore
-#global boolean ${ZESHY_IS_DEBUGGING}, but do so *AT THE TOP OF THIS FILE*
+#global boolean ${ZESHY_IS_DEBUG}, but do so *AT THE TOP OF THIS FILE*
 #rather than in the configuration file. Default such global as follows:
 #
-#    ZESHY_IS_DEBUGGING=${ZESHY_IS_DEBUGGING-'@ZESHY_IS_DEBUGGING@'}
+#    ZESHY_IS_DEBUG=${ZESHY_IS_DEBUG-'@ZESHY_IS_DEBUG@'}
 #
 #So, the caller can override such global which defaults to non-empty. On
 #installation, Zeshy's install script should (obviously) delete the hard-coded
-#'@ZESHY_IS_DEBUGGING@' (i.e., replace such string with the empty string).
+#'@ZESHY_IS_DEBUG@' (i.e., replace such string with the empty string).
 #Perfectimo.
 #detecting an upgrade to new versions of Zeshy.
 # Absolute paths for Zeshy-specific directories and files. See commentary below.
@@ -1321,7 +1346,7 @@ return_true
 # defined at the top of this component to run the passed command instead.
 #FUXME: Rename to ZESHY_USER_CACHE_DIGEST_FILE.
 #FUXME: Rename to ZESHY_USER_CACHE_VERSION_FILE.
-#is -n "${ZESHY_IS_DEBUGGING-}" si and printf\
+#is -n "${ZESHY_IS_DEBUG-}" si and printf\
 #FUXME: Parse ${arg_options} and ${arg_shell_commands} here. Test a bit, of course.
 
 #   typeset -p ZESHY_COLOR
@@ -1367,13 +1392,13 @@ return_true
 #typeset -Agx ZESHY_FUNCTION_NAME_TO_DOC_STRING
 #    ZESHY_FUNCTION_NAME_TO_DOC_STRING[${1}]="${2}"
 
-#is_boolean_true ZESHY_IS_DEBUGGING and printf\
+#is_boolean_true ZESHY_IS_DEBUG and printf\
 #FUXME: Source all remaining arguments via source_shell_script().
 # Source such arguments *AFTER* printing Zeshy's startup time to avoid
 # incrementing such time by the time required to source such arguments.
-#FUXME: If ${ZESHY_IS_DEBUGGING}, print out a brief line printing timing statistics:
+#FUXME: If ${ZESHY_IS_DEBUG}, print out a brief line printing timing statistics:
 #namely, how quickly Zeshy started up. *ALWAYS* start timing as the first line
-#of this file, since we won't have access to ${ZESHY_IS_DEBUGGING} for a bit of
+#of this file, since we won't have access to ${ZESHY_IS_DEBUG} for a bit of
 #time. (What's the best way to perform shell profiling? Google us up.) Hmm;
 #don't adopt the "zprof" solution, which imposes a bit too much overhead. We
 #want a no-overhead -- the "times" command looks particularly helpful. Is there
