Substantially improved terminal color support.
Colorized list_interactive_aliases() to demonstrate such support.

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -880,59 +880,6 @@ function source_zeshy_script() {
     }
 }
 
-set_function_documentation load_zeshy '
-void load_zeshy(void)
-
-Load Zeshy into the current zsh shell. Specifically:
-
-* If such shell is a login shell, establish sensible login shell settings.
-  See set_shell_login_defaults() for further details.
-* Source all Zeshy configuration files.
-* If no Zeshy digest file has been compiled or such file requires
-  recompilation (e.g., due to upgrading Zeshy, editing Zeshy configuration
-  files, or installing new command or uninstalling old commands from the
-  current ${PATH}), recompile such digest.
-* Prepend such digest to the current ${FPATH}, thus effectively loading all
-  Zeshy functions. For efficiency, the Zsh autoload system delays defining
-  these functions until the first call to such functions.
-* Perform all Zeshy startup tasks, including:
-  * Defining all Zeshy aliases and globals.
-  * Calling all user-defined startup hooks.
-'
-function load_zeshy() {
-    # Validate passed arguments.
-    (( # == 0 )) || die 'expected no arguments'
-
-    # If the current shell is a login shell, set login-specific behavior.
-    [[ -o login ]] && source_zeshy_script login
-
-    # Source all Zeshy configuration files and compile and load Zeshy's digest.
-    source_zeshy_script setup autoload
-
-    # Undefine all globals defined by such recompilation. The reasons are subtle but
-    # the logic flows like butter. Zeshy may (and often does) declare globals to be
-    # read-only. Sadly, Zsh fails on attempting to redefine read-only globals. Since
-    # the subsequent call to startup_zeshy() and hence startup_zeshy_globals() does
-    # just that, undefine Zeshy-specific globals prior to such calls. Do so in the
-    # root global context (i.e., in this component outside of functions) to
-    # guarantee expected behavior. "'tis all a tad silly and worm-bitten, but such
-    # is life in the tranche of code trenches."
-    #
-    # Since Zsh never fails on redefining aliases or functions, do not bother
-    # undefining either. We could, but there's little point (or profit) in it.
-    [[ -n "${ZESHY_GLOBAL_NAMES-}" ]] && {
-    #   print -l "===ZESHY_GLOBAL_NAMES===" "${ZESHY_GLOBAL_NAMES[@]}"
-        typeset +r -- "${ZESHY_GLOBAL_NAMES[@]}"
-        unset      -- "${ZESHY_GLOBAL_NAMES[@]}"
-    #   print "glob: ${ZESHY_GLOB_SHELL_EMULATABLE_DIRECTLY}"
-    }
-
-    # Initialize Zeshy, having recompiled the Zeshy digest file above and hence
-    # defined all autoloads applicable to the current user.
-    startup_zeshy
-}
-
-# ....................{ LOAD ~ reload                      }....................
 # If sourcing the current script under Zsh startup logic (e.g., from a Zsh
 # script with basename matching either ".zlogin", ".zprofile", or ".zshrc"),
 # prevent Zsh from reloading Zeshy if already loaded earlier during such logic.
@@ -964,21 +911,67 @@ function load_zeshy() {
 #print "zeshy: process ID (cached.)=${ZESHY_PID_LAST_LOADED_BY-}"
 #print "zeshy: passed option names=${(k)arg_options}"
 
-# If the caller requests we not reload Zeshy if previously loaded by the current
-# shell and (indeed!) Zeshy was loaded by such shell, avoid doing so again.
+# If the caller requests not reloading Zeshy when previously loaded under the
+# current shell and Zeshy has indeed already been loaded, do not do so again.
 if (( ZESHY_PID_LAST_LOADED_BY == $$ )); then
     # If Zeshy has *NOT* been previously loaded under the current shell (as the
     # the lack of get_zeshy_version() implies), throw an exception.
     typeset -f get_zeshy_version &>/dev/null or
         die "get_zeshy_version() not defined, so Zeshy not previously loaded"
-# Otherwise, Zeshy has not yet been loaded.
+# Otherwise, Zeshy has not yet been loaded. Do so! Specifically:
+#
+# * If such shell is a login shell, establish sensible login shell settings.
+#   See set_shell_login_defaults() for further details.
+# * Source all Zeshy configuration files.
+# * If no Zeshy digest file has been compiled or such file requires
+#   recompilation (e.g., due to upgrading Zeshy, editing Zeshy configuration
+#   files, or installing new command or uninstalling old commands from the
+#   current ${PATH}), recompile such digest.
+# * Prepend such digest to the current ${FPATH}, thus effectively loading all
+#   Zeshy functions. For efficiency, the Zsh autoload system delays defining
+#   these functions until the first call to such functions.
+# * Perform all Zeshy startup tasks, including:
+#   * Defining all Zeshy aliases and globals.
+#   * Calling all user-defined startup hooks.
 else
-    # Do so.
-    load_zeshy
+    # If the current shell is a login shell, set login-specific behavior.
+    [[ -o login ]] && source_zeshy_script login
 
-    # To test the prior conditional on the next attempt to load Zeshy under the
-    # current shell, set the process ID to that of this shell *AFTER*
-    # successfully loading Zeshy.
+    # Source all Zeshy configuration files and compile and load Zeshy's digest.
+    source_zeshy_script setup autoload
+#   typeset -p ZESHY_COLOR
+
+    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+    #Note: this *MUST* be performed from a global rather than function context.
+    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+    #
+    # Undefine all globals defined by such recompilation. The reasons are subtle but
+    # the logic flows like butter. Zeshy may (and often does) declare globals to be
+    # read-only. Sadly, Zsh fails on attempting to redefine read-only globals. Since
+    # the subsequent call to startup_zeshy() and hence startup_zeshy_globals() does
+    # just that, undefine Zeshy-specific globals prior to such calls. Do so in the
+    # root global context (i.e., in this component outside of functions) to
+    # guarantee expected behavior. "'tis all a tad silly and worm-bitten, but such
+    # is life in the tranche of code trenches."
+    #
+    # Since Zsh never fails on redefining aliases or functions, do not bother
+    # undefining either. We could, but there's little point (or profit) in it.
+    [[ -n "${ZESHY_GLOBAL_NAMES-}" ]] && {
+    #   print -l "===ZESHY_GLOBAL_NAMES===" "${ZESHY_GLOBAL_NAMES[@]}"
+        typeset +r -- "${ZESHY_GLOBAL_NAMES[@]}"
+        unset      -- "${ZESHY_GLOBAL_NAMES[@]}"
+    #   print "glob: ${ZESHY_GLOB_SHELL_EMULATABLE_DIRECTLY}"
+    }
+
+    # Initialize Zeshy, having recompiled the Zeshy digest file above and hence
+    # defined all autoloads applicable to the current user.
+#   typeset -gAx ZESHY_COLOR
+    startup_zeshy
+#   typeset -p ZESHY_COLOR
+
+    # Ensure this conditional evaluates to true on the next attempt to load
+    # Zeshy under the current shell by setting such process ID to that of this
+    # shell after successfully loading Zeshy. (The "after" is key here!)
     ZESHY_PID_LAST_LOADED_BY=$$
 fi
 
@@ -1068,6 +1061,24 @@ is -n "${ZESHY_IS_DEBUGGING-}" si and printf\
 return_true
 
 # --------------------( WASTELANDS                         )--------------------
+# Unfortunately, at least the sourcing of Zeshy component "autoload" must be
+# performed from a global rather than function context. The reason is, of course, subtle:
+# zsh fails
+# to to properly unset globals declared from a function transitively called
+    # Do so.
+#   load_zeshy
+#   typeset -p ZESHY_COLOR
+
+#set_function_documentation load_zeshy '
+#void load_zeshy(void)
+#
+#Load Zeshy into the current zsh shell. '
+#function load_zeshy() {
+#    # Validate passed arguments.
+#    (( # == 0 )) || die 'expected no arguments'
+
+#FUXME: O.K.; interesting. This *CAN'T* be a function. Fair and simple enough.
+#typeset -gAx ZESHY_COLOR
     #FUXME: Kill this. Kill this soon. (You know you want to...)
 #   setup_zeshy
     # Delay validating passed arguments aside from the number of such arguments
