Substantially improved argument parsing aliases.
Added and began calling document_alias(). Improved POSIX path
operations, particularly copy, move, and remove. Added an empty
"path/posix/make" component, to be implemented shortly.

"The heady trough that tread
 The bucket of the head
 Doth murmur sweet abandoned blood,
 Sloth-fed,
 Worm-urned, and
 Dias-spurned of
 Sickly benedictions.

 Maledictions fiery-formed,
 Ergot and misbegotten faery-veriformed,
      trod
 At dawn's misfired grotto
 Of the antetemple-spawned awning."

diff --git a/src/setup b/src/setup
--- a/src/setup
+++ b/src/setup
@@ -60,11 +60,10 @@ zero only if such file was outdated at shell startup.
 export -i ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME
 
 # ....................{ ALIASES                            }....................
-# Zeshy configuration files declare only global exports. While such files can
-# declare locals and non-exported globals with traditional Zsh primitives (e.g.,
+# Zeshy's user configuration files only export globals. While such files can
+# declare locals and non-exported globals via traditional zsh primitives (e.g.,
 # "typedef -Fr"), avoid promoting such bad behavior by aliasing human-readable
-# names to such primitives. Delay defining all remaining Zeshy aliases to the
-# main Zeshy codebase.
+# names to such primitives. Defer defining further aliases to Zeshy's codebase.
 alias string_global_export='export'
 alias boolean_global_export='export'
 alias integer_global_export='export -i'
@@ -75,50 +74,7 @@ alias list_set_global_export='export -Ua'
 # "export -A" fails with error; "export -a", however, succeeds. *massive shrug*
 alias map_global_export='typeset -Agx'
 
-# ....................{ SETUP                              }....................
-set_function_documentation setup_zeshy '
-void setup_zeshy(void)
-
-Prepare Zeshy for subsequent startup and possible user digest file compilation.
-Specifically, ascertain whether such file requires compilation and source all
-applicable user configuration files.
-'
-function setup_zeshy() {
-    # Validate sanity.
-    (( # == 0 )) || die 'expected no arguments'
-
-    # Unless loading Zeshy's user directory, return silently.
-    [[ -n "${ZESHY_DOT_DIR}" ]] || return 0
-
-    # Record whether Zeshy's user digest file is outdated.
-    is_zeshy_digest_outdated && ZESHY_DOT_DIGEST_FILE_IS_OUTDATED=true
-
-    # Call the corresponding setup function.
-    if [[ -z "${ZESHY_DOT_DIGEST_FILE_IS_OUTDATED}" ]]
-    then setup_zeshy_digest_uptodate
-    else setup_zeshy_digest_outdated
-    fi
-
-    # Undefine lower-level documentators, hereafter replaced by the previously
-    # defined higher-level documentators.
-    unfunction\
-        set_alias_documentation\
-        set_function_documentation\
-        set_global_documentation
-
-    # Source Zeshy's user configuration.
-    setup_zeshy_configuration
-}
-
 # ....................{ TESTERS                            }....................
-#FIXME: Should probably be pushed into "main". Ideally, this could allow us to
-#obsolete the lower-level set_*_documentation() family of functions in favor of
-#the higher-level document_*() family of functions. It will increase the size of
-#"main", but probably not by quite as much as thought -- after all, we'd also be
-#removing a sizable block of existing functionality: set_*_documentation().
-#Naturally, this requires moving document_*() and all conditional logic defining
-#such functions from here to "main".
-
 set_function_documentation is_zeshy_digest_outdated '
 boolean is_zeshy_digest_outdated(void)
 
@@ -258,6 +214,41 @@ function is_zeshy_digest_outdated() {
         ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME ))
 }
 
+# ....................{ SETUP                              }....................
+set_function_documentation setup_zeshy '
+void setup_zeshy(void)
+
+Prepare Zeshy for subsequent startup and possible user digest file compilation.
+Specifically, ascertain whether such file requires compilation and source all
+applicable user configuration files.
+'
+function setup_zeshy() {
+    # Validate sanity.
+    (( # == 0 )) || die 'expected no arguments'
+
+    # Unless loading Zeshy's user directory, return silently.
+    [[ -n "${ZESHY_DOT_DIR}" ]] || return 0
+
+    # Record whether Zeshy's user digest file is outdated.
+    is_zeshy_digest_outdated && ZESHY_DOT_DIGEST_FILE_IS_OUTDATED=true
+
+    # Call the corresponding setup function.
+    if [[ -z "${ZESHY_DOT_DIGEST_FILE_IS_OUTDATED}" ]]
+    then setup_zeshy_digest_uptodate
+    else setup_zeshy_digest_outdated
+    fi
+
+    # Undefine lower-level documentators, hereafter replaced by the previously
+    # defined higher-level documentators.
+    unfunction\
+        set_alias_documentation\
+        set_function_documentation\
+        set_global_documentation
+
+    # Source Zeshy's user configuration.
+    setup_zeshy_configuration
+}
+
 # ....................{ SETUP ~ digest                     }....................
 set_function_documentation setup_zeshy_digest_uptodate '
 void setup_zeshy_digest_uptodate(void)
@@ -275,8 +266,6 @@ function setup_zeshy_digest_uptodate() {
     alias document_global=':'
 }
 
-#FIXME: Define document_alias().
-
 set_function_documentation setup_zeshy_digest_outdated '
 void setup_zeshy_digest_outdated(void)
 
@@ -287,7 +276,73 @@ function setup_zeshy_digest_outdated() {
     # Validate sanity.
     (( # == 0 )) || die 'expected no arguments'
 
+    # ------------------< FUNCTIONS                          >------------------
+    # Define document_function() before document_alias(), which documents itself
+    # with the former function.
+    set_function_documentation document_function '
+void document_function(string documentation)
+
+Document the function prefixing the passed string with such string. Call this
+function *BEFORE* compiling Zeshy''s user digest file.
+'
+    function document_function() {
+        # Validate passed arguments.
+        (( # == 1 )) || die 'expected one documentation string'
+        local documentation="${1}"
+
+        # If such documentation is prefixed by a function prototype, match the
+        # relevant function name from such prototype. zsh permissively allows
+        # function name declarations to be quoted and hence contain arbitrary
+        # characters, necessitating a more lenient glob expression than liked.
+        # Dismantled, this is:
+        #
+        # * "(#b)", capturing match groups into global list ${match}.
+        # * "[[:space:]]#", matching optional whitespace.
+        # * "[^[:space:]]##", matching the function return type.
+        # * "[[:space:]]##", matching mandatory whitespace.
+        # * "([^'(']##)", matching the function name into ${match[1]}.
+        # * '(', matching the beginning of the function argument list.
+        if [[ "${documentation}" ==\
+            (#b)[[:space:]]#[^[:space:]]##[[:space:]]##([^'(']##)'('* ]]
+        then ZESHY_FUNCTION_NAME_TO_DOCUMENTATION[${match[1]}]="${documentation}"
+#           print "function name: ${match[1]}"
+        # Else throw an exception with a portion of such documentation.
+        else die "help string \"${documentation[1,40]}...\" not prefixed by a function prototype"
+        fi
+    }
+
     # ------------------< ALIASES                            >------------------
+    document_function '
+void document_alias(string documentation)
+
+Document the alias prefixing the passed string with such string. Call this
+function *BEFORE* compiling Zeshy''s user digest file.
+'
+    function document_alias() {
+        # Validate passed arguments.
+        (( # == 1 )) || die 'expected one documentation string'
+        local documentation="${1}"
+
+        # If such documentation is prefixed by an alias prototype, match the
+        # relevant alias name from such prototype. While zsh permissively allows
+        # alias name declarations to be quoted and hence contain arbitrary
+        # characters as with functions, such aliases are not runnable: e.g.,
+        #
+        #   >>> alias "o w s"="print 'revolt is dead; long live revolt'"
+        #   >>> o\ w\ s
+        #   zsh: command not found: o w s
+        #
+        # For simplicity, use a similar glob expression as document_function().
+        if [[ "${documentation}" ==\
+            (#b)[[:space:]]#[^[:space:]]##[[:space:]]##([^'<']##)'<'* ]]
+        then ZESHY_ALIAS_NAME_TO_DOCUMENTATION[${match[1]}]="${documentation}"
+#           print "function name: ${match[1]}"
+        # Else throw an exception with a portion of such documentation.
+        else die "help string \"${documentation[1,40]}...\" not prefixed by an alias prototype"
+        fi
+    }
+
+    # ------------------< GLOBALS                            >------------------
     set_global_documentation ZESHY_GLOBAL_TYPE_TO_DECLARATOR '
 map ZESHY_GLOBAL_TYPE_TO_DECLARATOR
 
@@ -309,11 +364,6 @@ Map variable type to the command prefix exporting globals of such type.
         map 'typeset -Agx'
     )
 
-    #FIXME: We may need to explicitly unset ${documentation_dg} *ONCE* after
-    #sourcing all configuration files. We'll know whether we need to do so based on
-    #whether or not the current environment has become polluted with such variable
-    #after entering a new Zeshy shell.
-
     set_alias_documentation document_global '
 void document_global(string documentation)
 
@@ -325,7 +375,7 @@ compiling Zeshy''s user digest file.
     alias document_global='
     {
         # Localize the passed herestring.
-        local documentation_dg="$(< /dev/stdin)"
+        local documentation__dg="$(< /dev/stdin)"
 
         # If such documentation is prefixed by a function prototype, match the
         # relevant function name from such prototype. zsh permissively allows
@@ -340,9 +390,9 @@ compiling Zeshy''s user digest file.
         # * "([[:IDENT:]]##)", matching the variable name into ${match[2]}.
         #
         # Else throw an exception with a portion of such documentation.
-        [[ "${documentation_dg}" ==\
+        [[ "${documentation__dg}" ==\
             (#b)[[:space:]]#([^[:space:]]##)[[:space:]]##([[:IDENT:]]##)* ]] ||
-            die "help string \"${documentation_dg[1,40]}...\" not prefixed by a variable declaration"
+            die "help string \"${documentation__dg[1,40]}...\" not prefixed by a variable declaration"
 
         # If the matched variable type is not a Zeshy-specific type, throw an
         # exception. See is_map_key() for implementation details.
@@ -356,43 +406,9 @@ compiling Zeshy''s user digest file.
         ${(z)ZESHY_GLOBAL_TYPE_TO_DECLARATOR[${match[1]}]} "${match[2]}"
 
         # Document such global.
-        ZESHY_GLOBAL_NAME_TO_DOCUMENTATION[${match[2]}]="${documentation_dg}"
+        ZESHY_GLOBAL_NAME_TO_DOCUMENTATION[${match[2]}]="${documentation__dg}"
     #   print "function name: ${match[1]}"
     } <<<'
-
-    # ------------------< FUNCTIONS                          >------------------
-    set_function_documentation document_function '
-void document_function(string documentation)
-
-Parse the passed documentation, associating the function name prefixing such
-documentation with such documentation. Call this function only before compiling
-Zeshy''s user digest file.
-'
-    function document_function() {
-        # Validate passed arguments.
-        (( # == 1 )) || die 'expected one documentation string'
-        local documentation="${1}"
-
-        # If such documentation is prefixed by a valid function prototype, match the
-        # relevant function name from such prototype. zsh permissively allows
-        # function name declarations to be quoted and hence contain arbitrary
-        # characters, necessitating a more lenient glob expression than liked here.
-        # Dismantled, this is:
-        #
-        # * "(#b)", capturing match groups into global list ${match}.
-        # * "[[:space:]]#", matching optional whitespace.
-        # * "[^[:space:]]##", matching the function return type.
-        # * "[[:space:]]##", matching mandatory whitespace.
-        # * "([^\(]##)", matching and capturing the function name into ${match[1]}.
-        # * '(', matching the beginning of the function argument list.
-        if [[ "${documentation}" ==\
-            (#b)[[:space:]]#[^[:space:]]##[[:space:]]##([^\(]##)'('* ]]
-        then ZESHY_FUNCTION_NAME_TO_DOCUMENTATION[${match[1]}]="${documentation}"
-#           print "function name: ${match[1]}"
-        # Else throw an exception with a portion of such documentation.
-        else die "help string \"${documentation[1,40]}...\" not prefixed by a function prototype"
-        fi
-    }
 }
 
 # ....................{ SETUP ~ config                     }....................
@@ -431,6 +447,30 @@ function setup_zeshy_configuration() {
 setup_zeshy
 
 # --------------------( WASTELANDS                         )--------------------
+    #FUXME: We may need to explicitly unset ${documentation__dg} *ONCE* after
+    #sourcing all configuration files. We'll know whether we need to do so based on
+    #whether or not the current environment has become polluted with such variable
+    #after entering a new Zeshy shell.
+
+#FUXME: Should probably be pushed into "main". Ideally, this could allow us to
+#obsolete the lower-level set_*_documentation() family of functions in favor of
+#the higher-level document_*() family of functions. It will increase the size of
+#"main", but probably not by quite as much as thought -- after all, we'd also be
+#removing a sizable block of existing functionality: set_*_documentation().
+#Naturally, this requires moving document_*() and all conditional logic defining
+#such functions from here to "main".
+#FUXME: Since we'd like to declare such functionality as "early" as possible, we
+#should probably declare "set -e" at the top of "main" and then inject such code
+#immediately after "setopt" calls (i.e., before defining die(), say(), and
+#friends). This implies we should undo "set -e" immediately prior to defining
+#die(). (I recall we do something similar; just double-check us up.)
+#FUXME: Actually, the current method isn't terribly inappropriate. Steady as she
+#goes, folks!
+
+        # Nonetheless, reuse the same glob expression for simplicity.
+        # Hence, this glob expression matches more strictly than the function
+        # glob expression above. Dismantled, this is:
+
 #FIXME: Hopefully superfluous, after implementing document_global() properly.
 #Excise after excising from all config files.
     # If Zeshy's user digest file is up-to-date, define placeholders for
