Fixed a major digest recompilation regression.
Split "os/time/time" into "string", "integer", and "calendar" components.
Significantly improved time-related nomenclature. Split
"io/output/output" into "output" and "say/say" components. Nominally
prepared say_heading() for caller name caching.

diff --git a/src/setup b/src/setup
--- a/src/setup
+++ b/src/setup
@@ -47,21 +47,26 @@ currently supports no boolean type, Zeshy emulates such type with strings.
 export ZESHY_BOOLEAN_TRUE=true ZESHY_BOOLEAN_FALSE=
 
 # ....................{ GLOBALS ~ digest                   }....................
+# Explicitly define such globals to default values. When not doing so, such
+# globals erroneously inherit their default values from the parent shell,
+# typically resulting in Zeshy recompiling its user digest file on each startup.
+
 set_global_documentation ZESHY_DOT_DIGEST_FILE_IS_OUTDATED '
 boolean ZESHY_DOT_DIGEST_FILE_IS_OUTDATED
 
-If non-empty, Zeshy''s user digest file was outdated at shell startup. See
+If true, Zeshy''s user digest file was outdated at Zeshy startup. See
 is_zeshy_digest_outdated() for further details.
 '
-export ZESHY_DOT_DIGEST_FILE_IS_OUTDATED
+export ZESHY_DOT_DIGEST_FILE_IS_OUTDATED=${ZESHY_BOOLEAN_FALSE}
 
-set_global_documentation ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME '
+set_global_documentation\
+    ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME '
 integer ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME
 
-Modification time of the newest path Zeshy''s user digest file depends on, non-
-zero only if such file was outdated at shell startup.
+If Zeshy''s user digest file was outdated at Zeshy startup, the modification
+time of the newest path such file depends on; else 0.
 '
-export -i ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME
+export -i ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME=0
 
 # ....................{ ALIASES                            }....................
 # Zeshy's user configuration files only export globals. While such files can
@@ -80,17 +85,22 @@ alias list_set_global_export='export -Ua'
 alias map_global_export='typeset -Agx'
 
 # ....................{ TESTERS                            }....................
+#FIXME: Documentation outdated.
 set_function_documentation is_zeshy_digest_outdated '
 boolean is_zeshy_digest_outdated(void)
 
-Return true if Zeshy''s digest file is outdated, thus requiring recompilation.
-Return true specifically when such file does not exist or does but is older
-than the newest of:
+Return true if Zeshy''s user digest file is outdated and requires recompilation.
+This is the case when such file either does not exist or does but is older than
+the newest of:
 
 * The main user-specific Zeshy configuration file. This file contains theme
   settings, which when edited require recompiling theme autoloads.
 * The main system-wide command directories (e.g., "/bin", "/usr/bin").
   Installing or uninstalling commands requires recompiling command autoloads.
+
+For convenience, set global
+${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME} to the modification
+time of the newest path such digest depends upon.
 '
 function is_zeshy_digest_outdated() {
     # Validate sanity.
@@ -99,19 +109,24 @@ function is_zeshy_digest_outdated() {
     #FIXME: Add support for Zeshy upgrading: namely, if upgrading Zeshy,
     #immediately return 0 (i.e., true).
 
-    # Unless:
-    #
-    # * Zeshy's user digest file exists under such directory and
-    # * Zeshy's user configuration directory exists under such directory and is
-    #   non-empty (i.e., contains at least one configuration file),
-    #
-    # Return such digest to be outdated.
-    # * Loading Zeshy's user directory and
-    [[ -f "${ZESHY_DOT_DIGEST_FILE}" && -d "${ZESHY_DOT_CONFIG_DIR}" ]] && {
+    # Unless loading Zeshy's user directory *AND* Zeshy's user digest file and
+    # configuration directory both exist *AND* the latter contains at least one
+    # directory or file (i.e., is non-empty), return such digest to be outdated.
+    [[ -n "${ZESHY_DOT_DIR}" &&\
+       -f "${ZESHY_DOT_DIGEST_FILE}" &&\
+       -d "${ZESHY_DOT_CONFIG_DIR}" ]] && {
         local -a zeshy_dot_config_dir_if_nonempty
         zeshy_dot_config_dir_if_nonempty=( "${ZESHY_DOT_CONFIG_DIR}"(/F) )
-        (( #zeshy_dot_config_dir_if_nonempty ))
-    } || return 0
+        (( ${#zeshy_dot_config_dir_if_nonempty} ))
+    } || {
+        # Before returning, set global
+        # ${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME} as
+        # required by this function's definition to the current time. This
+        # guarantees the modification time for Zeshy's user digest file will be
+        # coerced to the current time.
+        ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME="$(date +'%s')"
+        return 0
+    }
 
     # List of modification times of paths on which Zeshy's digest depends,
     # initialized to contain .
@@ -234,7 +249,8 @@ function setup_zeshy() {
     [[ -n "${ZESHY_DOT_DIR}" ]] || return 0
 
     # Record whether Zeshy's user digest file is outdated.
-    is_zeshy_digest_outdated && ZESHY_DOT_DIGEST_FILE_IS_OUTDATED=true
+    is_zeshy_digest_outdated &&
+        ZESHY_DOT_DIGEST_FILE_IS_OUTDATED=${ZESHY_BOOLEAN_TRUE}
 
     # Call the corresponding setup function.
     if [[ -z "${ZESHY_DOT_DIGEST_FILE_IS_OUTDATED}" ]]
@@ -279,6 +295,14 @@ functions required only for compiling an outdated digest file.
 function setup_zeshy_digest_outdated() {
     # Validate sanity.
     (( # == 0 )) || die 'expected no arguments'
+
+    # If debugging Zeshy, print modification times for Zeshy's user digest file
+    # and the newest path such file depends upon.
+    [[ -n "${ZESHY_IS_DEBUGGING-}" ]] && {
+        [[ -f "${ZESHY_DOT_DIGEST_FILE}" ]] &&
+            say "digest mtime:                   $(zstat +mtime "${ZESHY_DOT_DIGEST_FILE}")"
+            say "digest newest dependency mtime: ${ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME}"
+    }
 
     # ------------------< FUNCTIONS                          >------------------
     # Define document_function() before document_alias(), which documents itself
@@ -368,7 +392,8 @@ map ZESHY_GLOBAL_TYPE_TO_DECLARATOR
 
 Map variable type to the command prefix exporting globals of such type.
 '
-    typeset -Agx ZESHY_GLOBAL_TYPE_TO_DECLARATOR; ZESHY_GLOBAL_TYPE_TO_DECLARATOR=(
+    typeset -Agx ZESHY_GLOBAL_TYPE_TO_DECLARATOR
+    ZESHY_GLOBAL_TYPE_TO_DECLARATOR=(
         # Scalar types.
         string   'export'
         boolean  'export'
@@ -477,6 +502,17 @@ function setup_zeshy_configuration() {
 setup_zeshy
 
 # --------------------( WASTELANDS                         )--------------------
+#       say 'digest outdated!'
+#   print "ZESHY_DOT_DIGEST_FILE_IS_OUTDATED: ${ZESHY_DOT_DIGEST_FILE_IS_OUTDATED}"
+# non-zero only if such file was outdated at shell startup.
+    #FUXME: Not quite right. We need to set
+    #ZESHY_DOT_DIGEST_FILE_DEPENDENCY_NEWEST_MODIFICATION_TIME to the current
+    #time. Now how do we do that, again...?
+#* The main user-specific Zeshy configuration file. This file contains theme
+#  settings, which when edited require recompiling theme autoloads.
+#* The main system-wide command directories (e.g., "/bin", "/usr/bin").
+#  Installing or uninstalling commands requires recompiling command autoloads.
+
 #           if [[ "${function_name}" == *'[OR]'* ]]; then
 #FUXME: Shift is_zeshy_digest_outdated() here and cache the result into a global
 #variable, as subsequent components will also need reference such result. Shift
